#ifndef _HTML_H_007_H_
#define _HTML_H_007_H_
static const char h_007[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
 "<head>\n"
  "<meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'/>\n"
  "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
  "<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
  "<style type='text/css'>\n"
  	".inquery{margin:5px auto;width:780px;text-align:right;padding-right:10px;}\n"
  	".txt{margin:0 10px;width:120px;text-align:center;}\n"
  	".PagerView{font-size:12px;font-family:tahoma,arial;color:#333;text-align:center;padding:8px;line-height:100%;}\n"
  	".PagerView span{color:#999;margin:0 1px;padding:3px 6px;border:1px solid #ccc;}\n"
  	".PagerView span.on{color:#fff;font-weight:bold;border:1px solid #666;background:#39f;}\n"
  	".PagerView a{color:#00f;text-decoration:none;}\n"
  	".PagerView a span{color:#33f;border:1px solid #66c;}\n"
  	".pager{width:780px;margin:0 auto;}\n"
        ".time{width:80px;}\n"
 "</style>\n"
    "<script src='j_002.js' type='text/javascript'></script>\n"
    "<script type=\"text/javascript\" src=\"jquery.min.js\"></script>\n"
    "<script type=\"text/javascript\" src=\"j_encoding-indexes.js\"></script>\n"
    "<script type=\"text/javascript\" src=\"j_encoding.js\"></script>\n"
    "<script type=\"text/javascript\" src=\"j_filesaver.js\"></script>\n"
 "</head>\n"
 "<body onload='Init()'>\n"
 "<script type='text/javascript'>\n"
 	"show_T('N01');\n"
 	"show_sT('N02');\n"
 "</script>\n"
 "<div class='inquery'>\n"
 	"<span id='N03'></span>\n"
 	"<select class='time' id='ID_0x0101' onchange='CheckDay(\"ID_0x0101\",\"ID_0x0102\",\"ID_0x0103\")'>\n"
 		"<script type='text/javascript'>SelectYear();</script>\n"
 	"</select>&nbsp;- \n"
 	"<select class='time' id='ID_0x0102' onchange='CheckDay(\"ID_0x0101\",\"ID_0x0102\",\"ID_0x0103\");'>\n"
 		"<script type='text/javascript'>SelectMonth();</script>\n"
 	"</select>&nbsp;- \n"
 	"<select class='time' id='ID_0x0103' value='1' onchange='select_nbps()'></select>&nbsp;&nbsp;&nbsp;\n"
 	"<button class='btn' onclick='doSubmit()'><span id='N04'></span></button>\n"
 	"<span id='SpanHide' style='font-size:20px;display:none;'><b>&nbsp;/&nbsp;</b></span>\n"
 	"<button class='btn' disabled='true' id='Exp' style='display:none;' onclick='Exp()'><span id='N05'></span></button>\n"
 "</div>\n"
 "<div class='line_long'></div>\n"
 "<div class='blank'></div>\n"
 "<script type='text/javascript'>\n"
 "show_sT('N06');\n"
 "</script>\n"
  "<!-- 需要将h_011.html改为h_011.IExx -->\n"
  "<iframe id='Run_Record' src='h_011.html' frameBorder='0' width='90%' scrolling='auto' height='320'></iframe>\n"
 "<br/>\n"
 "<img id='waiting' style='margin:0 auto;z-index:20000;position:relative;top:-168px;visibility:hidden;' src='i_002.gif'/>\n"
 "<br/>\n"
 "<div id='pager'></div>\n"
 "<table width='90%' border='0'><tr><td width='100%' class='even tip'><span id='tip'>&nbsp;</span></td></tr></table>\n"
 "<div class='btm_blank'></div>\n"
"</body>\n"
 "<script type='text/javascript'>\n"
 	"window.history.forward(1);\n"
 	"var pager;\n"
 	"var page_num=1;\n"
  	"var language=1;\n"
        "var busy = false;\n"
  	"var Json;\n"
  	"var lang=\n"
  	"{\n"
  		"N01:['运行记录','Running Records'],\n"
  		"N02:['查询&amp;导出','Inquery&amp;Exp'],\n"
  		"N03:['查询日期：','Inquery Date:'],\n"
  		"N04:['查&nbsp;&nbsp;询','Inquery'],\n"
  		"N05:['导&nbsp;&nbsp;出','Exp'],\n"
  		"N06:['详细记录','Detailed Records'],\n"
  		"N07:['一共','Total '],\n"
  		"N08:['页，共',' pages, '],\n"
  		"N09:['页，共',' page, '],\n"
  		"N10:['条记录',' records'],\n"
  		"N11:['条记录',' record'],\n"
  		"N12:['无记录。',' No record.']\n"
  	"};\n"
"\n"
 	"function Exp()\n"
 	"{\n"
             // IE <10 is explicitly unsupported
            "if (typeof navigator !== \"undefined\" &&\n"
                "/MSIE [1-9]\\./.test(navigator.userAgent)) {\n"
                "return;\n"
            "}\n"
            "if(busy) return;\n"
             //$.ajax({
            "jQuery.ajax({\n"
                "url:'Running_Records('+OBJ('ID_0x0101').value+'_'+((parseInt(OBJ('ID_0x0102').value)<10)?('0'+String(OBJ('ID_0x0102').value)):String(OBJ('ID_0x0102').value))+'_'+((parseInt(OBJ('ID_0x0103').value)<10)?('0'+String(OBJ('ID_0x0103').value)):String(OBJ('ID_0x0103').value))+').csv',\n"
                "type:\"get\",\n"
                "contentType:\"application/text;charset=gb2312\",\n"
                "dataType:\"text\",\n"
                "async: false,\n"
                "beforeSend:function()\n"
                "{\n"
                    "OBJ('Exp').disabled = true;\n"
                    "OBJ('waiting').style.visibility='visible';\n"
                    "busy=true;\n"
                "},\n"
                "success:function(data)\n"
                "{\n"
                    "var myData = data;\n"
                    "textEncoder = new CustomTextEncoder('gb2312', {NONSTANDARD_allowLegacyEncoding: true}),\n"
                    "fileName = 'Running_Records('+OBJ('ID_0x0101').value+'_'+((parseInt(OBJ('ID_0x0102').value)<10)?('0'+String(OBJ('ID_0x0102').value)):String(OBJ('ID_0x0102').value))+'_'+((parseInt(OBJ('ID_0x0103').value)<10)?('0'+String(OBJ('ID_0x0103').value)):String(OBJ('ID_0x0103').value))+').csv';\n"
                    "var csvContentEncoded = textEncoder.encode([myData]);\n"
                    "var blob = new Blob([csvContentEncoded], {type: 'text/csv;charset=gb2312;'});\n"
                    "saveAs(blob, fileName);\n"
                    "OBJ('Exp').disabled = false;\n"
                    "OBJ('waiting').style.visibility='hidden';\n"
                    "busy=false;\n"
                "}\n"
            "});\n"
 	"}\n"
 	"function Init()\n"
 	"{\n"
            "FromWhichDevice();\n"
            "if(FromMobileDevice)\n"
 		"{\n"
 			"OBJ('SpanHide').style.display='none';\n"
 			"OBJ('Exp').style.display='none';\n"
 		"}\n"
 		"var myDate=new Date();\n"
 	 	//"Json={ID_0x0301:85};\n"
 	 	"var URL='s_007.html?0x0000&time='+Math.random();\n"
 	 	"var xmlhttp;\n"
 	 	"if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 	 	"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 	 	"xmlhttp.onreadystatechange=function()\n"
 	 	"{\n"
 	 		"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 	 		"{\n"
 	 			"eval('Json='+xmlhttp.responseText);\n"
 	 			"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
 	 			"lang_init(6);\n"
                     // IE <10 is explicitly unsupported
                    "if (typeof navigator !== \"undefined\" &&\n"
                        "/MSIE [1-9]\\./.test(navigator.userAgent)) {\n"
                    "}else{\n"
                     "OBJ('SpanHide').style.display='inline';\n"
                        "OBJ('Exp').style.display='inline';\n"
                    "}\n"
 	 			"OBJ('ID_0x0101').value=myDate.getFullYear();\n"
 	 			"OBJ('ID_0x0102').value=myDate.getMonth()+1;\n"
 	 			"CheckDay('ID_0x0101','ID_0x0102','ID_0x0103');\n"
 	 			"document.getElementById('Run_Record').contentWindow.Init(language);\n"
 	 			"doSubmit();\n"
 	 			"show_tip('&nbsp;');\n"
 	 		"}\n"
  		"};\n"
 	 	"xmlhttp.open('GET',URL,true);\n"
 	 	"xmlhttp.send();\n"
  	"}\n"
 	 "function doSubmit()\n"
 	 "{\n"
 	 		//测试
  			//temp={'R':[
  			//{'C1':1,'C2':'2014.08.13/14:32:00','C3':1,'C4':'100.0kW','C5':1,'C6':1,'C7':1,'C8':2,'C9':1,'C10':'400.1V','C11':'50.0Hz',
  			//  'C12':'30.0kW',
  			//  'C13':1,'C14':0,'C15':1,'C16':0,
  			//  'C17':0,'C18':1,'C19':'10.0kW','C20':0,'C21':'48.0kW','C22':'380.5V','C23':'49.9Hz',
  			//  'C24':'60.1kW','C25':'700.3V','C26':'49.0kW','C27':'390.3V','C28':'650.9V','C29':'50.1%','C30':'50.1%','C31':'50.1%'
  			//},
  			//{'end':0}]};Records=12;
 	 	"\n"
 	 	"var URL='r_007.html?'\n"
 	 	"+'Y='+OBJ('ID_0x0101').value\n"
 	 	"+'&M='+OBJ('ID_0x0102').value\n"
 	 	"+'&D='+OBJ('ID_0x0103').value\n"
 	 	"+'&P='+page_num\n"
 	 	"+'&time='+Math.random();\n"
 	 	"var xmlhttp;\n"
 	 	"if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 	 	"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 	 	"xmlhttp.onreadystatechange=function()\n"
 	 	"{\n"
 	 		"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 	 		"{\n"
 	 			"show_tip('&nbsp;');\n"
 	 			"eval('temp='+xmlhttp.responseText);\n"
 	 			"document.getElementById('Run_Record').contentWindow.Show_Records(temp,language);\n"
 	 			"if(Records<=10)\n"
 	 			"{\n"
 	 				"if(Records==0)\n"
 	 				"{\n"
 	 					"show_tip(lang.N12[language]);\n"
 	 					"OBJ('waiting').style.visibility='hidden';\n"
 	 					"OBJ('pager').style.display='none';\n"
 	 					"OBJ('Exp').disabled=true;\n"
 	 					"return false;\n"
 	 				"}\n"
 	 				"else if(Records==1)\n"
 	 				"{\n"
 	 					"OBJ('pager').style.display='block';\n"
 	 					"pager=new PagerView('pager',lang.N07[language],lang.N09[language],lang.N11[language]);\n"
 	 					"OBJ('Exp').disabled=false;\n"
 	 				"}\n"
 	 				"else\n"
 	 				"{\n"
 	 					"OBJ('pager').style.display='block';\n"
 	 					"pager=new PagerView('pager',lang.N07[language],lang.N09[language],lang.N10[language]);\n"
 	 					"OBJ('Exp').disabled=false;\n"
 	 				"}\n"
 	 			"}\n"
 	 			"else\n"
 	 			"{\n"
 	 				"OBJ('pager').style.display='block';\n"
 	 				"pager=new PagerView('pager',lang.N07[language],lang.N08[language],lang.N10[language]);\n"
 	 				"OBJ('Exp').disabled=false;\n"
 	 			"}\n"
 	 			"pager.itemCount=Records;\n"
 	 			"pager.size=10;\n"
 	 			"pager.index=1;\n"
 	 			"pager.onclick=function(index)\n"
 	 			"{\n"
 	 					//测试
 			 			//temp={'R':[
 			 			//{'C1':1,'C2':'2014.08.13/14:32:00','C3':1,'C4':'100.0kW','C5':1,'C6':1,'C7':1,'C8':2,'C9':1,'C10':'400.1V','C11':'50.0Hz',
 			 			//  'C12':'30.0kW',
 			 			//  'C13':1,'C14':0,'C15':1,'C16':0,
 			 			//  'C17':0,'C18':1,'C19':'10.0kW','C20':0,'C21':'48.0kW','C22':'380.5V','C23':'49.9Hz',
 			 			//  'C24':'60.1kW','C25':'700.3V','C26':'49.0kW','C27':'390.3V','C28':'650.9V','C29':'650.9V','C30':'50.1%','C31':'50.1%'
 			 			//},
 			 			//{'end':0}]};Records=12;
"\n"
 	 				"var URL='r_007.html?'\n"
 	 				"+'Y='+OBJ('ID_0x0101').value\n"
 	 				"+'&M='+OBJ('ID_0x0102').value\n"
 	 				"+'&D='+OBJ('ID_0x0103').value\n"
 	 				"+'&P='+index\n"
 	 				"+'&time='+Math.random();\n"
 	 				"var xmlhttp;\n"
 	 				"if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 	 				"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 	 				"xmlhttp.onreadystatechange=function()\n"
 	 				"{\n"
 	 					"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 	 					"{\n"
 	 						"show_tip('&nbsp;');\n"
 	 						"eval('temp='+xmlhttp.responseText);\n"
 	 						"document.getElementById('Run_Record').contentWindow.Show_Records(temp,language);\n"
 	 						"OBJ('waiting').style.visibility='hidden';\n"
 	 					"}\n"
 	 				"};\n"
 	 				"xmlhttp.open('GET',URL,true);\n"
 	 				"xmlhttp.send();\n"
 	 				"OBJ('waiting').style.visibility='visible';\n"
 	 			"};\n"
 	 			"pager.render();\n"
 	 			"OBJ('waiting').style.visibility='hidden';\n"
 	 		"}\n"
 	 	"};\n"
 	 	"xmlhttp.open('GET',URL,true);\n"
 	 	"xmlhttp.send();\n"
 	 	"OBJ('waiting').style.visibility='visible';\n"
 	 "}\n"
 	 "function select_nbps()\n"
 	 "{\n"
 	 	"if(OBJ('tip').innerHTML==lang.N12[language])show_nbsp();\n"
 	 "}\n"
 "</script>\n"
};
#endif
