#ifndef _HTML_H_000_H_
#define _HTML_H_000_H_
static const char h_000[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<title></title>\n"
        "<style type='text/css'>\n"
            "body{margin:0;padding:0;text-align:center;font-size:14px;font-family:'微软雅黑',Verdana,'宋体',sans-serif;background-color:#F7F7F7;}\n"
            ".title{margin:10px auto;width:400px;text-align:left;overflow:hidden;}\n"
            ".subtitle{width:400px;text-align:left;}\n"
            ".subcolor{background-color:#84C1FF;}\n"
            ".cn{width:80px;float:right;}\n"
            ".en{width:80px;float:right;padding-right:26px;}\n"
            ".r1{margin:0 5px;height:1px;overflow:hidden;}\n"
            ".r2{margin:0 3px;height:1px;overflow:hidden;}\n"
            ".r3{margin:0 2px;height:1px;overflow:hidden;}\n"
            ".r4{margin:0 1px;height:2px;overflow:hidden;}\n"
            ".content{height:41px;padding-left:20px;}\n"
            ".subcontent{padding:0;height:210px;font-size:18px;}\n"
            ".line_long{height:2px;overflow:hidden;margin:0 10px;background-color:#050;}\n"
            ".login{height:240px;width:100%;position:absolute;top:50%;left:50%;margin:-115px 0 0 -50%;background-color:#E8E8E8;}\n"
            ".N01{width:150px;float:left;padding-right:20px;text-align:right;height:22px;line-height:22px;}\n"
            ".N02{width:200px;float:left;height:22px;height:22px;margin-top: 2px;}\n"
            "#ID_0x0282{width:130px;text-align:left;float:left;}\n"
            "#ID_0x0283{width:124px;text-align:left;float:left;}\n"
            ".main{height:30px;font-size:16px;}\n"
            ".div_btn{text-align:left;padding-left:250px;padding-top:10px;}\n"
            ".btn{width:75px;height:24px;}\n"
            ".img{width:173px;height:41px;background-image:url(i_000.png) !important;background-repeat:no-repeat;_filter:progid: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='i_000.png');_background-image:none;}\n"
            ".tip{width:350px;height:30px;margin:0 auto;text-align:left;color:#ff0000;font-weight:bold;font-size:14px;padding-left:20px;}\n"
        "</style>\n"
        "<script type=\"text/javascript\" src=\"jquery.min.js\"></script>\n"
        "<script type='text/javascript'>\n"
            "window.history.forward(1);\n"
            "var language=0;\n"
            "var Json;\n"
            "var timer=-1;\n"
            "var result=4;\n"
            "var OBJ=function(o){return document.getElementById(o);};\n"
            "var lang=\n"
            "{\n"
                "N01:['用户名:','Username:'],\n"
                "N02:['密码:','Password:'],\n"
                "N03:['登&nbsp;&nbsp;录','Login'],\n"
                "N04:['密码错误，请重新输入！','Wrong password, please re-enter the password!'],\n"
                "N05:['请输入密码','Please key in your password!'],\n"
                "N06:['已经有用户登录，请稍后再试！','User has logged in,please try again later!'],\n"
                "N07:['登录用户满，请稍后再试！','logged in Users is Full,please try again later!'],\n"
                "N08:['登录超时，请稍后再试！','logged in timeout,please try again later!'],\n"
                "N09:['网络繁忙, 请稍后再试！','Network busy,please try again later!'],\n"
                "N10:['操作员','Operator'],\n"
                "N11:['管理员','Administrator'],\n"
                "N12:['维护员','Maintainer']\n"
            "};\n"
            "var doKeyCheck=function(evt)\n"
            "{\n"
                "evt=window.event||evt;\n"
                "if(evt.keyCode==13)doCheck();\n"
            "};\n"
            "window.document.onkeyup=doKeyCheck;\n"
            "function Init()\n"
            "{\n"
                "$.ajax({\n"
                    "url:\"s_000.html\",\n"
                    "type:\"get\",\n"
                    "contentType:\"application/json;charset=utf-8\",\n"
                    "data:'time='+Math.random(),\n"
                    "dataType:\"json\",\n"
                    "async: true,\n"
                    "success:function(data){\n"
                        "Json = data;\n"
         			"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
         			"OBJ('N01').innerHTML=lang.N01[language];\n"
         			"OBJ('N02').innerHTML=lang.N02[language];\n"
         			"OBJ('N03').innerHTML=lang.N03[language];\n"
                        "OBJ('ID_0x0282').options.add(new Option(lang.N10[language],0));\n"
                        "OBJ('ID_0x0282').options.add(new Option(lang.N11[language],1));\n"
                        "OBJ('ID_0x0282').options.add(new Option(lang.N12[language],2));\n"
         			"document.title=Json.ID_0x0202;\n"
                        "document.getElementById('ID_0x0283').focus();\n"
                    "}\n"
                "});\n"
            "}\n"
            "function doCheck()\n"
            "{\n"
                "if(OBJ('ID_0x0283').value=='')\n"
                "{\n"
                    "show_tip(lang.N05[language]);\n"
                    "OBJ('ID_0x0283').focus();\n"
                "}\n"
                "else\n"
                "{\n"
                    "doSubmit(); \n"
                "} \n"
            "}\n"
            "function doSubmit()\n"
            "{\n"
                 //使用地址附带参数的方法上传参数.
                "var URL='LA.html?'+'0x0282='+OBJ('ID_0x0282').value+'&0x0283='+OBJ('ID_0x0283').value +'&time='+Math.random();\n"
                "$.ajax({\n"
                    "url:URL,\n"
                    "type:\"get\",\n"
                    "contentType:\"application/json;charset=utf-8\",\n"
                     //也可以通过参数传递的方式上传参数.
                     //url:\"LA.html\"
                     //data:'0x0282='+OBJ('ID_0x0282').value+'&0x0283='+OBJ('ID_0x0283').value +'&time='+Math.random(),
                     //数据返回的方式 text html json 
                    "dataType:\"text\",\n"
                    "async: true,\n"
		    "timeout : 2000,\n"
                    "success:function(data)\n"
                    "{\n"
                        "if(data=='1'){\n"
                            "replace_location('Index.html');\n"
                            "return;\n"
                        "}else if(data=='3'){\n"
                            "replace_location('Config.html');\n"
                            "return;                            \n"
                        "}else if(data=='5'){\n"
                            "replace_location('Debug.html');\n"
                            "return;                            \n"
                        "}else if(data=='0'){\n"
                            "show_tip(lang.N04[language]);\n"
                        "}else if(data=='2'){\n"
                            "show_tip(lang.N06[language]);\n"
                        "}else if(data=='4'){\n"
                            "show_tip(lang.N07[language]);\n"
                        "}\n"
                        "$('ID_0x0283').value='';\n"
                        "$('ID_0x0283').focus();\n"
                    "},\n"
                    "error:function (textStatus) \n"
                    "{\n"
                        //网络繁忙, 加载错误！
                       "show_tip(lang.N09[language]);\n"
                    "},\n"
                    "complete:function(XMLHttpRequest,status)\n"
                    "{\n"
                         //超时
                "if(status=='timeout'){\n"
                "show_tip(lang.N08[language]);\n"
                "}\n"
                    "}\n"
                "});  \n"
            "}\n"
            "function replace_location(url)\n"
            "{\n"
                "var isIe=(document.all)?true:false;\n"
                "if(isIe)\n"
                "{\n"
                    "var linka=document.createElement('a');\n"
                    "linka.href=url;\n"
                    "document.body.appendChild(linka);\n"
                    "linka.click();\n"
                "}\n"
                "else window.location=url;\n"
            "}\n"
            "function return_to_blank()\n"
            "{\n"
                "OBJ('tip').innerHTML='&nbsp;';\n"
            "}\n"
            "function show_tip(obj)\n"
            "{\n"
                "if(timer!=-1){clearInterval(timer);timer=-1;}\n"
                "OBJ('tip').innerHTML='&nbsp;';\n"
                "OBJ('tip').innerHTML=obj;\n"
                "timer=setInterval('return_to_blank()',3000);\n"
            "}\n"
            "function lang_color_GB()\n"
            "{\n"
                "if(language==0)\n"
                "{\n"
                    "OBJ('CHN').className='text B_C';\n"
                    "OBJ('EN').className='text G_C';\n"
                "}\n"
                "else\n"
                "{\n"
                    "OBJ('CHN').className='text G_C';\n"
                    "OBJ('EN').className='text B_C';\n"
                "}\n"
            "}\n"
            "function lang_color_R(obj)\n"
            "{\n"
                "obj.className='text R_C';\n"
            "}\n"
            "function do_Submit(Lang)\n"
            "{\n"
                "lang_color_GB();\n"
                "var URL='a_012.html?0x0301='+Lang+'&time='+Math.random();\n"
                "var xmlhttp;\n"
                "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                "xmlhttp.onreadystatechange=function()\n"
                "{\n"
                    "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                    "{              \n"
                        "replace_location('Login.html');\n"
                        "return;\n"
                    "}\n"
                "};\n"
                "xmlhttp.open('GET',URL,true);\n"
                "xmlhttp.send();\n"
            "}\n"
        "</script>\n"
    "</head>\n"
    "<body onload='Init()'>\n"
        "<div>\n"
            "<div class='head'>\n"
                "<div class='en' onclick='do_Submit(\"170\")'>\n"
                    "<a class='a' href='#'><img class='flag' src='i_004.png'/><span id='EN' class='text' onmousemove='lang_color_R(this)' onmouseout='lang_color_GB()'>English</span></a>\n"
                "</div>\n"
                "<div class='cn' onclick='do_Submit(\"85\")'>\n"
                    "<a class='a' href='#'><img class='flag' src='i_003.png'/><span id='CHN' class='text' onmousemove='lang_color_R(this)' onmouseout='lang_color_GB()'>简体中文</span></a>\n"
                "</div>\n"
            "</div>\n"
        "</div>\n"
        "<div class='login'>\n"
            "<div class='title'>\n"
                "<div class='subtitle'>\n"
                    "<div class='r1 subcolor'></div>\n"
                    "<div class='r2 subcolor'></div>\n"
                    "<div class='r3 subcolor'></div>\n"
                    "<div class='r4 subcolor'></div>\n"
                    "<div class='content subcolor subcontent'>\n"
                        "<div class='content subcolor' style='padding-top:15px;'>\n"
                            "<div class='img'></div>\n"
                        "</div>\n"
                        "<div class='line_long'></div>\n"
                        "<div class='main' style='padding-top:25px;'>\n"
                            "<div class='N01'><span id='N01'>&nbsp;</span></div>\n"
                            "<div class='N02'>\n"
                                "<select id='ID_0x0282' onchange='$(\"ID_0x0283\").select()'></select>\n"
                            "</div>\n"
                        "</div>\n"
                        "<div class='main' style='padding-top:5px;'>\n"
                            "<div class='N01'><span id='N02'>&nbsp;</span></div>\n"
                            "<div class='N02'><input id='ID_0x0283' type='password'/></div>\n"
                        "</div>\n"
                        "<div class='div_btn'>\n"
                            "<button class='btn' id='btn0' onclick='doCheck()'><span id='N03'>&nbsp;</span></button>\n"
                        "</div>\n"
                        "<div id='tip' class='tip'>&nbsp;</div>\n"
                    "</div>\n"
                    "<div class='r4 subcolor'></div>\n"
                    "<div class='r3 subcolor'></div>\n"
                    "<div class='r2 subcolor'></div>\n"
                    "<div class='r1 subcolor'></div>\n"
                "</div>\n"
            "</div>\n"
        "</div>\n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
"</html>\n"
};
#endif
