#ifndef _HTML_H_006_H_
#define _HTML_H_006_H_
static const char h_006[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
 "<head>\n"
 	"<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
 	"<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
 	"<script type='text/javascript'>\n"
 		"var $=function(o){return document.getElementById(o);};\n"
 		"function lang_init_ex(st,end){for(var i=st;i<=end;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
 		"function show_T(tid)\n"
 		"{\n"
 			"var str='';\n"
 			"str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
 			"str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
 			"str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
 			"document.write(str);\n"
 		"}\n"
 		"function show_sT(tid)\n"
 		"{\n"
 			"var str='';\n"
 			"str+=\"<div class='title' style='width:90%;'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
 			"str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
 			"str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
 			"document.write(str);\n"
 		"}\n"
 		"function sendHttpReq(url, successFn)\n"
 		"{\n"
 				//alert(url);	
 		       "var xmlhttp;\n"
 		       "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		       "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		       "xmlhttp.onreadystatechange=function()\n"
 		       "{\n"
 		           "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 		           "{\n"
 		               "if(xmlhttp.responseText=='1'){successFn();}\n"
 		           "}\n"
 		       "};\n"
 		       "xmlhttp.open('GET',url,true);\n"
 		       "xmlhttp.send();\n"
 		"}				\n"
 	"</script>\n"
 	"<style type='text/css'>\n"
 		"tr{height:27px;}\n"
 		".select{width:180px;_width:150px;}\n"
 		".time{width:65px;_width:100px;}\n"
 		".txt{width:120px;height:22px;font-size:14px;text-align:right;}\n"
 		".short_txt{width:50px;}\n"
 		".td_value{text-align:right;padding-right:20px;}\n"
 		".td1{padding-left:40px;text-align:left;}\n"
 		".td2{padding-left:0px;text-align:left;}\n"
 		".td3{padding-left:60px;text-align:left;}\n"
 		".td4{padding-right:5px;text-align:right;}\n"
 		".td5{padding-right:10px;text-align:right;}\n"
 		".radio{padding-left:30px;}\n"
 		".btnStyle{width:50px;height:24px;}\n"
 	"</style>\n"
 "</head>\n"
 "<body onload='Init()'>\n"
 	"<script type='text/javascript'>\n"
 		"show_T('N01');\n"
 		"show_sT('N02');\n"
 	"</script>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='10%' class='td1 odd'><span id='N03'></span></td>\n"
 			 "<td width='15%' class='td2 odd'><input class='txt' style='text-align:center;' id='IP' onkeyup='IPverify(this)' type='text'/></td>\n"
 			"<td width='10%' class='td1 odd'><span id='N04'></span></td>\n"
 			 "<td width='15%' class='td2 odd'><input class='txt' style='text-align:center;' id='SUBMASK' onkeyup='IPverify(this)' type='text'/></td>\n"
 			"<td width='10%' class='td1 odd'><span id='N05'></span></td>\n"
 			 "<td width='15%' class='td2 odd'><input class='txt' style='text-align:center;' id='GATEWAY' onkeyup='IPverify(this)' type='text'/></td>\n"
 			  "<td width='10%' class='td1 odd'><span id='N48'></span></td>\n"
 			 "<td width='15%' class='td2 odd'><input class='txt' style='text-align:center;' id='MAC' onkeyup='MACverify(this)' type='text'/></td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='50%' class='even' align='left'><span id='tip1' class='tip'>&nbsp;</span></td>\n"
 			"<td width='50%' class='even' align='right'>\n"
 				"<button class='btn' onclick='doSubmit(this)' id='N500' style='display:block;'></button>\n"
 			"</td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<div class='line_long'></div>\n"
 	"<div class='blank'></div>\n"
 	"<script type='text/javascript'>\n"
 		"show_sT('N44');\n"
 	"</script>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='10%' class='td1 odd'><span id='N45'></span></td>\n"
 			 "<td width='15%' class='td2 odd'><input class='txt' style='text-align:center;' id='IP2' onkeyup='IPverify2(this)' type='text'/></td>\n"
 			"<td width='10%' class='td1 odd'><span id='N46'></span></td>\n"
 			 "<td width='15%' class='td2 odd'><input class='txt' style='text-align:center;' id='SUBMASK2' onkeyup='IPverify2(this)' type='text'/></td>\n"
 			"<td width='10%' class='td1 odd'><span id='N47'></span></td>\n"
 			 "<td width='15%' class='td2 odd'><input class='txt' style='text-align:center;' id='GATEWAY2' onkeyup='IPverify2(this)' type='text'/></td>\n"
 			   "<td width='10%' class='td1 odd'><span id='N49'></span></td>\n"
 			 "<td width='15%' class='td2 odd'><input class='txt' style='text-align:center;' id='MAC2' onkeyup='MAC2verify(this)' type='text'/></td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='50%' class='even' align='left'><span id='tip8' class='tip'>&nbsp;</span></td>\n"
 			"<td width='50%' class='even' align='right'>\n"
 				"<button class='btn' onclick='doSubmit(this)' id='N512' style='display:block;'></button>\n"
 			"</td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<div class='line_long'></div>\n"
 	"<div class='blank'></div>\n"
 	"<script type='text/javascript'>\n"
 		"show_sT('N08');\n"
 	"</script>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='13%' class='td1 odd'><span id='N09'></span></td>\n"
 			 "<td width='15%' class='td2 odd'><input class='txt' id='ID_0x0164' maxlength='3' onkeyup='Verify(this)' type='text'/></td>\n"
 			"<td width='20%' class='td2 odd'>(1~247)</td>\n"
 			"<td width='20%' class='td1 odd'><span id='N10'></span></td>\n"
 			 "<td width='12%' class='td2 odd'><input class='txt' id='ID_0x0165' maxlength='5' onkeyup='Verify(this)' type='text'/></td>\n"
 			"<td width='20%' class='td2 odd'>(1~65535)</td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='50%' class='even' align='left'><span id='tip3' class='tip'>&nbsp;</span></td>\n"
 			"<td width='50%' class='even' align='right'>\n"
 				"<button class='btn' onclick='doSubmit(this)' id='N502' style='display:block;'></button>\n"
 			"</td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<div class='line_long'></div>\n"
 	"<div class='blank'></div>\n"
 	"<script type='text/javascript'>\n"
 		"show_sT('N11');\n"
 	"</script>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='15%' class='td1 odd'><span id='N12'></span></td>\n"
 			"<td width='15%' class='td2 odd'><input name='BMSMODE' type='radio' id='BMSM0' onclick='radiocontrol()' value='0' checked='checked'/><span id='N13'></span></td>\n"
 			"<td width='15%' class='td2 odd'><input name='BMSMODE' type='radio' id='BMSM1' onclick='radiocontrol()' value='1'/><span id='N14'></span></td>\n"
 			"<td width='15%' class='td2 odd'><input name='BMSMODE' type='radio' id='BMSM2' onclick='radiocontrol()' value='2'/><span id='N15'></span></td>\n"
 			"<td width='15%' class='td2 odd'></td>\n"
 			"<td width='10%' class='td2 odd'></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<td class='td1 even'><span id='N16'></span></td>\n"
 			"<td class='td2 even'><input name='BMSFCONT' type='radio' id='BMSFC0' value='0' checked='checked'/><span id='N17'></span></td>\n"
 			"<td class='td2 even'><input name='BMSFCONT' type='radio' id='BMSFC1' value='1'/><span id='N18'></span></td>\n"
 			"<td class='td2 even'><input name='BMSFCONT' type='radio' id='BMSFC2' value='2'/><span id='N19'></span></td>\n"
 			"<td class='td2 even'></td>\n"
 			"<td class='td2 even'></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<td class='td1 odd'><span id='N20'></span></td>\n"
 			"<td class='td2 odd'><input name='BMSWCONT' type='radio' id='BMSWC0' value='0' checked='checked'/><span id='N21'></span></td>\n"
 			"<td class='td2 odd'><input name='BMSWCONT' type='radio' id='BMSWC1' value='1'/><span id='N22'></span></td>\n"
 			"<td class='td2 odd'><input name='BMSWCONT' type='radio' id='BMSWC2' value='2'/><span id='N23'></span></td>\n"
 			"<td class='td2 odd'></td>\n"
 			"<td class='td2 odd'></td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='50%' class='even' align='left'><span id='tip4' class='tip'>&nbsp;</span></td>\n"
 			"<td width='50%' class='even' align='right'>\n"
 				"<button class='btn' onclick='doSubmit(this)' id='N503' style='display:block;'></button>\n"
 			"</td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<div class='line_long'></div>\n"
 	"<div class='blank'></div>\n"
 	"<script type='text/javascript'>\n"
 		"show_sT('N25');\n"
 	"</script>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='17%' class='td1 odd'><span id='N26'></span></td>\n"
 			 "<td width='17%' class='td2 odd'><input class='txt' id='ID_0x016A' maxlength='5' onkeyup='Verify(this)' type='text'/></td>\n"
 			"<td width='15%' class='td2 odd'>(1~65535)</td>\n"
 			"<td width='17%' class='td1 odd'></td>\n"
 			"<td width='17%' class='td2 odd'></td>\n"
 			"<td width='17%' class='td2 odd'></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<td class='td1 even'><span id='N27'></span></td>\n"
 			"<td class='td2 even'><input class='txt' id='ID_0x016B' maxlength='3' onkeyup='Verify(this)' type='text'/>s</td>\n"
 			"<td class='td2 even'>(1~255)</td>\n"
 			"<td class='td1 even'><span id='N28'></span></td>\n"
 			"<td class='td2 even'><input class='txt' id='ID_0x016C' maxlength='3' onkeyup='Verify(this)' type='text'/>s</td>\n"
 			"<td class='td2 even'>(1~255)</td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<td class='td1 odd'><span id='N29'></span></td>\n"
 			"<td class='td2 odd'><input class='txt' id='ID_0x016D' maxlength='5' onkeyup='Verify(this)' type='text'/></td>\n"
 			"<td class='td2 odd'>(1~32767)</td>\n"
 			"<td class='td1 odd'><span id='N30'></span></td>\n"
 			"<td class='td2 odd'><input class='txt' id='ID_0x016E' maxlength='5' onkeyup='Verify(this)' type='text'/></td>\n"
 			"<td class='td2 odd'>(1~32767)</td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='50%' class='even' align='left'><span id='tip5' class='tip'>&nbsp;</span></td>\n"
 			"<td width='50%' class='even' align='right'>\n"
 				"<button class='btn' onclick='doSubmit(this)' id='N504' style='display:block;'></button>\n"
 			"</td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<div class='line_long'></div>\n"
 	"<div class='blank'></div>\n"
        "<!-- 通讯参数配置 -->\n"
        "<script type='text/javascript'>\n"
            "show_sT('N38');\n"
        "</script>\n"
        "<table width='90%' border='1' id='tab1' style='border-collapse:collapse;border-spacing:0px;border-color:#e0e0e0;'>  \n"
            "<tr id='tr0'>\n"
                "<!-- 串口号 -->\n"
                "<td width='10%' class='odd'><span id='N39' style=\"font-weight:bold;\"></span></td>\n"
                "<!-- 波特率 -->\n"
                "<td width='20%' class='odd'><span id='N40' style=\"font-weight:bold;\"></span></td>\n"
                "<!-- 接入设备类型 -->\n"
                "<td width='20%' class='odd'><span id='N41' style=\"font-weight:bold;\"></span></td>\n"
                "<!-- 起始ID -->\n"
                "<td width='25%' class='odd'><span id='N42' style=\"font-weight:bold;\"></span></td>\n"
                "<!-- 结束ID -->\n"
                "<td width='25%' class='odd'><span id='N43' style=\"font-weight:bold;\"></span></td>\n"
            "</tr>\n"
            "<tr id='tr1'>\n"
                "<td width='10%' class='even'><span>1</span></td>\n"
                "<td width='20%' class='even'><select style='width:135px;text-align:center;' id='COM_BAUD0'></select></td>\n"
                "<td width='20%' class='even'><select onchange='onChange(this)' style='width:135px;text-align:center;' id='COM_DEVICE_TYPE0'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='COM_BEGIN_ID0'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='COM_END_ID0'></select></td>\n"
            "</tr>\n"
            "<tr id='tr2'>\n"
                "<td width='10%' class='even'><span>2</span></td>\n"
                "<td width='20%' class='even'><select style='width:135px;text-align:center;' id='COM_BAUD1'></select></td>\n"
                "<td width='20%' class='even'><select onchange='onChange(this)' style='width:135px;text-align:center;' id='COM_DEVICE_TYPE1'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='COM_BEGIN_ID1'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='COM_END_ID1'></select></td>\n"
            "</tr>\n"
            "<tr id='tr3'>\n"
                "<td width='10%' class='even'><span>3</span></td>\n"
                "<td width='20%' class='even'><select style='width:135px;text-align:center;' id='COM_BAUD2'></select></td>\n"
                "<td width='20%' class='even'><select onchange='onChange(this)' style='width:135px;text-align:center;' id='COM_DEVICE_TYPE2'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='COM_BEGIN_ID2'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='COM_END_ID2'></select></td>\n"
            "</tr>\n"
            "<tr id='tr4'>\n"
                "<td width='10%' class='even'><span>4</span></td>\n"
                "<td width='20%' class='even'><select style='width:135px;text-align:center;' id='COM_BAUD3'></select></td>\n"
                "<td width='20%' class='even'><select onchange='onChange(this)' style='width:135px;text-align:center;' id='COM_DEVICE_TYPE3'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='COM_BEGIN_ID3'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='COM_END_ID3'></select></td>\n"
            "</tr>   \n"
            "<tr id='tr5'>\n"
                "<td width='10%' class='even'><span>5</span></td>\n"
                "<td width='20%' class='even'><select style='width:135px;text-align:center;' id='COM_BAUD4'></select></td>\n"
                "<td width='20%' class='even'><select onchange='onChange(this)' style='width:135px;text-align:center;' id='COM_DEVICE_TYPE4'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='COM_BEGIN_ID4'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='COM_END_ID4'></select></td>\n"
            "</tr>  \n"
            "<tr id='tr6'>\n"
                "<td width='10%' class='even'><span>6</span></td>\n"
                "<td width='20%' class='even'><select style='width:135px;text-align:center;' id='COM_BAUD5'></select></td>\n"
                "<td width='20%' class='even'><select onchange='onChange(this)' style='width:135px;text-align:center;' id='COM_DEVICE_TYPE5'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='COM_BEGIN_ID5'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='COM_END_ID5'></select></td>\n"
            "</tr>    \n"
        "</table>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='50%' class='even' align='left'><span id='tip7' class='tip'>&nbsp;</span></td>\n"
 			"<td width='50%' class='even' align='right'>\n"
 				"<button class='btn' onclick='doSubmit(this)' id='N511' style='display:block;'></button>\n"
 			"</td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<div class='line_long'></div>\n"
 	"<div class='blank'></div>\n"
 	"<script type='text/javascript'>\n"
 		"show_sT('N31');\n"
 	"</script>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr id='tPcs'>\n"
 			"<!-- PCS最大个数配置 -->\n"
 			"<td width='30%' class='td1 odd' align='left'><span id='N32'></span></td>\n"
 		  	  "<td width='30%' class='odd' align='right'><input class='txt' id='ID_0x0350' maxlength='6' onkeyup='Verify(this)' type='text'/></td>\n"
 			"<td width='40%' class='td1 odd' align='left'>(1~60)</td>\n"
 		"</tr>\n"
 		"<tr id='bPcs'>\n"
 			"<td width='30%' class='even' align='left'><span id='tip10' class='tip'>&nbsp;</span></td>\n"
 			"<td width='30%' class='even' align='left'></td>\n"
 			"<td width='40%' class='even' align='right'>\n"
 				"<button class='btn' onclick='doSubmit(this)' id='N505' style='display:block;'></button>\n"
 			"</td>\n"
 		"</tr>\n"
 		"<tr id='tPv'>\n"
 			"<!-- PV最大个数配置 -->\n"
 			"<td width='30%' class='td1 odd' align='left'><span id='N33'></span></td>\n"
 		  	  "<td width='30%' class='odd' align='right'><input class='txt' id='ID_0x0351' maxlength='6' onkeyup='Verify(this)' type='text'/></td>\n"
 			"<td width='40%' class='td1 odd' align='left'>(1~60)</td>\n"
 		"</tr>\n"
 		"<tr id='bPv'>\n"
 			"<td width='30%' class='even' align='left'><span id='tip11' class='tip'>&nbsp;</span></td>\n"
 			"<td width='30%' class='even' align='left'></td>\n"
 			"<td width='40%' class='even' align='right'>\n"
 				"<button class='btn' onclick='doSubmit(this)' id='N506' style='display:block;'></button>\n"
 			"</td>\n"
 		"</tr>\n"
 		"<tr id='tDcdc'>\n"
 			"<!-- DCDC最大个数配置 -->\n"
 			"<td width='30%' class='td1 odd' align='left'><span id='N34'></span></td>\n"
 		  	  "<td width='30%' class='odd' align='right'><input class='txt' id='ID_0x0352' maxlength='6' onkeyup='Verify(this)' type='text'/></td>\n"
 			"<td width='40%' class='td1 odd' align='left'>(1~30)</td>\n"
 		"</tr>\n"
 		"<tr id='bDcdc'>\n"
 			"<td width='30%' class='even' align='left'><span id='tip12' class='tip'>&nbsp;</span></td>\n"
 			"<td width='30%' class='even' align='left'></td>\n"
 			"<td width='40%' class='even' align='right'>\n"
 				"<button class='btn' onclick='doSubmit(this)' id='N507' style='display:block;'></button>\n"
 			"</td>\n"
 		"</tr>\n"
 		"</tr>\n"
 			"<tr id='tPvs'>\n"
 			"<!-- PVS最大个数配置 -->\n"
 			"<td width='30%' class='td1 odd' align='left'><span id='N35'></span></td>\n"
 		  	  "<td width='30%' class='odd' align='right'><input class='txt' id='ID_0x0353' maxlength='6' onkeyup='Verify(this)' type='text'/></td>\n"
 			"<td width='40%' class='td1 odd' align='left'>(1~50)</td>\n"
 		"</tr>\n"
 		"<tr id='bPvs'>\n"
 			"<td width='30%' class='even' align='left'><span id='tip13' class='tip'>&nbsp;</span></td>\n"
 			"<td width='30%' class='even' align='left'></td>\n"
 			"<td width='40%' class='even' align='right'>\n"
 				"<button class='btn' onclick='doSubmit(this)' id='N508' style='display:block;'></button>\n"
 			"</td>\n"
 		"</tr>\n"
 		"<tr id='tBms'>\n"
 			"<!-- BMS最大个数配置 -->\n"
 			"<td width='30%' class='td1 odd' align='left'><span id='N36'></span></td>\n"
 		  	  "<td width='30%' class='odd' align='right'><input class='txt' id='ID_0x0354' maxlength='6' onkeyup='Verify(this)' type='text'/></td>\n"
 			"<td width='40%' class='td1 odd' align='left'>(1~60)</td>\n"
 		"</tr>\n"
 		"<tr id='bBms'>\n"
 			"<td width='30%' class='even' align='left'><span id='tip14' class='tip'>&nbsp;</span></td>\n"
 			"<td width='30%' class='even' align='left'></td>\n"
 			"<td width='40%' class='even' align='right'>\n"
 				"<button class='btn' onclick='doSubmit(this)' id='N509' style='display:block;'></button>\n"
 			"</td>\n"
 		"</tr>\n"
 		"<tr id='tAmmeter'>\n"
 			"<!-- 电表最大个数配置 -->\n"
 			"<td width='30%' class='td1 odd' align='left'><span id='N37'></span></td>\n"
 		  	  "<td width='30%' class='odd' align='right'><input class='txt' id='ID_0x0355' maxlength='6' onkeyup='Verify(this)' type='text'/></td>\n"
 			"<td width='40%' class='td1 odd' align='left'>(1~12)</td>\n"
 		"</tr>\n"
 		"<tr id='bAmmeter'>\n"
 			"<td width='30%' class='even' align='left'><span id='tip15' class='tip'>&nbsp;</span></td>\n"
 			"<td width='30%' class='even' align='left'></td>\n"
 			"<td width='40%' class='even' align='right'>\n"
 				"<button class='btn' onclick='doSubmit(this)' id='N510' style='display:block;'></button>\n"
 			"</td>\n"
 	"</table>\n"
 	"<div class='line_long'></div>\n"
 	"<div class='btm_blank'></div>\n"
 	"<div id='trans'></div>\n"
 	"<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
 "</body>\n"
 "<script language='javascript' type='text/javascript'>\n"
 	"var language=1;\n"
 	"var Json;\n"
 	"var lang=\n"
 	"{\n"
 		"N01:['通讯参数','Communication Parameters'],\n"
 		"N02:['网络1参数','Network1 Parameters'],\n"
 		"N03:['IP地址','IP Address'],\n"
 		"N04:['子网掩码','Subnet Mask'],\n"
 		"N05:['网关','Gateway'],\n"
 		"N06:['RS485参数','RS485 Parameters'],\n"
 		"N07:['波特率','Baud Rate'],\n"
 		"N08:['Modbus参数','Modbus Parameters'],\n"
 		"N09:['地址','Address'],\n"
 		"N10:['TCP端口号','TCP Port'],\n"
 		"N11:['BMS参数','BMS Parameters'],\n"
 		"N12:['BMS通讯方式','BMS Com-Mode'],\n"
 		"N13:['无','None'],\n"
 		"N14:['CAN','CAN'],\n"
 		"N15:['RS485','RS485'],\n"
 		"N16:['BMS故障干接点','BMS F-Contact'],\n"
 		"N17:['关闭','Disabled'],\n"
 		"N18:['开启（常开）','Enabled(Open)'],\n"
 		"N19:['开启（常闭）','Enabled(Close)'],\n"
 		"N20:['BMS告警干接点','BMS W-Contact'],\n"
 		"N21:['关闭','Disabled'],\n"
 		"N22:['开启（常开）','Enabled(Open)'],\n"
 		"N23:['开启（常闭）','Enabled(Close)'],\n"
 		"N24:['开启（常闭）','Enabled(Close)'],			\n"
 		"N25:['IEC-104参数','IEC-104 Parameters'],\n"
 		"N26:['地址','Address'],\n"
 		"N27:['超时时间T1','Timeout T1'],\n"
 		"N28:['超时时间T3','Timeout T3'],\n"
 		"N29:['参数k','Parameter k'],\n"
 		"N30:['参数w','Parameter w'],\n"
 		"N31:['设备最大台数','Devices Max Num'],\n"
 		"N32:['储能逆变器个数','PCS Num'],\n"
 		"N33:['光伏逆变器个数','PV Num'],\n"
 		"N34:['光伏控制器个数','DCDC Num'],\n"
 		"N35:['汇流箱个数','PVS Num'],\n"
 		"N36:['电池个数','BMS Num'],\n"
 		"N37:['电表个数','Ammeter Num'],\n"
"\n"
            "N38:['通讯口配置','Com Config'],\n"
            "N39:['串口号','Serial Num'],\n"
            "N40:['波特率','Baud'],\n"
            "N41:['接入设备类型','Device Type'],\n"
            "N42:['起始ID','Begin ID'],\n"
            "N43:['结束ID','End ID'],	\n"
"\n"
 		"N44:['网络2参数','Network2 Parameters'],\n"
 		"N45:['IP地址','IP Address'],\n"
 		"N46:['子网掩码','Subnet Mask'],\n"
 		"N47:['网关','Gateway'],      \n"
"\n"
 		"N48:['物理地址','Mac'],  \n"
 		"N49:['物理地址','Mac'],    		\n"
"\n"
 		"N50:['80端口已被占用！','Port 80 has been occupied!'],\n"
 		"N51:['2404端口已被占用！','Port 2404 has been occupied!'],\n"
 		"N52:['保存成功！','Saved successfully!'],\n"
 		"N53:['格式错误！','Format error!'],\n"
 		"N54:['范围错误！','Range error!'],\n"
 		"N55:['超时时间T1&lt;超时时间T3！','Timeout T1&lt;Timeout T3!'],\n"
 		"N56:['超时时间T3&gt;超时时间T1！','Timeout T3&gt;Timeout T1!'],\n"
 		"N57:['k*2/3&gt;=w！','k*2/3&gt;=w!'],\n"
 		"N58:['设置失败！','Set failed!'],\n"
 		"N59:['设置成功！','Set successfully!'],\n"
"\n"
            "N100:['触摸屏','TOUCH'],\n"
            "N101:['储能逆变器','PCS'],\n"
            "N102:['光伏逆变器','PV'],\n"
            "N103:['光伏控制器','DCDC'],\n"
            "N104:['电池','BMS'],\n"
            "N105:['电表','AMMETER'],\n"
            "N106:['汇流箱','PVS'],\n"
            "N107:['环境监测仪','Env-Detector'], \n"
            "N108:['无','NONE'],\n"
          "\n"
            "N110:['触摸屏','TOUCH'],\n"
            "N111:['储能逆变器','PCS'],\n"
            "N112:['光伏逆变器','PV'],\n"
            "N113:['光伏控制器','DCDC'],\n"
            "N114:['电池','BMS'],\n"
            "N115:['电表','AMMETER'],\n"
            "N116:['汇流箱','PVS'], \n"
            "N117:['环境监测仪','Env-Detector'], \n"
            "N118:['无','NONE'],\n"
"\n"
            "N120:['触摸屏','TOUCH'],\n"
            "N121:['储能逆变器','PCS'],\n"
            "N122:['光伏逆变器','PV'],\n"
            "N123:['光伏控制器','DCDC'],\n"
            "N124:['电池','BMS'],\n"
            "N125:['电表','AMMETER'],\n"
            "N126:['汇流箱','PVS'],  \n"
            "N127:['环境监测仪','Env-Detector'], \n"
            "N128:['无','NONE'],                   \n"
"\n"
            "N130:['触摸屏','TOUCH'],\n"
            "N131:['储能逆变器','PCS'],\n"
            "N132:['光伏逆变器','PV'],\n"
            "N133:['光伏控制器','DCDC'],\n"
            "N134:['电池','BMS'],\n"
            "N135:['电表','AMMETER'],\n"
            "N136:['汇流箱','PVS'], \n"
            "N137:['环境监测仪','Env-Detector'], \n"
            "N138:['无','NONE'],\n"
"\n"
            "N140:['触摸屏','TOUCH'],\n"
            "N141:['储能逆变器','PCS'],\n"
            "N142:['光伏逆变器','PV'],\n"
            "N143:['光伏控制器','DCDC'],\n"
            "N144:['电池','BMS'],\n"
            "N145:['电表','AMMETER'],\n"
            "N146:['汇流箱','PVS'], \n"
            "N147:['环境监测仪','Env-Detector'], \n"
            "N148:['无','NONE'],\n"
"\n"
            "N150:['触摸屏','TOUCH'],\n"
            "N151:['上位机','PC'],  			\n"
"\n"
 		"N500:['设&nbsp;&nbsp;置','Set'],\n"
 		"N501:['设&nbsp;&nbsp;置','Set'],\n"
 		"N502:['设&nbsp;&nbsp;置','Set'],\n"
 		"N503:['设&nbsp;&nbsp;置','Set'],\n"
 		"N504:['设&nbsp;&nbsp;置','Set'],\n"
 		"N505:['设&nbsp;&nbsp;置','Set'],\n"
 		"N506:['设&nbsp;&nbsp;置','Set'],\n"
 		"N507:['设&nbsp;&nbsp;置','Set'],\n"
 		"N508:['设&nbsp;&nbsp;置','Set'],\n"
 		"N509:['设&nbsp;&nbsp;置','Set'],\n"
 		"N510:['设&nbsp;&nbsp;置','Set'],\n"
 		"N511:['设&nbsp;&nbsp;置','Set'],\n"
 		"N512:['设&nbsp;&nbsp;置','Set']\n"
 	"};\n"
 	"var temp_IP,temp_MASK,temp_GATE;\n"
"\n"
 	"function Init()\n"
 	"{\n"
 		"var URL='s_006.html?0x0000&time='+Math.random();\n"
 		"var xmlhttp;\n"
 		"if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		"xmlhttp.onreadystatechange=function()\n"
 		"{\n"
 			"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 			"{\n"
 				"eval('Json='+xmlhttp.responseText);\n"
 				"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
 				"lang_init_ex(1,5);\n"
 				"lang_init_ex(8,23);\n"
 				"lang_init_ex(25,49);\n"
 				"lang_init_ex(500,500);\n"
 				"lang_init_ex(502,512);\n"
"\n"
 					//删除所有option, 动态切换语言时必须操作
 				"for(var i=0;i<6;i++)\n"
 				"{\n"
 					"eval('$(\\'COM_BAUD'+i+'\\').options.length=0;');\n"
 					"eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options.length=0;');\n"
 					"eval('$(\\'COM_BEGIN_ID'+i+'\\').options.length=0;');\n"
 					"eval('$(\\'COM_END_ID'+i+'\\').options.length=0;');\n"
 				"}					\n"
"\n"
                     //初始化
                    "for(var i=0;i<5;i++)\n"
                    "{\n"
                        "eval('$(\\'COM_BAUD'+i+'\\').options.add(new Option('+9600+',0));');\n"
                        "eval('$(\\'COM_BAUD'+i+'\\').options.add(new Option('+19200+',1));');\n"
                        "eval('$(\\'COM_BAUD'+i+'\\').options.add(new Option('+38400+',2));');\n"
                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options.add(new Option(lang.N'+(100+i*10+1)+'[language],0));');\n"
                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options.add(new Option(lang.N'+(100+i*10+2)+'[language],1));');\n"
                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options.add(new Option(lang.N'+(100+i*10+3)+'[language],2));');\n"
                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options.add(new Option(lang.N'+(100+i*10+4)+'[language],3));');\n"
                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options.add(new Option(lang.N'+(100+i*10+5)+'[language],4));');\n"
                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options.add(new Option(lang.N'+(100+i*10+6)+'[language],5));');\n"
                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options.add(new Option(lang.N'+(100+i*10+7)+'[language],6));');\n"
                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options.add(new Option(lang.N'+(100+i*10+8)+'[language],7));');\n"
                        "for(var j=0; j<247; j++)eval('$(\\'COM_BEGIN_ID'+i+'\\').options.add(new Option('+(j+1)+','+j+'));');\n"
                        "for(var k=0; k<247; k++)eval('$(\\'COM_END_ID'+i+'\\').options.add(new Option('+(k+1)+','+k+'));');                 \n"
                    "}\n"
"\n"
                    "$('COM_BAUD5').options.add(new Option(9600,0));\n"
                    "$('COM_BAUD5').options.add(new Option(19200,1));\n"
                    "$('COM_BAUD5').options.add(new Option(38400,2));\n"
"\n"
                     //$('COM_BAUD5').disabled = true;
                    "$('COM_DEVICE_TYPE5').options.add(new Option(lang.N150[language],0));\n"
                    "$('COM_DEVICE_TYPE5').options.add(new Option(lang.N151[language],1));\n"
                     //$('COM_DEVICE_TYPE5').disabled = true;
                    "for(var j=0; j<247; j++)eval('$(\\'COM_BEGIN_ID5\\').options.add(new Option('+(j+1)+','+j+'));');\n"
                     //$('COM_BEGIN_ID5').disabled = true;
                    "$('COM_END_ID5').disabled = true;\n"
"\n"
 				"doSetValue(Json);\n"
"\n"
 				"if(Json.ID_0x0282==0x11)\n"
 				"{\n"
 					"$('N500').style.display='none';\n"
 					"for(var i=502; i<=512; i++) eval('$(\\'N'+i+'\\').style.display=\\'none\\';'); \n"
 					"$('trans').style.zIndex=9999;	\n"
 				"}\n"
 				"else\n"
 				"{\n"
 					"$('N500').style.display='inline';\n"
 					"for(var i=502; i<=512; i++) eval('$(\\'N'+i+'\\').style.display=\\'inline\\';');\n"
 					"$('trans').style.zIndex=-9999;\n"
 				"}\n"
 			"}\n"
 		"};\n"
 		"xmlhttp.open('GET',URL,true);\n"
 		"xmlhttp.send();\n"
 	"}\n"
        "function onChange(obj)\n"
        "{\n"
         "switch(obj.id)\n"
         "{\n"
 	        "case 'COM_DEVICE_TYPE0':\n"
 		        "if($('COM_DEVICE_TYPE0').selectedIndex==7){\n"
 		        	"$('COM_BAUD0').disabled=true;\n"
 		               "$('COM_BEGIN_ID0').disabled = true;\n"
 		               "$('COM_END_ID0').disabled = true; 	\n"
 		        "}else{\n"
 		        	"$('COM_BAUD0').disabled=false;\n"
 		               "$('COM_BEGIN_ID0').disabled = false;\n"
 		               "$('COM_END_ID0').disabled = false;         		\n"
 		        "}   \n"
 	        "break;     	\n"
 	        "case 'COM_DEVICE_TYPE1':\n"
 		        "if($('COM_DEVICE_TYPE1').selectedIndex==7){\n"
 		        	"$('COM_BAUD1').disabled=true;\n"
 		               "$('COM_BEGIN_ID1').disabled = true;\n"
 		               "$('COM_END_ID1').disabled = true; 	\n"
 		        "}else{\n"
 		        	"$('COM_BAUD1').disabled=false;\n"
 		               "$('COM_BEGIN_ID1').disabled = false;\n"
 		               "$('COM_END_ID1').disabled = false;         		\n"
 		        "}   \n"
 	        "break;\n"
 	        "case 'COM_DEVICE_TYPE2':\n"
 		        "if($('COM_DEVICE_TYPE2').selectedIndex==7){\n"
 		        	"$('COM_BAUD2').disabled=true;\n"
 		               "$('COM_BEGIN_ID2').disabled = true;\n"
 		               "$('COM_END_ID2').disabled = true; 	\n"
 		        "}else{\n"
 		        	"$('COM_BAUD2').disabled=false;\n"
 		               "$('COM_BEGIN_ID2').disabled = false;\n"
 		               "$('COM_END_ID2').disabled = false;         		\n"
 		        "}   \n"
 	        "break;\n"
 	        "case 'COM_DEVICE_TYPE3':\n"
 		        "if($('COM_DEVICE_TYPE3').selectedIndex==7){\n"
 		        	"$('COM_BAUD3').disabled=true;\n"
 		               "$('COM_BEGIN_ID3').disabled = true;\n"
 		               "$('COM_END_ID3').disabled = true; 	\n"
 		        "}else{\n"
 		        	"$('COM_BAUD3').disabled=false;\n"
 		               "$('COM_BEGIN_ID3').disabled = false;\n"
 		               "$('COM_END_ID3').disabled = false;         		\n"
 		        "}   \n"
 	        "break;\n"
 	        "case 'COM_DEVICE_TYPE4':\n"
 		        "if($('COM_DEVICE_TYPE4').selectedIndex==7){\n"
 		        	"$('COM_BAUD4').disabled=true;\n"
 		               "$('COM_BEGIN_ID4').disabled = true;\n"
 		               "$('COM_END_ID4').disabled = true; 	\n"
 		        "}else{\n"
 		        	"$('COM_BAUD4').disabled=false;\n"
 		               "$('COM_BEGIN_ID4').disabled = false;\n"
 		               "$('COM_END_ID4').disabled = false;         		\n"
 		        "}   \n"
 	        "break;\n"
 	        "case 'COM_DEVICE_TYPE5':\n"
 		           "if($('COM_DEVICE_TYPE5').selectedIndex==0){\n"
 		               "$('COM_BEGIN_ID5').disabled = true;\n"
 		               "$('COM_END_ID5').disabled = true; \n"
 		           "}else if($('COM_DEVICE_TYPE5').selectedIndex==1){\n"
 		               "$('COM_BEGIN_ID5').disabled = false;\n"
 		               "$('COM_END_ID5').disabled = true; \n"
 		           "}\n"
 		       "break;\n"
         "}\n"
        "}\n"
         //16进制数补齐2位
 	"function str_pad(hex){\n"
 		  "var zero = '00';   \n"
 		  "var tmp  = 2-hex.length;\n"
 		  "return zero.substr(0,tmp) + hex;\n"
 	"}\n"
 	"function read_back(addr)\n"
 	"{\n"
 		"var url='s_006.html?';\n"
"\n"
 		"if(addr==0x157){url=url+'0x0157'+'&0x0158'+'&0x0159'+'&0x015A'+'&0x015B'+'&0x015C'+'&0x015D'+'&0x015E'+'&0x015F'+'&0x0160'+'&0x0161'+'&0x0162'+'&0x0230'+'&0x0231'+'&0x0232'+'&0x0233'+'&0x0234'+'&0x0235';}\n"
 		"else if(addr==0x210){url=url+'0x0210'+'&0x0211'+'&0x0212'+'&0x0213'+'&0x0214'+'&0x0215'+'&0x0216'+'&0x0217'+'&0x0218'+'&0x0219'+'&0x021A'+'&0x021B'+'&0x0240'+'&0x0241'+'&0x0242'+'&0x0243'+'&0x0244'+'&0x0245';}\n"
 		"else if(addr==0x164){url=url+'0x0164'+'&0x0165';}\n"
 		"else if(addr==0x166){url=url+'0x0166'+'&0x0167'+'&0x0168';}\n"
 		"else if(addr==0x16A){url=url+'0x016A'+'&0x016B'+'&0x016C'+'&0x016D'+'&0x016E';}\n"
 		"else if(addr==0x2000){url=url+'0x2000'+'&0x2001'+'&0x2002'+'&0x2003'+'&0x2004'+'&0x2005'+'&0x2006'+'&0x2007'+'&0x2008'+'&0x2009'+'&0x200A'+'&0x200B'+\n"
 			"'&0x200C'+'&0x200D'+'&0x200E'+'&0x200F'+'&0x2010'+'&0x2011'+'&0x2012'+'&0x2013'+'&0x2014'+'&0x2015'+'&0x2016'+'&0x2017';}\n"
 		"else{url=url+'0x0'+addr.toString(16).toUpperCase();}	\n"
 		"url=url+'&time='+Math.random();\n"
 			//alert(url); 
"\n"
 		"var xmlhttp;\n"
 		"if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		"xmlhttp.onreadystatechange=function()\n"
 		"{\n"
 			"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 			"{\n"
 				"eval('Json='+xmlhttp.responseText);\n"
 				"if(addr==0x157)\n"
 				"{\n"
 					"var ip=$('IP').value;\n"
 					"var submask=$('SUBMASK').value;\n"
 					"var gateway=$('GATEWAY').value;\n"
 					"var mac=$('MAC').value;\n"
 					"var ip_get=String(Json.ID_0x0157)+'.'+String(Json.ID_0x0158)+'.'+String(Json.ID_0x0159)+'.'+String(Json.ID_0x015A);\n"
 					"var submask_get=String(Json.ID_0x015B)+'.'+String(Json.ID_0x015C)+'.'+String(Json.ID_0x015D)+'.'+String(Json.ID_0x015E);\n"
 					"var gateway_get=String(Json.ID_0x015F)+'.'+String(Json.ID_0x0160)+'.'+String(Json.ID_0x0161)+'.'+String(Json.ID_0x0162);\n"
 					"var mac_get=String(str_pad(Json.ID_0x0230.toString(16)))+':'+String(str_pad(Json.ID_0x0231.toString(16)))+':'+String(str_pad(Json.ID_0x0232.toString(16)))+':'+String(str_pad(Json.ID_0x0233.toString(16)))+':'+String(str_pad(Json.ID_0x0234.toString(16)))+':'+String(str_pad(Json.ID_0x0235.toString(16)));\n"
 					"show_tip_ex(1,'&nbsp;');\n"
 					"if(ip!=ip_get || submask!=submask_get || gateway!= gateway_get || mac!=mac_get){\n"
 						"$('IP').value=ip_get;\n"
 						"$('SUBMASK').value=submask_get;\n"
 						"$('GATEWAY').value=gateway_get;\n"
 						"$('MAC').value=String(str_pad(Json.ID_0x0230.toString(16)))+':'+String(str_pad(Json.ID_0x0231.toString(16)))+':'+String(str_pad(Json.ID_0x0232.toString(16)))+':'+String(str_pad(Json.ID_0x0233.toString(16)))+':'+String(str_pad(Json.ID_0x0234.toString(16)))+':'+String(str_pad(Json.ID_0x0235.toString(16)));\n"
 						"setTimeout('show_tip_ex(1,lang.N58[language])',500);		\n"
 					"}else{\n"
 						"setTimeout('show_tip_ex(1,lang.N59[language])',500);\n"
 					"}\n"
 					"setTimeout('show_tip_ex(1,\\'&nbsp;\\')',2500);\n"
 				"}\n"
 				"else if(addr==0x210)\n"
 				"{\n"
 					"var ip=$('IP2').value;\n"
 					"var submask=$('SUBMASK2').value;\n"
 					"var gateway=$('GATEWAY2').value;\n"
 					"var mac=$('MAC2').value;\n"
 					"var ip_get=String(Json.ID_0x0210)+'.'+String(Json.ID_0x0211)+'.'+String(Json.ID_0x0212)+'.'+String(Json.ID_0x0213);\n"
 					"var submask_get=String(Json.ID_0x0214)+'.'+String(Json.ID_0x0215)+'.'+String(Json.ID_0x0216)+'.'+String(Json.ID_0x0217);\n"
 					"var gateway_get=String(Json.ID_0x0218)+'.'+String(Json.ID_0x0219)+'.'+String(Json.ID_0x021A)+'.'+String(Json.ID_0x021B);\n"
 					"var mac_get=String(str_pad(Json.ID_0x0240.toString(16)))+':'+String(str_pad(Json.ID_0x0241.toString(16)))+':'+String(str_pad(Json.ID_0x0242.toString(16)))+':'+String(str_pad(Json.ID_0x0243.toString(16)))+':'+String(str_pad(Json.ID_0x0244.toString(16)))+':'+String(str_pad(Json.ID_0x0245.toString(16)));\n"
 					"show_tip_ex(8,'&nbsp;');\n"
 					"if(ip!=ip_get || submask!=submask_get || gateway!= gateway_get || mac!=mac_get){\n"
 						"$('IP2').value=ip_get;\n"
 						"$('SUBMASK2').value=submask_get;\n"
 						"$('GATEWAY2').value=gateway_get;\n"
 						"$('MAC2').value=String(str_pad(Json.ID_0x0240.toString(16)))+':'+String(str_pad(Json.ID_0x0241.toString(16)))+':'+String(str_pad(Json.ID_0x0242.toString(16)))+':'+String(str_pad(Json.ID_0x0243.toString(16)))+':'+String(str_pad(Json.ID_0x0244.toString(16)))+':'+String(str_pad(Json.ID_0x0245.toString(16)));\n"
 						"setTimeout('show_tip_ex(8,lang.N58[language])',500);		\n"
 					"}else{\n"
 						"setTimeout('show_tip_ex(8,lang.N59[language])',500);\n"
 					"}\n"
 					"setTimeout('show_tip_ex(8,\\'&nbsp;\\')',2500);\n"
 				"}\n"
 				"else if(addr==0x164)\n"
 				"{\n"
 					"var pr_addr,fe_addr,pr_port,fe_port;\n"
 					"pr_addr=$('ID_0x0164').value;\n"
 					"pr_port=$('ID_0x0165').value;\n"
 					"fe_addr=Json.ID_0x0164;\n"
 					"fe_port=Json.ID_0x0165;\n"
 					"if(pr_addr!=fe_addr || pr_port!=fe_port){\n"
 						"$('ID_0x0164').value=Json.ID_0x0164;\n"
 						"$('ID_0x0165').value=Json.ID_0x0165;\n"
 						"setTimeout('show_tip_ex(3,lang.N58[language])',500);\n"
 					"}else{\n"
 						"setTimeout('show_tip_ex(3,lang.N59[language])',500);\n"
 					"}\n"
 					"setTimeout('show_tip_ex(3,\\'&nbsp;\\')',2500);\n"
 				"}\n"
 				"else if(addr==0x166)\n"
 				"{\n"
 					"var pr_bmsmode, fe_bmsmode;\n"
 					"var pr_bmsfcont, fe_bmsfcont;\n"
 					"var pr_bmswcont, fe_bmswcont;\n"
 					"if($('BMSM0').checked)pr_bmsmode=$('BMSM0').value;\n"
 					"else if($('BMSM1').checked)pr_bmsmode=$('BMSM1').value;\n"
 					"else if($('BMSM2').checked)pr_bmsmode=$('BMSM2').value;\n"
 					"if($('BMSFC0').checked)pr_bmsfcont=$('BMSFC0').value;\n"
 					"else if($('BMSFC1').checked)pr_bmsfcont=$('BMSFC1').value;\n"
 					"else if($('BMSFC2').checked)pr_bmsfcont=$('BMSFC2').value;\n"
 					"if($('BMSWC0').checked)pr_bmswcont=$('BMSWC0').value;\n"
 					"else if($('BMSWC1').checked)pr_bmswcont=$('BMSWC1').value;\n"
 					"else if($('BMSWC2').checked)pr_bmswcont=$('BMSWC2').value;\n"
 					"fe_bmsmode=Json.ID_0x0166;\n"
 					"fe_bmsfcont=Json.ID_0x0167;\n"
 					"fe_bmswcont=Json.ID_0x0168;\n"
 					"if(pr_bmsmode!=fe_bmsmode || pr_bmsfcont!=fe_bmsfcont || pr_bmswcont!=fe_bmswcont){\n"
 						"if(Json.ID_0x0166==0)\n"
 						"{\n"
 							"$('BMSM0').checked=true;\n"
 							"$('BMSM1').checked=false;\n"
 							"$('BMSM2').checked=false;\n"
 				               "$('BMSFC0').disabled=true;\n"
 				               "$('BMSFC1').disabled=true;\n"
 				               "$('BMSFC2').disabled=true;\n"
 				               "$('BMSWC0').disabled=true;\n"
 				               "$('BMSWC1').disabled=true;\n"
 				               "$('BMSWC2').disabled=true;\n"
 						"}\n"
 						"else if(Json.ID_0x0166==1)\n"
 						"{\n"
 							"$('BMSM0').checked=false;\n"
 							"$('BMSM1').checked=true;\n"
 							"$('BMSM2').checked=false;\n"
 						"}\n"
 						"else if(Json.ID_0x0166==2)\n"
 						"{\n"
 							"$('BMSM0').checked=false;\n"
 							"$('BMSM1').checked=false;\n"
 							"$('BMSM2').checked=true;\n"
 						"}\n"
 						"if(Json.ID_0x0167==0)\n"
 						"{\n"
 							"$('BMSFC0').checked=true;\n"
 							"$('BMSFC1').checked=false;\n"
 							"$('BMSFC2').checked=false;\n"
 						"}\n"
 						"else if(Json.ID_0x0167==1)\n"
 						"{\n"
 							"$('BMSFC0').checked=false;\n"
 							"$('BMSFC1').checked=true;\n"
 							"$('BMSFC2').checked=false;\n"
 						"}\n"
 						"else if(Json.ID_0x0167==2)\n"
 						"{\n"
 							"$('BMSFC0').checked=false;\n"
 							"$('BMSFC1').checked=false;\n"
 							"$('BMSFC2').checked=true;\n"
 						"}\n"
 						"if(Json.ID_0x0168==0)\n"
 						"{\n"
 							"$('BMSWC0').checked=true;\n"
 							"$('BMSWC1').checked=false;\n"
 							"$('BMSWC2').checked=false;\n"
 						"}\n"
 						"else if(Json.ID_0x0168==1)\n"
 						"{\n"
 							"$('BMSWC0').checked=false;\n"
 							"$('BMSWC1').checked=true;\n"
 							"$('BMSWC2').checked=false;\n"
 						"}\n"
 						"else if(Json.ID_0x0168==2)\n"
 						"{\n"
 							"$('BMSWC0').checked=false;\n"
 							"$('BMSWC1').checked=false;\n"
 							"$('BMSWC2').checked=true;\n"
 						"}\n"
 						"setTimeout('show_tip_ex(4,lang.N58[language])',500);\n"
 					"}else{\n"
 						"setTimeout('show_tip_ex(4,lang.N59[language])',500);\n"
 					"}\n"
 					"setTimeout('show_tip_ex(4,\\'&nbsp;\\')',2500);\n"
 				"}\n"
 				"else if(addr==0x16A)\n"
 				"{\n"
 					"var pr_addr, fe_addr;\n"
 					"var pr_t1, fe_t1;\n"
 					"var pr_t3, fe_t3;\n"
 					"var pr_k, fe_k;\n"
 					"var pr_w, fe_w;\n"
 					"pr_addr=$('ID_0x016A').value;\n"
 					"pr_t1=$('ID_0x016B').value;\n"
 					"pr_t3=$('ID_0x016C').value;\n"
 					"pr_k=$('ID_0x016D').value;\n"
 					"pr_w=$('ID_0x016E').value;\n"
 					"fe_addr=Json.ID_0x016A;\n"
 					"fe_t1=Json.ID_0x016B;\n"
 					"fe_t3=Json.ID_0x016C;\n"
 					"fe_k=Json.ID_0x016D;\n"
 					"fe_w=Json.ID_0x016E;\n"
 					"if(pr_addr!=fe_addr || pr_t1!=fe_t1 || pr_t3!=fe_t3 || pr_k!=fe_k || pr_w!=fe_w){\n"
 						"$('ID_0x016A').value=Json.ID_0x016A;\n"
 						"$('ID_0x016B').value=Json.ID_0x016B;\n"
 						"$('ID_0x016C').value=Json.ID_0x016C;\n"
 						"$('ID_0x016D').value=Json.ID_0x016D;\n"
 						"$('ID_0x016E').value=Json.ID_0x016E;\n"
 						"setTimeout('show_tip_ex(5,lang.N58[language])',500);\n"
 					"}else{\n"
 						"setTimeout('show_tip_ex(5,lang.N59[language])',500);\n"
 					"}\n"
 					"setTimeout('show_tip_ex(5,\\'&nbsp;\\')',2500);\n"
 				"}\n"
                    "else if(addr == 0x2000)\n"
                    "{\n"
                        "var pr_baud=new Array(0,0,0,0,0), fe_baud=new Array(0,0,0,0,0); \n"
                        "var pr_type=new Array(0,0,0,0,0), fe_type=new Array(0,0,0,0,0);\n"
                        "var pr_st=new Array(0,0,0,0,0), fe_st=new Array(0,0,0,0,0);\n"
                        "var pr_end=new Array(0,0,0,0,0), fe_end=new Array(0,0,0,0,0);\n"
                        "for(var i=0; i<6; i++)\n"
                        "{\n"
                            "if(eval('$(\\'COM_BAUD'+i+'\\').selectedIndex;')==0) pr_baud[i]=9600;\n"
                            "else if(eval('$(\\'COM_BAUD'+i+'\\').selectedIndex;')==1) pr_baud[i]=19200;\n"
                            "else if(eval('$(\\'COM_BAUD'+i+'\\').selectedIndex;')==2) pr_baud[i]=38400;\n"
                            "if(i<5){\n"
                                "if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==0) pr_type[i]=1;\n"
                                "else if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==1) pr_type[i]=2;\n"
                                "else if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==2) pr_type[i]=3;\n"
                                "else if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==3) pr_type[i]=4;\n"
                                "else if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==4) pr_type[i]=5;\n"
                                "else if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==5) pr_type[i]=6; \n"
                                "else if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==6) pr_type[i]=8; \n"
                                "else if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==7) pr_type[i]=10; \n"
                                "pr_st[i] = eval('$(\\'COM_BEGIN_ID'+i+'\\').selectedIndex;')+1;\n"
                                "pr_end[i] = eval('$(\\'COM_END_ID'+i+'\\').selectedIndex;')+1;\n"
                            "}else{\n"
                                "if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==0) pr_type[i]=0;\n"
                                "else if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==1) pr_type[i]=7; \n"
                                "pr_st[i] = eval('$(\\'COM_BEGIN_ID'+i+'\\').selectedIndex;')+1;\n"
                                "pr_end[i] = 0;\n"
                            "} \n"
"\n"
                            "fe_baud[i] = eval('Json.ID_0x'+(0x2000+4*i).toString(16).toUpperCase()+'');\n"
                            "fe_type[i] = eval('Json.ID_0x'+(0x2000+4*i+1).toString(16).toUpperCase()+'');\n"
                            "fe_st[i] = eval('Json.ID_0x'+(0x2000+4*i+2).toString(16).toUpperCase()+'');\n"
                            "fe_end[i] = eval('Json.ID_0x'+(0x2000+4*i+3).toString(16).toUpperCase()+'');                                    \n"
                        "}\n"
                        "for(var i=0; i<6; i++)\n"
                        "{\n"
                            "if(pr_baud[i] != fe_baud[i])\n"
                            "{\n"
                                "if(eval('Json.ID_0x'+(0x2000+i*4).toString(16).toUpperCase()+'')==9600){\n"
                                    "eval('$(\\'COM_BAUD'+i+'\\').options[0].selected=true;');\n"
                                "}else if(eval('Json.ID_0x'+(0x2000+i*4).toString(16).toUpperCase()+'')==19200){\n"
                                    "eval('$(\\'COM_BAUD'+i+'\\').options[1].selected=true;');\n"
                                "}else if(eval('Json.ID_0x'+(0x2000+i*4).toString(16).toUpperCase()+'')==38400){\n"
                                    "eval('$(\\'COM_BAUD'+i+'\\').options[2].selected=true;');\n"
                                "}\n"
                            "}\n"
                            "if(i<5){\n"
                                "if(pr_type[i] != fe_type[i])\n"
                                "{\n"
                                    "if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==1){\n"
                                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[0].selected=true;');\n"
                                    "}else if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==2){\n"
                                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[1].selected=true;');\n"
                                    "}else if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==3){\n"
                                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[2].selected=true;');\n"
                                    "}else if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==4){\n"
                                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[3].selected=true;');\n"
                                    "}else if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==5){\n"
                                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[4].selected=true;');\n"
                                    "}else if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==6){\n"
                                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[5].selected=true;');\n"
                                    "}else if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==8){\n"
                                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[6].selected=true;');\n"
                                    "}else if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==10){\n"
                                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[7].selected=true;');\n"
                                    "}\n"
                                "}    \n"
                                "var temp = 0;\n"
                                "if(pr_st[i] != fe_st[i])\n"
                                "{\n"
                                    "temp = eval('Json.ID_0x'+(0x2000+i*4+2).toString(16).toUpperCase()+'-1');\n"
                                    "eval('$(\\'COM_BEGIN_ID'+i+'\\').options['+temp+'].selected=true;');\n"
                                "}\n"
                                "if(pr_end[i] != fe_end[i])\n"
                                "{\n"
                                    "temp = eval('Json.ID_0x'+(0x2000+i*4+3).toString(16).toUpperCase()+'-1');\n"
                                    "eval('$(\\'COM_END_ID'+i+'\\').options['+temp+'].selected=true;');\n"
                                "}                 \n"
                            "}else{\n"
                                "if(pr_type[i] != fe_type[i])\n"
                                "{\n"
                                    "if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==0){\n"
                                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[0].selected=true;');\n"
                                    "}else if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==7){\n"
                                        "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[1].selected=true;');\n"
                                    "}                                    \n"
                                "}\n"
                                "var temp = 0;\n"
                                "if(pr_st[i] != fe_st[i])\n"
                                "{\n"
                                    "temp = eval('Json.ID_0x'+(0x2000+i*4+2).toString(16).toUpperCase()+'-1');\n"
                                    "eval('$(\\'COM_BEGIN_ID'+i+'\\').options['+temp+'].selected=true;');\n"
                                "}\n"
                            "}\n"
                        "}\n"
                        "show_tip_ex(7,'&nbsp;');\n"
                        "if(pr_baud[0]!=fe_baud[0] || pr_baud[1]!=fe_baud[1] || pr_baud[2]!=fe_baud[2] || pr_baud[3]!=fe_baud[3] || pr_baud[4]!=fe_baud[4] || pr_baud[5]!=fe_baud[5] || pr_type[0] != fe_type[0] || pr_type[1] != fe_type[1] || pr_type[2] != fe_type[2] || pr_type[3] != fe_type[3] || pr_type[4] != fe_type[4] || pr_type[5] != fe_type[5] || pr_st[0] != fe_st[0] || pr_st[1] != fe_st[1] || pr_st[2] != fe_st[2] || pr_st[3] != fe_st[3] || pr_st[4] != fe_st[4] || pr_st[5] != fe_st[5] || pr_end[0] != fe_end[0] || pr_end[1] != fe_end[1] || pr_end[2] != fe_end[2] || pr_end[3] != fe_end[3] || pr_end[4] != fe_end[4])\n"
                        "{setTimeout('show_tip_ex(7,lang.N58[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(7,lang.N59[language])',500);}\n"
                        "setTimeout('show_tip_ex(7,\\'&nbsp;\\')',2500);\n"
                    "}\n"
 				"else\n"
 				"{\n"
 					"var pr,fe;\n"
 					"eval('pr=$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value;');\n"
 					"eval('fe=Json.ID_0x0'+addr.toString(16).toUpperCase()+';');	\n"
 					"if(pr!=fe) eval('$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value=Json.ID_0x0'+addr.toString(16).toUpperCase()+';');\n"
 					"if(addr == 0x350){\n"
 			    		"show_tip_ex(10,'&nbsp;');\n"
 			    		"if(pr==fe){setTimeout('show_tip_ex(10,lang.N59[language])',500);}\n"
 			    		"else {setTimeout('show_tip_ex(10,lang.N58[language])',500);}\n"
 				           "setTimeout('show_tip_ex(10,\\'&nbsp;\\')',2500); \n"
 	            	"}else if(addr == 0x351){\n"
 			    		"show_tip_ex(11,'&nbsp;');\n"
 			    		"if(pr==fe){setTimeout('show_tip_ex(11,lang.N59[language])',500);}\n"
 			    		"else {setTimeout('show_tip_ex(11,lang.N58[language])',500);}\n"
 				           "setTimeout('show_tip_ex(11,\\'&nbsp;\\')',2500);  \n"
 	            	"}else if(addr == 0x352){\n"
 			    		"show_tip_ex(12,'&nbsp;');\n"
 			    		"if(pr==fe){setTimeout('show_tip_ex(12,lang.N59[language])',500);}\n"
 			    		"else {setTimeout('show_tip_ex(12,lang.N58[language])',500);}\n"
 				           "setTimeout('show_tip_ex(12,\\'&nbsp;\\')',2500);  \n"
 	            	"}else if(addr == 0x353){\n"
 			    		"show_tip_ex(13,'&nbsp;');\n"
 			    		"if(pr==fe){setTimeout('show_tip_ex(13,lang.N59[language])',500);}\n"
 			    		"else {setTimeout('show_tip_ex(13,lang.N58[language])',500);}\n"
 				           "setTimeout('show_tip_ex(13,\\'&nbsp;\\')',2500);   \n"
 	            	"}else if(addr == 0x354){\n"
 			    		"show_tip_ex(14,'&nbsp;');\n"
 			    		"if(pr==fe){setTimeout('show_tip_ex(14,lang.N59[language])',500);}\n"
 			    		"else {setTimeout('show_tip_ex(14,lang.N58[language])',500);}\n"
 				           "setTimeout('show_tip_ex(14,\\'&nbsp;\\')',2500); \n"
 	            	"}else if(addr == 0x355){\n"
 			    		"show_tip_ex(15,'&nbsp;');\n"
 			    		"if(pr==fe){setTimeout('show_tip_ex(15,lang.N59[language])',500);}\n"
 			    		"else {setTimeout('show_tip_ex(15,lang.N58[language])',500);}\n"
 				           "setTimeout('show_tip_ex(15,\\'&nbsp;\\')',2500);  \n"
 	            	"} \n"
 				"}\n"
 			"}\n"
 		"};\n"
 		"xmlhttp.open('GET',url,true);\n"
 		"xmlhttp.send();   		\n"
 	"}\n"
 	"function stringToHex(str){\n"
 		"var val=0;  \n"
 		"for(var i = 0; i < str.length; i++){\n"
 			"if(val == 0)  \n"
 				"val = str.charCodeAt(i).toString(16);\n"
 			"else\n"
 				"val += str.charCodeAt(i).toString(16);\n"
 		"}\n"
 		"return val;\n"
 	"} \n"
 	"function doSubmit(obj)\n"
 	"{\n"
            "var URL='a_006.html?';\n"
            "var readBack=[0,0,0,0,0,0,0,0,0,0,0,0];\n"
            "var readCnt=0;\n"
            "switch(obj.id)\n"
            "{\n"
            	"case 'N500':\n"
 		           "var ip=$('IP').value.split('.');\n"
 				"var submask=$('SUBMASK').value.split('.');\n"
 				"var gateway=$('GATEWAY').value.split('.');\n"
 				"var mac=$('MAC').value.split(':');\n"
 				"URL=URL+'&0x0157='+ip[0]+'&0x0158='+ip[1]+'&0x0159='+ip[2]+'&0x015A='+ip[3];\n"
 				"URL=URL+'&0x015B='+submask[0]+'&0x015C='+submask[1]+'&0x015D='+submask[2]+'&0x015E='+submask[3];\n"
 				"URL=URL+'&0x015F='+gateway[0]+'&0x0160='+gateway[1]+'&0x0161='+gateway[2]+'&0x0162='+gateway[3];\n"
 				"URL=URL+'&0x0230='+parseInt(mac[0],16)+'&0x0231='+parseInt(mac[1],16)+'&0x0232='+parseInt(mac[2],16)+'&0x0233='+parseInt(mac[3],16)+'&0x0234='+parseInt(mac[4],16)+'&0x0235='+parseInt(mac[5],16);\n"
 				"readBack=0x0157;\n"
            		"break;\n"
            	"case 'N502':\n"
 				"URL=URL+'&0x0164='+$('ID_0x0164').value;\n"
 				"URL=URL+'&0x0165='+$('ID_0x0165').value;\n"
 				"readBack=0x0164;\n"
 				"break;\n"
 			"case 'N503':\n"
 					//BMS通讯方式、故障干接点、告警干接点
 				"var bmsmode;\n"
 				"var bmsfcont;\n"
 				"var bmswcont;\n"
 				"if($('BMSM0').checked)bmsmode=$('BMSM0').value;\n"
 				"if($('BMSM1').checked)bmsmode=$('BMSM1').value;\n"
 				"if($('BMSM2').checked)bmsmode=$('BMSM2').value;\n"
 				"if($('BMSFC0').checked)bmsfcont=$('BMSFC0').value;\n"
 				"if($('BMSFC1').checked)bmsfcont=$('BMSFC1').value;\n"
 				"if($('BMSFC2').checked)bmsfcont=$('BMSFC2').value;\n"
 				"if($('BMSWC0').checked)bmswcont=$('BMSWC0').value;\n"
 				"if($('BMSWC1').checked)bmswcont=$('BMSWC1').value;\n"
 				"if($('BMSWC2').checked)bmswcont=$('BMSWC2').value;\n"
 				"URL=URL+'&0x0166='+bmsmode+'&0x0167='+bmsfcont+'&0x0168='+bmswcont;\n"
 				"readBack=0x0166;\n"
 				"break;\n"
 			"case 'N504':\n"
 				"URL=URL+'&0x016A='+$('ID_0x016A').value\n"
 				"+'&0x016B='+$('ID_0x016B').value\n"
 				"+'&0x016C='+$('ID_0x016C').value\n"
 				"+'&0x016D='+$('ID_0x016D').value\n"
 				"+'&0x016E='+$('ID_0x016E').value;\n"
 				"readBack=0x016A;\n"
 				"break;\n"
 			"case 'N505':\n"
 				"URL=URL+'&0x0350='+$('ID_0x0350').value;\n"
 				"readBack=0x0350;\n"
 				"break;\n"
 			"case 'N506':\n"
 				"URL=URL+'&0x0351='+$('ID_0x0351').value;\n"
 				"readBack=0x0351;\n"
 				"break;\n"
 			"case 'N507':\n"
 				"URL=URL+'&0x0352='+$('ID_0x0352').value;\n"
 				"readBack=0x0352;\n"
 				"break;\n"
 			"case 'N508':\n"
 				"URL=URL+'&0x0353='+$('ID_0x0353').value;\n"
 				"readBack=0x0353;\n"
 				"break;\n"
 			"case 'N509':\n"
 				"URL=URL+'&0x0354='+$('ID_0x0354').value;\n"
 				"readBack=0x0354;\n"
 				"break;\n"
 			"case 'N510':\n"
 				"URL=URL+'&0x0355='+$('ID_0x0355').value;\n"
 				"readBack=0x0355;\n"
 				"break;\n"
                "case 'N511':\n"
                    "var baud, type, st, end; \n"
                    "for(var i=0; i<6; i++)\n"
                    "{\n"
                        "if(i<5)\n"
                        "{\n"
                            "if(eval('$(\\'COM_BAUD'+i+'\\').selectedIndex;')==0) baud=9600;\n"
                            "else if(eval('$(\\'COM_BAUD'+i+'\\').selectedIndex;')==1) baud=19200;\n"
                            "else if(eval('$(\\'COM_BAUD'+i+'\\').selectedIndex;')==2) baud=38400;\n"
                            "eval('URL=URL+\\'&0x'+(0x2000+4*i).toString(16).toUpperCase()+'=\\'+baud;');\n"
                            "if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==0) type=1;\n"
                            "else if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==1) type=2;\n"
                            "else if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==2) type=3;\n"
                            "else if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==3) type=4;\n"
                            "else if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==4) type=5;\n"
                            "else if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==5) type=6;  \n"
                            "else if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==6) type=8; \n"
                            "else if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==7) type=10; \n"
                            "eval('URL=URL+\\'&0x'+(0x2000+4*i+1).toString(16).toUpperCase()+'=\\'+type;');\n"
                            "st = eval('$(\\'COM_BEGIN_ID'+i+'\\').selectedIndex;')+1;\n"
                            "eval('URL=URL+\\'&0x'+(0x2000+4*i+2).toString(16).toUpperCase()+'=\\'+st;');\n"
                            "end = eval('$(\\'COM_END_ID'+i+'\\').selectedIndex;')+1;\n"
                            "eval('URL=URL+\\'&0x'+(0x2000+4*i+3).toString(16).toUpperCase()+'=\\'+end;');             \n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "if(eval('$(\\'COM_BAUD'+i+'\\').selectedIndex;')==0) baud=9600;\n"
                            "else if(eval('$(\\'COM_BAUD'+i+'\\').selectedIndex;')==1) baud=19200;\n"
                            "else if(eval('$(\\'COM_BAUD'+i+'\\').selectedIndex;')==2) baud=38400;  \n"
                            "eval('URL=URL+\\'&0x'+(0x2000+4*i).toString(16).toUpperCase()+'=\\'+baud;');\n"
                            "if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==0) type=0;\n"
                            "else if(eval('$(\\'COM_DEVICE_TYPE'+i+'\\').selectedIndex;')==1) type=7;  \n"
                            "eval('URL=URL+\\'&0x'+(0x2000+4*i+1).toString(16).toUpperCase()+'=\\'+type;');   \n"
                            "st = eval('$(\\'COM_BEGIN_ID'+i+'\\').selectedIndex;')+1;\n"
                            "eval('URL=URL+\\'&0x'+(0x2000+4*i+2).toString(16).toUpperCase()+'=\\'+st;'); \n"
                            "eval('URL=URL+\\'&0x'+(0x2000+4*i+3).toString(16).toUpperCase()+'=\\'+0;');                \n"
                        "}\n"
                    "}\n"
                    "readBack=0x2000;\n"
                "break;\n"
            	"case 'N512':\n"
 		           "var ip=$('IP2').value.split('.');\n"
 				"var submask=$('SUBMASK2').value.split('.');\n"
 				"var gateway=$('GATEWAY2').value.split('.');\n"
 				"var mac=$('MAC2').value.split(':');\n"
 				"URL=URL+'&0x0210='+ip[0]+'&0x0211='+ip[1]+'&0x0212='+ip[2]+'&0x0213='+ip[3];\n"
 				"URL=URL+'&0x0214='+submask[0]+'&0x0215='+submask[1]+'&0x0216='+submask[2]+'&0x0217='+submask[3];\n"
 				"URL=URL+'&0x0218='+gateway[0]+'&0x0219='+gateway[1]+'&0x021A='+gateway[2]+'&0x021B='+gateway[3];\n"
 				"URL=URL+'&0x0240='+parseInt(mac[0],16)+'&0x0241='+parseInt(mac[1],16)+'&0x0242='+parseInt(mac[2],16)+'&0x0243='+parseInt(mac[3],16)+'&0x0244='+parseInt(mac[4],16)+'&0x0245='+parseInt(mac[5],16);\n"
 				"readBack=0x0210;\n"
            		"break;\n"
            "}\n"
"\n"
            "URL=URL+'&time='+Math.random();\n"
             //alert(URL);     
"\n"
            "function success()\n"
            "{\n"
             "if(readBack >= 0x157 && readBack <= 0x162)\n"
             "{\n"
 	     		"show_tip_ex(1,'&nbsp;');\n"
 	    		"setTimeout('read_back('+readBack+')', 100);\n"
 		           "setTimeout('show_tip_ex(1,\\'&nbsp;\\')',2500);               		\n"
             "}\n"
             "else if(readBack >= 0x210 && readBack <= 0x21B)\n"
             "{\n"
 	     		"show_tip_ex(8,'&nbsp;');\n"
 	    		"setTimeout('read_back('+readBack+')', 100);\n"
 		           "setTimeout('show_tip_ex(8,\\'&nbsp;\\')',2500);               		\n"
             "}\n"
             "else if(readBack == 0x163)\n"
             "{\n"
 	     		"show_tip_ex(2,'&nbsp;');\n"
 	    		"setTimeout('read_back('+readBack+')', 100);\n"
 		           "setTimeout('show_tip_ex(2,\\'&nbsp;\\')',2500);               		\n"
             "}\n"
             "else if(readBack >= 0x164 && readBack <= 0x165)\n"
             "{\n"
 	     		"show_tip_ex(3,'&nbsp;');\n"
 	    		"setTimeout('read_back('+readBack+')', 100);\n"
 		           "setTimeout('show_tip_ex(3,\\'&nbsp;\\')',2500);               		\n"
             "}\n"
             "else if(readBack >= 0x166 && readBack <= 0x168)\n"
             "{\n"
 	     		"show_tip_ex(4,'&nbsp;');\n"
 	    		"setTimeout('read_back('+readBack+')', 100);\n"
 		           "setTimeout('show_tip_ex(4,\\'&nbsp;\\')',2500);               		\n"
             "}\n"
             "else if(readBack >= 0x16A && readBack <= 0x16E)\n"
             "{\n"
 	     		"show_tip_ex(5,'&nbsp;');\n"
 	    		"setTimeout('read_back('+readBack+')', 100);\n"
 		           "setTimeout('show_tip_ex(5,\\'&nbsp;\\')',2500);               		\n"
             "}\n"
             "else if(readBack >= 0x350 && readBack <= 0x355)\n"
             "{\n"
 	     			//show_tip_ex(6,'&nbsp;');
 	    		"setTimeout('read_back('+readBack+')', 100);\n"
 		            //setTimeout('show_tip_ex(6,\\'&nbsp;\\')',2500);               		
             "}\n"
             "else if(readBack >= 0x2000 && readBack <= 0x2017)\n"
 	     	"{\n"
 				"show_tip_ex(7,'&nbsp;');\n"
 	    		"setTimeout('read_back('+readBack+')', 100);\n"
 		           "setTimeout('show_tip_ex(7,\\'&nbsp;\\')',2500); \n"
             "}\n"
            "}\n"
"\n"
             //测试
             //success();  
"\n"
 		"sendHttpReq(URL, success);            \n"
 	"}\n"
 	"function radiocontrol()\n"
 	"{\n"
            "if($('BMSM0').checked)\n"
            "{\n"
                "$('BMSFC0').disabled=true;\n"
                "$('BMSFC1').disabled=true;\n"
                "$('BMSFC2').disabled=true;\n"
                "$('BMSFC0').checked=true;\n"
                "$('BMSFC1').checked=false;\n"
                "$('BMSFC2').checked=false;\n"
            "}\n"
            "else\n"
            "{\n"
                "$('BMSFC0').disabled=false;\n"
                "$('BMSFC1').disabled=false;\n"
                "$('BMSFC2').disabled=false;\n"
            "}\n"
            "if($('BMSM0').checked)\n"
            "{\n"
                "$('BMSWC0').disabled=true;\n"
                "$('BMSWC1').disabled=true;\n"
                "$('BMSWC2').disabled=true;\n"
                "$('BMSWC0').checked=true;\n"
                "$('BMSWC1').checked=false;\n"
                "$('BMSWC2').checked=false;\n"
            "}\n"
            "else\n"
            "{\n"
                "$('BMSWC0').disabled=false;\n"
                "$('BMSWC1').disabled=false;\n"
                "$('BMSWC2').disabled=false;\n"
            "}\n"
 	"}\n"
 	"function doSetValue(Json)\n"
 	"{\n"
 		"$('IP').value=String(Json.ID_0x0157)+'.'+String(Json.ID_0x0158)+'.'+String(Json.ID_0x0159)+'.'+String(Json.ID_0x015A);\n"
 		"$('SUBMASK').value=String(Json.ID_0x015B)+'.'+String(Json.ID_0x015C)+'.'+String(Json.ID_0x015D)+'.'+String(Json.ID_0x015E);\n"
 		"$('GATEWAY').value=String(Json.ID_0x015F)+'.'+String(Json.ID_0x0160)+'.'+String(Json.ID_0x0161)+'.'+String(Json.ID_0x0162);\n"
 		"$('MAC').value=String(str_pad(Json.ID_0x0230.toString(16)))+':'+String(str_pad(Json.ID_0x0231.toString(16)))+':'+String(str_pad(Json.ID_0x0232.toString(16)))+':'+String(str_pad(Json.ID_0x0233.toString(16)))+':'+String(str_pad(Json.ID_0x0234.toString(16)))+':'+String(str_pad(Json.ID_0x0235.toString(16)));\n"
 		"$('IP2').value=String(Json.ID_0x0210)+'.'+String(Json.ID_0x0211)+'.'+String(Json.ID_0x0212)+'.'+String(Json.ID_0x0213);\n"
 		"$('SUBMASK2').value=String(Json.ID_0x0214)+'.'+String(Json.ID_0x0215)+'.'+String(Json.ID_0x0216)+'.'+String(Json.ID_0x0217);\n"
 		"$('GATEWAY2').value=String(Json.ID_0x0218)+'.'+String(Json.ID_0x0219)+'.'+String(Json.ID_0x021A)+'.'+String(Json.ID_0x021B);\n"
 		"$('MAC2').value=String(str_pad(Json.ID_0x0240.toString(16)))+':'+String(str_pad(Json.ID_0x0241.toString(16)))+':'+String(str_pad(Json.ID_0x0242.toString(16)))+':'+String(str_pad(Json.ID_0x0243.toString(16)))+':'+String(str_pad(Json.ID_0x0244.toString(16)))+':'+String(str_pad(Json.ID_0x0245.toString(16)));\n"
 		"if(Json.ID_0x020B == 1){\n"
 			"$('MAC').disabled = true;  \n"
 			"$('MAC2').disabled = true;  \n"
 		"}else{\n"
 			"$('MAC').disabled = false;\n"
 			"$('MAC2').disabled = false;\n"
 		"}\n"
"\n"
 		"$('ID_0x0164').value=Json.ID_0x0164;\n"
 		"$('ID_0x0165').value=Json.ID_0x0165;\n"
 		"$('ID_0x016A').value=Json.ID_0x016A;\n"
 		"$('ID_0x016B').value=Json.ID_0x016B;\n"
 		"$('ID_0x016C').value=Json.ID_0x016C;\n"
 		"$('ID_0x016D').value=Json.ID_0x016D;\n"
 		"$('ID_0x016E').value=Json.ID_0x016E;\n"
 		"$('ID_0x0350').value=Json.ID_0x0350;\n"
 		"$('ID_0x0351').value=Json.ID_0x0351;\n"
 		"$('ID_0x0352').value=Json.ID_0x0352;\n"
 		"$('ID_0x0353').value=Json.ID_0x0353;\n"
 		"$('ID_0x0354').value=Json.ID_0x0354;\n"
 		"$('ID_0x0355').value=Json.ID_0x0355;\n"
 		"temp_IP=$('IP').value;\n"
 		"temp_MASK=$('SUBMASK').value;\n"
 		"temp_GATE=$('GATEWAY').value;\n"
 		"if(Json.ID_0x0166==0)\n"
 		"{\n"
 			"$('BMSM0').checked=true;\n"
 			"$('BMSM1').checked=false;\n"
 			"$('BMSM2').checked=false;\n"
                "$('BMSFC0').disabled=true;\n"
                "$('BMSFC1').disabled=true;\n"
                "$('BMSFC2').disabled=true;\n"
                "$('BMSWC0').disabled=true;\n"
                "$('BMSWC1').disabled=true;\n"
                "$('BMSWC2').disabled=true;\n"
 		"}\n"
 		"else if(Json.ID_0x0166==1)\n"
 		"{\n"
 			"$('BMSM0').checked=false;\n"
 			"$('BMSM1').checked=true;\n"
 			"$('BMSM2').checked=false;\n"
 		"}\n"
 		"else if(Json.ID_0x0166==2)\n"
 		"{\n"
 			"$('BMSM0').checked=false;\n"
 			"$('BMSM1').checked=false;\n"
 			"$('BMSM2').checked=true;\n"
 		"}\n"
 		"if(Json.ID_0x0167==0)\n"
 		"{\n"
 			"$('BMSFC0').checked=true;\n"
 			"$('BMSFC1').checked=false;\n"
 			"$('BMSFC2').checked=false;\n"
 		"}\n"
 		"else if(Json.ID_0x0167==1)\n"
 		"{\n"
 			"$('BMSFC0').checked=false;\n"
 			"$('BMSFC1').checked=true;\n"
 			"$('BMSFC2').checked=false;\n"
 		"}\n"
 		"else if(Json.ID_0x0167==2)\n"
 		"{\n"
 			"$('BMSFC0').checked=false;\n"
 			"$('BMSFC1').checked=false;\n"
 			"$('BMSFC2').checked=true;\n"
 		"}\n"
 		"if(Json.ID_0x0168==0)\n"
 		"{\n"
 			"$('BMSWC0').checked=true;\n"
 			"$('BMSWC1').checked=false;\n"
 			"$('BMSWC2').checked=false;\n"
 		"}\n"
 		"else if(Json.ID_0x0168==1)\n"
 		"{\n"
 			"$('BMSWC0').checked=false;\n"
 			"$('BMSWC1').checked=true;\n"
 			"$('BMSWC2').checked=false;\n"
 		"}\n"
 		"else if(Json.ID_0x0168==2)\n"
 		"{\n"
 			"$('BMSWC0').checked=false;\n"
 			"$('BMSWC1').checked=false;\n"
 			"$('BMSWC2').checked=true;\n"
 		"}\n"
             //通讯口
            "for(var i=0;i<5;i++)\n"
            "{\n"
                "if(eval('Json.ID_0x'+(0x2000+i*4).toString(16).toUpperCase()+'')==9600){\n"
                    "eval('$(\\'COM_BAUD'+i+'\\').options[0].selected=true;');\n"
                "}else if(eval('Json.ID_0x'+(0x2000+i*4).toString(16).toUpperCase()+'')==19200){\n"
                    "eval('$(\\'COM_BAUD'+i+'\\').options[1].selected=true;');\n"
                "}else if(eval('Json.ID_0x'+(0x2000+i*4).toString(16).toUpperCase()+'')==38400){\n"
                    "eval('$(\\'COM_BAUD'+i+'\\').options[2].selected=true;');\n"
                "}\n"
                "if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==1){\n"
                    "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[0].selected=true;');\n"
                "}else if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==2){\n"
                    "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[1].selected=true;');\n"
                "}else if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==3){\n"
                    "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[2].selected=true;');\n"
                "}else if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==4){\n"
                    "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[3].selected=true;');\n"
                "}else if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==5){\n"
                    "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[4].selected=true;');\n"
                "}else if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==6){\n"
                    "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[5].selected=true;');\n"
                "}else if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==8){\n"
                    "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[6].selected=true;');\n"
                "}else if(eval('Json.ID_0x'+(0x2000+i*4+1).toString(16).toUpperCase()+'')==10){\n"
                    "eval('$(\\'COM_DEVICE_TYPE'+i+'\\').options[7].selected=true;');\n"
                "}\n"
                "var temp = 0;\n"
                "temp = eval('Json.ID_0x'+(0x2000+i*4+2).toString(16).toUpperCase()+'-1');\n"
                "eval('$(\\'COM_BEGIN_ID'+i+'\\').options['+temp+'].selected=true;');\n"
                "temp = eval('Json.ID_0x'+(0x2000+i*4+3).toString(16).toUpperCase()+'-1');\n"
                "eval('$(\\'COM_END_ID'+i+'\\').options['+temp+'].selected=true;');\n"
            "}\n"
"\n"
            "if(Json.ID_0x2014==9600){\n"
                "$('COM_BAUD5').options[0].selected=true;\n"
            "}else if(Json.ID_0x2014==19200){\n"
                "$('COM_BAUD5').options[1].selected=true;\n"
            "}else if(Json.ID_0x2014==38400){\n"
                "$('COM_BAUD5').options[2].selected=true;\n"
            "}\n"
"\n"
            "if(Json.ID_0x2015==0){\n"
                "$('COM_DEVICE_TYPE5').options[0].selected=true;\n"
                "$('COM_BEGIN_ID5').disabled = true;\n"
                "$('COM_END_ID5').disabled = true;            \n"
            "}else if(Json.ID_0x2015==7){\n"
                "$('COM_DEVICE_TYPE5').options[1].selected=true;\n"
                "$('COM_BEGIN_ID5').disabled = false;\n"
                "$('COM_END_ID5').disabled = true; \n"
            "}\n"
            "var temp = 0;\n"
            "temp = Json.ID_0x2016-1;\n"
            "eval('$(\\'COM_BEGIN_ID5\\').options['+temp+'].selected=true;');    \n"
"\n"
 		"if(Json.ID_0x0390==0){$('tPcs').style.display='none';$('bPcs').style.display='none';}\n"
 		"if(Json.ID_0x0391==0){$('tPv').style.display='none';$('bPv').style.display='none';}\n"
 		"if(Json.ID_0x0392==0){$('tDcdc').style.display='none';$('bDcdc').style.display='none';}\n"
 		"if(Json.ID_0x0393==0){$('tPvs').style.display='none';$('bPvs').style.display='none';}\n"
 			//$('tPvs').style.display='none';$('bPvs').style.display='none';
 		"if(Json.ID_0x0394==0){$('tBms').style.display='none';$('bBms').style.display='none';}\n"
 			//if(Json.ID_0x0395==0){$('tAmmeter').style.display='none';$('bAmmeter').style.display='none';}
 		"$('tAmmeter').style.display='none';$('bAmmeter').style.display='none';\n"
 	"}\n"
"\n"
 	"function show_tip_ex(id, obj){eval('$(\\'tip'+id+'\\').innerHTML=obj;');eval('$(\\'tip'+id+'\\').style.color=\\'#F00\\';');}\n"
 	"function IPverify(obj)\n"
 	"{\n"
 			//需要将 '\\'转换为'\\\\'
 		"var reg=/^(\\d{1,2}|1\\d\\d|2[0-4]\\d|25[0-5])(\\.(\\d{1,2}|1\\d\\d|2[0-4]\\d|25[0-5])){3}$/;\n"
 		"if(!obj.value.match(reg))\n"
 		"{\n"
 			"$('N500').disabled=true;\n"
 			"obj.style.color='#F00';\n"
 			"show_tip_ex(1,lang.N53[language]);\n"
 		"}\n"
 		"else\n"
 		"{\n"
 			"$('N500').disabled=false;\n"
 			"obj.style.color='#000';\n"
 			"show_tip_ex(1,'&nbsp;');\n"
 		"}\n"
 	"}\n"
 	"function IPverify2(obj)\n"
 	"{\n"
 			//需要将 '\\'转换为'\\\\'
 		"var reg=/^(\\d{1,2}|1\\d\\d|2[0-4]\\d|25[0-5])(\\.(\\d{1,2}|1\\d\\d|2[0-4]\\d|25[0-5])){3}$/;\n"
 		"if(!obj.value.match(reg))\n"
 		"{\n"
 			"$('N512').disabled=true;\n"
 			"obj.style.color='#F00';\n"
 			"show_tip_ex(8,lang.N53[language]);\n"
 		"}\n"
 		"else\n"
 		"{\n"
 			"$('N512').disabled=false;\n"
 			"obj.style.color='#000';\n"
 			"show_tip_ex(8,'&nbsp;');\n"
 		"}\n"
 	"}\n"
 	"function MACverify(obj)\n"
 	"{\n"
 		"var reg=/[a-fA-F\\d]{2}:[a-fA-F\\d]{2}:[a-fA-F\\d]{2}:[a-fA-F\\d]{2}:[a-fA-F\\d]{2}:[a-fA-F\\d]{2}/;\n"
 		"if(!obj.value.match(reg))\n"
 		"{\n"
 			"$('N500').disabled=true;\n"
 			"obj.style.color='#F00';\n"
 			"show_tip_ex(1,lang.N53[language]);\n"
 		"}\n"
 		"else\n"
 		"{\n"
 			"$('N500').disabled=false;\n"
 			"obj.style.color='#000';\n"
 			"show_tip_ex(1,'&nbsp;');\n"
 		"}\n"
 	"}\n"
 	"function MAC2verify(obj)\n"
 	"{\n"
 		"var reg=/[a-fA-F\\d]{2}:[a-fA-F\\d]{2}:[a-fA-F\\d]{2}:[a-fA-F\\d]{2}:[a-fA-F\\d]{2}:[a-fA-F\\d]{2}/;\n"
 		"if(!obj.value.match(reg))\n"
 		"{\n"
 			"$('N512').disabled=true;\n"
 			"obj.style.color='#F00';\n"
 			"show_tip_ex(8,lang.N53[language]);\n"
 		"}\n"
 		"else\n"
 		"{\n"
 			"$('N512').disabled=false;\n"
 			"obj.style.color='#000';\n"
 			"show_tip_ex(8,'&nbsp;');\n"
 		"}\n"
 	"}\n"
 	"var err_tip3=[0,0];\n"
 	"var err_tip5=[0,0,0,0,0];\n"
 	"var err_tip6=[0,0,0,0,0,0];\n"
 	"function Verify(obj)\n"
 	"{			\n"
 		"var reg=/^[1-9]\\d*$/;\n"
 		"var range=parseInt(obj.value);\n"
 		"switch(obj.id)\n"
 		"{\n"
 			"case 'ID_0x0164':\n"
 				"if(!obj.value.match(reg)){$('N502').disabled=true;obj.style.color='#F00';show_tip_ex(3,lang.N53[language]);err_tip3[0]=1;}\n"
 				"else if(range<1||range>247){$('N502').disabled=true;obj.style.color='#F00';show_tip_ex(3,lang.N54[language]);err_tip3[0]=1;}\n"
 				"else if((err_tip3[0]|err_tip3[1])==0){$('N502').disabled=false;obj.style.color='#000';show_tip_ex(3,'&nbsp;');}\n"
 				"else{\n"
 					"err_tip3[0]=0;obj.style.color='#000';\n"
 					"if((err_tip3[0]|err_tip3[1])==0){$('N502').disabled=false;show_tip_ex(3,'&nbsp;');}\n"
 				"}\n"
 			"break;\n"
 			"case 'ID_0x0165':\n"
 				"if(!obj.value.match(reg)){$('N502').disabled=true;obj.style.color='#F00';show_tip_ex(3,lang.N53[language]);err_tip3[1]=1;}\n"
 				"else if(range<1||range>65535){$('N502').disabled=true;obj.style.color='#F00';show_tip_ex(3,lang.N54[language]);err_tip3[1]=1;}\n"
 				"else {\n"
 					"err_tip3[1]=0;obj.style.color='#000';\n"
 					"if((err_tip3[0]|err_tip3[1])==0){$('N502').disabled=false;show_tip_ex(3,'&nbsp;');}\n"
 				"}\n"
 			"break;\n"
 			"case 'ID_0x016A':\n"
 				"if(!obj.value.match(reg)){$('N504').disabled=true;obj.style.color='#F00';show_tip_ex(5,lang.N53[language]);err_tip5[0]=1;}\n"
 				"else if(range<1||range>65535){$('N504').disabled=true;obj.style.color='#F00';show_tip_ex(5,lang.N54[language]);err_tip5[0]=1;}\n"
 				"else if((err_tip5[0]|err_tip5[1]|err_tip5[2]|err_tip5[3]|err_tip5[4])==0){$('N504').disabled=false;obj.style.color='#000';show_tip_ex(5,'&nbsp;');}\n"
 				"else{\n"
 					"err_tip5[0]=0;obj.style.color='#000';\n"
 					"if((err_tip5[0]|err_tip5[1]|err_tip5[2]|err_tip5[3]|err_tip5[4])==0){$('N504').disabled=false;show_tip_ex(5,'&nbsp;');}\n"
 				"}\n"
 			"break;\n"
 			"case 'ID_0x016B':\n"
 				"if(!obj.value.match(reg)){$('N504').disabled=true;obj.style.color='#F00';show_tip_ex(5,lang.N53[language]);err_tip5[1]=1;}\n"
 				"else if(range<1||range>255){$('N504').disabled=true;obj.style.color='#F00';show_tip_ex(5,lang.N54[language]);err_tip5[1]=1;}\n"
 				"else if((err_tip5[0]|err_tip5[1]|err_tip5[2]|err_tip5[3]|err_tip5[4])==0){$('N504').disabled=false;obj.style.color='#000';show_tip_ex(5,'&nbsp;');}\n"
 				"else{\n"
 					"err_tip5[1]=0;obj.style.color='#000';\n"
 					"if((err_tip5[0]|err_tip5[1]|err_tip5[2]|err_tip5[3]|err_tip5[4])==0){$('N504').disabled=false;show_tip_ex(5,'&nbsp;');}\n"
 				"}\n"
 			"break;\n"
 			"case 'ID_0x016C':\n"
 				"if(!obj.value.match(reg)){$('N504').disabled=true;obj.style.color='#F00';show_tip_ex(5,lang.N53[language]);err_tip5[2]=1;}\n"
 				"else if(range<1||range>255){$('N504').disabled=true;obj.style.color='#F00';show_tip_ex(5,lang.N54[language]);err_tip5[2]=1;}\n"
 				"else if((err_tip5[0]|err_tip5[1]|err_tip5[2]|err_tip5[3]|err_tip5[4])==0){$('N504').disabled=false;obj.style.color='#000';show_tip_ex(5,'&nbsp;');}\n"
 				"else{\n"
 					"err_tip5[2]=0;obj.style.color='#000';\n"
 					"if((err_tip5[0]|err_tip5[1]|err_tip5[2]|err_tip5[3]|err_tip5[4])==0){$('N504').disabled=false;show_tip_ex(5,'&nbsp;');}\n"
 				"}\n"
 			"break;\n"
 			"case 'ID_0x016D':\n"
 				"if(!obj.value.match(reg)){$('N504').disabled=true;obj.style.color='#F00';show_tip_ex(5,lang.N53[language]);err_tip5[3]=1;}\n"
 				"else if(range<1||range>32767){$('N504').disabled=true;obj.style.color='#F00';show_tip_ex(5,lang.N54[language]);err_tip5[3]=1;}\n"
 				"else if((err_tip5[0]|err_tip5[1]|err_tip5[2]|err_tip5[3]|err_tip5[4])==0){$('N504').disabled=false;obj.style.color='#000';show_tip_ex(5,'&nbsp;');}\n"
 				"else{\n"
 					"err_tip5[3]=0;obj.style.color='#000';\n"
 					"if((err_tip5[0]|err_tip5[1]|err_tip5[2]|err_tip5[3]|err_tip5[4])==0){$('N504').disabled=false;show_tip_ex(5,'&nbsp;');}\n"
 				"}\n"
 			"break;\n"
 			"case 'ID_0x016E':\n"
 				"if(!obj.value.match(reg)){$('N504').disabled=true;obj.style.color='#F00';show_tip_ex(5,lang.N53[language]);err_tip5[4]=1;}\n"
 				"else if(range<1||range>32767){$('N504').disabled=true;obj.style.color='#F00';show_tip_ex(5,lang.N54[language]);err_tip5[4]=1;}\n"
 				"else if((err_tip5[0]|err_tip5[1]|err_tip5[2]|err_tip5[3]|err_tip5[4])==0){$('N504').disabled=false;obj.style.color='#000';show_tip_ex(5,'&nbsp;');}\n"
 				"else{\n"
 					"err_tip5[4]=0;obj.style.color='#000';\n"
 					"if((err_tip5[0]|err_tip5[1]|err_tip5[2]|err_tip5[3]|err_tip5[4])==0){$('N504').disabled=false;show_tip_ex(5,'&nbsp;');}\n"
 				"}\n"
 			"break;\n"
 			"case 'ID_0x0350':\n"
 				"if(!obj.value.match(reg)){$('N505').disabled=true;obj.style.color='#F00';show_tip_ex(6,lang.N53[language]);err_tip6[0]=1;}\n"
 				"else if(range<1||range>60){$('N505').disabled=true;obj.style.color='#F00';show_tip_ex(6,lang.N54[language]);err_tip6[0]=1;}\n"
 				"else if((err_tip6[0]|err_tip6[1]|err_tip6[2]|err_tip6[3]|err_tip6[4]|err_tip6[5])==0){$('N505').disabled=false;obj.style.color='#000';show_tip_ex(5,'&nbsp;');}\n"
 				"else{\n"
 					"err_tip6[0]=0;obj.style.color='#000';$('N505').disabled=false;\n"
 					"if((err_tip6[0]|err_tip6[1]|err_tip6[2]|err_tip6[3]|err_tip6[4]|err_tip6[5])==0){show_tip_ex(6,'&nbsp;');}\n"
 				"}\n"
 			"break;\n"
 			"case 'ID_0x0351':\n"
 				"if(!obj.value.match(reg)){$('N506').disabled=true;obj.style.color='#F00';show_tip_ex(6,lang.N53[language]);err_tip6[1]=1;}\n"
 				"else if(range<1||range>60){$('N506').disabled=true;obj.style.color='#F00';show_tip_ex(6,lang.N54[language]);err_tip6[1]=1;}\n"
 				"else if((err_tip6[0]|err_tip6[1]|err_tip6[2]|err_tip6[3]|err_tip6[4]|err_tip6[5])==0){$('N506').disabled=false;obj.style.color='#000';show_tip_ex(5,'&nbsp;');}\n"
 				"else{\n"
 					"err_tip6[1]=0;obj.style.color='#000';$('N506').disabled=false;\n"
 					"if((err_tip6[0]|err_tip6[1]|err_tip6[2]|err_tip6[3]|err_tip6[4]|err_tip6[5])==0){show_tip_ex(6,'&nbsp;');}\n"
 				"}\n"
 			"break;\n"
 			"case 'ID_0x0352':\n"
 				"if(!obj.value.match(reg)){$('N507').disabled=true;obj.style.color='#F00';show_tip_ex(6,lang.N53[language]);err_tip6[2]=1;}\n"
 				"else if(range<1||range>30){$('N507').disabled=true;obj.style.color='#F00';show_tip_ex(6,lang.N54[language]);err_tip6[2]=1;}\n"
 				"else if((err_tip6[0]|err_tip6[1]|err_tip6[2]|err_tip6[3]|err_tip6[4]|err_tip6[5])==0){$('N507').disabled=false;obj.style.color='#000';show_tip_ex(5,'&nbsp;');}\n"
 				"else{\n"
 					"err_tip6[2]=0;obj.style.color='#000';$('N507').disabled=false;\n"
 					"if((err_tip6[0]|err_tip6[1]|err_tip6[2]|err_tip6[3]|err_tip6[4]|err_tip6[5])==0){show_tip_ex(6,'&nbsp;');}\n"
 				"}\n"
 			"break;\n"
 			"case 'ID_0x0353':\n"
 				"if(!obj.value.match(reg)){$('N508').disabled=true;obj.style.color='#F00';show_tip_ex(6,lang.N53[language]);err_tip6[3]=1;}\n"
 				"else if(range<1||range>50){$('N508').disabled=true;obj.style.color='#F00';show_tip_ex(6,lang.N54[language]);err_tip6[3]=1;}\n"
 				"else if((err_tip6[0]|err_tip6[1]|err_tip6[2]|err_tip6[3]|err_tip6[4]|err_tip6[5])==0){$('N508').disabled=false;obj.style.color='#000';show_tip_ex(5,'&nbsp;');}\n"
 				"else{\n"
 					"err_tip6[3]=0;obj.style.color='#000';$('N508').disabled=false;\n"
 					"if((err_tip6[0]|err_tip6[1]|err_tip6[2]|err_tip6[3]|err_tip6[4]|err_tip6[5])==0){show_tip_ex(6,'&nbsp;');}\n"
 				"}\n"
 			"break;\n"
 			"case 'ID_0x0354':\n"
 				"if(!obj.value.match(reg)){$('N509').disabled=true;obj.style.color='#F00';show_tip_ex(6,lang.N53[language]);err_tip6[4]=1;}\n"
 				"else if(range<1||range>60){$('N509').disabled=true;obj.style.color='#F00';show_tip_ex(6,lang.N54[language]);err_tip6[4]=1;}\n"
 				"else if((err_tip6[0]|err_tip6[1]|err_tip6[2]|err_tip6[3]|err_tip6[4]|err_tip6[5])==0){$('N509').disabled=false;obj.style.color='#000';show_tip_ex(5,'&nbsp;');}\n"
 				"else{\n"
 					"err_tip6[4]=0;obj.style.color='#000';$('N509').disabled=false;\n"
 					"if((err_tip6[0]|err_tip6[1]|err_tip6[2]|err_tip6[3]|err_tip6[4]|err_tip6[5])==0){show_tip_ex(6,'&nbsp;');}\n"
 				"}\n"
 			"break;\n"
 			"case 'ID_0x0355':\n"
 				"if(!obj.value.match(reg)){$('N510').disabled=true;obj.style.color='#F00';show_tip_ex(6,lang.N53[language]);err_tip6[5]=1;}\n"
 				"else if(range<1||range>12){$('N510').disabled=true;obj.style.color='#F00';show_tip_ex(6,lang.N54[language]);err_tip6[5]=1;}\n"
 				"else if((err_tip6[0]|err_tip6[1]|err_tip6[2]|err_tip6[3]|err_tip6[4]|err_tip6[5])==0){$('N505').disabled=false;obj.style.color='#000';show_tip_ex(5,'&nbsp;');}\n"
 				"else{\n"
 					"err_tip6[5]=0;obj.style.color='#000';$('N510').disabled=false;\n"
 					"if((err_tip6[0]|err_tip6[1]|err_tip6[2]|err_tip6[3]|err_tip6[4]|err_tip6[5])==0){show_tip_ex(6,'&nbsp;');}\n"
 				"}\n"
 			"break;\n"
 		"}		\n"
 	"}\n"
 "</script>\n"
"</html>\n"
};
#endif

