#ifndef _HTML_H_002_H_
#define _HTML_H_002_H_
static const char h_002[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<style type='text/css'>\n"
            "html{_overflow-y:scroll;}\n"
            "body{margin:0;padding:0;text-align:center;font-size:14px;font-family:'微软雅黑',Verdana,'宋体',sans-serif;min-width:867px;-moz-user-select:none;}\n"
            "img{vertical-align: top; display: block;}\n"
            ".title{margin:5px auto;width:80%;text-align:left;}\n"
            ".r1{margin:0 5px;height:1px;overflow:hidden;}\n"
            ".r2{margin:0 3px;height:1px;overflow:hidden;}\n"
            ".r3{margin:0 2px;height:1px;overflow:hidden;}\n"
            ".r4{margin:0 1px;height:2px;overflow:hidden;}\n"
            ".color{background-color:#F58E03;}\n"
            ".color2{background-color:#888;}\n"
            ".color3{background-color:#f00;}\n"
            ".color4{background-color:#fff200;}\n"
            ".content{height:24px;line-height:24px;padding-left:20px;font-size:24px;color:#EEE;text-align:left;}\n"
            ".blank{height:4px;overflow:hidden;}\n"
            ".btm_blank{height:15px;overflow:hidden;}\n"
            ".back_color{background-color:#efefff;}\n"
            ".back_high1{width:100%;height:80px;margin:0 auto;}\n"
            ".back_high2{width:100%;height:150px;margin:0 auto;}\n"
            ".line_long{height:2px;overflow:hidden;margin:2px auto;background-color:#ccc; width:90%;}\n"
            ".img_common{float:right;margin-right:12px;width:32px;height:32px;}\n"
            ".bg1{background:transparent url(i_037.png) no-repeat;}\n"
            ".bg2{background:transparent url(i_038.png) no-repeat;}\n"
            ".name{padding-left:10%;text-align:left;font-size:14px;font-weight:bold;color:#666;}\n"
            ".value{padding-left:10%;text-align:left;font-size:18px;font-weight:bold;color:#00a2e8;font-style:normal;}\n"
            ".Ftab{height:26px;line-height:26px;padding-left:20px;color:#EEE;text-align:center;}\n"
            ".Ftab span{margin:0;padding:0;width:90%;float:left;width:20%;height:26px;line-height:26px;font-size:20px;color:#EEE;}\n"
            ".Ftab .select{background: #007B3E;}\n"
            ".Frame{width:100%; height:680px;}\n"
        "</style>\n"
        "<script type=\"text/javascript\" src=\"jquery.min.js\"></script>\n"
        "<script type=\"text/javascript\" src=\"j_zDialog.js\"></script>\n"
        "<script type='text/javascript'>\n"
            "function show_T(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
                "str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
                "document.write(str);\n"
            "}\n"
        "</script> \n"
    "</head>\n"
    "<body onload='Init()'>\n"
        "<script type='text/javascript'>\n"
            "show_T('N01');\n"
        "</script>  \n"
        "<div class='title' style='width:90%;'>\n"
            "<div class='back_high1 back_color'>\n"
                "<table width='100%' border='0'>\n"
                    "<tr>\n"
                        "<td class='name' width='30%' height='32'><span id='N02'></span></td>    \n"
                        "<td class='name' width='30%' height='32'><span id='N03'></span></td>\n"
                        "<td class='name' width='30%' height='32'><span id='N04'></span></td>\n"
                        "<td width='10%'><div id='fault_block' class='img_common bg1' style='display:none;'></div></td>\n"
                    "</tr>\n"
                    "<tr>\n"
                        "<td class='value' width='30%' height='32'><span id='ID_0x014F'></span></td>\n"
                        "<td class='value' width='30%' height='32'><span id='ID_0x0182'></span></td>\n"
                        "<td class='value' width='30%' height='32'><span id='ID_0x018B'></span></td>\n"
                        "<td width='10%'><div id='alarm_block' class='img_common bg2' style='display:none;'></div></td>                        \n"
                    "</tr>\n"
              "</table>\n"
            "</div>\n"
        "</div>\n"
        "<div class='blank'></div>\n"
        "<script type='text/javascript'>\n"
            "show_T('N05');\n"
        "</script> \n"
        "<div class='title' style='width:90%;'>\n"
            "<div class='back_high2 back_color'>\n"
                "<table width='100%' border='0'>\n"
                    "<tr>\n"
                        "<td class='name' width='30%' height='25'><span id='N06'></span></td>\n"
                        "<td class='name' width='30%' height='25'><span id='N07'></span></td>\n"
                        "<td class='name' width='30%' height='25'><div></div></td>\n"
                        "<td width='10%'><div class='img_common'></div></td>\n"
                    "</tr>\n"
                    "<tr>\n"
                        "<td class='value' width='30%' height='25'><span id='ID_0x0016'></span></td>\n"
                        "<td class='value' width='30%' height='25'><span id='ID_0x0017'></span></td>\n"
                        "<td class='value' width='30%' height='25'><div></div></td>\n"
                        "<td width='10%'><div class='img_common'></div></td>\n"
                    "</tr>\n"
                    "<tr>\n"
                        "<td class='name' width='30%' height='25'><span id='N09'></span></td>\n"
                        "<td class='name' width='30%' height='25'><span id='N10'></span></td>\n"
                        "<td class='name' width='30%' height='25'><span id='N11'></span></td>\n"
                        "<td width='10%'><div class='img_common'></div></td>\n"
                    "</tr>\n"
                    "<tr>\n"
                        "<td class='value' width='30%' height='25'><span id='ID_0x0005'></span></td>\n"
                        "<td class='value' width='30%' height='25'><span id='ID_0x000B'></span></td>\n"
                        "<td class='value' width='30%' height='25'><span id='ID_0x0008'></span></td>\n"
                        "<td width='10%'><div class='img_common'></div></td>\n"
                    "</tr>     \n"
                "</table>\n"
            "</div>\n"
        "</div> \n"
        "<div class='blank'></div>\n"
        "<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\n"
        "<div class='Ftab color' id=\"tabFunc\">\n"
            "<span class='select' id='N100'></span><span id='N101' style='display:none;'></span><span id='N102' style='display:none;'></span><span id='N103' style='display:none;'></span><span id='N104' style='display:none;'></span><span id='N105' style='display:none;'></span><span id='N106' style='display:none;'></span>\n"
        "</div>\n"
        "<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\n"
        "<iframe class='Frame' frameborder=\"0\" id=\"frame1\"></iframe>\n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script>\n"
        "var tab_index=0;\n"
        "var btns = document.getElementById('tabFunc').getElementsByTagName('span');\n"
        "var frame1 = document.getElementById('frame1');\n"
        "for (var i = 0; i < btns.length; i++) {\n"
            "btns[i].index = i;\n"
            "btns[i].onclick = function(){\n"
                "tab_index = this.index;\n"
                "for (var i = 0; i < btns.length; i++) { btns[i].className = ''; };\n"
                "this.className = 'select';\n"
                "if(tab_index <= 5){\n"
                    "if(document.all){\n"
                        "frame1.src = 'h_0'+(btns[tab_index].index+31)+'.html';\n"
                    "}else{\n"
                        "frame1.src = 'h_0'+(btns[tab_index].index+31)+'.html';\n"
                    "}                    \n"
                "}else{\n"
                    "if(document.all){\n"
                        "frame1.src = 'h_042.html';\n"
                    "}else{\n"
                        "frame1.src = 'h_042.html';\n"
                    "} \n"
                "}\n"
"\n"
                 // 进行高度控制和处理
                 //setTimeout(function(){
                 //    frame1.style.height = frame1.contentWindow.document.body.offsetHeight+'px';
                 //    console.log(frame1.contentWindow.document.body.offsetHeight);
                 //},100);
            "}\n"
        "};\n"
        "function Switch_Tab(index)\n"
        "{\n"
            "for (var i = 0; i < btns.length; i++) { btns[i].className = ''; };\n"
            "btns[index].className = 'select';\n"
            "if(tab_index <= 5){\n"
                "if(document.all){\n"
                    "frame1.src = 'h_0'+(btns[index].index+31)+'.html';\n"
                "}else{\n"
                    "frame1.src = 'h_0'+(btns[index].index+31)+'.html';\n"
                "}\n"
            "}else{\n"
                "if(document.all){\n"
                    "frame1.src = 'h_042.html';\n"
                "}else{\n"
                    "frame1.src = 'h_042.html';\n"
                "} \n"
            "}\n"
        "}\n"
    "</script>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var FromMobileDevice=false;\n"
        "function FromWhichDevice()\n"
        "{\n"
            "var sUserAgent=navigator.userAgent.toLowerCase();\n"
            "var Ipad=sUserAgent.match(/ipad/i)=='ipad';\n"
            "var IphoneOs=sUserAgent.match(/iphone os/i)=='iphone os';\n"
            "var Android=sUserAgent.match(/android/i)=='android';\n"
            "var WindowsPhone=sUserAgent.match(/windows phone/i)=='windows phone';\n"
            "if(Ipad||IphoneOs||Android||WindowsPhone)FromMobileDevice=true;\n"
            "else FromMobileDevice=false;\n"
        "}\n"
        "function lang_init_ex(st,end){for(var i=st;i<=end;i++)eval('document.getElementById(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
         //使用了jquery,下面的不能使用
         //var $=function(o){return document.getElementById(o);};
        "var language=0;\n"
        "var Json;\n"
        "var lang=\n"
        "{\n"
            "N01:['系统状态','System State'],\n"
            "N02:['系统工作状态','Work State'],\n"
            "N03:['工作模式','Work Mode'],\n"
            "N04:['并网控制模式','Grid Control Mode'],\n"
            "N05:['系统功率','System Power'],\n"
            "N06:['微网电压','Mgrid Voltage'],\n"
            "N07:['微网频率','Mgrid Frequency'],\n"
            "N08:['电网状态','Grid Status'],\n"
            "N09:['PCS总有功功率','PCS Total Active Power'],\n"
            "N10:['负载有功功率','Load Active Power'],\n"
            "N11:['PV总有功功率','PV Total Active Power'],\n"
"\n"
            "N20:['固定功率','Const Power'],\n"
            "N21:['跟踪负载功率','Tracking Load'],\n"
            "N22:['PCC点功率控制','PCC Control'],\n"
            "N23:['防逆流','Anti Reflux'], \n"
            "N24:[' ',' '], \n"
            "N25:[' ',' '], \n"
            "N26:[' ',' '], \n"
            "N27:[' ',' '], \n"
            "N28:[' ',' '], \n"
            "N29:[' ',' '], \n"
            "N30:['削峰填谷','Peak Load Shifting'], \n"
            "N31:['交流限发','AC Limited Produce'], \n"
            "N32:['输出平滑','Ramp Rate Control'],\n"
            "N33:['调频','FR'],  \n"
"\n"
            "N64:['并网','Grid'],\n"
            "N65:['离网','Island'],\n"
            "N66:['并离网切换','Grid & Island'],\n"
            "N67:['主动模式','Active Mode'],\n"
            "N68:['被动模式','Passive Mode'],\n"
            "N69:['电网优先','Grid First'],\n"
            "N70:['微网优先','MGrid First'],\n"
            "N71:['无电','Missed'],\n"
            "N72:['有电','Exist'],\n"
"\n"
            "N100:['运行状态','Running Status'],\n"
            "N101:['分时电价','Time Of Use'],\n"
            "N102:['削峰填谷','Peak Load Shifting'],\n"
            "N103:['交流限发','AC Limited Produce'],\n"
            "N104:['输出平滑','Ramp Rate Control'],\n"
            "N105:['调频','FR'],\n"
            "N106:['微网','MGrid'],\n"
"\n"
 		"N132:['<span style=color:#000>初始状态</span>','<span style=color:#000>Initial Status</span>'],\n"
            "N133:['<span style=color:#000>自检过程</span>','<span style=color:#000>Self Checking</span>'],\n"
            "N134:['<span style=color:#007B3E>微网供电启动</span>','<span style=color:#007B3E>MG Starting</span>'],\n"
            "N135:['<span style=color:#007B3E>电网供电启动</span>','<span style=color:#007B3E>Grid Starting</span>'],\n"
            "N136:['<span style=color:#007B3E>微网供电运行</span>','<span style=color:#007B3E>MG Running</span>'],\n"
            "N137:['<span style=color:#007B3E>电网供电运行</span>','<span style=color:#007B3E>Grid Running</span>'],\n"
            "N138:['<span style=color:#F00>故障</span>','<span style=color:#F00>Fault</span>'],\n"
            "N139:['<span style=color:#007B3E>停机中</span>','<span style=color:#007B3E>Stopping</span>'],\n"
            "N140:['<span style=color:#000>停机</span>','<span style=color:#000>Stopped</span>'],\n"
 		"N141:['<span style=color:#F00>紧急停机</span>','<span style=color:#F00>Emergency Stop</span>'],\n"
            "N142:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N143:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N144:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N145:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N146:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N147:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N148:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N149:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N150:['<span style=color:#007B3E>启动中</span>','<span style=color:#007B3E>Starting</span>'],\n"
            "N151:['<span style=color:#007B3E>正在同步</span>','<span style=color:#007B3E>Synchronizing</span>'],\n"
            "N152:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N153:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N154:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N155:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N156:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N157:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N158:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N159:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N160:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N161:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N162:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N163:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>']\n"
        "};\n"
 	"var E_id=new Array(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31);\n"
 	"var E_name=new Array('132','133','134','135','136','137','138','139','140','141','142','143','144','145','146','147','148','149','150','151','152','153','154','155','156','157','158','159','160','161','162','163');\n"
        "var all_color=new Array('#3CF','#ABFF5D');\n"
        "var o_grid_contactor;\n"
        "var o_mgrid_contactor;\n"
        "var o_grid_direction;\n"
        "var o_mgrid_direction;\n"
        "var o_pv_direction;\n"
        "var o_load_direction;\n"
    "\n"
        "function Init()\n"
        "{\n"
            "FromWhichDevice();\n"
"\n"
            "document.getElementById('fault_block').onclick= function(){\n"
                "if(Json.ID_0x0152!=0||Json.ID_0x0153!=0)\n"
                "{\n"
                    "var diag = new Dialog();\n"
                    "diag.Width = 900;\n"
                    "diag.Height = 520;\n"
                    "if(document.all){\n"
                        "diag.URL = \"h_038.html\";\n"
                    "}else{\n"
                        "diag.URL = \"h_038.html\";\n"
                    "}\n"
                    "diag.show();                   \n"
                "}\n"
            "}\n"
"\n"
            "document.getElementById('alarm_block').onclick= function(){\n"
                "if(Json.ID_0x0154!=0)\n"
                "{\n"
                    "var diag = new Dialog();\n"
                    "diag.Width = 900;\n"
                    "diag.Height = 520;\n"
                    "if(document.all){\n"
                        "diag.URL = \"h_039.html\";\n"
                    "}else{\n"
                        "diag.URL = \"h_039.html\";\n"
                    "}\n"
                    "diag.show();\n"
                "}\n"
            "}\n"
"\n"
            "Switch_Tab(tab_index);\n"
            "ajax_2s();\n"
            "setInterval('ajax_2s()',2000);\n"
        "}\n"
        "function ajax_2s()\n"
        "{\n"
            "var URL='s_002.html?time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function() \n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);\n"
         		"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
         		"lang_init_ex(1,7);\n"
                    "lang_init_ex(9,11);\n"
                    "lang_init_ex(100,106);\n"
         		"for(var k=0;k<E_id.length;k++)if(Json.ID_0x014F==E_id[k])eval(\"document.getElementById('ID_0x014F').innerHTML=lang.N\"+E_name[k]+\"[language];\");\n"
                    "if(Json.ID_0x0152!=0||Json.ID_0x0153!=0) document.getElementById('fault_block').style.display='block'; \n"
                    "else document.getElementById('fault_block').style.display='none'; \n"
                    "if(Json.ID_0x0154!=0) document.getElementById('alarm_block').style.display='block';\n"
                    "else document.getElementById('alarm_block').style.display='none';\n"
                    "eval(\"document.getElementById('ID_0x018B').innerHTML=lang.N\"+String(Json.ID_0x018B+20)+\"[language];\");\n"
                    "eval(\"document.getElementById('ID_0x0182').innerHTML=lang.N\"+String(Json.ID_0x0182+64)+\"[language];\");\n"
                    "document.getElementById('ID_0x0016').innerHTML=(Json.ID_0x0016/10.0).toFixed(1)+'V';\n"
                    "document.getElementById('ID_0x0017').innerHTML=(Json.ID_0x0017/100.0).toFixed(2)+'Hz';\n"
                     //eval(\"document.getElementById('ID_0x0004').innerHTML=lang.N\"+String(Json.ID_0x0004+71)+\"[language];\");
         		"document.getElementById('ID_0x0005').innerHTML=(Json.ID_0x0005/10.0).toFixed(1)+'kW';\n"
         		"document.getElementById('ID_0x0008').innerHTML=(Json.ID_0x0008/10.0).toFixed(1)+'kW';\n"
                    "document.getElementById('ID_0x000B').innerHTML=(Json.ID_0x000B/10.0).toFixed(1)+'kW';\n"
                     //高级功能曲线
                    "if(Json.ID_0x050B >=10){\n"
                        "document.getElementById('N101').style.display='none';\n"
                        "document.getElementById('N106').style.display='none';\n"
                        "if(Json.ID_0x050B==10){ document.getElementById('N102').style.display='block'; }else{ document.getElementById('N102').style.display='none'; }\n"
                        "if(Json.ID_0x050B==11){ document.getElementById('N103').style.display='block'; }else{ document.getElementById('N103').style.display='none'; }\n"
                        "if(Json.ID_0x050B==12){ document.getElementById('N104').style.display='block'; }else{ document.getElementById('N104').style.display='none'; }\n"
                        "if(Json.ID_0x050B==13){ document.getElementById('N105').style.display='block'; }else{ document.getElementById('N105').style.display='none'; }                        \n"
                    "}else{\n"
                        "document.getElementById('N102').style.display='none';\n"
                        "document.getElementById('N103').style.display='none';\n"
                        "document.getElementById('N104').style.display='none';\n"
                        "document.getElementById('N105').style.display='none';  \n"
                        "if(Json.ID_0x0389==0){ \n"
                            "document.getElementById('N106').style.display='block';\n"
                            "document.getElementById('N101').style.display='none';                          \n"
                        "}else{\n"
                            "document.getElementById('N101').style.display='block';\n"
                            "document.getElementById('N106').style.display='none';  \n"
                        "}\n"
                    "}\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}\n"
    "</script>\n"
"</html>\n"
};
#endif

