#ifndef _HTML_H_009_H_
#define _HTML_H_009_H_
static const char h_009[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
        "<style type='text/css'>\n"
            ".inquery{margin:5px auto;width:780px;_width:770px;text-align:right;padding-right:10px;}\n"
            ".txt{margin:0 10px;width:120px;}\n"
            ".PagerView{font-size:12px;font-family:tahoma,arial;color:#333;text-align:center;padding:8px;line-height:100%;}\n"
            ".PagerView span{color:#999;margin:0 1px;padding:3px 6px;border:1px solid #ccc;}\n"
            ".PagerView span.on{color:#fff;font-weight:bold;border:1px solid #666;background:#39f;}\n"
            ".PagerView a{color:#00f;text-decoration:none;}\n"
            ".PagerView a span{color:#33f;border:1px solid #66c;}\n"
            ".pager{width:780px;margin:0 auto;}\n"
        "</style>\n"
        "<script src='j_002.js' type='text/javascript'></script>\n"
        "<script type=\"text/javascript\" src=\"jquery.min.js\"></script>\n"
        "<script type=\"text/javascript\" src=\"j_encoding-indexes.js\"></script>\n"
        "<script type=\"text/javascript\" src=\"j_encoding.js\"></script>\n"
        "<script type=\"text/javascript\" src=\"j_filesaver.js\"></script>\n"
    "</head>\n"
    "<body onload='Init()'>\n"
        "<script type='text/javascript'>\n"
            "show_T('N01');\n"
        "</script>\n"
 	"<div class='title'>\n"
 		"<div class='subtitle'>\n"
 			"<div class='r1 subcolor'></div>\n"
 			"<div class='r2 subcolor'></div>\n"
 			"<div class='r3 subcolor'></div>\n"
 			"<div class='r4 subcolor'></div>\n"
 			"<div class='content subcolor subcontent'>\n"
 				"<span id='N02'></span>\n"
 			"</div>\n"
 			"<div class='r4 subcolor'></div>\n"
 			"<div class='r3 subcolor'></div>\n"
 			"<div class='r2 subcolor'></div>\n"
 			"<div class='r1 subcolor'></div>\n"
 			"</div>\n"
 			"<div class='line_short'></div>\n"
 			"<button id='Exp' style='float:right;display:none;margin-top:-30px;width:75px;height:24px;margin-right:20px;' onclick='Export()'><span id='N77'></span></button>\n"
 		"</div>\n"
 	"</div>\n"
        "<div class='blank'></div>\n"
        "<table width='90%' border='0' style=' margin:0 auto;'>\n"
            "<tr>\n"
                "<td>\n"
                    "<table width='100%' border='0' style='border-collapse:collapse;border:1px #aaa solid;'>\n"
                        "<tr>\n"
                            "<th width='100' scope='col'><span id='N03'></span></span></th>\n"
                            "<th width='332' scope='col'><span id='N04'></span></th>\n"
                            "<th width='332' scope='col'><span id='N05'></span></th>\n"
                        "</tr>\n"
                    "</table>\n"
                "</td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td>\n"
                    "<table width='100%' border='0' style='margin-top:2px;border-collapse:collapse;border:1px #ddd solid;text-align:center'>\n"
                        "<script type='text/javascript'>\n"
                            "var str='';\n"
                            "for(var i=1;i<=10;i++)\n"
                            "{\n"
                                "str+=\"<tr class='\"+(i%2?\"odd\":\"even\")+\"'>\";\n"
                                "str+=\"<td id='r\"+(i<10?(\"0\"+i):i)+\"1' width='100'></td>\";\n"
                                "str+=\"<td id='r\"+(i<10?(\"0\"+i):i)+\"2' width='332'></td>\";\n"
                                "str+=\"<td id='r\"+(i<10?(\"0\"+i):i)+\"3' width='332' style='color:#F00'></td>\";\n"
                                "str+=\"</tr>\";\n"
                            "}\n"
                            "document.write(str);\n"
                        "</script>\n"
                    "</table>\n"
                    "<img id='waiting' style='margin:0 auto;z-index:20000;position:relative;top:-168px;visibility:hidden;' src='i_002.gif'/>\n"
                "</td>\n"
            "</tr>\n"
        "</table>\n"
        "<br/>\n"
        "<div id='pager'></div>\n"
        "<table width='90%' border='0'><tr><td width='100%' class='even tip'><span id='tip'>&nbsp;</span></td></tr></table>\n"
        "<div class='btm_blank'></div>\n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var pager;\n"
        "var tid;\n"
        "var temp;\n"
        "var page_num=1;\n"
        "var language=1;\n"
        "var busy = false;\n"
        "var Json;\n"
        "var lang=\n"
        "{\n"
            "N01:['故障记录','Fault Records'],\n"
            "N02:['详细记录','Detailed Records'],\n"
            "N03:['序号','No.'],\n"
            "N04:['时间','Time'],\n"
            "N05:['故障名称','Fault Name'],\n"
            "N06:['一共','Total '],\n"
            "N07:['页，共',' pages, '],\n"
            "N08:['页，共',' page, '],\n"
            "N09:['条记录',' records'],\n"
            "N10:['条记录',' record'],\n"
            "N11:['无记录。',' No record.'],\n"
"\n"
             //64位故障定义
            "N12:['储能逆变器故障','PCS Fault'],\n"
            "N13:['储能逆变器通讯故障','PCS Comm Fault'],\n"
            "N14:['储能逆变器地址冲突','PCS Address Conflict'],\n"
            "N15:['',''],\n"
            "N16:['光伏逆变器故障','PV Fault'],\n"
            "N17:['光伏逆变器通讯故障','PV Comm Fault'],\n"
            "N18:['光伏逆变器地址冲突','PV Address Conflict'],\n"
            "N19:['',''],\n"
            "N20:['接触器故障','Contact Fault'],\n"
            "N21:['',''],\n"
            "N22:['',''],\n"
            "N23:['',''],\n"
            "N24:['负载防雷故障','SPD Fault'],\n"
            "N25:['电池电量低','Low Battery'],\n"
            "N26:['BMS故障','BMS Fault'],\n"
            "N27:['自检失败','Self Check Fail'],\n"
            "N28:['自检超时','Self Check Timeout'],\n"
            "N29:['微网供电启动超时','MG Start Timeout'],\n"
            "N30:['微网供电启动失败','MG Start Fail'],\n"
            "N31:['电网供电启动超时','Grid Start Timeout'],\n"
            "N32:['电网供电启动失败','Grid Start Fail'],\n"
            "N33:['',''],\n"
            "N34:['同步失败','Sync Failed'],\n"
            "N35:['停机超时','Stop Timeout'],\n"
            "N36:['',''],\n"
            "N37:['',''],\n"
            "N38:['',''],\n"
            "N39:['',''],\n"
            "N40:['',''],\n"
            "N41:['',''],\n"
            "N42:['',''],\n"
            "N43:['',''],\n"
            "N44:['节点1故障','Node 1 Fault'],\n"
            "N45:['节点2故障','Node 2 Fault'],\n"
            "N46:['节点3故障','Node 3 Fault'],\n"
            "N47:['节点4故障','Node 4 Fault'],\n"
            "N48:['节点5故障','Node 5 Fault'],\n"
            "N49:['节点6故障','Node 6 Fault'],\n"
            "N50:['节点7故障','Node 7 Fault'],\n"
            "N51:['节点8故障','Node 8 Fault'],\n"
            "N52:['',''],\n"
            "N53:['',''],\n"
            "N54:['',''],\n"
            "N55:['',''],\n"
            "N56:['',''],\n"
            "N57:['',''],\n"
            "N58:['',''],\n"
            "N59:['',''],\n"
            "N60:['',''],\n"
            "N61:['',''],\n"
            "N62:['',''],\n"
            "N63:['',''],\n"
            "N64:['DSP通讯故障','DSP Com-fault'],\n"
            "N65:['',''],\n"
            "N66:['',''],\n"
            "N67:['',''],\n"
            "N68:['',''],\n"
            "N69:['',''],\n"
            "N70:['',''],\n"
            "N71:['',''],\n"
            "N72:['',''],\n"
            "N73:['',''],\n"
            "N74:['',''],\n"
            "N75:['',''],\n"
            "\n"
            "N77:['导出','Export']\n"
        "};\n"
"\n"
        "function Export()\n"
        "{\n"
             // IE <10 is explicitly unsupported
            "if (typeof navigator !== \"undefined\" &&\n"
                "/MSIE [1-9]\\\\./.test(navigator.userAgent)) {\n"
                "return;\n"
            "}\n"
            "if(busy) return;\n"
             //$.ajax({
            "jQuery.ajax({\n"
                "url:\"Fault_Records.csv\",\n"
                "type:\"get\",\n"
                "contentType:\"application/text;charset=gb2312\",\n"
                "dataType:\"text\",\n"
                "async: false,\n"
                "beforeSend:function()\n"
                "{\n"
                    "OBJ('Exp').disabled = true;\n"
                    "OBJ('waiting').style.visibility='visible';\n"
                    "busy=true;\n"
                "},\n"
                "success:function(data)\n"
                "{\n"
                    "var myData = data;\n"
                    "textEncoder = new CustomTextEncoder('gb2312', {NONSTANDARD_allowLegacyEncoding: true}),\n"
                    "fileName = 'Fault_Records.csv';\n"
                    "var csvContentEncoded = textEncoder.encode([myData]);\n"
                    "var blob = new Blob([csvContentEncoded], {type: 'text/csv;charset=gb2312;'});\n"
                    "saveAs(blob, fileName);\n"
                    "OBJ('Exp').disabled = false;\n"
                    "OBJ('waiting').style.visibility='hidden';\n"
                    "busy=false;\n"
                "}\n"
            "});\n"
        "}\n"
        "function Init()\n"
        "{\n"
 		"FromWhichDevice();\n"
 		"if(FromMobileDevice==true)OBJ('Exp').style.display='none';\n"
"\n"
            "var URL='s_009.html?0x0000&time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);\n"
 				"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
 				"lang_init(5);\n"
                     // IE <10 is explicitly unsupported
                    "if (typeof navigator !== \"undefined\" &&\n"
                        "/MSIE [1-9]\\./.test(navigator.userAgent)) {\n"
                    "}else{\n"
                        "OBJ('Exp').style.display='block';\n"
                    "}\n"
 				"OBJ('N77').innerHTML=lang.N77[language];\n"
 				"doSubmit();\n"
 				"show_tip('&nbsp;');\n"
         	"}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
      "}\n"
 	"var F_id=new Array('1','2','3','4','5','6','7','8',\n"
 						  "'9','10','11','12','13','14','15','16',\n"
 						  "'17','18','19','20','21','22','23','24',\n"
 						  "'25','26','27','28','29','30','31','32',\n"
 						  "'33','34','35','36','37','38','39','40',\n"
 						  "'41','42','43','44','45','46','47','48',\n"
 						  "'49','50','51','52','53','54','55','56',\n"
 						  "'57','58','59','60','61','62','63','64');\n"
 	"var F_name=new Array('12','13','14','15','16','17','18','19',\n"
 							"'20','21','22','23','24','25','26','27',\n"
 							"'28','29','30','31','32','33','34','35',\n"
 							"'36','37','38','39','40','41','42','43',\n"
 							"'44','45','46','47','48','49','50','51',\n"
 							"'52','53','54','55','56','57','58','59',\n"
 							"'60','61','62','63','64','65','66','67',\n"
 							"'68','69','70','71','72','73','74','75');\n"
        "function doSubmit()\n"
        "{\n"
         	//测试
"\n"
 			//temp={'r':[
 			//{'C1':1,'C2':'2014/08/13&nbsp;&nbsp;15:10:42','C3':'1'},
 			//{'C1':2,'C2':'2014/08/13&nbsp;&nbsp;15:10:37','C3':'2'},
 			//{'C1':3,'C2':'2014/08/13&nbsp;&nbsp;11:46:23','C3':'3'},
 			//{'C1':4,'C2':'2014/08/13&nbsp;&nbsp;11:46:23','C3':'4'},
 			//{'C1':5,'C2':'2014/08/13&nbsp;&nbsp;11:46:23','C3':'5'},
 			//{'C1':6,'C2':'2014/08/13&nbsp;&nbsp;11:46:23','C3':'6'},
 			//{'C1':7,'C2':'2014/08/13&nbsp;&nbsp;11:46:23','C3':'7'},
 			//{'C1':8,'C2':'2014/08/13&nbsp;&nbsp;11:46:23','C3':'8'},
 			//{'C1':9,'C2':'2014/08/13&nbsp;&nbsp;11:46:23','C3':'9'},
 			//{'C1':10,'C2':'2014/08/13&nbsp;&nbsp;11:46:23','C3':'10'},
 			//{'end':0}]};Records=14;
"\n"
            "var URL='r_009.html?'\n"
            "+'Y='+2000\n"
            "+'&M='+1\n"
            "+'&D='+1\n"
            "+'&P='+page_num\n"
            "+'&time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
 				"show_tip('&nbsp;');\n"
 				"eval('temp='+xmlhttp.responseText);\n"
 				"loop=temp.r.length-1;\n"
 				"for(var aa=0;aa<loop;aa++)\n"
 				"{\n"
 					"tid=(aa<9)?'0'+(aa+1):aa+1;\n"
 					"for(var j=1;j<=3;j++)\n"
 					"{\n"
 						"eval(\"OBJ('r'+tid+'\"+j+\"').innerHTML=temp.r[aa].C\"+j+\";\");\n"
 						"if(j==3)for(var k=0;k<F_id.length;k++)eval(\"eval(\\\"if(temp.r[aa].C\\\"+\\\"\"+j+\"==F_id[k])OBJ('r\\\"+\\\"\"+tid+\"3').innerHTML=lang.N\"+F_name[k]+\"[language];\\\")\");\n"
 					"}\n"
 				"}\n"
 				"for(var bb=loop;bb<10;bb++)\n"
 				"{\n"
 					"tid=(bb<9)?'0'+(bb+1):bb+1;\n"
 					"for(var k=1;k<=3;k++)OBJ('r'+tid+k).innerHTML='';\n"
 				"}\n"
 				"if(Records==0)OBJ('Exp').disabled=true;else OBJ('Exp').disabled=false;\n"
 				"if(Records<=10)\n"
 				"{\n"
 					"if(Records==0)\n"
 					"{\n"
 						"show_tip(lang.N11[language]);\n"
 						"OBJ('waiting').style.visibility='hidden'\n"
 						"OBJ('pager').style.display='none';\n"
 						"return false;\n"
 					"}\n"
 					"else if(Records==1)\n"
 					"{\n"
 						"OBJ('pager').style.display='block';\n"
 						"pager=new PagerView('pager',lang.N06[language],lang.N08[language],lang.N10[language]);\n"
 					"}\n"
 					"else\n"
 					"{\n"
 						"OBJ('pager').style.display='block';\n"
 						"pager=new PagerView('pager',lang.N06[language],lang.N08[language],lang.N09[language]);\n"
 					"}\n"
 				"}\n"
 				"else\n"
 				"{\n"
 					"OBJ('pager').style.display='block';\n"
 					"pager=new PagerView('pager',lang.N06[language],lang.N07[language],lang.N09[language]);\n"
 				"}\n"
 				"pager.itemCount=Records;\n"
 				"pager.size=10;\n"
 				"pager.index=1;\n"
 				"pager.onclick=function(index)\n"
 				"{\n"
 						//测试
"\n"
 						//temp={'r':[
 						//{'C1':1,'C2':'2014/08/13&nbsp;&nbsp;15:10:42','C3':'2'},
 						//{'C1':2,'C2':'2014/08/13&nbsp;&nbsp;15:10:37','C3':'4'},
 						//{'C1':3,'C2':'2014/08/13&nbsp;&nbsp;11:46:23','C3':'7'},
 						//{'C1':4,'C2':'2014/08/13&nbsp;&nbsp;11:46:23','C3':'19'},
 						//{'C1':5,'C2':'2014/08/13&nbsp;&nbsp;11:46:23','C3':'13'},
 						//{'C1':6,'C2':'2014/08/13&nbsp;&nbsp;11:46:23','C3':'12'},
 						//{'C1':7,'C2':'2014/08/13&nbsp;&nbsp;11:46:23','C3':'18'},
 						//{'C1':8,'C2':'2014/08/13&nbsp;&nbsp;11:46:23','C3':'9'},
 						//{'C1':9,'C2':'2014/08/13&nbsp;&nbsp;11:46:23','C3':'10'},
 						//{'C1':10,'C2':'2014/08/13&nbsp;&nbsp;11:46:23','C3':'1'},
 						//{'end':0}]};Records=14;
"\n"
                        "var URL='r_009.html?'\n"
                        "+'Y='+2000\n"
                        "+'&M='+1\n"
                        "+'&D='+1\n"
                        "+'&P='+index\n"
                        "+'&time='+Math.random();\n"
"\n"
                        "var xmlhttp;\n"
                        "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                        "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                        "xmlhttp.onreadystatechange=function()\n"
                        "{\n"
                            "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                            "{\n"
                             "show_tip('&nbsp;');\n"
                                "eval('temp='+xmlhttp.responseText);\n"
                             "if(temp.r.length>10)\n"
                             "{\n"
 								"loop=10;	\n"
                             "}\n"
                             "else\n"
                             "{\n"
                             	"loop=temp.r.length-1;\n"
                             "}\n"
                             "for(var cc=0;cc<loop;cc++)\n"
                             "{\n"
                             	"tid=(cc<9)?'0'+(cc+1):cc+1;\n"
                             	"for(var j=1;j<=3;j++)\n"
                             	"{\n"
                             		"eval(\"OBJ('r'+tid+'\"+j+\"').innerHTML=temp.r[cc].C\"+j+\";\");\n"
                             		"if(j==3)for(var k=0;k<F_id.length;k++)eval(\"eval(\\\"if(temp.r[cc].C\\\"+\\\"\"+j+\"==F_id[k])OBJ('r\\\"+\\\"\"+tid+\"3').innerHTML=lang.N\"+F_name[k]+\"[language];\\\")\");\n"
                             	"}\n"
                             "}\n"
                             "for(var dd=loop;dd<10;dd++)\n"
                             "{\n"
                             	"tid=(dd<9)?'0'+(dd+1):dd+1;\n"
                             	"for(var k=1;k<=3;k++)OBJ('r'+tid+k).innerHTML='';\n"
                             "}\n"
                             "OBJ('waiting').style.visibility='hidden'\n"
                         "}\n"
                     "};\n"
                     "xmlhttp.open('GET',URL,true);\n"
                     "xmlhttp.send();\n"
                     "OBJ('waiting').style.visibility='visible';\n"
                 "};\n"
                 "pager.render();\n"
                 "OBJ('waiting').style.visibility='hidden';\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
            "OBJ('waiting').style.visibility='visible';\n"
        "}\n"
    "</script>\n"
"</html>\n"
};
#endif
