#ifndef _HTML_H_013_H_
#define _HTML_H_013_H_
static const char h_013[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
"<head>\n"
"<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
"<style type='text/css'>\n"
 "body{margin:0;padding:0;background-color:#fff;font-family:'微软雅黑',Arial,'宋体',sans-serif;}\n"
 "#menu{margin:5px 0 0 0;width:245px;float:right;}\n"
 ".menu_cn{line-height:36px;padding-left:65px;width:180px;height:36px;color:#000;background-color:#F58E03;font-weight:bold;font-size:16px;}\n"
 ".submenu_cn{line-height:32px;padding-left:55px;width:190px;height:32px;color:#000;background-color:#eee;font-weight:normal;font-size:14px;}\n"
 ".menu_en{line-height:36px;padding-left:6px;width:239px;height:36px;color:#000;background-color:#F58E03;font-weight:bold;font-size:16px;}\n"
 ".submenu_en{line-height:32px;padding-left:20px;width:225px;height:32px;color:#000;background-color:#eee;font-weight:normal;font-size:14px;}\n"
 ".color{background-color:#F58E03;}\n"
 ".change_color{background-color:#007B3E;}\n"
 ".r1{margin:0 5px;height:1px;overflow:hidden;}\n"
 ".r2{margin:0 3px;height:1px;overflow:hidden;}\n"
 ".r3{margin:0 2px;height:1px;overflow:hidden;}\n"
 ".r4{margin:0 1px;height:2px;overflow:hidden;}\n"
 ".blank{height:1px;overflow:hidden;background-color:#fff;width:213px;}\n"
"</style>\n"
"<script language='javascript' type='text/javascript'>\n"
 "var $=function(o){return document.getElementById(o);};\n"
 "var current_id='h_002';\n"
 "var language=1;\n"
 "var Json;\n"
 "var HaveInitH002=false;\n"
 "var lang=\n"
 "{\n"
 	"N01:['运行信息','Operating Information'],\n"
 	"N02:['概要信息','Summary Information'],\n"
 	"N03:['储能逆变器信息','PCS Information'],\n"
 	"N04:['参数设置','Parameters Settings'],\n"
 	"N05:['系统参数','System Parameters'],\n"
 	"N06:['运行参数','Operating Parameters'],\n"
 	"N07:['EMS通讯参数','EMS Comm Parameters'],\n"
 	"N08:['历史记录','History Records'],\n"
 	"N09:['运行记录','Running Records'],\n"
 	"N10:['事件记录','Event Records'],\n"
 	"N11:['故障记录','Fault Records'],\n"
 	"N12:['系统信息','System Information'],\n"
 	"N13:['光伏逆变器信息', 'PV Information'],\n"
 	"N14:['光伏汇流箱信息', 'PVS Information'],\n"
 	"N15:['光伏控制器信息', 'DCDC Information'],\n"
 	"N16:['电池信息', 'BMS Information'],\n"
 	"N17:['电表信息', 'Ammeter Information'],\n"
 	"N18:['实时监控信息', 'RealTime Monitor'],\n"
 	"N19:['从设备参数', 'Slave Unit Parameters'],\n"
 	"N20:['保护参数', 'Protection Parameters'],\n"
 	"N21:['告警记录','Alarm Records'],\n"
 	"N22:['详细信息','Detail Information'],\n"
 	"N23:['环境监测仪信息','Env-Detector Information']\n"
 "};\n"
 "var temp1=new Array('yxxx','cssz','lsjl','h_010');\n"
 	//+ h_025: 实时监控界面
 "var temp2=new Array('h_002','h_003','h_004','h_005','h_006','h_007','h_008','h_009','h_015','h_016','h_017','h_018','h_025','h_026','h_027','h_028','h_029','h_043','h_045');\n"
 "function change_color(obj)\n"
 "{\n"
 	"if(current_id!=obj.id)\n"
 	"{\n"
 		"for(var i=1;i<=4;i++)\n"
 		"{\n"
 			"if(obj.id=='yxxx')\n"
 			"$('top'+i).className='r'+i+' change_color';\n"
 			"if(obj.id=='h_010')\n"
 			"$('btm'+i).className='r'+i+' change_color';\n"
 		"}\n"
 		"obj.style.background='#007b3e';\n"
 		"obj.style.color='#fff';\n"
 	"}\n"
 "}\n"
 "function resume_color(obj)\n"
 "{\n"
 	"if(current_id!=obj.id)\n"
 	"{\n"
 		"for(var i=1;i<=4;i++)\n"
 		"{\n"
 			"if(obj.id=='yxxx')\n"
 			"$('top'+i).className='r'+i+' color';\n"
 			"if(obj.id=='h_010')\n"
 			"$('btm'+i).className='r'+i+' color';\n"
 		"}\n"
 		"switch(obj.id)\n"
 		"{\n"
 			"case 'yxxx':\n"
 			"case 'cssz':\n"
 			"case 'lsjl':\n"
 			"case 'h_010':\n"
 				"obj.style.background='#F58E03';\n"
 				"obj.style.color='#000';\n"
 			"break;\n"
 			"default:\n"
 				"obj.style.background='#eee';\n"
 				"obj.style.color='#000';\n"
 			"break;\n"
 		"}\n"
 	"}\n"
 "}\n"
 "function showurl(obj)\n"
 "{\n"
 	"var temp_num;\n"
 	"for(var i=2;i<=18;i++)\n"
 	"{\n"
 		"if(i==11||i==12||i==13||i==14) continue;\n"
 		"if(i<10)temp_num='h_00'+i;\n"
 		"else temp_num='h_0'+i;\n"
 		"if(i==10){\n"
 			"$(temp_num).style.background='#F58E03';\n"
 			"$(temp_num).style.color='#000';\n"
 		"}else{\n"
 			"$(temp_num).style.background='#eeeeee';\n"
 			"$(temp_num).style.color='#000';\n"
 		"}\n"
 	"}\n"
"\n"
 		//+实时监控界面
 	"$('h_025').style.background='#eeeeee';\n"
 	"$('h_025').style.color='#000';\n"
"\n"
 		//+电表界面
 	"$('h_026').style.background='#eeeeee';\n"
 	"$('h_026').style.color='#000';\n"
"\n"
 		//+从设备通讯参数
 	"$('h_027').style.background='#eeeeee';\n"
 	"$('h_027').style.color='#000';\n"
"\n"
 		//+保护参数
 	"$('h_028').style.background='#eeeeee';\n"
 	"$('h_028').style.color='#000';		\n"
"\n"
 		//告警界面
 	"$('h_029').style.background='#eeeeee';\n"
 	"$('h_029').style.color='#000';		\n"
"\n"
 		//详细信息界面
 	"$('h_043').style.background='#eeeeee';\n"
 	"$('h_043').style.color='#000';			\n"
"\n"
 		//环境仪信息界面
 	"$('h_045').style.background='#eeeeee';\n"
 	"$('h_045').style.color='#000';	\n"
"\n"
 	"obj.style.background='#007B3E';\n"
 	"obj.style.color='#fff';\n"
 	"if(obj.id!='h_010')\n"
 	"{\n"
 		"for(var i=1;i<=4;i++)\n"
 		"{\n"
 			"$('btm'+i).className='r'+i+' color';\n"
 		"}\n"
 	"}\n"
 	"current_id=obj.id;\n"
 	"var SURL='';\n"
 	"if(document.all){\n"
 		"SURL=current_id+'.html';\n"
 	"}else{\n"
 		"SURL=current_id+'.html';\n"
 	"}\n"
 		//alert(SURL);
 	"top.main.location.href=SURL;\n"
 "}\n"
 "function Init()\n"
 "{\n"
 	"var URL='s_013.html?time='+Math.random();\n"
 	"var xmlhttp;\n"
 	"if(window.XMLHttpRequest) xmlhttp=new XMLHttpRequest();\n"
 	"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 	"xmlhttp.onreadystatechange=function()\n"
 	"{\n"
 		"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 		"{	\n"
 			"var num,temp;\n"
"\n"
 			"eval('Json='+xmlhttp.responseText);\n"
"\n"
 			"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
 			"if(language==0)\n"
 			"{\n"
 				"for(var i=0;i<temp1.length;i++)\n"
 				"{\n"
 					"$(temp1[i]).className='menu_cn';\n"
 				"}\n"
 				"for(var j=0;j<temp2.length;j++)\n"
 				"{\n"
 					"$(temp2[j]).className='submenu_cn';\n"
 				"}\n"
 			"}\n"
 			"else if(language==1)\n"
 			"{\n"
 				"for(var i=0;i<temp1.length;i++)\n"
 				"{\n"
 					"$(temp1[i]).className='menu_en';\n"
 				"}\n"
 				"for(var j=0;j<temp2.length;j++)\n"
 				"{\n"
 					"$(temp2[j]).className='submenu_en';\n"
 				"}\n"
 			"}\n"
 			"for(var i=1;i<=16;i++)\n"
 			"{\n"
 				"eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');\n"
 			"}\n"
 			"$('N17').innerHTML=lang.N17[language];\n"
 			"$('N18').innerHTML=lang.N18[language];\n"
 			"$('N19').innerHTML=lang.N19[language];\n"
 			"$('N20').innerHTML=lang.N20[language];\n"
 			"$('N21').innerHTML=lang.N21[language];\n"
 			"$('N22').innerHTML=lang.N22[language];\n"
 			"$('N23').innerHTML=lang.N23[language];\n"
"\n"
 			"if(Json.ID_0x0390==0x00){$('h_003').style.display='none';$('h_003_blank').style.display='none';}else{$('h_003').style.display='block';$('h_003_blank').style.display='block';}\n"
 			"if(Json.ID_0x0391==0x00){$('h_015').style.display='none';$('h_015_blank').style.display='none';}else{$('h_015').style.display='block';$('h_015_blank').style.display='block';}\n"
 			"if(Json.ID_0x0393==0x00){$('h_016').style.display='none';$('h_016_blank').style.display='none';}else{$('h_016').style.display='block';$('h_016_blank').style.display='block';}\n"
 			"if(Json.ID_0x0392==0x00){$('h_017').style.display='none';$('h_017_blank').style.display='none';}else{$('h_017').style.display='block';$('h_017_blank').style.display='block';}\n"
 			"if(Json.ID_0x0394==0x00){$('h_018').style.display='none';$('h_018_blank').style.display='none';}else{$('h_018').style.display='block';$('h_018_blank').style.display='block';}\n"
 			"if(Json.ID_0x0395==0x00){$('h_026').style.display='none';$('h_026_blank').style.display='none';}else{$('h_026').style.display='block';$('h_026_blank').style.display='block';}\n"
 			"if(Json.ID_0x0396==0x00){$('h_025').style.display='none';$('h_025_blank').style.display='none';}else{$('h_025').style.display='block';$('h_025_blank').style.display='block';}\n"
 			"if(Json.ID_0x039A==0x00){$('h_045').style.display='none';$('h_045_blank').style.display='none';}else{$('h_045').style.display='block';$('h_045_blank').style.display='block';}\n"
"\n"
 			"if(HaveInitH002==false)\n"
 			"{\n"
 				"$('h_002').style.background='#007B3E';\n"
 				"$('h_002').style.color='#fff';\n"
 			"}\n"
 		"}\n"
 	"};\n"
 	"xmlhttp.open('GET',URL,true);\n"
 	"xmlhttp.send();			\n"
 	"if(HaveInitH002==false)\n"
 	"{\n"
 		"setTimeout(\"showurl($('h_002'))\",500);\n"
 		"HaveInitH002=true;\n"
 	"}\n"
 "}\n"
"</script>\n"
"</head>\n"
 "<body onload='Init();'>\n"
 	"<div id='menu'>\n"
 		"<div id='top1' class='r1 color'></div>\n"
 		"<div id='top2' class='r2 color'></div>\n"
 		"<div id='top3' class='r3 color'></div>\n"
 		"<div id='top4' class='r4 color'></div>\n"
 		"<div id='yxxx' class='menu_en' style='cursor:default;'><span id='N01'></span></div>\n"
 		"<div class='blank'></div>\n"
 		"<div id='h_002' class='submenu_en' style='cursor:pointer;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N02'></span></div>\n"
 		"<div class='blank'></div>\n"
 		"<div id='h_003' class='submenu_en' style='cursor:pointer; display:block;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N03'></span></div>\n"
 		"<div id='h_003_blank' class='blank'></div>			\n"
 		"<div id='h_015' class='submenu_en' style='cursor:pointer; display:none;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N13'></span></div>\n"
 		"<div id='h_015_blank' class='blank'></div>\n"
 		"<div id='h_016' class='submenu_en' style='cursor:pointer; display:none;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N14'></span></div>\n"
 		"<div id='h_016_blank' class='blank'></div>\n"
 		"<div id='h_017' class='submenu_en' style='cursor:pointer; display:none;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N15'></span></div>\n"
 		"<div id='h_017_blank' class='blank'></div>\n"
 		"<div id='h_018' class='submenu_en' style='cursor:pointer; display:none;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N16'></span></div>\n"
 		"<div id='h_018_blank' class='blank'></div>\n"
 		"<div id='h_026' class='submenu_en' style='cursor:pointer; display:none;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N17'></span></div>\n"
 		"<div id='h_026_blank' class='blank'></div>\n"
 		"<div id='h_025' class='submenu_en' style='cursor:pointer; display:none;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N18'></span></div>\n"
 		"<div id='h_025_blank' class='blank'></div>\n"
 		"<div id='h_045' class='submenu_en' style='cursor:pointer; display:none;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N23'></span></div>\n"
 		"<div id='h_045_blank' class='blank'></div>\n"
 		"<div id='h_043' class='submenu_en' style='cursor:pointer;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N22'></span></div>\n"
 		"<div id='h_043_blank' class='blank'></div>\n"
 		"<div id='cssz' class='menu_en' style='cursor:default;'><span id='N04'></span></div>\n"
 		"<div class='blank'></div>\n"
 		"<div id='h_004' class='submenu_en' style='cursor:pointer;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N05'></span></div>\n"
 		"<div class='blank'></div>\n"
 		"<div id='h_005' class='submenu_en' style='cursor:pointer;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N06'></span></div>\n"
 		"<div class='blank'></div>\n"
 		"<div id='h_006' class='submenu_en' style='cursor:pointer;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N07'></span></div>\n"
 		"<div class='blank'></div>\n"
 		"<div id='h_027' class='submenu_en' style='cursor:pointer;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N19'></span></div>\n"
 		"<div class='blank'></div>\n"
 		"<div id='h_028' class='submenu_en' style='cursor:pointer;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N20'></span></div>\n"
 		"<div class='blank'></div>\n"
 		"<div id='lsjl' class='menu_en' style='cursor:default;'><span id='N08'></span></div>\n"
 		"<div class='blank'></div>\n"
 		"<div id='h_007' class='submenu_en' style='cursor:pointer;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N09'></span></div>\n"
 		"<div class='blank'></div>\n"
 		"<div id='h_008' class='submenu_en' style='cursor:pointer;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N10'></span></div>\n"
 		"<div class='blank'></div>\n"
 		"<div id='h_009' class='submenu_en' style='cursor:pointer;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N11'></span></div>\n"
 		"<div class='blank'></div>\n"
 		"<div id='h_029' class='submenu_en' style='cursor:pointer;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N21'></span></div>\n"
 		"<div class='blank'></div>\n"
 		"<div id='h_010' class='menu_en' style='cursor:pointer;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N12'></span></div>\n"
 		"<div id='btm4' class='r4 color'></div>\n"
 		"<div id='btm3' class='r3 color'></div>\n"
 		"<div id='btm2' class='r2 color'></div>\n"
 		"<div id='btm1' class='r1 color'></div>\n"
 	"</div>\n"
 	"<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
 "</body>\n"
"</html>\n"
};
#endif
