#ifndef _HTML_H_010_H_
#define _HTML_H_010_H_
static const char h_010[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
        "<style type='text/css'>\n"
            ".td1{padding-left:40px;text-align:left;}\n"
            ".td_val{text-align:right;padding-right:40px;}\n"
 		".td2{text-align:center;}\n"
            ".td3{padding-right:10px;text-align:right;}\n"
 		".pwd{text-align:center;}\n"
            ".m_btn{width:100px;height:24px;float: right;}\n"
        "</style>\n"
        "<script type='text/javascript'>\n"
            "var $=function(o){return document.getElementById(o);};\n"
            "function lang_init_ex(st,end){for(var i=st;i<=end;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
            "function show_tip(obj){$('tip').innerHTML=obj;}\n"
            "function show_T(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
                "str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_sT(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_sT_ex(tid, id)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' id='\"+id+\"' style='display:none;width:90%'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}      \n"
        "</script>   \n"
    "</head>\n"
    "<body onload='Init()'>\n"
        "<script type='text/javascript'>\n"
            "show_T('N01');\n"
            "show_sT_ex('N02', 'title1');\n"
        "</script>\n"
        "<table width='90%' border='0' id='pwds_operator'>\n"
            "<tr>\n"
                "<td width='50%' class='td1 odd'><span id='N03'></span></td>\n"
                "<td width='50%' class='td1 odd'><input id='oldpwd_operator' class='pwd' maxlength='8' type='password'/></td>\n"
                "<td width='30%' class='td1 odd'><span></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td width='50%' class='td1 even'><span id='N04'></span></td>\n"
                "<td width='50%' class='td1 even'><input id='newpwd1_operator' class='pwd' maxlength='8' type='password'/></td>\n"
                "<td width='30%' class='td1 even'><span></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td width='50%' class='td1 odd'><span id='N05'></span></td>\n"
                "<td width='50%' class='td1 odd'><input id='newpwd2_operator' class='pwd' maxlength='8' type='password'/></td>\n"
                "<td width='30%' class='td1 odd' style='text-align:right;'><button class='m_btn' onclick='ModifyPassword($(\"oldpwd_operator\"),$(\"newpwd1_operator\"),$(\"newpwd2_operator\"),0)'><span id='N06'></span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<script type='text/javascript'>\n"
            "show_sT_ex('N07', 'title2');\n"
        "</script>\n"
        "<table width='90%' border='0' id='pwds_admin'>\n"
            "<tr>\n"
                "<td width='50%' class='td1 odd'><span id='N08'></span></td>\n"
                "<td width='50%' class='td1 odd'><input id='oldpwd_admin' class='pwd' maxlength='8' type='password'/></td>\n"
                "<td width='30%' class='td1 odd'><span></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td width='50%' class='td1 even'><span id='N09'></span></td>\n"
                "<td width='50%' class='td1 even'><input id='newpwd1_admin' class='pwd' maxlength='8' type='password'/></td>\n"
                "<td width='30%' class='td1 even'><span></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td width='50%' class='td1 odd'><span id='N10'></span></td>\n"
                "<td width='50%' class='td1 odd'><input id='newpwd2_admin' class='pwd' maxlength='8' type='password'/></td>\n"
                "<td width='30%' class='td1 odd' style='text-align:right;'><button class='m_btn' onclick='ModifyPassword($(\"oldpwd_admin\"),$(\"newpwd1_admin\"),$(\"newpwd2_admin\"),1)'><span id='N11'></span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<script type='text/javascript'>\n"
            "show_sT_ex('N12', 'title3');\n"
        "</script>\n"
        "<table width='90%' border='0' id='pwds_maintriner'>\n"
            "<tr>\n"
                "<td width='50%' class='td1 odd'><span id='N13'></span></td>\n"
                "<td width='50%' class='td1 odd'><input id='oldpwd_maintriner' class='pwd' maxlength='8' type='password'/></td>\n"
                "<td width='30%' class='td1 odd'><span></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td width='50%' class='td1 even'><span id='N14'></span></td>\n"
                "<td width='50%' class='td1 even'><input id='newpwd1_maintriner' class='pwd' maxlength='8' type='password'/></td>\n"
                "<td width='30%' class='td1 even'><span></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td width='50%' class='td1 odd'><span id='N15'></span></td>\n"
                "<td width='50%' class='td1 odd'><input id='newpwd2_maintriner' class='pwd' maxlength='8' type='password'/></td>\n"
                "<td width='30%' class='td1 odd' style='text-align:right;'><button class='m_btn' onclick='ModifyPassword($(\"oldpwd_maintriner\"),$(\"newpwd1_maintriner\"),$(\"newpwd2_maintriner\"),2)'><span id='N16'></span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='blank'></div>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N30');\n"
        "</script>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td class='td1 odd' width='50%'><span id='N31'></span></td>\n"
                "<td class='td_val odd' width='50%'><span id='ID_0x0203'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 even'><span id='N32'></span></td>\n"
                "<td class='td_val even'><span id='ID_0x0204'></span></td>\n"
            "</tr>\n"
            "<tr style='display:none;'>\n"
                "<td class='td1 odd'><span id='N33'></span></td>\n"
                "<td class='td_val odd'><span id='ID_0x0205'></span></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='tip' id='tip' style='width:90%;'>&nbsp;</div>\n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var language=1;\n"
        "var Json;\n"
        "var lang=\n"
        "{\n"
            "N01:['系统信息','System Information'],\n"
"\n"
            "N02:['修改操作员密码','Change Opt-Pwd'],\n"
            "N03:['原始密码','Old Password'],\n"
            "N04:['更新密码','New Password'],\n"
            "N05:['确认密码','Repeat Password'],\n"
            "N06:['修改','Modify'],\n"
"\n"
            "N07:['修改管理员密码','Change Admin-Pwd'],\n"
            "N08:['原始密码','Old Password'],\n"
            "N09:['更新密码','New Password'],\n"
            "N10:['确认密码','Repeat Password'],\n"
            "N11:['修改','Modify'],\n"
"\n"
            "N12:['修改维护员密码','Change Maint-Pwd'],\n"
            "N13:['原始密码','Old Password'],\n"
            "N14:['更新密码','New Password'],\n"
            "N15:['确认密码','Repeat Password'],\n"
            "N16:['修改','Modify'],\n"
            "\n"
            "N18:['请输入原密码！','Please enter the original password!'],\n"
            "N19:['请输入新密码！','Please enter your new password!'],\n"
            "N20:['请再次输入新密码！','Please re-enter the new password!'],\n"
            "N21:['密码格式错误，请输入4-7位的仅包含字母与数字的密码！','Password format error, please enter 4-7 only contain letters and numbers password!'],\n"
            "N22:['两次输入的新密码不同，请重新输入！','The two input new passwords are different, please re-enter!'],\n"
            "N23:['新密码与原密码相同，请重新输入新密码！','The new password is identical with the original password, please re-enter the new password!'],\n"
            "N24:['原密码错误，请重新输入！','The original password is incorrect, please re-enter it!'],\n"
            "N25:['密码修改成功！','Password changed successfully!'],\n"
            "N26:['密码修改失败！','Password changed failure!'],\n"
"\n"
            "N30:['版本信息','Version Information'],\n"
            "N31:['LCD版本号','LCD Version'],\n"
            "N32:['Web版本号','Web Version'],\n"
            "N33:['TOUCH版本号','TOUCH Version']\n"
        "};\n"
        "function Init()\n"
        "{\n"
            "var URL='s_010.html?time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);\n"
                    "if(Json.ID_0x0301==0x55)language=0; else language=1;\n"
         		"lang_init_ex(1,16);\n"
                    "lang_init_ex(30,33);\n"
"\n"
                    "$('oldpwd_operator').value='9999';\n"
                    "$('newpwd1_operator').value='9999';\n"
                    "$('newpwd2_operator').value='9999';\n"
"\n"
                    "$('oldpwd_admin').value='9999';\n"
                    "$('newpwd1_admin').value='9999';\n"
                    "$('newpwd2_admin').value='9999';\n"
"\n"
                    "$('oldpwd_maintriner').value='9999';\n"
                    "$('newpwd1_maintriner').value='9999';\n"
                    "$('newpwd2_maintriner').value='9999';\n"
"\n"
                    "if(Json.ID_0x0282 != 1){\n"
                        "$('title1').style.display='none';\n"
                        "$('title2').style.display='none';\n"
                        "$('title3').style.display='none';\n"
                        "$('pwds_operator').style.display='none';\n"
                        "$('pwds_admin').style.display='none';\n"
                        "$('pwds_maintriner').style.display='none';\n"
                    "}else{\n"
                        "$('title1').style.display='block';\n"
                        "$('title2').style.display='block';\n"
                        "$('title3').style.display='block';\n"
                        "$('pwds_operator').style.display='block';\n"
                        "$('pwds_admin').style.display='block';\n"
                        "$('pwds_maintriner').style.display='block';                      \n"
                    "}\n"
"\n"
         		"$('ID_0x0203').innerHTML=Json.ID_0x0203;\n"
         		"$('ID_0x0204').innerHTML=Json.ID_0x0204;\n"
         		"$('ID_0x0205').innerHTML=Json.ID_0x0205;\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}\n"
        "function ModifyPassword(A,B,C, USER)\n"
        "{\n"
            "var reg =/^[A-Za-z0-9]{4,7}$/;\n"
            "var a=A;\n"
            "var b=B;\n"
            "var c=C;\n"
            "var user = USER;\n"
            "if(a.value=='')\n"
            "{\n"
                "show_tip(lang.N18[language]);;a.focus();\n"
            "}\n"
            "else if(b.value=='')\n"
            "{\n"
                "show_tip(lang.N19[language]);b.focus();\n"
            "}\n"
            "else if(c.value=='')\n"
            "{\n"
                "show_tip(lang.N20[language]);c.focus();\n"
            "}\n"
            "else if(!(a.value.match(reg)&&b.value.match(reg)&&c.value.match(reg)))\n"
            "{\n"
                "show_tip(lang.N21[language]);\n"
                "if(!c.value.match(reg))\n"
                "{\n"
                    "c.value='9999';c.focus();\n"
                "}\n"
                "if(!b.value.match(reg))\n"
                "{\n"
                    "b.value='9999';b.focus();\n"
                "}\n"
                "if(!a.value.match(reg))\n"
                "{\n"
                    "a.value='9999';a.focus();\n"
                "}\n"
            "}\n"
            "else if(b.value!=c.value)\n"
            "{\n"
                "show_tip(lang.N22[language]);c.select();\n"
            "}\n"
            "else if(a.value==b.value)\n"
            "{\n"
                "show_tip(lang.N23[language]);b.value='';c.value='';b.focus();\n"
            "}\n"
            "else\n"
            "{\n"
                "var URL='PDM.html?'\n"
                "+'0x0282='+user \n"
                "+'&0x0283='+a.value\n"
                "+'&0x0284='+c.value\n"
                "+'&time='+Math.random();\n"
                "var xmlhttp;\n"
                "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                "xmlhttp.onreadystatechange=function()\n"
                "{\n"
                    "if(xmlhttp.readyState==4&&xmlhttp.status==200)\n"
                    "{\n"
                        "if(xmlhttp.responseText=='1')\n"
                        "{\n"
                            "show_tip('&nbsp;');\n"
                            "setTimeout('show_tip(lang.N25[language])',500);\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "a.value='9999';b.value='9999';c.value='9999';\n"
                            "show_tip(lang.N26[language]);\n"
                        "}\n"
                    "}\n"
                "};\n"
                "xmlhttp.open('GET',URL,true);\n"
                "xmlhttp.send();\n"
            "}\n"
        "}\n"
    "</script>\n"
"</html>\n"
};
#endif
