#ifndef _HTML_H_017_H_
#define _HTML_H_017_H_
static const char h_017[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
        "<script src='j_001.js' type='text/javascript'></script>\n"
        "<style type='text/css'>\n"
        "tr{height:27px;}\n"
        ".td1{text-align:left;padding-left:40px;}\n"
        ".td2{text-align:right;padding-right:5px;}\n"
        ".td3{text-align:right;padding-right:40px;}\n"
        ".div_tab{width:780px;height:45px;margin:0 auto;}\n"
        ".div_btn{width:80px;margin:0 auto;height:30px;text-align:right;margin-top:8px;float:left;}\n"
        ".div_text{width:80px;margin:0 auto;height:25px;text-align:right;margin-top:10px;float:left;}\n"
        ".div_span{width:40px;margin:0 auto;height:25px;font-size:16px;font-weight:bold;text-align:right;margin-top:12px;float:left;}\n"
        ".btn{width:75px;height:30px;}\n"
        ".PagerView{font-size:14px;font-family:tahoma,arial;font-weight:bold;color:#333;text-align:center;padding:8px;line-height:100%;}\n"
        ".PagerView span{color:#999;margin:0 1px;padding:3px 6px;border:1px solid #ccc;}\n"
        ".PagerView span.on{color:#fff;font-weight:bold;border:1px solid #666;background:#888;} \n"
        ".PagerView a{color:#00f;text-decoration:none;}\n"
        ".PagerView a span{color:#33f;border:1px solid #888;}\n"
        ".pager{width:780px;margin:0 auto;}\n"
        "</style>\n"
        "<script type='text/javascript'>\n"
            "var TAB1_1=\"tab1_1\";\n"
            "var DC1_1=new Array('N003','','N004','','N005','','N006','','N007','','N008','','N009','','N010','');\n"
            "var DC1_2=new Array('ID_0x0078','','ID_0x0071','','ID_0x0072','','ID_0x0073','','ID_0x0074','','ID_0x0075','','ID_0x0076','','ID_0x0077','');\n"
            "var DC1_3=new Array('','','V','','A','','V','','A','','Kw','','℃','','℃','');\n"
"\n"
            "var TAB1_2=\"tab1_2\";\n"
            "var DC2_1=new Array('N012','','N013','','N014','','N015','','N016','','N017','','N018','','N019','');\n"
            "var DC2_2=new Array('ID_0x008C','','ID_0x0085','','ID_0x0086','','ID_0x0087','','ID_0x0088','','ID_0x0089','','ID_0x008A','','ID_0x008B','');\n"
            "var DC2_3=new Array('','','V','','A','','V','','A','','Kw','','℃','','℃','');\n"
"\n"
            "var TAB1_3=\"tab1_3\";\n"
            "var DC3_1=new Array('N021','','N022','','N023','','N024','','N025','','N026','','N027','','N028','');\n"
            "var DC3_2=new Array('ID_0x00A0','','ID_0x0099','','ID_0x009A','','ID_0x009B','','ID_0x009C','','ID_0x009D','','ID_0x009E','','ID_0x009F','');\n"
            "var DC3_3=new Array('','','V','','A','','V','','A','','Kw','','℃','','℃','');\n"
"\n"
            "var TAB1_4=\"tab1_4\";\n"
            "var DC4_1=new Array('N030','','N031','','N032','','N033','','N034','','N035','','N036','','N037','');\n"
            "var DC4_2=new Array('ID_0x00B4','','ID_0x00AD','','ID_0x00AE','','ID_0x00AF','','ID_0x00B0','','ID_0x00B1','','ID_0x00B2','','ID_0x00B3','');\n"
            "var DC4_3=new Array('','','V','','A','','V','','A','','Kw','','℃','','℃','');\n"
"\n"
            "var TAB2_1=\"tab2_1\";\n"
            "var DC2_1_1=new Array('N101','','N102','','N103','','N104','','N105','','N106','','N107','','N108','');\n"
            "var DC2_1_2=new Array('ID_0x00F1','','ID_0x00F2','','ID_0x00F3','','ID_0x00F4','','ID_0x00F5','','ID_0x00F6','','ID_0x00F7','','ID_0x00F8','');\n"
            "var DC2_1_3=new Array('','','','','V','','A','','V','','A','','℃','','℃',''); \n"
"\n"
            "var TAB2_2=\"tab2_2\";\n"
            "var DC2_2_1=new Array('N111','','N112','','N113','','N114','','N115','','N116','','N117','','N118','');\n"
            "var DC2_2_2=new Array('ID_0x0101','','ID_0x0102','','ID_0x0103','','ID_0x0104','','ID_0x0105','','ID_0x0106','','ID_0x0107','','ID_0x0108','');\n"
            "var DC2_2_3=new Array('','','','','V','','A','','V','','A','','℃','','℃','');     \n"
"\n"
            "var TAB2_3=\"tab2_3\";\n"
            "var DC2_3_1=new Array('N121','','N122','','N123','','N124','','N125','','N126','','N127','','N128','');\n"
            "var DC2_3_2=new Array('ID_0x0111','','ID_0x0112','','ID_0x0113','','ID_0x0114','','ID_0x0115','','ID_0x0116','','ID_0x0117','','ID_0x0118','');\n"
            "var DC2_3_3=new Array('','','','','V','','A','','V','','A','','℃','','℃','');          \n"
"\n"
            "var TAB2_4=\"tab2_4\";\n"
            "var DC2_4_1=new Array('N131','','N132','','N133','','N134','','N135','','N136','','N137','','N138','');\n"
            "var DC2_4_2=new Array('ID_0x0121','','ID_0x0122','','ID_0x0123','','ID_0x0124','','ID_0x0125','','ID_0x0126','','ID_0x0127','','ID_0x0128','');\n"
            "var DC2_4_3=new Array('','','','','V','','A','','V','','A','','℃','','℃',''); \n"
            "function show_sT_ex(bid, tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' id='\"+bid+\"' style='width:90%;'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_line(id)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div id='\"+id+\"' class='line_long'></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_SUB(TAB,TR1,TR2,TR3)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<table id='\"+TAB+\"' width='90%' border='0' style='display:none;'>\";\n"
                "for(var i=0;i<TR1.length;i+=2)\n"
                "{\n"
                    "str+=\"<tr id='\"+TR1[i]+i+\"'>\";\n"
                        "str+=\"<td width='40%' class='td1 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR1[i]+\"'></span></td>\";\n"
                        "str+=\"<td width='30%' class='td2 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR2[i]+\"'></span></td>\";\n"
                        "str+=\"<td width='30%' class='td3 \"+(i%4?\"even\":\"odd\")+\"'>\"+TR3[i]+\"</td>\";\n"
                        "if(i+1!=TR1.length)\n"
                        "{\n"
                            "str+=\"<td width='40%' class='td1 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR1[i+1]+\"'></span></td>\";\n"
                            "str+=\"<td width='30%' class='td2 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR2[i+1]+\"'></span></td>\";\n"
                            "str+=\"<td width='30%' class='td3 \"+(i%4?\"even\":\"odd\")+\"'>\"+TR3[i+1]+\"</td>\";\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "str+=\"<td width='40%' class='td1 \"+(i%4?\"even\":\"odd\")+\"'></td>\";\n"
                            "str+=\"<td width='30%' class='td2 \"+(i%4?\"even\":\"odd\")+\"'></td>\";\n"
                            "str+=\"<td width='30%' class='td3 \"+(i%4?\"even\":\"odd\")+\"'></td>\";\n"
                        "}\n"
                        "\n"
                    "str+=\"</tr>\";\n"
                "}\n"
                "str+=\"</table>\";\n"
                "document.write(str);\n"
            "}\n"
        "var PagerView=function(id,AAA,BBB,CCC)\n"
            "{\n"
                "var self=this;\n"
                "this.id=id;\n"
                "this._pageCount=0;\n"
                "this._start=1;\n"
                "this._end=1;\n"
                "this.container=null;\n"
                "this.index=1;\n"
                "this.size=10;\n"
                "this.maxButtons=18;\n"
                "this.itemCount=0;\n"
                "this.onclick=function(index){return true;};\n"
                "this._onclick=function(index)\n"
                "{\n"
                    "var old=self.index;\n"
                    "self.index=index;\n"
                    "if(self.onclick(index)!==false)self.render();\n"
                    "else self.index=old;\n"
                "};\n"
                "this._calculate=function()\n"
                "{\n"
                    "self._pageCount=parseInt(Math.ceil(self.itemCount/self.size));\n"
                    "self.index=parseInt(self.index);\n"
                    "if(self.index>self._pageCount)self.index=self._pageCount;\n"
                    "if(self.index<1)self.index=1;\n"
                    "self._start=Math.max(1,self.index-parseInt(self.maxButtons/2));\n"
                    "self._end=Math.min(self._pageCount,self._start+self.maxButtons-1);\n"
                    "self._start=Math.max(1,self._end-self.maxButtons+1);\n"
                "};\n"
                "this.page=function(rows)\n"
                "{\n"
                    "self._calculate();\n"
                    "var s_num=(self.index-1)*self.size ;\n"
                    "var e_num=self.index*self.size;\n"
                    "return rows.slice(s_num,e_num);\n"
                "};\n"
                "this.render=function()\n"
                "{\n"
                    "var div=document.getElementById(self.id);\n"
                    "div.view=self;\n"
                    "self.container=div;\n"
                    "self._calculate();\n"
                    "var str='';\n"
                    "str+='<div class=\"PagerView\">\\n';\n"
                    "if(self._pageCount>1)\n"
                    "{\n"
                        "if(self.index!=1)\n"
                        "{\n"
                            "str+='<a href=\"javascript://1\"><span>|&lt;</span></a>';\n"
                            "str+='<a href=\"javascript://'+(self.index-1)+'\"><span>&lt;&lt;</span></a>';\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "str+='<span>|&lt;</span>';\n"
                            "str+='<span>&lt;&lt;</span>';\n"
                        "}\n"
                    "}\n"
                    "for(var i=self._start;i<=self._end;i++)\n"
                    "{\n"
                        "if(i==this.index)\n"
                        "{\n"
                            "if(i<10)str+='<span class=\"on\">'+'0'+i+\"</span>\";\n"
                            "else str+='<span class=\"on\">'+i+\"</span>\";\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "if(i<10)str+='<a href=\"javascript://'+i+'\"><span>'+'0'+i+\"</span></a>\";\n"
                            "else str+='<a href=\"javascript://'+i+'\"><span>'+i+\"</span></a>\";\n"
                        "}\n"
                    "}\n"
                    "if(self._pageCount>1)\n"
                    "{\n"
                        "if(self.index!=self._pageCount)\n"
                        "{\n"
                            "str+='<a href=\"javascript://'+(self.index+1)+'\"><span>&gt;&gt;</span></a>';\n"
                            "str+='<a href=\"javascript://'+self._pageCount+'\"><span>&gt;|</span></a>';\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "str+='<span>&gt;&gt;</span>';\n"
                            "str+='<span>&gt;|</span>';\n"
                        "}\n"
                    "}\n"
                    "str+=AAA+self._pageCount+BBB+self.itemCount+CCC;\n"
                    "str+='</div><!--/.pagerView-->\\n';\n"
                    "self.container.innerHTML=str;\n"
                    "var a_list=self.container.getElementsByTagName('a');\n"
                    "for(var i=0;i<a_list.length;i++)\n"
                    "{\n"
                        "a_list[i].onclick=function()\n"
                        "{\n"
                            "var index=this.getAttribute('href');\n"
                            "if(index!=undefined&&index!='')\n"
                            "{\n"
                                "index=parseInt(index.replace('javascript://',''));\n"
                                "self._onclick(index);\n"
                            "}\n"
                            "return false;\n"
                        "};\n"
                    "}\n"
                "};\n"
            "};\n"
        "</script>\n"
    "</head>\n"
    "<body onload='Init();'>\n"
        "<script type='text/javascript'>\n"
            "show_T('N001');\n"
        "</script>        \n"
        "<div id='pager' width='90%' style='padding-left:5%;float:left;'></div>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N002');\n"
            "show_SUB(TAB1_1,DC1_1,DC1_2,DC1_3);\n"
            "show_SUB(TAB2_1,DC2_1_1,DC2_1_2,DC2_1_3);\n"
        "</script>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>      \n"
        "<script type='text/javascript'>\n"
            "show_sT('N011');\n"
            "show_SUB(TAB1_2,DC2_1,DC2_2,DC2_3);\n"
            "show_SUB(TAB2_2,DC2_2_1,DC2_2_2,DC2_2_3);\n"
        "</script>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>   \n"
        "<script type='text/javascript'>\n"
            "show_sT('N020');\n"
            "show_SUB(TAB1_3,DC3_1,DC3_2,DC3_3);\n"
            "show_SUB(TAB2_3,DC2_3_1,DC2_3_2,DC2_3_3);\n"
        "</script>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>   \n"
        "<script type='text/javascript'>\n"
            "show_sT_ex('tmode4', 'N029');\n"
             //show_SUB(TAB1_4,DC4_1,DC4_2,DC4_3);
            "show_SUB(TAB2_4,DC2_4_1,DC2_4_2,DC2_4_3);\n"
            "show_line('line');\n"
        "</script>\n"
        "<div class='blank'></div>   \n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var $=function(o){return document.getElementById(o);};\n"
        "var language=0;\n"
        "var Json;\n"
        "var CurDcdc;\n"
        "var lang=\n"
        "{\n"
            "N001:['光伏控制器信息','DCDC Information'],\n"
"\n"
            "N002:['模块 1#','Module 1#'],\n"
            "N003:['状态','Status'],\n"
            "N004:['阵列电压','Array V'],\n"
            "N005:['阵列电流','Array I'],\n"
            "N006:['电池电压','Bat. V'],\n"
            "N007:['充电电流','Charge I'],\n"
            "N008:['充电功率','Charge p'],\n"
            "N009:['机内温度','Inside T'],\n"
            "N010:['电池温度','Bat. T'],\n"
"\n"
            "N011:['模块 2#','Module 2#'],\n"
            "N012:['状态','Status'],\n"
            "N013:['阵列电压','Array V'],\n"
            "N014:['阵列电流','Array I'],\n"
            "N015:['电池电压','Bat. V'],\n"
            "N016:['充电电流','Charge I'],\n"
            "N017:['充电功率','Charge p'],\n"
            "N018:['机内温度','Inside T'],\n"
            "N019:['电池温度','Bat. T'],   \n"
"\n"
            "N020:['模块 3#','Module 3#'],\n"
            "N021:['状态','Status'],\n"
            "N022:['阵列电压','Array V'],\n"
            "N023:['阵列电流','Array I'],\n"
            "N024:['电池电压','Bat. V'],\n"
            "N025:['充电电流','Charge I'],\n"
            "N026:['充电功率','Charge p'],\n"
            "N027:['机内温度','Inside T'],\n"
            "N028:['电池温度','Bat. T'],  \n"
"\n"
            "N029:['模块 4#','Module 4#'],\n"
            "N030:['状态','Status'],\n"
            "N031:['阵列电压','Array V'],\n"
            "N032:['阵列电流','Array I'],\n"
            "N033:['电池电压','Bat. V'],\n"
            "N034:['充电电流','Charge I'],\n"
            "N035:['充电功率','Charge p'],\n"
            "N036:['机内温度','Inside T'],\n"
            "N037:['电池温度','Bat. T'],             \n"
                               "\n"
            "N038:['第：','No.：'],\n"
            "N039:['共：','All：'],\n"
"\n"
            "N060:['运行','Runing'],\n"
            "N061:['待机','Standy'],\n"
            "N062:['停机','Stoped'],\n"
            "N063:['故障','Fault'],\n"
            "N064:['初始状态','Initial'],\n"
            "N065:['紧急停机','EMG-Stop'],\n"
            "N066:['无通讯','Com fail'],\n"
"\n"
            "N101:['状态','Status'],\n"
            "N102:['故障状态','Fault state'],\n"
            "N103:['母线侧电压','Bus bar V'],\n"
            "N104:['母线侧电流','Bus bar I'],\n"
            "N105:['蓄电池侧电压','Bat.V'],\n"
            "N106:['蓄电池侧电流','Bat.I'],\n"
            "N107:['模块1温度','Module 1# T'],\n"
            "N108:['模块2温度','Module 2# T'],    \n"
"\n"
            "N111:['状态','Status'],\n"
            "N112:['故障状态','Fault state'],\n"
            "N113:['母线侧电压','Bus bar V'],\n"
            "N114:['母线侧电流','Bus bar I'],\n"
            "N115:['蓄电池侧电压','Bat.V'],\n"
            "N116:['蓄电池侧电流','Bat.I'],\n"
            "N117:['模块1温度','Module 1# T'],\n"
            "N118:['模块2温度','Module 2# T'],   \n"
"\n"
            "N121:['状态','Status'],\n"
            "N122:['故障状态','Fault state'],\n"
            "N123:['母线侧电压','Bus bar V'],\n"
            "N124:['母线侧电流','Bus bar I'],\n"
            "N125:['蓄电池侧电压','Bat.V'],\n"
            "N126:['蓄电池侧电流','Bat.I'],\n"
            "N127:['模块1温度','Module 1# T'],\n"
            "N128:['模块2温度','Module 2# T'], \n"
"\n"
            "N131:['状态','Status'],\n"
            "N132:['故障状态','Fault state'],\n"
            "N133:['母线侧电压','Bus bar V'],\n"
            "N134:['母线侧电流','Bus bar I'],\n"
            "N135:['蓄电池侧电压','Bat.V'],\n"
            "N136:['蓄电池侧电流','Bat.I'],\n"
            "N137:['模块1温度','Module 1# T'],\n"
            "N138:['模块2温度','Module 2# T'],  \n"
"\n"
            "N160:['停机','Stoped'],\n"
            "N161:['恒流充电','Const I charge'],\n"
            "N162:['恒流放电','Const I discharge'],\n"
            "N163:['恒功率充电','Const P charge'],\n"
            "N164:['恒功率放电','Const P discharge'],\n"
            "N165:['停机','Stoped'],\n"
            "N166:['待机','Standy'],\n"
            "N167:['紧急停机','EMG-Stop'],\n"
"\n"
            "N170:['正常','Normal'],\n"
            "N171:['故障','Fault'],\n"
"\n"
            "N500:['一共','Total '],\n"
            "N501:['页，共',' Pages, '],\n"
            "N502:['页，共',' Page, '],\n"
            "N503:['台',' Nums'],\n"
            "N504:['台',' Num']\n"
        "};\n"
        "var E_id=new Array(0,1,2,3,4,5,6);\n"
        "var E_name=new Array('60','61','62','63','64','65','66');\n"
"\n"
        "var E2_id=new Array(0,1,2,3,4,5,6,7);\n"
        "var E2_name=new Array('160','161','162','163','164','165','166','167');   \n"
"\n"
        "var E3_id=new Array(0,1);\n"
        "var E3_name=new Array('170','171');         \n"
"\n"
         //获取串口PVS数据
        "function Get_Dcdc_Index(index)\n"
        "{\n"
            "eval('var URL=\\'s_017.html?0x'+(0+index).toString(16).toUpperCase()+'&time=\\'+Math.random();');\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);   \n"
                    "if(Json.ID_0x02B2 == 0)\n"
                    "{\n"
                        "if(Json.ID_0x038B == 1)\n"
                        "{\n"
                            "$('ID_0x0071').innerHTML=(Json.ID_0x0071/10.0).toFixed(1);\n"
                            "$('ID_0x0072').innerHTML=(Json.ID_0x0072/10.0).toFixed(1);\n"
                            "$('ID_0x0073').innerHTML=(Json.ID_0x0073/10.0).toFixed(1);\n"
                            "$('ID_0x0074').innerHTML=(Json.ID_0x0074/10.0).toFixed(1);\n"
                            "$('ID_0x0075').innerHTML=(Json.ID_0x0075/10.0).toFixed(1);\n"
                            "$('ID_0x0076').innerHTML=(Json.ID_0x0076/10.0).toFixed(1);\n"
                            "$('ID_0x0077').innerHTML=(Json.ID_0x0077/10.0).toFixed(1);\n"
"\n"
                            "$('ID_0x0085').innerHTML=(Json.ID_0x0085/10.0).toFixed(1);\n"
                            "$('ID_0x0086').innerHTML=(Json.ID_0x0086/10.0).toFixed(1);\n"
                            "$('ID_0x0087').innerHTML=(Json.ID_0x0087/10.0).toFixed(1);\n"
                            "$('ID_0x0088').innerHTML=(Json.ID_0x0088/10.0).toFixed(1);\n"
                            "$('ID_0x0089').innerHTML=(Json.ID_0x0089/10.0).toFixed(1);\n"
                            "$('ID_0x008A').innerHTML=(Json.ID_0x008A/10.0).toFixed(1);\n"
                            "$('ID_0x008B').innerHTML=(Json.ID_0x008B/10.0).toFixed(1);\n"
"\n"
                            "$('ID_0x0099').innerHTML=(Json.ID_0x0099/10.0).toFixed(1);\n"
                            "$('ID_0x009A').innerHTML=(Json.ID_0x009A/10.0).toFixed(1);\n"
                            "$('ID_0x009B').innerHTML=(Json.ID_0x009B/10.0).toFixed(1);\n"
                            "$('ID_0x009C').innerHTML=(Json.ID_0x009C/10.0).toFixed(1);\n"
                            "$('ID_0x009D').innerHTML=(Json.ID_0x009D/10.0).toFixed(1);\n"
                            "$('ID_0x009E').innerHTML=(Json.ID_0x009E/10.0).toFixed(1);\n"
                            "$('ID_0x009F').innerHTML=(Json.ID_0x009F/10.0).toFixed(1);  \n"
                            "\n"
                             //$('ID_0x00AD').innerHTML=(Json.ID_0x00AD/10.0).toFixed(1);
                             //$('ID_0x00AE').innerHTML=(Json.ID_0x00AE/10.0).toFixed(1);
                             //$('ID_0x00AF').innerHTML=(Json.ID_0x00AF/10.0).toFixed(1);
                             //$('ID_0x00B0').innerHTML=(Json.ID_0x00B0/10.0).toFixed(1);
                             //$('ID_0x00B1').innerHTML=(Json.ID_0x00B1/10.0).toFixed(1);
                             //$('ID_0x00B2').innerHTML=(Json.ID_0x00B2/10.0).toFixed(1);
                             //$('ID_0x00B3').innerHTML=(Json.ID_0x00B3/10.0).toFixed(1);      
"\n"
                            "for(var k=0;k<E_id.length;k++)if(Json.ID_0x0078==E_id[k])eval(\"$('ID_0x0078').innerHTML=lang.N0\"+E_name[k]+\"[language];\");\n"
                            "for(var k=0;k<E_id.length;k++)if(Json.ID_0x008C==E_id[k])eval(\"$('ID_0x008C').innerHTML=lang.N0\"+E_name[k]+\"[language];\");\n"
                            "for(var k=0;k<E_id.length;k++)if(Json.ID_0x00A0==E_id[k])eval(\"$('ID_0x00A0').innerHTML=lang.N0\"+E_name[k]+\"[language];\");\n"
                             //for(var k=0;k<E_id.length;k++)if(Json.ID_0x00B4==E_id[k])eval(\"$('ID_0x00B4').innerHTML=lang.N0\"+E_name[k]+\"[language];\");  
"\n"
                            "if(Json.ID_0x0078 == 6) \n"
                            "{\n"
                                 "document.getElementById('ID_0x0078').style.color='#ff6820';\n"
                                 "document.getElementById('ID_0x0078').style.fontWeight='bold';                    \n"
                            "}\n"
                            "else if(Json.ID_0x0078 == 3 || Json.ID_0x0078 == 5)\n"
                            "{\n"
                                "document.getElementById('ID_0x0078').style.color='#ff0000';\n"
                                "document.getElementById('ID_0x0078').style.fontWeight='bold';\n"
                            "}\n"
                            "else\n"
                            "{\n"
                                "document.getElementById('ID_0x0078').style.fontWeight='normal';\n"
                                "document.getElementById('ID_0x0078').style.color='#000';\n"
                            "}\n"
"\n"
                            "if(Json.ID_0x008C == 6) \n"
                            "{\n"
                                 "document.getElementById('ID_0x008C').style.color='#ff6820';\n"
                                 "document.getElementById('ID_0x008C').style.fontWeight='bold';                    \n"
                            "}\n"
                            "else if(Json.ID_0x008C == 3 || Json.ID_0x008C == 5)\n"
                            "{\n"
                                "document.getElementById('ID_0x008C').style.color='#ff0000';\n"
                                "document.getElementById('ID_0x008C').style.fontWeight='bold';\n"
                            "}\n"
                            "else\n"
                            "{\n"
                                "document.getElementById('ID_0x008C').style.fontWeight='normal';\n"
                                "document.getElementById('ID_0x008C').style.color='#000';\n"
                            "}\n"
"\n"
                            "if(Json.ID_0x00A0 == 6) \n"
                            "{\n"
                                 "document.getElementById('ID_0x00A0').style.color='#ff6820';\n"
                                 "document.getElementById('ID_0x00A0').style.fontWeight='bold';                    \n"
                            "}\n"
                            "else if(Json.ID_0x00A0 == 3 || Json.ID_0x00A0 == 5)\n"
                            "{\n"
                                "document.getElementById('ID_0x00A0').style.color='#ff0000';\n"
                                "document.getElementById('ID_0x00A0').style.fontWeight='bold';\n"
                            "}\n"
                            "else\n"
                            "{\n"
                                "document.getElementById('ID_0x00A0').style.fontWeight='normal';\n"
                                "document.getElementById('ID_0x00A0').style.color='#000';\n"
                            "}\n"
                        "}\n"
                        "else if(Json.ID_0x038B == 2)\n"
                        "{\n"
                            "$('ID_0x00F3').innerHTML=(Json.ID_0x00F3/10.0).toFixed(1);\n"
                            "$('ID_0x00F4').innerHTML=(Json.ID_0x00F4/10.0).toFixed(1);\n"
                            "$('ID_0x00F5').innerHTML=(Json.ID_0x00F5/10.0).toFixed(1);\n"
                            "$('ID_0x00F6').innerHTML=(Json.ID_0x00F6/10.0).toFixed(1);\n"
                            "$('ID_0x00F7').innerHTML=(Json.ID_0x00F7/10.0).toFixed(1);\n"
                            "$('ID_0x00F8').innerHTML=(Json.ID_0x00F8/10.0).toFixed(1);\n"
"\n"
                            "$('ID_0x0103').innerHTML=(Json.ID_0x0103/10.0).toFixed(1);\n"
                            "$('ID_0x0104').innerHTML=(Json.ID_0x0104/10.0).toFixed(1);\n"
                            "$('ID_0x0105').innerHTML=(Json.ID_0x0105/10.0).toFixed(1);\n"
                            "$('ID_0x0106').innerHTML=(Json.ID_0x0106/10.0).toFixed(1);\n"
                            "$('ID_0x0107').innerHTML=(Json.ID_0x0107/10.0).toFixed(1);\n"
                            "$('ID_0x0108').innerHTML=(Json.ID_0x0108/10.0).toFixed(1);\n"
"\n"
                            "$('ID_0x0113').innerHTML=(Json.ID_0x0113/10.0).toFixed(1);\n"
                            "$('ID_0x0114').innerHTML=(Json.ID_0x0114/10.0).toFixed(1);\n"
                            "$('ID_0x0115').innerHTML=(Json.ID_0x0115/10.0).toFixed(1);\n"
                            "$('ID_0x0116').innerHTML=(Json.ID_0x0116/10.0).toFixed(1);\n"
                            "$('ID_0x0117').innerHTML=(Json.ID_0x0117/10.0).toFixed(1);\n"
                            "$('ID_0x0118').innerHTML=(Json.ID_0x0118/10.0).toFixed(1);  \n"
"\n"
                            "$('ID_0x0123').innerHTML=(Json.ID_0x0123/10.0).toFixed(1);\n"
                            "$('ID_0x0124').innerHTML=(Json.ID_0x0124/10.0).toFixed(1);\n"
                            "$('ID_0x0125').innerHTML=(Json.ID_0x0125/10.0).toFixed(1);\n"
                            "$('ID_0x0126').innerHTML=(Json.ID_0x0126/10.0).toFixed(1);\n"
                            "$('ID_0x0127').innerHTML=(Json.ID_0x0127/10.0).toFixed(1);\n"
                            "$('ID_0x0128').innerHTML=(Json.ID_0x0128/10.0).toFixed(1);   \n"
"\n"
                            "for(var k=0;k<E2_id.length;k++)if(Json.ID_0x00F1==E2_id[k])eval(\"$('ID_0x00F1').innerHTML=lang.N\"+E2_name[k]+\"[language];\");  \n"
                            "for(var k=0;k<E2_id.length;k++)if(Json.ID_0x0101==E2_id[k])eval(\"$('ID_0x0101').innerHTML=lang.N\"+E2_name[k]+\"[language];\");\n"
                            "for(var k=0;k<E2_id.length;k++)if(Json.ID_0x0111==E2_id[k])eval(\"$('ID_0x0111').innerHTML=lang.N\"+E2_name[k]+\"[language];\");\n"
                            "for(var k=0;k<E2_id.length;k++)if(Json.ID_0x0121==E2_id[k])eval(\"$('ID_0x0121').innerHTML=lang.N\"+E2_name[k]+\"[language];\");\n"
                            "for(var k=0;k<E3_id.length;k++)if(Json.ID_0x00F2==E3_id[k])eval(\"$('ID_0x00F2').innerHTML=lang.N\"+E3_name[k]+\"[language];\"); \n"
                            "for(var k=0;k<E3_id.length;k++)if(Json.ID_0x0102==E3_id[k])eval(\"$('ID_0x0102').innerHTML=lang.N\"+E3_name[k]+\"[language];\"); \n"
                            "for(var k=0;k<E3_id.length;k++)if(Json.ID_0x0112==E3_id[k])eval(\"$('ID_0x0112').innerHTML=lang.N\"+E3_name[k]+\"[language];\"); \n"
                            "for(var k=0;k<E3_id.length;k++)if(Json.ID_0x0122==E3_id[k])eval(\"$('ID_0x0122').innerHTML=lang.N\"+E3_name[k]+\"[language];\"); \n"
"\n"
                            "if(Json.ID_0x00F1 == 7)\n"
                            "{\n"
                                "document.getElementById('ID_0x00F1').style.color='#ff0000';\n"
                                "document.getElementById('ID_0x00F1').style.fontWeight='bold';\n"
                            "}\n"
                            "else\n"
                            "{\n"
                                "document.getElementById('ID_0x00F1').style.fontWeight='normal';\n"
                                "document.getElementById('ID_0x00F1').style.color='#000';\n"
                            "}\n"
"\n"
                            "if(Json.ID_0x0101 == 7)\n"
                            "{\n"
                                "document.getElementById('ID_0x0101').style.color='#ff0000';\n"
                                "document.getElementById('ID_0x0101').style.fontWeight='bold';\n"
                            "}\n"
                            "else\n"
                            "{\n"
                                "document.getElementById('ID_0x0101').style.fontWeight='normal';\n"
                                "document.getElementById('ID_0x0101').style.color='#000';\n"
                            "}\n"
"\n"
                            "if(Json.ID_0x0111 == 7)\n"
                            "{\n"
                                "document.getElementById('ID_0x0111').style.color='#ff0000';\n"
                                "document.getElementById('ID_0x0111').style.fontWeight='bold';\n"
                            "}\n"
                            "else\n"
                            "{\n"
                                "document.getElementById('ID_0x0111').style.fontWeight='normal';\n"
                                "document.getElementById('ID_0x0111').style.color='#000';\n"
                            "}\n"
"\n"
                            "if(Json.ID_0x0121 == 7)\n"
                            "{\n"
                                "document.getElementById('ID_0x0121').style.color='#ff0000';\n"
                                "document.getElementById('ID_0x0121').style.fontWeight='bold';\n"
                            "}\n"
                            "else\n"
                            "{\n"
                                "document.getElementById('ID_0x0121').style.fontWeight='normal';\n"
                                "document.getElementById('ID_0x0121').style.color='#000';\n"
                            "}\n"
"\n"
                            "if(Json.ID_0x00F2 == 1)\n"
                            "{\n"
                                "document.getElementById('ID_0x00F2').style.color='#ff0000';\n"
                                "document.getElementById('ID_0x00F2').style.fontWeight='bold';\n"
                            "}\n"
                            "else\n"
                            "{\n"
                                "document.getElementById('ID_0x00F2').style.fontWeight='normal';\n"
                                "document.getElementById('ID_0x00F2').style.color='#000';\n"
                            "}\n"
"\n"
                            "if(Json.ID_0x0102 == 1)\n"
                            "{\n"
                                "document.getElementById('ID_0x0102').style.color='#ff0000';\n"
                                "document.getElementById('ID_0x0102').style.fontWeight='bold';\n"
                            "}\n"
                            "else\n"
                            "{\n"
                                "document.getElementById('ID_0x0102').style.fontWeight='normal';\n"
                                "document.getElementById('ID_0x0102').style.color='#000';\n"
                            "}\n"
"\n"
                            "if(Json.ID_0x0112 == 1)\n"
                            "{\n"
                                "document.getElementById('ID_0x0112').style.color='#ff0000';\n"
                                "document.getElementById('ID_0x0112').style.fontWeight='bold';\n"
                            "}\n"
                            "else\n"
                            "{\n"
                                "document.getElementById('ID_0x0112').style.fontWeight='normal';\n"
                                "document.getElementById('ID_0x0112').style.color='#000';\n"
                            "}\n"
"\n"
                            "if(Json.ID_0x0122 == 1)\n"
                            "{\n"
                                "document.getElementById('ID_0x0122').style.color='#ff0000';\n"
                                "document.getElementById('ID_0x0122').style.fontWeight='bold';\n"
                            "}\n"
                            "else\n"
                            "{\n"
                                "document.getElementById('ID_0x0122').style.fontWeight='normal';\n"
                                "document.getElementById('ID_0x0122').style.color='#000';\n"
                            "}\n"
                        "}\n"
                    "}\n"
                    "else\n"
                    "{\n"
                        "if(Json.ID_0x038B == 1)\n"
                        "{\n"
                            "$('ID_0x0071').innerHTML='--';\n"
                            "$('ID_0x0072').innerHTML='--';\n"
                            "$('ID_0x0073').innerHTML='--';\n"
                            "$('ID_0x0074').innerHTML='--';\n"
                            "$('ID_0x0075').innerHTML='--';\n"
                            "$('ID_0x0076').innerHTML='--';\n"
                            "$('ID_0x0077').innerHTML='--';\n"
"\n"
                            "$('ID_0x0085').innerHTML='--';\n"
                            "$('ID_0x0086').innerHTML='--';\n"
                            "$('ID_0x0087').innerHTML='--';\n"
                            "$('ID_0x0088').innerHTML='--';\n"
                            "$('ID_0x0089').innerHTML='--';\n"
                            "$('ID_0x008A').innerHTML='--';\n"
                            "$('ID_0x008B').innerHTML='--';\n"
"\n"
                            "$('ID_0x0099').innerHTML='--';\n"
                            "$('ID_0x009A').innerHTML='--';\n"
                            "$('ID_0x009B').innerHTML='--';\n"
                            "$('ID_0x009C').innerHTML='--';\n"
                            "$('ID_0x009D').innerHTML='--';\n"
                            "$('ID_0x009E').innerHTML='--';\n"
                            "$('ID_0x009F').innerHTML='--';  \n"
                            "\n"
                             //$('ID_0x00AD').innerHTML=(Json.ID_0x00AD/10.0).toFixed(1);
                             //$('ID_0x00AE').innerHTML=(Json.ID_0x00AE/10.0).toFixed(1);
                             //$('ID_0x00AF').innerHTML=(Json.ID_0x00AF/10.0).toFixed(1);
                             //$('ID_0x00B0').innerHTML=(Json.ID_0x00B0/10.0).toFixed(1);
                             //$('ID_0x00B1').innerHTML=(Json.ID_0x00B1/10.0).toFixed(1);
                             //$('ID_0x00B2').innerHTML=(Json.ID_0x00B2/10.0).toFixed(1);
                             //$('ID_0x00B3').innerHTML=(Json.ID_0x00B3/10.0).toFixed(1);      
"\n"
                            "$('ID_0x0078').innerHTML='--';\n"
                            "document.getElementById('ID_0x0078').style.fontWeight='normal';\n"
                            "document.getElementById('ID_0x0078').style.color='#000';\n"
                            "$('ID_0x008C').innerHTML='--';\n"
                            "document.getElementById('ID_0x008C').style.fontWeight='normal';\n"
                            "document.getElementById('ID_0x008C').style.color='#000';\n"
                            "$('ID_0x00A0').innerHTML='--'; \n"
                            "document.getElementById('ID_0x00A0').style.fontWeight='normal';\n"
                            "document.getElementById('ID_0x00A0').style.color='#000';\n"
                        "}\n"
                        "else if(Json.ID_0x038B == 2)\n"
                        "{\n"
                            "$('ID_0x00F3').innerHTML='--';\n"
                            "$('ID_0x00F4').innerHTML='--';\n"
                            "$('ID_0x00F5').innerHTML='--';\n"
                            "$('ID_0x00F6').innerHTML='--';\n"
                            "$('ID_0x00F7').innerHTML='--';\n"
                            "$('ID_0x00F8').innerHTML='--';\n"
"\n"
                            "$('ID_0x0103').innerHTML='--';\n"
                            "$('ID_0x0104').innerHTML='--';\n"
                            "$('ID_0x0105').innerHTML='--';\n"
                            "$('ID_0x0106').innerHTML='--';\n"
                            "$('ID_0x0107').innerHTML='--';\n"
                            "$('ID_0x0108').innerHTML='--';\n"
"\n"
                            "$('ID_0x0113').innerHTML='--';\n"
                            "$('ID_0x0114').innerHTML='--';\n"
                            "$('ID_0x0115').innerHTML='--';\n"
                            "$('ID_0x0116').innerHTML='--';\n"
                            "$('ID_0x0117').innerHTML='--';\n"
                            "$('ID_0x0118').innerHTML='--'; \n"
"\n"
                            "$('ID_0x0123').innerHTML='--';\n"
                            "$('ID_0x0124').innerHTML='--';\n"
                            "$('ID_0x0125').innerHTML='--';\n"
                            "$('ID_0x0126').innerHTML='--';\n"
                            "$('ID_0x0127').innerHTML='--';\n"
                            "$('ID_0x0128').innerHTML='--';   \n"
"\n"
                            "$('ID_0x00F1').innerHTML='--';  \n"
                            "document.getElementById('ID_0x00F1').style.fontWeight='normal';\n"
                            "document.getElementById('ID_0x00F1').style.color='#000';\n"
                            "$('ID_0x0101').innerHTML='--';\n"
                            "document.getElementById('ID_0x0101').style.fontWeight='normal';\n"
                            "document.getElementById('ID_0x0101').style.color='#000';\n"
                            "$('ID_0x0111').innerHTML='--';\n"
                            "document.getElementById('ID_0x0111').style.fontWeight='normal';\n"
                            "document.getElementById('ID_0x0111').style.color='#000';\n"
                            "$('ID_0x0121').innerHTML='--';\n"
                            "document.getElementById('ID_0x0121').style.fontWeight='normal';\n"
                            "document.getElementById('ID_0x0121').style.color='#000';\n"
                            "$('ID_0x00F2').innerHTML='--'; \n"
                            "document.getElementById('ID_0x00F2').style.fontWeight='normal';\n"
                            "document.getElementById('ID_0x00F2').style.color='#000';\n"
                            "$('ID_0x0102').innerHTML='--'; \n"
                            "document.getElementById('ID_0x0102').style.fontWeight='normal';\n"
                            "document.getElementById('ID_0x0102').style.color='#000';\n"
                            "$('ID_0x0112').innerHTML='--'; \n"
                            "document.getElementById('ID_0x0112').style.fontWeight='normal';\n"
                            "document.getElementById('ID_0x0112').style.color='#000';\n"
                            "$('ID_0x0122').innerHTML='--'; \n"
                            "document.getElementById('ID_0x0122').style.fontWeight='normal';\n"
                            "document.getElementById('ID_0x0122').style.color='#000';\n"
                        "}\n"
                    "}                                       \n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
             //alert(URL);   
        "}    \n"
         //整数补齐位数,希望输出的数字长度是固定的，假设为10，如果数字为123，则输出0000000123
        "function PrefixInteger(num, length) {  return (num/Math.pow(10,length)).toFixed(length).substr(2);}    \n"
        "function ajax()\n"
        "{\n"
            "var URL='s_017.html?time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);           \n"
                    "if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                    "for(var i=1;i<=29;i++){eval('$(\\'N0'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N0'+(i<10?'0'+i:i)+'[language];');}\n"
                    "for(var i=101;i<=108;i++){eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}  \n"
                    "for(var i=111;i<=118;i++){eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');} \n"
                    "for(var i=121;i<=128;i++){eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');} \n"
                    "for(var i=131;i<=138;i++){eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}                               \n"
"\n"
                    "if(Json.ID_0x038B == 1){\n"
                        "$('tab1_1').style.display='block';\n"
                        "$('tab1_2').style.display='block';\n"
                        "$('tab1_3').style.display='block';\n"
                         //$('tab1_4').style.display='block';    
                        "$('tab2_1').style.display='none';\n"
                        "$('tab2_2').style.display='none';\n"
                        "$('tab2_3').style.display='none';\n"
                        "$('tab2_4').style.display='none';  \n"
                        "$('tmode4').style.display='none';  \n"
                        "$('line').style.display='none';                              \n"
                    "}else if(Json.ID_0x038B == 2){\n"
                        "$('tab1_1').style.display='none';\n"
                        "$('tab1_2').style.display='none';\n"
                        "$('tab1_3').style.display='none';\n"
                         //$('tab1_4').style.display='none';    
                        "$('tab2_1').style.display='block';\n"
                        "$('tab2_2').style.display='block';\n"
                        "$('tab2_3').style.display='block';\n"
                        "$('tab2_4').style.display='block';   \n"
                        "$('tmode4').style.display='block'; \n"
                        "$('line').style.display='block';                                            \n"
                    "}\n"
"\n"
                    "if(Json.ID_0x0352==0){\n"
                        "$('pager').style.display='none';\n"
                    "}else{\n"
                        "$('pager').style.display='block';\n"
                        "mpager=new PagerView('pager',lang.N500[language],lang.N502[language],lang.N503[language]);\n"
                    "}\n"
  "\n"
                    "mpager.itemCount=Json.ID_0x0352;\n"
                    "mpager.size=1;\n"
                    "mpager.index=1; \n"
                    "CurDcdc = mpager.index;\n"
                    "Get_Dcdc_Index(CurDcdc);               \n"
                    "mpager.onclick=function(index)\n"
                    "{  \n"
                        "CurDcdc = index;\n"
                         //获取PCS储能逆变器信息
                        "Get_Dcdc_Index(index);\n"
                    "};\n"
                     //index显示更新
                    "mpager.render();    \n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}        \n"
        "function Init()\n"
        "{\n"
            "ajax();\n"
            "setInterval('Get_Dcdc_Index(CurDcdc)', 2000);\n"
        "}    \n"
    "</script>\n"
"</html>\n"
};
#endif
