#ifndef _HTML_H_011_H_
#define _HTML_H_011_H_
static const char h_011[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
 "<head>\n"
	"<meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'/>\n"
 	"<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
 	"<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
 	"<script src='j_002.js' type='text/javascript'></script>\n"
 	"<script language='javascript' type='text/javascript'>\n"
 		"var language=1;\n"
 		"var lang=\n"
 		"{\n"
 			"N01:['序号','No.'],\n"
 			"N02:['日期&amp;时间','Date&amp;Time'],\n"
 			"N03:['储能型号','PCS Type'],\n"
 			"N04:['系统额定功率','Sys Rated Power'],\n"
 			"N05:['并网使能','Grid Enable'],\n"
 			"N06:['总线类型','Bus Type'],\n"
 			"N07:['分时使能','Time Enable'],\n"
 			"N08:['工作状态','Work Status'],\n"
 			"N09:['电网状态','Grid Status'],\n"
 			"N10:['电网电压','Grid Voltage'],\n"
 			"N11:['电网频率','Grid Frequency'],\n"
 			"N12:['电网功率','Grid Power'],		\n"
 			"N13:['电网接触器状态','Grid Contactor Status'],\n"
 			"N14:['电网接触器故障状态','Grid COntactor Fault Status'],\n"
 			"N15:['微网接触器状态','MGrid Contactor Status'],\n"
 			"N16:['微网接触器故障状态','MGrid COntactor Fault Status'],\n"
 			"N17:['运行模式','Running Mode'],\n"
 			"N18:['功率控制模式','Power Control Mode'],\n"
 			"N19:['运行功率','Operating Power'],\n"
 			"N20:['储能并网工作模式','PCS Working Mode'],\n"
 			"N21:['储能逆变器有功功率','PCS Active Power'],\n"
 			"N22:['微网电压','MGrid Voltage'],\n"
 			"N23:['微网频率','MGrid Frequency'],\n"
 			"N24:['光伏逆变器功率','PV Power'],\n"
 			"N25:['光伏逆变器电压','PV Voltage'],\n"
 			"N26:['负载功率','Load Power'],\n"
 			"N27:['负载电压','Load Voltage'],\n"
 			"N28:['电池最大电压','Battery Max Voltage'],\n"
 			"N29:['电池最小电压','Battery Max Voltage'],\n"
 			"N30:['电池最大SOC','Battery Max SOC'],\n"
 			"N31:['电池最小SOC','Battery Min SOC']\n"
 		"};\n"
 		"var State=\n"
 		"{\n"
                "N0:['',''],\n"
                "N1:['初始停机','Initial Stop'],\n"
                "N2:['微网供电启动','MG Starting'],\n"
                "N3:['电网供电启动','Grid Starting'],\n"
                "N4:['微网供电运行','MG Running'],\n"
                "N5:['电网供电运行','Grid Running'],\n"
                "N6:['故障','Fault'],	\n"
                "N7:['停机中','Stopping'],  		\n"
                "N8:['停机','Stopped'],\n"
                "N9:['紧急停机','Emergency Stop'],\n"
                "N10:['',''],\n"
                "N11:['',''],\n"
                "N12:['',''],\n"
                "N13:['',''],\n"
                "N14:['',''],\n"
                "N15:['',''],\n"
                "N16:['',''],\n"
                "N17:['',''],\n"
                "N18:['启动中','Starting'],\n"
                "N19:['正在同步','Synchronizing'],\n"
 		"};\n"
 		"var ContactorState=\n"
 		"{\n"
                "N0:['断开','Opened'],\n"
                "N1:['闭合','Closed']\n"
 		"};\n"
 		"var GridStatus=\n"
 		"{\n"
 			"N0:['无电','MisGrid'],\n"
                "N1:['有电','Grid']\n"
 		"};\n"
 		"var ContactorFaultStatus=\n"
 		"{\n"
 			"N0:['正常','Normal'],\n"
 			"N1:['故障','Fault']\n"
 		"};\n"
 		"var PcsType=\n"
 		"{\n"
                "N0:['SC50','SC50'],\n"
                "N1:['SC100','SC100'],\n"
                "N2:['SC250','SC250'],\n"
                "N3:['SC500','SC500'],\n"
                "N4:['SC500TL','SC500TL'],	\n"
                "N5:['SC1000','SC1000']\n"
 		"};\n"
 		"var EnableStatus=\n"
 		"{\n"
 			"N0:['禁止','Disable'],\n"
 			"N1:['使能','Enable']\n"
 		"};\n"
 		"var TimeEnableStatus=\n"
 		"{\n"
 			"N0:['禁止','Disable'],\n"
 			"N1:['按小时','By Hour'],\n"
 			"N2:['按星期','By Week']\n"
 		"};\n"
 		"var BusType=\n"
 		"{\n"
 			"N0:['直流母线','AC-BUS'],\n"
 			"N1:['交流母线','DC-BUS']		\n"
 		"}\n"
 		"var RunMode=\n"
 		"{\n"
 			"N0:['并网','Grid'],\n"
 			"N1:['离网','Off-Grid'],\n"
 			"N2:['并离网切换','Grid-OnOFF']\n"
 		"};\n"
 		"var CtrlMode=\n"
 		"{\n"
 			"N0:['固定功率','Fixed Power'],\n"
 			"N1:['跟踪负载','Tacking Load'],\n"
 			"N2:['PCC点功率控制','PCC Control'],\n"
 			"N3:['防逆流','Anti Reflux'], \n"
 			"N4:['',''],\n"
 			"N5:['',''],\n"
 			"N6:['',''],\n"
 			"N7:['',''],\n"
 			"N8:['',''],\n"
 			"N9:['',''],\n"
             "N10:['削峰填谷','Peak Load Shifting'], \n"
             "N11:['交流限发','AC Limited Produce'], \n"
             "N12:['输出平滑','OutPut Smooth'],\n"
             "N13:['调频','FM']\n"
 		"};\n"
 		"var PcsRunningMode=\n"
 		"{\n"
 			"N0:['恒流','CC-Mode'],\n"
 			"N1:['恒压','CV-Mode'],\n"
 			"N2:['恒直流功率','CP-Mode(DC)'],\n"
 			"N3:['恒交流功率','CP-Mode(AC)'],\n"
 			"N4:['待机','Standby-Mode'],\n"
 			"N5:['停机','Stop']\n"
 		"};\n"
"\n"
 		"var TH1=new Array('30','150','100','100','100','110','110','110','110','110','110','110','110','110','110','110','110','110','110','110','110','110','110','110','110','110','110','110','110','110','110');\n"
 		"function Init(language)\n"
 		"{\n"
 			"for(var i=1;i<=31;i++)eval('OBJ(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'['+language+'];');\n"
 		"}\n"
 			//显示记录数据
 		"function Show_Records(Json,language)\n"
 		"{\n"
 			"var loop=Json.R.length-1;\n"
                "for(var i=0;i<loop;i++)\n"
                "{\n"
                    "for(var j=1;j<=31;j++)\n"
                    "{\n"
                     "if(j==3) \n"
 					"{\n"
 							//储能型号
 						"eval(\"OBJ('N'+'\"+String(i)+\"'+'\"+(j<10?'0'+j:j)+\"').innerHTML=PcsType.N\"+Json.R[i].C3+\"[\"+language+\"]\");\n"
 					"}\n"
 					"else if(j==5) \n"
 					"{\n"
 							//并网使能
 						"eval(\"OBJ('N'+'\"+String(i)+\"'+'\"+(j<10?'0'+j:j)+\"').innerHTML=EnableStatus.N\"+Json.R[i].C5+\"[\"+language+\"]\");\n"
 					"}\n"
 					"else if(j==6) \n"
 					"{\n"
 							//总线类型
 						"eval(\"OBJ('N'+'\"+String(i)+\"'+'\"+(j<10?'0'+j:j)+\"').innerHTML=BusType.N\"+Json.R[i].C6+\"[\"+language+\"]\");\n"
 					"}\n"
 					"else if(j==7) \n"
 					"{\n"
 							//分时使能
 						"eval(\"OBJ('N'+'\"+String(i)+\"'+'\"+(j<10?'0'+j:j)+\"').innerHTML=TimeEnableStatus.N\"+Json.R[i].C7+\"[\"+language+\"]\");\n"
 					"}\n"
 					"else if(j==8) \n"
 					"{\n"
 							//工作状态
 						"eval(\"OBJ('N'+'\"+String(i)+\"'+'\"+(j<10?'0'+j:j)+\"').innerHTML=State.N\"+Json.R[i].C8+\"[\"+language+\"]\");\n"
 					"}\n"
 					"else if(j==9)\n"
 					"{\n"
 							//电网状态
 						"eval(\"OBJ('N'+'\"+String(i)+\"'+'\"+(j<10?'0'+j:j)+\"').innerHTML=GridStatus.N\"+Json.R[i].C9+\"[\"+language+\"]\");\n"
 					"}\n"
 					"else if(j==13)\n"
 					"{\n"
 							// 接触器状态
 						"eval(\"OBJ('N'+'\"+String(i)+\"'+'\"+(j<10?'0'+j:j)+\"').innerHTML=ContactorState.N\"+Json.R[i].C13+\"[\"+language+\"]\");\n"
 					"}\n"
 					"else if(j==15)\n"
 					"{\n"
 							// 接触器状态
 						"eval(\"OBJ('N'+'\"+String(i)+\"'+'\"+(j<10?'0'+j:j)+\"').innerHTML=ContactorState.N\"+Json.R[i].C15+\"[\"+language+\"]\");\n"
 					"}\n"
 					"else if(j==14)\n"
 					"{\n"
 							//接触器故障状态
 						"eval(\"OBJ('N'+'\"+String(i)+\"'+'\"+(j<10?'0'+j:j)+\"').innerHTML=ContactorFaultStatus.N\"+Json.R[i].C14+\"[\"+language+\"]\");\n"
 					"}\n"
 					"else if(j==16)\n"
 					"{\n"
 							//接触器故障状态
 						"eval(\"OBJ('N'+'\"+String(i)+\"'+'\"+(j<10?'0'+j:j)+\"').innerHTML=ContactorFaultStatus.N\"+Json.R[i].C16+\"[\"+language+\"]\");\n"
 					"}\n"
 					"else if(j==17) \n"
 					"{\n"
 							//运行模式
 						"eval(\"OBJ('N'+'\"+String(i)+\"'+'\"+(j<10?'0'+j:j)+\"').innerHTML=RunMode.N\"+Json.R[i].C17+\"[\"+language+\"]\");\n"
 					"}\n"
 					"else if(j==18) \n"
 					"{\n"
 							//功率控制模式
 						"eval(\"OBJ('N'+'\"+String(i)+\"'+'\"+(j<10?'0'+j:j)+\"').innerHTML=CtrlMode.N\"+Json.R[i].C18+\"[\"+language+\"]\");\n"
 					"}\n"
 					"else if(j==20) \n"
 					"{\n"
 							//储能并网工作模式 
 						"eval(\"OBJ('N'+'\"+String(i)+\"'+'\"+(j<10?'0'+j:j)+\"').innerHTML=PcsRunningMode.N\"+Json.R[i].C20+\"[\"+language+\"]\");\n"
 					"}\n"
 					"else\n"
 					"{\n"
 							//数据
 						"eval(\"OBJ('N'+'\"+String(i)+\"'+'\"+(j<10?'0'+j:j)+\"').innerHTML=Json.R[i].C\"+String(j)+\";\");\n"
 					"}\n"
                    "}\n"
                "}\n"
                 //如果小于10条记录，清空记录外的数据位
                "for(var aa=loop;aa<10;aa++)\n"
                "{\n"
                    "for(var j=1;j<=31;j++)\n"
                    "{\n"
 					"OBJ('N'+String(aa)+(j<10?'0'+j:j)).innerHTML='';\n"
                    "}\n"
                "}\n"
 		"}\n"
 			//设置列表头字体
 		"function show_TH(TR1)\n"
 		"{\n"
 			"var str='';\n"
 			"str+=\"<table width='3800' border='0' style='border-collapse:collapse;border:1px #ddd solid;text-align:center;'>\";\n"
 				"str+=\"<tr>\";\n"
 				"for(var i=1;i<=31;i++)\n"
 				"{\n"
 					"str+=\"<th width='\"+TR1[i-1]+\"'><span id='N\"+(i<10?'0'+i:i)+\"'></span></th>\";\n"
 				"}\n"
 				"str+=\"</tr>\";\n"
 			"str+=\"</table>\";\n"
 			"document.write(str);\n"
 		"}\n"
 			//设置列表显示样式及内容
 		"function show_TD(TR1)\n"
 		"{\n"
 			"var str='';\n"
 			"str+=\"<table width='3800' border='0' style='border-collapse:collapse;border:1px #ddd solid;text-align:center;'>\";\n"
 				"for(var i=0;i<10;i++)\n"
 				"{\n"
 					"str+=\"<tr>\";\n"
 						"for(var j=1;j<=31;j++)\n"
 						"{\n"
 							"str+=\"<td width='\"+TR1[j-1]+\"' class='\"+(i%2?\"even\":\"odd\")+\"'><span id='N\"+String(i)+(j<10?'0'+j:j)+\"'></span></td>\";\n"
 						"}\n"
 					"str+=\"</tr>\";\n"
 				"}\n"
 			"str+=\"</table>\";\n"
 			"document.write(str);\n"
 		"}\n"
 	"</script>\n"
 "</head>\n"
 "<body>\n"
 "<script type='text/javascript'>\n"
 	"show_TH(TH1);\n"
 "</script>\n"
 "<div style=\"height:2px;overflow:hidden;\"></div>\n"
 "<script type='text/javascript'>\n"
 	"show_TD(TH1);\n"
 "</script>\n"
 "</body>\n"
"</html>\n"
};
#endif
