#ifndef _HTML_H_018_H_
#define _HTML_H_018_H_
static const char h_018[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
        "<script src='j_001.js' type='text/javascript'></script>\n"
        "<style type='text/css'>\n"
        "tr{height:27px;}\n"
        ".td1{text-align:left;padding-left:40px;}\n"
        ".td2{text-align:right;padding-right:5px;}\n"
        ".td3{text-align:right;padding-right:40px;}\n"
        ".div_tab{width:780px;height:45px;margin:0 auto;}\n"
        ".div_btn{width:80px;margin:0 auto;height:30px;text-align:right;margin-top:8px;float:left;}\n"
        ".div_text{width:80px;margin:0 auto;height:25px;text-align:right;margin-top:10px;float:left;}\n"
        ".div_span{width:40px;margin:0 auto;height:25px;font-size:16px;font-weight:bold;text-align:right;margin-top:12px;float:left;}\n"
        ".btn{width:75px;height:30px;}\n"
        ".PagerView{font-size:14px;font-family:tahoma,arial;font-weight:bold;color:#333;text-align:center;padding:8px;line-height:100%;}\n"
        ".PagerView span{color:#999;margin:0 1px;padding:3px 6px;border:1px solid #ccc;}\n"
        ".PagerView span.on{color:#fff;font-weight:bold;border:1px solid #666;background:#888;} \n"
        ".PagerView a{color:#00f;text-decoration:none;}\n"
        ".PagerView a span{color:#33f;border:1px solid #888;}\n"
        ".pager{width:780px;margin:0 auto;}\n"
        "</style>\n"
        "<script type='text/javascript'>\n"
            "var BMS1=new Array('N03','N04','N05','N06','N07','N08','N09','N10','N11','N12','N13','N14','N15');\n"
            "var BMS2=new Array('ID_0x0051','ID_0x0052','ID_0x0053','ID_0x0054','ID_0x0056','ID_0x0055','ID_0x0058','ID_0x0057','ID_0x0059','ID_0x005A','ID_0x005B','ID_0x005C','ID_0x005D');\n"
            "var BMS3=new Array('V','A','%','%','V','V','℃','℃','A','A','','','');\n"
             //rack告警
            "var ALARM1_68=new Array('N71','N72','N73','N74','N75','N76','N77','N78','N79','N80','N81','N82','N83','N84','N85','N86');\n"
            "var ALARM2_68=new Array('ID_A71','ID_A72','ID_A73','ID_A74','ID_A75','ID_A76','ID_A77','ID_A78','ID_A79','ID_A80','ID_A81','ID_A82','ID_A83','ID_A84','ID_A85','ID_A86');\n"
            "var ALARM3_68=new Array('','','','','','','','','','','','','','','','');\n"
             //sys告警
            "var ALARM1_68_sys=new Array('N87','N88','N89','N90','N91','N92','N93','N94','N95','N96','N97','N98','N99','N100');\n"
            "var ALARM2_68_sys=new Array('ID_A87','ID_A88','ID_A89','ID_A90','ID_A91','ID_A92','ID_A93','ID_A94','ID_A95','ID_A96','ID_A97','ID_A98','ID_A99','ID_A100');\n"
            "var ALARM3_68_sys=new Array('','','','','','','','','','','','','','');\n"
"\n"
            "var FAULT1_68=new Array('N52','N53','N54','N58','N59','N60','N61','N62','N64','N65','N66');\n"
            "var FAULT2_68=new Array('ID_F52','ID_F53','ID_F54','ID_F58','ID_F59','ID_F60','ID_F61','ID_F62','ID_F64','ID_F65','ID_F66');\n"
            "var FAULT3_68=new Array('','','','','','','','','','','');\n"
"\n"
            "var ALARM1_94=new Array('N120','N121','N122','N123','N124','N125','N126','N127','N128','N129','N130','N131','N132','N133','N134','N135','N136','N137','N160','N161','N162','N163','N164','N165','N166','N167','N168');\n"
            "var ALARM2_94=new Array('ID_A120','ID_A121','ID_A122','ID_A123','ID_A124','ID_A125','ID_A126','ID_A127','ID_A128','ID_A129','ID_A130','ID_A131','ID_A132','ID_A133','ID_A134','ID_A135','ID_A136','ID_A137','ID_A160','ID_A161','ID_A162','ID_A163','ID_A164','ID_A165','ID_A166','ID_A167','ID_A168');\n"
            "var ALARM3_94=new Array('','','','','','','','','','','','','','','','','','','','','','','','','','','');\n"
"\n"
            "var FAULT1_94=new Array('N200','N201','N202','N203','N204','N205','N206','N207','N208','N209','N210','N211','N212','N213','N214','N215','N216','N217','N240','N241','N242','N243','N244','N245','N246','N247','N248');\n"
            "var FAULT2_94=new Array('ID_F200','ID_F201','ID_F202','ID_F203','ID_F204','ID_F205','ID_F206','ID_F207','ID_F208','ID_F209','ID_F210','ID_F211','ID_F212','ID_F213','ID_F214','ID_F215','ID_F216','ID_F217','ID_F240','ID_F241','ID_F242','ID_F243','ID_F244','ID_F245','ID_F246','ID_F247','ID_F248');\n"
            "var FAULT3_94=new Array('','','','','','','','','','','','','','','','','','','','','','','','','','','');\n"
"\n"
            "function show_SUB(TAB,TR1,TR2,TR3)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<table id='\"+TAB+\"' style='display:table;' width='90%' border='0'>\";\n"
                "for(var i=0;i<TR1.length;i+=2)\n"
                "{\n"
                    "str+=\"<tr id='\"+TR1[i]+i+\"'>\";\n"
                        "str+=\"<td width='30%' class='td1 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR1[i]+\"'></span></td>\";\n"
                        "str+=\"<td width='15%' class='td2 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR2[i]+\"'></span></td>\";\n"
                        "str+=\"<td width='5%' class='td3 \"+(i%4?\"even\":\"odd\")+\"'>\"+TR3[i]+\"</td>\";\n"
                        "if(i+1!=TR1.length)\n"
                        "{\n"
                            "str+=\"<td width='30%' class='td1 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR1[i+1]+\"'></span></td>\";\n"
                            "str+=\"<td width='15%' class='td2 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR2[i+1]+\"'></span></td>\";\n"
                            "str+=\"<td width='5%' class='td3 \"+(i%4?\"even\":\"odd\")+\"'>\"+TR3[i+1]+\"</td>\";\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "str+=\"<td width='30%' class='td1 \"+(i%4?\"even\":\"odd\")+\"'></td>\";\n"
                            "str+=\"<td width='15%' class='td2 \"+(i%4?\"even\":\"odd\")+\"'></td>\";\n"
                            "str+=\"<td width='5%' class='td3 \"+(i%4?\"even\":\"odd\")+\"'></td>\";\n"
                        "}\n"
                        "\n"
                    "str+=\"</tr>\";\n"
                "}\n"
                "str+=\"</table>\";\n"
                "document.write(str);\n"
            "}\n"
        "var PagerView=function(id,AAA,BBB,CCC)\n"
            "{\n"
                "var self=this;\n"
                "this.id=id;\n"
                "this._pageCount=0;\n"
                "this._start=1;\n"
                "this._end=1;\n"
                "this.container=null;\n"
                "this.index=1;\n"
                "this.size=10;\n"
                "this.maxButtons=18;\n"
                "this.itemCount=0;\n"
                "this.onclick=function(index){return true;};\n"
                "this._onclick=function(index)\n"
                "{\n"
                    "var old=self.index;\n"
                    "self.index=index;\n"
                    "if(self.onclick(index)!==false)self.render();\n"
                    "else self.index=old;\n"
                "};\n"
                "this._calculate=function()\n"
                "{\n"
                    "self._pageCount=parseInt(Math.ceil(self.itemCount/self.size));\n"
                    "self.index=parseInt(self.index);\n"
                    "if(self.index>self._pageCount)self.index=self._pageCount;\n"
                    "if(self.index<1)self.index=1;\n"
                    "self._start=Math.max(1,self.index-parseInt(self.maxButtons/2));\n"
                    "self._end=Math.min(self._pageCount,self._start+self.maxButtons-1);\n"
                    "self._start=Math.max(1,self._end-self.maxButtons+1);\n"
                "};\n"
                "this.page=function(rows)\n"
                "{\n"
                    "self._calculate();\n"
                    "var s_num=(self.index-1)*self.size ;\n"
                    "var e_num=self.index*self.size;\n"
                    "return rows.slice(s_num,e_num);\n"
                "};\n"
                "this.render=function()\n"
                "{\n"
                    "var div=document.getElementById(self.id);\n"
                    "div.view=self;\n"
                    "self.container=div;\n"
                    "self._calculate();\n"
                    "var str='';\n"
                    "str+='<div class=\"PagerView\">\\n';\n"
                    "if(self._pageCount>1)\n"
                    "{\n"
                        "if(self.index!=1)\n"
                        "{\n"
                            "str+='<a href=\"javascript://1\"><span>|&lt;</span></a>';\n"
                            "str+='<a href=\"javascript://'+(self.index-1)+'\"><span>&lt;&lt;</span></a>';\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "str+='<span>|&lt;</span>';\n"
                            "str+='<span>&lt;&lt;</span>';\n"
                        "}\n"
                    "}\n"
                    "for(var i=self._start;i<=self._end;i++)\n"
                    "{\n"
                        "if(i==this.index)\n"
                        "{\n"
                            "if(i<10)str+='<span class=\"on\">'+'0'+i+\"</span>\";\n"
                            "else str+='<span class=\"on\">'+i+\"</span>\";\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "if(i<10)str+='<a href=\"javascript://'+i+'\"><span>'+'0'+i+\"</span></a>\";\n"
                            "else str+='<a href=\"javascript://'+i+'\"><span>'+i+\"</span></a>\";\n"
                        "}\n"
                    "}\n"
                    "if(self._pageCount>1)\n"
                    "{\n"
                        "if(self.index!=self._pageCount)\n"
                        "{\n"
                            "str+='<a href=\"javascript://'+(self.index+1)+'\"><span>&gt;&gt;</span></a>';\n"
                            "str+='<a href=\"javascript://'+self._pageCount+'\"><span>&gt;|</span></a>';\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "str+='<span>&gt;&gt;</span>';\n"
                            "str+='<span>&gt;|</span>';\n"
                        "}\n"
                    "}\n"
                    "str+=AAA+self._pageCount+BBB+self.itemCount+CCC;\n"
                    "str+='</div><!--/.pagerView-->\\n';\n"
                    "self.container.innerHTML=str;\n"
                    "var a_list=self.container.getElementsByTagName('a');\n"
                    "for(var i=0;i<a_list.length;i++)\n"
                    "{\n"
                        "a_list[i].onclick=function()\n"
                        "{\n"
                            "var index=this.getAttribute('href');\n"
                            "if(index!=undefined&&index!='')\n"
                            "{\n"
                                "index=parseInt(index.replace('javascript://',''));\n"
                                "self._onclick(index);\n"
                            "}\n"
                            "return false;\n"
                        "};\n"
                    "}\n"
                "};\n"
            "};\n"
        "</script>\n"
    "</head>\n"
    "<body onload='Init();'>\n"
        "<script type='text/javascript'>\n"
            "show_T('N01');\n"
        "</script>        \n"
        "<div id='pager' width='90%' style='padding-left:5%;float:left;'></div>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N02');\n"
            "show_SUB('info',BMS1,BMS2,BMS3);\n"
        "</script>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>          \n"
        "<script type='text/javascript'>\n"
            "show_sT_ex('N42', 't_68_rack');\n"
            "show_SUB('alarm_t_1',ALARM1_68,ALARM2_68,ALARM3_68);\n"
            "show_sT_ex('N40', 't_68_sys');\n"
            "show_SUB('alarm_t_sys',ALARM1_68_sys,ALARM2_68_sys,ALARM3_68_sys);\n"
            "show_SUB('alarm_t_2',ALARM1_94,ALARM2_94,ALARM3_94);\n"
        "</script>      \n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>  \n"
        "<script type='text/javascript'>\n"
            "show_sT('N41');\n"
            "show_SUB('fault_t_1',FAULT1_68,FAULT2_68,FAULT3_68);\n"
            "show_SUB('fault_t_2',FAULT1_94,FAULT2_94,FAULT3_94);\n"
        "</script>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>  \n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var $=function(o){return document.getElementById(o);};\n"
        "var language=0;\n"
        "var Json;\n"
        "var CurBms;\n"
        "var lang=\n"
        "{\n"
            "N01:['电池信息','BMS Information'],\n"
            "N02:['系统信息','System Information'],\n"
            "N03:['电池系统电压','System V'],\n"
            "N04:['电池系统电流','System I'],\n"
            "N05:['系统SOC','System SOC'],\n"
            "N06:['系统SOH','System SOH'],\n"
            "N07:['最大单体电压','Max cell V'],\n"
            "N08:['最低单体电压','Min cell V'],\n"
            "N09:['最高单体温度','Max cell T'],\n"
            "N10:['最低单体温度','Min cell T'],\n"
            "N11:['充电限制电流','Charge limit I'],\n"
            "N12:['放电限制电流','Discharge limit I'],\n"
            "N13:['运行Rack数','Rack in service'],\n"
            "N14:['总Rack数','Rack in system'],\n"
            "N15:['系统模式','System Mode'],\n"
"\n"
            "N40:['系统告警状态','Sys Alarm Status'],\n"
            "N41:['故障状态','Fault Status'],\n"
            "N42:['Rack告警状态','Rack Alarm Status'],\n"
"\n"
             //68Ah fault
            "N51:['',''],\n"
            "N52:['单体过温','Cell Over Temperature'],\n"
            "N53:['单体欠压','Cell Under Voltage'],\n"
            "N54:['单体过压','Cell Over Voltage'],\n"
            "N55:['',''],\n"
            "N56:['',''],\n"
            "N57:['',''],\n"
            "N58:['Rack欠压','Rack Under Voltage'],\n"
            "N59:['Rack过压','Rack Over Voltage'],\n"
            "N60:['通讯故障(系统Rack)','Comm fault (Rack-system)'],\n"
            "N61:['通讯故障(模块Rack)','Comm fault (Module-Rack)'],\n"
            "N62:['过流保护','Over Current Protection'],\n"
            "N63:['',''],\n"
            "N64:['附加保护','Additional Protection'],\n"
            "N65:['直流接触器故障','DC Contactor fail'],\n"
            "N66:['直流接触器传感器失败','DC Contactor Sensor fail'],\n"
             //68Ah rack alarm
            "N71:['单体欠温','Cell Under Temperature'],\n"
            "N72:['单体过温','Cell Over Temperature'],\n"
            "N73:['单体欠压','Cell Under Voltage'],\n"
            "N74:['单体过压','Cell Over Voltage'],\n"
            "N75:['电压误差过大','Sensing Volt Diff'],\n"
            "N76:['电压不平衡','Voltage imbalance'],\n"
            "N77:['温度不平衡','Temp imbalance'],\n"
            "N78:['Rack欠压','Rack Under Voltage'],\n"
            "N79:['Rack过压','Rack Over Voltage'],\n"
            "N80:['通讯故障(系统Rack)','Comm fault (Rack-system)'],\n"
            "N81:['通讯故障(模块Rack)','Comm fault (Module-Rack)'],\n"
            "N82:['过流保护','Over Current Protection'],\n"
            "N83:['过充','Full Charge'],\n"
            "N84:['电流传感器错误','Current Sensor Error'],\n"
            "N85:['充电限流错误','Charge Limit Error'],\n"
            "N86:['风扇错误','Fan Error'],\n"
             //68Ah sys alarm
            "N87:['CAN 告警 #1','CAN Alarm #1'],\n"
            "N88:['CAN 告警 #2','CAN Alarm #2'],\n"
            "N89:['RTU 告警 #1','RTU Alarm #1'],\n"
            "N90:['RTU 告警 #2','RTU Alarm #2'],\n"
            "N91:['TCP502 告警 #1','TCP502 Alarm #1'],\n"
            "N92:['TCP502 告警 #2','TCP502 Alarm #2'],\n"
            "N93:['TCP602 告警 #1','TCP602 Alarm #1'],\n"
            "N94:['TCP602 告警 #2','TCP602 Alarm #2'],\n"
            "N95:['S.UVP 告警 #1','S.UVP Alarm #1'],\n"
            "N96:['S.UVP 告警 #2','S.UVP Alarm #2'],\n"
            "N97:['不平衡告警','Imbalance Alarm'],\n"
            "N98:['不平衡停止','Imbalance Stop'],\n"
            "N99:['控制信息不可获取','Ctrl Infor Not Valid'],\n"
            "N100:['控制信息无效','Ctrl Infor Invalid'],\n"
            "N101:['',''],\n"
            "N102:['',''],\n"
"\n"
             //94Ah - alarm1
            "N120:['模块欠温','module UT'],\n"
            "N121:['模块过温','module OT'],\n"
            "N122:['模块欠压','module UV'],\n"
            "N123:['模块过压','module OV'],\n"
            "N124:['模块电压不平衡','module V-imb'],\n"
            "N125:['模块温度不平衡','module T-imb'],\n"
            "N126:['通讯故障(模块Rack)','R-M comm fail'],\n"
            "N127:['通讯故障(系统Rack)','R-S comm fail'],\n"
            "N128:['rack充电过流','rack ChgOC'],\n"
            "N129:['rack放电过流','rack DchgOC'],\n"
            "N130:['rack欠压','rack UV'],\n"
            "N131:['rack过压','rack OV'],\n"
            "N132:['rack电压误差过大','rack V sensing diff'],\n"
            "N133:['rack电流传感器失效','rack I senser fail'],\n"
            "N134:['rack架电压不平衡','rack string V-imb'],\n"
            "N135:['rack架电流不平衡','rack string I-imb'],\n"
             //94Ah - alarm2
            "N136:['rack熔断器失效','rack fuse fail'],\n"
            "N137:['永久欠压','permanent uv'],\n"
            "N138:['',''],\n"
            "N139:['',''],\n"
            "N140:['',''],\n"
            "N141:['',''],\n"
            "N142:['',''],\n"
            "N143:['',''],\n"
            "N144:['',''],\n"
            "N145:['',''],\n"
            "N146:['',''],\n"
            "N147:['',''],\n"
            "N148:['',''],\n"
            "N149:['',''],\n"
            "N150:['',''],\n"
            "N151:['',''],\n"
             //94Ah - alarm3
            "N152:['',''],\n"
            "N153:['',''],\n"
            "N154:['',''],\n"
            "N155:['',''],\n"
            "N156:['',''],\n"
            "N157:['',''],\n"
            "N158:['',''],\n"
            "N159:['',''],\n"
            "N160:['dcsw1传感器失效','dcsw1_sensing_fail'],\n"
            "N161:['dcsw2传感器失效','dcsw2_sensing_fail'],\n"
            "N162:['dcsw3传感器失效','dcsw3_sensing_fail'],\n"
            "N163:['dcsw3失效','dcsw3_fail'],\n"
            "N164:['模块pcb欠温','module pcb ut'],\n"
            "N165:['模块pcb过温','module pcb ot'],\n"
            "N166:['充电电流限制','chg current limit'],\n"
            "N167:['放电电流限制','dchg current limit'],\n"
             //94Ah - alarm4
            "N168:['附加保护失败','additional protection fail'],\n"
            "N169:['',''],\n"
            "N170:['',''],\n"
            "N171:['',''],\n"
            "N172:['',''],\n"
            "N173:['',''],\n"
            "N174:['',''],\n"
            "N175:['',''],\n"
            "N176:['',''],\n"
            "N177:['',''],\n"
            "N178:['',''],\n"
            "N179:['',''],\n"
            "N180:['',''],\n"
            "N181:['',''],\n"
            "N182:['',''],\n"
            "N183:['',''],\n"
            "N184:['',''],\n"
"\n"
             //94Ah - protection1
            "N200:['模块欠温','module UT'],\n"
            "N201:['模块过温','module OT'],\n"
            "N202:['模块欠压','module UV'],\n"
            "N203:['模块过压','module OV'],\n"
            "N204:['模块电压不平衡','module V-imb'],\n"
            "N205:['模块温度不平衡','module T-imb'],\n"
            "N206:['通讯故障(模块Rack)','R-M comm fail'],\n"
            "N207:['通讯故障(系统Rack)','R-S comm fail'],\n"
            "N208:['rack充电过流','rack ChgOC'],\n"
            "N209:['rack放电过流','rack DchgOC'],\n"
            "N210:['rack欠压','rack UV'],\n"
            "N211:['rack过压','rack OV'],\n"
            "N212:['rack电压误差过大','rack V sensing diff'],\n"
            "N213:['rack电流传感器失效','rack I senser fail'],\n"
            "N214:['rack架电压不平衡','rack string V-imb'],\n"
            "N215:['rack架电流不平衡','rack string I-imb'],\n"
             //94Ah - protection2
            "N216:['rack熔断器失效','rack fuse fail'],\n"
            "N217:['永久欠压','permanent  uv'],\n"
            "N218:['',''],\n"
            "N219:['',''],\n"
            "N220:['',''],\n"
            "N221:['',''],\n"
            "N222:['',''],\n"
            "N223:['',''],\n"
            "N224:['',''],\n"
            "N225:['',''],\n"
            "N226:['',''],\n"
            "N227:['',''],\n"
            "N228:['',''],\n"
            "N229:['',''],\n"
            "N230:['',''],\n"
            "N231:['',''],\n"
             //94Ah - protection3
            "N232:['',''],\n"
            "N233:['',''],\n"
            "N234:['',''],\n"
            "N235:['',''],\n"
            "N236:['',''],\n"
            "N237:['',''],\n"
            "N238:['',''],\n"
            "N239:['',''],\n"
            "N240:['dcsw1传感器失效','dcsw1_sensing_fail'],\n"
            "N241:['dcsw2传感器失效','dcsw2_sensing_fail'],\n"
            "N242:['dcsw3传感器失效','dcsw3_sensing_fail'],\n"
            "N243:['dcsw3失效','dcsw3_fail'],\n"
            "N244:['模块pcb欠温','module pcb ut'],\n"
            "N245:['模块pcb过温','module pcb ot'],\n"
            "N246:['充电电流限制','chg current limit'],\n"
            "N247:['放电电流限制','dchg current limit'],\n"
             //94Ah - protection4
            "N248:['附加保护失败','additional protection fail'],\n"
            "N249:['',''],\n"
            "N250:['',''],\n"
            "N251:['',''],\n"
            "N252:['',''],\n"
            "N253:['',''],\n"
            "N254:['',''],\n"
            "N255:['',''],\n"
            "N256:['',''],\n"
            "N257:['',''],\n"
            "N258:['',''],\n"
            "N259:['',''],\n"
            "N260:['',''],\n"
            "N261:['',''],\n"
            "N262:['',''],\n"
            "N263:['',''],\n"
"\n"
             //68ah-system mode
            "N300:['输出控制0','Output #0'],\n"
            "N301:['输出控制1','Output #1'],\n"
            "N302:['',''],\n"
            "N303:['',''],\n"
            "N304:['输入状态0','Input #0'],\n"
            "N305:['输入状态1','Input #1'],\n"
            "N306:['',''],\n"
            "N307:['',''],\n"
            "N308:['充电','Charge'],\n"
            "N309:['放电','Discharge'],\n"
            "N310:['准备','Ready'],\n"
            "N311:['空闲','Idle'],\n"
            "N312:['离线','Off line'],\n"
            "N313:['',''],\n"
            "N314:['',''],\n"
            "N315:['',''],\n"
"\n"
             //94ah-system mode
            "N350:['输出控制1','Output Control No.1'],\n"
            "N351:['输出控制2','Output Control No.2'],\n"
            "N352:['',''],\n"
            "N353:['',''],\n"
            "N354:['输入状态1','Input Status No.1'],\n"
            "N355:['输入状态2','Input Status No.2'],\n"
            "N356:['输入状态3','Input Status No.3'],\n"
            "N357:['输入状态4','Input Status No.4'],\n"
            "N358:['',''],\n"
            "N359:['',''],\n"
            "N360:['',''],\n"
            "N361:['',''],\n"
            "N362:['',''],\n"
            "N363:['',''],\n"
            "N364:['放电模式','Discharge Mode'],\n"
            "N365:['充电模式','Charge Mode'],\n"
"\n"
"\n"
            "N500:['一共','Total '],\n"
            "N501:['页，共',' Pages, '],\n"
            "N502:['页，共',' Page, '],\n"
            "N503:['台',' Nums'],\n"
            "N504:['台',' Num']\n"
        "};\n"
        "var FaultStatus=\n"
        "{\n"
            "N0:['正常','Normal'],\n"
            "N1:['故障','Fault']\n"
        "};\n"
        "var AlarmStatus=\n"
        "{\n"
            "N0:['正常','Normal'],\n"
            "N1:['告警','Alarm']\n"
        "};\n"
         //获取串口PVS数据
        "function Get_Bms_Index(index)\n"
        "{\n"
            "eval('var URL=\\'s_018.html?0x'+(0+index).toString(16).toUpperCase()+'&time=\\'+Math.random();');\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);   \n"
                    "if(Json.ID_0x02B3 == 0)\n"
                    "{\n"
                        "$('ID_0x0051').innerHTML=(Json.ID_0x0051/10.0).toFixed(1);\n"
                        "$('ID_0x0052').innerHTML=Json.ID_0x0052;\n"
                        "$('ID_0x0053').innerHTML=(Json.ID_0x0053/10.0).toFixed(1);\n"
                        "$('ID_0x0054').innerHTML=(Json.ID_0x0054/10.0).toFixed(1);  \n"
                        "$('ID_0x0055').innerHTML=(Json.ID_0x0055/1000.0).toFixed(3); \n"
                        "$('ID_0x0056').innerHTML=(Json.ID_0x0056/1000.0).toFixed(3);\n"
                        "if(Json.ID_0x038A == 1){\n"
                            "$('ID_0x0057').innerHTML=Json.ID_0x0057; \n"
                            "$('ID_0x0058').innerHTML=Json.ID_0x0058;   \n"
                        "}else if(Json.ID_0x038A == 2){\n"
                            "$('ID_0x0057').innerHTML=(Json.ID_0x0057/100.0).toFixed(2); \n"
                            "$('ID_0x0058').innerHTML=(Json.ID_0x0058/100.0).toFixed(2); \n"
                        "}\n"
                        "$('ID_0x0059').innerHTML=(Json.ID_0x0059/10.0).toFixed(1); \n"
                        "$('ID_0x005A').innerHTML=(Json.ID_0x005A/10.0).toFixed(1);    \n"
                        "$('ID_0x005B').innerHTML=Json.ID_0x005B; \n"
                        "$('ID_0x005C').innerHTML=Json.ID_0x005C;   \n"
                        "$('ID_0x005D').style.fontWeight='bold';\n"
"\n"
                        "if(Json.ID_0x038A == 1){\n"
                             //系统模式  
                            "if(Json.ID_0x005D<16)eval('document.getElementById(\\'ID_0x005D\\').innerHTML=lang.N'+(Json.ID_0x005D+300)+'[language];');\n"
                             //故障
                            "for(var i=0;i<16;i++)\n"
                            "{\n"
                                "if(i==0 || i==4 || i==5 || i==6 || i==12) continue;\n"
                                "if(((Json.ID_0x0068>>i)&1)==1)\n"
                                "{\n"
                                    "eval('$(\\'ID_F'+(51+i)+'\\').innerHTML=FaultStatus.N1[language];');\n"
                                    "eval('$(\\'ID_F'+(51+i)+'\\').style.color=\\'#F00\\';');\n"
                                "}\n"
                                "else\n"
                                "{\n"
                                    "eval('$(\\'ID_F'+(51+i)+'\\').innerHTML=FaultStatus.N0[language];');\n"
                                    "eval('$(\\'ID_F'+(51+i)+'\\').style.color=\\'#000\\';');\n"
                                "}\n"
                            "}\n"
                             //系统告警
                            "for(var i=0;i<14;i++)\n"
                            "{\n"
                                "if(((Json.ID_0x0069>>i)&1)==1)\n"
                                "{\n"
                                    "eval('$(\\'ID_A'+(87+i)+'\\').innerHTML=AlarmStatus.N1[language];');\n"
                                    "eval('$(\\'ID_A'+(87+i)+'\\').style.color=\\'#FF9500\\';');\n"
                                "}\n"
                                "else\n"
                                "{\n"
                                    "eval('$(\\'ID_A'+(87+i)+'\\').innerHTML=AlarmStatus.N0[language];');\n"
                                    "eval('$(\\'ID_A'+(87+i)+'\\').style.color=\\'#000\\';');\n"
                                "}\n"
                            "}\n"
                             //RACK告警
                            "for(var i=0;i<16;i++)\n"
                            "{\n"
                                "if(((Json.ID_0x006A>>i)&1)==1)\n"
                                "{\n"
                                    "eval('$(\\'ID_A'+(71+i)+'\\').innerHTML=AlarmStatus.N1[language];');\n"
                                    "eval('$(\\'ID_A'+(71+i)+'\\').style.color=\\'#FF9500\\';');\n"
                                "}\n"
                                "else\n"
                                "{\n"
                                    "eval('$(\\'ID_A'+(71+i)+'\\').innerHTML=AlarmStatus.N0[language];');\n"
                                    "eval('$(\\'ID_A'+(71+i)+'\\').style.color=\\'#000\\';');\n"
                                "}\n"
                            "}\n"
                        "}else if(Json.ID_0x038A == 2){\n"
                             //系统模式  
                            "if(Json.ID_0x005D<16)eval('document.getElementById(\\'ID_0x005D\\').innerHTML=lang.N'+(Json.ID_0x005D+350)+'[language];');\n"
                             //告警1
                            "for(var i=0;i<16;i++)\n"
                            "{\n"
                                "if(((Json.ID_0x005E>>i)&1)==1)\n"
                                "{\n"
                                    "eval('$(\\'ID_A'+(120+i)+'\\').innerHTML=AlarmStatus.N1[language];');\n"
                                    "eval('$(\\'ID_A'+(120+i)+'\\').style.color=\\'#FF9500\\';');\n"
                                "}\n"
                                "else\n"
                                "{\n"
                                    "eval('$(\\'ID_A'+(120+i)+'\\').innerHTML=AlarmStatus.N0[language];');\n"
                                    "eval('$(\\'ID_A'+(120+i)+'\\').style.color=\\'#000\\';');\n"
                                "}\n"
                            "}\n"
                             //告警2
                            "for(var i=0;i<2;i++)\n"
                            "{\n"
                                "if(((Json.ID_0x005F>>i)&1)==1)\n"
                                "{\n"
                                    "eval('$(\\'ID_A'+(136+i)+'\\').innerHTML=AlarmStatus.N1[language];');\n"
                                    "eval('$(\\'ID_A'+(136+i)+'\\').style.color=\\'#FF9500\\';');\n"
                                "}\n"
                                "else\n"
                                "{\n"
                                    "eval('$(\\'ID_A'+(136+i)+'\\').innerHTML=AlarmStatus.N0[language];');\n"
                                    "eval('$(\\'ID_A'+(136+i)+'\\').style.color=\\'#000\\';');\n"
                                "}\n"
                            "}\n"
                             //告警3
                            "for(var i=8;i<16;i++)\n"
                            "{\n"
                                "if(((Json.ID_0x0060>>i)&1)==1)\n"
                                "{\n"
                                    "eval('$(\\'ID_A'+(152+i)+'\\').innerHTML=AlarmStatus.N1[language];');\n"
                                    "eval('$(\\'ID_A'+(152+i)+'\\').style.color=\\'#FF9500\\';');\n"
                                "}\n"
                                "else\n"
                                "{\n"
                                    "eval('$(\\'ID_A'+(152+i)+'\\').innerHTML=AlarmStatus.N0[language];');\n"
                                    "eval('$(\\'ID_A'+(152+i)+'\\').style.color=\\'#000\\';');\n"
                                "}\n"
                            "}\n"
                             //告警4
                            "for(var i=0;i<1;i++)\n"
                            "{\n"
                                "if(((Json.ID_0x0061>>i)&1)==1)\n"
                                "{\n"
                                    "eval('$(\\'ID_A'+(168+i)+'\\').innerHTML=AlarmStatus.N1[language];');\n"
                                    "eval('$(\\'ID_A'+(168+i)+'\\').style.color=\\'#FF9500\\';');\n"
                                "}\n"
                                "else\n"
                                "{\n"
                                    "eval('$(\\'ID_A'+(168+i)+'\\').innerHTML=AlarmStatus.N0[language];');\n"
                                    "eval('$(\\'ID_A'+(168+i)+'\\').style.color=\\'#000\\';');\n"
                                "}\n"
                            "}\n"
                             //故障1
                            "for(var i=0;i<16;i++)\n"
                            "{\n"
                                "if(((Json.ID_0x0062>>i)&1)==1)\n"
                                "{\n"
                                    "eval('$(\\'ID_F'+(200+i)+'\\').innerHTML=FaultStatus.N1[language];');\n"
                                    "eval('$(\\'ID_F'+(200+i)+'\\').style.color=\\'#F00\\';');\n"
                                "}\n"
                                "else\n"
                                "{\n"
                                    "eval('$(\\'ID_F'+(200+i)+'\\').innerHTML=FaultStatus.N0[language];');\n"
                                    "eval('$(\\'ID_F'+(200+i)+'\\').style.color=\\'#000\\';');\n"
                                "}\n"
                            "}\n"
                             //故障2
                            "for(var i=0;i<2;i++)\n"
                            "{\n"
                                "if(((Json.ID_0x0063>>i)&1)==1)\n"
                                "{\n"
                                    "eval('$(\\'ID_F'+(216+i)+'\\').innerHTML=FaultStatus.N1[language];');\n"
                                    "eval('$(\\'ID_F'+(216+i)+'\\').style.color=\\'#F00\\';');\n"
                                "}\n"
                                "else\n"
                                "{\n"
                                    "eval('$(\\'ID_F'+(216+i)+'\\').innerHTML=FaultStatus.N0[language];');\n"
                                    "eval('$(\\'ID_F'+(216+i)+'\\').style.color=\\'#000\\';');\n"
                                "}\n"
                            "}\n"
                             //故障3
                            "for(var i=8;i<16;i++)\n"
                            "{\n"
                                "if(((Json.ID_0x0064>>i)&1)==1)\n"
                                "{\n"
                                    "eval('$(\\'ID_F'+(232+i)+'\\').innerHTML=FaultStatus.N1[language];');\n"
                                    "eval('$(\\'ID_F'+(232+i)+'\\').style.color=\\'#F00\\';');\n"
                                "}\n"
                                "else\n"
                                "{\n"
                                    "eval('$(\\'ID_F'+(232+i)+'\\').innerHTML=FaultStatus.N0[language];');\n"
                                    "eval('$(\\'ID_F'+(232+i)+'\\').style.color=\\'#000\\';');\n"
                                "}\n"
                            "}\n"
                             //故障4
                            "for(var i=0;i<1;i++)\n"
                            "{\n"
                                "if(((Json.ID_0x0065>>i)&1)==1)\n"
                                "{\n"
                                    "eval('$(\\'ID_F'+(248+i)+'\\').innerHTML=FaultStatus.N1[language];');\n"
                                    "eval('$(\\'ID_F'+(248+i)+'\\').style.color=\\'#F00\\';');\n"
                                "}\n"
                                "else\n"
                                "{\n"
                                    "eval('$(\\'ID_F'+(248+i)+'\\').innerHTML=FaultStatus.N0[language];');\n"
                                    "eval('$(\\'ID_F'+(248+i)+'\\').style.color=\\'#000\\';');\n"
                                "}\n"
                            "}\n"
                        "} \n"
                    "}\n"
                    "else\n"
                    "{\n"
                        "$('ID_0x0051').innerHTML='--';\n"
                        "$('ID_0x0052').innerHTML='--';\n"
                        "$('ID_0x0053').innerHTML='--';\n"
                        "$('ID_0x0054').innerHTML='--';  \n"
                        "$('ID_0x0055').innerHTML='--'; \n"
                        "$('ID_0x0056').innerHTML='--';\n"
                        "$('ID_0x0057').innerHTML='--'; \n"
                        "$('ID_0x0058').innerHTML='--';   \n"
"\n"
                        "$('ID_0x0059').innerHTML='--'; \n"
                        "$('ID_0x005A').innerHTML='--';    \n"
                        "$('ID_0x005B').innerHTML='--'; \n"
                        "$('ID_0x005C').innerHTML='--';\n"
"\n"
                        "if(Json.ID_0x038A == 1){\n"
                             //系统模式 
                            "$('ID_0x005D').innerHTML='--'; \n"
                             //故障
                            "for(var i=0;i<16;i++)\n"
                            "{\n"
                                "if(i==0 || i==4 || i==5 || i==6 || i==12) continue;\n"
                                "eval('$(\\'ID_F'+(51+i)+'\\').innerHTML=\\'--\\';');\n"
                                "eval('$(\\'ID_F'+(51+i)+'\\').style.color=\\'#000\\';');\n"
                            "}\n"
                             //系统告警
                            "for(var i=0;i<14;i++)\n"
                            "{\n"
                                "eval('$(\\'ID_A'+(87+i)+'\\').innerHTML=\\'--\\';');\n"
                                "eval('$(\\'ID_A'+(87+i)+'\\').style.color=\\'#000\\';');\n"
                            "}\n"
                             //RACK告警
                            "for(var i=0;i<16;i++)\n"
                            "{\n"
                                "eval('$(\\'ID_A'+(71+i)+'\\').innerHTML=\\'--\\';');\n"
                                "eval('$(\\'ID_A'+(71+i)+'\\').style.color=\\'#000\\';');\n"
                            "}\n"
                        "}else if(Json.ID_0x038A == 2){\n"
                             //系统模式 
                            "$('ID_0x005D').innerHTML='--'; \n"
                             //告警1
                            "for(var i=0;i<16;i++)\n"
                            "{\n"
                                "eval('$(\\'ID_A'+(120+i)+'\\').innerHTML=\\'--\\';');\n"
                                "eval('$(\\'ID_A'+(120+i)+'\\').style.color=\\'#000\\';');\n"
                            "}\n"
                             //告警2
                            "for(var i=0;i<2;i++)\n"
                            "{\n"
                                "eval('$(\\'ID_A'+(136+i)+'\\').innerHTML=\\'--\\';');\n"
                                "eval('$(\\'ID_A'+(136+i)+'\\').style.color=\\'#000\\';');\n"
                            "}\n"
                             //告警3
                            "for(var i=8;i<16;i++)\n"
                            "{\n"
                                "eval('$(\\'ID_A'+(152+i)+'\\').innerHTML=\\'--\\';');\n"
                                "eval('$(\\'ID_A'+(152+i)+'\\').style.color=\\'#000\\';');\n"
                            "}\n"
                             //告警4
                            "for(var i=0;i<1;i++)\n"
                            "{\n"
                                "eval('$(\\'ID_A'+(168+i)+'\\').innerHTML=\\'--\\';');\n"
                                "eval('$(\\'ID_A'+(168+i)+'\\').style.color=\\'#000\\';');\n"
                            "}\n"
                             //故障1
                            "for(var i=0;i<16;i++)\n"
                            "{\n"
                                "eval('$(\\'ID_F'+(200+i)+'\\').innerHTML=\\'--\\';');\n"
                                "eval('$(\\'ID_F'+(200+i)+'\\').style.color=\\'#000\\';');\n"
                            "}\n"
                             //故障2
                            "for(var i=0;i<2;i++)\n"
                            "{\n"
                                "eval('$(\\'ID_F'+(216+i)+'\\').innerHTML=\\'--\\';');\n"
                                "eval('$(\\'ID_F'+(216+i)+'\\').style.color=\\'#000\\';');\n"
                            "}\n"
                             //故障3
                            "for(var i=8;i<16;i++)\n"
                            "{\n"
                                "eval('$(\\'ID_F'+(232+i)+'\\').innerHTML=\\'--\\';');\n"
                                "eval('$(\\'ID_F'+(232+i)+'\\').style.color=\\'#000\\';');\n"
                            "}\n"
                             //故障4
                            "for(var i=0;i<1;i++)\n"
                            "{\n"
                                "eval('$(\\'ID_F'+(248+i)+'\\').innerHTML=\\'--\\';');\n"
                                "eval('$(\\'ID_F'+(248+i)+'\\').style.color=\\'#000\\';');\n"
                            "}\n"
                        "} \n"
                    "}\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
             //alert(URL);   
        "}  \n"
        "function ajax()\n"
        "{\n"
            "var URL='s_018.html?time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);           \n"
                    "if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                    "lang_init_ex(1,15);\n"
                    "lang_init_ex(40,42);\n"
                    "lang_init_ex(52,54);\n"
                    "lang_init_ex(58,62);\n"
                    "lang_init_ex(64,66);\n"
                    "lang_init_ex(71,100);\n"
                    "lang_init_ex(120,137);\n"
                    "lang_init_ex(160,168);\n"
                    "lang_init_ex(200,217);\n"
                    "lang_init_ex(240,248);\n"
"\n"
                    "if(Json.ID_0x038A == 1){\n"
                        "$('t_68_sys').style.display='block';\n"
                        "$('t_68_rack').style.display='block';\n"
                        "$('alarm_t_2').style.display='none';\n"
                        "$('fault_t_2').style.display='none';\n"
                    "}else if(Json.ID_0x038A == 2){\n"
                        "$('t_68_sys').style.display='block';\n"
                        "$('t_68_rack').style.display='none';\n"
                        "$('alarm_t_1').style.display='none';\n"
                        "$('alarm_t_sys').style.display='none';\n"
                        "$('fault_t_1').style.display='none';\n"
                    "}else{\n"
                        "$('t_68_sys').style.display='block';\n"
                        "$('t_68_rack').style.display='none';\n"
                        "$('alarm_t_1').style.display='none';\n"
                        "$('alarm_t_sys').style.display='none';\n"
                        "$('fault_t_1').style.display='none';\n"
                        "$('alarm_t_2').style.display='none';\n"
                        "$('fault_t_2').style.display='none';\n"
                        "$('info').style.display='none';\n"
                    "}\n"
"\n"
                    "if(Json.ID_0x0354==0){\n"
                        "$('pager').style.display='none';\n"
                    "}else{\n"
                        "$('pager').style.display='block';\n"
                        "mpager=new PagerView('pager',lang.N500[language],lang.N502[language],lang.N503[language]);\n"
                    "}\n"
  "\n"
                    "mpager.itemCount=Json.ID_0x0354;\n"
                    "mpager.size=1;\n"
                    "mpager.index=1; \n"
                    "CurBms = mpager.index;\n"
                    "Get_Bms_Index(CurBms);               \n"
                    "mpager.onclick=function(index)\n"
                    "{  \n"
                        "CurBms = index;\n"
                         //获取PCS储能逆变器信息
                        "Get_Bms_Index(index);\n"
                    "};\n"
                     //index显示更新
                    "mpager.render();\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}        \n"
        "function Init()\n"
        "{\n"
            "ajax();\n"
            "setInterval('Get_Bms_Index(CurBms)', 2000);\n"
        "}   \n"
    "</script>\n"
"</html>\n"
};
#endif
