#ifndef _HTML_H_015_H_
#define _HTML_H_015_H_
static const char h_015[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
        "<script src='j_001.js' type='text/javascript'></script>\n"
        "<style type='text/css'>\n"
        "tr{height:27px;}\n"
        ".td1{text-align:left;padding-left:40px;}\n"
        ".td2{text-align:right;padding-right:5px;}\n"
        ".td3{text-align:right;padding-right:40px;}\n"
        ".div_tab{width:780px;height:45px;margin:0 auto;}\n"
        ".div_btn{width:80px;margin:0 auto;height:30px;text-align:right;margin-top:8px;float:left;}\n"
        ".div_text{width:80px;margin:0 auto;height:25px;text-align:right;margin-top:10px;float:left;}\n"
        ".div_span{width:40px;margin:0 auto;height:25px;font-size:16px;font-weight:bold;text-align:right;margin-top:12px;float:left;}\n"
        ".btn{width:75px;height:30px;}\n"
        ".PagerView{font-size:14px;font-family:tahoma,arial;font-weight:bold;color:#333;text-align:center;padding:8px;line-height:100%;}\n"
        ".PagerView span{color:#999;margin:0 1px;padding:3px 6px;border:1px solid #ccc;}\n"
        ".PagerView span.on{color:#fff;font-weight:bold;border:1px solid #666;background:#888;} \n"
        ".PagerView a{color:#00f;text-decoration:none;}\n"
        ".PagerView a span{color:#33f;border:1px solid #888;}\n"
        ".pager{width:780px;margin:0 auto;}\n"
        "</style>\n"
        "<script type=\"text/javascript\" src=\"jquery.min.js\"></script>\n"
        "<script type=\"text/javascript\" src=\"j_highcharts.js\"></script>\n"
        "<script type='text/javascript'>\n"
            "var DC1=new Array('N003','N004','N005','N006');\n"
            "var DC2=new Array('ID_0x0131','ID_0x0132','ID_0x0133','ID_0x0134');\n"
            "var DC3=new Array('V','A','V','A');\n"
    "\n"
            "var AC1=new Array('N011','','N012','','N013','','N008','N009','N010','N014');\n"
            "var AC2=new Array('ID_0x0135','','ID_0x0136','','ID_0x0137','','ID_0x0139','ID_0x013A','ID_0x013B','ID_0x0138');\n"
            "var AC3=new Array('V','','V','','V','','kW','kVar','','Hz');\n"
                                "\n"
            "var STAC1=new Array('N016');\n"
            "var STAC2=new Array('ID_0x013C');\n"
            "var STAC3=new Array('kWh');\n"
"\n"
            "var RUN1=new Array('N019','N020','N050','N018');\n"
            "var RUN2=new Array('ID_0x013F','ID_0x0140','ID_0x013D','ID_0x013E');\n"
            "var RUN3=new Array('','%','','');            \n"
            "function show_SUB(TR1,TR2,TR3)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<table width='90%' border='0'>\";\n"
                "for(var i=0;i<TR1.length;i+=2)\n"
                "{\n"
                    "str+=\"<tr id='\"+TR1[i]+i+\"' style='width:100%;height:24;'>\";\n"
                        "str+=\"<td width='25%' class='td1 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR1[i]+\"'></span></td>\";\n"
                        "str+=\"<td width='15%' class='td2 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR2[i]+\"'></span></td>\";\n"
                        "str+=\"<td width='10%' class='td3 \"+(i%4?\"even\":\"odd\")+\"'>\"+TR3[i]+\"</td>\";\n"
                        "if(i+1!=TR1.length)\n"
                        "{\n"
                            "str+=\"<td width='25%' class='td1 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR1[i+1]+\"'></span></td>\";\n"
                            "str+=\"<td width='15%' class='td2 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR2[i+1]+\"'></span></td>\";\n"
                            "str+=\"<td width='10%' class='td3 \"+(i%4?\"even\":\"odd\")+\"'>\"+TR3[i+1]+\"</td>\";\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "str+=\"<td width='25%' class='td1 \"+(i%4?\"even\":\"odd\")+\"'></td>\";\n"
                            "str+=\"<td width='15%' class='td2 \"+(i%4?\"even\":\"odd\")+\"'></td>\";\n"
                            "str+=\"<td width='10%' class='td3 \"+(i%4?\"even\":\"odd\")+\"'></td>\";\n"
                        "}\n"
                        "\n"
                    "str+=\"</tr>\";\n"
                "}\n"
                "str+=\"</table>\";\n"
                "document.write(str);\n"
            "}\n"
        "var PagerView=function(id,AAA,BBB,CCC)\n"
            "{\n"
                "var self=this;\n"
                "this.id=id;\n"
                "this._pageCount=0;\n"
                "this._start=1;\n"
                "this._end=1;\n"
                "this.container=null;\n"
                "this.index=1;\n"
                "this.size=10;\n"
                "this.maxButtons=18;\n"
                "this.itemCount=0;\n"
                "this.onclick=function(index){return true;};\n"
                "this._onclick=function(index)\n"
                "{\n"
                    "var old=self.index;\n"
                    "self.index=index;\n"
                    "if(self.onclick(index)!==false)self.render();\n"
                    "else self.index=old;\n"
                "};\n"
                "this._calculate=function()\n"
                "{\n"
                    "self._pageCount=parseInt(Math.ceil(self.itemCount/self.size));\n"
                    "self.index=parseInt(self.index);\n"
                    "if(self.index>self._pageCount)self.index=self._pageCount;\n"
                    "if(self.index<1)self.index=1;\n"
                    "self._start=Math.max(1,self.index-parseInt(self.maxButtons/2));\n"
                    "self._end=Math.min(self._pageCount,self._start+self.maxButtons-1);\n"
                    "self._start=Math.max(1,self._end-self.maxButtons+1);\n"
                "};\n"
                "this.page=function(rows)\n"
                "{\n"
                    "self._calculate();\n"
                    "var s_num=(self.index-1)*self.size ;\n"
                    "var e_num=self.index*self.size;\n"
                    "return rows.slice(s_num,e_num);\n"
                "};\n"
                "this.render=function()\n"
                "{\n"
                    "var div=document.getElementById(self.id);\n"
                    "div.view=self;\n"
                    "self.container=div;\n"
                    "self._calculate();\n"
                    "var str='';\n"
                    "str+='<div class=\"PagerView\">\\n';\n"
                    "if(self._pageCount>1)\n"
                    "{\n"
                        "if(self.index!=1)\n"
                        "{\n"
                            "str+='<a href=\"javascript://1\"><span>|&lt;</span></a>';\n"
                            "str+='<a href=\"javascript://'+(self.index-1)+'\"><span>&lt;&lt;</span></a>';\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "str+='<span>|&lt;</span>';\n"
                            "str+='<span>&lt;&lt;</span>';\n"
                        "}\n"
                    "}\n"
                    "for(var i=self._start;i<=self._end;i++)\n"
                    "{\n"
                        "if(i==this.index)\n"
                        "{\n"
                            "if(i<10)str+='<span class=\"on\">'+'0'+i+\"</span>\";\n"
                            "else str+='<span class=\"on\">'+i+\"</span>\";\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "if(i<10)str+='<a href=\"javascript://'+i+'\"><span>'+'0'+i+\"</span></a>\";\n"
                            "else str+='<a href=\"javascript://'+i+'\"><span>'+i+\"</span></a>\";\n"
                        "}\n"
                    "}\n"
                    "if(self._pageCount>1)\n"
                    "{\n"
                        "if(self.index!=self._pageCount)\n"
                        "{\n"
                            "str+='<a href=\"javascript://'+(self.index+1)+'\"><span>&gt;&gt;</span></a>';\n"
                            "str+='<a href=\"javascript://'+self._pageCount+'\"><span>&gt;|</span></a>';\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "str+='<span>&gt;&gt;</span>';\n"
                            "str+='<span>&gt;|</span>';\n"
                        "}\n"
                    "}\n"
                    "str+=AAA+self._pageCount+BBB+self.itemCount+CCC;\n"
                    "str+='</div><!--/.pagerView-->\\n';\n"
                    "self.container.innerHTML=str;\n"
                    "var a_list=self.container.getElementsByTagName('a');\n"
                    "for(var i=0;i<a_list.length;i++)\n"
                    "{\n"
                        "a_list[i].onclick=function()\n"
                        "{\n"
                            "var index=this.getAttribute('href');\n"
                            "if(index!=undefined&&index!='')\n"
                            "{\n"
                                "index=parseInt(index.replace('javascript://',''));\n"
                                "self._onclick(index);\n"
                            "}\n"
                            "return false;\n"
                        "};\n"
                    "}\n"
                "};\n"
            "};\n"
        "</script>\n"
    "</head>\n"
    "<body onload='Init();'>\n"
        "<script type='text/javascript'>\n"
            "show_T('N001');\n"
        "</script>        \n"
        "<div id='pager' width='90%' style='padding-left:5%;float:left;'></div>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N017');\n"
            "show_SUB(RUN1,RUN2,RUN3);\n"
        "</script> \n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N002');\n"
            "show_SUB(DC1,DC2,DC3);\n"
        "</script>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N007');\n"
            "show_SUB(AC1,AC2,AC3);\n"
        "</script>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N015');\n"
            "show_SUB(STAC1,STAC2,STAC3);\n"
        "</script>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>\n"
        "<div style='width:780px;margin:0 auto;' id='fault_code'></div>\n"
        "<div class='btm_blank'></div>\n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
         //var $=function(o){return document.getElementById(o);};
        "var language=0;\n"
        "var Json;\n"
        "var CurPv;\n"
        "var lang=\n"
        "{\n"
            "N001:['光伏逆变器信息','PV Information'],\n"
            "N002:['直流侧信息','DC Information'],\n"
            "N003:['光伏直流电压1','DC Voltage1'],\n"
            "N004:['光伏直流电流1','PV DC Current1'],\n"
            "N005:['光伏直流电压2','DC Voltage2'],\n"
            "N006:['光伏直流电流2','PV DC Current2'],\n"
            "N007:['交流侧信息','AC Information'],\n"
            "N008:['光伏有功功率','PV Active Power'],\n"
            "N009:['光伏无功功率','PV Reactive Power'],\n"
            "N010:['光伏功率因数','PV Powerfactor'],\n"
            "N011:['光伏电网电压VA','VA'],\n"
            "N012:['光伏电网电压VB','VB'],\n"
            "N013:['光伏电网电压VC','VC'],\n"
            "N014:['光伏电网频率','PV Frequency'],\n"
            "N015:['统计信息','Statistics Information'],\n"
            "N016:['光伏累计发电','E-PV Total'],\n"
            "N017:['运行信息','Runing Info'],\n"
            "N018:['光伏开关机','PV ON-OFF'],\n"
            "N019:['光伏限功率开关','PV Power Limit SW'],\n"
            "N020:['光伏限功率设置','PV Power Limit Val'],\n"
            "N021:['第：','No.：'],\n"
            "N022:['共：','All：'],\n"
            "N023:['实时功率', 'Real-time Power'],\n"
"\n"
            "N029:['无操作','NO operation'],\n"
            "N030:['开机','Runing'],\n"
            "N031:['关机','Stoped'],\n"
            "N032:['关闭','Disable'],\n"
            "N033:['启用','Enable'],\n"
        "\n"
            "N050:['光伏工作状态','PV Work Status'],\n"
"\n"
            "N060:['无通讯','Com fail'],\n"
            "N061:['运行','Running'],\n"
            "N062:['直流过压','DC overvoltage'],\n"
            "N063:['直流欠压','DC undervoltage'],\n"
            "N064:['直流过流','DC overcurrent'],\n"
            "N065:['电网过压','Grid overvoltage'],\n"
            "N066:['电网欠压','Grid undervoltage'],\n"
            "N067:['变压器过温','Trans. over T'],\n"
            "N068:['频率故障','Frequence fault'],\n"
            "N069:['孤岛故障','Island fault'],\n"
            "N070:['温度故障','Temper. fault'],\n"
            "N071:['硬件故障','Hardware fault'],\n"
            "N072:['接地故障','GND-con fault'],\n"
            "N073:['模块故障','Module fault'],\n"
            "N074:['',''],\n"
            "N075:['',''],\n"
            "N076:['接触器故障','Contactor fault'],\n"
            "N077:['停机','Stopped'],\n"
            "N078:['初始待机','Initial standby'],\n"
            "N079:['按键关机','Key poweroff'],\n"
            "N080:['待机','Standby'],\n"
            "N081:['紧急停机','Emergency stop'],\n"
            "N082:['启动中','Starting'],\n"
            "N083:['电网过频','Grid overfrequency'],\n"
            "N084:['电网欠频','Grid underfrequency'],\n"
            "N085:['直流母线过压','DC-bus overvoltage'],\n"
            "N086:['直流母线欠压','DC-bus undervoltage'],\n"
            "N087:['通讯故障','Comm fault'],\n"
            "N088:['直流分量','DC component'],\n"
            "N089:['逆变过压','Invert overvoltage'],\n"
            "N090:['输出过载','overload'],\n"
            "N091:['蓄电池过压','Bat. overvoltage'],\n"
            "N092:['继电器故障','Relay fault'],\n"
            "N093:['蓄电池欠压','Bat. undervoltage'],\n"
            "N094:['ENS故障','ENS fault'],\n"
            "N095:['电网过流','Grid overcurrent'],\n"
            "N096:['升级失败','Update fail'],\n"
            "N097:['模块过温','Module over T'],\n"
            "N098:['GFDI故障','GFDI fault'],\n"
            "N099:['绝缘阻抗','Isolation fault'],\n"
            "N100:['休眠','Sleep'],\n"
            "N101:['直流熔断器故障','DC fuse fault'],\n"
            "N102:['电抗器过温','Reactor over T'],\n"
            "N103:['风机故障','Fan fault'],\n"
            "N104:['防雷器故障','SPD fault'],\n"
            "N105:['风扇故障','Blower fault'],\n"
            "N106:['散热器故障','Heat sink fault'],\n"
            "N107:['采样故障','Sample fault'],\n"
            "N108:['直流2过压','DC-2 overvoltage'],\n"
            "N109:['直流2过流','DC-2 overcurrent'],\n"
            "N110:['硬件保护','Hareware protect'],\n"
            "N111:['检测熔断器故障','Detection fuse fault'],\n"
            "N112:['接触器吸合','Contact ON'],\n"
            "N113:['接触器断开','Contact OFF'],\n"
            "N114:['关机中','Stopping'],\n"
            "N115:['直流脱扣','DC tripped'],\n"
            "N116:['交流脱扣','AC tripped'],\n"
            "N117:['故障','Fault'],\n"
            "N118:['降额运行','Derated capacity'],\n"
            "N119:['调度运行','Dispatching operation'],\n"
            "N120:['告警运行','Warining operation'],\n"
"\n"
            "N500:['一共','Total '],\n"
            "N501:['页，共',' Pages, '],\n"
            "N502:['页，共',' Page, '],\n"
            "N503:['台',' Nums'],\n"
            "N504:['台',' Num']\n"
        "};\n"
"\n"
         //获取串口PV数据
        "function Get_PV_Index(index)\n"
        "{\n"
            "eval('var URL=\\'s_015.html?0x'+(0+index).toString(16).toUpperCase()+'&time=\\'+Math.random();');\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);   \n"
                    "if(Json.ID_0x02B1 == 0)\n"
                    "{\n"
                         //直流电压1
                        "document.getElementById('ID_0x0131').innerHTML=(Json.ID_0x0131/10.0).toFixed(1);\n"
                         //直流电流1
                        "document.getElementById('ID_0x0132').innerHTML=(Json.ID_0x0132/10.0).toFixed(1);\n"
                         //直流电压2
                        "document.getElementById('ID_0x0133').innerHTML=(Json.ID_0x0133/10.0).toFixed(1);\n"
                         //直流电流2
                        "document.getElementById('ID_0x0134').innerHTML=(Json.ID_0x0134/10.0).toFixed(1);\n"
                         //VA
                        "document.getElementById('ID_0x0135').innerHTML=(Json.ID_0x0135/10.0).toFixed(1);\n"
                         //VB
                        "document.getElementById('ID_0x0136').innerHTML=(Json.ID_0x0136/10.0).toFixed(1);\n"
                         //VC
                        "document.getElementById('ID_0x0137').innerHTML=(Json.ID_0x0137/10.0).toFixed(1);\n"
                         //电网频率
                        "document.getElementById('ID_0x0138').innerHTML=(Json.ID_0x0138/10.0).toFixed(1);\n"
                         //有功功率
                        "document.getElementById('ID_0x0139').innerHTML=(Json.ID_0x0139/10.0).toFixed(1);\n"
                         //无功功率
                        "document.getElementById('ID_0x013A').innerHTML=(Json.ID_0x013A/10.0).toFixed(1);\n"
                         //功率因数
                        "document.getElementById('ID_0x013B').innerHTML=(Json.ID_0x013B/1000.0).toFixed(3);\n"
                         //累计发电量
                        "document.getElementById('ID_0x013C').innerHTML=Json.ID_0x013C;\n"
                         //开关机状态
                        "if(Json.ID_0x013E == 0xce) { document.getElementById('ID_0x013E').innerHTML=lang.N031[language]; }\n"
                        "else if(Json.ID_0x013E == 0xcf) {  document.getElementById('ID_0x013E').innerHTML=lang.N030[language]; }\n"
                        "else { document.getElementById('ID_0x013E').innerHTML=lang.N029[language]; }\n"
                         //限功率开关状态
                        "if(Json.ID_0x013F == 0x55) {  document.getElementById('ID_0x013F').innerHTML=lang.N032[language]; }\n"
                        "else if(Json.ID_0x013F == 0xAA) { document.getElementById('ID_0x013F').innerHTML=lang.N033[language]; }\n"
                         //限功率值
                        "document.getElementById('ID_0x0140').innerHTML=(Json.ID_0x0140/10.0).toFixed(1);\n"
                         //工作状态
                        "eval('document.getElementById(\\'ID_0x013D\\').innerHTML=lang.N'+(Json.ID_0x013D>39?(Json.ID_0x013D+60):'0'+(Json.ID_0x013D+60))+'[language];');\n"
                        "if(Json.ID_0x013D == 0 || Json.ID_0x013D == 21) \n"
                        "{\n"
                             "document.getElementById('ID_0x013D').style.color='#ff6820';\n"
                             "document.getElementById('ID_0x013D').style.fontWeight='bold';                    \n"
                        "}\n"
                        "else if((Json.ID_0x013D >= 2 && Json.ID_0x013D <= 13) ||\n"
                            "(Json.ID_0x013D  == 16) ||\n"
                            "(Json.ID_0x013D >= 23 && Json.ID_0x013D <= 39) ||\n"
                            "(Json.ID_0x013D >= 41 && Json.ID_0x013D <= 51) ||\n"
                            "(Json.ID_0x013D >= 55 && Json.ID_0x013D <= 57))\n"
                        "{\n"
                            "document.getElementById('ID_0x013D').style.color='#ff0000';\n"
                            "document.getElementById('ID_0x013D').style.fontWeight='bold';\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "document.getElementById('ID_0x013D').style.fontWeight='normal';\n"
                            "document.getElementById('ID_0x013D').style.color='#000';\n"
                        "}                \n"
                    "}     \n"
                    "else\n"
                    "{\n"
                         //直流电压1
                        "document.getElementById('ID_0x0131').innerHTML='--';\n"
                         //直流电流1
                        "document.getElementById('ID_0x0132').innerHTML='--';\n"
                         //直流电压2
                        "document.getElementById('ID_0x0133').innerHTML='--';\n"
                         //直流电流2
                        "document.getElementById('ID_0x0134').innerHTML='--';\n"
                         //VA
                        "document.getElementById('ID_0x0135').innerHTML='--';\n"
                         //VB
                        "document.getElementById('ID_0x0136').innerHTML='--';\n"
                         //VC
                        "document.getElementById('ID_0x0137').innerHTML='--';\n"
                         //电网频率
                        "document.getElementById('ID_0x0138').innerHTML='--';\n"
                         //有功功率
                        "document.getElementById('ID_0x0139').innerHTML='--';\n"
                         //无功功率
                        "document.getElementById('ID_0x013A').innerHTML='--';\n"
                         //功率因数
                        "document.getElementById('ID_0x013B').innerHTML='--';\n"
                         //累计发电量
                        "document.getElementById('ID_0x013C').innerHTML='--';\n"
                         //开关机状态
                        "document.getElementById('ID_0x013E').innerHTML='--';\n"
                         //限功率开关状态
                        "document.getElementById('ID_0x013F').innerHTML='--';\n"
                         //限功率值
                        "document.getElementById('ID_0x0140').innerHTML='--';\n"
                         //工作状态
                        "document.getElementById('ID_0x013D').innerHTML='--';\n"
                        "document.getElementById('ID_0x013D').style.fontWeight='normal';\n"
                        "document.getElementById('ID_0x013D').style.color='#000';\n"
                    "}\n"
                "}\n"
            "};\n"
             "xmlhttp.open('GET',URL,true);\n"
             "xmlhttp.send(); \n"
        "}         \n"
        "function ajax()\n"
        "{\n"
            "var URL='s_015.html?time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);           \n"
                    "if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                    "for(var i=1;i<=20;i++)\n"
                    "{\n"
                        "eval('document.getElementById(\\'N0'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N0'+(i<10?'0'+i:i)+'[language];');\n"
                    "}\n"
                    "document.getElementById('N050').innerHTML=lang.N050[language];\n"
                    "if(Json.ID_0x0351==0){\n"
                        "document.getElementById('pager').style.display='none';\n"
                    "}else{\n"
                        "document.getElementById('pager').style.display='block';\n"
                        "mpager=new PagerView('pager',lang.N500[language],lang.N502[language],lang.N503[language]);\n"
                    "}\n"
  "\n"
                    "mpager.itemCount=Json.ID_0x0351;\n"
                    "mpager.size=1;\n"
                    "mpager.index=1; \n"
                    "CurPv = mpager.index;\n"
                    "Get_PV_Index(CurPv);               \n"
                    "mpager.onclick=function(index)\n"
                    "{  \n"
                        "CurPv = index;\n"
                         //获取PV储能逆变器信息
                        "Get_PV_Index(index);\n"
                    "};\n"
                     //index显示更新
                    "mpager.render(); \n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}        \n"
        "function Init()\n"
        "{\n"
            "ajax();\n"
            "setInterval('Get_PV_Index(CurPv)', 2000);\n"
        "}    \n"
    "</script>\n"
"</html>\n"
};
#endif
