#ifndef _HTML_H_026_H_
#define _HTML_H_026_H_
static const char h_026[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
        "<script src='j_001.js' type='text/javascript'></script>\n"
        "<style type='text/css'>\n"
        "tr{height:27px;}\n"
        ".td1{text-align:left;padding-left:40px;}\n"
        ".td2{text-align:right;padding-right:5px;}\n"
        ".td3{text-align:right;padding-right:40px;}\n"
        ".div_tab{width:780px;height:45px;margin:0 auto;}\n"
        ".div_btn{width:80px;margin:0 auto;height:30px;text-align:right;margin-top:8px;float:left;}\n"
        ".div_text{width:80px;margin:0 auto;height:25px;text-align:right;margin-top:10px;float:left;}\n"
        ".div_span{width:40px;margin:0 auto;height:25px;font-size:16px;font-weight:bold;text-align:right;margin-top:12px;float:left;}\n"
        ".btn{width:75px;height:30px;}\n"
        ".PagerView{font-size:14px;font-family:tahoma,arial;font-weight:bold;color:#333;text-align:center;padding:8px;line-height:100%;}\n"
        ".PagerView span{color:#999;margin:0 1px;padding:3px 6px;border:1px solid #ccc;}\n"
        ".PagerView span.on{color:#fff;font-weight:bold;border:1px solid #666;background:#888;} \n"
        ".PagerView a{color:#00f;text-decoration:none;}\n"
        ".PagerView a span{color:#33f;border:1px solid #888;}\n"
        ".pager{width:780px;margin:0 auto;}\n"
        "</style>\n"
        "<script type='text/javascript'>\n"
            "var DC1=new Array('N003','N004','N005','N006','N007','','N008','');\n"
            "var DC2=new Array('ID_0x00C2','ID_0x00C3','ID_0x00C4','ID_0x00C5','ID_0x00C6','','ID_0x00C7','');\n"
            "var DC3=new Array('V','V','V','kW','Var','','','','','');\n"
              "\n"
            "function show_SUB(TR1,TR2,TR3)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<table width='90%' border='0'>\";\n"
                "for(var i=0;i<TR1.length;i+=2)\n"
                "{\n"
                    "str+=\"<tr id='\"+TR1[i]+i+\"'>\";\n"
                        "str+=\"<td width='253' class='td1 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR1[i]+\"'></span></td>\";\n"
                        "str+=\"<td width='80' class='td2 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR2[i]+\"'></span></td>\";\n"
                        "str+=\"<td width='34' class='td3 \"+(i%4?\"even\":\"odd\")+\"'>\"+TR3[i]+\"</td>\";\n"
                        "if(i+1!=TR1.length)\n"
                        "{\n"
                            "str+=\"<td width='253' class='td1 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR1[i+1]+\"'></span></td>\";\n"
                            "str+=\"<td width='80' class='td2 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR2[i+1]+\"'></span></td>\";\n"
                            "str+=\"<td width='34' class='td3 \"+(i%4?\"even\":\"odd\")+\"'>\"+TR3[i+1]+\"</td>\";\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "str+=\"<td width='253' class='td1 \"+(i%4?\"even\":\"odd\")+\"'></td>\";\n"
                            "str+=\"<td width='80' class='td2 \"+(i%4?\"even\":\"odd\")+\"'></td>\";\n"
                            "str+=\"<td width='34' class='td3 \"+(i%4?\"even\":\"odd\")+\"'></td>\";\n"
                        "}\n"
                        "\n"
                    "str+=\"</tr>\";\n"
                "}\n"
                "str+=\"</table>\";\n"
                "document.write(str);\n"
            "}\n"
        "var PagerView=function(id,AAA,BBB,CCC)\n"
            "{\n"
                "var self=this;\n"
                "this.id=id;\n"
                "this._pageCount=0;\n"
                "this._start=1;\n"
                "this._end=1;\n"
                "this.container=null;\n"
                "this.index=1;\n"
                "this.size=10;\n"
                "this.maxButtons=18;\n"
                "this.itemCount=0;\n"
                "this.onclick=function(index){return true;};\n"
                "this._onclick=function(index)\n"
                "{\n"
                    "var old=self.index;\n"
                    "self.index=index;\n"
                    "if(self.onclick(index)!==false)self.render();\n"
                    "else self.index=old;\n"
                "};\n"
                "this._calculate=function()\n"
                "{\n"
                    "self._pageCount=parseInt(Math.ceil(self.itemCount/self.size));\n"
                    "self.index=parseInt(self.index);\n"
                    "if(self.index>self._pageCount)self.index=self._pageCount;\n"
                    "if(self.index<1)self.index=1;\n"
                    "self._start=Math.max(1,self.index-parseInt(self.maxButtons/2));\n"
                    "self._end=Math.min(self._pageCount,self._start+self.maxButtons-1);\n"
                    "self._start=Math.max(1,self._end-self.maxButtons+1);\n"
                "};\n"
                "this.page=function(rows)\n"
                "{\n"
                    "self._calculate();\n"
                    "var s_num=(self.index-1)*self.size ;\n"
                    "var e_num=self.index*self.size;\n"
                    "return rows.slice(s_num,e_num);\n"
                "};\n"
                "this.render=function()\n"
                "{\n"
                    "var div=document.getElementById(self.id);\n"
                    "div.view=self;\n"
                    "self.container=div;\n"
                    "self._calculate();\n"
                    "var str='';\n"
                    "str+='<div class=\"PagerView\">\\n';\n"
                    "if(self._pageCount>1)\n"
                    "{\n"
                        "if(self.index!=1)\n"
                        "{\n"
                            "str+='<a href=\"javascript://1\"><span>|&lt;</span></a>';\n"
                            "str+='<a href=\"javascript://'+(self.index-1)+'\"><span>&lt;&lt;</span></a>';\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "str+='<span>|&lt;</span>';\n"
                            "str+='<span>&lt;&lt;</span>';\n"
                        "}\n"
                    "}\n"
                    "for(var i=self._start;i<=self._end;i++)\n"
                    "{\n"
                        "if(i==this.index)\n"
                        "{\n"
                            "if(i<10)str+='<span class=\"on\">'+'0'+i+\"</span>\";\n"
                            "else str+='<span class=\"on\">'+i+\"</span>\";\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "if(i<10)str+='<a href=\"javascript://'+i+'\"><span>'+'0'+i+\"</span></a>\";\n"
                            "else str+='<a href=\"javascript://'+i+'\"><span>'+i+\"</span></a>\";\n"
                        "}\n"
                    "}\n"
                    "if(self._pageCount>1)\n"
                    "{\n"
                        "if(self.index!=self._pageCount)\n"
                        "{\n"
                            "str+='<a href=\"javascript://'+(self.index+1)+'\"><span>&gt;&gt;</span></a>';\n"
                            "str+='<a href=\"javascript://'+self._pageCount+'\"><span>&gt;|</span></a>';\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "str+='<span>&gt;&gt;</span>';\n"
                            "str+='<span>&gt;|</span>';\n"
                        "}\n"
                    "}\n"
                    "str+=AAA+self._pageCount+BBB+self.itemCount+CCC;\n"
                    "str+='</div><!--/.pagerView-->\\n';\n"
                    "self.container.innerHTML=str;\n"
                    "var a_list=self.container.getElementsByTagName('a');\n"
                    "for(var i=0;i<a_list.length;i++)\n"
                    "{\n"
                        "a_list[i].onclick=function()\n"
                        "{\n"
                            "var index=this.getAttribute('href');\n"
                            "if(index!=undefined&&index!='')\n"
                            "{\n"
                                "index=parseInt(index.replace('javascript://',''));\n"
                                "self._onclick(index);\n"
                            "}\n"
                            "return false;\n"
                        "};\n"
                    "}\n"
                "};\n"
            "};\n"
        "</script>\n"
    "</head>\n"
    "<body onload='Init();'>\n"
        "<script type='text/javascript'>\n"
            "show_T('N001');\n"
        "</script>        \n"
        "<div id='pager' width='90%' style='padding-left:5%;float:left;'></div>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N002');\n"
            "show_SUB(DC1,DC2,DC3);\n"
        "</script>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>      \n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var $=function(o){return document.getElementById(o);};\n"
        "var language=0;\n"
        "var Json;\n"
        "var CurAmmeter;\n"
        "var lang=\n"
        "{\n"
            "N001:['电表信息','Ammeter Information'],\n"
            "N002:['交流信息','AC Information'],\n"
            "N003:['Vab','Vab'],\n"
            "N004:['Vbc','Vbc'],\n"
            "N005:['Vac','Uac'],\n"
            "N006:['电表有功功率','Active Power'],\n"
            "N007:['电表无功功率','Reactive Power'],\n"
            "N008:['电表功率因数','Power Factor'],\n"
            "N009:['工作状态','Working Status'],\n"
            "N010:['第：','No.：'],\n"
            "N011:['共：','All：'],\n"
        "\n"
            "N060:['故障信息','Fault Information'],\n"
            "N061:['故障&nbsp;','Fault&nbsp;'],\n"
            "N062:['直流过压','DC Voltage High'],\n"
            "N063:['直流欠压','DC Voltage Low'],\n"
            "N064:['直流过流','DC Current High'],\n"
            "N065:['电网过压','AC Voltage High'],\n"
            "N066:['电网欠压','AC Voltage Low'],\n"
            "N067:['电网过频','AC Frequency High'],\n"
            "N068:['电网欠频','AC Frequency Low'],\n"
            "N069:['交流过流','AC Current High'],\n"
            "N070:['交流漏电流保护','I-leak Protection'],\n"
            "N071:['孤岛保护','Island Protection'],\n"
            "N072:['相位异常','Phase Fault'],\n"
            "N073:['独立逆变过压保护','Vind-inv High'],\n"
            "N074:['交流电压不平衡','AC Voltage Unbalanced'],\n"
            "N075:['交流电流不平衡','AC Current Unbalanced'],\n"
            "N076:['环境过温','Temp High'],\n"
            "N077:['模块A1过温','Module A1 Temp High'],\n"
            "N078:['模块B1过温','Module B1 Temp High'],\n"
            "N079:['模块C1过温','Module C1 Temp High'],\n"
            "N080:['变压器过温','Transformer Temp High'],\n"
            "N081:['电抗器1过温','Reactor 1 Temp High'],\n"
            "N082:['电抗器2过温','Reactor 2 Temp High'],\n"
            "N083:['模块故障','Module Fault'],\n"
            "N084:['风扇故障','Fan Fault'],\n"
            "N085:['传感器失效','Sensor Error'],\n"
            "N046:['交流主接触器故障','AC Main Contactor Fault'],\n"
            "N087:['直流主接触器故障','DC Main Contactor Fault'],\n"
            "N088:['AD采样故障','AD Sample Fault'],\n"
            "N089:['B相电流采样故障','AD Sample Fault'],\n"
            "N090:['C相电流采样故障','AD Sample Fault'],\n"
            "N091:['漏电流采样故障','AD Sample Fault'],\n"
            "N092:['',''],\n"
            "N093:['',''],\n"
            "N094:['A相逆变电压采样故障','AD Sample Fault'],\n"
            "N095:['B相逆变电压采样故障','AD Sample Fault'],\n"
            "N096:['C相逆变电压采样故障','AD Sample Fault'],\n"
            "N097:['A相电容电压采样故障','AD Sample Fault'],\n"
            "N098:['B相电容电压采样故障','AD Sample Fault'],\n"
            "N099:['C相电容电压采样故障','AD Sample Fault'],\n"
            "N100:['',''],\n"
            "N101:['',''],\n"
            "N102:['',''],\n"
            "N103:['电池故障','Battery Fault'],\n"
            "N104:['DSP通讯故障','DSP Com-fault'],\n"
            "N105:['电池通讯故障','BMS Com-fault'],\n"
            "N106:['',''],\n"
            "N107:['',''],\n"
            "N108:['',''],\n"
            "N109:['模块A2过温','Module A2 Temp High'],\n"
            "N110:['模块B2过温','Module B2 Temp High'],\n"
            "N111:['模块C2过温','Module C2 Temp High'],\n"
            "N112:['交流防雷器故障','AC SPD Fault'],\n"
            "N113:['直流熔断器故障','DC Fuse Fault'],\n"
            "N114:['检测熔断器故障','Detc. Fuse Fault'],\n"
            "N115:['极性反接故障','Reversed Polarity Fault'],\n"
            "N116:['',''],\n"
            "N117:['',''],\n"
            "N118:['',''],\n"
            "N119:['',''],\n"
            "N120:['',''],\n"
            "N121:['',''],\n"
            "N122:['',''],\n"
            "N123:['',''],\n"
            "N124:['',''],\n"
            "N125:['',''],\n"
"\n"
            "N500:['一共','Total '],\n"
            "N501:['页，共',' Pages, '],\n"
            "N502:['页，共',' Page, '],\n"
            "N503:['台',' Nums'],\n"
            "N504:['台',' Num']\n"
        "};\n"
         //获取串口Ammeter数据
        "function Get_Ammeter_Index(index)\n"
        "{\n"
            "eval('var URL=\\'s_026.html?0x'+(0+index).toString(16).toUpperCase()+'&time=\\'+Math.random();');\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);   \n"
                    "if(Json.ID_0x02B4 == 0)\n"
                    "{\n"
                        "$('ID_0x00C2').innerHTML=(Json.ID_0x00C2/10.0).toFixed(1);\n"
                        "$('ID_0x00C3').innerHTML=(Json.ID_0x00C3/10.0).toFixed(1);\n"
                        "$('ID_0x00C4').innerHTML=(Json.ID_0x00C4/10.0).toFixed(1);\n"
                        "$('ID_0x00C5').innerHTML=(Json.ID_0x00C5/10.0).toFixed(1);\n"
                        "$('ID_0x00C6').innerHTML=(Json.ID_0x00C6/10.0).toFixed(1);\n"
                        "$('ID_0x00C7').innerHTML=(Json.ID_0x00C7/1000.0).toFixed(3);  \n"
                    "}\n"
                    "else\n"
                    "{\n"
                        "$('ID_0x00C2').innerHTML='--';\n"
                        "$('ID_0x00C3').innerHTML='--';\n"
                        "$('ID_0x00C4').innerHTML='--';\n"
                        "$('ID_0x00C5').innerHTML='--';\n"
                        "$('ID_0x00C6').innerHTML='--';\n"
                        "$('ID_0x00C7').innerHTML='--';        \n"
                    "}\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
             //alert(URL);   
        "} \n"
        "function ajax()\n"
        "{\n"
            "var URL='s_026.html?time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);           \n"
                    "if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                    "for(var i=1;i<=8;i++)\n"
                    "{\n"
                        "eval('$(\\'N0'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N0'+(i<10?'0'+i:i)+'[language];');\n"
                    "}\n"
"\n"
                    "if(Json.ID_0x0355==0){\n"
                        "$('pager').style.display='none';\n"
                    "}else{\n"
                        "$('pager').style.display='block';\n"
                        "mpager=new PagerView('pager',lang.N500[language],lang.N502[language],lang.N503[language]);\n"
                    "}\n"
  "\n"
                    "mpager.itemCount=Json.ID_0x0355;\n"
                    "mpager.size=1;\n"
                    "mpager.index=1; \n"
                    "CurAmmeter = mpager.index;\n"
                    "Get_Ammeter_Index(CurAmmeter);               \n"
                    "mpager.onclick=function(index)\n"
                    "{  \n"
                        "CurAmmeter = index;\n"
                         //获取PCS储能逆变器信息
                        "Get_Ammeter_Index(index);\n"
                    "};\n"
                     //index显示更新
                    "mpager.render();\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}        \n"
        "function Init()\n"
        "{\n"
            "ajax();\n"
            "setInterval('Get_Ammeter_Index(CurAmmeter)', 2000);\n"
        "}  \n"
    "</script>\n"
"</html>\n"
};
#endif
