#ifndef _HTML_H_024_H_
#define _HTML_H_024_H_
static const char h_024[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
 "<head>\n"
 	"<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
 	"<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
 	"<script type='text/javascript'>\n"
            "var $=function(o){return document.getElementById(o);};\n"
            "function lang_init_ex(st,end){for(var i=st;i<=end;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
            "function show_tip(obj){$('tip').innerHTML=obj;}\n"
            "function show_T(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
                "str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_sT(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_sT_ex(tid, id)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' id='\"+id+\"' style='display:none;width:90%'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function sendHttpReq(url, successFn)\n"
            "{\n"
                 //alert(url);   
                "var xmlhttp;\n"
                "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                "xmlhttp.onreadystatechange=function()\n"
                "{\n"
                    "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                    "{\n"
                        "if(xmlhttp.responseText=='1'){successFn();}\n"
                    "}\n"
                "};\n"
                "xmlhttp.open('GET',url,true);\n"
                "xmlhttp.send();\n"
            "}\n"
        "</script>\n"
 	"<style type='text/css'>\n"
 		"tr{height:27px;}\n"
 		".td1{padding-left:40px;text-align:left;}\n"
 		".td2{text-align:left;}\n"
 		".td3{padding-right:40px;text-align:right;}\n"
 		".txt{width:80px;text-align:right;}\n"
            ".tipL{width:255px;margin:0 auto;text-align:left;margin-top:5px;color:#f00;font-weight:bold;font-size:16px;}\n"
 	"</style>\n"
 "</head>\n"
 "<body onload='Init()'>\n"
 	"<script type='text/javascript'>\n"
 		"show_T('N01');\n"
 		"show_sT('N02');\n"
 	"</script>\n"
 	"<!-- 系统功率设置 -->\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
                "<td width='30%' class='td1 odd'><span id='N03'></span></td>\n"
                "<td width='20%' class='td1 odd'><input class='txt' id='ID_0x0384' onkeyup='Verify(this)' type='text' maxlength='7'/>&nbsp;</td>\n"
                "<td width='15%' class='td2 odd'>(0, 29000)kW</td>\n"
                "<td width='35%' class='td3 odd'></td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='50%' class='tipL even'><span id='tip1'>&nbsp;</span></td>\n"
             "<!-- 保存 -->\n"
 			  "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn1' style='display:block;'><span id='N400'>Save</span></button></td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<div class='line_long'></div>\n"
 	"<div class='blank'></div>\n"
        "<!-- 并网模式选择 -->\n"
        "<script type='text/javascript'>\n"
            "show_sT('N40');\n"
        "</script>\n"
            "<!-- 并网模式, 默认不显示 -->\n"
            "<table width='90%' border='0' style='display:block;' id='GRID1'>\n"
                "<tr>\n"
                    "<!-- 恒流模式 -->\n"
                    "<td width='30%' class='td1 odd'><input name='Grid_Mode' type='radio' value='0' id='CC' onclick='Change_Grid_Mode(this)'/><span id='N41'></span></td>\n"
                    "<!-- 恒直流功率模式 -->\n"
                    "<td width='20%' class='td1 odd'><input name='Grid_Mode' type='radio' value='2' id='CP_DC' onclick='Change_Grid_Mode(this)'/><span id='N43'></span></td>\n"
                    "<td width='50%' class='td1 odd'></td>\n"
                "</tr>\n"
                "<tr>\n"
                    "<!-- 恒压模式 -->\n"
                    "<td width='30%' class='td1 even'><input name='Grid_Mode' type='radio' value='1' id='CV' onclick='Change_Grid_Mode(this)'/><span id='N42'></span></td>\n"
                    "<!-- 恒交流功率模式 -->\n"
                    "<td width='70%' class='td1 even'><input name='Grid_Mode' type='radio' value='3' id='CP_AC' onclick='Change_Grid_Mode(this)'/><span id='N44'></span></td>\n"
                "</tr>\n"
                "<tr>\n"
                    "<!-- 待机模式 -->\n"
                    "<td width='30%' class='td1 odd'><input name='Grid_Mode' type='radio' value='4' id='STANDBY' onclick='Change_Grid_Mode(this)'/><span id='N45'></span></td>\n"
                    "<td width='20%' class='td1 odd'></td>\n"
                    "<td width='50%' class='td1 odd'></td>\n"
                "</tr>\n"
            "</table>\n"
            "<!--并网模式,恒流充电电流上下限设置，默认不显示-->\n"
            "<table width='100%' border='0' style='display:none;' id='TR1'>\n"
                "<tr>\n"
                    "<td width='177' class='td1 odd'><span id='N50'></span></td>\n"
                    "<td width='90' class='td2 odd'><input class='txt' id='ID_0x0175' onkeyup='Verify(this,reg4)' type='text' maxlength='7'/>A</td>\n"
                    "<td width='110' class='td3 odd'>(<span id='ID_0x0400'></span>~<span id='ID_0x0401'></span>)</td>\n"
                    "<td width='177' class='td1 odd'></td>\n"
                    "<td width='90' class='td2 odd'></td>\n"
                    "<td width='110' class='td3 odd'></td>\n"
                "</tr>\n"
            "</table>\n"
            "<!-- 并网模式,恒压充电电压上下限设置, 默认不显示 -->\n"
            "<table width='100%' border='0' style='display:none;' id='TR2'>\n"
                "<tr>\n"
                    "<td width='177' class='td1 odd'><span id='N51'></span></td>\n"
                    "<td width='90' class='td2 odd'><input class='txt' id='ID_0x0177' onkeyup='Verify(this,reg1)' type='text' maxlength='6'/>V</td>\n"
                    "<td width='110' class='td3 odd'>(<span id='ID_0x0402'></span>~<span id='ID_0x0403'></span>)</td>\n"
                    "<td width='177' class='td1 odd'><span id='N52'></span></td>\n"
                    "<td width='90' class='td2 odd'><input class='txt' id='ID_0x0176' onkeyup='Verify(this,reg1)' type='text' maxlength='6'/>A</td>\n"
                    "<td width='110' class='td3 odd'>(<span id='ID_0x0404'></span>~<span id='ID_0x0405'></span>)</td>\n"
                "</tr>\n"
            "</table>\n"
            "<!-- 并网模式,恒功率DC功率上下限 -->\n"
            "<table width='100%' border='0' style='display:none;' id='TR3'>\n"
                "<tr>\n"
                    "<td width='177' class='td1 odd'><span id='N53'></span></td>\n"
                    "<td width='90' class='td2 odd'><input class='txt' id='ID_0x0178' onkeyup='Verify(this,reg4)' type='text' maxlength='6'/>kW</td>\n"
                    "<td width='110' class='td3 odd'>(<span id='ID_0x0406'></span>~<span id='ID_0x0407'></span>)</td>\n"
                    "<td width='177' class='td1 odd'></td>\n"
                    "<td width='90' class='td2 odd'></td>\n"
                    "<td width='110' class='td3 odd'></td>\n"
                "</tr>\n"
            "</table>\n"
            "<!-- 并网模式,恒功率AC功率上下限 -->\n"
            "<table width='100%' border='0' style='display:none;' id='TR4'>\n"
                "<tr>\n"
                    "<td width='177' class='td1 odd'><span id='N54'></span></td>\n"
                    "<td width='90' class='td2 odd'><input class='txt' id='ID_0x0179' onkeyup='Verify(this,reg4)' type='text' maxlength='6'/>kW</td>\n"
                    "<td width='110' class='td3 odd'>(<span id='ID_0x040E'></span>~<span id='ID_0x040F'></span></span>)</td>\n"
                    "<td width='177' class='td1 odd'></td>\n"
                    "<td width='90' class='td2 odd'></td>\n"
                    "<td width='110' class='td3 odd'></td>\n"
                "</tr>\n"
            "</table>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='50%' class='tipL even'><span id='tip2'>&nbsp;</span></td>\n"
             "<!-- 保存 -->\n"
 			  "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn2' style='display:block;'><span id='N401'>Save</span></button></td>\n"
 		"</tr>\n"
 	"</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>\n"
        "<!-- 控制方式 -->\n"
        "<script type='text/javascript'>\n"
            "show_sT('N04');\n"
        "</script>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='30%' class='td1 odd'><input name='CONTROL-Mode' type='radio' value='0' id='LoRemo'/><span id='N05'></span></td>\n"
                "<td width='30%' class='td1 odd'><input name='CONTROL-Mode' type='radio' value='1' id='Remote'/><span id='N06'></span></td>\n"
                "<td width='30%' class='td1 odd'><input name='CONTROL-Mode' type='radio' value='2' id='Local'/><span id='N07'></span></td>\n"
        "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='tipL even'><span id='tip3'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn3' style='display:block;'><span id='N402'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>\n"
        "<!-- 离网参数 -->\n"
        "<script type='text/javascript'>\n"
            "show_sT('N08');\n"
        "</script>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='30%' class='td1 odd'><span id='N09'></span></td>\n"
                "<td width='20%' class='td1 odd'><input class='txt' id='ID_0x0180' onkeyup='Verify(this)' type='text' maxlength='6'/>&nbsp;</td>\n"
                "<td width='15%' class='td2 odd'>(<span id='ID_0x0410'></span>~<span id='ID_0x0411'></span>)V</td>\n"
                "<td width='35%' class='td3 odd'></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td width='30%' class='td1 even'><span id='N10'></span></td>\n"
                "<td width='20%' class='td1 even'><input class='txt' id='ID_0x0181' onkeyup='Verify(this)' type='text' maxlength='6'/>&nbsp;</td>\n"
                "<td width='15%' class='td2 even'>(<span id='ID_0x0412'></span>~<span id='ID_0x0413'></span>)Hz</td>\n"
                "<td width='35%' class='td3 even'></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td width='30%' class='td1 odd'><span id='N11'></span></td>\n"
                "<td width='20%' class='td1 odd'><input class='txt' id='ID_0x019A' onkeyup='Verify(this)' type='text' maxlength='6'/>&nbsp;</td>\n"
                "<td width='15%' class='td2 odd'>(<span id='ID_0x0426'></span>~<span id='ID_0x0427'></span>)V</td>\n"
                "<td width='35%' class='td3 odd'></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td width='30%' class='td1 even'><span id='N12'></span></td>\n"
                "<td width='20%' class='td1 even'><input class='txt' id='ID_0x019B' onkeyup='Verify(this)' type='text' maxlength='6'/>&nbsp;</td>\n"
                "<td width='15%' class='td2 even'>(<span id='ID_0x0428'></span>~<span id='ID_0x0429'></span>)V</td>\n"
                "<td width='35%' class='td3 even'></td>\n"
            "</tr>\n"
        "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='tipL odd'><span id='tip4'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='odd'><button class='btn' onclick='doSubmit(this)' id='btn4' style='display:block;'><span id='N403'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>\n"
        "<!-- 柴油机参数 -->\n"
        "<script type='text/javascript'>\n"
            "show_sT('N13');\n"
        "</script>\n"
        "<table width='90%' border='0' id='tNotice' style='font-size:10px;'>\n"
            "<tr>\n"
                "<td width='100%' class='even' align='left'><span id='N497' class='tip' style='font-size:14px;'>&nbsp;</span></td>\n"
            "</tr>\n"
        "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='30%' class='td1 odd'><span id='N14'></span></td>\n"
                "<td width='20%' class='td1 odd'><input class='txt' id='ID_0x0360' onkeyup='Verify(this)' type='text' maxlength='7'/>&nbsp;</td>\n"
                "<td width='15%' class='td2 odd'>(0, 30000)kW</td>\n"
                "<td width='35%' class='td3 odd'></td>\n"
            "</tr>\n"
        "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='tipL even'><span id='tip5'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn5' style='display:block;'><span id='N404'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>\n"
        "<!-- 网口下发周期 -->\n"
        "<script type='text/javascript'>\n"
            "show_sT('N15');\n"
        "</script>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='30%' class='td1 odd'><span id='N16'></span></td>\n"
                "<td width='20%' class='td1 odd'><input class='txt' id='ID_0x0361' onkeyup='Verify(this)' type='text' maxlength='4'/>&nbsp;</td>\n"
                "<td width='15%' class='td2 odd'>(5,2000)ms</td>\n"
                "<td width='35%' class='td3 odd'></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td width='30%' class='td1 even'><span id='N17'></span></td>\n"
                "<td width='20%' class='td1 even'><input class='txt' id='ID_0x0362' onkeyup='Verify(this)' type='text' maxlength='4'/>&nbsp;</td>\n"
                "<td width='15%' class='td2 even'>(1,50)</td>\n"
                "<td width='35%' class='td3 even'></td>\n"
            "</tr>\n"
        "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='tipL odd'><span id='tip6'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='odd'><button class='btn' onclick='doSubmit(this)' id='btn6' style='display:block;'><span id='N405'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>\n"
 	"<div id='trans'></div>\n"
 	"<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
 "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var language=0;\n"
        "var Json;\n"
        "var lang=\n"
        "{\n"
            "N01:['运行设置','Running Settings'],\n"
 		"N02:['系统功率','System Power'],\n"
            "N03:['功率设定','Power Set'],\n"
            "N04:['控制方式','Control Ways'],\n"
            "N05:['本地/远程','Local/ Remote'],\n"
            "N06:['远程','Remote'],\n"
            "N07:['本地','Local'],\n"
            "N08:['离网参数','OffGrid Parameter'],\n"
            "N09:['微网电压设定','MG Voltage Set'],\n"
            "N10:['微网频率设定','MG Frequecy Set'],\n"
            "N11:['并网模式恒压模式放电目标电压','Grid CV-Mode Discharge Target Voltage'],\n"
            "N12:['并网模式恒压模式充电目标电压','Grid CV-Mode Charge Target Voltage'],\n"
            "N13:['运行保护参数', 'Running Protect Param'],\n"
            "N14:['最大逆流功率', 'Max Backwash Power'],\n"
            "N15:['网口参数', 'Net Para'],\n"
            "N16:['发送周期', 'Period of Send'],\n"
            "N17:['设置周期', 'Period of Set'],\n"
"\n"
             //并网模式
            "N40:['并网运行模式','Grid Running Mode'],\n"
            "N41:['恒流模式','CC-Mode'],\n"
            "N42:['恒压模式','CV-Mode'],\n"
            "N43:['恒功率模式(DC)','CP-Mode(DC)'],\n"
            "N44:['恒功率模式(AC)','CP-Mode(AC)'],\n"
            "N45:['待机模式','Standby-Mode'],\n"
"\n"
             //并网模式参数
            "N50:['恒流模式电流','CC-Current'],\n"
            "N51:['恒压模式电压','CV-Vlotage'],\n"
            "N52:['恒压模式电流','CV-Current'],\n"
            "N53:['恒功率模式功率(DC)','CP-Power(DC)'],\n"
            "N54:['恒功率模式功率(AC)','CP-Power(AC)'],          \n"
"\n"
            "N400:['设&nbsp;&nbsp;置','Set'],             \n"
            "N401:['设&nbsp;&nbsp;置','Set'], \n"
            "N402:['设&nbsp;&nbsp;置','Set'],\n"
            "N403:['设&nbsp;&nbsp;置','Set'],\n"
            "N404:['设&nbsp;&nbsp;置','Set'],\n"
            "N405:['设&nbsp;&nbsp;置','Set'],\n"
"\n"
            "N497:['注意：逆流功率需大于PCC功率和限发功率!','Notice: Reflux power need to be greater than PCC power and Limited power!'],\n"
            "N499:['设置成功！','Set successfully!'],\n"
            "N500:['设置失败！','Set Failed!'],\n"
            "N501:['格式错误！','Format error!'],\n"
            "N502:['范围错误！','Range error!']               \n"
        "};\n"
        "function Init()\n"
        "{\n"
            "var URL='s_024.html?0x0000&time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{               \n"
                    "eval('Json='+xmlhttp.responseText);				\n"
     			"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                     //初始化语言
     			"lang_init_ex(1,17);\n"
                    "lang_init_ex(40,45); \n"
                    "lang_init_ex(50,54); \n"
                    "lang_init_ex(400,405);    \n"
                    "lang_init_ex(497,497);\n"
"\n"
     			"doSetValue(Json);\n"
"\n"
     			"if(Json.ID_0x0282==0x11)\n"
     			"{\n"
                        "$('btn1').style.display='none';\n"
     				"$('btn2').style.display='none';\n"
                        "$('btn3').style.display='none';\n"
     				"$('trans').style.zIndex=9999;\n"
     			"}\n"
     			"else\n"
     			"{\n"
                        "$('btn1').style.display='inline';\n"
     				"$('btn2').style.display='inline';\n"
                        "$('btn3').style.display='inline';\n"
     				"$('trans').style.zIndex=-9999;\n"
     			"}\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}\n"
"\n"
         //隐藏并网模式下所有子模式的参数设置框
        "function Hide_box()\n"
        "{\n"
            "for(var i=1;i<=4;i++)eval(\"$('TR\"+i+\"').style.display='none';\");\n"
            "select_nbps();\n"
        "}\n"
         //根据当前并网模式，显示对于的参数设置框
        "function Visit_box(obj)\n"
        "{\n"
            "Hide_box();\n"
             //从obj第2个字符后开始截取字符
             //eval(\"$('TR\"+obj.id.substring(2)+\"').style.display='block';\");
        "}\n"
         //并网模式下子模式间的切换
        "function Change_Grid_Mode(obj)\n"
        "{\n"
            "select_nbps();\n"
            "switch(obj.id)\n"
            "{\n"
                "case 'CC':\n"
                    "Visit_box($('TR1'));\n"
                "break;\n"
                "case 'CV':\n"
                    "Visit_box($('TR2'));\n"
                "break;\n"
                "case 'CP_DC':\n"
                    "Visit_box($('TR3'));\n"
                "break;\n"
                "case 'CP_AC':\n"
                    "Visit_box($('TR4'));\n"
                "break;\n"
                "default:\n"
                    "Hide_box();\n"
                "break;\n"
            "}\n"
        "}\n"
        "function doSetValue(Json)\n"
        "{\n"
         	//系统功率匹配设置
            "$('ID_0x0384').value=Json.ID_0x0384;\n"
"\n"
            "$('ID_0x0360').value=Json.ID_0x0360;\n"
            "$('ID_0x0361').value=Json.ID_0x0361;\n"
            "$('ID_0x0362').value=Json.ID_0x0362;\n"
"\n"
             //独立逆变电压、频率
            "$('ID_0x0180').value=(Json.ID_0x0180/10.0).toFixed(1);\n"
            "$('ID_0x0181').value=(Json.ID_0x0181/100.0).toFixed(2);\n"
            "$('ID_0x019A').value=(Json.ID_0x019A/10.0).toFixed(1);\n"
            "$('ID_0x019B').value=(Json.ID_0x019B/10.0).toFixed(1);            \n"
"\n"
            "$('ID_0x0410').innerHTML=(Json.ID_0x0410/10.0).toFixed(1);\n"
            "$('ID_0x0411').innerHTML=(Json.ID_0x0411/10.0).toFixed(1);\n"
            "$('ID_0x0412').innerHTML=(Json.ID_0x0412/100.0).toFixed(2);\n"
            "$('ID_0x0413').innerHTML=(Json.ID_0x0413/100.0).toFixed(2);\n"
            "$('ID_0x0426').innerHTML=(Json.ID_0x0426/10.0).toFixed(1);\n"
            "$('ID_0x0427').innerHTML=(Json.ID_0x0427/10.0).toFixed(1);\n"
            "$('ID_0x0428').innerHTML=(Json.ID_0x0428/10.0).toFixed(1);\n"
            "$('ID_0x0429').innerHTML=(Json.ID_0x0429/10.0).toFixed(1);\n"
             //并网模式设置
            "switch(Json.ID_0x0187)\n"
            "{\n"
                "case 0:$('CC').checked=true;break;"//$('TR1').style.display='block';break;
                "case 1:$('CV').checked=true;break;"//$('TR2').style.display='block';break;
                "case 2:$('CP_DC').checked=true;break;"//$('TR3').style.display='block';break;
                "case 3:$('CP_AC').checked=true;break;"//$('TR4').style.display='block';break;
                "case 4:$('STANDBY').checked=true;break;\n"
                 //case 5:$('STOP').checked=true;break;
            "}\n"
             //控制模式设置
            "if(Json.ID_0x0183==0){\n"
                "$('LoRemo').checked=true;$('Remote').checked=false;$('Local').checked=false;\n"
            "}if(Json.ID_0x0183==1){\n"
                "$('LoRemo').checked=false;$('Remote').checked=true;$('Local').checked=false;\n"
            "}if(Json.ID_0x0183==2){\n"
                "$('LoRemo').checked=false;$('Remote').checked=false;$('Local').checked=true;\n"
            "}    \n"
        "}\n"
        "function show_tip_ex(id, obj){eval('$(\\'tip'+id+'\\').innerHTML=obj;');}\n"
        "function read_back(addr)\n"
        "{\n"
            "var url='s_024.html?';\n"
            "if(addr == 0x180) {url=url+'0x0180'+'&0x0181'+'&0x019A'+'&0x019B';}\n"
            "else if(addr == 0x361) {url=url+'0x0361'+'&0x0362';}\n"
            "else {url=url+'0x0'+addr.toString(16).toUpperCase();}\n"
            "url=url+'&time='+Math.random();\n"
"\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText); \n"
                    "if(addr == 0x384)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "pr=$('ID_0x0384').value;\n"
                        "fe=Json.ID_0x0384;\n"
                        "if(pr!=fe)$('ID_0x0384').value=Json.ID_0x0384;\n"
                        "show_tip_ex(1,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(1,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(1,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(1,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x187)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('CC').checked){pr=$('CC').value;}\n"
                        "if($('CV').checked){pr=$('CV').value;}\n"
                        "if($('CP_DC').checked){pr=$('CP_DC').value;}\n"
                        "if($('CP_AC').checked){pr=$('CP_AC').value;}\n"
                        "if($('STANDBY').checked){pr=$('STANDBY').value;}\n"
                        "fe=Json.ID_0x0187;\n"
                        "if(pr!=fe){\n"
                            "switch(Json.ID_0x0187)\n"
                            "{\n"
                                "case 0:$('CC').checked=true;break;"//$('TR1').style.display='block';break;
                                "case 1:$('CV').checked=true;break;"//$('TR2').style.display='block';break;
                                "case 2:$('CP_DC').checked=true;break;"//$('TR3').style.display='block';break;
                                "case 3:$('CP_AC').checked=true;break;"//$('TR4').style.display='block';break;
                                "case 4:$('STANDBY').checked=true;break;\n"
                                 //case 5:$('STOP').checked=true;break;
                            "}\n"
                        "}\n"
                        "show_tip_ex(2,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(2,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(2,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(2,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x183)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('LoRemo').checked){pr=$('LoRemo').value;}\n"
                        "if($('Remote').checked){pr=$('Remote').value;}\n"
                        "if($('Local').checked){pr=$('Local').value;}\n"
                        "fe=Json.ID_0x0183;\n"
                        "if(pr!=fe){\n"
                             "if(Json.ID_0x0183==0){\n"
                                "$('LoRemo').checked=true;$('Remote').checked=false;$('Local').checked=false;\n"
                            "}if(Json.ID_0x0183==1){\n"
                                "$('LoRemo').checked=false;$('Remote').checked=true;$('Local').checked=false;\n"
                            "}if(Json.ID_0x0183==2){\n"
                                "$('LoRemo').checked=false;$('Remote').checked=false;$('Local').checked=true;\n"
                            "}\n"
                        "}\n"
                        "show_tip_ex(3,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(3,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(3,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(3,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x180)\n"
                    "{\n"
                        "var pr_vol=0,fe_vol=0;\n"
                        "var pr2_vol=0,fe2_vol=0;\n"
                        "var pr3_vol=0,fe3_vol=0;\n"
                        "var pr_hz=0,fe_hz=0;\n"
                        "pr_vol=$('ID_0x0180').value*10;\n"
                        "pr_hz=$('ID_0x0181').value*100;\n"
                        "pr2_vol=$('ID_0x019A').value*10;\n"
                        "pr3_vol=$('ID_0x019B').value*10;\n"
                        "fe_vol=Json.ID_0x0180;\n"
                        "fe_hz=Json.ID_0x0181;\n"
                        "fe2_vol=Json.ID_0x019A;\n"
                        "fe3_vol=Json.ID_0x019B;\n"
                        "if(pr_vol!=fe_vol || pr_hz!=fe_hz || pr2_vol!=fe2_vol || pr3_vol!=fe3_vol){\n"
                            "$('ID_0x0180').value=(Json.ID_0x0180/10.0).toFixed(1);\n"
                            "$('ID_0x0181').value=(Json.ID_0x0181/100.0).toFixed(2);\n"
                            "$('ID_0x019A').value=(Json.ID_0x019A/10.0).toFixed(1);\n"
                            "$('ID_0x019B').value=(Json.ID_0x019B/10.0).toFixed(1);\n"
                        "}\n"
                        "show_tip_ex(4,'&nbsp;');\n"
                        "if(pr_vol!=fe_vol || pr_hz!=fe_hz || pr2_vol!=fe2_vol || pr3_vol!=fe3_vol){setTimeout('show_tip_ex(4,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(4,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(4,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x360)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "pr=$('ID_0x0360').value;\n"
                        "fe=Json.ID_0x0360;\n"
                        "if(pr!=fe)$('ID_0x0360').value=Json.ID_0x0360;\n"
                        "show_tip_ex(5,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(5,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(5,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(5,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x361)\n"
                    "{\n"
                        "var pr=0,fe=0,pr2=0,fe2=0;\n"
                        "pr=$('ID_0x0361').value;\n"
                        "pr2=$('ID_0x0362').value;\n"
                        "fe=Json.ID_0x0361;\n"
                        "fe2=Json.ID_0x0362;\n"
                        "if(pr!=fe || pr2!=fe2){\n"
                            "$('ID_0x0361').value=Json.ID_0x0361;\n"
                            "$('ID_0x0362').value=Json.ID_0x0362;\n"
                        "}\n"
                        "show_tip_ex(6,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(6,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(6,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(6,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',url,true);\n"
            "xmlhttp.send();  \n"
        "}\n"
"\n"
        "function doSubmit(obj)\n"
        "{\n"
            "var URL='a_024.html?';\n"
            "var readBack=0;\n"
"\n"
            "switch(obj.id)\n"
            "{\n"
                "case 'btn1':\n"
                    "URL=URL+'&0x0384='+$('ID_0x0384').value;\n"
                    "readBack=0x0384;\n"
                "break;\n"
                "case 'btn2':\n"
                    "var grid_mode;\n"
                    "if($('CC').checked){grid_mode=$('CC').value;}\n"
                    "if($('CV').checked){grid_mode=$('CV').value;}\n"
                    "if($('CP_DC').checked){grid_mode=$('CP_DC').value;}\n"
                    "if($('CP_AC').checked){grid_mode=$('CP_AC').value;}\n"
                    "if($('STANDBY').checked){grid_mode=$('STANDBY').value;}\n"
                    "URL=URL+'&0x0187='+grid_mode;\n"
                    "readBack=0x0187;\n"
                "break;\n"
                "case 'btn3':\n"
                    "var mode;\n"
                    "if($('LoRemo').checked){mode=$('LoRemo').value;}\n"
                    "if($('Remote').checked){mode=$('Remote').value;}\n"
                    "if($('Local').checked){mode=$('Local').value;}\n"
                    "URL=URL+'&0x0183='+mode;\n"
                    "readBack=0x0183;\n"
                "break;\n"
                "case 'btn4':\n"
                    "URL=URL+'&0x0180='+$('ID_0x0180').value*10;\n"
                    "URL=URL+'&0x0181='+$('ID_0x0181').value*100;\n"
                    "URL=URL+'&0x019A='+$('ID_0x019A').value*10;\n"
                    "URL=URL+'&0x019B='+$('ID_0x019B').value*10;\n"
                    "readBack=0x0180;                   \n"
                "break;\n"
                "case 'btn5':\n"
                    "URL=URL+'&0x0360='+$('ID_0x0360').value;\n"
                    "readBack=0x0360; \n"
                "break;\n"
                "case 'btn6':\n"
                    "URL=URL+'&0x0361='+$('ID_0x0361').value+'&0x0362='+$('ID_0x0362').value;\n"
                    "readBack=0x0361; \n"
                "break;\n"
            "}\n"
            "URL=URL+'&time='+Math.random();\n"
             //alert(URL);
"\n"
            "function success()\n"
            "{\n"
                "setTimeout('read_back('+readBack+')', 100);\n"
            "}            \n"
"\n"
             //测试
             //success();
            "\n"
            "sendHttpReq(URL,success);                                               \n"
        "}\n"
        "var err_mg=[0,0,0,0];\n"
        "function Verify(obj)\n"
        "{\n"
 		"var reg=/^-?[0-9][0-9]*$/;\n"
             //正整数、带1-2位小数的正浮点数
            "var reg2=/^((0(\\.\\d{1,2})?)|([1-9]\\d*(\\.\\d{1,2})?))$/;\n"
             //正整数、带一位小数的正浮点数
            "var reg3=/^((0(\\.\\d{1})?)|([1-9]\\d*(\\.\\d{1})?))$/;\n"
            "var range=parseInt(obj.value);\n"
            "var range2=parseFloat(obj.value);\n"
"\n"
            "switch(obj.id)\n"
            "{\n"
                "case 'ID_0x0384':\n"
                    "if(!obj.value.match(reg)){$('btn1').disabled=true;obj.style.color='#F00';show_tip_ex(1,lang.N501[language]);}\n"
                    "else if(range<0||range>29000){$('btn1').disabled=true;obj.style.color='#F00';show_tip_ex(1,lang.N502[language]);}\n"
                    "else{\n"
                        "obj.style.color='#000';\n"
                        "$('btn1').disabled=false;\n"
                        "show_tip_ex(1,'&nbsp;');\n"
                    "}\n"
                "break;\n"
                "case 'ID_0x0180':\n"
                    "if(!obj.value.match(reg3)){$('btn4').disabled=true;obj.style.color='#F00';show_tip_ex(4,lang.N501[language]);err_mg[0]=1;}\n"
                    "else if(range2<(Json.ID_0x0410/10.0).toFixed(1)||range2>(Json.ID_0x0411/10.0).toFixed(1)){$('btn4').disabled=true;obj.style.color='#F00';show_tip_ex(4,lang.N502[language]);err_mg[0]=1;}\n"
                    "else{\n"
                        "err_mg[0]=0;\n"
                        "obj.style.color='#000';\n"
                        "if((err_mg[0]|err_mg[1]|err_mg[2]|err_mg[3])==0){\n"
                            "$('btn4').disabled=false;\n"
                            "show_tip_ex(4,'&nbsp;');\n"
                        "}\n"
                    "}\n"
                "break;\n"
                "case 'ID_0x0181':\n"
                    "if(!obj.value.match(reg2)){$('btn4').disabled=true;obj.style.color='#F00';show_tip_ex(4,lang.N501[language]);err_mg[1]=1;}\n"
                    "else if(range2<(Json.ID_0x0412/100.0).toFixed(2)||range2>(Json.ID_0x0413/100.0).toFixed(2)){$('btn4').disabled=true;obj.style.color='#F00';show_tip_ex(4,lang.N502[language]);err_mg[1]=1;}\n"
                    "else{\n"
                        "err_mg[1]=0;\n"
                        "obj.style.color='#000';\n"
                        "if((err_mg[0]|err_mg[1]|err_mg[2]|err_mg[3])==0){\n"
                            "$('btn4').disabled=false;\n"
                            "show_tip_ex(4,'&nbsp;');\n"
                        "}\n"
                    "}\n"
                "break;\n"
                "case 'ID_0x019A':\n"
                    "if(!obj.value.match(reg3)){$('btn4').disabled=true;obj.style.color='#F00';show_tip_ex(4,lang.N501[language]);err_mg[2]=1;}\n"
                    "else if(range2<(Json.ID_0x0426/10.0).toFixed(1)||range2>(Json.ID_0x0427/10.0).toFixed(1)){$('btn4').disabled=true;obj.style.color='#F00';show_tip_ex(4,lang.N502[language]);err_mg[2]=1;}\n"
                    "else{\n"
                        "err_mg[2]=0;\n"
                        "obj.style.color='#000';\n"
                        "if((err_mg[0]|err_mg[1]|err_mg[2]|err_mg[3])==0){\n"
                            "$('btn4').disabled=false;\n"
                            "show_tip_ex(4,'&nbsp;');\n"
                        "}\n"
                    "}\n"
                "break;\n"
                "case 'ID_0x019B':\n"
                    "if(!obj.value.match(reg3)){$('btn4').disabled=true;obj.style.color='#F00';show_tip_ex(4,lang.N501[language]);err_mg[3]=1;}\n"
                    "else if(range2<(Json.ID_0x0428/10.0).toFixed(1)||range2>(Json.ID_0x0429/10.0).toFixed(1)){$('btn4').disabled=true;obj.style.color='#F00';show_tip_ex(4,lang.N502[language]);err_mg[3]=1;}\n"
                    "else{\n"
                        "err_mg[3]=0;\n"
                        "obj.style.color='#000';\n"
                        "if((err_mg[0]|err_mg[1]|err_mg[2]|err_mg[3])==0){\n"
                            "$('btn4').disabled=false;\n"
                            "show_tip_ex(4,'&nbsp;');\n"
                        "}\n"
                    "}\n"
                "break;  \n"
                "case 'ID_0x0360':\n"
                    "if(!obj.value.match(reg)){$('btn5').disabled=true;obj.style.color='#F00';show_tip_ex(5,lang.N501[language]);}\n"
                    "else if(range<0||range>30000){$('btn5').disabled=true;obj.style.color='#F00';show_tip_ex(5,lang.N502[language]);}\n"
                    "else{\n"
                        "obj.style.color='#000';\n"
                        "$('btn5').disabled=false;\n"
                        "show_tip_ex(5,'&nbsp;');\n"
                    "}\n"
                "break;     \n"
                "case 'ID_0x0361':\n"
                    "if(!obj.value.match(reg)){$('btn6').disabled=true;obj.style.color='#F00';show_tip_ex(6,lang.N501[language]);}\n"
                    "else if(range<5||range>2000){$('btn6').disabled=true;obj.style.color='#F00';show_tip_ex(6,lang.N502[language]);}\n"
                    "else{\n"
                        "obj.style.color='#000';\n"
                        "$('btn6').disabled=false;\n"
                        "show_tip_ex(6,'&nbsp;');\n"
                    "}\n"
                "break;    \n"
                "case 'ID_0x0362':\n"
                    "if(!obj.value.match(reg)){$('btn6').disabled=true;obj.style.color='#F00';show_tip_ex(6,lang.N501[language]);}\n"
                    "else if(range<1||range>50){$('btn6').disabled=true;obj.style.color='#F00';show_tip_ex(6,lang.N502[language]);}\n"
                    "else{\n"
                        "obj.style.color='#000';\n"
                        "$('btn6').disabled=false;\n"
                        "show_tip_ex(6,'&nbsp;');\n"
                    "}\n"
                "break;   \n"
            "}\n"
        "}\n"
    "</script>\n"
"</html>\n"
};
#endif
