#ifndef _HTML_H_025_H_
#define _HTML_H_025_H_

#if Web_RunTime_Debug==1
static const char h_025[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
 "<head>\n"
 	"<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>	\n"
 	"<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
        "<script type=\"text/javascript\" src=\"jquery.min.js\"></script>\n"
        "<script type=\"text/javascript\" src=\"j_highcharts.js\"></script>\n"
 "</head>\n"
 "<body onload='Init()'>\n"
 	"<div id=\"curver\" width='100%' style=\"height: 445px;min-width: 780px;\"></div>\n"
 "</body>\n"
 "<script type='text/javascript'>\n"
 	"window.history.forward(1);\n"
"\n"
 	"var language=1;\n"
 	"var Json;\n"
 	"var lang=\n"
 	"{\n"
 		"N01:['实时数据','RealTime Data'],\n"
"\n"
 			//下面由图表使用
 		"N02:['储能总有功功率(kW)','PCS Total Active Power(kW)'],\n"
 		"N03:['储能直流电压(V)','PCS DC Voltage(V)'],\n"
 		"N04:['储能交流电压(V)','PCS AC Voltage(V)'],\n"
 		"N05:['微网频率(Hz)','MGrid Freq(Hz)'],\n"
 		"N06:['光伏总有功功率','PV Total Active Power'],\n"
 		"N07:['光伏直流电压(V)','PV DC Voltage(V)'],\n"
 		"N08:['光伏交流电压(V)','PV AC Voltage(V)'],\n"
 		"N09:['负载功率(kW)','Load Power(kW)']\n"
 	"};		\n"
"\n"
        "var interval_time = 2000;\n"
        "var chart;\n"
         //超过1000个点时提示错误: error #12: www.highcharts.com/errors/12
         //解决方法： 1，设置 turboThreshold:0    2, 把传入的点的数据改为数组或者数列
        "var range = 300;\n"
      "\n"
        "function ConfigureChart()\n"
        "{\n"
            "Highcharts.setOptions({\n"
                "global: {\n"
                    "useUTC: false\n"
                "},\n"
                "chart:{\n"
                    "renderTo: 'curver'\n"
                     //'spline' 'line' 'area'
                     //type: 'spline',
                     //背景渐变
                     //backgroundColor: {
                     //    linearGradient: [0, 0, 500, 500],
                     //    stops: [
                     //        [0, 'rgb(230, 230, 230)'],
                     //        [1, 'rgb(180, 180, 180)']
                     //    ]
                     //}
                "},\n"
                "title: {\n"
                    "text: ''\n"
                "},\n"
                "xAxis: {\n"
                     //X轴标题
                    "title: {\n"
                        "text:'Range(10 min)'\n"
                    "}, \n"
                    "type: 'datetime',         \n"
                    "showFirstLable: true,\n"
                    "showLastLabel: true,   \n"
                    "lineWidth: 2,\n"
                    "lineColor: '#808080',\n"
                    "tickColor: '#e0e0e0',\n"
                    "tickPixelInterval: 150,\n"
                     //垂直网格粗细 
                     //gridLineWidth: 1,
                    "labels: {\n"
                        "formatter: function() {\n"
                            "return Highcharts.dateFormat('%H:%M:%S', this.value);\n"
                        "}\n"
                    "} \n"
                "},\n"
                "yAxis: {\n"
                     //Y轴标题
                    "title: {\n"
                        "text: ''\n"
                    "},\n"
                     //showEmpty: false,
                    "lineWidth: 2,\n"
                    "lineColor: '#808080',\n"
                    "gridLineColor: '#e0e0e0',\n"
                     //隔行显示颜色
                     //alternateGridColor: '#FDFFD5',
                     //网格线颜色
                    "gridLineColor: '#e0e0e0',\n"
                    "gridLineWidth: 1,\n"
                    "labels: {\n"
                        "formatter: function() {\n"
                            "return  this.value;\n"
                        "}\n"
                    "},\n"
                     //max: 500,
                     //min: -500,
                    "plotLines: [{\n"
                        "value: 0,\n"
                        "width: 1,\n"
                        "color: '#808080'\n"
                    "}]\n"
                "},\n"
                "plotOptions: {\n"
                      //针对图形类型的设置 'spline' 'line' 'area'
                     "spline: {\n"
                          "marker:{\n"
                                "enabled: false,\n"
                                "states: {\n"
                                "hover: {\n"
                                    "enabled: true,\n"
                                    "symbol: 'circle',\n"
                                    "radius: 2,\n"
                                    "lineWidth: 1\n"
                                "}\n"
                            "}\n"
                        "}\n"
                    "},\n"
                    "series: {\n"
                        "animation: false,\n"
                        "marker:{\n"
                            "enabled: false\n"
                        "},\n"
 	                    //set 0 to disable the cheack
 	                   "turboThreshold:0 \n"
                    "}\n"
                "},\n"
                "tooltip: {\n"
                    "formatter: function() {\n"
                            "return '<b><span style=\"color:'+this.series.color+'\">'+ this.series.name +'</span></b><br/>'+\n"
                            "Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.x) +'<br/>'+\n"
                            "Highcharts.numberFormat(this.y, 2);\n"
                    "}\n"
                "},\n"
                 //版本信息
                "credits: {\n"
                    "text: ''\n"
                "},\n"
                 //图例
                "legend: {\n"
                    "backgroundColor: '#FCFFC5',\n"
                    "borderColor: '#C98657',\n"
                    "borderWidth: 1,\n"
                    "layout: 'vertical',\n"
                     //layout: 'horizontal',
                    "itemDistance: 10,\n"
                    "backgroundColor: '#FFFFFF',\n"
                    "floating: true,\n"
                    "align: 'left',\n"
                    "verticalAlign: 'top',\n"
                    "x: 50,\n"
                    "y: 0,\n"
                    "labelFormatter: function () {\n"
                        "return this.name;\n"
                    "}\n"
                "}\n"
            "});\n"
        "}\n"
"\n"
        "function CreateChart()\n"
        "{\n"
            "chart = new Highcharts.Chart({\n"
                "chart: {\n"
                    "events: {\n"
                        "load: function() {\n"
                            "var series1 = this.series[0];\n"
                            "var series2 = this.series[1];\n"
                            "var series3 = this.series[2];\n"
                            "var series4 = this.series[3];\n"
                            "var series5 = this.series[4];\n"
                            "var series6 = this.series[5];\n"
                            "var series7 = this.series[6];\n"
                            "var series8 = this.series[7];\n"
                            "setInterval(function() {\n"
                                "var x = (new Date()).getTime();\n"
                                "var y1 = Json.ID_0x02A0;\n"
                                "var y2 = Json.ID_0x02A1;\n"
                                "var y3 = Json.ID_0x02A2;\n"
                                "var y4 = Json.ID_0x02A3;\n"
                                "var y5 = Json.ID_0x02A4;\n"
                                "var y6 = Json.ID_0x02A5;\n"
                                "var y7 = Json.ID_0x02A6;\n"
                                "var y8 = Json.ID_0x02A7;\n"
                                "var shift = series1.data.length > range;\n"
                                "series1.addPoint([x, y1], false, shift);\n"
                                "series2.addPoint([x, y2], false, shift);\n"
                                "series3.addPoint([x, y3], false, shift);\n"
                                "series4.addPoint([x, y4], false, shift);\n"
                                "series5.addPoint([x, y5], false, shift);\n"
                                "series6.addPoint([x, y6], false, shift);\n"
                                "series7.addPoint([x, y7], false, shift);\n"
                                "series8.addPoint([x, y8], false, shift);\n"
                                "chart.redraw();\n"
                            "}, interval_time);\n"
                        "}\n"
                    "}\n"
                "},\n"
                 //数据段
                "series: \n"
                "[\n"
                    "{\n"
                         //数据段1名称
                        "name: lang.N02[language],\n"
                         //数据段1初始化
                        "data: (function() {\n"
                            "var data = [],time = (new Date()).getTime(),i;\n"
                            "for (i = -range; i <= 0; i++) {\n"
                                "data.push({\n"
                                    "x: time + i * interval_time,\n"
                                    "y: 0\n"
                                "});\n"
                            "}\n"
                            "return data;\n"
                        "})()\n"
                    "},\n"
                    "{\n"
                         //数据段2名称
                        "name: lang.N03[language],\n"
                        "data: (function() {\n"
                            "var data = [],time = (new Date()).getTime(),i;\n"
                            "for (i = -range; i <= 0; i++) {\n"
                                "data.push({\n"
                                    "x: time + i * interval_time,\n"
                                    "y: 0\n"
                                "});\n"
                            "}\n"
                            "return data;\n"
                        "})()\n"
                    "},\n"
                    "{\n"
                         //数据段3名称
                        "name: lang.N04[language],\n"
                        "data: (function() {\n"
                            "var data = [],time = (new Date()).getTime(),i;\n"
                            "for (i = -range; i <= 0; i++) {\n"
                                "data.push({\n"
                                    "x: time + i * interval_time,\n"
                                    "y: 0\n"
                                "});\n"
                            "}\n"
                            "return data;\n"
                        "})()\n"
                    "},\n"
                    "{\n"
                         //数据段4名称
                        "name: lang.N05[language],\n"
                        "data: (function() {\n"
                            "var data = [],time = (new Date()).getTime(),i;\n"
                            "for (i = -range; i <= 0; i++) {\n"
                                "data.push({\n"
                                    "x: time + i * interval_time,\n"
                                    "y: 0\n"
                                "});\n"
                            "}\n"
                            "return data;\n"
                        "})()\n"
                    "},\n"
                    "{\n"
                         //数据段5名称
                        "name: lang.N06[language],\n"
                        "data: (function() {\n"
                            "var data = [],time = (new Date()).getTime(),i;\n"
                            "for (i = -range; i <= 0; i++) {\n"
                                "data.push({\n"
                                    "x: time + i * interval_time,\n"
                                    "y: 0\n"
                                "});\n"
                            "}\n"
                            "return data;\n"
                        "})()\n"
                    "},\n"
                    "{\n"
                         //数据段6名称
                        "name: lang.N07[language],\n"
                        "data: (function() {\n"
                            "var data = [],time = (new Date()).getTime(),i;\n"
                            "for (i = -range; i <= 0; i++) {\n"
                                "data.push({\n"
                                    "x: time + i * interval_time,\n"
                                    "y: 0\n"
                                "});\n"
                            "}\n"
                            "return data;\n"
                        "})()\n"
                    "},\n"
                    "{\n"
                         //数据段7名称
                        "name: lang.N08[language],\n"
                        "data: (function() {\n"
                            "var data = [],time = (new Date()).getTime(),i;\n"
                            "for (i = -range; i <= 0; i++) {\n"
                                "data.push({\n"
                                    "x: time + i * interval_time,\n"
                                    "y: 0\n"
                                "});\n"
                            "}\n"
                            "return data;\n"
                        "})()\n"
                    "},\n"
                    "{\n"
                         //数据段8名称
                        "name: lang.N09[language],\n"
                        "data: (function() {\n"
                            "var data = [],time = (new Date()).getTime(),i;\n"
                            "for (i = -range; i <= 0; i++) {\n"
                                "data.push({\n"
                                    "x: time + i * interval_time,\n"
                                    "y: 0\n"
                                "});\n"
                            "}\n"
                            "return data;\n"
                        "})()\n"
                    "}\n"
                "]\n"
            "});              \n"
        "}\n"
 	"function Init()\n"
 	"{\n"
 		"var URL='s_025.html?time='+new Date();\n"
 	       "var xmlhttp;\n"
 	       "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 	       "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 	       "xmlhttp.onreadystatechange=function()\n"
 	       "{\n"
 	           "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 	           "{\n"
 				"eval('Json='+xmlhttp.responseText);\n"
 				"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
 		           "ConfigureChart();\n"
 		           "CreateChart();\n"
"\n"
 		           "setInterval('update()', 2000);\n"
 	           "}\n"
 	       "};\n"
 	       "xmlhttp.open('GET',URL,true);\n"
 	       "xmlhttp.send();\n"
 	"}	\n"
 	"function update() \n"
 	"{		\n"
 		"var URL='s_025.html?time='+new Date();\n"
 	       "var xmlhttp;\n"
 	       "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 	       "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 	       "xmlhttp.onreadystatechange=function()\n"
 	       "{\n"
 	           "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 	           "{\n"
 		           "eval('Json='+xmlhttp.responseText);          	\n"
 	           "}\n"
 	       "};\n"
 	       "xmlhttp.open('GET',URL,true);\n"
 	       "xmlhttp.send();\n"
 	"}\n"
 "</script>\n"
"</html>\n"
};
#else
static const char h_025[] = {0};
#endif

#endif
