#ifndef _HTML_H_020_H_
#define _HTML_H_020_H_
static const char h_020[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
"<head>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<title></title>\n"
        "<script type='text/javascript'>\n"
            "window.history.forward(1);\n"
            "var Json;\n"
            "setInterval('feed()',5000);\n"
            "function Init()\n"
            "{\n"
                 //测试
                 //Json={ID_0x0202:'EMS100-1000K',ID_0x0301:85}; 
"\n"
                "var URL='s_020.html?'+'time='+Math.random();\n"
                "var xmlhttp;\n"
                "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                "xmlhttp.onreadystatechange=function()\n"
                "{\n"
                    "if(xmlhttp.readyState==4&&xmlhttp.status==200)\n"
                    "{\n"
                        "eval('Json='+xmlhttp.responseText);\n"
                        "document.title=Json.ID_0x0202;\n"
                    "}\n"
                "};\n"
                "xmlhttp.open('GET',URL,true);\n"
                "xmlhttp.send();\n"
            "}\n"
"\n"
             //定时发送心跳包
            "function feed()\n"
            "{\n"
                "var URL='Feed.html?'+'time='+Math.random();\n"
                "var xmlhttp;\n"
                "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                "xmlhttp.onreadystatechange=function()\n"
                "{\n"
                    "if(xmlhttp.readyState==4&&xmlhttp.status==200)\n"
                    "{\n"
                        "if(xmlhttp.responseText=='1')\n"
                        "{\n"
                            "parent.document.location.href='Login.html';\n"
                        "}\n"
 				"}\n"
                "};\n"
                "xmlhttp.open('GET',URL,true);\n"
                "xmlhttp.send();\n"
            "}\n"
        "</script>\n"
    "</head>\n"
        "<frameset rows='89,*' cols='*' border='0' onload='Init()'>\n"
            "<!-- 需要将h_012.html和h_021.html改成h_012.aspx和h_021.aspx的框架调用方式 -->\n"
            "<frame noresize='noresize' src='h_047.aspx' name='logo' id='logo'>\n"
            "<frameset rows='*' cols='250,*' border='0'>\n"
                "<frame noresize='noresize' src='h_021.aspx' name='menu' id='menu'>\n"
                "<frame noresize='noresize' name='main' id='main'>\n"
         "</frameset>\n"
        "</frameset>\n"
        "<noframes>\n"
        "</noframes>)\n"
"</html>\n"
};
#endif
