#ifndef _HTML_H_022_H_
#define _HTML_H_022_H_
static const char h_022[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
 "<head>\n"
 	"<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
 	"<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
 	"<script type='text/javascript'>\n"
            "var $=function(o){return document.getElementById(o);};\n"
            "function lang_init_ex(st,end){for(var i=st;i<=end;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
            "function show_tip_ex(id, obj){eval('$(\\'tip'+id+'\\').innerHTML=obj;');}\n"
            "function show_T(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
                "str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_sT(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_sT_ex(tid, id)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' id='\"+id+\"' style='display:none;width:90%'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function sendHttpReq(url, successFn)\n"
            "{\n"
                 //alert(url);   
                "var xmlhttp;\n"
                "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                "xmlhttp.onreadystatechange=function()\n"
                "{\n"
                    "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                    "{\n"
                        "if(xmlhttp.responseText=='1'){successFn();}\n"
                    "}\n"
                "};\n"
                "xmlhttp.open('GET',url,true);\n"
                "xmlhttp.send();\n"
            "}\n"
        "</script>\n"
 	"<style type='text/css'>\n"
 		"tr{height:27px;}\n"
 		".td1{padding-left:40px;text-align:left;}\n"
 		".td2{text-align:left;}\n"
 		".td3{padding-right:40px;text-align:right;}\n"
 		".txt{width:50px;text-align:right;}\n"
 	"</style>\n"
 "</head>\n"
 "<body onload='Init()'>\n"
 	"<script type='text/javascript'>\n"
 		"show_T('N01');\n"
 	"</script>\n"
        "<!-- 储能逆变器型号设置 -->\n"
        "<script type='text/javascript'>\n"
            "show_sT('N14');\n"
        "</script>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
              "<td width='30%' class='td1 odd'><input name='PCS-Type' type='radio' value='0' id='SC30-50'/><span id='N15'></span></td>\n"
              "<td width='30%' class='td1 odd'><input name='PCS-Type' type='radio' value='1' id='SC100'/><span id='N16'></span></td>\n"
              "<td width='30%' class='td1 odd'><input name='PCS-Type' type='radio' value='2' id='SC250'/><span id='N17'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
              "<td width='30%' class='td1 even'><input name='PCS-Type' type='radio' value='3' id='SC500'/><span id='N18'></span></td>\n"
              "<td width='30%' class='td1 even'><input name='PCS-Type' type='radio' value='4' id='SC500TL'/><span id='N19'></span></td>\n"
              "<td width='30%' class='td1 even'><input name='PCS-Type' type='radio' value='5' id='SC1000'/><span id='N20'></span></td>\n"
            "</tr>           \n"
        "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip5'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn5' style='display:block;'><span id='N404'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N02');\n"
        "</script>\n"
 	"<!-- 协议选择 -->\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='30%' class='td1 odd'><input name='Protocol-Sel' type='radio' value='0' id='NewProtocol'/><span id='N03'></span></td>\n"
 			"<td width='30%' class='td1 odd'><input name='Protocol-Sel' type='radio' value='1' id='OldProtocol'/><span id='N04'></span></td>\n"
 		"</tr>\n"
 	  "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip1'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn1' style='display:block;'><span id='N400'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
 	"<div class='line_long'></div>\n"
 	"<div class='blank'></div>\n"
 	"<!-- 总线类型 -->\n"
 	"<script type='text/javascript'>\n"
 		"show_sT('N05');\n"
 	"</script>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='30%' class='td1 odd'><input name='BusType' type='radio' value='1' id='AC-Bus'/><span id='N07'></span></td>\n"
 			"<td width='30%' class='td1 odd'><input name='BusType' type='radio' value='0' id='DC-Bus'/><span id='N06'></span></td>\n"
 		"</tr>\n"
 	  "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip2'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn2' style='display:block;'><span id='N401'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
 	"<div class='line_long'></div>\n"
 	"<div class='blank'></div>\n"
 	"<!-- 并网类型 -->\n"
 	"<script type='text/javascript'>\n"
 		"show_sT('N08');\n"
 	"</script>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='30%' class='td1 odd'><input name='GridConected' type='radio' value='0' id='GC-NO'/><span id='N09'></span></td>\n"
 			"<td width='30%' class='td1 odd'><input name='GridConected' type='radio' value='1' id='GC-YES'/><span id='N10'></span></td>\n"
 		"</tr>\n"
 	"</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip3'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn3' style='display:block;'><span id='N402'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
 	"<div class='line_long'></div>\n"
 	"<div class='blank'></div>\n"
 	"<!-- 直流母线充电使能 -->		\n"
 	"<script type='text/javascript'>\n"
 		"show_sT('N11');\n"
 	"</script>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='30%' class='td1 odd'><input name='ChargePermit' type='radio' value='0' id='CP-DIS'/><span id='N12'></span></td>\n"
 			"<td width='30%' class='td1 odd'><input name='ChargePermit' type='radio' value='1' id='CP-EN'/><span id='N13'></span></td>\n"
 		"</tr>\n"
 	"</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip4'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn4' style='display:block;'><span id='N403'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
 	"<div class='line_long'></div>\n"
 	"<div class='blank'></div>\n"
 	"<div id='trans'></div>\n"
 	"<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
 "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var language=0;\n"
        "var Json;\n"
         //需要将'\\'转换为'\\\\'
         //正整数、带一位小数的正浮点数
        "var reg1=/^[1-9]\\d*$/;	\n"
         //正负整数、带1位小数的正负浮点数
        "var reg4=/^((-?0(\\.\\d{1})?)|(-?[1-9]\\d*(\\.\\d{1})?))$/;	 \n"
        "var lang=\n"
        "{\n"
            "N01:['基本设置','System-Config'],\n"
            "N02:['协议选择','Protocol-Sel'],\n"
 		"N03:['新协议','New-Protocol'],\n"
 		"N04:['旧协议','Old-Protocol'],\n"
 		"N05:['母线类型','BusType'],\n"
 		"N06:['直流母线','DC-Bus'],\n"
 		"N07:['交流母线','AC-Bus'],\n"
 		"N08:['是否并网','Grid Connected'],\n"
 		"N09:['非并网','No'],\n"
 		"N10:['并网','Yes'],\n"
 		"N11:['直流母线充电使能','DC Bus Charge Permit'],\n"
 		"N12:['禁止','DISABLE'],\n"
 		"N13:['允许','ENABLE'],\n"
"\n"
 		"N14:['储能逆变器型号','PCS Type'],\n"
            "N15:['SC50','SC50'],\n"
            "N16:['SC100','SC100'],\n"
            "N17:['SC250','SC250'],\n"
            "N18:['SC500','SC500'],\n"
            "N19:['SC500TL','SC500TL'],\n"
            "N20:['SC1000','SC1000'],\n"
            "N21:['优先级选择','Priority-Sel'],\n"
            "N22:['电网优先','Gird-First'],\n"
            "N23:['微网优先','Micro-Grid First'],\n"
"\n"
            "N400:['设&nbsp;&nbsp;置','Set'], \n"
            "N401:['设&nbsp;&nbsp;置','Set'], \n"
            "N402:['设&nbsp;&nbsp;置','Set'], \n"
            "N403:['设&nbsp;&nbsp;置','Set'], \n"
            "N404:['设&nbsp;&nbsp;置','Set'], \n"
            "N405:['设&nbsp;&nbsp;置','Set'],  	          \n"
"\n"
            "N499:['设置成功！','Set successfully!'],\n"
            "N500:['设置失败！','Set Failed!'],\n"
            "N501:['格式错误！','Format error!'],\n"
            "N502:['范围错误！','Range error!']    \n"
        "};\n"
        "function Init()\n"
        "{\n"
            "var URL='s_022.html?time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{              \n"
                    "eval('Json='+xmlhttp.responseText);				\n"
"\n"
     			"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                     //初始化语言
                    "lang_init_ex(1,13); \n"
     			"lang_init_ex(14,20);  \n"
     			"lang_init_ex(400,404);       \n"
     			"doSetValue(Json);\n"
"\n"
     				//user用户不能配置，install用户可以配置
     			"if(Json.ID_0x0282==0x11)\n"
     			"{\n"
     				"$('btn1').style.display='none';\n"
     				"$('trans').style.zIndex=9999;\n"
     			"}\n"
     			"else\n"
     			"{\n"
     				"$('btn1').style.display='inline';\n"
     				"$('trans').style.zIndex=-9999;\n"
     			"}\n"
 			    "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}\n"
        "function read_back(addr)\n"
        "{\n"
            "var url='s_022.html?';\n"
            "url=url+'&time='+Math.random();\n"
"\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText); \n"
                    "if(addr == 0x0380)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('NewProtocol').checked){pr=$('NewProtocol').value;}\n"
                        "else if($('OldProtocol').checked){pr=$('OldProtocol').value;} \n"
                        "fe=Json.ID_0x0380;\n"
                        "if(pr!=fe)\n"
                        "{\n"
                            "if(Json.ID_0x0380==0)\n"
                            "{\n"
                                "$('NewProtocol').checked=true;\n"
                                "$('OldProtocol').checked=false;\n"
                            "}\n"
                            "else\n"
                            "{\n"
                                "$('NewProtocol').checked=false;\n"
                                "$('OldProtocol').checked=true;              \n"
                            "}\n"
                        "}\n"
                        "show_tip_ex(1,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(1,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(1,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(1,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x0381)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('AC-Bus').checked){pr=$('AC-Bus').value;} \n"
                        "else if($('DC-Bus').checked){pr=$('DC-Bus').value;}\n"
                        "fe=Json.ID_0x0381;\n"
                        "if(pr!=fe)\n"
                        "{\n"
                            "if(Json.ID_0x0381==1)\n"
                            "{\n"
                                "$('AC-Bus').checked=true;\n"
                                "$('DC-Bus').checked=false;\n"
                            "}\n"
                            "else\n"
                            "{\n"
                                "$('AC-Bus').checked=false;\n"
                                "$('DC-Bus').checked=true;               \n"
                            "}\n"
                        "}\n"
                        "show_tip_ex(2,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(2,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(2,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(2,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x0382)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('GC-NO').checked){pr=$('GC-NO').value;}  \n"
                        "else if($('GC-YES').checked){pr=$('GC-YES').value;} \n"
                        "fe=Json.ID_0x0382;\n"
                        "if(pr!=fe)\n"
                        "{\n"
                            "if(Json.ID_0x0382==0)\n"
                            "{\n"
                                "$('GC-NO').checked=true;\n"
                                "$('GC-YES').checked=false;\n"
                            "}\n"
                            "else\n"
                            "{\n"
                                "$('GC-NO').checked=false;\n"
                                "$('GC-YES').checked=true;               \n"
                            "}\n"
                        "}\n"
                        "show_tip_ex(3,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(3,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(3,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(3,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x0383)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('CP-DIS').checked){pr=$('CP-DIS').value;}  \n"
                        "else if($('CP-EN').checked){pr=$('CP-EN').value;}\n"
                        "fe=Json.ID_0x0383;\n"
                        "if(pr!=fe)\n"
                        "{\n"
                            "if(Json.ID_0x0383==0)\n"
                            "{\n"
                                "$('CP-DIS').checked=true;\n"
                                "$('CP-EN').checked=false;\n"
                            "}\n"
                            "else\n"
                            "{\n"
                                "$('CP-DIS').checked=false;\n"
                                "$('CP-EN').checked=true;            \n"
                            "}\n"
                        "}\n"
                        "show_tip_ex(4,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(4,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(4,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(4,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x0385)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('SC30-50').checked){pr=$('SC30-50').value;}   \n"
                        "else if($('SC100').checked){pr=$('SC100').value;}\n"
                        "else if($('SC250').checked){pr=$('SC250').value;}  \n"
                        "else if($('SC500').checked){pr=$('SC500').value;}  \n"
                        "else if($('SC500TL').checked){pr=$('SC500TL').value;}\n"
                        "else if($('SC1000').checked){pr=$('SC1000').value;}\n"
                        "fe=Json.ID_0x0385;\n"
                        "if(pr!=fe)\n"
                        "{\n"
                            "if(Json.ID_0x0385==0)\n"
                            "{\n"
                                "$('SC30-50').checked=true;\n"
                                "$('SC100').checked=false;\n"
                                "$('SC250').checked=false;\n"
                                "$('SC500').checked=false;\n"
                                "$('SC500TL').checked=false;\n"
                                "$('SC1000').checked=false;\n"
                            "}\n"
                            "else if(Json.ID_0x0385==1)\n"
                            "{\n"
                                "$('SC30-50').checked=false;\n"
                                "$('SC100').checked=true;\n"
                                "$('SC250').checked=false;\n"
                                "$('SC500').checked=false;\n"
                                "$('SC500TL').checked=false; \n"
                                "$('SC1000').checked=false;        \n"
                            "}\n"
                            "else if(Json.ID_0x0385==2)\n"
                            "{\n"
                                "$('SC30-50').checked=false;\n"
                                "$('SC100').checked=false;\n"
                                "$('SC250').checked=true;\n"
                                "$('SC500').checked=false;\n"
                                "$('SC500TL').checked=false;  \n"
                                "$('SC1000').checked=false;   \n"
                            "}\n"
                            "else if(Json.ID_0x0385==3)\n"
                            "{\n"
                                "$('SC30-50').checked=false;\n"
                                "$('SC100').checked=false;\n"
                                "$('SC250').checked=false;\n"
                                "$('SC500').checked=true;\n"
                                "$('SC500TL').checked=false;\n"
                                "$('SC1000').checked=false;\n"
                            "}\n"
                            "else if(Json.ID_0x0385==4)\n"
                            "{\n"
                                "$('SC30-50').checked=false;\n"
                                "$('SC100').checked=false;\n"
                                "$('SC250').checked=false;\n"
                                "$('SC500').checked=false;\n"
                                "$('SC500TL').checked=true;\n"
                                "$('SC1000').checked=false;\n"
                            "}\n"
                            "else if(Json.ID_0x0385==5)\n"
                            "{\n"
                                "$('SC30-50').checked=false;\n"
                                "$('SC100').checked=false;\n"
                                "$('SC250').checked=false;\n"
                                "$('SC500').checked=false;\n"
                                "$('SC500TL').checked=false;\n"
                                "$('SC1000').checked=true;                                \n"
                            "}\n"
                        "}\n"
                        "show_tip_ex(5,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(5,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(5,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(5,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',url,true);\n"
            "xmlhttp.send();  \n"
        "}\n"
        "function doSubmit(obj)\n"
        "{\n"
            "var Protocol,BusType,Grid,DBusCharge,SC_Type,DCDC_Type,Priority,VSG,MacLock;\n"
            "var URL='a_022.html?';\n"
            "switch(obj.id)\n"
            "{\n"
             "case 'btn1': \n"
             	 "if($('NewProtocol').checked){Protocol=$('NewProtocol').value;}\n"
             	 "else if($('OldProtocol').checked){Protocol=$('OldProtocol').value;} \n"
 				"URL=URL+'&0x0380='+Protocol;\n"
                    "readBack=0x0380;\n"
             "break;\n"
             "case 'btn2':\n"
      			"if($('AC-Bus').checked){BusType=$('AC-Bus').value;}	\n"
 				"else if($('DC-Bus').checked){BusType=$('DC-Bus').value;}\n"
 				"URL=URL+'&0x0381='+BusType;\n"
                    "readBack=0x0381;\n"
             "break;\n"
             "case 'btn3': \n"
        			"if($('GC-NO').checked){Grid=$('GC-NO').value;}	\n"
 				"else if($('GC-YES').checked){Grid=$('GC-YES').value;} \n"
 				"URL=URL+'&0x0382='+Grid;\n"
                    "readBack=0x0382;\n"
             "break;\n"
             "case 'btn4': \n"
  				"if($('CP-DIS').checked){DBusCharge=$('CP-DIS').value;}	\n"
 				"else if($('CP-EN').checked){DBusCharge=$('CP-EN').value;}\n"
             	"URL=URL+'&0x0383='+DBusCharge;\n"
                    "readBack=0x0383;\n"
             "break;\n"
             "case 'btn5': \n"
 			 	"if($('SC30-50').checked){SC_Type=$('SC30-50').value;}	\n"
 				"else if($('SC100').checked){SC_Type=$('SC100').value;}\n"
 				"else if($('SC250').checked){SC_Type=$('SC250').value;}	\n"
 				"else if($('SC500').checked){SC_Type=$('SC500').value;}	\n"
 				"else if($('SC500TL').checked){SC_Type=$('SC500TL').value;}\n"
                    "else if($('SC1000').checked){SC_Type=$('SC1000').value;}\n"
 				"URL=URL+'&0x0385='+SC_Type;\n"
                    "readBack=0x0385;\n"
             "break;\n"
             "default:break;\n"
            "}\n"
            "URL=URL+'&time='+Math.random();\n"
             //alert(URL);
"\n"
            "function success()\n"
            "{\n"
                "setTimeout('read_back('+readBack+')', 100);            			\n"
            "}\n"
             //测试
             //success();            
 		"sendHttpReq(URL, success);\n"
        "}\n"
        "function doSetValue(Json)\n"
        "{\n"
         	//协议选择
         "if(Json.ID_0x0380==0)\n"
         "{\n"
         	"$('NewProtocol').checked=true;\n"
         	"$('OldProtocol').checked=false;\n"
         "}\n"
         "else\n"
         "{\n"
          	"$('NewProtocol').checked=false;\n"
         	"$('OldProtocol').checked=true;       		\n"
         "}\n"
         	//母线类型
         "if(Json.ID_0x0381==1)\n"
         "{\n"
         	"$('AC-Bus').checked=true;\n"
         	"$('DC-Bus').checked=false;\n"
         "}\n"
         "else\n"
         "{\n"
          	"$('AC-Bus').checked=false;\n"
         	"$('DC-Bus').checked=true;       		\n"
         "}\n"
         	//是否并网
         "if(Json.ID_0x0382==0)\n"
         "{\n"
         	"$('GC-NO').checked=true;\n"
         	"$('GC-YES').checked=false;\n"
         "}\n"
         "else\n"
         "{\n"
          	"$('GC-NO').checked=false;\n"
         	"$('GC-YES').checked=true;       		\n"
         "}\n"
         	//直流母线充电使能
         "if(Json.ID_0x0383==0)\n"
         "{\n"
         	"$('CP-DIS').checked=true;\n"
         	"$('CP-EN').checked=false;\n"
         "}\n"
         "else\n"
         "{\n"
          	"$('CP-DIS').checked=false;\n"
         	"$('CP-EN').checked=true;       		\n"
         "}\n"
         	//储能逆变器型号
         "if(Json.ID_0x0385==0)\n"
         "{\n"
         	"$('SC30-50').checked=true;\n"
         	"$('SC100').checked=false;\n"
         	"$('SC250').checked=false;\n"
         	"$('SC500').checked=false;\n"
         	"$('SC500TL').checked=false;\n"
                "$('SC1000').checked=false;\n"
         "}\n"
         "else if(Json.ID_0x0385==1)\n"
         "{\n"
          	"$('SC30-50').checked=false;\n"
         	"$('SC100').checked=true;\n"
         	"$('SC250').checked=false;\n"
         	"$('SC500').checked=false;\n"
         	"$('SC500TL').checked=false;\n"
                "$('SC1000').checked=false;  		\n"
         "}\n"
         "else if(Json.ID_0x0385==2)\n"
         "{\n"
            	"$('SC30-50').checked=false;\n"
         	"$('SC100').checked=false;\n"
         	"$('SC250').checked=true;\n"
         	"$('SC500').checked=false;\n"
         	"$('SC500TL').checked=false;	\n"
                "$('SC1000').checked=false;	\n"
         "}\n"
         "else if(Json.ID_0x0385==3)\n"
         "{\n"
    		       "$('SC30-50').checked=false;\n"
         	"$('SC100').checked=false;\n"
         	"$('SC250').checked=false;\n"
         	"$('SC500').checked=true;\n"
         	"$('SC500TL').checked=false;\n"
                "$('SC1000').checked=false;\n"
         "}\n"
         "else if(Json.ID_0x0385==4)\n"
         "{\n"
    		       "$('SC30-50').checked=false;\n"
         	"$('SC100').checked=false;\n"
         	"$('SC250').checked=false;\n"
         	"$('SC500').checked=false;\n"
         	"$('SC500TL').checked=true;\n"
                "$('SC1000').checked=false;\n"
         "}\n"
            "else if(Json.ID_0x0385==5)\n"
            "{\n"
                "$('SC30-50').checked=false;\n"
                "$('SC100').checked=false;\n"
                "$('SC250').checked=false;\n"
                "$('SC500').checked=false;\n"
                "$('SC500TL').checked=false;\n"
                "$('SC1000').checked=true;\n"
            "}\n"
        "}\n"
    "</script>\n"
"</html>\n"
};
#endif
