#ifndef _HTML_H_028_H_
#define _HTML_H_028_H_
static const char h_028[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
 "<head>\n"
 	"<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
 	"<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
 	"<script type='text/javascript'>\n"
 		"var $=function(o){return document.getElementById(o);};\n"
 		"function lang_init_ex(st,end){for(var i=st;i<=end;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
 		"function show_tip(obj){$('tip').innerHTML=obj;}\n"
 		"function show_T(tid)\n"
 		"{\n"
 			"var str='';\n"
 			"str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
 			"str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
 			"str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
 			"document.write(str);\n"
 		"}\n"
 		"function show_sT(tid)\n"
 		"{\n"
 			"var str='';\n"
 			"str+=\"<div class='title' style='width:90%;'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
 			"str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
 			"str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
 			"document.write(str);\n"
 		"}\n"
 		"function show_sT_ex(tid, id)\n"
 		"{\n"
 			"var str='';\n"
 			"str+=\"<div class='title' id='\"+id+\"' style='display:none;width:90%'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
 			"str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
 			"str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
 			"document.write(str);\n"
 		"}\n"
 		"function sendHttpReq(url, successFn)\n"
 		"{\n"
 				//alert(url);	
 		       "var xmlhttp;\n"
 		       "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		       "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		       "xmlhttp.onreadystatechange=function()\n"
 		       "{\n"
 		           "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 		           "{\n"
 		               "if(xmlhttp.responseText=='1'){successFn();}\n"
 		           "}\n"
 		       "};\n"
 		       "xmlhttp.open('GET',url,true);\n"
 		       "xmlhttp.send();\n"
 		"}\n"
 	"</script>\n"
 	"<style type='text/css'>\n"
 		"tr{height:27px;}\n"
 		".select{width:180px;_width:150px;}\n"
 		".time{width:65px;_width:100px;}\n"
 		".txt{width:100px;text-align:center;}\n"
 		".short_txt{width:50px;}\n"
 		".td_value{text-align:right;padding-right:20px;}\n"
 		".td1{padding-left:40px;text-align:left;}\n"
 		".td2{padding-left:0px;text-align:left;}\n"
 		".td3{padding-left:60px;text-align:left;}\n"
 		".td4{padding-right:10px;text-align:right;}\n"
 		".td5{padding-right:10px;text-align:right;}\n"
 		".radio{padding-left:30px;}\n"
 		".btnStyle{width:80px;height:24px;text-align:right;}\n"
 	"</style>\n"
 "</head>\n"
 "<body onload='Init()'>\n"
 	"<script type='text/javascript'>\n"
 		"show_T('N01');\n"
 	"</script>\n"
 	"<!-- SOC参数 -->\n"
 	"<script type='text/javascript'>\n"
 		"show_sT('N02');\n"
 	"</script>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='350' class='td1 odd'><input name='SOC-PARAM' type='radio' value='85' id='SOC-DIS'/><span id='N03'></span></td>\n"
 			"<td width='28%' class='td1 odd'><input name='SOC-PARAM' type='radio' value='170' id='SOC-EN'/><span id='N04'></span></td>\n"
 			"<!-- 保存 -->\n"
 			  "<td width='35%' align='right' class='odd'><button class='btn' onclick='doSubmit(this)' id='N500' style='display:block;'></button></td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<div class='tip' id='tip' style='width:90%;'><span>&nbsp;</span></div>\n"
 	"<table id='tab_soc' width='90%' border='0' style='display:none;'>\n"
 		"<tr>\n"
 			"<!-- SOC 上限2级 -->\n"
 			"<td width='350' class='td1 odd'><span id='N05'></span></td>\n"
 			"<td width='26%' class='td4 odd'><input class='txt' id='ID_0x0601' maxlength='6' onkeyup='Verify(this)' type='text'/>%</td>\n"
 			"<td width='26%' class='td2 odd'>(<span id='ID_0x0440'></span>~<span id='ID_0x0441'></span>)</td>\n"
 			"<td width='28%' align='right' class='odd'><button class='btn' onclick='doSubmit(this)' id='N501' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<!-- SOC 上限1级 -->\n"
 			"<td width='350' class='td1 even'><span id='N06'></span></td>\n"
 			"<td width='26%' class='td4 even'><input class='txt' id='ID_0x0602' maxlength='6' onkeyup='Verify(this)' type='text'/>%</td>\n"
 			"<td width='26%' class='td2 even'>(<span id='ID_0x0442'></span>~<span id='ID_0x0443'></span>)</td>\n"
 			"<td width='28%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='N502' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<!-- SOC 下限1级 -->\n"
 			"<td width='350' class='td1 odd'><span id='N07'></span></td>\n"
 			"<td width='26%' class='td4 odd'><input class='txt' id='ID_0x0603' maxlength='6' onkeyup='Verify(this)' type='text'/>%</td>\n"
 			"<td width='26%' class='td2 odd'>(<span id='ID_0x0444'></span>~<span id='ID_0x0445'></span>)</td>\n"
 			"<td width='28%' align='right' class='odd'><button class='btn' onclick='doSubmit(this)' id='N503' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<!-- SOC 下限2级 -->\n"
 			"<td width='350' class='td1 even'><span id='N08'></span></td>\n"
 			"<td width='26%' class='td4 even'><input class='txt' id='ID_0x0604' maxlength='6' onkeyup='Verify(this)' type='text'/>%</td>\n"
 			"<td width='26%' class='td2 even'>(<span id='ID_0x0446'></span>~<span id='ID_0x0447'></span>)</td>\n"
 			"<td width='28%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='N504' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr style=\"display:none;\">\n"
 			"<!-- SOC 上限2级恢复 -->\n"
 			"<td width='350' class='td1 odd'><span id='N09'></span></td>\n"
 			"<td width='26%' class='td4 odd'><input class='txt' id='ID_0x0605' maxlength='6' onkeyup='Verify(this)' type='text'/>%</td>\n"
 			"<td width='26%' class='td2 odd'>(<span id='ID_0x0448'></span>~<span id='ID_0x0449'></span>)</td>\n"
 			"<td width='28%' align='right' class='odd'><button class='btn' onclick='doSubmit(this)' id='N505' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr style=\"display:none;\">\n"
 			"<!-- SOC 上限1级恢复 -->\n"
 			"<td width='255' class='td1 even'><span id='N10'></span></td>\n"
 			"<td width='26%' class='td4 even'><input class='txt' id='ID_0x0606' maxlength='6' onkeyup='Verify(this)' type='text'/>%</td>\n"
 			"<td width='26%' class='td2 even'>(<span id='ID_0x044A'></span>~<span id='ID_0x044B'></span>)</td>\n"
 			"<td width='28%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='N506' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<!-- SOC 下限1级恢复 -->\n"
 			"<td width='350' class='td1 odd'><span id='N11'></span></td>\n"
 			"<td width='26%' class='td4 odd'><input class='txt' id='ID_0x0607' maxlength='6' onkeyup='Verify(this)' type='text'/>%</td>\n"
 			"<td width='26%' class='td2 odd'>(<span id='ID_0x044C'></span>~<span id='ID_0x044D'></span>)</td>\n"
 			"<td width='28%' align='right' class='odd'><button class='btn' onclick='doSubmit(this)' id='N507' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<!-- SOC 下限2级恢复 -->\n"
 			"<td width='255' class='td1 even'><span id='N12'></span></td>\n"
 			"<td width='26%' class='td4 even'><input class='txt' id='ID_0x0608' maxlength='6' onkeyup='Verify(this)' type='text'/>%</td>\n"
 			"<td width='26%' class='td2 even'>(<span id='ID_0x044E'></span>~<span id='ID_0x044F'></span>)</td>\n"
 			"<td width='28%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='N508' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<!-- SOC 滞环控制值 -->\n"
 			"<td width='350' class='td1 odd'><span id='N13'></span></td>\n"
 			"<td width='26%' class='td4 odd'><input class='txt' id='ID_0x0609' maxlength='6' onkeyup='Verify(this)' type='text'/>%</td>\n"
 			"<td width='26%' class='td2 odd'>(<span id='ID_0x0450'></span>~<span id='ID_0x0451'></span>)</td>\n"
 			"<td width='28%' align='right' class='odd'><button class='btn' onclick='doSubmit(this)' id='N509' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<!-- SOC 控制延迟时间 -->\n"
 			"<td width='255' class='td1 even'><span id='N14'></span></td>\n"
 			"<td width='26%' class='td4 even'><input class='txt' id='ID_0x060A' maxlength='6' onkeyup='Verify(this)' type='text'/>S</td>\n"
 			"<td width='26%' class='td2 even'>(<span id='ID_0x0452'></span>~<span id='ID_0x0453'></span>)</td>\n"
 			"<td width='28%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='N510' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<!-- SOC 恢复延迟时间-->\n"
 			"<td width='350' class='td1 odd'><span id='N15'></span></td>\n"
 			"<td width='26%' class='td4 odd'><input class='txt' id='ID_0x060B' maxlength='6' onkeyup='Verify(this)' type='text'/>S</td>\n"
 			"<td width='26%' class='td2 odd'>(<span id='ID_0x0454'></span>~<span id='ID_0x0455'></span>)</td>\n"
 			"<td width='28%' align='right' class='odd'><button class='btn' onclick='doSubmit(this)' id='N511' style='display:block;'></button></td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<div class='tip' id='tip2' style='width:90%;'><span>&nbsp;</span></div>\n"
 	"<div class='line_long'></div>\n"
 	"<!-- Vbat参数 -->\n"
 	"<script type='text/javascript'>\n"
 		"show_sT('N16');\n"
 	"</script>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='350' class='td1 odd'><input name='VBAT-PARAM' type='radio' value='85' id='VBAT-DIS'/><span id='N17'></span></td>\n"
 			"<td width='28%' class='td1 odd'><input name='VBAT-PARAM' type='radio' value='170' id='VBAT-EN'/><span id='N18'></span></td>\n"
 			"<!-- 保存 -->\n"
 			  "<td width='35%' align='right' class='odd'><button class='btn' onclick='doSubmit(this)' id='N512' style='display:block;'></button></td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<div class='tip' id='tip3' style='width:90%;'><span>&nbsp;</span></div>\n"
 	"<table id='tab_vbat' width='90%' border='0' style='display:none;'>\n"
 		"<tr>\n"
 			"<!-- VBAT 上限2级 -->\n"
 			"<td width='350' class='td1 odd'><span id='N19'></span></td>\n"
 			"<td width='26%' class='td4 odd'><input class='txt' id='ID_0x0611' maxlength='6' onkeyup='Verify(this)' type='text'/>V</td>\n"
 			"<td width='26%' class='td2 odd'>(<span id='ID_0x0456'></span>~<span id='ID_0x0457'></span>)</td>\n"
 			"<td width='28%' align='right' class='odd'><button class='btn' onclick='doSubmit(this)' id='N513' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<!-- VBAT 上限1级 -->\n"
 			"<td width='350' class='td1 even'><span id='N20'></span></td>\n"
 			"<td width='26%' class='td4 even'><input class='txt' id='ID_0x0612' maxlength='6' onkeyup='Verify(this)' type='text'/>V</td>\n"
 			"<td width='26%' class='td2 even'>(<span id='ID_0x0458'></span>~<span id='ID_0x0459'></span>)</td>\n"
 			"<td width='28%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='N514' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<!-- VBAT 下限1级 -->\n"
 			"<td width='350' class='td1 odd'><span id='N21'></span></td>\n"
 			"<td width='26%' class='td4 odd'><input class='txt' id='ID_0x0613' maxlength='6' onkeyup='Verify(this)' type='text'/>V</td>\n"
 			"<td width='26%' class='td2 odd'>(<span id='ID_0x045A'></span>~<span id='ID_0x045B'></span>)</td>\n"
 			"<td width='28%' align='right' class='odd'><button class='btn' onclick='doSubmit(this)' id='N515' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<!-- VBAT 下限2级 -->\n"
 			"<td width='350' class='td1 even'><span id='N22'></span></td>\n"
 			"<td width='26%' class='td4 even'><input class='txt' id='ID_0x0614' maxlength='6' onkeyup='Verify(this)' type='text'/>V</td>\n"
 			"<td width='26%' class='td2 even'>(<span id='ID_0x045C'></span>~<span id='ID_0x045D'></span>)</td>\n"
 			"<td width='28%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='N516' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr style=\"display:none;\">\n"
 			"<!-- VBAT 上限2级恢复 -->\n"
 			"<td width='350' class='td1 odd'><span id='N23'></span></td>\n"
 			"<td width='26%' class='td4 odd'><input class='txt' id='ID_0x0615' maxlength='6' onkeyup='Verify(this)' type='text'/>V</td>\n"
 			"<td width='26%' class='td2 odd'>(<span id='ID_0x045E'></span>~<span id='ID_0x045F'></span>)</td>\n"
 			"<td width='28%' align='right' class='odd'><button class='btn' onclick='doSubmit(this)' id='N517' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr style=\"display:none;\">\n"
 			"<!-- VBAT 上限1级恢复 -->\n"
 			"<td width='350' class='td1 even'><span id='N24'></span></td>\n"
 			"<td width='26%' class='td4 even'><input class='txt' id='ID_0x0616' maxlength='6' onkeyup='Verify(this)' type='text'/>V</td>\n"
 			"<td width='26%' class='td2 even'>(<span id='ID_0x0460'></span>~<span id='ID_0x0461'></span>)</td>\n"
 			"<td width='28%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='N518' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<!-- VBAT 下限1级恢复 -->\n"
 			"<td width='350' class='td1 odd'><span id='N25'></span></td>\n"
 			"<td width='26%' class='td4 odd'><input class='txt' id='ID_0x0617' maxlength='6' onkeyup='Verify(this)' type='text'/>V</td>\n"
 			"<td width='26%' class='td2 odd'>(<span id='ID_0x0462'></span>~<span id='ID_0x0463'></span>)</td>\n"
 			"<td width='28%' align='right' class='odd'><button class='btn' onclick='doSubmit(this)' id='N519' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<!-- VBAT 下限2级恢复 -->\n"
 			"<td width='350' class='td1 even'><span id='N26'></span></td>\n"
 			"<td width='26%' class='td4 even'><input class='txt' id='ID_0x0618' maxlength='6' onkeyup='Verify(this)' type='text'/>V</td>\n"
 			"<td width='26%' class='td2 even'>(<span id='ID_0x0464'></span>~<span id='ID_0x0465'></span>)</td>\n"
 			"<td width='28%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='N520' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<!-- VBAT 滞环控制值 -->\n"
 			"<td width='350' class='td1 odd'><span id='N27'></span></td>\n"
 			"<td width='26%' class='td4 odd'><input class='txt' id='ID_0x0619' maxlength='6' onkeyup='Verify(this)' type='text'/>V</td>\n"
 			"<td width='26%' class='td2 odd'>(<span id='ID_0x0466'></span>~<span id='ID_0x0467'></span>)</td>\n"
 			"<td width='28%' align='right' class='odd'><button class='btn' onclick='doSubmit(this)' id='N521' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<!-- VBAT 控制延迟时间 -->\n"
 			"<td width='350' class='td1 even'><span id='N28'></span></td>\n"
 			"<td width='26%' class='td4 even'><input class='txt' id='ID_0x061A' maxlength='6' onkeyup='Verify(this)' type='text'/>S</td>\n"
 			"<td width='26%' class='td2 even'>(<span id='ID_0x0468'></span>~<span id='ID_0x0469'></span>)</td>\n"
 			"<td width='28%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='N522' style='display:block;'></button></td>\n"
 		"</tr>\n"
 		"<tr>\n"
 			"<!-- VBAT 恢复延迟时间 -->\n"
 			"<td width='350' class='td1 odd'><span id='N29'></span></td>\n"
 			"<td width='26%' class='td4 odd'><input class='txt' id='ID_0x061B' maxlength='6' onkeyup='Verify(this)' type='text'/>S</td>\n"
 			"<td width='26%' class='td2 odd'>(<span id='ID_0x046A'></span>~<span id='ID_0x046B'></span>)</td>\n"
 			"<td width='28%' align='right' class='odd'><button class='btn' onclick='doSubmit(this)' id='N523' style='display:block;'></button></td>\n"
 		"</tr>\n"
 	"</table>\n"
 	"<div class='tip' id='tip4' style='width:90%;'><span>&nbsp;</span></div>\n"
 	"<div class='line_long'></div>\n"
 	"<div class='btm_blank'></div>\n"
 	"<div id='trans'></div>\n"
 	"<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
 "</body>\n"
 "<script language='javascript' type='text/javascript'>\n"
 	"var language=1;\n"
 	"var Json;\n"
 		//正整数、带一位小数的正浮点数
 	"var reg=/^((0(\\.\\d{1})?)|([1-9]\\d*(\\.\\d{1})?))$/;\n"
 		//正整数+0
 	"var reg2=/^(0|[1-9]\\d*)$/;\n"
 	"var lang=\n"
 	"{\n"
 		"N01:['保护参数','Protection Parameters'],\n"
 		"N02:['SOC参数','SOC Parameters'],\n"
 		"N03:['禁止','Disable'],\n"
 		"N04:['使能','Enable'],\n"
 		"N05:['SOC上限2级','SOC Uplimit2(%)'],\n"
 		"N06:['SOC上限1级','SOC Uplimit1(%)'],\n"
 		"N07:['SOC下限1级','SOC Lowlimit1(%)'],\n"
 		"N08:['SOC下限2级','SOC Lowlimit2(%)'],\n"
 		"N09:['SOC上限2恢复','SOC Uplimit2 Recovery(%)'],\n"
 		"N10:['SOC上限1恢复','SOC Uplimit1 Recovery(%)'],\n"
 		"N11:['SOC下限1恢复','SOC Lowlimit1 Recovery(%)'],\n"
 		"N12:['SOC下限2恢复','SOC Lowlimit2 Recovery(%)'],\n"
 		"N13:['SOC滞环控制','SOC Hysteresis Control(%)'],\n"
 		"N14:['SOC控制延迟时间','SOC Control Delay Time(S)'],\n"
 		"N15:['SOC控制恢复时间','SOC Control Recover Time(S)'],\n"
 		"N16:['电池电压参数','Vbat Parameters'],\n"
 		"N17:['禁止','Disable'],\n"
 		"N18:['使能','Enable'],\n"
 		"N19:['电池电压上限2级','Vbat Uplimit2(%)'],\n"
 		"N20:['电池电压上限1级','Vbat Uplimit1(%)'],\n"
 		"N21:['电池电压下限1级','Vbat Lowlimit1(%)'],\n"
 		"N22:['电池电压下限2级','Vbat Lowlimit2(%)'],\n"
 		"N23:['电池电压上限2恢复','Vbat Uplimit2 Recovery(%)'],\n"
 		"N24:['电池电压上限1恢复','Vbat Uplimit1 Recovery(%)'],\n"
 		"N25:['电池电压下限1恢复','Vbat Lowlimit1 Recovery(%)'],\n"
 		"N26:['电池电压下限2恢复','Vbat Lowlimit2 Recovery(%)'],\n"
 		"N27:['电池电压滞环控制','Vbat Hysteresis Control(%)'],\n"
 		"N28:['电池电压控制延迟时间','Vbat Control Delay Time(S)'],\n"
 		"N29:['电池电压控制恢复时间','Vbat Control Recover Time(S)'],\n"
 		"\n"
 		"N51:['设置失败！','Set failed!'],\n"
 		"N52:['设置成功！','Set successfully!'],\n"
 		"N53:['格式错误！','Format error!'],\n"
 		"N54:['范围错误！','Range error!'],\n"
"\n"
 		"N500:['设&nbsp;&nbsp;置','Set'],\n"
 		"N501:['设&nbsp;&nbsp;置','Set'],\n"
 		"N502:['设&nbsp;&nbsp;置','Set'],\n"
 		"N503:['设&nbsp;&nbsp;置','Set'],\n"
 		"N504:['设&nbsp;&nbsp;置','Set'],\n"
 		"N505:['设&nbsp;&nbsp;置','Set'],\n"
 		"N506:['设&nbsp;&nbsp;置','Set'],\n"
 		"N507:['设&nbsp;&nbsp;置','Set'],\n"
 		"N508:['设&nbsp;&nbsp;置','Set'],\n"
 		"N509:['设&nbsp;&nbsp;置','Set'],\n"
 		"N510:['设&nbsp;&nbsp;置','Set'],\n"
 		"N511:['设&nbsp;&nbsp;置','Set'],\n"
 		"N512:['设&nbsp;&nbsp;置','Set'],\n"
 		"N513:['设&nbsp;&nbsp;置','Set'],\n"
 		"N514:['设&nbsp;&nbsp;置','Set'],\n"
 		"N515:['设&nbsp;&nbsp;置','Set'],\n"
 		"N516:['设&nbsp;&nbsp;置','Set'],\n"
 		"N517:['设&nbsp;&nbsp;置','Set'],\n"
 		"N518:['设&nbsp;&nbsp;置','Set'],\n"
 		"N519:['设&nbsp;&nbsp;置','Set'],\n"
 		"N520:['设&nbsp;&nbsp;置','Set'],\n"
 		"N521:['设&nbsp;&nbsp;置','Set'],\n"
 		"N522:['设&nbsp;&nbsp;置','Set'],\n"
 		"N523:['设&nbsp;&nbsp;置','Set']\n"
 	"};\n"
        "function ajax()\n"
        "{\n"
            "var URL='s_028.html?0x0000&time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);           \n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}\n"
 	"function Init()\n"
 	"{\n"
 			//参数=0读所有设备地址
 		"var URL='s_028.html?0x0000&time='+Math.random();\n"
 		"var xmlhttp;\n"
 		"if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		"xmlhttp.onreadystatechange=function()\n"
 		"{\n"
 			"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 			"{\n"
 				"eval('Json='+xmlhttp.responseText);\n"
 				"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
 				"lang_init_ex(1,29);\n"
 				"lang_init_ex(500,523);\n"
 				"doSetValue(Json);\n"
 "\n"
 				"if(Json.ID_0x0282==0x11)\n"
 				"{\n"
 					"for(var i=0; i<=23; i++)eval('$(\\'N'+(500+i)+'\\').style.display=\\'none\\';');\n"
 					"$('SOC-EN').disabled=true;\n"
 					"$('SOC-DIS').disabled=true;\n"
 					"$('VBAT-EN').disabled=true;\n"
 					"$('VBAT-DIS').disabled=true;\n"
 					"$('trans').style.zIndex=9999;	\n"
 				"}\n"
 				"else\n"
 				"{\n"
 					"for(var i=0; i<=23; i++)eval('$(\\'N'+(500+i)+'\\').style.display=\\'block\\';');\n"
 					"$('SOC-EN').disabled=false;\n"
 					"$('SOC-DIS').disabled=false;\n"
 					"$('VBAT-EN').disabled=false;\n"
 					"$('VBAT-DIS').disabled=false;\n"
 					"$('trans').style.zIndex=-9999;\n"
 				"}\n"
"\n"
 				"setInterval('ajax()', 2000);\n"
 			"}\n"
 		"};\n"
 		"xmlhttp.open('GET',URL,true);\n"
 		"xmlhttp.send();\n"
 	"}\n"
"\n"
 	"function doSetValue(Json)  \n"
 	"{\n"
 		"if(Json.ID_0x0600==85){$('SOC-DIS').checked=true;$('SOC-EN').checked=false;$('tab_soc').style.display='none';$('tip2').style.display='none';}else{$('SOC-DIS').checked=false;$('SOC-EN').checked=true;$('tab_soc').style.display='block';$('tip2').style.display='block';show_tip_ex(2,\"&nbsp;\");}\n"
"\n"
 		"for(var i=1; i<=9; i++)eval('$(\\'ID_0x0'+(0x600+i).toString(16).toUpperCase()+'\\').value=(Json.ID_0x0'+(0x600+i).toString(16).toUpperCase()+'/10.0).toFixed(1);');\n"
 		"for(var i=10; i<=11; i++)eval('$(\\'ID_0x0'+(0x600+i).toString(16).toUpperCase()+'\\').value=Json.ID_0x0'+(0x600+i).toString(16).toUpperCase()+';');\n"
"\n"
 		"if(Json.ID_0x0610==85){$('VBAT-DIS').checked=true;$('VBAT-EN').checked=false;$('tab_vbat').style.display='none';$('tip4').style.display='none';}else{$('VBAT-DIS').checked=false;$('VBAT-EN').checked=true;$('tab_vbat').style.display='block';$('tip4').style.display='block';show_tip_ex(4,\"&nbsp;\");}\n"
"\n"
 		"for(var i=1; i<=9; i++)eval('$(\\'ID_0x0'+(0x610+i).toString(16).toUpperCase()+'\\').value=(Json.ID_0x0'+(0x610+i).toString(16).toUpperCase()+'/10.0).toFixed(1);');\n"
 		"for(var i=10; i<=11; i++)eval('$(\\'ID_0x0'+(0x610+i).toString(16).toUpperCase()+'\\').value=Json.ID_0x0'+(0x610+i).toString(16).toUpperCase()+';');\n"
"\n"
 		"for(var i=0x0440; i<=0x044F; i++) eval('$(\\'ID_0x0'+i.toString(16).toUpperCase()+'\\').innerHTML=(Json.ID_0x0'+i.toString(16).toUpperCase()+'/10.0).toFixed(1);');\n"
 		"for(var i=0x0450; i<=0x0451; i++) eval('$(\\'ID_0x0'+i.toString(16).toUpperCase()+'\\').innerHTML=(Json.ID_0x0'+i.toString(16).toUpperCase()+'/10.0).toFixed(1);');\n"
 		"for(var i=0x0452; i<=0x0455; i++) eval('$(\\'ID_0x0'+i.toString(16).toUpperCase()+'\\').innerHTML=Json.ID_0x0'+i.toString(16).toUpperCase()+';');\n"
 		"for(var i=0x0456; i<=0x0465; i++) eval('$(\\'ID_0x0'+i.toString(16).toUpperCase()+'\\').innerHTML=(Json.ID_0x0'+i.toString(16).toUpperCase()+'/10.0).toFixed(1);');\n"
 		"for(var i=0x0466; i<=0x0467; i++) eval('$(\\'ID_0x0'+i.toString(16).toUpperCase()+'\\').innerHTML=(Json.ID_0x0'+i.toString(16).toUpperCase()+'/10.0).toFixed(1);');\n"
 		"for(var i=0x0468; i<=0x046B; i++) eval('$(\\'ID_0x0'+i.toString(16).toUpperCase()+'\\').innerHTML=Json.ID_0x0'+i.toString(16).toUpperCase()+';');\n"
 	"}\n"
"\n"
 	 "function read_back(addr)\n"
 	"{ \n"
 		"var url='s_028.html?';\n"
 		"if(addr == 0x600||addr == 0x610){url=url+'0x0000';}\n"
 		"else {url=url+'0x0'+addr.toString(16).toUpperCase();}  \n"
 		"url=url+'&time='+Math.random();\n"
 			//alert(url);
"\n"
 		"var xmlhttp;\n"
 		"if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		"xmlhttp.onreadystatechange=function()\n"
 		"{\n"
 			"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 			"{\n"
 				"eval('Json='+xmlhttp.responseText);	\n"
 				"var pr=0,fe=0;\n"
"\n"
 	               "if(addr == 0x600)\n"
 	            "{\n"
 					"if($('SOC-EN').checked)pr=$('SOC-EN').value;\n"
            			"else if($('SOC-DIS').checked)pr=$('SOC-DIS').value;\n"
 					"eval('fe=Json.ID_0x0'+addr.toString(16).toUpperCase()+';');\n"
 					"if(pr!=fe) {if(fe==0){$('SOC-DIS').checked=true;$('SOC-EN').checked=false;}else{$('SOC-DIS').checked=false;$('SOC-EN').checked=true;}}\n"
 					"if(fe==85){$('tab_soc').style.display='none';$('tip2').style.display='none';}else{$('tab_soc').style.display='block';$('tip2').style.display='block';}\n"
 		    		"show_tip('&nbsp;');\n"
 		    		"if(pr==fe){setTimeout('show_tip(lang.N52[language])',500);}\n"
 		    		"else {setTimeout('show_tip(lang.N51[language])',500);}\n"
 			           "setTimeout('show_tip(\\'&nbsp;\\')',2500);\n"
 			           "doSetValue(Json);\n"
 			       "}\n"
 			       "else if(addr >= 0x601 && addr <= 0x60B)\n"
 	            "{\n"
 	            	"if(addr >= 0x601 && addr <= 0x609){eval('pr=$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value*10;');}\n"
 	            	"else{eval('pr=$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value;');}\n"
 					"eval('fe=Json.ID_0x0'+addr.toString(16).toUpperCase()+';');\n"
 					"if(pr!=fe) eval('$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value=(Json.ID_0x0'+addr.toString(16).toUpperCase()+'/10.0).toFixed(1);');	            		\n"
 		    		"show_tip_ex(2,'&nbsp;');\n"
 		    		"if(pr==fe){setTimeout('show_tip_ex(2,lang.N52[language])',500);}\n"
 		    		"else {setTimeout('show_tip_ex(2,lang.N51[language])',500);}\n"
 			           "setTimeout('show_tip_ex(2,\\'&nbsp;\\')',2500);\n"
 			       "}\n"
 			       "else if(addr == 0x610)\n"
 	            "{\n"
 		           	"if($('VBAT-EN').checked)pr=$('VBAT-EN').value;\n"
 		           	"else if($('VBAT-DIS').checked)pr=$('VBAT-DIS').value;\n"
 					"eval('fe=Json.ID_0x0'+addr.toString(16).toUpperCase()+';');\n"
 					"if(pr!=fe) {if(fe==0){$('VBAT-DIS').checked=true;$('VBAT-EN').checked=false;}else{$('VBAT-DIS').checked=false;$('VBAT-EN').checked=true;}}\n"
 					"if(fe==85){$('tab_vbat').style.display='none';$('tip4').style.display='none';}else{$('tab_vbat').style.display='block';$('tip4').style.display='block';}		    			\n"
 		    		"show_tip_ex(3,'&nbsp;');\n"
 		    		"if(pr==fe){setTimeout('show_tip_ex(3,lang.N52[language])',500);}\n"
 		    		"else {setTimeout('show_tip_ex(3,lang.N51[language])',500);}\n"
 			           "setTimeout('show_tip_ex(3,\\'&nbsp;\\')',2500);\n"
 			           "doSetValue(Json);\n"
 			       "}\n"
 			       "else if(addr >= 0x611 && addr <= 0x61B)\n"
 	            "{\n"
 					"if(addr >= 0x611 && addr <= 0x619){eval('pr=$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value*10;');}\n"
 					"else{eval('pr=$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value;');}\n"
 					"eval('fe=Json.ID_0x0'+addr.toString(16).toUpperCase()+';');\n"
 					"if(pr!=fe) eval('$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value=(Json.ID_0x0'+addr.toString(16).toUpperCase()+'/10.0).toFixed(1);');\n"
 		    		"show_tip_ex(4,'&nbsp;');\n"
 		    		"if(pr==fe){setTimeout('show_tip_ex(4,lang.N52[language])',500);}\n"
 		    		"else {setTimeout('show_tip_ex(4,lang.N51[language])',500);}\n"
 			           "setTimeout('show_tip_ex(4,\\'&nbsp;\\')',2500);\n"
 			       "}\n"
 			"}\n"
 		"};\n"
 		"xmlhttp.open('GET',url,true);\n"
 		"xmlhttp.send();     \n"
        "} \n"
"\n"
 	"function doSubmit(obj)\n"
 	"{\n"
            "var URL='a_028.html?';\n"
            "var readBack=0;\n"
            "var en;\n"
            "switch(obj.id)\n"
            "{\n"
            	"case 'N500': \n"
            	"if($('SOC-EN').checked)en=$('SOC-EN').value;\n"
            	"else if($('SOC-DIS').checked)en=$('SOC-DIS').value;\n"
            	"URL=URL+'&0x0600='+en;readBack=0x0600;\n"
            	"break;\n"
             "case 'N501': URL=URL+'&0x0601='+$('ID_0x0601').value*10;readBack=0x0601;break;\n"
             "case 'N502': URL=URL+'&0x0602='+$('ID_0x0602').value*10;readBack=0x0602;break;\n"
             "case 'N503': URL=URL+'&0x0603='+$('ID_0x0603').value*10;readBack=0x0603;break;\n"
             "case 'N504': URL=URL+'&0x0604='+$('ID_0x0604').value*10;readBack=0x0604;break;\n"
             "case 'N505': URL=URL+'&0x0605='+$('ID_0x0605').value*10;readBack=0x0605;break;\n"
             "case 'N506': URL=URL+'&0x0606='+$('ID_0x0606').value*10;readBack=0x0606;break;\n"
             "case 'N507': URL=URL+'&0x0607='+$('ID_0x0607').value*10;readBack=0x0607;break;\n"
             "case 'N508': URL=URL+'&0x0608='+$('ID_0x0608').value*10;readBack=0x0608;break;\n"
             "case 'N509': URL=URL+'&0x0609='+$('ID_0x0609').value*10;readBack=0x0609;break;\n"
             "case 'N510': URL=URL+'&0x060A='+$('ID_0x060A').value;readBack=0x060A;break;\n"
             "case 'N511': URL=URL+'&0x060B='+$('ID_0x060B').value;readBack=0x060B;break;\n"
            	"case 'N512': \n"
            	"if($('VBAT-EN').checked)en=$('VBAT-EN').value;\n"
            	"else if($('VBAT-DIS').checked)en=$('VBAT-DIS').value;\n"
            	"URL=URL+'&0x0610='+en;readBack=0x0610;\n"
            	"break;\n"
             "case 'N513': URL=URL+'&0x0611='+$('ID_0x0611').value*10;readBack=0x0611;break;\n"
             "case 'N514': URL=URL+'&0x0612='+$('ID_0x0612').value*10;readBack=0x0612;break;\n"
             "case 'N515': URL=URL+'&0x0613='+$('ID_0x0613').value*10;readBack=0x0613;break;\n"
             "case 'N516': URL=URL+'&0x0614='+$('ID_0x0614').value*10;readBack=0x0614;break;\n"
             "case 'N517': URL=URL+'&0x0615='+$('ID_0x0615').value*10;readBack=0x0615;break;\n"
             "case 'N518': URL=URL+'&0x0616='+$('ID_0x0616').value*10;readBack=0x0616;break;\n"
             "case 'N519': URL=URL+'&0x0617='+$('ID_0x0617').value*10;readBack=0x0617;break;\n"
             "case 'N520': URL=URL+'&0x0618='+$('ID_0x0618').value*10;readBack=0x0618;break;\n"
             "case 'N521': URL=URL+'&0x0619='+$('ID_0x0619').value*10;readBack=0x0619;break;\n"
             "case 'N522': URL=URL+'&0x061A='+$('ID_0x061A').value;readBack=0x061A;break;\n"
             "case 'N523': URL=URL+'&0x061B='+$('ID_0x061B').value;readBack=0x061B;break;\n"
             "default:break;\n"
            "}\n"
            "URL=URL+'&time='+ Math.random();\n"
             //alert(URL);  
"\n"
            "function success()\n"
            "{\n"
             "if(readBack >= 0x600 && readBack <= 0x61B)\n"
             "{\n"
 	     		"show_tip('&nbsp;');\n"
 	    		"setTimeout('read_back('+readBack+')', 100);\n"
 		           "setTimeout('show_tip(\\'&nbsp;\\')',2500);               		\n"
             "}\n"
            "} \n"
"\n"
             //测试
             //success();  
"\n"
 		"sendHttpReq(URL, success);\n"
 	"}\n"
"\n"
 	"function show_tip_ex(id, obj){eval('$(\\'tip'+id+'\\').innerHTML=obj;');}\n"
 	"function Verify(obj)\n"
 	"{\n"
 		"var range=parseFloat(obj.value);\n"
 		"var range2=parseInt(obj.value);\n"
 		"var err;\n"
"\n"
 		"switch(obj.id)\n"
 		"{\n"
 			"case \"ID_0x0601\":if(!obj.value.match(reg)){err=2;$('N501').disabled=true;}else if(range<(Json.ID_0x0440/10.0).toFixed(1)||range>(Json.ID_0x0441/10.0).toFixed(1)){err=1;$('N501').disabled=true;}else{err=0;$('N501').disabled=false;}break;\n"
 			"case \"ID_0x0602\":if(!obj.value.match(reg)){err=2;$('N502').disabled=true;}else if(range<(Json.ID_0x0442/10.0).toFixed(1)||range>(Json.ID_0x0443/10.0).toFixed(1)){err=1;$('N502').disabled=true;}else{err=0;$('N502').disabled=false;}break;\n"
 			"case \"ID_0x0603\":if(!obj.value.match(reg)){err=2;$('N503').disabled=true;}else if(range<(Json.ID_0x0444/10.0).toFixed(1)||range>(Json.ID_0x0445/10.0).toFixed(1)){err=1;$('N503').disabled=true;}else{err=0;$('N503').disabled=false;}break;\n"
 			"case \"ID_0x0604\":if(!obj.value.match(reg)){err=2;$('N504').disabled=true;}else if(range<(Json.ID_0x0446/10.0).toFixed(1)||range>(Json.ID_0x0447/10.0).toFixed(1)){err=1;$('N504').disabled=true;}else{err=0;$('N504').disabled=false;}break;\n"
 			"case \"ID_0x0605\":if(!obj.value.match(reg)){err=2;$('N505').disabled=true;}else if(range<(Json.ID_0x0448/10.0).toFixed(1)||range>(Json.ID_0x0449/10.0).toFixed(1)){err=1;$('N505').disabled=true;}else{err=0;$('N505').disabled=false;}break;\n"
 			"case \"ID_0x0606\":if(!obj.value.match(reg)){err=2;$('N506').disabled=true;}else if(range<(Json.ID_0x044A/10.0).toFixed(1)||range>(Json.ID_0x044B/10.0).toFixed(1)){err=1;$('N506').disabled=true;}else{err=0;$('N506').disabled=false;}break;\n"
 			"case \"ID_0x0607\":if(!obj.value.match(reg)){err=2;$('N507').disabled=true;}else if(range<(Json.ID_0x044C/10.0).toFixed(1)||range>(Json.ID_0x044D/10.0).toFixed(1)){err=1;$('N507').disabled=true;}else{err=0;$('N507').disabled=false;}break;\n"
 			"case \"ID_0x0608\":if(!obj.value.match(reg)){err=2;$('N508').disabled=true;}else if(range<(Json.ID_0x044E/10.0).toFixed(1)||range>(Json.ID_0x044F/10.0).toFixed(1)){err=1;$('N508').disabled=true;}else{err=0;$('N508').disabled=false;}break;\n"
 				//传送x10,按整数下发
 			"case \"ID_0x0609\":if(!obj.value.match(reg)){err=2;$('N509').disabled=true;}else if(range<(Json.ID_0x0450/10.0).toFixed(1)||range>(Json.ID_0x0451/10.0).toFixed(1)){err=1;$('N509').disabled=true;}else{err=0;$('N509').disabled=false;}break;\n"
 			"case \"ID_0x060A\":if(!obj.value.match(reg2)){err=2;$('N510').disabled=true;}else if(range2<Json.ID_0x0452||range2>Json.ID_0x0453){err=1;$('N510').disabled=true;}else{err=0;$('N510').disabled=false;}break;\n"
 			"case \"ID_0x060B\":if(!obj.value.match(reg2)){err=2;$('N511').disabled=true;}else if(range2<Json.ID_0x0454||range2>Json.ID_0x0455){err=1;$('N511').disabled=true;}else{err=0;$('N511').disabled=false;}break;\n"
"\n"
 			"case \"ID_0x0611\":if(!obj.value.match(reg)){err=2;$('N513').disabled=true;}else if(range<(Json.ID_0x0456/10.0).toFixed(1)||range>(Json.ID_0x0457/10.0).toFixed(1)){err=1;$('N513').disabled=true;}else{err=0;$('N513').disabled=false;}break;\n"
 			"case \"ID_0x0612\":if(!obj.value.match(reg)){err=2;$('N514').disabled=true;}else if(range<(Json.ID_0x0458/10.0).toFixed(1)||range>(Json.ID_0x0459/10.0).toFixed(1)){err=1;$('N514').disabled=true;}else{err=0;$('N514').disabled=false;}break;\n"
 			"case \"ID_0x0613\":if(!obj.value.match(reg)){err=2;$('N515').disabled=true;}else if(range<(Json.ID_0x045A/10.0).toFixed(1)||range>(Json.ID_0x045B/10.0).toFixed(1)){err=1;$('N515').disabled=true;}else{err=0;$('N515').disabled=false;}break;\n"
 			"case \"ID_0x0614\":if(!obj.value.match(reg)){err=2;$('N516').disabled=true;}else if(range<(Json.ID_0x045C/10.0).toFixed(1)||range>(Json.ID_0x045D/10.0).toFixed(1)){err=1;$('N516').disabled=true;}else{err=0;$('N516').disabled=false;}break;\n"
 			"case \"ID_0x0615\":if(!obj.value.match(reg)){err=2;$('N517').disabled=true;}else if(range<(Json.ID_0x045E/10.0).toFixed(1)||range>(Json.ID_0x045F/10.0).toFixed(1)){err=1;$('N517').disabled=true;}else{err=0;$('N517').disabled=false;}break;\n"
 			"case \"ID_0x0616\":if(!obj.value.match(reg)){err=2;$('N518').disabled=true;}else if(range<(Json.ID_0x0460/10.0).toFixed(1)||range>(Json.ID_0x0461/10.0).toFixed(1)){err=1;$('N518').disabled=true;}else{err=0;$('N518').disabled=false;}break;\n"
 			"case \"ID_0x0617\":if(!obj.value.match(reg)){err=2;$('N519').disabled=true;}else if(range<(Json.ID_0x0462/10.0).toFixed(1)||range>(Json.ID_0x0463/10.0).toFixed(1)){err=1;$('N519').disabled=true;}else{err=0;$('N519').disabled=false;}break;\n"
 			"case \"ID_0x0618\":if(!obj.value.match(reg)){err=2;$('N520').disabled=true;}else if(range<(Json.ID_0x0464/10.0).toFixed(1)||range>(Json.ID_0x0465/10.0).toFixed(1)){err=1;$('N520').disabled=true;}else{err=0;$('N520').disabled=false;}break;\n"
 				//传送x10,按整数下发
 			"case \"ID_0x0619\":if(!obj.value.match(reg)){err=2;$('N521').disabled=true;}else if(range<(Json.ID_0x0466/10.0).toFixed(1)||range>(Json.ID_0x0467/10.0).toFixed(1)){err=1;$('N521').disabled=true;}else{err=0;$('N521').disabled=false;}break;\n"
 			"case \"ID_0x061A\":if(!obj.value.match(reg2)){err=2;$('N522').disabled=true;}else if(range<Json.ID_0x0468||range>Json.ID_0x0469){err=1;$('N522').disabled=true;}else{err=0;$('N522').disabled=false;}break;\n"
 			"case \"ID_0x061B\":if(!obj.value.match(reg2)){err=2;$('N523').disabled=true;}else if(range<Json.ID_0x046A||range>Json.ID_0x046B){err=1;$('N523').disabled=true;}else{err=0;$('N523').disabled=false;}break;\n"
 			"default:\n"
 			"break;	\n"
 		"}\n"
"\n"
 		"switch(obj.id)\n"
 		"{\n"
 			"case \"ID_0x0601\":case \"ID_0x0602\":case \"ID_0x0603\":case \"ID_0x0604\":case \"ID_0x0605\":case \"ID_0x0606\":case \"ID_0x0607\":case \"ID_0x0608\":\n"
 			"case \"ID_0x0609\":case \"ID_0x060A\":case \"ID_0x060B\":\n"
 				"if(err==1)show_tip_ex(2,lang.N54[language]);\n"
 				"else if(err==2)show_tip_ex(2,lang.N53[language]);\n"
 				"else show_tip_ex(2,\"&nbsp;\");\n"
 			"break;\n"
 			"case \"ID_0x0611\":case \"ID_0x0612\":case \"ID_0x0613\":case \"ID_0x0614\":case \"ID_0x0615\":case \"ID_0x0616\":case \"ID_0x0617\":case \"ID_0x0618\":\n"
 			"case \"ID_0x0619\":case \"ID_0x061A\":case \"ID_0x061B\":\n"
 				"if(err==1)show_tip_ex(4,lang.N54[language]);\n"
 				"else if(err==2)show_tip_ex(4,lang.N53[language]);\n"
 				"else show_tip_ex(4,\"&nbsp;\");\n"
 			"break;\n"
 			"default:\n"
 			"break;				\n"
 		"}	\n"
 	"}		\n"
"\n"
 "</script>\n"
"</html>\n"
};
#endif
