#ifndef _HTML_H_023_H_
#define _HTML_H_023_H_
static const char h_023[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
 "<head>\n"
 	"<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
 	"<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
 	"<script type='text/javascript'>\n"
            "var $=function(o){return document.getElementById(o);};\n"
            "function lang_init_ex(st,end){for(var i=st;i<=end;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
            "function show_tip_ex(id, obj){eval('$(\\'tip'+id+'\\').innerHTML=obj;');}\n"
            "function show_T(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
                "str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_sT(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_sT_ex(tid, id)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' id='\"+id+\"' style='display:none;width:90%'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function sendHttpReq(url, successFn)\n"
            "{\n"
                 //alert(url);   
                "var xmlhttp;\n"
                "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                "xmlhttp.onreadystatechange=function()\n"
                "{\n"
                    "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                    "{\n"
                        "if(xmlhttp.responseText=='1'){successFn();}\n"
                    "}\n"
                "};\n"
                "xmlhttp.open('GET',url,true);\n"
                "xmlhttp.send();\n"
            "}\n"
        "</script>\n"
 	"<style type='text/css'>\n"
 		"tr{height:27px;}\n"
 		".td1{padding-left:40px;text-align:left;}\n"
 		".td2{text-align:left;}\n"
 		".td3{padding-right:40px;text-align:right;}\n"
 		".txt{width:50px;text-align:right;}\n"
 	"</style>\n"
 "</head>\n"
 "<body onload='Init()'>\n"
 	"<script type='text/javascript'>\n"
 		"show_T('N01');\n"
 		"show_sT('N02');\n"
 	"</script>\n"
        "<!-- 界面选择 -->\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
              "<td width='30%' class='td1 odd'><input name='SalveDevice-Sel' type='checkbox' id='Device-PCS'/><span id='N03'></span></td>\n"
              "<td width='30%' class='td1 odd'><input name='SalveDevice-Sel' type='checkbox' id='Device-PV'/><span id='N04'></span></td>\n"
              "<td width='30%' class='td1 odd'><input name='SalveDevice-Sel' type='checkbox' id='Device-DCDC'/><span id='N05'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
              "<td width='30%' class='td1 even'><input name='SalveDevice-Sel' type='checkbox' id='Device-PVS'/><span id='N06'></span></td>\n"
              "<td width='30%' class='td1 even'><input name='SalveDevice-Sel' type='checkbox' id='Device-BMS'/><span id='N07'></span></td>\n"
              "<td width='30%' class='td1 even'><input name='SalveDevice-Sel' type='checkbox' id='Device-Ammeter'/><span id='N08'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
              "<td width='30%' class='td1 odd'><input name='SalveDevice-Sel' type='checkbox' id='Device-ENV'/><span id='N09'></span></td>\n"
              "<td width='30%' class='td1 odd'><span></span></td>\n"
              "<td width='30%' class='td1 odd'><span></span></td>\n"
            "</tr>\n"
            "<tr style='display:none;'>\n"
                "<td width='30%' class='td1 even'><input name='SalveDevice-Sel' type='checkbox' id='Device-RealTimeMonitor'/><span id='N32'></span></td>\n"
             "<td width='30%' class='td1 even'><input name='SalveDevice-Sel' type='checkbox' id='Device-BetteryControl' style='display:none;'/><span id='N33' style='display:none;'></span></td>\n"
                "<td width='30%' class='td1 even'><span></span></td>\n"
            "</tr>\n"
        "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip1'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn1' style='display:block;'><span id='N400'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>  \n"
        "<!-- 分时段控制使能 -->\n"
        "<script type='text/javascript'>\n"
            "show_sT('N12');\n"
        "</script>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='30%' class='td1 odd'><input name='TIME-SLOT-EN' type='radio' value='0' id='T-DIS'/><span id='N13'></span></td>\n"
                "<td width='30%' class='td1 odd'><input name='TIME-SLOT-EN' type='radio' value='1' id='T-HOUR'/><span id='N14'></span></td>\n"
                "<td width='30%' class='td1 odd'><input name='TIME-SLOT-EN' type='radio' value='2' id='T-WEEK'/><span id='N34'></span></td>\n"
            "</tr>\n"
        "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip2'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn2' style='display:block;'><span id='N402'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='btm_blank'></div>\n"
 	"<!-- 电池类型 -->\n"
 	"<script type='text/javascript'>\n"
 		"show_sT('N15');\n"
 	"</script>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			 "<td width='30%' class='td1 odd'><input name='BATTERY-TYPE' type='radio' value='0' id='B-NONE'/><span id='N16'></span></td>\n"
 			 "<td width='30%' class='td1 odd'><input name='BATTERY-TYPE' type='radio' value='1' id='B-TYPE1'/><span id='N17'></span></td>\n"
 			 "<td width='30%' class='td1 odd'><input name='BATTERY-TYPE' type='radio' value='2' id='B-TYPE2'/><span id='N18'></span></td>\n"
            "</tr>			\n"
 	"</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip3'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn3' style='display:block;'><span id='N403'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
 	"<div class='btm_blank'></div>\n"
 	"<!-- DCDC类型 -->\n"
 	"<script type='text/javascript'>\n"
 		"show_sT('N19');\n"
 	"</script>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='30%' class='td1 odd'><input name='DCDC-Type' type='radio' value='0' id='DCDC-DIS'/><span id='N20'></span></td>\n"
                "<td width='30%' class='td1 odd'><input name='DCDC-Type' type='radio' value='1' id='DCDC-OneWay'/><span id='N21'></span></td>\n"
                "<td width='30%' class='td1 odd'><input name='DCDC-Type' type='radio' value='2' id='DCDC-BothWay'/><span id='N22'></span></td>\n"
 		"</tr>\n"
 	"</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip4'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn4' style='display:block;'><span id='N404'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
 	"<div class='btm_blank'></div>\n"
 	"<!-- PCS通讯方式 -->\n"
 	"<script type='text/javascript'>\n"
 		"show_sT('N26');\n"
 	"</script>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='30%' class='td1 odd'><input name='PCS-COM-MODE' type='radio' value='0' id='PCS-UART'/><span id='N27'></span></td>\n"
 			"<td width='30%' class='td1 odd'><input name='PCS-COM-MODE' type='radio' value='1' id='PCS-NET'/><span id='N28'></span></td>\n"
 		"</tr>\n"
 	"</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip6'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn6' style='display:block;'><span id='N406'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
 	"<div class='btm_blank'></div>\n"
        "<!-- 配电功能使能 -->\n"
        "<script type='text/javascript'>\n"
            "show_sT('N29');\n"
        "</script>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='30%' class='td1 odd'><input name='Distribution-EN' type='radio' value='85' id='D-DIS'/><span id='N30'></span></td>\n"
                "<td width='30%' class='td1 odd'><input name='Distribution-EN' type='radio' value='170' id='D-EN'/><span id='N31'></span></td>\n"
            "</tr>\n"
        "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip7'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn7' style='display:block;'><span id='N407'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='btm_blank'></div>\n"
        "<!-- 均衡控制使能 -->\n"
        "<script type='text/javascript'>\n"
            "show_sT('N35');\n"
        "</script>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='30%' class='td1 odd'><input name='Balance-EN' type='radio' value='85' id='B-DIS'/><span id='N36'></span></td>\n"
                "<td width='30%' class='td1 odd'><input name='Balance-EN' type='radio' value='170' id='B-EN'/><span id='N37'></span></td>\n"
            "</tr>\n"
        "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip8'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn8' style='display:block;'><span id='N408'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='btm_blank'></div>\n"
        "<!-- PCS离网启动策略 -->\n"
        "<script type='text/javascript'>\n"
            "show_sT('N38');\n"
        "</script>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='30%' class='td1 odd'><input name='OFFGRID-POLICY' type='radio' value='0' id='ALL-NORMAL'/><span id='N39'></span></td>\n"
                "<td width='30%' class='td1 odd'><input name='OFFGRID-POLICY' type='radio' value='1' id='PART-NORMAL'/><span id='N40'></span></td>\n"
            "</tr>\n"
        "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip9'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn9' style='display:block;'><span id='N409'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='btm_blank'></div>\n"
        "<!-- PV通讯方式 -->\n"
        "<script type='text/javascript'>\n"
            "show_sT('N41');\n"
        "</script>  \n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='30%' class='td1 odd'><input name='PV-COM-MODE' type='radio' value='0' id='PV-UART'/><span id='N42'></span></td>\n"
                "<td width='30%' class='td1 odd'><input name='PV-COM-MODE' type='radio' value='1' id='PV-NET'/><span id='N43'></span></td>\n"
            "</tr>\n"
        "</table> \n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip10'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn10' style='display:block;'><span id='N410'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='btm_blank'></div>\n"
        "<!-- 电表协议 -->\n"
        "<script type='text/javascript'>\n"
            "show_sT('N44');\n"
        "</script>  \n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='30%' class='td1 odd'><input name='AMMETER-PROTOCOL' type='radio' value='0' id='AMMETER-MODBUS'/><span id='N45'></span></td>\n"
                "<td width='30%' class='td1 odd'><input name='AMMETER-PROTOCOL' type='radio' value='1' id='AMMETER-DLT645'/><span id='N46'></span></td>\n"
            "</tr>\n"
        "</table> \n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip11'>&nbsp;</span></td>\n"
                "<!-- 保存 -->\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn11' style='display:block;'><span id='N411'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='btm_blank'></div>\n"
 	"<div id='trans'></div>\n"
 	"<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
 "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var language=0;\n"
        "var Json; \n"
        "var lang=\n"
        "{\n"
            "N01:['功能设置','Function Settings'],\n"
            "N02:['界面','Interface'],\n"
            "N03:['储能逆变器','PCS'],\n"
            "N04:['光伏逆变器','PV'],\n"
            "N05:['光伏控制器','DCDC'],\n"
            "N06:['光伏汇流箱','PVS'],\n"
            "N07:['电池管理系统','BMS'],\n"
            "N08:['电表','Ammeter'],\n"
            "N09:['环境监测仪','Env-Detector'],\n"
"\n"
            "N12:['分时段控制使能','Time Slot Enbale'],\n"
            "N13:['禁止','Disable'],\n"
            "N14:['按小时','By Hour'], \n"
          "N15:['电池类型','Battery Type'],\n"
          "N16:['禁止','Disable'],\n"
          "N17:['68Ah','68Ah'],\n"
          "N18:['94Ah','94Ah'],\n"
          "N19:['DCDC类型','DCDC Type'],\n"
            "N20:['禁止','Disable'],\n"
            "N21:['单向DCDC','One-way DCDC'],\n"
            "N22:['双向DCDC','Bothway DCDC'],\n"
"\n"
          "N26:['PCS通讯模式','PCS Comm Mode'],\n"
            "N27:['串口','Uart'],\n"
            "N28:['网口','TCP/IP'],\n"
            "N29:['配电使能','Distribution Enbale'],\n"
            "N30:['禁止','Disable'],\n"
            "N31:['使能','Enable'],          \n"
            "N32:['实时监控','RealTime Monitor'],\n"
            "N33:['电池控制','Battery Control'], \n"
            "N34:['按星期','By Week'],  \n"
            "N35:['均衡控制使能','Balance Control Enbale'],\n"
            "N36:['禁止','Disable'],\n"
            "N37:['使能','Enable'],\n"
            "N38:['PCS离网启动策略','PCS OFF-Grid Start Policy'],\n"
            "N39:['全部正常','All Normal'],\n"
            "N40:['部分正常','Normal Part'],\n"
            "N41:['PV通讯模式','PV Comm Mode'],\n"
            "N42:['串口','Uart'],\n"
            "N43:['网口','TCP/IP'],\n"
            "N44:['电表协议','Ammeter Protocol'],\n"
            "N45:['MODBUS','MODBUS'],\n"
            "N46:['DL/T645','DL/T645'],\n"
"\n"
            "N400:['设&nbsp;&nbsp;置','Set'], \n"
            "N401:['设&nbsp;&nbsp;置','Set'], \n"
            "N402:['设&nbsp;&nbsp;置','Set'],  \n"
            "N403:['设&nbsp;&nbsp;置','Set'], \n"
            "N404:['设&nbsp;&nbsp;置','Set'],  \n"
            "N405:['设&nbsp;&nbsp;置','Set'], 	          \n"
            "N406:['设&nbsp;&nbsp;置','Set'],  \n"
            "N407:['设&nbsp;&nbsp;置','Set'], \n"
            "N408:['设&nbsp;&nbsp;置','Set'], \n"
            "N409:['设&nbsp;&nbsp;置','Set'], \n"
            "N410:['设&nbsp;&nbsp;置','Set'], \n"
            "N411:['设&nbsp;&nbsp;置','Set'], \n"
"\n"
            "N499:['设置成功！','Set successfully!'],\n"
            "N500:['设置失败！','Set Failed!'],\n"
            "N501:['格式错误！','Format error!'],\n"
            "N502:['范围错误！','Range error!']      \n"
        "};\n"
        "function Init()\n"
        "{\n"
            "var URL='s_023.html?time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{            \n"
                    "eval('Json='+xmlhttp.responseText);				\n"
"\n"
     			"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                     //初始化语言
     			"lang_init_ex(1,9);\n"
                    "lang_init_ex(12,22);\n"
                    "lang_init_ex(26,46);\n"
                    "lang_init_ex(400,400); \n"
                    "lang_init_ex(402,404);\n"
                    "lang_init_ex(406,411);\n"
"\n"
     			"doSetValue(Json);\n"
"\n"
     				//user用户不能配置，install用户可以配置
     			"if(Json.ID_0x0282==0x11)\n"
     			"{\n"
     				"$('btn1').style.display='none';\n"
     				"$('trans').style.zIndex=9999;\n"
     			"}\n"
     			"else\n"
     			"{\n"
     				"$('btn1').style.display='inline';\n"
     				"$('trans').style.zIndex=-9999;\n"
     			"}\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}\n"
        "function read_back(addr)\n"
        "{\n"
            "var url='s_023.html?';\n"
            "if(addr==0x038A){url=url+'&0x038A'+'&0x0394';}\n"
            "if(addr==0x038B){url=url+'&0x038B'+'&0x0392';}\n"
            "if(addr==0x038C){url=url+'&0x038C'+'&0x0395';}\n"
            "if(addr==0x0390){url=url+'&0x0390'+'&0x0391'+'&0x0392'+'&0x0393'+'&0x0394'+'&0x0395'+'&0x0396'+'&0x0397'+'&0x0398'+'&0x0399'+'&0x039A';}\n"
            "url=url+'&time='+Math.random();\n"
"\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText); \n"
                    "if(addr == 0x0390)\n"
                    "{\n"
                        "var pr_d_pcs=0,fe_d_pcs=0;\n"
                        "var pr_d_pv=0,fe_d_pv=0;\n"
                        "var pr_d_dcdc=0,fe_d_dcdc=0;\n"
                        "var pr_d_bms=0,fe_d_bms=0;\n"
                        "var pr_d_ammeter=0,fe_d_ammeter=0;\n"
                        "var pr_d_pvs=0,fe_d_pvs=0;\n"
                        "var pr_d_realtime=0,fe_d_realtime=0;\n"
                        "var pr_d_env=0,fe_d_env=0;\n"
                        "if($('Device-PCS').checked){pr_d_pcs=1;}else{pr_d_pcs=0;}\n"
                        "if($('Device-PV').checked){pr_d_pv=1;}else{pr_d_pv=0;}\n"
                        "if($('Device-DCDC').checked){pr_d_dcdc=1;}else{pr_d_dcdc=0;}\n"
                        "if($('Device-PVS').checked){pr_d_pvs=1;}else{pr_d_pvs=0;}\n"
                        "if($('Device-BMS').checked){pr_d_bms=1;}else{pr_d_bms=0;} \n"
                        "if($('Device-Ammeter').checked){pr_d_ammeter=1;}else{pr_d_ammeter=0;}\n"
                        "if($('Device-RealTimeMonitor').checked){pr_d_realtime=1;}else{pr_d_realtime=0;}\n"
                        "if($('Device-ENV').checked){pr_d_env=1;}else{pr_d_env=0;}\n"
                        "fe_d_pcs = Json.ID_0x0390;\n"
                        "fe_d_pv = Json.ID_0x0391;\n"
                        "fe_d_dcdc = Json.ID_0x0392;\n"
                        "fe_d_pvs = Json.ID_0x0393;\n"
                        "fe_d_bms = Json.ID_0x0394;\n"
                        "fe_d_ammeter = Json.ID_0x0395;\n"
                        "fe_d_realtime = Json.ID_0x0396;\n"
                        "fe_d_env = Json.ID_0x039A;\n"
                        "show_tip_ex(1,'&nbsp;');\n"
                        "if(pr_d_pcs!=fe_d_pcs || pr_d_pv!=fe_d_pv || pr_d_dcdc!=fe_d_dcdc || pr_d_pvs!=fe_d_pvs || pr_d_bms!=fe_d_bms || pr_d_ammeter!=fe_d_ammeter || pr_d_realtime!=fe_d_realtime || pr_d_env!=fe_d_env){\n"
                            "setTimeout('show_tip_ex(1,lang.N500[language])',500);\n"
                        "}\n"
                        "else {setTimeout('show_tip_ex(1,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(1,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x0389)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('T-DIS').checked){pr=$('T-DIS').value;}\n"
                        "else if($('T-HOUR').checked){pr=$('T-HOUR').value;}\n"
                        "else if($('T-WEEK').checked){pr=$('T-WEEK').value;}\n"
                        "fe=Json.ID_0x0389;\n"
                        "if(pr!=fe){\n"
                            "if(Json.ID_0x0389==0)\n"
                            "{\n"
                                "$('T-DIS').checked=true;\n"
                                "$('T-HOUR').checked=false;\n"
                                "$('T-WEEK').checked=false;\n"
                            "}\n"
                            "else if(Json.ID_0x0389==1)\n"
                            "{\n"
                                "$('T-DIS').checked=false;\n"
                                "$('T-HOUR').checked=true;\n"
                                "$('T-WEEK').checked=false;              \n"
                            "}\n"
                            "else if(Json.ID_0x0389==2)\n"
                            "{\n"
                                "$('T-DIS').checked=false;\n"
                                "$('T-HOUR').checked=false;  \n"
                                "$('T-WEEK').checked=true;             \n"
                            "}\n"
                        "}\n"
                        "show_tip_ex(2,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(2,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(2,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(2,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x038A)\n"
                    "{\n"
                        "if(Json.ID_0x0394==0){$('Device-BMS').checked=false;}else{$('Device-BMS').checked=true;}\n"
                        "var pr=0,fe=0;\n"
                        "if($('B-NONE').checked){pr=$('B-NONE').value;} \n"
                        "else if($('B-TYPE1').checked){pr=$('B-TYPE1').value;} \n"
                        "else if($('B-TYPE2').checked){pr=$('B-TYPE2').value;} \n"
                        "fe=Json.ID_0x038A;\n"
                        "if(pr!=fe){\n"
                            "if(Json.ID_0x038A==0)\n"
                            "{\n"
                                "$('Device-BMS').disabled=true;\n"
                                "$('B-NONE').checked=true;\n"
                                "$('B-TYPE1').checked=false;\n"
                                "$('B-TYPE2').checked=false;\n"
                            "}\n"
                            "else if(Json.ID_0x038A==1)\n"
                            "{\n"
                                "$('Device-BMS').disabled=false;\n"
                                "$('B-NONE').checked=false;\n"
                                "$('B-TYPE1').checked=true;\n"
                                "$('B-TYPE2').checked=false;\n"
                            "}\n"
                            "else if(Json.ID_0x038A==2)\n"
                            "{\n"
                                "$('Device-BMS').disabled=false;\n"
                                "$('B-NONE').checked=false;\n"
                                "$('B-TYPE1').checked=false;\n"
                                "$('B-TYPE2').checked=true;          \n"
                            "} \n"
                        "}\n"
                        "show_tip_ex(3,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(3,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(3,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(3,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x038B)\n"
                    "{\n"
                        "if(Json.ID_0x0392==0){$('Device-DCDC').checked=false;}else{$('Device-DCDC').checked=true;}\n"
                        "var pr=0,fe=0;\n"
                        "if($('DCDC-DIS').checked){pr=$('DCDC-DIS').value;}   \n"
                        "else if($('DCDC-OneWay').checked){pr=$('DCDC-OneWay').value;}\n"
                        "else if($('DCDC-BothWay').checked){pr=$('DCDC-BothWay').value;}\n"
                        "fe=Json.ID_0x038B;\n"
                        "if(pr!=fe)\n"
                        "{\n"
                            "if(Json.ID_0x038B==0)\n"
                            "{\n"
                                "$('Device-DCDC').disabled=true;\n"
                                "$('DCDC-DIS').checked=true;\n"
                                "$('DCDC-OneWay').checked=false;\n"
                                "$('DCDC-BothWay').checked=false;\n"
                            "}\n"
                            "else if(Json.ID_0x038B==1)\n"
                            "{\n"
                                "$('Device-DCDC').disabled=false;\n"
                                "$('DCDC-DIS').checked=false;\n"
                                "$('DCDC-OneWay').checked=true;\n"
                                "$('DCDC-BothWay').checked=false;            \n"
                            "} \n"
                            "else if(Json.ID_0x038B==2)\n"
                            "{\n"
                                "$('Device-DCDC').disabled=false;\n"
                                "$('DCDC-DIS').checked=false;\n"
                                "$('DCDC-OneWay').checked=false;\n"
                                "$('DCDC-BothWay').checked=true;            \n"
                            "} \n"
                        "}\n"
                        "show_tip_ex(4,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(4,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(4,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(4,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x038D)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('PCS-UART').checked){pr=$('PCS-UART').value;}    \n"
                        "else if($('PCS-NET').checked){pr=$('PCS-NET').value;}\n"
                        "fe=Json.ID_0x038D;\n"
                        "if(pr!=fe)\n"
                        "{\n"
                            "if(Json.ID_0x038D==0)\n"
                            "{\n"
                                "$('PCS-UART').checked=true;\n"
                                "$('PCS-NET').checked=false;\n"
                            "}\n"
                            "else if(Json.ID_0x038D==1)\n"
                            "{\n"
                                "$('PCS-UART').checked=false;\n"
                                "$('PCS-NET').checked=true;              \n"
                            "}  \n"
                        "}\n"
                        "show_tip_ex(6,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(6,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(6,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(6,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x038E)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('D-DIS').checked){pr=$('D-DIS').value;}    \n"
                        "else if($('D-EN').checked){pr=$('D-EN').value;}\n"
                        "fe=Json.ID_0x038E;\n"
                        "if(pr!=fe)\n"
                        "{\n"
                            "if(Json.ID_0x038E==0x55)\n"
                            "{\n"
                                "$('D-DIS').checked=true;\n"
                                "$('D-EN').checked=false;\n"
                            "}\n"
                            "else if(Json.ID_0x038E==0xAA)\n"
                            "{\n"
                                "$('D-DIS').checked=false;\n"
                                "$('D-EN').checked=true;              \n"
                            "}\n"
                        "}\n"
                        "show_tip_ex(7,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(7,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(7,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(7,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x0370)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('B-DIS').checked){pr=$('B-DIS').value;}    \n"
                        "else if($('B-EN').checked){pr=$('B-EN').value;}\n"
                        "fe=Json.ID_0x0370;\n"
                        "if(pr!=fe)\n"
                        "{\n"
                            "if(Json.ID_0x0370==0x55)\n"
                            "{\n"
                                "$('B-DIS').checked=true;\n"
                                "$('B-EN').checked=false; \n"
                            "}\n"
                            "else if(Json.ID_0x0370==0xAA)\n"
                            "{\n"
                                "$('B-DIS').checked=false;\n"
                                "$('B-EN').checked=true;              \n"
                            "}\n"
                        "}\n"
                        "show_tip_ex(8,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(8,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(8,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(8,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x0371)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('ALL-NORMAL').checked){pr=$('ALL-NORMAL').value;}    \n"
                        "else if($('PART-NORMAL').checked){pr=$('PART-NORMAL').value;}\n"
                        "fe=Json.ID_0x0371;\n"
                        "if(pr!=fe)\n"
                        "{\n"
                            "if(Json.ID_0x0371==0)\n"
                            "{\n"
                                "$('ALL-NORMAL').checked=true;\n"
                                "$('PART-NORMAL').checked=false; \n"
                            "}\n"
                            "else if(Json.ID_0x0371==1)\n"
                            "{\n"
                                "$('ALL-NORMAL').checked=false;\n"
                                "$('PART-NORMAL').checked=true;              \n"
                            "} \n"
                        "}\n"
                        "show_tip_ex(9,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(9,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(9,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(9,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x0387)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('PV-UART').checked){pr=$('PV-UART').value;}    \n"
                        "else if($('PV-NET').checked){pr=$('PV-NET').value;}\n"
                        "fe=Json.ID_0x0387;\n"
                        "if(pr!=fe)\n"
                        "{\n"
                            "if(Json.ID_0x0387==0)\n"
                            "{\n"
                                "$('PV-UART').checked=true;\n"
                                "$('PV-NET').checked=false;\n"
                            "}\n"
                            "else if(Json.ID_0x0387==1)\n"
                            "{\n"
                                "$('PV-UART').checked=false;\n"
                                "$('PV-NET').checked=true;              \n"
                            "} \n"
                        "}\n"
                        "show_tip_ex(10,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(10,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(10,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(10,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x036F)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('AMMETER-MODBUS').checked){pr=$('AMMETER-MODBUS').value;}    \n"
                        "else if($('AMMETER-DLT645').checked){pr=$('AMMETER-DLT645').value;}\n"
                        "fe=Json.ID_0x036F;\n"
                        "if(pr!=fe)\n"
                        "{\n"
                            "if(Json.ID_0x036F == 0)\n"
                            "{\n"
                                "$('AMMETER-MODBUS').checked=true;\n"
                                "$('AMMETER-DLT645').checked=false;\n"
                            "}\n"
                            "else if(Json.ID_0x036F == 1)\n"
                            "{\n"
                                "$('AMMETER-MODBUS').checked=false;\n"
                                "$('AMMETER-DLT645').checked=true;\n"
                            "} \n"
                        "}\n"
                        "show_tip_ex(11,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(11,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(11,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(11,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',url,true);\n"
            "xmlhttp.send();  \n"
        "}\n"
        "function doSubmit(obj)\n"
        "{\n"
            "var Device_PCS,Device_PV,Device_DCDC,Device_PVS,Device_BMS,Device_Ammeter,Device_RealTimeMonitor,Device_env,TimeSolt,BatteryType,DCDC_comm,Ammeter_comm,BMS_comm,PCS_comm,PV_comm,Ammeter_Protocol,BatteryControl,Distribution_En,Balance_EN,Offgrid_St,pcs_baud,pv_baud;\n"
"\n"
            "var URL='a_023.html?';\n"
            "switch(obj.id)\n"
            "{\n"
             "case 'btn1': \n"
 		           "if($('Device-PCS').checked){Device_PCS=1;}else{Device_PCS=0;}\n"
 		           "if($('Device-PV').checked){Device_PV=1;}else{Device_PV=0;}\n"
 		           "if($('Device-DCDC').checked){Device_DCDC=1;}else{Device_DCDC=0;}\n"
 		           "if($('Device-PVS').checked){Device_PVS=1;}else{Device_PVS=0;}\n"
 		           "if($('Device-BMS').checked){Device_BMS=1;}else{Device_BMS=0;} \n"
 		           "if($('Device-Ammeter').checked){Device_Ammeter=1;}else{Device_Ammeter=0;}\n"
                    "if($('Device-RealTimeMonitor').checked){Device_RealTimeMonitor=1;}else{Device_RealTimeMonitor=0;}\n"
                     //if($('Device-BetteryControl').checked){BatteryControl=1;}else{BatteryControl=0;}
                    "if($('Device-ENV').checked){Device_env=1;}else{Device_env=0;}\n"
 		           "URL=URL+'&0x0390='+Device_PCS;\n"
 		           "URL=URL+'&0x0391='+Device_PV;\n"
 		           "URL=URL+'&0x0392='+Device_DCDC;\n"
 		           "URL=URL+'&0x0393='+Device_PVS;\n"
 		           "URL=URL+'&0x0394='+Device_BMS;\n"
 		           "URL=URL+'&0x0395='+Device_Ammeter;\n"
                    "URL=URL+'&0x0396='+Device_RealTimeMonitor;\n"
                    "URL=URL+'&0x0397='+BatteryControl;\n"
                    "URL=URL+'&0x039A='+Device_env;\n"
                    "readBack=0x0390;\n"
             "break;\n"
                "case 'btn2': \n"
                    "if($('T-DIS').checked){TimeSolt=$('T-DIS').value;}\n"
                    "else if($('T-HOUR').checked){TimeSolt=$('T-HOUR').value;}\n"
                    "else if($('T-WEEK').checked){TimeSolt=$('T-WEEK').value;}\n"
                    "URL=URL+'&0x0389='+TimeSolt;\n"
                    "readBack=0x0389;  \n"
                "break;\n"
             "case 'btn3': \n"
                    "var bms_show;\n"
        			"if($('B-NONE').checked){BatteryType=$('B-NONE').value;bms_show=0;}	\n"
 				"else if($('B-TYPE1').checked){BatteryType=$('B-TYPE1').value;bms_show=1;} \n"
 				"else if($('B-TYPE2').checked){BatteryType=$('B-TYPE2').value;bms_show=1;} \n"
 				"URL=URL+'&0x038A='+BatteryType+'&0x0394='+bms_show;\n"
                    "readBack=0x038A; \n"
             "break;\n"
             "case 'btn4': \n"
                    "var dcdc_show;\n"
  				"if($('DCDC-DIS').checked){DCDC_comm=$('DCDC-DIS').value;dcdc_show=0;}	\n"
 				"else if($('DCDC-OneWay').checked){DCDC_comm=$('DCDC-OneWay').value;dcdc_show=1;}\n"
                    "else if($('DCDC-BothWay').checked){DCDC_comm=$('DCDC-BothWay').value;dcdc_show=1;}\n"
             	"URL=URL+'&0x038B='+DCDC_comm+'&0x0392='+dcdc_show;\n"
                    "readBack=0x038B; \n"
             "break;\n"
             "case 'btn5': \n"
             "break;\n"
             "case 'btn6': \n"
 			 	"if($('PCS-UART').checked){PCS_comm=$('PCS-UART').value;}	\n"
 				"else if($('PCS-NET').checked){PCS_comm=$('PCS-NET').value;}\n"
 				"URL=URL+'&0x038D='+PCS_comm;\n"
                    "readBack=0x038D; \n"
             "break;\n"
                "case 'btn7':\n"
                    "if($('D-DIS').checked){Distribution_En=$('D-DIS').value;}    \n"
                    "else if($('D-EN').checked){Distribution_En=$('D-EN').value;}\n"
                    "URL=URL+'&0x038E='+Distribution_En;\n"
                    "readBack=0x038E; \n"
                "break;\n"
                "case 'btn8':\n"
                    "if($('B-DIS').checked){Balance_EN=$('B-DIS').value;}    \n"
                    "else if($('B-EN').checked){Balance_EN=$('B-EN').value;}\n"
                    "URL=URL+'&0x0370='+Balance_EN;\n"
                    "readBack=0x0370; \n"
                "break;\n"
                "case 'btn9':\n"
                    "if($('ALL-NORMAL').checked){Offgrid_St=$('ALL-NORMAL').value;}    \n"
                    "else if($('PART-NORMAL').checked){Offgrid_St=$('PART-NORMAL').value;}\n"
                    "URL=URL+'&0x0371='+Offgrid_St;\n"
                    "readBack=0x0371; \n"
                "break;\n"
                "case 'btn10': \n"
                    "if($('PV-UART').checked){PV_comm=$('PV-UART').value;}    \n"
                    "else if($('PV-NET').checked){PV_comm=$('PV-NET').value;}\n"
                    "URL=URL+'&0x0387='+PV_comm;\n"
                    "readBack=0x0387; \n"
                "break;\n"
                "case 'btn11': \n"
                    "if($('AMMETER-MODBUS').checked){Ammeter_Protocol=$('AMMETER-MODBUS').value;}    \n"
                    "else if($('AMMETER-DLT645').checked){Ammeter_Protocol=$('AMMETER-DLT645').value;}\n"
                    "URL=URL+'&0x036F='+Ammeter_Protocol;\n"
                    "readBack=0x036F; \n"
                "break;\n"
             "default:break;\n"
            "}\n"
            "URL=URL+'&time='+Math.random();\n"
             //alert(URL);
"\n"
            "function success()\n"
            "{\n"
     		"setTimeout('read_back('+readBack+')', 100);         			\n"
            "}\n"
"\n"
             //测试
             //success();  
"\n"
 		"sendHttpReq(URL, success);\n"
        "}\n"
        "function doSetValue(Json)\n"
        "{\n"
             //从设备设置
            "if(Json.ID_0x0390==0){$('Device-PCS').checked=false;}else{$('Device-PCS').checked=true;}\n"
            "if(Json.ID_0x0391==0){$('Device-PV').checked=false;}else{$('Device-PV').checked=true;}\n"
            "if(Json.ID_0x0392==0){$('Device-DCDC').checked=false;}else{$('Device-DCDC').checked=true;}\n"
            "if(Json.ID_0x0393==0){$('Device-PVS').checked=false;}else{$('Device-PVS').checked=true;}\n"
            "if(Json.ID_0x0394==0){$('Device-BMS').checked=false;}else{$('Device-BMS').checked=true;}\n"
            "if(Json.ID_0x0395==0){$('Device-Ammeter').checked=false;}else{$('Device-Ammeter').checked=true;}\n"
            "if(Json.ID_0x0396==0){$('Device-RealTimeMonitor').checked=false;}else{$('Device-RealTimeMonitor').checked=true;}\n"
             //if(Json.ID_0x0397==0){$('Device-BetteryControl').checked=false;}else{$('Device-BetteryControl').checked=true;}
            "if(Json.ID_0x039A==0){$('Device-ENV').checked=false;}else{$('Device-ENV').checked=true;}\n"
"\n"
         	//分段控制使能
         "if(Json.ID_0x0389==0)\n"
         "{\n"
         	"$('T-DIS').checked=true;\n"
         	"$('T-HOUR').checked=false;\n"
                "$('T-WEEK').checked=false;\n"
         "}\n"
         "else if(Json.ID_0x0389==1)\n"
         "{\n"
          	"$('T-DIS').checked=false;\n"
         	"$('T-HOUR').checked=true;\n"
                "$('T-WEEK').checked=false;      		\n"
         "}\n"
            "else if(Json.ID_0x0389==2)\n"
            "{\n"
                "$('T-DIS').checked=false;\n"
                "$('T-HOUR').checked=false;  \n"
                "$('T-WEEK').checked=true;             \n"
            "}             \n"
"\n"
         	//电池类型
         "if(Json.ID_0x038A==0)\n"
         "{\n"
                "$('Device-BMS').disabled=true;\n"
         	"$('B-NONE').checked=true;\n"
         	"$('B-TYPE1').checked=false;\n"
         	"$('B-TYPE2').checked=false;\n"
         "}\n"
         "else if(Json.ID_0x038A==1)\n"
         "{\n"
                "$('Device-BMS').disabled=false;\n"
         	"$('B-NONE').checked=false;\n"
         	"$('B-TYPE1').checked=true;\n"
         	"$('B-TYPE2').checked=false;\n"
         "}\n"
         "else if(Json.ID_0x038A==2)\n"
         "{\n"
                "$('Device-BMS').disabled=false;\n"
         	"$('B-NONE').checked=false;\n"
         	"$('B-TYPE1').checked=false;\n"
         	"$('B-TYPE2').checked=true;   		\n"
         "}  \n"
"\n"
         	//DCDC类型
         "if(Json.ID_0x038B==0)\n"
         "{\n"
                "$('Device-DCDC').disabled=true;\n"
         	"$('DCDC-DIS').checked=true;\n"
         	"$('DCDC-OneWay').checked=false;\n"
                "$('DCDC-BothWay').checked=false;\n"
         "}\n"
         "else if(Json.ID_0x038B==1)\n"
         "{\n"
                "$('Device-DCDC').disabled=false;\n"
                "$('DCDC-DIS').checked=false;\n"
                "$('DCDC-OneWay').checked=true;\n"
                "$('DCDC-BothWay').checked=false;    		\n"
         "} \n"
            "else if(Json.ID_0x038B==2)\n"
            "{\n"
                "$('Device-DCDC').disabled=false;\n"
                "$('DCDC-DIS').checked=false;\n"
                "$('DCDC-OneWay').checked=false;\n"
                "$('DCDC-BothWay').checked=true;            \n"
            "} \n"
"\n"
          	//PCS通讯模式
         "if(Json.ID_0x038D==0)\n"
         "{\n"
         	"$('PCS-UART').checked=true;\n"
         	"$('PCS-NET').checked=false;\n"
         "}\n"
         "else if(Json.ID_0x038D==1)\n"
         "{\n"
                "$('PCS-UART').checked=false;\n"
                "$('PCS-NET').checked=true;      		\n"
         "}  \n"
"\n"
             //配电使能
            "if(Json.ID_0x038E==0x55)\n"
            "{\n"
                "$('D-DIS').checked=true;\n"
                "$('D-EN').checked=false;\n"
            "}\n"
            "else if(Json.ID_0x038E==0xAA)\n"
            "{\n"
                "$('D-DIS').checked=false;\n"
                "$('D-EN').checked=true;              \n"
            "}\n"
"\n"
             //均衡使能
            "if(Json.ID_0x0370==0x55)\n"
            "{\n"
                "$('B-DIS').checked=true;\n"
                "$('B-EN').checked=false; \n"
            "}\n"
            "else if(Json.ID_0x0370==0xAA)\n"
            "{\n"
                "$('B-DIS').checked=false;\n"
                "$('B-EN').checked=true;              \n"
            "}\n"
"\n"
             //PCS离网启动策略
            "if(Json.ID_0x0371==0)\n"
            "{\n"
                "$('ALL-NORMAL').checked=true;\n"
                "$('PART-NORMAL').checked=false; \n"
            "}\n"
            "else if(Json.ID_0x0371==1)\n"
            "{\n"
                "$('ALL-NORMAL').checked=false;\n"
                "$('PART-NORMAL').checked=true;              \n"
            "} \n"
"\n"
             //PV通讯模式
            "if(Json.ID_0x0387==0)\n"
            "{\n"
                "$('PV-UART').checked=true;\n"
                "$('PV-NET').checked=false;\n"
            "}\n"
            "else if(Json.ID_0x0387==1)\n"
            "{\n"
                "$('PV-UART').checked=false;\n"
                "$('PV-NET').checked=true;              \n"
            "}    \n"
"\n"
             //电表协议
            "if(Json.ID_0x036F == 0)\n"
            "{\n"
                "$('AMMETER-MODBUS').checked=true;\n"
                "$('AMMETER-DLT645').checked=false;\n"
            "}\n"
            "else if(Json.ID_0x036F == 1)\n"
            "{\n"
                "$('AMMETER-MODBUS').checked=false;\n"
                "$('AMMETER-DLT645').checked=true;\n"
            "}       \n"
        "}\n"
    "</script>\n"
"</html>\n"
};
#endif
