#ifndef _HTML_H_021_H_
#define _HTML_H_021_H_
static const char h_021[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
"<head>\n"
"<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
"<script src='j_001.js' type='text/javascript'></script>\n"
"<style type='text/css'>\n"
 "body{margin:0;padding:0;background-color:#fff;font-family:'微软雅黑',Arial,'宋体',sans-serif;}\n"
 "#menu{margin:5px 0 0 0;width:245px;float:right;}\n"
 ".menu_cn{line-height:36px;padding-left:65px;width:180px;height:36px;color:#000;background-color:#F58E03;font-weight:bold;font-size:16px;;}\n"
 ".submenu_cn{line-height:32px;padding-left:65px;width:180px;height:32px;color:#000;background-color:#eee;font-weight:normal;font-size:14px;}\n"
 ".menu_en{line-height:36px;padding-left:45px;width:200px;height:36px;color:#000;background-color:#F58E03;font-weight:bold;font-size:16px;}\n"
 ".submenu_en{line-height:32px;padding-left:45px;width:200px;height:32px;color:#000;background-color:#eee;font-weight:normal;font-size:14px;}\n"
 ".color{background-color:#F58E03;}\n"
 ".change_color{background-color:#007B3E;}\n"
 ".r1{margin:0 5px;height:1px;overflow:hidden;}\n"
 ".r2{margin:0 3px;height:1px;overflow:hidden;}\n"
 ".r3{margin:0 2px;height:1px;overflow:hidden;}\n"
 ".r4{margin:0 1px;height:2px;overflow:hidden;}\n"
 ".blank{height:1px;overflow:hidden;background-color:#fff;width:213px;}\n"
"</style>\n"
"<script language='javascript' type='text/javascript'>\n"
 "var $=function(o){return document.getElementById(o);};\n"
 "var current_id='h_022';\n"
 "var language=1;\n"
 "var Json;\n"
 "var HaveInitH022=false;\n"
 "var lang=\n"
 "{\n"
 	"N01:['系统配置','System Config'],\n"
 	"N02:['基本设置','Basic Settings'],\n"
 	"N03:['功能设置','Function Settings'],\n"
 	"N04:['运行设置','Running Settings'],\n"
 	"N05:['专家设置','Proficient Settings'],\n"
 	"N06:['高级设置','Advanced Settings'],\n"
 	"N07:['辅助设置','Auxiliary Settings']\n"
 "};\n"
 "var temp1=new Array('xtpz');\n"
 "var temp2=new Array('h_022','h_023','h_024','h_030','h_37');\n"
 "function change_color(obj)\n"
 "{\n"
 	"if(current_id!=obj.id)\n"
 	"{\n"
 		"for(var i=1;i<=1;i++)\n"
 		"{\n"
 			"if(obj.id=='xtpz')\n"
 			"$('top'+i).className='r'+i+' change_color';\n"
 		"}\n"
 		"obj.style.background='#007b3e';\n"
 		"obj.style.color='#fff';\n"
 	"}\n"
 "}\n"
 "function resume_color(obj)\n"
 "{\n"
 	"if(current_id!=obj.id)\n"
 	"{\n"
 		"for(var i=1;i<=1;i++)\n"
 		"{\n"
 			"if(obj.id=='xtpz')\n"
 			"$('top'+i).className='r'+i+' color';\n"
 		"}\n"
 		"switch(obj.id)\n"
 		"{\n"
 			"case 'xtpz':\n"
 				"obj.style.background='#F58E03';\n"
 				"obj.style.color='#000';\n"
 			"break;\n"
 			"default:\n"
 				"obj.style.background='#eee';\n"
 				"obj.style.color='#000';\n"
 			"break;\n"
 		"}\n"
 	"}\n"
 "}\n"
 "function showurl(obj)\n"
 "{\n"
 	"$('h_022').style.background='#eeeeee';\n"
 	"$('h_022').style.color='#000';\n"
 	"$('h_023').style.background='#eeeeee';\n"
 	"$('h_023').style.color='#000';\n"
 	"$('h_024').style.background='#eeeeee';\n"
 	"$('h_024').style.color='#000';\n"
 	"$('h_030').style.background='#eeeeee';\n"
 	"$('h_030').style.color='#000'\n"
 	"$('h_037').style.background='#eeeeee';\n"
 	"$('h_037').style.color='#000'\n"
 	"$('h_044').style.background='#eeeeee';\n"
 	"$('h_044').style.color='#000'\n"
 	"obj.style.background='#007B3E';\n"
 	"obj.style.color='#fff';\n"
 	"for(var i=1;i<=1;i++)\n"
 	"{\n"
 		"$('btm'+i).className='r'+i+' color';\n"
 	"}\n"
 	"current_id=obj.id;\n"
 	"var SURL='';\n"
"\n"
 	"if(document.all)\n"
 	"{\n"
 			//IE浏览器  '.html' 改为 '.IExx'
 		"SURL=current_id+'.html';\n"
 	"}\n"
 	"else\n"
 	"{\n"
 			//非IE浏览器 '.html' 改为 '.NIEx'
 		"SURL=current_id+'.html';\n"
 	"}\n"
 		"top.main.location.href=SURL;\n"
 "}\n"
 "function Init()\n"
 "{\n"
        "var URL='s_021.html?time='+Math.random();\n"
        "var xmlhttp;\n"
        "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
        "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
        "xmlhttp.onreadystatechange=function()\n"
        "{\n"
            "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
            "{\n"
 			"var num,temp;\n"
"\n"
 			"eval('Json='+xmlhttp.responseText);\n"
"\n"
 			"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
 			"if(language==0)\n"
 			"{\n"
 				"for(var i=0;i<temp1.length;i++)\n"
 				"{\n"
 					"$(temp1[i]).className='menu_cn';\n"
 				"}\n"
 				"$('h_022').className='submenu_cn';\n"
 				"$('h_023').className='submenu_cn';\n"
 				"$('h_024').className='submenu_cn';\n"
 				"$('h_030').className='submenu_cn';\n"
 				"$('h_037').className='submenu_cn';\n"
 				"$('h_044').className='submenu_cn';\n"
 			"}\n"
 			"else if(language==1)\n"
 			"{\n"
 				"for(var i=0;i<temp1.length;i++)\n"
 				"{\n"
 					"$(temp1[i]).className='menu_en';\n"
 				"}\n"
 				"$('h_022').className='submenu_en';\n"
 				"$('h_023').className='submenu_en';\n"
 				"$('h_024').className='submenu_en';\n"
 				"$('h_030').className='submenu_en';\n"
 				"$('h_037').className='submenu_en';\n"
 				"$('h_044').className='submenu_en';\n"
 			"}\n"
 			"\n"
 			"lang_init_ex(1,7);\n"
"\n"
 			"if(HaveInitH022==false)\n"
 			"{\n"
 				"$('h_022').style.background='#007B3E';\n"
 				"$('h_022').style.color='#fff';\n"
 			"}\n"
 	    "}\n"
        "};\n"
        "xmlhttp.open('GET',URL,true);\n"
        "xmlhttp.send();	\n"
 	"if(HaveInitH022==false)\n"
 	"{\n"
 		"setTimeout(\"showurl($('h_022'))\",500);\n"
 		"HaveInitH022=true;\n"
 	"}\n"
 "}\n"
"</script>\n"
"</head>\n"
 "<body onload='Init();'>\n"
 	"<div id='menu'>\n"
 		"<div id='top1' class='r1 color'></div>\n"
 		"<div id='top2' class='r2 color'></div>\n"
 		"<div id='top3' class='r3 color'></div>\n"
 		"<div id='top4' class='r4 color'></div>\n"
 		"<div id='xtpz' class='menu_en' style='cursor:default;'><span id='N01'></span></div>\n"
 		"<div class='blank'></div>\n"
 		"<div id='h_022' class='submenu_en' style='cursor:pointer;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N02'></span></div>\n"
 		"<div class='blank'></div>\n"
 		"<div id='h_023' class='submenu_en' style='cursor:pointer; display:block;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N03'></span></div>\n"
 		"<div id='h_023_blank' class='blank'></div>			\n"
 		"<div id='h_024' class='submenu_en' style='cursor:pointer; display:block;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N04'></span></div>\n"
 		"<div id='h_024_blank' class='blank'></div>\n"
 		"<div id='h_030' class='submenu_en' style='cursor:pointer; display:block;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N05'></span></div>\n"
 		"<div id='h_030_blank' class='blank'></div>\n"
 		"<div id='h_037' class='submenu_en' style='cursor:pointer; display:block;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N06'></span></div>\n"
 		"<div id='h_037_blank' class='blank'></div>\n"
 		"<div id='h_044' class='submenu_en' style='cursor:pointer; display:block;' onmousemove='change_color(this)' onmouseout='resume_color(this)' onclick='showurl(this)'><span id='N07'></span></div>\n"
 		"<div id='h_044_blank' class='blank'></div>\n"
 		"<div class='menu_en' style='cursor:pointer;'<span></span></div>\n"
 		"<div id='btm4' class='r4 color'></div>\n"
 		"<div id='btm3' class='r3 color'></div>\n"
 		"<div id='btm2' class='r2 color'></div>\n"
 		"<div id='btm1' class='r1 color'></div>\n"
 	"</div>\n"
 	"<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
 "</body>\n"
"</html>\n"
};
#endif
