#ifndef _HTML_H_038_H_
#define _HTML_H_038_H_
static const char h_038[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
	"<meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'/>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
        "<script src='j_001.js' type='text/javascript'></script>\n"
        "<style type='text/css'>\n"
        "tr{height:27px;}\n"
        ".td1{text-align:left;padding-left:40px;}\n"
        ".td2{text-align:right;padding-right:5px;}\n"
        ".td3{text-align:right;padding-right:40px;}\n"
        ".backcolor{background-color:#F00;}\n"
        ".color1{color:#F00;font-weight: bold;}\n"
        ".color2{color:#888;font-weight: bold;}\n"
        ".color3{color:#444;font-weight: bold;}\n"
        "</style>\n"
    "</head>\n"
    "<script type=\"text/javascript\" src=\"jquery.min.js\"></script>\n"
    "<body onload='Init();'>\n"
        "<div style='width:100%;' id='fault_code'></div>\n"
        "<div class='blank'></div>\n"
        "<div class='title' style='width:90%;'>\n"
        "<div class='subtitle'>\n"
            "<div class='r1 backcolor'></div>\n"
            "<div class='r2 backcolor'></div>\n"
            "<div class='r3 backcolor'></div>\n"
            "<div class='r4 backcolor'></div>\n"
            "<div class='content backcolor subcontent'>\n"
                "<span id='N060'></span>\n"
            "</div>\n"
            "<div class='r4 backcolor'></div>\n"
            "<div class='r3 backcolor'></div>\n"
            "<div class='r2 backcolor'></div>\n"
            "<div class='r1 backcolor'></div>\n"
            "<div class='line_short'></div>\n"
        "</div>\n"
        "</div>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST0'></span></td>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST1'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST2'></span></td>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST6'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST8'></span></td>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST15'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST16'></span></td>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST17'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST18'></span></td>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST19'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST20'></span></td>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST23'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='SF0'></span></td>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='SF1'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='SF2'></span></td>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='SF3'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='SF4'></span></td>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='SF5'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='SF6'></span></td>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='SF7'></span></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='btm_blank'></div>\n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var language=0;\n"
        "var Json;\n"
        "var lang=\n"
        "{		\n"
            "N060:['故障信息','Fault Information'],\n"
            "N061:['故障&nbsp;','Fault&nbsp;'],\n"
            "N062:['储能逆变器故障','PCS Fault'],\n"
            "N063:['储能逆变器通讯故障','PCS Comm Fault'],\n"
            "N064:['储能逆变器地址冲突','PCS Address Conflict'],\n"
            "N065:['',''],\n"
            "N066:['光伏逆变器故障','PV Fault'],\n"
            "N067:['光伏逆变器通讯故障','PV Comm Fault'],\n"
            "N068:['光伏逆变器地址冲突','PV Address Conflict'],\n"
            "N069:['',''],\n"
            "N070:['接触器故障','Contactor Fault'],\n"
            "N071:['',''],\n"
            "N072:['',''],\n"
            "N073:['',''],\n"
            "N074:['',''],\n"
            "N075:['',''],\n"
            "N076:['',''],\n"
            "N077:['自检失败','Self Check Fail'],\n"
            "N078:['自检超时','Self Check Timeout'],\n"
            "N079:['微网供电启动超时','Grid Start Timeout'],\n"
            "N080:['微网供电启动失败','Grid Start Fail'],\n"
            "N081:['电网供电启动超时','Micro Start Timeout'],\n"
            "N082:['电网供电启动失败','Micro Start Fail'],\n"
            "N083:['',''],\n"
            "N084:['',''],\n"
            "N085:['停机超时','Stop Timeout'],\n"
            "N086:['',''],\n"
            "N087:['',''],\n"
            "N088:['',''],\n"
            "N089:['',''],\n"
            "N090:['',''],\n"
            "N091:['',''],\n"
            "N092:['',''],\n"
            "N093:['',''],\n"
            "N094:['节点1故障','Node 1 Fault'],\n"
            "N095:['节点2故障','Node 2 Fault'],\n"
            "N096:['节点3故障','Node 3 Fault'],\n"
            "N097:['节点4故障','Node 4 Fault'],\n"
            "N098:['节点5故障','Node 5 Fault'],\n"
            "N099:['节点6故障','Node 6 Fault'],\n"
            "N100:['节点7故障','Node 7 Fault'],\n"
            "N101:['节点8故障','Node 8 Fault'],\n"
            "N102:['',''],\n"
            "N103:['',''],\n"
            "N104:['',''],\n"
            "N105:['',''],\n"
            "N106:['',''],\n"
            "N107:['',''],\n"
            "N108:['',''],\n"
            "N109:['',''],\n"
            "N110:['',''],\n"
            "N111:['',''],\n"
            "N112:['',''],\n"
            "N113:['',''],\n"
            "N114:['',''],\n"
            "N115:['',''],\n"
            "N116:['',''],\n"
            "N117:['',''],\n"
            "N118:['',''],\n"
            "N119:['',''],\n"
            "N120:['',''],\n"
            "N121:['',''],\n"
            "N122:['',''],\n"
            "N123:['',''],\n"
            "N124:['',''],\n"
            "N125:['','']\n"
        "};\n"
"\n"
        "function jquery_ajax()\n"
        "{\n"
            "var i=0;\n"
            "var Fcode=new Array(2);\n"
"\n"
            "$.ajax({\n"
                "url:\"s_038.html?\",\n"
                "type:\"get\",\n"
                "contentType:\"application/json;charset=utf-8\",\n"
                "data:JSON.stringify({\n"
                    "\"time\":Math.random()\n"
                "}),\n"
                "dataType:\"json\",\n"
                "success:function(data){\n"
                    "Json = data;         \n"
                    "if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                    "document.getElementById('N060').innerHTML=lang.N060[language];\n"
                    "document.getElementById('ST0').innerHTML=lang.N062[language];\n"
                    "document.getElementById('ST1').innerHTML=lang.N063[language];\n"
                    "document.getElementById('ST2').innerHTML=lang.N064[language];\n"
                     //document.getElementById('ST5').innerHTML=lang.N067[language];
                    "document.getElementById('ST6').innerHTML=lang.N068[language];\n"
                    "document.getElementById('ST8').innerHTML=lang.N070[language];\n"
                    "document.getElementById('ST15').innerHTML=lang.N077[language];\n"
                    "document.getElementById('ST16').innerHTML=lang.N078[language];\n"
                    "document.getElementById('ST17').innerHTML=lang.N079[language];\n"
                    "document.getElementById('ST18').innerHTML=lang.N080[language];\n"
                    "document.getElementById('ST19').innerHTML=lang.N081[language];\n"
                    "document.getElementById('ST20').innerHTML=lang.N082[language];\n"
                    "document.getElementById('ST23').innerHTML=lang.N085[language];\n"
"\n"
                    "document.getElementById('SF0').innerHTML=lang.N094[language];\n"
                    "document.getElementById('SF1').innerHTML=lang.N095[language];\n"
                    "document.getElementById('SF2').innerHTML=lang.N096[language];\n"
                    "document.getElementById('SF3').innerHTML=lang.N097[language];\n"
                    "document.getElementById('SF4').innerHTML=lang.N098[language];\n"
                    "document.getElementById('SF5').innerHTML=lang.N099[language];\n"
                    "document.getElementById('SF6').innerHTML=lang.N100[language];\n"
                    "document.getElementById('SF7').innerHTML=lang.N101[language];\n"
"\n"
                    "Fcode[0]=Json.ID_0x0152;\n"
                    "Fcode[1]=Json.ID_0x0153;\n"
"\n"
                    "for(i=0;i<32;i++)\n"
                    "{\n"
                        "if(i==0 || i==1 || i==2 || i==6 || i==8 || i==15 || i==16 || i==17 || i==18 || i==19 || i==20 || i==23)\n"
                        "{\n"
                            "if(((Fcode[0]>>i)&1)==1){\n"
                                "eval('document.getElementById(\\'ST'+i+'\\').className=\\'color1\\';');\n"
                            "}else{\n"
                                "eval('document.getElementById(\\'ST'+i+'\\').className=\\'color3\\';');\n"
                            "}\n"
                        "}\n"
                    "}\n"
                    "for(i=0;i<32;i++)\n"
                    "{\n"
                        "if(i==0 || i==1 || i==2 || i==3 || i==4 || i==5 || i==6 || i==7)\n"
                        "{\n"
                            "if(((Fcode[1]>>i)&1)==1){\n"
                                "eval('document.getElementById(\\'SF'+i+'\\').className=\\'color1\\';');\n"
                            "}else{\n"
                                "eval('document.getElementById(\\'SF'+i+'\\').className=\\'color3\\';');\n"
                            "}\n"
                        "}\n"
                    "}\n"
                "}\n"
            "});            \n"
        "}\n"
        "window.onresize = function()\n"
        "{\n"
            "var bodywidth=document.body.clientWidth;\n"
            "if(bodywidth<867){document.body.style.width=\"867px\";}else{document.body.style.width=\"auto\";}\n"
        "} \n"
        "function Init()\n"
        "{\n"
            "jquery_ajax();\n"
            "setInterval('jquery_ajax()',1000);\n"
        "}\n"
        "function pad(num,n)\n"
        "{\n"
            "var len=num.toString().length;\n"
            "while(len++<n)num='0'+num;\n"
            "return num;\n"
        "}    \n"
    "</script>\n"
"</html>\n"
};
#endif
