#ifndef _HTML_H_037_H_
#define _HTML_H_037_H_
static const char h_037[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
 "<head>\n"
 	"<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
 	"<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
 	"<script type='text/javascript'>\n"
            "var $=function(o){return document.getElementById(o);};\n"
            "function lang_init_ex(st,end){for(var i=st;i<=end;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
            "function show_tip_ex(id, obj){eval('$(\\'tip'+id+'\\').innerHTML=obj;');}\n"
            "function show_T(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
                "str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_sT(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_sT_ex(tid, id)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' id='\"+id+\"' style='display:none;width:90%'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function sendHttpReq(url, successFn)\n"
            "{\n"
                 //alert(url);   
                "var xmlhttp;\n"
                "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                "xmlhttp.onreadystatechange=function()\n"
                "{\n"
                    "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                    "{\n"
                        "if(xmlhttp.responseText=='1'){successFn();}\n"
                    "}\n"
                "};\n"
                "xmlhttp.open('GET',url,true);\n"
                "xmlhttp.send();\n"
            "}\n"
        "</script>\n"
 	"<style type='text/css'>\n"
 		"tr{height:27px;}\n"
 		".td1{padding-left:40px;text-align:left;}\n"
 		".td2{text-align:left;}\n"
 		".td3{padding-right:40px;text-align:right;}\n"
 		".txt{width:100px;text-align:right;}\n"
 	"</style>\n"
 "</head>\n"
 "<body onload='Init()'>\n"
 	"<script type='text/javascript'>\n"
 		"show_T('N01');\n"
 		"show_sT('N02');\n"
 	"</script>\n"
 	"<table width='90%' border='0'>\n"
 		"<tr>\n"
 			"<td width='30%' class='td1 odd'><input name='Peak-Sel' type='radio' value='85' id='Peak-DIS'/><span id='N03'></span></td>\n"
 			"<td width='30%' class='td1 odd'><input name='Peak-Sel' type='radio' value='170' id='Peak-EN'/><span id='N04'></span></td>\n"
 		"</tr>\n"
 	  "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip1'>&nbsp;</span></td>\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn1' style='display:block;'><span id='N400'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
 	"<div class='line_long'></div>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N05');\n"
        "</script>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='30%' class='td1 odd'><input name='AcLimite-Sel' type='radio' value='85' id='AcLimite-DIS'/><span id='N06'></span></td>\n"
                "<td width='30%' class='td1 odd'><input name='AcLimite-Sel' type='radio' value='170' id='AcLimite-EN'/><span id='N07'></span></td>\n"
            "</tr>\n"
       "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip2'>&nbsp;</span></td>\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn2' style='display:block;'><span id='N401'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N08');\n"
        "</script>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='30%' class='td1 odd'><input name='Smooth-Sel' type='radio' value='85' id='Smooth-DIS'/><span id='N09'></span></td>\n"
                "<td width='30%' class='td1 odd'><input name='Smooth-Sel' type='radio' value='170' id='Smooth-EN'/><span id='N10'></span></td>\n"
            "</tr>\n"
       "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip3'>&nbsp;</span></td>\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn3' style='display:block;'><span id='N402'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N11');\n"
        "</script>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='30%' class='td1 odd'><input name='FM-Sel' type='radio' value='85' id='FM-DIS'/><span id='N12'></span></td>\n"
                "<td width='30%' class='td1 odd'><input name='FM-Sel' type='radio' value='170' id='FM-EN'/><span id='N13'></span></td>\n"
            "</tr>\n"
       "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even tip'><span id='tip4'>&nbsp;</span></td>\n"
                "<td width='50%' align='right' class='even'><button class='btn' onclick='doSubmit(this)' id='btn4' style='display:block;'><span id='N403'>Save</span></button></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
 	"<div class='blank'></div>\n"
 	"<div class='btm_blank'></div>\n"
 	"<div id='trans'></div>\n"
 	"<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
 "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var language=0;\n"
        "var Json;	 \n"
        "var lang=\n"
        "{\n"
            "N01:['高级设置','Advanced Settings'],\n"
            "N02:['削峰填谷','Peak Load Shifting'],\n"
 		"N03:['禁止','DISABLE'],\n"
 		"N04:['允许','ENABLE'],\n"
            "N05:['交流限发','AC Limited Produce'],\n"
            "N06:['禁止','DISABLE'],\n"
            "N07:['允许','ENABLE'],\n"
            "N08:['输出平滑','Ramp Rate Control'],\n"
            "N09:['禁止','DISABLE'],\n"
            "N10:['允许','ENABLE'],\n"
            "N11:['调频','FR'],  \n"
            "N12:['禁止','DISABLE'],\n"
            "N13:['允许','ENABLE'],\n"
"\n"
            "N400:['设&nbsp;&nbsp;置','Set'], \n"
            "N401:['设&nbsp;&nbsp;置','Set'], \n"
            "N402:['设&nbsp;&nbsp;置','Set'],           \n"
            "N403:['设&nbsp;&nbsp;置','Set'], \n"
"\n"
            "N499:['设置成功！','Set successfully!'],\n"
            "N500:['设置失败！','Set Failed!'],\n"
            "N501:['格式错误！','Format error!'],\n"
            "N502:['范围错误！','Range error!']    \n"
        "};\n"
        "function Init()\n"
        "{\n"
            "var URL='s_037.html?0x0000&time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{             \n"
                    "eval('Json='+xmlhttp.responseText);				\n"
"\n"
     			"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
"\n"
                     //初始化语言
                    "lang_init_ex(1,13); \n"
     			"lang_init_ex(400,403);       \n"
     			"doSetValue(Json);\n"
"\n"
     				//user用户不能配置，install用户可以配置
     			"if(Json.ID_0x0282==0x11)\n"
     			"{\n"
     				"$('btn1').style.display='none';\n"
                        "$('btn2').style.display='none';\n"
                        "$('btn2').style.display='none';\n"
     				"$('trans').style.zIndex=9999;\n"
     			"}\n"
     			"else\n"
     			"{\n"
     				"$('btn1').style.display='inline';\n"
                        "$('btn2').style.display='inline';\n"
                        "$('btn3').style.display='inline';\n"
     				"$('trans').style.zIndex=-9999;\n"
     			"}\n"
 			    "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}\n"
        "function read_back(addr)\n"
        "{\n"
            "var url='s_037.html?';\n"
            "url=url+'&time='+Math.random();\n"
"\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText); \n"
                    "if(addr == 0x03B1)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('Peak-DIS').checked){pr=$('Peak-DIS').value;}\n"
                        "else if($('Peak-EN').checked){pr=$('Peak-EN').value;} \n"
                        "fe=Json.ID_0x03B1;\n"
                        "if(pr!=fe)\n"
                        "{\n"
                            "if(Json.ID_0x03B1==0x55)\n"
                            "{\n"
                                "$('Peak-DIS').checked=true;\n"
                                "$('Peak-EN').checked=false;\n"
                            "}\n"
                            "else if(Json.ID_0x03B1==0xAA)\n"
                            "{\n"
                                "$('Peak-DIS').checked=false;\n"
                                "$('Peak-EN').checked=true;         \n"
                            "}\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "if(Json.ID_0x03B1==0xAA)\n"
                            "{\n"
                                "$('AcLimite-DIS').checked=true;\n"
                                "$('AcLimite-EN').checked=false; \n"
                                "$('Smooth-DIS').checked=true;\n"
                                "$('Smooth-EN').checked=false;    \n"
                                "$('FM-DIS').checked=true;\n"
                                "$('FM-EN').checked=false;    \n"
                            "}\n"
                        "}\n"
                        "show_tip_ex(1,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(1,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(1,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(1,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x03B5)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('AcLimite-DIS').checked){pr=$('AcLimite-DIS').value;}\n"
                        "else if($('AcLimite-EN').checked){pr=$('AcLimite-EN').value;} \n"
                        "fe=Json.ID_0x03B5;\n"
                        "if(pr!=fe)\n"
                        "{\n"
                            "if(Json.ID_0x03B5==0x55)\n"
                            "{\n"
                                "$('AcLimite-DIS').checked=true;\n"
                                "$('AcLimite-EN').checked=false;\n"
                            "}\n"
                            "else if(Json.ID_0x03B5==0xAA)\n"
                            "{\n"
                                "$('AcLimite-DIS').checked=false;\n"
                                "$('AcLimite-EN').checked=true; \n"
                            "}\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "if(Json.ID_0x03B5==0xAA)\n"
                            "{\n"
                                "$('Peak-DIS').checked=true;\n"
                                "$('Peak-EN').checked=false;\n"
                                "$('Smooth-DIS').checked=true;\n"
                                "$('Smooth-EN').checked=false;    \n"
                                "$('FM-DIS').checked=true;\n"
                                "$('FM-EN').checked=false;  \n"
                            "}\n"
                        "}\n"
                        "show_tip_ex(2,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(2,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(2,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(2,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x03B8)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('Smooth-DIS').checked){pr=$('Smooth-DIS').value;}\n"
                        "else if($('Smooth-EN').checked){pr=$('Smooth-EN').value;} \n"
                        "fe=Json.ID_0x03B8;\n"
                        "if(pr!=fe)\n"
                        "{\n"
                            "if(Json.ID_0x03B8==0x55)\n"
                            "{\n"
                                "$('Smooth-DIS').checked=true;\n"
                                "$('Smooth-EN').checked=false;\n"
                            "}\n"
                            "else if(Json.ID_0x03B8==0xAA)\n"
                            "{\n"
                                "$('Smooth-DIS').checked=false;\n"
                                "$('Smooth-EN').checked=true;     \n"
                            "}\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "if(Json.ID_0x03B8==0xAA)\n"
                            "{\n"
                                "$('Peak-DIS').checked=true;\n"
                                "$('Peak-EN').checked=false;\n"
                                "$('AcLimite-DIS').checked=true;\n"
                                "$('AcLimite-EN').checked=false;\n"
                                "$('FM-DIS').checked=true;\n"
                                "$('FM-EN').checked=false;   \n"
                            "}\n"
                        "}\n"
                        "show_tip_ex(3,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(3,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(3,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(3,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                    "else if(addr == 0x03C0)\n"
                    "{\n"
                        "var pr=0,fe=0;\n"
                        "if($('FM-DIS').checked){pr=$('FM-DIS').value;}\n"
                        "else if($('FM-EN').checked){pr=$('FM-EN').value;} \n"
                        "fe=Json.ID_0x03C0;\n"
                        "if(pr!=fe)\n"
                        "{\n"
                            "if(Json.ID_0x03C0==0x55)\n"
                            "{\n"
                                "$('FM-DIS').checked=true;\n"
                                "$('FM-EN').checked=false;\n"
                            "}\n"
                            "else if(Json.ID_0x03C0==0xAA)\n"
                            "{\n"
                                "$('FM-DIS').checked=false;\n"
                                "$('FM-EN').checked=true;              \n"
                            "}\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "if(Json.ID_0x03C0==0xAA)\n"
                            "{\n"
                                "$('Peak-DIS').checked=true;\n"
                                "$('Peak-EN').checked=false;\n"
                                "$('AcLimite-DIS').checked=true;\n"
                                "$('AcLimite-EN').checked=false;\n"
                                "$('Smooth-DIS').checked=true;\n"
                                "$('Smooth-EN').checked=false;\n"
                            "}\n"
                        "}\n"
                        "show_tip_ex(4,'&nbsp;');\n"
                        "if(pr!=fe){setTimeout('show_tip_ex(4,lang.N500[language])',500);}\n"
                        "else {setTimeout('show_tip_ex(4,lang.N499[language])',500);}\n"
                        "setTimeout('show_tip_ex(4,\\'&nbsp;\\')',2500);\n"
                    "}\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',url,true);\n"
            "xmlhttp.send();  \n"
        "}\n"
        "function doSubmit(obj)\n"
        "{\n"
            "var peak_en, aclimit_en, smooth_en, fm_en;\n"
            "var URL='a_037.html?';\n"
            "switch(obj.id)\n"
            "{\n"
             "case 'btn1': \n"
             	 "if($('Peak-DIS').checked){peak_en=$('Peak-DIS').value;}\n"
             	 "else if($('Peak-EN').checked){peak_en=$('Peak-EN').value;} \n"
 				"URL=URL+'&0x03B1='+peak_en;\n"
                    "readBack=0x03B1;\n"
             "break;\n"
                "case 'btn2': \n"
                    "if($('AcLimite-DIS').checked){aclimit_en=$('AcLimite-DIS').value;}\n"
                    "else if($('AcLimite-EN').checked){aclimit_en=$('AcLimite-EN').value;} \n"
                    "URL=URL+'&0x03B5='+aclimit_en;\n"
                    "readBack=0x03B5;\n"
                "break;\n"
                "case 'btn3': \n"
                    "if($('Smooth-DIS').checked){smooth_en=$('Smooth-DIS').value;}\n"
                    "else if($('Smooth-EN').checked){smooth_en=$('Smooth-EN').value;} \n"
                    "URL=URL+'&0x03B8='+smooth_en;\n"
                    "readBack=0x03B8;\n"
                "break;\n"
                "case 'btn4': \n"
                    "if($('FM-DIS').checked){fm_en=$('FM-DIS').value;}\n"
                    "else if($('FM-EN').checked){fm_en=$('FM-EN').value;} \n"
                    "URL=URL+'&0x03C0='+fm_en;\n"
                    "readBack=0x03C0;\n"
                "break;\n"
             "default:break;\n"
            "}\n"
            "URL=URL+'&time='+Math.random();\n"
             //alert(URL);
"\n"
            "function success()\n"
            "{\n"
                "setTimeout('read_back('+readBack+')', 100);            			\n"
            "}\n"
             //测试
             //success();            
 		"sendHttpReq(URL, success);\n"
        "}\n"
        "function doSetValue(Json)\n"
        "{\n"
         "if(Json.ID_0x03B1==0x55)\n"
         "{\n"
         	"$('Peak-DIS').checked=true;\n"
         	"$('Peak-EN').checked=false;\n"
         "}\n"
         "else if(Json.ID_0x03B1==0xAA)\n"
         "{\n"
          	"$('Peak-DIS').checked=false;\n"
         	"$('Peak-EN').checked=true;       		\n"
         "}\n"
            "if(Json.ID_0x03B5==0x55)\n"
            "{\n"
                "$('AcLimite-DIS').checked=true;\n"
                "$('AcLimite-EN').checked=false;\n"
            "}\n"
            "else if(Json.ID_0x03B5==0xAA)\n"
            "{\n"
                "$('AcLimite-DIS').checked=false;\n"
                "$('AcLimite-EN').checked=true;              \n"
            "}\n"
            "if(Json.ID_0x03B8==0x55)\n"
            "{\n"
                "$('Smooth-DIS').checked=true;\n"
                "$('Smooth-EN').checked=false;\n"
            "}\n"
            "else if(Json.ID_0x03B8==0xAA)\n"
            "{\n"
                "$('Smooth-DIS').checked=false;\n"
                "$('Smooth-EN').checked=true;              \n"
            "}\n"
            "if(Json.ID_0x03C0==0x55)\n"
            "{\n"
                "$('FM-DIS').checked=true;\n"
                "$('FM-EN').checked=false;\n"
            "}\n"
            "else if(Json.ID_0x03C0==0xAA)\n"
            "{\n"
                "$('FM-DIS').checked=false;\n"
                "$('FM-EN').checked=true;              \n"
            "}\n"
        "}\n"
    "</script\n"
"</html>\n"
};
#endif
