#ifndef _HTML_H_033_H_
#define _HTML_H_033_H_
static const char h_033[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
	"<meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'/>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<style type='text/css'>\n"
            "html{_overflow-y:scroll;}\n"
            "body{\n"
             "margin:0;\n"
             "padding:0;\n"
             "text-align:center;\n"
             "font-size:14px;\n"
             "font-family:'微软雅黑',Verdana,'宋体',sans-serif;\n"
             "background-color:#fff;\n"
             "min-width:867px;\n"
             "margin-top: 4px;\n"
            "}\n"
            "img{vertical-align: top; display: block;}\n"
            ".title{margin:5px auto;width:90%;text-align:left;overflow:hidden;}\n"
            ".r1{margin:0 5px;height:1px;overflow:hidden;width:490px;}\n"
            ".r2{margin:0 3px;height:1px;overflow:hidden;width:494px;}\n"
            ".r3{margin:0 2px;height:1px;overflow:hidden;width:496px;}\n"
            ".r4{margin:0 1px;height:2px;overflow:hidden;width:498px;}\n"
            ".color{background-color:#F58E03;}\n"
            ".content{height:24px;line-height:24px;padding-left:20px;font-size:24px;color:#EEE;text-align:left;}\n"
            ".blank{height:4px;overflow:hidden;}\n"
            ".btm_blank{height:15px;overflow:hidden;}\n"
            ".back_color{background-color:#efefff;}\n"
            ".back_high{width:100%;height:240px;margin:0 auto;}\n"
            ".line_long{height:2px;overflow:hidden;margin:2px auto;background-color:#ccc; width:90%;}\n"
            ".img_common{float:right;margin-right:12px;width:50px;height:50px;}\n"
            ".bg1{background:transparent url(i_001.png) no-repeat scroll 0 0;}\n"
            ".bg2{background:transparent url(i_001.png) no-repeat scroll -50px 0;}\n"
            ".bg3{background:transparent url(i_001.png) no-repeat scroll -100px 0;}\n"
            ".bg4{background:transparent url(i_001.png) no-repeat scroll 0 -50px;}\n"
            ".bg5{background:transparent url(i_001.png) no-repeat scroll -50px -50px;}\n"
            ".bg6{background:transparent url(i_001.png) no-repeat scroll -100px -50px;}\n"
            ".bg7{background:transparent url(i_005.png) no-repeat scroll 0 0;}\n"
            ".bg8{background:transparent url(i_006.png) no-repeat scroll 0 0;}\n"
            ".bg9{background:transparent url(i_007.png) no-repeat scroll 0 0;}\n"
            ".name{text-align:left;font-size:14px;font-weight:normal;color:#000;}\n"
            ".value{text-align:left;font-size:18px;font-weight:bold;color:#06C;font-style:normal;}\n"
            ".div_query{margin:0px auto;width:90%;padding-left:100px;width:90%;float:left;height:30px;line-height:24px;font-size:16px;color:#000;}\n"
            ".date_label{width:150px;float:left;height:24px;}\n"
            ".div_btn{width:100px;float:left;margin-left:50px;text-align:center;font-weight: bold;color:#888;height:26px;}\n"
            ".color{background-color:#F58E03;}\n"
            ".color2{background-color:#aaa;}\n"
            ".date{width:100px;float:left;margin-left:10px;text-align:center;color:#00f;height:20px;}\n"
            ".Ftab{width:480px;height:20px;line-height:20px;padding-left:20px;font-size:18px;text-align:center;}\n"
            ".Ftab span{margin:0;padding:0;float:left;width:48%;color:#fff;}\n"
            ".Ftab .select{background: #007B3E;}\n"
        "</style>\n"
        "<script src='j_000.js' type='text/javascript'></script>\n"
        "<script type=\"text/javascript\" src=\"jquery.min.js\"></script>\n"
        "<script type=\"text/javascript\" src=\"j_highcharts.js\"></script>\n"
        "<script type=\"text/javascript\" src=\"j_exporting.js\"></script>\n"
        "<script type=\"text/javascript\" src=\"j_canvas-tools.js\"></script>\n"
        "<script type=\"text/javascript\" src=\"j_export-csv.js\"></script>\n"
        "<script type=\"text/javascript\" src=\"j_highcharts-export-clientside.js\"></script>\n"
        "<script type='text/javascript'>\n"
            "function show_T(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
                "str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
                "document.write(str);\n"
            "}\n"
        "</script> \n"
    "</head>\n"
    "<body onload='Init()'>  \n"
        "<div class='title'>\n"
            "<div class='r1 color2'></div><div class='r2 color2'></div><div class='r3 color2'></div><div class='r4 color2'></div>\n"
            "<div class='Ftab color2' id=\"tabFunc\">\n"
                "<span class='select' id='N02'></span><span id='N03'></span>\n"
            "</div>  \n"
            "<div class='r4 color2'></div><div class='r3 color2'></div><div class='r2 color2'></div><div class='r1 color2'></div>\n"
        "</div>\n"
        "<div class='blank'></div>\n"
        "<div id='query' class='div_query'>\n"
            "<span class='date_label' id='N20'></span>\n"
            "<input id='DATE' class='date' type=\"text\" onClick=\"SelectDate(this,'yyyy-MM-dd',language)\"/>\n"
            "<button class='div_btn' onclick='doSubmit()'><span id='N21'></span></button>\n"
        "</div>\n"
        "<div id=\"curver\" width='90%' style=\"height: 600px;padding-left:2%; min-width: 780px; padding-right:5%;\"></div>\n"
        "<br/><img id='waiting' style='margin:0 auto;z-index:20000;position:relative;top:-368px;visibility:hidden;' src='i_002.gif'/><br/> \n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script>\n"
        "var fresh_time;\n"
        "var tab_index=0;\n"
        "var CurRecordIndex=1;\n"
        "var busy = false;\n"
        "var btns = OBJ('tabFunc').getElementsByTagName('span');\n"
        "for (var i = 0; i < btns.length; i++) {\n"
            "btns[i].index = i;\n"
            "btns[i].onclick = function(){\n"
                "tab_index = this.index;\n"
                "for (var i = 0; i < btns.length; i++) { btns[i].className = ''; };\n"
                "this.className = 'select';\n"
                "Switch_Tab(tab_index);\n"
            "}\n"
        "};\n"
        "function Switch_Tab(index)\n"
        "{\n"
            "if(busy) return;\n"
            "for (var i = 0; i < btns.length; i++) { btns[i].className = ''; };\n"
            "btns[index].className = 'select';\n"
            "if(tab_index==0){\n"
                "OBJ('query').style.display='none';\n"
                "ajax_s(tab_index+1);\n"
                "fresh_time=setInterval('ajax_s(tab_index+1)',interval_time);\n"
            "}else{\n"
                "OBJ('query').style.display='block';\n"
                "clearTimeout(fresh_time);\n"
                "ajax_s(tab_index+1);\n"
            "}\n"
        "}\n"
    "</script>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var FromMobileDevice=false;\n"
        "function FromWhichDevice()\n"
        "{\n"
            "var sUserAgent=navigator.userAgent.toLowerCase();\n"
            "var Ipad=sUserAgent.match(/ipad/i)=='ipad';\n"
            "var IphoneOs=sUserAgent.match(/iphone os/i)=='iphone os';\n"
            "var Android=sUserAgent.match(/android/i)=='android';\n"
            "var WindowsPhone=sUserAgent.match(/windows phone/i)=='windows phone';\n"
            "if(Ipad||IphoneOs||Android||WindowsPhone)FromMobileDevice=true;\n"
            "else FromMobileDevice=false;\n"
        "}\n"
        "var language=0;\n"
        "var Json;\n"
        "var lang=\n"
        "{\n"
            "N01:['XX','XX'],\n"
            "N02:['实时功率','Realtime Power'],\n"
            "N03:['记录','Record'],\n"
"\n"
            "N07:['导&nbsp;&nbsp;出','Export'],\n"
            "N08:['负载功率','Load Power'],\n"
            "N09:['电网功率','Grid Power'],\n"
            "N10:['储能逆变器功率','PCS Power'],\n"
"\n"
            "N20:['查询日期：','Inquery Date:'],\n"
            "N21:['查&nbsp;&nbsp;询','Inquery'],\n"
"\n"
            "N29:['导出/打印', 'Export/Print'],\n"
            "N30:['打印图表', 'Print Chart'],\n"
            "N31:['下载 JPEG 文件', 'Download JPEG'],\n"
            "N32:['下载 PNG 文件', 'Download PNG'],\n"
            "N33:['下载 SVG 文件', 'Download SVG'],\n"
            "N34:['下载 CSV 文件', 'Download CSV'],\n"
            "N35:['下载 XLS 文件', 'Download XLS'],\n"
"\n"
            "N500:['一共','Total '],\n"
            "N501:['页，共',' Pages, '],\n"
            "N502:['条',' Nums']\n"
        "};\n"
"\n"
        "var interval_time = 10000;\n"
        "var chart;\n"
        "var timer;\n"
   "\n"
        "function ConfigureChart()\n"
        "{\n"
            "Highcharts.setOptions({\n"
                "global: {\n"
                    "useUTC: false\n"
                "},\n"
                "lang: {\n"
                    "printChart: lang.N30[language],\n"
                    "downloadJPEG: lang.N31[language], \n"
                    "downloadPNG: lang.N32[language],\n"
                    "downloadSVG: lang.N33[language], \n"
                    "downloadCSV: lang.N34[language],\n"
                    "downloadXLS: lang.N35[language]\n"
                "},\n"
                "chart:{\n"
                    "renderTo: 'curver',\n"
                     //'spline' 'line' 'area'
                     //type: 'area',
                     //背景色
                     //backgroundColor: '#eee',
                     //背景渐变
                     //backgroundColor: {
                     //    linearGradient: [0, 0, 500, 500],
                     //    stops: [
                     //        [0, 'rgb(255, 255, 255)'],
                     //        [1, 'rgb(200, 200, 255)']
                     //    ]
                     //},
                     //animation: Highcharts.svg,
                     //marginRight: 10
                "},\n"
                "title: {\n"
                    "text: ''\n"
                "},\n"
                "xAxis: {\n"
                     //X轴标题
                    "title: { text:'T(h)/'+ Json.D00+'-'+Json.D01+'-'+Json.D02 }, \n"
                    "showFirstLable: true,\n"
                    "showLastLabel: true,   \n"
                    "lineWidth: 2,\n"
                    "lineColor: '#808080',\n"
                    "tickColor: '#e0e0e0',             \n"
                     // The types are 'linear', 'logarithmic' and 'datetime'
                    "type: 'linear',    \n"
                    "categories: ['0', '', '0:30', '', '1:00', '', '1:30', '', '2:00', '', '2:30', '', '3:00', '', '3:30', '', '4:00', '', '4:30', '', '5:00', '', '5:30', '', '6:00', '', '6:30', '', '7:00', '', '7:30', '', '8:00', '', '8:30', '', '9:00', '', '9:30', '', '10:00', '', '10:30', '', '11:00', '', '11:30', '', '12:00', '', '12:30', '', '13:00', '', '13:30', '', '14:00', '', '14:30', '', '15:00', '', '15:30', '', '16:00', '', '16:30', '', '17:00', '', '17:30', '', '18:00', '', '18:30', '', '19:00', '', '19:30', '', '20:00', '', '20:30', '', '21:00', '', '21:30', '', '22:00', '', '22:30', '', '23:00', '', '23:30', '', '0']\n"
                "},\n"
                "yAxis: {\n"
                     //Y轴标题
                    "title: { text: 'P(Kw)' },\n"
                    "showEmpty: false,\n"
                    "lineWidth: 2,\n"
                    "lineColor: '#808080',\n"
                     //隔行显示颜色
                     //alternateGridColor: '#FDFFD5',
                     //网格线颜色
                    "gridLineColor: '#e0e0e0',\n"
                    "gridLineWidth: 1,\n"
                    "labels: {\n"
                        "formatter: function() {\n"
                            "return  this.value + ' Kw';\n"
                        "}\n"
                    "},\n"
                     //max: 500,
                     //min: -500,
                    "plotLines: [{\n"
                        "value: 0,\n"
                        "width: 1,\n"
                        "color: '#808080'\n"
                    "}]\n"
                "},\n"
                "plotOptions: {\n"
                      //针对图形类型的设置 'spline' 'line' 'area'
                    "area: {\n"
                        "allowPointSelect:true,\n"
                        "fillOpacity:0.6,\n"
                        "marker:{\n"
                            "enabled: false,\n"
                                "states: {\n"
                                "hover: {\n"
                                    "enabled: true,\n"
                                    "symbol: 'circle',\n"
                                    "radius: 2,\n"
                                    "lineWidth: 1\n"
                                "}\n"
                            "}\n"
                        "}\n"
                    "},\n"
                    "series: {\n"
                        "animation: false,\n"
                        "marker:{\n"
                            "enabled: false\n"
                        "}\n"
                    "}\n"
                "},\n"
                "tooltip: {\n"
                    "formatter: function() {\n"
                        "return '<b><span style=\"color:'+this.series.color+'\">'+ this.series.name +'</span></b><br/>'+\n"
                        "Highcharts.numberFormat(this.y, 1) + ' Kw';\n"
                    "}\n"
                "},\n"
                 //版本信息
                "credits: {\n"
                    "text: ''\n"
                "},\n"
                "navigation: {\n"
                    "buttonOptions: {\n"
                        "enabled: true,\n"
                        "theme: {\n"
                            "style: {\n"
                                "color: '#0000FF',\n"
                                "textDecoration: 'underline'\n"
                            "}\n"
                        "}\n"
                    "}\n"
                "},\n"
                "exporting: {\n"
                     //enabled:true, //默认为可用，当设置为false时，图表的打印及导出功能失效
                     //配置按钮选项
                    "buttons:{   \n"
                        "contextButton: {\n"
                            "text: lang.N29[language],\n"
                            "symbol: 'circle',\n"
                            "symbolFill: '#A349A4',\n"
                             //menuItems: [
                             //    Highcharts.getOptions().exporting.buttons.contextButton.menuItems[1],
                             //    Highcharts.getOptions().exporting.buttons.contextButton.menuItems[2],
                             //    Highcharts.getOptions().exporting.buttons.contextButton.menuItems[3],
                             //    Highcharts.getOptions().exporting.buttons.contextButton.menuItems[4],
                             //    Highcharts.getOptions().exporting.buttons.contextButton.menuItems[5],
                             //    Highcharts.getOptions().exporting.buttons.contextButton.menuItems[6],
                             //    Highcharts.getOptions().exporting.buttons.contextButton.menuItems[7]
                             //]
                             //禁止导出列表子项显示
                             //menuItems: null,
                             //点击导出按钮时直接导出
                             //onclick: function () { this.exportChart(); }
                        "},\n"
                         //配置打印按钮
                         //printButton:{   
                         //    width:50,
                         //    symbolSize:20,
                         //    borderWidth:2,
                         //    borderRadius:0,
                         //    hoverBorderColor:'red',
                         //    height:30,
                         //    symbolX:25,
                         //    symbolY:15,
                         //    x:-200,
                         //    y:20
                         //},
                         //配置导出按钮
                         //exportButton:{  
                         //    width:50,
                         //    symbolSize:20,
                         //    borderWidth:2,
                         //    borderRadius:0,
                         //    hoverBorderColor:'red',
                         //    height:30,
                         //    symbolX:25,
                         //    symbolY:15,
                         //    x:-150,
                         //    y:20
                         //}
                    "},\n"
                    "chartOptions: {\n"
                        "plotOptions: {\n"
                            "series: {\n"
                                "dataLabels: {\n"
                                     //导出时显示数据标签
                                    "enabled: true\n"
                                "}\n"
                            "}\n"
                        "}\n"
                    "},\n"
                    "filename:'pls',\n"
                     //type:'image/png',
                     //width:800,
                     //height:600  
                "},\n"
                 //图例
                "legend: {\n"
                    "backgroundColor: '#FCFFC5',\n"
                    "borderColor: '#C98657',\n"
                    "borderWidth: 1,\n"
                     //layout: 'vertical',
                    "layout: 'horizontal',\n"
                    "itemDistance: 10,\n"
                    "backgroundColor: '#FFFFFF',\n"
                    "floating: true,\n"
                    "align: 'left',\n"
                    "verticalAlign: 'top',\n"
                    "x: 80,\n"
                    "y: 0,\n"
                    "labelFormatter: function () {\n"
                        "return this.name;\n"
                    "}\n"
                "}\n"
            "});\n"
        "}\n"
        "function CreateChart()\n"
        "{\n"
            "chart = new Highcharts.Chart({\n"
                "events: {\n"
                    "redraw: function () {\n"
                        "var label = this.renderer.label('The chart was just redrawn', 100, 120)\n"
                            ".attr({\n"
                                "fill: Highcharts.getOptions().colors[0],\n"
                                "padding: 10,\n"
                                "r: 5,\n"
                                "zIndex: 8\n"
                            "})\n"
                            ".css({\n"
                                "color: '#FFFFFF'\n"
                            "})\n"
                            ".add();\n"
"\n"
                        "setTimeout(function () {\n"
                            "label.fadeOut();\n"
                        "}, 1000);\n"
                    "}\n"
                "},\n"
                 //数据段
                "series: \n"
                "[   \n"
                    "{\n"
                        "type: 'line',\n"
                         //ShortDash,LongDash,ShortDot,ShortDashDot,DashDot
                        "dashStyle:\"ShortDash\",\n"
                        "name: lang.N08[language],\n"
                         //线段颜色
                         //lineColor: '#303030',
                         //线段或区域颜色
                        "color: '#F7A35C',\n"
                         //数据段1初始化
                         //data: (function() {
                         //    return data1;
                         //})()
                    "},\n"
                    "{\n"
                        "type: 'area',\n"
                        "name: lang.N09[language],\n"
                         //线段颜色
                         //lineColor: '#303030',
                         //线段或区域颜色
                        "color: '#90ED7D',\n"
                         //数据段2初始化
                         //data: (function() {
                         //    return data2;
                         //})()
                    "},\n"
                    "{\n"
                        "type: 'area',\n"
                        "name: lang.N10[language],\n"
                         //线段颜色
                         //lineColor: '#303030',
                         //线段或区域颜色
                        "color: '#99D9EA',\n"
                         //数据段2初始化
                         //data: (function() {
                         //    return data2;
                         //})()
                    "}\n"
                "]\n"
            "});    \n"
        "}\n"
"\n"
        "function Init()\n"
        "{\n"
            "FromWhichDevice();\n"
            "var URL ='s_033.html?0x0000&time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function() \n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);\n"
                    "if(Json.ID_0x0301==0x55)language=0;else language=1;    \n"
                    "OBJ('N02').innerHTML=lang.N02[language];\n"
                    "OBJ('N03').innerHTML=lang.N03[language];\n"
                     //OBJ('N04').innerHTML=lang.N04[language];
                     //OBJ('N05').innerHTML=lang.N05[language];
                     //OBJ('N06').innerHTML=lang.N06[language];
"\n"
                    "OBJ('N20').innerHTML=lang.N20[language];\n"
                    "OBJ('N21').innerHTML=lang.N21[language];\n"
                    "var d = new Date();\n"
                    "var year = d.getYear()-100;\n"
                    "var month = d.getMonth() + 1;\n"
                    "var day = d.getDate();    \n"
                    "OBJ('DATE').value=(year+2000)+'-'+(month<10?'0'+month:month)+'-'+(day<10?'0'+day:day);\n"
                    "Switch_Tab(tab_index);\n"
                "}\n"
            "}            \n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();      \n"
        "}\n"
"\n"
         //
         //var data3 = [];
         //var data4 = [];  
"\n"
         //type: 0x0001 获取实时数据, 0x0002 获取历史数据
        "function ajax_s(type)\n"
        "{\n"
            "var URL;\n"
            "if(type == 1){\n"
                "URL ='s_033.html?0x000'+type+'&time='+Math.random();\n"
            "}else{\n"
                "var ip=OBJ('DATE').value.split('-');\n"
                "var URL='r_033.html?'+'Y='+ip[0]+'&M='+ip[1]+'&D='+ip[2]+'&P='+1+'&time='+Math.random();\n"
            "}\n"
"\n"
            "$.ajax({\n"
                "url:URL,\n"
                "type:\"get\",\n"
                "contentType:\"application/text;charset=utf-8\",\n"
                "dataType:\"text\",\n"
                "async: true,\n"
                "timeout : 5000,\n"
                "beforeSend:function()\n"
                "{\n"
                    "if(type != 1)OBJ('waiting').style.visibility='visible';\n"
                    "busy=true;\n"
                "},\n"
                "success:function(data)\n"
                "{\n"
                    "eval('Json='+data);\n"
                    "if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
"\n"
                    "var data1 = [];\n"
                    "var data2 = [];  \n"
                    "var data3 = [];                  \n"
                    "for(var i=0; i<96; i++){\n"
                        "if(i<10) eval('data1['+i+']=Json.A0'+i+';');else eval('data1['+i+']=Json.A'+i+';');\n"
                        "if(i<10) eval('data2['+i+']=Json.B0'+i+';');else eval('data2['+i+']=Json.B'+i+';');\n"
                        "if(i<10) eval('data3['+i+']=Json.C0'+i+';');else eval('data3['+i+']=Json.C'+i+';');\n"
                         //data1[i]=(Math.random()*1.3+40);
                         //data2[i]=(Math.random()*1.3+50);
                         //data3[i]=(Math.random()*1.3+60);
                    "}\n"
                    "if(chart!=undefined)chart.destroy();\n"
                    "ConfigureChart();\n"
                    "CreateChart();\n"
                    "chart.series[0].setData(data1);\n"
                    "chart.series[1].setData(data2);\n"
                    "chart.series[2].setData(data3);\n"
                    "chart.redraw();\n"
                     //data1.length=0;  //会影响图片导出
                     //data2.length=0;  //会影响图片导出
                     //data3.length=0;  //会影响图片导出
"\n"
                     //for(var i=0; i<96; i++){
                     //    data3.push( (Math.random()*1.3+40) );
                     //    data4.push( (Math.random()*1.3+50) );
                     //}
                     //chart.series[0].setData(data3);
                     //chart.series[1].setData(data4);
                     //chart.redraw();
                    "OBJ('waiting').style.visibility='hidden';\n"
                    "busy=false;\n"
                "},\n"
                "complete:function(XMLHttpRequest,status)\n"
                "{\n"
                     //超时
                    "if(status=='timeout'){\n"
                        "OBJ('waiting').style.visibility='hidden';\n"
                        "busy=false;\n"
                    "}\n"
                "}\n"
            "});\n"
        "}\n"
        "function doSubmit(obj)\n"
        "{\n"
            "ajax_s(2);\n"
        "}\n"
    "</script>  \n"
    "<script>\n"
     //日期控件
    "var cal;\n"
     //是否为焦点
    "var isFocus=false; \n"
     //自加
    "var objdate;\n"
"\n"
    "var objdate1;\n"
"\n"
     //选择日期  lang: 0 --中文， 1--英文
    "function SelectDate(obj,strFormat,lang)\n"
    "{\n"
         //自加
        "objdate = obj;\n"
        "var date = new Date();\n"
         //最小值 → 50 年前
        "var by = date.getFullYear()-50;  \n"
         //最大值 → 50 年后
        "var ey = date.getFullYear()+50;  \n"
         //初始化英文版，0 为中文版
        "cal = (cal==null) ? new Calendar(by, ey, lang) : cal;    \n"
        "cal.dateFormatStyle = strFormat;\n"
        "cal.show(obj);\n"
    "}\n"
"\n"
     // * 返回日期
     // * @param d the delimiter
     // * @param p the pattern of your date
     // * 根据用户指定的 style 来确定；
     //String.prototype.toDate = function(x, p) {
    "String.prototype.toDate = function(style) {\n"
      "var y = this.substring(style.indexOf('y'),style.lastIndexOf('y')+1);\n"
      "var m = this.substring(style.indexOf('M'),style.lastIndexOf('M')+1);\n"
      "var d = this.substring(style.indexOf('d'),style.lastIndexOf('d')+1);\n"
      "if(isNaN(y)) y = new Date().getFullYear();\n"
      "if(isNaN(m)) m = new Date().getMonth();\n"
      "if(isNaN(d)) d = new Date().getDate();\n"
      "var dt ;\n"
      "eval (\"dt = new Date('\"+ y+\"', '\"+(m-1)+\"','\"+ d +\"')\");\n"
      "return dt;\n"
    "}\n"
"\n"
     // * 格式化日期
     // * @param   d the delimiter
     // * @param   p the pattern of your date
     // * @author  meizz
    "Date.prototype.format = function(style) {\n"
      "var o = {\n"
        "\"M+\" : this.getMonth() + 1, \n"
        "\"d+\" : this.getDate(),     \n"
        "\"h+\" : this.getHours(),    \n"
        "\"m+\" : this.getMinutes(),   \n"
        "\"s+\" : this.getSeconds(),   \n"
        "\"w+\" : \"天一二三四五六\".charAt(this.getDay()),  \n"
        "\"q+\" : Math.floor((this.getMonth() + 3) / 3),  \n"
        "\"S\"  : this.getMilliseconds() \n"
      "}\n"
      "if(/(y+)/.test(style)) {\n"
        "style = style.replace(RegExp.$1,\n"
        "(this.getFullYear() + \"\").substr(4 - RegExp.$1.length));\n"
      "}\n"
      "for(var k in o){\n"
        "if(new RegExp(\"(\"+ k +\")\").test(style)){\n"
          "style = style.replace(RegExp.$1,\n"
            "RegExp.$1.length == 1 ? o[k] :\n"
            "(\"00\" + o[k]).substr((\"\" + o[k]).length));\n"
        "}\n"
      "}\n"
      "return style;\n"
    "};\n"
"\n"
     // * 日历类
     // * @param   beginYear 1990
     // * @param   endYear   2010
     // * @param   lang      0(中文)|1(英语) 可自由扩充
     // * @param   dateFormatStyle  \"yyyy-MM-dd\";
     // * @version 2006-04-01
     // * @author  KimSoft (jinqinghua [at] gmail.com)
     // * @update
    "function Calendar(beginYear, endYear, lang, dateFormatStyle) {\n"
      "this.beginYear = 1990;\n"
      "this.endYear = 2010;\n"
       //0(中文) | 1(英文)
      "this.lang = 0;            \n"
      "this.dateFormatStyle = \"yyyy-MM-dd\";\n"
"\n"
      "if (beginYear != null && endYear != null){\n"
        "this.beginYear = beginYear;\n"
        "this.endYear = endYear;\n"
      "}\n"
      "if (lang != null){\n"
        "this.lang = lang\n"
      "}\n"
"\n"
      "if (dateFormatStyle != null){\n"
        "this.dateFormatStyle = dateFormatStyle\n"
      "}\n"
"\n"
      "this.dateControl = null;\n"
      "this.panel = this.getElementById(\"calendarPanel\");\n"
      "this.container = this.getElementById(\"ContainerPanel\");\n"
      "this.form  = null;\n"
"\n"
      "this.date = new Date();\n"
      "this.year = this.date.getFullYear();\n"
      "this.month = this.date.getMonth();\n"
"\n"
      "this.colors = {\n"
           //当日日期文字颜色
          "\"cur_word\"      : \"#FFFFFF\",  \n"
           //当日日期单元格背影色
          "\"cur_bg\"        : \"#00FF00\",  \n"
           //已被选择的日期单元格背影色 2006-12-03 寒羽枫添加
          "\"sel_bg\"        : \"#FFCCCC\",  \n"
           //星期天文字颜色
          "\"sun_word\"      : \"#FF0000\",  \n"
           //星期六文字颜色
          "\"sat_word\"      : \"#0000FF\",  \n"
           //单元格文字颜色
          "\"td_word_light\" : \"#333333\",  \n"
           //单元格文字暗色
          "\"td_word_dark\"  : \"#CCCCCC\",  \n"
           //单元格背影色
          "\"td_bg_out\"     : \"#EFEFEF\", \n"
           //单元格背影色 
          "\"td_bg_over\"    : \"#FFCC00\", \n"
           //日历头文字颜色 
          "\"tr_word\"       : \"#FFFFFF\", \n"
           //日历头背影色 
          "\"tr_bg\"         : \"#666666\", \n"
           //input控件的边框颜色 
          "\"input_border\"  : \"#CCCCCC\",\n"
           //input控件的背影色  
          "\"input_bg\"      : \"#EFEFEF\"   \n"
      "}\n"
"\n"
      "this.draw();\n"
      "this.bindYear();\n"
      "this.bindMonth();\n"
      "this.changeSelect();\n"
      "this.bindData();\n"
    "}\n"
"\n"
     //日历类属性（语言包，可自由扩展）
    "Calendar.language = {\n"
      "\"year\"   : [[\"\"], [\"\"]],\n"
      "\"months\" : [[\"一月\",\"二月\",\"三月\",\"四月\",\"五月\",\"六月\",\"七月\",\"八月\",\"九月\",\"十月\",\"十一月\",\"十二月\"],\n"
            "[\"JAN\",\"FEB\",\"MAR\",\"APR\",\"MAY\",\"JUN\",\"JUL\",\"AUG\",\"SEP\",\"OCT\",\"NOV\",\"DEC\"]\n"
             "],\n"
      "\"weeks\"  : [[\"日\",\"一\",\"二\",\"三\",\"四\",\"五\",\"六\"],\n"
            "[\"SUN\",\"MON\",\"TUR\",\"WED\",\"THU\",\"FRI\",\"SAT\"]\n"
             "],\n"
      "\"clear\"  : [[\"清空\"], [\"CLS\"]],\n"
      "\"today\"  : [[\"今天\"], [\"TODAY\"]],\n"
      "\"close\"  : [[\"关闭\"], [\"CLOSE\"]]\n"
    "}\n"
"\n"
    "Calendar.prototype.draw = function() {\n"
      "calendar = this;\n"
"\n"
      "var mvAry = [];  \n"
      "mvAry[mvAry.length]  = '  <div name=\"calendarForm\" style=\"margin: 0px;\">';\n"
      "mvAry[mvAry.length]  = '    <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\">';\n"
      "mvAry[mvAry.length]  = '      <tr>';\n"
      "mvAry[mvAry.length]  = '        <th align=\"left\" width=\"1%\"><input style=\"border: 1px solid ' + calendar.colors[\"input_border\"] + ';background-color:' + calendar.colors[\"input_bg\"] + ';width:16px;height:20px;\" name=\"prevMonth\" type=\"button\" id=\"prevMonth\" value=\"&lt;\" /></th>';\n"
      "mvAry[mvAry.length]  = '        <th align=\"center\" width=\"98%\" nowrap=\"nowrap\"><select name=\"calendarYear\" id=\"calendarYear\" style=\"font-size:12px;\"></select><select name=\"calendarMonth\" id=\"calendarMonth\" style=\"font-size:12px;\"></select></th>';\n"
      "mvAry[mvAry.length]  = '        <th align=\"right\" width=\"1%\"><input style=\"border: 1px solid ' + calendar.colors[\"input_border\"] + ';background-color:' + calendar.colors[\"input_bg\"] + ';width:16px;height:20px;\" name=\"nextMonth\" type=\"button\" id=\"nextMonth\" value=\"&gt;\" /></th>';\n"
      "mvAry[mvAry.length]  = '      </tr>';\n"
      "mvAry[mvAry.length]  = '    </table>';\n"
      "mvAry[mvAry.length]  = '    <table id=\"calendarTable\" width=\"100%\" style=\"border:0px solid #CCCCCC;background-color:#FFFFFF;font-size:9pt\" border=\"0\" cellpadding=\"2\" cellspacing=\"1\">';\n"
      "mvAry[mvAry.length]  = '      <tr>';\n"
      "for(var i = 0; i < 7; i++) {\n"
        "mvAry[mvAry.length]  = '      <th style=\"font-weight:normal;background-color:' + calendar.colors[\"tr_bg\"] + ';color:' + calendar.colors[\"tr_word\"] + ';\">' + Calendar.language[\"weeks\"][this.lang][i] + '</th>';\n"
      "}\n"
      "mvAry[mvAry.length]  = '      </tr>';\n"
      "for(var i = 0; i < 6;i++){\n"
        "mvAry[mvAry.length]  = '    <tr align=\"center\">';\n"
        "for(var j = 0; j < 7; j++) {\n"
          "if (j == 0){\n"
            "mvAry[mvAry.length]  = '  <td style=\"cursor:default;color:' + calendar.colors[\"sun_word\"] + ';\"></td>';\n"
          "} else if(j == 6) {\n"
            "mvAry[mvAry.length]  = '  <td style=\"cursor:default;color:' + calendar.colors[\"sat_word\"] + ';\"></td>';\n"
          "} else {\n"
            "mvAry[mvAry.length]  = '  <td style=\"cursor:default;\"></td>';\n"
          "}\n"
        "}\n"
        "mvAry[mvAry.length]  = '    </tr>';\n"
      "}\n"
      "mvAry[mvAry.length]  = '      <tr style=\"background-color:' + calendar.colors[\"input_bg\"] + ';\">';\n"
      "mvAry[mvAry.length]  = '        <th colspan=\"2\"><input name=\"calendarClear\" type=\"button\" id=\"calendarClear\" value=\"' + Calendar.language[\"clear\"][this.lang] + '\" style=\"border: 1px solid ' + calendar.colors[\"input_border\"] + ';background-color:' + calendar.colors[\"input_bg\"] + ';width:100%;height:18px;font-size:9pt;\"/></th>';\n"
      "mvAry[mvAry.length]  = '        <th colspan=\"3\"><input name=\"calendarToday\" type=\"button\" id=\"calendarToday\" value=\"' + Calendar.language[\"today\"][this.lang] + '\" style=\"border: 1px solid ' + calendar.colors[\"input_border\"] + ';background-color:' + calendar.colors[\"input_bg\"] + ';width:100%;height:18px;font-size:9pt;\"/></th>';\n"
      "mvAry[mvAry.length]  = '        <th colspan=\"2\"><input name=\"calendarClose\" type=\"button\" id=\"calendarClose\" value=\"' + Calendar.language[\"close\"][this.lang] + '\" style=\"border: 1px solid ' + calendar.colors[\"input_border\"] + ';background-color:' + calendar.colors[\"input_bg\"] + ';width:100%;height:18px;font-size:9pt;\"/></th>';\n"
      "mvAry[mvAry.length]  = '      </tr>';\n"
      "mvAry[mvAry.length]  = '    </table>';  \n"
      "mvAry[mvAry.length]  = '  </div>';\n"
      "this.panel.innerHTML = mvAry.join(\"\");\n"
      "\n"
       ///**//******** 以下代码由寒羽枫 2006-12-01 添加 **********/
      "var obj = this.getElementById(\"prevMonth\");\n"
      "obj.onclick = function () {calendar.goPrevMonth(calendar);}\n"
      "obj.onblur = function () {calendar.onblur();}\n"
      "this.prevMonth= obj;\n"
      "\n"
      "obj = this.getElementById(\"nextMonth\");\n"
      "obj.onclick = function () {calendar.goNextMonth(calendar);}\n"
      "obj.onblur = function () {calendar.onblur();}\n"
      "this.nextMonth= obj;   \n"
"\n"
      "obj = this.getElementById(\"calendarClear\");\n"
      "obj.onclick = function () {calendar.dateControl.value = \"\";calendar.hide();}\n"
      "this.calendarClear = obj;\n"
      "\n"
      "obj = this.getElementById(\"calendarClose\");\n"
      "obj.onclick = function () {calendar.hide();}\n"
      "this.calendarClose = obj;\n"
      "\n"
      "obj = this.getElementById(\"calendarYear\");\n"
      "obj.onchange = function () {calendar.update(calendar);}\n"
      "obj.onblur = function () {calendar.onblur();}\n"
      "this.calendarYear = obj;\n"
      "\n"
      "obj = this.getElementById(\"calendarMonth\");\n"
      "with(obj)\n"
      "{\n"
        "onchange = function () {calendar.update(calendar);}\n"
        "onblur = function () {calendar.onblur();}\n"
      "}this.calendarMonth = obj;\n"
     "\n"
      "obj = this.getElementById(\"calendarToday\");\n"
      "obj.onclick = function () {\n"
        "var today = new Date();\n"
        "calendar.date = today;\n"
        "calendar.year = today.getFullYear();\n"
        "calendar.month = today.getMonth();\n"
        "calendar.changeSelect();\n"
        "calendar.bindData();\n"
        "calendar.dateControl.value = today.format(calendar.dateFormatStyle);\n"
        "calendar.hide();\n"
      "}\n"
      "this.calendarToday = obj; \n"
    "}\n"
"\n"
     //年份下拉框绑定数据
    "Calendar.prototype.bindYear = function() { \n"
      "var cy = this.calendarYear;\n"
      "cy.length = 0;\n"
      "for (var i = this.beginYear; i <= this.endYear; i++){\n"
        "cy.options[cy.length] = new Option(i + Calendar.language[\"year\"][this.lang], i);\n"
      "}\n"
    "}\n"
"\n"
     //月份下拉框绑定数据
    "Calendar.prototype.bindMonth = function() { \n"
      "var cm = this.calendarMonth;\n"
      "cm.length = 0;\n"
      "for (var i = 0; i < 12; i++){\n"
        "cm.options[cm.length] = new Option(Calendar.language[\"months\"][this.lang][i], i);\n"
      "}\n"
    "}\n"
"\n"
     //向前一月
    "Calendar.prototype.goPrevMonth = function(e){\n"
      "if (this.year == this.beginYear && this.month == 0){return;}\n"
      "this.month--;\n"
      "if (this.month == -1) {\n"
        "this.year--;\n"
        "this.month = 11;\n"
      "}\n"
      "this.date = new Date(this.year, this.month, 1);\n"
      "this.changeSelect();\n"
      "this.bindData();\n"
    "}\n"
"\n"
     //向后一月
    "Calendar.prototype.goNextMonth = function(e){\n"
      "if (this.year == this.endYear && this.month == 11){return;}\n"
      "this.month++;\n"
      "if (this.month == 12) {\n"
        "this.year++;\n"
        "this.month = 0;\n"
      "}\n"
      "this.date = new Date(this.year, this.month, 1);\n"
      "this.changeSelect();\n"
      "this.bindData();\n"
    "}\n"
"\n"
     //改变SELECT选中状态
    "Calendar.prototype.changeSelect = function() { \n"
      "var cy = this.calendarYear;\n"
      "var cm = this.calendarMonth;\n"
      "for (var i= 0; i < cy.length; i++){\n"
        "if (cy.options[i].value == this.date.getFullYear()){\n"
          "cy[i].selected = true;\n"
          "break;\n"
        "}\n"
      "}\n"
      "for (var i= 0; i < cm.length; i++){\n"
        "if (cm.options[i].value == this.date.getMonth()){\n"
          "cm[i].selected = true;\n"
          "break;\n"
        "}\n"
      "}\n"
    "}\n"
"\n"
     //更新年、月
    "Calendar.prototype.update = function (e){ \n"
      "this.year  = e.calendarYear.options[e.calendarYear.selectedIndex].value;\n"
      "this.month = e.calendarMonth.options[e.calendarMonth.selectedIndex].value;\n"
      "this.date = new Date(this.year, this.month, 1);\n"
      "this.changeSelect();\n"
      "this.bindData();\n"
    "}\n"
"\n"
     //绑定数据到月视图
    "Calendar.prototype.bindData = function () {\n"
      "var calendar = this;\n"
      "var dateArray = this.getMonthViewArray(this.date.getFullYear(), this.date.getMonth());\n"
      "var tds = this.getElementById(\"calendarTable\").getElementsByTagName(\"td\");\n"
      "for(var i = 0; i < tds.length; i++) {\n"
       //tds[i].style.color = calendar.colors[\"td_word_light\"];
      "tds[i].style.backgroundColor = calendar.colors[\"td_bg_out\"];\n"
        "tds[i].onclick = function () {return;}\n"
        "tds[i].onmouseover = function () {return;}\n"
        "tds[i].onmouseout = function () {return;}\n"
        "if (i > dateArray.length - 1) break;\n"
        "tds[i].innerHTML = dateArray[i];\n"
        "if (dateArray[i] != \"&nbsp;\"){\n"
          "tds[i].onclick = function () {\n"
            "if (calendar.dateControl != null){\n"
              "calendar.dateControl.value = new Date(calendar.date.getFullYear(),\n"
                                                    "calendar.date.getMonth(),\n"
                                                    "this.innerHTML).format(calendar.dateFormatStyle);\n"
            "}\n"
            "calendar.hide();\n"
          "}\n"
          "tds[i].onmouseover = function () {\n"
            "this.style.backgroundColor = calendar.colors[\"td_bg_over\"];\n"
          "}\n"
          "tds[i].onmouseout = function () {\n"
            "this.style.backgroundColor = calendar.colors[\"td_bg_out\"];\n"
          "}\n"
          "if (new Date().format(calendar.dateFormatStyle) ==\n"
              "new Date(calendar.date.getFullYear(),\n"
                       "calendar.date.getMonth(),\n"
                       "dateArray[i]).format(calendar.dateFormatStyle)) {\n"
             //tds[i].style.color = calendar.colors[\"cur_word\"];
            "tds[i].style.backgroundColor = calendar.colors[\"cur_bg\"];\n"
            "tds[i].onmouseover = function () {\n"
              "this.style.backgroundColor = calendar.colors[\"td_bg_over\"];\n"
            "}\n"
            "tds[i].onmouseout = function () {\n"
              "this.style.backgroundColor = calendar.colors[\"cur_bg\"];\n"
            "}\n"
             //continue; //若不想当天单元格的背景被下面的覆盖，请取消注释
          "}   \n"
          "\n"
          "if (calendar.dateControl != null && calendar.dateControl.value == new Date(calendar.date.getFullYear(),\n"
                       "calendar.date.getMonth(),\n"
                       "dateArray[i]).format(calendar.dateFormatStyle)) {\n"
            "tds[i].style.backgroundColor = calendar.colors[\"sel_bg\"];\n"
            "tds[i].onmouseover = function () {\n"
              "this.style.backgroundColor = calendar.colors[\"td_bg_over\"];\n"
            "}\n"
            "tds[i].onmouseout = function () {\n"
              "this.style.backgroundColor = calendar.colors[\"sel_bg\"];\n"
            "}\n"
          "}\n"
        "}\n"
      "}\n"
    "}\n"
"\n"
     //根据年、月得到月视图数据(数组形式)
    "Calendar.prototype.getMonthViewArray = function (y, m) {\n"
      "var mvArray = [];\n"
      "var dayOfFirstDay = new Date(y, m, 1).getDay();\n"
      "var daysOfMonth = new Date(y, m + 1, 0).getDate();\n"
      "for (var i = 0; i < 42; i++) {\n"
        "mvArray[i] = \"&nbsp;\";\n"
      "}\n"
      "for (var i = 0; i < daysOfMonth; i++){\n"
        "mvArray[i + dayOfFirstDay] = i + 1;\n"
      "}\n"
      "return mvArray;\n"
"\n"
       //  var dateArray = new Array(42);
       //  var dayOfFirstDate = new Date(y, m, 1).getDay();
       //  var dateCountOfMonth = new Date(y, m + 1, 0).getDate();
       //  for (var i = 0; i < dateCountOfMonth; i++) {
       //      dateArray[i + dayOfFirstDate] = i + 1;
       //  }
       //  return dateArray;
    "}\n"
"\n"
     //扩展 OBJ(id) 多浏览器兼容性 from meizz tree source
    "Calendar.prototype.getElementById = function(id){\n"
      "if (typeof(id) != \"string\" || id == \"\") return null;\n"
      "if (OBJ) return OBJ(id);\n"
      "if (document.all) return document.all(id);\n"
      "try {return eval(id);} catch(e){ return null;}\n"
    "}\n"
"\n"
     //扩展 object.getElementsByTagName(tagName)
    "Calendar.prototype.getElementsByTagName = function(object, tagName){\n"
      "if (document.getElementsByTagName) return document.getElementsByTagName(tagName);\n"
      "if (document.all) return document.all.tags(tagName);\n"
    "}\n"
"\n"
     //取得HTML控件绝对位置
    "Calendar.prototype.getAbsPoint = function (e){\n"
      "var x = e.offsetLeft;\n"
      "var y = e.offsetTop;\n"
      "while(e = e.offsetParent){\n"
        "x += e.offsetLeft;\n"
        "y += e.offsetTop;\n"
      "}\n"
      "return {\"x\": x, \"y\": y};\n"
    "}\n"
"\n"
     //显示日历
    "Calendar.prototype.show = function (dateObj, popControl) {\n"
      "if (dateObj == null){\n"
        "throw new Error(\"arguments[0] is necessary\")\n"
      "}\n"
      "this.dateControl = dateObj;\n"
      "\n"
      "this.date = (dateObj.value.length > 0) ? new Date(dateObj.value.toDate(this.dateFormatStyle)) : new Date();\n"
      "this.year = this.date.getFullYear();\n"
      "this.month = this.date.getMonth();\n"
      "this.changeSelect();\n"
      "this.bindData();\n"
      "\n"
      "if (popControl == null){\n"
        "popControl = dateObj;\n"
      "}\n"
      "var xy = this.getAbsPoint(popControl);\n"
      "this.panel.style.left = xy.x  + \"px\";\n"
      "this.panel.style.top = (xy.y + dateObj.offsetHeight) + \"px\"; \n"
     "\n"
      "this.panel.style.display = \"\";\n"
      "this.container.style.display = \"\";\n"
      "\n"
      "dateObj.onblur = function(){calendar.onblur();}\n"
      "this.container.onmouseover = function(){isFocus=true;}\n"
      "this.container.onmouseout = function(){isFocus=false;}\n"
    "}\n"
     //隐藏日历
    "Calendar.prototype.hide = function() {\n"
      "this.panel.style.display = \"none\";\n"
      "this.container.style.display = \"none\";\n"
      "isFocus=false;\n"
      "\n"
"\n"
     // --自定义验控件是否为空--
     //  try
     // {
         "CheckDate(objdate);\n"
     //  }
     //  catch(err)
     //  {
     //  }
    "}\n"
    "function CheckDate(obj) \n"
    "{\n"
         //var t = OBJ('txtPeriod').value;
        "var t = obj.value;\n"
        "var v = null;\n"
        "var tt = /^(\\d{1,4})(-|\\/)(\\d{1,2})\\2(\\d{1,2})$/;\n"
        "var dv = obj.id;\n"
            "dv=\"dv_\"+dv;\n"
        "var dvDate =OBJ(dv);\n"
        "\n"
        "if (dvDate == null)\n"
        "{\n"
            "return;\n"
        "}\n"
        "if(t!=\"\")\n"
        "{\n"
            "if(t.search(tt)!=-1)\n"
            "{\n"
                "\n"
                "dvDate.style.display = 'none';\n"
                "v = 0;  \n"
            "}\n"
            "else\n"
            "{\n"
                "dvDate.style.display = 'block';\n"
                "v = 1;\n"
            "}\n"
            "if(DateCompare(obj.value,datenow)==true)\n"
            "{\n"
                "v = 0;\n"
            "}\n"
            "else\n"
            "{\n"
                "dvDate.style.display = 'block';\n"
                "dvDate.innerHTML = \"  <font color=red>&nbsp;&nbsp;您的截止日期必须大于今天</font>\";\n"
                "v = 1\n"
            "}\n"
        "}\n"
        "else\n"
        "{\n"
            "dvDate.style.display = 'block';\n"
            "v = 1;\n"
        "}\n"
        "return v;\n"
    "}\n"
"\n"
     //焦点转移时隐藏日历
    "Calendar.prototype.onblur = function() {\n"
        "if(!isFocus){this.hide();}\n"
    "}\n"
    "document.write('<div id=\"ContainerPanel\" style=\"display:none\"><div id=\"calendarPanel\" style=\"position: absolute;display: none;z-index: 9999;');\n"
    "document.write('background-color: #FFFFFF;border: 1px solid #CCCCCC;width:175px;font-size:9px;\"></div>');\n"
    "if(document.all)\n"
    "{\n"
        "document.write('<iframe style=\"position:absolute;z-index:2000;width:expression(this.previousSibling.offsetWidth);');\n"
        "document.write('height:expression(this.previousSibling.offsetHeight);');\n"
        "document.write('left:expression(this.previousSibling.offsetLeft);top:expression(this.previousSibling.offsetTop);');\n"
        "document.write('display:expression(this.previousSibling.style.display);\" scrolling=\"no\" frameborder=\"no\"></iframe>');\n"
    "}\n"
    "document.write('</div>');\n"
    "</script>\n"
"</html>\n"
};
#endif
