#ifndef _HTML_H_035_H_
#define _HTML_H_035_H_
static const char h_035[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
	"<meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'/>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<style type='text/css'>\n"
            "html{_overflow-y:scroll;}\n"
            "body{\n"
             "margin:0;\n"
             "padding:0;\n"
             "text-align:center;\n"
             "font-size:14px;\n"
             "font-family:'微软雅黑',Verdana,'宋体',sans-serif;\n"
             "background-color:#fff;\n"
             "min-width:867px;\n"
             "margin-top: 4px;\n"
            "}\n"
            "img{vertical-align: top; display: block;}\n"
            ".title{margin:5px auto;width:90%;text-align:left;overflow:hidden;}\n"
            ".r1{margin:0 5px;height:1px;overflow:hidden;width:490px;}\n"
            ".r2{margin:0 3px;height:1px;overflow:hidden;width:494px;}\n"
            ".r3{margin:0 2px;height:1px;overflow:hidden;width:496px;}\n"
            ".r4{margin:0 1px;height:2px;overflow:hidden;width:498px;}\n"
            ".color{background-color:#F58E03;}\n"
            ".content{height:24px;line-height:24px;padding-left:20px;font-size:24px;color:#EEE;text-align:left;}\n"
            ".blank{height:4px;overflow:hidden;}\n"
            ".btm_blank{height:15px;overflow:hidden;}\n"
            ".back_color{background-color:#efefff;}\n"
            ".back_high{width:100%;height:240px;margin:0 auto;}\n"
            ".line_long{height:2px;overflow:hidden;margin:2px auto;background-color:#ccc; width:90%;}\n"
            ".img_common{float:right;margin-right:12px;width:50px;height:50px;}\n"
            ".bg1{background:transparent url(i_001.png) no-repeat scroll 0 0;}\n"
            ".bg2{background:transparent url(i_001.png) no-repeat scroll -50px 0;}\n"
            ".bg3{background:transparent url(i_001.png) no-repeat scroll -100px 0;}\n"
            ".bg4{background:transparent url(i_001.png) no-repeat scroll 0 -50px;}\n"
            ".bg5{background:transparent url(i_001.png) no-repeat scroll -50px -50px;}\n"
            ".bg6{background:transparent url(i_001.png) no-repeat scroll -100px -50px;}\n"
            ".bg7{background:transparent url(i_005.png) no-repeat scroll 0 0;}\n"
            ".bg8{background:transparent url(i_006.png) no-repeat scroll 0 0;}\n"
            ".bg9{background:transparent url(i_007.png) no-repeat scroll 0 0;}\n"
            ".name{text-align:left;font-size:14px;font-weight:normal;color:#000;}\n"
            ".value{text-align:left;font-size:18px;font-weight:bold;color:#06C;font-style:normal;}\n"
            ".div_query{margin:0px auto;width:90%;padding-left:100px;width:90%;float:left;height:30px;line-height:24px;font-size:16px;color:#000;}\n"
            ".date_label{width:150px;float:left;height:24px;}\n"
            ".div_btn{width:100px;float:left;margin-left:50px;text-align:center;font-weight: bold;color:#888;height:26px;}\n"
            ".color{background-color:#F58E03;}\n"
            ".color2{background-color:#aaa;}\n"
            ".date{width:100px;float:left;margin-left:10px;text-align:center;color:#00f;height:20px;}\n"
            ".Ftab{width:480px;height:20px;line-height:20px;padding-left:20px;font-size:18px;text-align:center;}\n"
            ".Ftab span{margin:0;padding:0;float:left;width:48%;color:#fff;}\n"
            ".Ftab .select{background: #007B3E;}\n"
        "</style>\n"
        "<script src='j_000.js' type='text/javascript'></script>\n"
        "<script type=\"text/javascript\" src=\"jquery.min.js\"></script>\n"
        "<script type=\"text/javascript\" src=\"j_highcharts.js\"></script>\n"
        "<script type=\"text/javascript\" src=\"j_exporting.js\"></script>\n"
        "<script type=\"text/javascript\" src=\"j_canvas-tools.js\"></script>\n"
        "<script type=\"text/javascript\" src=\"j_export-csv.js\"></script>\n"
        "<script type=\"text/javascript\" src=\"j_highcharts-export-clientside.js\"></script>\n"
        "<script type='text/javascript'>\n"
            "function show_T(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
                "str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
                "document.write(str);\n"
            "}\n"
        "</script> \n"
    "</head>\n"
    "<body onload='Init()'>  \n"
        "<div class='title'>\n"
            "<div class='r1 color2'></div><div class='r2 color2'></div><div class='r3 color2'></div><div class='r4 color2'></div>\n"
            "<div class='Ftab color2' id=\"tabFunc\">\n"
                "<span class='select' id='N02'></span><span id='N03'></span>\n"
            "</div>  \n"
            "<div class='r4 color2'></div><div class='r3 color2'></div><div class='r2 color2'></div><div class='r1 color2'></div>\n"
        "</div>\n"
        "<div class='blank'></div>\n"
        "<div id='query' class='div_query'>\n"
            "<span class='date_label' id='N20'></span>\n"
            "<input id='DATE' class='date' type=\"text\" onClick=\"SelectDate(this,'yyyy-MM-dd',language)\"/>\n"
            "<button class='div_btn' onclick='doSubmit()'><span id='N21'></span></button>\n"
        "</div>\n"
        "<div id=\"curver\" width='90%' style=\"height: 600px;padding-left:2%; min-width: 780px; padding-right:5%;\"></div>\n"
        "<br/><img id='waiting' style='margin:0 auto;z-index:20000;position:relative;top:-368px;visibility:hidden;' src='i_002.gif'/><br/> \n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script>\n"
        "var fresh_time;\n"
        "var tab_index=0;\n"
        "var CurRecordIndex=1;\n"
        "var busy = false;\n"
        "var btns = OBJ('tabFunc').getElementsByTagName('span');\n"
        "for (var i = 0; i < btns.length; i++) {\n"
            "btns[i].index = i;\n"
            "btns[i].onclick = function(){\n"
                "tab_index = this.index;\n"
                "for (var i = 0; i < btns.length; i++) { btns[i].className = ''; };\n"
                "this.className = 'select';\n"
                "Switch_Tab(tab_index);\n"
            "}\n"
        "};\n"
        "function Switch_Tab(index)\n"
        "{             \n"
            "if(busy) return;\n"
            "for (var i = 0; i < btns.length; i++) { btns[i].className = ''; };\n"
            "btns[index].className = 'select';\n"
            "if(tab_index==0){\n"
                "var URL ='s_035.html?0x0000&time='+Math.random();\n"
                "var xmlhttp;\n"
                "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                "xmlhttp.onreadystatechange=function() \n"
                "{\n"
                    "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                    "{\n"
                        "eval('Json='+xmlhttp.responseText);\n"
                        "if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                         //实时数据
                        "OBJ('query').style.display='none';\n"
                        "if(chart!=undefined)chart.destroy();\n"
                        "ConfigureChart();\n"
                        "CreateChart();  \n"
                        "read_data(1);\n"
                        "fresh_time=setInterval('ajax_s()',interval_time);\n"
                    "}\n"
                "}            \n"
                "xmlhttp.open('GET',URL,true);\n"
                "xmlhttp.send();  \n"
            "}else{\n"
                "var URL ='s_035.html?0x0000&time='+Math.random();\n"
                "var xmlhttp;\n"
                "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                "xmlhttp.onreadystatechange=function() \n"
                "{\n"
                    "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                    "{\n"
                        "eval('Json='+xmlhttp.responseText);\n"
                        "if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                         //历史数据
                        "OBJ('query').style.display='block';\n"
                        "clearTimeout(fresh_time);\n"
                        "doSubmit();\n"
                    "}\n"
                "}            \n"
                "xmlhttp.open('GET',URL,true);\n"
                "xmlhttp.send();  \n"
            "}\n"
        "}\n"
    "</script>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var FromMobileDevice=false;\n"
        "function FromWhichDevice()\n"
        "{\n"
            "var sUserAgent=navigator.userAgent.toLowerCase();\n"
            "var Ipad=sUserAgent.match(/ipad/i)=='ipad';\n"
            "var IphoneOs=sUserAgent.match(/iphone os/i)=='iphone os';\n"
            "var Android=sUserAgent.match(/android/i)=='android';\n"
            "var WindowsPhone=sUserAgent.match(/windows phone/i)=='windows phone';\n"
            "if(Ipad||IphoneOs||Android||WindowsPhone)FromMobileDevice=true;\n"
            "else FromMobileDevice=false;\n"
        "}\n"
        "var language=0;\n"
        "var Json;\n"
        "var request_num=0;\n"
        "var lang=\n"
        "{\n"
            "N01:['XX','XX'],\n"
            "N02:['实时功率','Realtime Power'],\n"
            "N03:['记录','Record'],\n"
"\n"
            "N07:['导&nbsp;&nbsp;出','Export'],\n"
            "N08:['光伏逆变器功率','PV Power'],\n"
            "N09:['并网点功率','PCC Power'],\n"
            "N10:['储能逆变器功率','PCS Power'],\n"
"\n"
            "N20:['查询日期：','Inquery Date:'],\n"
            "N21:['查&nbsp;&nbsp;询','Inquery'],\n"
"\n"
            "N29:['导出/打印', 'Export/Print'],\n"
            "N30:['打印图表', 'Print Chart'],\n"
            "N31:['下载 JPEG 文件', 'Download JPEG'],\n"
            "N32:['下载 PNG 文件', 'Download PNG'],\n"
            "N33:['下载 SVG 文件', 'Download SVG'],\n"
            "N34:['下载 CSV 文件', 'Download CSV'],\n"
            "N35:['下载 XLS 文件', 'Download XLS'],\n"
"\n"
            "N500:['一共','Total '],\n"
            "N501:['页，共',' Pages, '],\n"
            "N502:['条',' Nums']\n"
        "};\n"
"\n"
        "var interval_time = 10000;\n"
        "var chart;\n"
        "var timer;\n"
   "\n"
        "function ConfigureChart()\n"
        "{\n"
            "Highcharts.setOptions({\n"
                "global: {\n"
                    "useUTC: false\n"
                "},\n"
                "lang: {\n"
                    "printChart: lang.N30[language],\n"
                    "downloadJPEG: lang.N31[language], \n"
                    "downloadPNG: lang.N32[language],\n"
                    "downloadSVG: lang.N33[language], \n"
                    "downloadCSV: lang.N34[language],\n"
                    "downloadXLS: lang.N35[language]\n"
                "},\n"
                "chart:{\n"
                    "renderTo: 'curver',\n"
                    "zoomType: 'x',\n"
                     //'spline' 'line' 'area'
                    "type: 'line',\n"
                     //背景色
                     //backgroundColor: '#eee',
                     //背景渐变
                     //backgroundColor: {
                     //    linearGradient: [0, 0, 500, 500],
                     //    stops: [
                     //        [0, 'rgb(255, 255, 255)'],
                     //        [1, 'rgb(200, 200, 255)']
                     //    ]
                     //},
                     //animation: Highcharts.svg,
                     //marginRight: 10
                "},\n"
                "title: {\n"
                    "text: ''\n"
                "},\n"
                "xAxis: {\n"
                     //X轴标题
                    "title: { text:'T(h)/'+ Json.D00+'-'+Json.D01+'-'+Json.D02 }, \n"
                    "showFirstLable: true,\n"
                    "showLastLabel: true,   \n"
                    "lineWidth: 2,\n"
                    "lineColor: '#808080',\n"
                    "tickColor: '#e0e0e0',             \n"
                     // The types are 'linear', 'logarithmic' and 'datetime'
                    "type: 'linear',    \n"
                    "categories: [\n"
                        "'0:00','0:01','0:02','0:03','0:04','0:05','0:06','0:07','0:08','0:09','0:10','0:11','0:12','0:13','0:14','0:15','0:16','0:17','0:18','0:19','0:20','0:21','0:22','0:23','0:24','0:25','0:26','0:27','0:28','0:29','0:30','0:31','0:32','0:33','0:34','0:35','0:36','0:37','0:38','0:39','0:40','0:41','0:42','0:43','0:44','0:45','0:46','0:47','0:48','0:49','0:50','0:51','0:52','0:53','0:54','0:55','0:56','0:57','0:58','0:59',\n"
                        "'1:00','1:01','1:02','1:03','1:04','1:05','1:06','1:07','1:08','1:09','1:10','1:11','1:12','1:13','1:14','1:15','1:16','1:17','1:18','1:19','1:20','1:21','1:22','1:23','1:24','1:25','1:26','1:27','1:28','1:29','1:30','1:31','1:32','1:33','1:34','1:35','1:36','1:37','1:38','1:39','1:40','1:41','1:42','1:43','1:44','1:45','1:46','1:47','1:48','1:49','1:50','1:51','1:52','1:53','1:54','1:55','1:56','1:57','1:58','1:59',\n"
                        "'2:00','2:01','2:02','2:03','2:04','2:05','2:06','2:07','2:08','2:09','2:10','2:11','2:12','2:13','2:14','2:15','2:16','2:17','2:18','2:19','2:20','2:21','2:22','2:23','2:24','2:25','2:26','2:27','2:28','2:29','2:30','2:31','2:32','2:33','2:34','2:35','2:36','2:37','2:38','2:39','2:40','2:41','2:42','2:43','2:44','2:45','2:46','2:47','2:48','2:49','2:50','2:51','2:52','2:53','2:54','2:55','2:56','2:57','2:58','2:59',\n"
                        "'3:00','3:01','3:02','3:03','3:04','3:05','3:06','3:07','3:08','3:09','3:10','3:11','3:12','3:13','3:14','3:15','3:16','3:17','3:18','3:19','3:20','3:21','3:22','3:23','3:24','3:25','3:26','3:27','3:28','3:29','3:30','3:31','3:32','3:33','3:34','3:35','3:36','3:37','3:38','3:39','3:40','3:41','3:42','3:43','3:44','3:45','3:46','3:47','3:48','3:49','3:50','3:51','3:52','3:53','3:54','3:55','3:56','3:57','3:58','3:59',\n"
                        "'4:00','4:01','4:02','4:03','4:04','4:05','4:06','4:07','4:08','4:09','4:10','4:11','4:12','4:13','4:14','4:15','4:16','4:17','4:18','4:19','4:20','4:21','4:22','4:23','4:24','4:25','4:26','4:27','4:28','4:29','4:30','4:31','4:32','4:33','4:34','4:35','4:36','4:37','4:38','4:39','4:40','4:41','4:42','4:43','4:44','4:45','4:46','4:47','4:48','4:49','4:50','4:51','4:52','4:53','4:54','4:55','4:56','4:57','4:58','4:59',\n"
                        "'5:00','5:01','5:02','5:03','5:04','5:05','5:06','5:07','5:08','5:09','5:10','5:11','5:12','5:13','5:14','5:15','5:16','5:17','5:18','5:19','5:20','5:21','5:22','5:23','5:24','5:25','5:26','5:27','5:28','5:29','5:30','5:31','5:32','5:33','5:34','5:35','5:36','5:37','5:38','5:39','5:40','5:41','5:42','5:43','5:44','5:45','5:46','5:47','5:48','5:49','5:50','5:51','5:52','5:53','5:54','5:55','5:56','5:57','5:58','5:59',\n"
                        "'6:00','6:01','6:02','6:03','6:04','6:05','6:06','6:07','6:08','6:09','6:10','6:11','6:12','6:13','6:14','6:15','6:16','6:17','6:18','6:19','6:20','6:21','6:22','6:23','6:24','6:25','6:26','6:27','6:28','6:29','6:30','6:31','6:32','6:33','6:34','6:35','6:36','6:37','6:38','6:39','6:40','6:41','6:42','6:43','6:44','6:45','6:46','6:47','6:48','6:49','6:50','6:51','6:52','6:53','6:54','6:55','6:56','6:57','6:58','6:59',\n"
                        "'7:00','7:01','7:02','7:03','7:04','7:05','7:06','7:07','7:08','7:09','7:10','7:11','7:12','7:13','7:14','7:15','7:16','7:17','7:18','7:19','7:20','7:21','7:22','7:23','7:24','7:25','7:26','7:27','7:28','7:29','7:30','7:31','7:32','7:33','7:34','7:35','7:36','7:37','7:38','7:39','7:40','7:41','7:42','7:43','7:44','7:45','7:46','7:47','7:48','7:49','7:50','7:51','7:52','7:53','7:54','7:55','7:56','7:57','7:58','7:59',\n"
                        "'8:00','8:01','8:02','8:03','8:04','8:05','8:06','8:07','8:08','8:09','8:10','8:11','8:12','8:13','8:14','8:15','8:16','8:17','8:18','8:19','8:20','8:21','8:22','8:23','8:24','8:25','8:26','8:27','8:28','8:29','8:30','8:31','8:32','8:33','8:34','8:35','8:36','8:37','8:38','8:39','8:40','8:41','8:42','8:43','8:44','8:45','8:46','8:47','8:48','8:49','8:50','8:51','8:52','8:53','8:54','8:55','8:56','8:57','8:58','8:59',\n"
                        "'9:00','9:01','9:02','9:03','9:04','9:05','9:06','9:07','9:08','9:09','9:10','9:11','9:12','9:13','9:14','9:15','9:16','9:17','9:18','9:19','9:20','9:21','9:22','9:23','9:24','9:25','9:26','9:27','9:28','9:29','9:30','9:31','9:32','9:33','9:34','9:35','9:36','9:37','9:38','9:39','9:40','9:41','9:42','9:43','9:44','9:45','9:46','9:47','9:48','9:49','9:50','9:51','9:52','9:53','9:54','9:55','9:56','9:57','9:58','9:59',\n"
                        "'10:00','10:01','10:02','10:03','10:04','10:05','10:06','10:07','10:08','10:09','10:10','10:11','10:12','10:13','10:14','10:15','10:16','10:17','10:18','10:19','10:20','10:21','10:22','10:23','10:24','10:25','10:26','10:27','10:28','10:29','10:30','10:31','10:32','10:33','10:34','10:35','10:36','10:37','10:38','10:39','10:40','10:41','10:42','10:43','10:44','10:45','10:46','10:47','10:48','10:49','10:50','10:51','10:52','10:53','10:54','10:55','10:56','10:57','10:58','10:59',\n"
                        "'11:00','11:01','11:02','11:03','11:04','11:05','11:06','11:07','11:08','11:09','11:10','11:11','11:12','11:13','11:14','11:15','11:16','11:17','11:18','11:19','11:20','11:21','11:22','11:23','11:24','11:25','11:26','11:27','11:28','11:29','11:30','11:31','11:32','11:33','11:34','11:35','11:36','11:37','11:38','11:39','11:40','11:41','11:42','11:43','11:44','11:45','11:46','11:47','11:48','11:49','11:50','11:51','11:52','11:53','11:54','11:55','11:56','11:57','11:58','11:59',\n"
                        "'12:00','12:01','12:02','12:03','12:04','12:05','12:06','12:07','12:08','12:09','12:10','12:11','12:12','12:13','12:14','12:15','12:16','12:17','12:18','12:19','12:20','12:21','12:22','12:23','12:24','12:25','12:26','12:27','12:28','12:29','12:30','12:31','12:32','12:33','12:34','12:35','12:36','12:37','12:38','12:39','12:40','12:41','12:42','12:43','12:44','12:45','12:46','12:47','12:48','12:49','12:50','12:51','12:52','12:53','12:54','12:55','12:56','12:57','12:58','12:59',\n"
                        "'13:00','13:01','13:02','13:03','13:04','13:05','13:06','13:07','13:08','13:09','13:10','13:11','13:12','13:13','13:14','13:15','13:16','13:17','13:18','13:19','13:20','13:21','13:22','13:23','13:24','13:25','13:26','13:27','13:28','13:29','13:30','13:31','13:32','13:33','13:34','13:35','13:36','13:37','13:38','13:39','13:40','13:41','13:42','13:43','13:44','13:45','13:46','13:47','13:48','13:49','13:50','13:51','13:52','13:53','13:54','13:55','13:56','13:57','13:58','13:59',\n"
                        "'14:00','14:01','14:02','14:03','14:04','14:05','14:06','14:07','14:08','14:09','14:10','14:11','14:12','14:13','14:14','14:15','14:16','14:17','14:18','14:19','14:20','14:21','14:22','14:23','14:24','14:25','14:26','14:27','14:28','14:29','14:30','14:31','14:32','14:33','14:34','14:35','14:36','14:37','14:38','14:39','14:40','14:41','14:42','14:43','14:44','14:45','14:46','14:47','14:48','14:49','14:50','14:51','14:52','14:53','14:54','14:55','14:56','14:57','14:58','14:59',\n"
                        "'15:00','15:01','15:02','15:03','15:04','15:05','15:06','15:07','15:08','15:09','15:10','15:11','15:12','15:13','15:14','15:15','15:16','15:17','15:18','15:19','15:20','15:21','15:22','15:23','15:24','15:25','15:26','15:27','15:28','15:29','15:30','15:31','15:32','15:33','15:34','15:35','15:36','15:37','15:38','15:39','15:40','15:41','15:42','15:43','15:44','15:45','15:46','15:47','15:48','15:49','15:50','15:51','15:52','15:53','15:54','15:55','15:56','15:57','15:58','15:59',\n"
                        "'16:00','16:01','16:02','16:03','16:04','16:05','16:06','16:07','16:08','16:09','16:10','16:11','16:12','16:13','16:14','16:15','16:16','16:17','16:18','16:19','16:20','16:21','16:22','16:23','16:24','16:25','16:26','16:27','16:28','16:29','16:30','16:31','16:32','16:33','16:34','16:35','16:36','16:37','16:38','16:39','16:40','16:41','16:42','16:43','16:44','16:45','16:46','16:47','16:48','16:49','16:50','16:51','16:52','16:53','16:54','16:55','16:56','16:57','16:58','16:59',\n"
                        "'17:00','17:01','17:02','17:03','17:04','17:05','17:06','17:07','17:08','17:09','17:10','17:11','17:12','17:13','17:14','17:15','17:16','17:17','17:18','17:19','17:20','17:21','17:22','17:23','17:24','17:25','17:26','17:27','17:28','17:29','17:30','17:31','17:32','17:33','17:34','17:35','17:36','17:37','17:38','17:39','17:40','17:41','17:42','17:43','17:44','17:45','17:46','17:47','17:48','17:49','17:50','17:51','17:52','17:53','17:54','17:55','17:56','17:57','17:58','17:59',\n"
                        "'18:00','18:01','18:02','18:03','18:04','18:05','18:06','18:07','18:08','18:09','18:10','18:11','18:12','18:13','18:14','18:15','18:16','18:17','18:18','18:19','18:20','18:21','18:22','18:23','18:24','18:25','18:26','18:27','18:28','18:29','18:30','18:31','18:32','18:33','18:34','18:35','18:36','18:37','18:38','18:39','18:40','18:41','18:42','18:43','18:44','18:45','18:46','18:47','18:48','18:49','18:50','18:51','18:52','18:53','18:54','18:55','18:56','18:57','18:58','18:59',\n"
                        "'19:00','19:01','19:02','19:03','19:04','19:05','19:06','19:07','19:08','19:09','19:10','19:11','19:12','19:13','19:14','19:15','19:16','19:17','19:18','19:19','19:20','19:21','19:22','19:23','19:24','19:25','19:26','19:27','19:28','19:29','19:30','19:31','19:32','19:33','19:34','19:35','19:36','19:37','19:38','19:39','19:40','19:41','19:42','19:43','19:44','19:45','19:46','19:47','19:48','19:49','19:50','19:51','19:52','19:53','19:54','19:55','19:56','19:57','19:58','19:59',\n"
                        "'20:00','20:01','20:02','20:03','20:04','20:05','20:06','20:07','20:08','20:09','20:10','20:11','20:12','20:13','20:14','20:15','20:16','20:17','20:18','20:19','20:20','20:21','20:22','20:23','20:24','20:25','20:26','20:27','20:28','20:29','20:30','20:31','20:32','20:33','20:34','20:35','20:36','20:37','20:38','20:39','20:40','20:41','20:42','20:43','20:44','20:45','20:46','20:47','20:48','20:49','20:50','20:51','20:52','20:53','20:54','20:55','20:56','20:57','20:58','20:59',\n"
                        "'21:00','21:01','21:02','21:03','21:04','21:05','21:06','21:07','21:08','21:09','21:10','21:11','21:12','21:13','21:14','21:15','21:16','21:17','21:18','21:19','21:20','21:21','21:22','21:23','21:24','21:25','21:26','21:27','21:28','21:29','21:30','21:31','21:32','21:33','21:34','21:35','21:36','21:37','21:38','21:39','21:40','21:41','21:42','21:43','21:44','21:45','21:46','21:47','21:48','21:49','21:50','21:51','21:52','21:53','21:54','21:55','21:56','21:57','21:58','21:59',\n"
                        "'22:00','22:01','22:02','22:03','22:04','22:05','22:06','22:07','22:08','22:09','22:10','22:11','22:12','22:13','22:14','22:15','22:16','22:17','22:18','22:19','22:20','22:21','22:22','22:23','22:24','22:25','22:26','22:27','22:28','22:29','22:30','22:31','22:32','22:33','22:34','22:35','22:36','22:37','22:38','22:39','22:40','22:41','22:42','22:43','22:44','22:45','22:46','22:47','22:48','22:49','22:50','22:51','22:52','22:53','22:54','22:55','22:56','22:57','22:58','22:59',\n"
                        "'23:00','23:01','23:02','23:03','23:04','23:05','23:06','23:07','23:08','23:09','23:10','23:11','23:12','23:13','23:14','23:15','23:16','23:17','23:18','23:19','23:20','23:21','23:22','23:23','23:24','23:25','23:26','23:27','23:28','23:29','23:30','23:31','23:32','23:33','23:34','23:35','23:36','23:37','23:38','23:39','23:40','23:41','23:42','23:43','23:44','23:45','23:46','23:47','23:48','23:49','23:50','23:51','23:52','23:53','23:54','23:55','23:56','23:57','23:58','23:59'\n"
                    "]\n"
                "},\n"
                "yAxis: {\n"
                     //Y轴标题
                    "title: { text: 'P(Kw)' },\n"
                    "showEmpty: false,\n"
                    "lineWidth: 2,\n"
                    "lineColor: '#808080',\n"
                     //隔行显示颜色
                     //alternateGridColor: '#FDFFD5',
                     //网格线颜色
                    "gridLineColor: '#e0e0e0',\n"
                    "gridLineWidth: 1,\n"
                    "labels: {\n"
                        "formatter: function() {\n"
                            "return  this.value + ' Kw';\n"
                        "}\n"
                    "},\n"
                     //max: 500,
                     //min: -500,
                    "plotLines: [{\n"
                        "value: 0,\n"
                        "width: 1,\n"
                        "color: '#808080'\n"
                    "}]\n"
                "},\n"
                "plotOptions: {\n"
                      //针对图形类型的设置 'spline' 'line' 'area'
                    "area: {\n"
                        "allowPointSelect:true,\n"
                        "fillOpacity:0.6,\n"
                        "marker:{\n"
                            "enabled: false,\n"
                                "states: {\n"
                                "hover: {\n"
                                    "enabled: true,\n"
                                    "symbol: 'circle',\n"
                                    "radius: 2,\n"
                                    "lineWidth: 1\n"
                                "}\n"
                            "}\n"
                        "}\n"
                    "},\n"
                    "series: {\n"
                        "animation: false,\n"
                        "marker:{\n"
                            "enabled: false\n"
                        "}\n"
                    "}\n"
                "},\n"
                "tooltip: {\n"
                    "formatter: function() {\n"
                        "return '<b><span style=\"color:'+this.series.color+'\">'+ this.series.name +'</span></b><br/>'+\n"
                        "Highcharts.numberFormat(this.y, 1) + ' Kw';\n"
                    "}\n"
                "},\n"
                 //版本信息
                "credits: {\n"
                    "text: ''\n"
                "},\n"
                "navigation: {\n"
                    "buttonOptions: {\n"
                        "enabled: true,\n"
                        "theme: {\n"
                            "style: {\n"
                                "color: '#0000FF',\n"
                                "textDecoration: 'underline'\n"
                            "}\n"
                        "}\n"
                    "}\n"
                "},\n"
                "exporting: {\n"
                     //enabled:true, //默认为可用，当设置为false时，图表的打印及导出功能失效
                     //配置按钮选项
                    "buttons:{   \n"
                        "contextButton: {\n"
                            "text: lang.N29[language],\n"
                            "symbol: 'circle',\n"
                            "symbolFill: '#A349A4',\n"
                            "x: 500,\n"
                            "y: 2,\n"
                            "align: 'left'\n"
                             //menuItems: [
                             //    Highcharts.getOptions().exporting.buttons.contextButton.menuItems[1],
                             //    Highcharts.getOptions().exporting.buttons.contextButton.menuItems[2],
                             //    Highcharts.getOptions().exporting.buttons.contextButton.menuItems[3],
                             //    Highcharts.getOptions().exporting.buttons.contextButton.menuItems[4],
                             //    Highcharts.getOptions().exporting.buttons.contextButton.menuItems[5],
                             //    Highcharts.getOptions().exporting.buttons.contextButton.menuItems[6],
                             //    Highcharts.getOptions().exporting.buttons.contextButton.menuItems[7]
                             //]
                             //禁止导出列表子项显示
                             //menuItems: null,
                             //点击导出按钮时直接导出
                             //onclick: function () { this.exportChart(); }
                        "},\n"
                         //配置打印按钮
                         //printButton:{   
                         //    width:50,
                         //    symbolSize:20,
                         //    borderWidth:2,
                         //    borderRadius:0,
                         //    hoverBorderColor:'red',
                         //    height:30,
                         //    symbolX:25,
                         //    symbolY:15,
                         //    x:-200,
                         //    y:20
                         //},
                         //配置导出按钮
                         //exportButton:{  
                         //    width:50,
                         //    symbolSize:20,
                         //    borderWidth:2,
                         //    borderRadius:0,
                         //    hoverBorderColor:'red',
                         //    height:30,
                         //    symbolX:25,
                         //    symbolY:15,
                         //    x:-150,
                         //    y:20
                         //}
                    "},\n"
                    "chartOptions: {\n"
                        "plotOptions: {\n"
                            "series: {\n"
                                "dataLabels: {\n"
                                     //导出时显示数据标签
                                    "enabled: true\n"
                                "}\n"
                            "}\n"
                        "}\n"
                    "},\n"
                    "filename:'pls',\n"
                     //type:'image/png',
                     //width:800,
                     //height:600  
                "},\n"
                 //图例
                "legend: {\n"
                    "backgroundColor: '#FCFFC5',\n"
                    "borderColor: '#C98657',\n"
                    "borderWidth: 1,\n"
                     //layout: 'vertical',
                    "layout: 'horizontal',\n"
                    "itemDistance: 10,\n"
                    "backgroundColor: '#FFFFFF',\n"
                    "floating: true,\n"
                    "align: 'left',\n"
                    "verticalAlign: 'top',\n"
                    "x: 80,\n"
                    "y: 0,\n"
                    "labelFormatter: function () {\n"
                        "return this.name;\n"
                    "}\n"
                "}\n"
            "});\n"
        "}\n"
        "function CreateChart()\n"
        "{\n"
            "chart = new Highcharts.Chart({\n"
                "events: {\n"
                    "redraw: function () {\n"
                        "var label = this.renderer.label('The chart was just redrawn', 100, 120)\n"
                            ".attr({\n"
                                "fill: Highcharts.getOptions().colors[0],\n"
                                "padding: 10,\n"
                                "r: 5,\n"
                                "zIndex: 8\n"
                            "})\n"
                            ".css({\n"
                                "color: '#FFFFFF'\n"
                            "})\n"
                            ".add();\n"
"\n"
                        "setTimeout(function () {\n"
                            "label.fadeOut();\n"
                        "}, 1000);\n"
                    "}\n"
                "},\n"
                 //数据段
                "series: \n"
                "[   \n"
                    "{\n"
                        "type: 'line',\n"
                         //ShortDash,LongDash,ShortDot,ShortDashDot,DashDot
                        "dashStyle:\"ShortDash\",\n"
                        "name: lang.N08[language],\n"
                         //线段颜色
                         //lineColor: '#303030',
                         //线段或区域颜色
                        "color: '#F7A35C',\n"
                         //数据段1初始化
                        "data: (function() {\n"
                            "var data = [];\n"
                            "for (var i = 0; i < 1440; i++) data.push(0);\n"
                            "return data;\n"
                        "})()\n"
                    "},\n"
                    "{\n"
                        "type: 'area',\n"
                        "name: lang.N09[language],\n"
                         //线段颜色
                         //lineColor: '#303030',
                         //线段或区域颜色
                        "color: '#90ED7D',\n"
                         //数据段2初始化
                        "data: (function() {\n"
                            "var data = [];\n"
                            "for (var i = 0; i < 1440; i++) data.push(0);\n"
                            "return data;\n"
                        "})()\n"
                    "},\n"
                    "{\n"
                        "type: 'area',\n"
                        "name: lang.N10[language],\n"
                         //线段颜色
                         //lineColor: '#303030',
                         //线段或区域颜色
                        "color: '#99D9EA',\n"
                         //数据段2初始化
                        "data: (function() {\n"
                            "var data = [];\n"
                            "for (var i = 0; i < 1440; i++) data.push(0);\n"
                            "return data;\n"
                        "})()\n"
                    "}\n"
                "]\n"
            "});    \n"
        "}\n"
"\n"
        "function Init()\n"
        "{\n"
            "FromWhichDevice();\n"
            "var URL ='s_035.html?0x0000&time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function() \n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);\n"
                    "if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                    "request_num = Json.T;\n"
                    "OBJ('N02').innerHTML=lang.N02[language];\n"
                    "OBJ('N03').innerHTML=lang.N03[language];\n"
                     //OBJ('N04').innerHTML=lang.N04[language];
                     //OBJ('N05').innerHTML=lang.N05[language];
                     //OBJ('N06').innerHTML=lang.N06[language];
                    "OBJ('N20').innerHTML=lang.N20[language];\n"
                    "OBJ('N21').innerHTML=lang.N21[language];\n"
                    "var d = new Date();\n"
                    "var year = d.getYear()-100;\n"
                    "var month = d.getMonth() + 1;\n"
                    "var day = d.getDate();    \n"
                    "OBJ('DATE').value=(year+2000)+'-'+(month<10?'0'+month:month)+'-'+(day<10?'0'+day:day);\n"
                 "\n"
                    "Switch_Tab(0);\n"
                "}\n"
            "}            \n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();      \n"
        "}\n"
         //type: 1 读实时数据, 2 读历史数据
         //D00 - 月，D01 - 日， P - 数据段(1440个点15个段), T - 需要传送的总段数(根据当前时间确定需要传送的总段数, 如果P == T请求数据结束), 96x3个数据
        "function read_data(type)\n"
        "{\n"
             //for(var j = 0; j < request_num; j++)
            "for(var j = 0; j < 15; j++)\n"
            "{\n"
                "var URL;\n"
                "if(type == 1){\n"
                    "URL ='s_035.html?0x000'+type+'&part=0x'+j.toString(16)+'&time='+Math.random();\n"
                "}else if(type == 2){\n"
                    "var time=OBJ('DATE').value.split('-');\n"
                    "var URL='r_035.html?'+'Y='+time[0]+'&M='+time[1]+'&D='+time[2]+'&part='+j+'&time='+Math.random();\n"
                "}\n"
"\n"
                "$.ajax({\n"
                    "url:URL,\n"
                    "type:\"get\",\n"
                    "contentType:\"application/text;charset=utf-8\",\n"
                    "dataType:\"text\",\n"
                    "async: false,\n"
                    "timeout : 5000,\n"
                    "beforeSend:function()\n"
                    "{\n"
                        "if(type != 1)OBJ('waiting').style.visibility='visible';\n"
                        "busy=true;\n"
                    "},\n"
                    "success:function(data)\n"
                    "{\n"
                        "eval('Json='+data);\n"
                        "if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                        "var k,dat1,dat2,dat3;\n"
                        "for(var i=0; i<96; i++)\n"
                        "{\n"
                            "Json.P = j; \n"
                            "eval('dat1=Json.A'+i+';');\n"
                            "eval('dat2=Json.B'+i+';');\n"
                            "eval('dat3=Json.C'+i+';');\n"
                             //测试
                             //dat1=(Math.random()*1.3+40);
                             //dat2=(Math.random()*1.3+50);
                             //dat3=(Math.random()*1.3+60);
                            "k = i+96*Json.P;\n"
                            "chart.series[0].data[k].update(dat1,false);\n"
                            "chart.series[1].data[k].update(dat2,false);\n"
                            "chart.series[2].data[k].update(dat3,false);\n"
                        "}\n"
                        "chart.redraw();\n"
                        "OBJ('waiting').style.visibility='hidden';\n"
                        "busy=false;\n"
                    "},\n"
                    "complete:function(XMLHttpRequest,status)\n"
                    "{\n"
                         //超时
                        "if(status=='timeout'){\n"
                            "OBJ('waiting').style.visibility='hidden';\n"
                            "busy=false;\n"
                        "}\n"
                    "}\n"
                "});            \n"
            "}\n"
        "}\n"
"\n"
         //type: 0x0002 实时获取一个点的数据
         //Index: 点的位置, Pa: 曲线1点值, Pb: 曲线2点值, Pc：曲线3点值
        "function ajax_s()\n"
        "{\n"
            "var URL ='s_035.html?0x0002&time='+Math.random();\n"
"\n"
            "$.ajax({\n"
                "url:URL,\n"
                "type:\"get\",\n"
                "contentType:\"application/text;charset=utf-8\",\n"
                "dataType:\"text\",\n"
                "async: true,\n"
                "timeout : 5000,\n"
                "beforeSend:function()\n"
                "{\n"
                     //OBJ('waiting').style.visibility='visible';
                    "busy=true;\n"
                "},\n"
                "success:function(data)\n"
                "{\n"
                    "eval('Json='+data);\n"
                    "if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
"\n"
                     //Json={Index: 10, Pa: 11.1, Pb: 23.4, Pc: 46.8};
"\n"
                    "var dat1=Json.Pa;\n"
                    "var dat2=Json.Pb;\n"
                    "var dat3=Json.Pc;\n"
                     //var dat1=(Math.random()*1.3+40);
                     //var dat2=(Math.random()*1.3+50);
                     //var dat3=(Math.random()*1.3+60);
                    "chart.series[0].data[Json.Index].update(dat1,false);\n"
                    "chart.series[1].data[Json.Index].update(dat2,false);\n"
                    "chart.series[2].data[Json.Index].update(dat3,false);\n"
                    "chart.redraw();\n"
                     //OBJ('waiting').style.visibility='hidden';
                    "busy=false;\n"
                "},\n"
                "complete:function(XMLHttpRequest,status)\n"
                "{\n"
                     //超时
                    "if(status=='timeout'){\n"
                         //OBJ('waiting').style.visibility='hidden';
                        "busy=false;\n"
                    "}\n"
                "}\n"
            "});\n"
        "}\n"
         //读历史数据
        "function doSubmit(obj)\n"
        "{\n"
            "var time=OBJ('DATE').value.split('-');\n"
            "Json.D00 = time[0];\n"
            "Json.D01 = time[1];\n"
            "Json.D02 = time[2];\n"
            "if(chart!=undefined)chart.destroy();\n"
            "ConfigureChart();\n"
            "CreateChart();   \n"
            "read_data(2);\n"
        "}\n"
    "</script>  \n"
    "<script>\n"
     //日期控件
    "var cal;\n"
     //是否为焦点
    "var isFocus=false; \n"
     //自加
    "var objdate;\n"
"\n"
    "var objdate1;\n"
"\n"
     //选择日期  lang: 0 --中文， 1--英文
    "function SelectDate(obj,strFormat,lang)\n"
    "{\n"
         //自加
        "objdate = obj;\n"
        "var date = new Date();\n"
         //最小值 → 50 年前
        "var by = date.getFullYear()-50;  \n"
         //最大值 → 50 年后
        "var ey = date.getFullYear()+50;  \n"
         //初始化英文版，0 为中文版
        "cal = (cal==null) ? new Calendar(by, ey, lang) : cal;    \n"
        "cal.dateFormatStyle = strFormat;\n"
        "cal.show(obj);\n"
    "}\n"
"\n"
     // * 返回日期
     // * @param d the delimiter
     // * @param p the pattern of your date
     // * 根据用户指定的 style 来确定；
     //String.prototype.toDate = function(x, p) {
    "String.prototype.toDate = function(style) {\n"
      "var y = this.substring(style.indexOf('y'),style.lastIndexOf('y')+1);\n"
      "var m = this.substring(style.indexOf('M'),style.lastIndexOf('M')+1);\n"
      "var d = this.substring(style.indexOf('d'),style.lastIndexOf('d')+1);\n"
      "if(isNaN(y)) y = new Date().getFullYear();\n"
      "if(isNaN(m)) m = new Date().getMonth();\n"
      "if(isNaN(d)) d = new Date().getDate();\n"
      "var dt ;\n"
      "eval (\"dt = new Date('\"+ y+\"', '\"+(m-1)+\"','\"+ d +\"')\");\n"
      "return dt;\n"
    "}\n"
"\n"
     // * 格式化日期
     // * @param   d the delimiter
     // * @param   p the pattern of your date
     // * @author  meizz
    "Date.prototype.format = function(style) {\n"
      "var o = {\n"
        "\"M+\" : this.getMonth() + 1, \n"
        "\"d+\" : this.getDate(),     \n"
        "\"h+\" : this.getHours(),    \n"
        "\"m+\" : this.getMinutes(),   \n"
        "\"s+\" : this.getSeconds(),   \n"
        "\"w+\" : \"天一二三四五六\".charAt(this.getDay()),  \n"
        "\"q+\" : Math.floor((this.getMonth() + 3) / 3),  \n"
        "\"S\"  : this.getMilliseconds() \n"
      "}\n"
      "if(/(y+)/.test(style)) {\n"
        "style = style.replace(RegExp.$1,\n"
        "(this.getFullYear() + \"\").substr(4 - RegExp.$1.length));\n"
      "}\n"
      "for(var k in o){\n"
        "if(new RegExp(\"(\"+ k +\")\").test(style)){\n"
          "style = style.replace(RegExp.$1,\n"
            "RegExp.$1.length == 1 ? o[k] :\n"
            "(\"00\" + o[k]).substr((\"\" + o[k]).length));\n"
        "}\n"
      "}\n"
      "return style;\n"
    "};\n"
"\n"
     // * 日历类
     // * @param   beginYear 1990
     // * @param   endYear   2010
     // * @param   lang      0(中文)|1(英语) 可自由扩充
     // * @param   dateFormatStyle  \"yyyy-MM-dd\";
     // * @version 2006-04-01
     // * @author  KimSoft (jinqinghua [at] gmail.com)
     // * @update
    "function Calendar(beginYear, endYear, lang, dateFormatStyle) {\n"
      "this.beginYear = 1990;\n"
      "this.endYear = 2010;\n"
       //0(中文) | 1(英文)
      "this.lang = 0;            \n"
      "this.dateFormatStyle = \"yyyy-MM-dd\";\n"
"\n"
      "if (beginYear != null && endYear != null){\n"
        "this.beginYear = beginYear;\n"
        "this.endYear = endYear;\n"
      "}\n"
      "if (lang != null){\n"
        "this.lang = lang\n"
      "}\n"
"\n"
      "if (dateFormatStyle != null){\n"
        "this.dateFormatStyle = dateFormatStyle\n"
      "}\n"
"\n"
      "this.dateControl = null;\n"
      "this.panel = this.getElementById(\"calendarPanel\");\n"
      "this.container = this.getElementById(\"ContainerPanel\");\n"
      "this.form  = null;\n"
"\n"
      "this.date = new Date();\n"
      "this.year = this.date.getFullYear();\n"
      "this.month = this.date.getMonth();\n"
"\n"
      "this.colors = {\n"
           //当日日期文字颜色
          "\"cur_word\"      : \"#FFFFFF\",  \n"
           //当日日期单元格背影色
          "\"cur_bg\"        : \"#00FF00\",  \n"
           //已被选择的日期单元格背影色 2006-12-03 寒羽枫添加
          "\"sel_bg\"        : \"#FFCCCC\",  \n"
           //星期天文字颜色
          "\"sun_word\"      : \"#FF0000\",  \n"
           //星期六文字颜色
          "\"sat_word\"      : \"#0000FF\",  \n"
           //单元格文字颜色
          "\"td_word_light\" : \"#333333\",  \n"
           //单元格文字暗色
          "\"td_word_dark\"  : \"#CCCCCC\",  \n"
           //单元格背影色
          "\"td_bg_out\"     : \"#EFEFEF\", \n"
           //单元格背影色 
          "\"td_bg_over\"    : \"#FFCC00\", \n"
           //日历头文字颜色 
          "\"tr_word\"       : \"#FFFFFF\", \n"
           //日历头背影色 
          "\"tr_bg\"         : \"#666666\", \n"
           //input控件的边框颜色 
          "\"input_border\"  : \"#CCCCCC\",\n"
           //input控件的背影色  
          "\"input_bg\"      : \"#EFEFEF\"   \n"
      "}\n"
"\n"
      "this.draw();\n"
      "this.bindYear();\n"
      "this.bindMonth();\n"
      "this.changeSelect();\n"
      "this.bindData();\n"
    "}\n"
"\n"
     //日历类属性（语言包，可自由扩展）
    "Calendar.language = {\n"
      "\"year\"   : [[\"\"], [\"\"]],\n"
      "\"months\" : [[\"一月\",\"二月\",\"三月\",\"四月\",\"五月\",\"六月\",\"七月\",\"八月\",\"九月\",\"十月\",\"十一月\",\"十二月\"],\n"
            "[\"JAN\",\"FEB\",\"MAR\",\"APR\",\"MAY\",\"JUN\",\"JUL\",\"AUG\",\"SEP\",\"OCT\",\"NOV\",\"DEC\"]\n"
             "],\n"
      "\"weeks\"  : [[\"日\",\"一\",\"二\",\"三\",\"四\",\"五\",\"六\"],\n"
            "[\"SUN\",\"MON\",\"TUR\",\"WED\",\"THU\",\"FRI\",\"SAT\"]\n"
             "],\n"
      "\"clear\"  : [[\"清空\"], [\"CLS\"]],\n"
      "\"today\"  : [[\"今天\"], [\"TODAY\"]],\n"
      "\"close\"  : [[\"关闭\"], [\"CLOSE\"]]\n"
    "}\n"
"\n"
    "Calendar.prototype.draw = function() {\n"
      "calendar = this;\n"
"\n"
      "var mvAry = [];  \n"
      "mvAry[mvAry.length]  = '  <div name=\"calendarForm\" style=\"margin: 0px;\">';\n"
      "mvAry[mvAry.length]  = '    <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\">';\n"
      "mvAry[mvAry.length]  = '      <tr>';\n"
      "mvAry[mvAry.length]  = '        <th align=\"left\" width=\"1%\"><input style=\"border: 1px solid ' + calendar.colors[\"input_border\"] + ';background-color:' + calendar.colors[\"input_bg\"] + ';width:16px;height:20px;\" name=\"prevMonth\" type=\"button\" id=\"prevMonth\" value=\"&lt;\" /></th>';\n"
      "mvAry[mvAry.length]  = '        <th align=\"center\" width=\"98%\" nowrap=\"nowrap\"><select name=\"calendarYear\" id=\"calendarYear\" style=\"font-size:12px;\"></select><select name=\"calendarMonth\" id=\"calendarMonth\" style=\"font-size:12px;\"></select></th>';\n"
      "mvAry[mvAry.length]  = '        <th align=\"right\" width=\"1%\"><input style=\"border: 1px solid ' + calendar.colors[\"input_border\"] + ';background-color:' + calendar.colors[\"input_bg\"] + ';width:16px;height:20px;\" name=\"nextMonth\" type=\"button\" id=\"nextMonth\" value=\"&gt;\" /></th>';\n"
      "mvAry[mvAry.length]  = '      </tr>';\n"
      "mvAry[mvAry.length]  = '    </table>';\n"
      "mvAry[mvAry.length]  = '    <table id=\"calendarTable\" width=\"100%\" style=\"border:0px solid #CCCCCC;background-color:#FFFFFF;font-size:9pt\" border=\"0\" cellpadding=\"2\" cellspacing=\"1\">';\n"
      "mvAry[mvAry.length]  = '      <tr>';\n"
      "for(var i = 0; i < 7; i++) {\n"
        "mvAry[mvAry.length]  = '      <th style=\"font-weight:normal;background-color:' + calendar.colors[\"tr_bg\"] + ';color:' + calendar.colors[\"tr_word\"] + ';\">' + Calendar.language[\"weeks\"][this.lang][i] + '</th>';\n"
      "}\n"
      "mvAry[mvAry.length]  = '      </tr>';\n"
      "for(var i = 0; i < 6;i++){\n"
        "mvAry[mvAry.length]  = '    <tr align=\"center\">';\n"
        "for(var j = 0; j < 7; j++) {\n"
          "if (j == 0){\n"
            "mvAry[mvAry.length]  = '  <td style=\"cursor:default;color:' + calendar.colors[\"sun_word\"] + ';\"></td>';\n"
          "} else if(j == 6) {\n"
            "mvAry[mvAry.length]  = '  <td style=\"cursor:default;color:' + calendar.colors[\"sat_word\"] + ';\"></td>';\n"
          "} else {\n"
            "mvAry[mvAry.length]  = '  <td style=\"cursor:default;\"></td>';\n"
          "}\n"
        "}\n"
        "mvAry[mvAry.length]  = '    </tr>';\n"
      "}\n"
      "mvAry[mvAry.length]  = '      <tr style=\"background-color:' + calendar.colors[\"input_bg\"] + ';\">';\n"
      "mvAry[mvAry.length]  = '        <th colspan=\"2\"><input name=\"calendarClear\" type=\"button\" id=\"calendarClear\" value=\"' + Calendar.language[\"clear\"][this.lang] + '\" style=\"border: 1px solid ' + calendar.colors[\"input_border\"] + ';background-color:' + calendar.colors[\"input_bg\"] + ';width:100%;height:18px;font-size:9pt;\"/></th>';\n"
      "mvAry[mvAry.length]  = '        <th colspan=\"3\"><input name=\"calendarToday\" type=\"button\" id=\"calendarToday\" value=\"' + Calendar.language[\"today\"][this.lang] + '\" style=\"border: 1px solid ' + calendar.colors[\"input_border\"] + ';background-color:' + calendar.colors[\"input_bg\"] + ';width:100%;height:18px;font-size:9pt;\"/></th>';\n"
      "mvAry[mvAry.length]  = '        <th colspan=\"2\"><input name=\"calendarClose\" type=\"button\" id=\"calendarClose\" value=\"' + Calendar.language[\"close\"][this.lang] + '\" style=\"border: 1px solid ' + calendar.colors[\"input_border\"] + ';background-color:' + calendar.colors[\"input_bg\"] + ';width:100%;height:18px;font-size:9pt;\"/></th>';\n"
      "mvAry[mvAry.length]  = '      </tr>';\n"
      "mvAry[mvAry.length]  = '    </table>';  \n"
      "mvAry[mvAry.length]  = '  </div>';\n"
      "this.panel.innerHTML = mvAry.join(\"\");\n"
      "\n"
       ///**//******** 以下代码由寒羽枫 2006-12-01 添加 **********/
      "var obj = this.getElementById(\"prevMonth\");\n"
      "obj.onclick = function () {calendar.goPrevMonth(calendar);}\n"
      "obj.onblur = function () {calendar.onblur();}\n"
      "this.prevMonth= obj;\n"
      "\n"
      "obj = this.getElementById(\"nextMonth\");\n"
      "obj.onclick = function () {calendar.goNextMonth(calendar);}\n"
      "obj.onblur = function () {calendar.onblur();}\n"
      "this.nextMonth= obj;   \n"
"\n"
      "obj = this.getElementById(\"calendarClear\");\n"
      "obj.onclick = function () {calendar.dateControl.value = \"\";calendar.hide();}\n"
      "this.calendarClear = obj;\n"
      "\n"
      "obj = this.getElementById(\"calendarClose\");\n"
      "obj.onclick = function () {calendar.hide();}\n"
      "this.calendarClose = obj;\n"
      "\n"
      "obj = this.getElementById(\"calendarYear\");\n"
      "obj.onchange = function () {calendar.update(calendar);}\n"
      "obj.onblur = function () {calendar.onblur();}\n"
      "this.calendarYear = obj;\n"
      "\n"
      "obj = this.getElementById(\"calendarMonth\");\n"
      "with(obj)\n"
      "{\n"
        "onchange = function () {calendar.update(calendar);}\n"
        "onblur = function () {calendar.onblur();}\n"
      "}this.calendarMonth = obj;\n"
     "\n"
      "obj = this.getElementById(\"calendarToday\");\n"
      "obj.onclick = function () {\n"
        "var today = new Date();\n"
        "calendar.date = today;\n"
        "calendar.year = today.getFullYear();\n"
        "calendar.month = today.getMonth();\n"
        "calendar.changeSelect();\n"
        "calendar.bindData();\n"
        "calendar.dateControl.value = today.format(calendar.dateFormatStyle);\n"
        "calendar.hide();\n"
      "}\n"
      "this.calendarToday = obj; \n"
    "}\n"
"\n"
     //年份下拉框绑定数据
    "Calendar.prototype.bindYear = function() { \n"
      "var cy = this.calendarYear;\n"
      "cy.length = 0;\n"
      "for (var i = this.beginYear; i <= this.endYear; i++){\n"
        "cy.options[cy.length] = new Option(i + Calendar.language[\"year\"][this.lang], i);\n"
      "}\n"
    "}\n"
"\n"
     //月份下拉框绑定数据
    "Calendar.prototype.bindMonth = function() { \n"
      "var cm = this.calendarMonth;\n"
      "cm.length = 0;\n"
      "for (var i = 0; i < 12; i++){\n"
        "cm.options[cm.length] = new Option(Calendar.language[\"months\"][this.lang][i], i);\n"
      "}\n"
    "}\n"
"\n"
     //向前一月
    "Calendar.prototype.goPrevMonth = function(e){\n"
      "if (this.year == this.beginYear && this.month == 0){return;}\n"
      "this.month--;\n"
      "if (this.month == -1) {\n"
        "this.year--;\n"
        "this.month = 11;\n"
      "}\n"
      "this.date = new Date(this.year, this.month, 1);\n"
      "this.changeSelect();\n"
      "this.bindData();\n"
    "}\n"
"\n"
     //向后一月
    "Calendar.prototype.goNextMonth = function(e){\n"
      "if (this.year == this.endYear && this.month == 11){return;}\n"
      "this.month++;\n"
      "if (this.month == 12) {\n"
        "this.year++;\n"
        "this.month = 0;\n"
      "}\n"
      "this.date = new Date(this.year, this.month, 1);\n"
      "this.changeSelect();\n"
      "this.bindData();\n"
    "}\n"
"\n"
     //改变SELECT选中状态
    "Calendar.prototype.changeSelect = function() { \n"
      "var cy = this.calendarYear;\n"
      "var cm = this.calendarMonth;\n"
      "for (var i= 0; i < cy.length; i++){\n"
        "if (cy.options[i].value == this.date.getFullYear()){\n"
          "cy[i].selected = true;\n"
          "break;\n"
        "}\n"
      "}\n"
      "for (var i= 0; i < cm.length; i++){\n"
        "if (cm.options[i].value == this.date.getMonth()){\n"
          "cm[i].selected = true;\n"
          "break;\n"
        "}\n"
      "}\n"
    "}\n"
"\n"
     //更新年、月
    "Calendar.prototype.update = function (e){ \n"
      "this.year  = e.calendarYear.options[e.calendarYear.selectedIndex].value;\n"
      "this.month = e.calendarMonth.options[e.calendarMonth.selectedIndex].value;\n"
      "this.date = new Date(this.year, this.month, 1);\n"
      "this.changeSelect();\n"
      "this.bindData();\n"
    "}\n"
"\n"
     //绑定数据到月视图
    "Calendar.prototype.bindData = function () {\n"
      "var calendar = this;\n"
      "var dateArray = this.getMonthViewArray(this.date.getFullYear(), this.date.getMonth());\n"
      "var tds = this.getElementById(\"calendarTable\").getElementsByTagName(\"td\");\n"
      "for(var i = 0; i < tds.length; i++) {\n"
       //tds[i].style.color = calendar.colors[\"td_word_light\"];
      "tds[i].style.backgroundColor = calendar.colors[\"td_bg_out\"];\n"
        "tds[i].onclick = function () {return;}\n"
        "tds[i].onmouseover = function () {return;}\n"
        "tds[i].onmouseout = function () {return;}\n"
        "if (i > dateArray.length - 1) break;\n"
        "tds[i].innerHTML = dateArray[i];\n"
        "if (dateArray[i] != \"&nbsp;\"){\n"
          "tds[i].onclick = function () {\n"
            "if (calendar.dateControl != null){\n"
              "calendar.dateControl.value = new Date(calendar.date.getFullYear(),\n"
                                                    "calendar.date.getMonth(),\n"
                                                    "this.innerHTML).format(calendar.dateFormatStyle);\n"
            "}\n"
            "calendar.hide();\n"
          "}\n"
          "tds[i].onmouseover = function () {\n"
            "this.style.backgroundColor = calendar.colors[\"td_bg_over\"];\n"
          "}\n"
          "tds[i].onmouseout = function () {\n"
            "this.style.backgroundColor = calendar.colors[\"td_bg_out\"];\n"
          "}\n"
          "if (new Date().format(calendar.dateFormatStyle) ==\n"
              "new Date(calendar.date.getFullYear(),\n"
                       "calendar.date.getMonth(),\n"
                       "dateArray[i]).format(calendar.dateFormatStyle)) {\n"
             //tds[i].style.color = calendar.colors[\"cur_word\"];
            "tds[i].style.backgroundColor = calendar.colors[\"cur_bg\"];\n"
            "tds[i].onmouseover = function () {\n"
              "this.style.backgroundColor = calendar.colors[\"td_bg_over\"];\n"
            "}\n"
            "tds[i].onmouseout = function () {\n"
              "this.style.backgroundColor = calendar.colors[\"cur_bg\"];\n"
            "}\n"
             //continue; //若不想当天单元格的背景被下面的覆盖，请取消注释
          "}   \n"
          "\n"
          "if (calendar.dateControl != null && calendar.dateControl.value == new Date(calendar.date.getFullYear(),\n"
                       "calendar.date.getMonth(),\n"
                       "dateArray[i]).format(calendar.dateFormatStyle)) {\n"
            "tds[i].style.backgroundColor = calendar.colors[\"sel_bg\"];\n"
            "tds[i].onmouseover = function () {\n"
              "this.style.backgroundColor = calendar.colors[\"td_bg_over\"];\n"
            "}\n"
            "tds[i].onmouseout = function () {\n"
              "this.style.backgroundColor = calendar.colors[\"sel_bg\"];\n"
            "}\n"
          "}\n"
        "}\n"
      "}\n"
    "}\n"
"\n"
     //根据年、月得到月视图数据(数组形式)
    "Calendar.prototype.getMonthViewArray = function (y, m) {\n"
      "var mvArray = [];\n"
      "var dayOfFirstDay = new Date(y, m, 1).getDay();\n"
      "var daysOfMonth = new Date(y, m + 1, 0).getDate();\n"
      "for (var i = 0; i < 42; i++) {\n"
        "mvArray[i] = \"&nbsp;\";\n"
      "}\n"
      "for (var i = 0; i < daysOfMonth; i++){\n"
        "mvArray[i + dayOfFirstDay] = i + 1;\n"
      "}\n"
      "return mvArray;\n"
"\n"
       //  var dateArray = new Array(42);
       //  var dayOfFirstDate = new Date(y, m, 1).getDay();
       //  var dateCountOfMonth = new Date(y, m + 1, 0).getDate();
       //  for (var i = 0; i < dateCountOfMonth; i++) {
       //      dateArray[i + dayOfFirstDate] = i + 1;
       //  }
       //  return dateArray;
    "}\n"
"\n"
     //扩展 OBJ(id) 多浏览器兼容性 from meizz tree source
    "Calendar.prototype.getElementById = function(id){\n"
      "if (typeof(id) != \"string\" || id == \"\") return null;\n"
      "if (OBJ) return OBJ(id);\n"
      "if (document.all) return document.all(id);\n"
      "try {return eval(id);} catch(e){ return null;}\n"
    "}\n"
"\n"
     //扩展 object.getElementsByTagName(tagName)
    "Calendar.prototype.getElementsByTagName = function(object, tagName){\n"
      "if (document.getElementsByTagName) return document.getElementsByTagName(tagName);\n"
      "if (document.all) return document.all.tags(tagName);\n"
    "}\n"
"\n"
     //取得HTML控件绝对位置
    "Calendar.prototype.getAbsPoint = function (e){\n"
      "var x = e.offsetLeft;\n"
      "var y = e.offsetTop;\n"
      "while(e = e.offsetParent){\n"
        "x += e.offsetLeft;\n"
        "y += e.offsetTop;\n"
      "}\n"
      "return {\"x\": x, \"y\": y};\n"
    "}\n"
"\n"
     //显示日历
    "Calendar.prototype.show = function (dateObj, popControl) {\n"
      "if (dateObj == null){\n"
        "throw new Error(\"arguments[0] is necessary\")\n"
      "}\n"
      "this.dateControl = dateObj;\n"
      "\n"
      "this.date = (dateObj.value.length > 0) ? new Date(dateObj.value.toDate(this.dateFormatStyle)) : new Date();\n"
      "this.year = this.date.getFullYear();\n"
      "this.month = this.date.getMonth();\n"
      "this.changeSelect();\n"
      "this.bindData();\n"
      "\n"
      "if (popControl == null){\n"
        "popControl = dateObj;\n"
      "}\n"
      "var xy = this.getAbsPoint(popControl);\n"
      "this.panel.style.left = xy.x  + \"px\";\n"
      "this.panel.style.top = (xy.y + dateObj.offsetHeight) + \"px\"; \n"
     "\n"
      "this.panel.style.display = \"\";\n"
      "this.container.style.display = \"\";\n"
      "\n"
      "dateObj.onblur = function(){calendar.onblur();}\n"
      "this.container.onmouseover = function(){isFocus=true;}\n"
      "this.container.onmouseout = function(){isFocus=false;}\n"
    "}\n"
     //隐藏日历
    "Calendar.prototype.hide = function() {\n"
      "this.panel.style.display = \"none\";\n"
      "this.container.style.display = \"none\";\n"
      "isFocus=false;\n"
      "\n"
"\n"
     // --自定义验控件是否为空--
     //  try
     // {
         "CheckDate(objdate);\n"
     //  }
     //  catch(err)
     //  {
     //  }
    "}\n"
    "function CheckDate(obj) \n"
    "{\n"
         //var t = OBJ('txtPeriod').value;
        "var t = obj.value;\n"
        "var v = null;\n"
        "var tt = /^(\\d{1,4})(-|\\/)(\\d{1,2})\\2(\\d{1,2})$/;\n"
        "var dv = obj.id;\n"
            "dv=\"dv_\"+dv;\n"
        "var dvDate =OBJ(dv);\n"
        "\n"
        "if (dvDate == null)\n"
        "{\n"
            "return;\n"
        "}\n"
        "if(t!=\"\")\n"
        "{\n"
            "if(t.search(tt)!=-1)\n"
            "{\n"
                "\n"
                "dvDate.style.display = 'none';\n"
                "v = 0;  \n"
            "}\n"
            "else\n"
            "{\n"
                "dvDate.style.display = 'block';\n"
                "v = 1;\n"
            "}\n"
            "if(DateCompare(obj.value,datenow)==true)\n"
            "{\n"
                "v = 0;\n"
            "}\n"
            "else\n"
            "{\n"
                "dvDate.style.display = 'block';\n"
                "dvDate.innerHTML = \"  <font color=red>&nbsp;&nbsp;您的截止日期必须大于今天</font>\";\n"
                "v = 1\n"
            "}\n"
        "}\n"
        "else\n"
        "{\n"
            "dvDate.style.display = 'block';\n"
            "v = 1;\n"
        "}\n"
        "return v;\n"
    "}\n"
"\n"
     //焦点转移时隐藏日历
    "Calendar.prototype.onblur = function() {\n"
        "if(!isFocus){this.hide();}\n"
    "}\n"
    "document.write('<div id=\"ContainerPanel\" style=\"display:none\"><div id=\"calendarPanel\" style=\"position: absolute;display: none;z-index: 9999;');\n"
    "document.write('background-color: #FFFFFF;border: 1px solid #CCCCCC;width:175px;font-size:9px;\"></div>');\n"
    "if(document.all)\n"
    "{\n"
        "document.write('<iframe style=\"position:absolute;z-index:2000;width:expression(this.previousSibling.offsetWidth);');\n"
        "document.write('height:expression(this.previousSibling.offsetHeight);');\n"
        "document.write('left:expression(this.previousSibling.offsetLeft);top:expression(this.previousSibling.offsetTop);');\n"
        "document.write('display:expression(this.previousSibling.style.display);\" scrolling=\"no\" frameborder=\"no\"></iframe>');\n"
    "}\n"
    "document.write('</div>');\n"
    "</script>\n"
"</html>\n"
};
#endif
