#ifndef _HTML_H_039_H_
#define _HTML_H_039_H_
static const char h_039[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
	"<meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'/>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
        "<script src='j_001.js' type='text/javascript'></script>\n"
        "<style type='text/css'>\n"
        "tr{height:27px;}\n"
        ".td1{text-align:left;padding-left:40px;}\n"
        ".td2{text-align:right;padding-right:5px;}\n"
        ".td3{text-align:right;padding-right:40px;}\n"
        ".backcolor{background-color:#FF9500;}\n"
        ".color1{color:#FF9500;font-weight: bold;}\n"
        ".color2{color:#888;font-weight: bold;}\n"
        ".color3{color:#444;font-weight: bold;}\n"
        "</style>\n"
    "</head>\n"
    "<script type=\"text/javascript\" src=\"jquery.min.js\"></script>\n"
"<body onload='Init();'>\n"
        "<div style='width:100%;' id='fault_code'></div>\n"
        "<div class='blank'></div>\n"
        "<div class='title' style='width:90%;'>\n"
        "<div class='subtitle'>\n"
            "<div class='r1 backcolor'></div>\n"
            "<div class='r2 backcolor'></div>\n"
            "<div class='r3 backcolor'></div>\n"
            "<div class='r4 backcolor'></div>\n"
            "<div class='content backcolor subcontent'>\n"
                "<span id='N060'></span>\n"
            "</div>\n"
            "<div class='r4 backcolor'></div>\n"
            "<div class='r3 backcolor'></div>\n"
            "<div class='r2 backcolor'></div>\n"
            "<div class='r1 backcolor'></div>\n"
            "<div class='line_short'></div>\n"
        "</div>\n"
        "</div>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST0'></span></td>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST1'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST2'></span></td>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST3'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST4'></span></td>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST5'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST6'></span></td>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST7'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST8'></span></td>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST9'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST10'></span></td>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST11'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST12'></span></td>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST13'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST14'></span></td>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST15'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST16'></span></td>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST17'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST20'></span></td>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST21'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST22'></span></td>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST23'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST24'></span></td>\n"
                "<td class='td1 even' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 even' width='30%'><span class='color1' id='ST25'></span></td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST26'></span></td>\n"
                "<td class='td1 odd' width='20%'><span class='color2'>▲</span></td>\n"
                "<td class='td3 odd' width='30%'><span class='color1' id='ST27'></span></td>\n"
            "</tr>\n"
        "</table>\n"
        //"<div class='line_long'></div>\n"
        "<div class='btm_blank'></div>\n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var language=0;\n"
        "var Json;\n"
        "var lang=\n"
        "{		\n"
            "N060:['告警信息','Alarm Information'],\n"
            "N061:['告警&nbsp;','Alarm&nbsp;'],\n"
            "N062:['储能逆变器故障告警','PCS Fault Alarm'],\n"
            "N063:['储能逆变器通讯故障告警','PCS Comm Fault Alarm'],\n"
            "N064:['光伏逆变器故障告警','PV Fault Alarm'],\n"
            "N065:['光伏逆变器通讯故障告警','PV Comm Fault Alarm'],\n"
            "N066:['电网侧接触器告警','Grid-side Contact Alarm'],\n"
            "N067:['微网侧接触器告警','MG-side Contact Alarm'],\n"
            "N068:['储能逆变器交流未连接','PCS AC-side Disconnect'],\n"
            "N069:['一组或多组电池电量低','One or More Low Battery'],\n"
            "N070:['一组或多组电池电量高','One or More High Battery'],\n"
            "N071:['BMS通讯故障告警','BMS Comm Fault Alarm '],\n"
            "N072:['BMS故障告警','BMS Fault Alarm'],\n"
            "N073:['BMS告警','BMS Alarm'],\n"
            "N074:['DCDC故障告警','DCDC Fault Alarm'],\n"
            "N075:['DCDC通讯故障告警','DCDC Comm Fault Alarm'],\n"
            "N076:['DSP通讯故障告警','DSP Comm Fault Alarm'],\n"
            "N077:['电表通讯故障告警','Ammeter Comm Fault Alarm'],\n"
            "N078:['汇流箱通讯故障告警','PVS Comm Fault Alarm'],\n"
            "N079:['环境检测仪通讯故障告警','Env-Detector Comm Fault Alarm'],\n"
            "N080:['',''],\n"
            "N081:['',''],\n"
            "N082:['节点1告警','Node 1 Alarm'],\n"
            "N083:['节点2告警','Node 2 Alarm'],\n"
            "N084:['节点3告警','Node 3 Alarm'],\n"
            "N085:['节点4告警','Node 4 Alarm'],\n"
            "N086:['节点5告警','Node 5 Alarm'],\n"
            "N087:['节点6告警','Node 6 Alarm'],\n"
            "N088:['节点7告警','Node 7 Alarm'],\n"
            "N089:['节点8告警','Node 8 Alarm'],\n"
            "N090:['',''],\n"
            "N091:['',''],\n"
            "N092:['',''],\n"
            "N093:['',''],\n"
            "N094:['',''],\n"
            "N095:['',''],\n"
            "N096:['','']\n"
        "};\n"
"\n"
        "function jquery_ajax()\n"
        "{\n"
            "var i=0;\n"
            "var Acode=new Array(1);\n"
            "$.ajax({\n"
                "url:\"s_039.html?\",\n"
                "type:\"get\",\n"
                "contentType:\"application/json;charset=utf-8\",\n"
                "data:JSON.stringify({\n"
                    "\"time\":Math.random()\n"
                "}),\n"
                "dataType:\"json\",\n"
                "success:function(data){\n"
                    "Json = data;         \n"
                    "if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                    "document.getElementById('N060').innerHTML=lang.N060[language];\n"
                    "document.getElementById('ST0').innerHTML=lang.N062[language];\n"
                    "document.getElementById('ST1').innerHTML=lang.N063[language];\n"
                    "document.getElementById('ST2').innerHTML=lang.N064[language];\n"
                    "document.getElementById('ST3').innerHTML=lang.N065[language];\n"
                    "document.getElementById('ST4').innerHTML=lang.N066[language];\n"
                    "document.getElementById('ST5').innerHTML=lang.N067[language];\n"
                    "document.getElementById('ST6').innerHTML=lang.N068[language];\n"
                    "document.getElementById('ST7').innerHTML=lang.N069[language];\n"
                    "document.getElementById('ST8').innerHTML=lang.N070[language];\n"
                    "document.getElementById('ST9').innerHTML=lang.N071[language];\n"
                    "document.getElementById('ST10').innerHTML=lang.N072[language];\n"
                    "document.getElementById('ST11').innerHTML=lang.N073[language];\n"
                    "document.getElementById('ST12').innerHTML=lang.N074[language];\n"
                    "document.getElementById('ST13').innerHTML=lang.N075[language];\n"
                    "document.getElementById('ST14').innerHTML=lang.N076[language];\n"
                    "document.getElementById('ST15').innerHTML=lang.N077[language];\n"
                    "document.getElementById('ST16').innerHTML=lang.N078[language];\n"
                    "document.getElementById('ST17').innerHTML=lang.N079[language];\n"
                    "document.getElementById('ST20').innerHTML=lang.N082[language];\n"
                    "document.getElementById('ST21').innerHTML=lang.N083[language];\n"
                    "document.getElementById('ST22').innerHTML=lang.N084[language];\n"
                    "document.getElementById('ST23').innerHTML=lang.N085[language];\n"
                    "document.getElementById('ST24').innerHTML=lang.N086[language];\n"
                    "document.getElementById('ST25').innerHTML=lang.N087[language];\n"
                    "document.getElementById('ST26').innerHTML=lang.N088[language];\n"
                    "document.getElementById('ST27').innerHTML=lang.N089[language];\n"
"\n"
                    "Acode[0]=Json.ID_0x0154;\n"
"\n"
                    "for(i=0;i<32;i++)\n"
                    "{\n"
                        "if(i==0 || i==1 || i==2 || i==3 || i==4 || i==5 || i==6 || i==7 || i==8 || i==9 || i==10 || i==11 || i==12 || i==13 \n"
                            "|| i==14 || i==15 || i==16 || i==17 || i==20 || i==21 || i==22 || i==23 || i==24 || i==25 || i==26 || i==27)\n"
                        "{\n"
                            "if(((Acode[0]>>i)&1)==1){\n"
                                "eval('document.getElementById(\\'ST'+i+'\\').className=\\'color1\\';');\n"
                            "}else{\n"
                                "eval('document.getElementById(\\'ST'+i+'\\').className=\\'color3\\';');\n"
                            "}\n"
                        "}\n"
                    "}\n"
                "}\n"
            "});\n"
        "}\n"
        "window.onresize = function()\n"
        "{\n"
            "var bodywidth=document.body.clientWidth;\n"
            "if(bodywidth<867){document.body.style.width=\"867px\";}else{document.body.style.width=\"auto\";}\n"
        "} \n"
        "function Init()\n"
        "{\n"
            "jquery_ajax();\n"
            "setInterval('jquery_ajax()',1000);\n"
        "}\n"
        "function pad(num,n)\n"
        "{\n"
            "var len=num.toString().length;\n"
            "while(len++<n)num='0'+num;\n"
            "return num;\n"
        "}    \n"
    "</script>\n"
"</html>\n"
};
#endif
