#ifndef _HTML_H_047_H_
#define _HTML_H_047_H_
static const char h_047[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<style type='text/css'>\n"
            "body{margin:0;padding:0;text-align:center;font-size:14px;font-family:'Times New Roman','宋体','微软雅黑',sans-serif;background-color:#eeeeee;}\n"
            ".cn{width:80px;float:right;}\n"
            ".en{width:80px;float:right;padding-right:26px;}\n"
            ".R_C{color:#F00;}\n"
            ".G_C{color:#AAA;}\n"
            ".B_C{color:#000;}\n"
            ".text{padding:0 5px;font-size:12px;}\n"
            ".quit{text-align:left;padding-left:5px;width:60px;float:left;line-height:100%;*line-height:120%;}\n"
            ".line{width:2px;_width:2px;border-right:1px #000 solid;float:left}\n"
            ".welcome1{width:140px;text-align:left;float:left;line-height:100%;}\n"
            ".welcome2{width:160px;text-align:left;float:left;line-height:100%;}\n"
            ".username1{width:80px;text-align:right;float:left;color:#ff0000;}\n"
            ".username2{width:80px;text-align:right;float:left;color:#ff0000;}\n"
            ".username3{width:80px;text-align:right;float:left;color:#ff0000;}\n"
            ".head{margin-top:8px;height:18px;}\n"
            ".line_long{height:1px;overflow:hidden;margin:2px 10px;background-color:#ccc;}\n"
            ".bottom{height:42px;margin:9px 0;}\n"
            ".logo{float:right;padding-right:25px;padding-top:3px;}\n"
            ".DS{width:215px;float:left;padding-left:5px;}\n"
            ".dev_name{text-align:center;width:215px;float:left;color:#888;font-style:italic;font-weight:bold;font-size:28px;font-family:Verdana,Geneva,sans-serif;padding-top:-18px;white-space:nowrap;}\n"
            ".SN{text-align:center;width:215px;float:left;color:#000;font-size:12px;font-family:Verdana,Geneva,sans-serif;white-space:nowrap;}\n"
            ".a{text-decoration:none;color:#000;}\n"
            ".flag{border:none;}\n"
            ".img{width:173px;height:41px;background-image:url(i_000.png) !important;background-repeat:no-repeat;_filter:progid: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='i_000.png');_background-image:none;}\n"
            ".cn_1{font-size:12px;margin-top:2px;display:inline;}\n"
            ".cn_2{font-size:12px;margin-top:3px;*margin-top:1px;display:inline;}\n"
            ".en_1{margin-top:1px;display:inline;}\n"
            ".en_2{margin-top:-1px;display:inline;}\n"
            ".long{width:92px;_width:92px;}\n"
        "</style>\n"
        "<script type='text/javascript'>\n"
 		"var FromMobileDevice=false;\n"
 		"function FromWhichDevice()\n"
 		"{\n"
 			"var sUserAgent=navigator.userAgent.toLowerCase();\n"
 			"var Ipad=sUserAgent.match(/ipad/i)=='ipad';\n"
 			"var IphoneOs=sUserAgent.match(/iphone os/i)=='iphone os';\n"
 			"var Android=sUserAgent.match(/android/i)=='android';\n"
 			"var WindowsPhone=sUserAgent.match(/windows phone/i)=='windows phone';\n"
 			"if(Ipad||IphoneOs||Android||WindowsPhone)FromMobileDevice=true;\n"
 			"else FromMobileDevice=false;\n"
 		"}\n"
            "var $=function(o){return document.getElementById(o);};\n"
            "var language=1;\n"
            "var Json;\n"
            "var lang=\n"
            "{\n"
                "N01:['退出','Logout'],\n"
                "N02:[', 欢迎您的到来！',', welcome your arrival!'],\n"
                "N10:['操作员','Operator'],\n"
                "N11:['管理员','Administrator'],\n"
                "N12:['维护员','Maintriner']\n"
            "};\n"
            "function lang_init()\n"
            "{\n"
                "$('N01').innerHTML=lang.N01[language];\n"
                "$('N02').innerHTML=lang.N02[language];\n"
                "if(Json.ID_0x0301==0x55)\n"
                "{\n"
                    "if(FromMobileDevice)$('welcome').className='welcome2 cn_1 long';\n"
                    "else $('welcome').className='welcome1 cn_1 long';\n"
                    "$('quit').className='quit cn_2';\n"
                "}\n"
                "else\n"
                "{\n"
                    "if(FromMobileDevice)$('welcome').className='welcome2 en_1';\n"
                    "else $('welcome').className='welcome1 en_1';\n"
                    "$('quit').claaaName='quit en_2';\n"
                "}\n"
            "}\n"
            "function quit()\n"
            "{\n"
                "var URL='a_047.html?0x0281=0&time='+Math.random();\n"
                "var xmlhttp;\n"
                "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                "xmlhttp.onreadystatechange=function()\n"
                "{\n"
                    "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                    "{  \n"
                        "parent.document.location.href='Login.html';\n"
                    "}\n"
                "}\n"
                "xmlhttp.open('GET',URL,true);\n"
                "xmlhttp.send();\n"
            "}\n"
            "function Init()\n"
            "{\n"
                "FromWhichDevice();\n"
                "var URL='s_047.html?time='+Math.random();\n"
                "var xmlhttp;\n"
                "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                "xmlhttp.onreadystatechange=function()\n"
                "{\n"
                    "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                    "{\n"
                        "eval('Json='+xmlhttp.responseText);             \n"
         			"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
         			"lang_init();\n"
         			"lang_color_GB();\n"
         			"$('ID_0x0201').innerHTML=Json.ID_0x0201;\n"
         			"$('ID_0x0202').innerHTML=Json.ID_0x0202;\n"
         			"if(Json.ID_0x0282==0)\n"
         			"{\n"
         				"$('ID_0x0282').innerHTML=lang.N10[language];\n"
         				"$('username').className='username1';\n"
         			"}\n"
         			"else if(Json.ID_0x0282==1)\n"
         			"{\n"
         				"$('ID_0x0282').innerHTML=lang.N11[language];\n"
         				"$('username').className='username2';\n"
         			"}\n"
                        "else if(Json.ID_0x0282==2)\n"
                        "{\n"
                            "$('ID_0x0282').innerHTML=lang.N12[language];\n"
                            "$('username').className='username3';\n"
                        "}\n"
                    "}\n"
                "};\n"
                "xmlhttp.open('GET',URL,true);\n"
                "xmlhttp.send();\n"
            "}\n"
            "function do_Submit(language)\n"
            "{\n"
                "lang_color_GB();\n"
                "var URL='a_047.html?0x0301='+language+'&time='+Math.random();\n"
                "var xmlhttp;\n"
                "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                "xmlhttp.onreadystatechange=function()\n"
                "{\n"
                    "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                    "{\n"
                        "Init();\n"
                        "window.parent.window.frames['main'].Init();\n"
                        "window.parent.window.frames['menu'].Init();\n"
			"window.parent.window.frames['stat'].Init();\n"
                    "}\n"
                "};\n"
                "xmlhttp.open('GET',URL,true);\n"
                "xmlhttp.send();\n"
            "}\n"
            "function lang_color_GB()\n"
            "{\n"
                "if(language==0)\n"
                "{\n"
                    "$('CHN').className='text B_C';\n"
                    "$('EN').className='text G_C';\n"
                "}\n"
                "else\n"
                "{\n"
                    "$('CHN').className='text G_C';\n"
                    "$('EN').className='text B_C';\n"
                "}\n"
            "}\n"
            "function lang_color_R(obj)\n"
            "{\n"
                "obj.className='text R_C';\n"
            "}\n"
        "</script>\n"
    "</head>\n"
    "<body onload='Init();'>\n"
        "<div>\n"
            "<div class='head'>\n"
                "<div class='en' onclick='do_Submit(\"170\")'>\n"
                    "<a class='a' href='#'><img class='flag' src='i_004.png'/><span id='EN' class='text' onmousemove='lang_color_R(this)' onmouseout='lang_color_GB()'>English</span></a>\n"
                "</div>\n"
                "<div class='cn' onclick='do_Submit(\"85\")'>\n"
                    "<a class='a' href='#'><img class='flag' src='i_003.png'/><span id='CHN' class='text' onmousemove='lang_color_R(this)' onmouseout='lang_color_GB()'>简体中文</span></a>\n"
                "</div>\n"
                "<div id='username' class='username2'>\n"
                    "<span id='ID_0x0282'>&nbsp;</span>\n"
                "</div>\n"
                "<div class='welcome' id='welcome'>\n"
                    "<span id='N02'>&nbsp;</span>\n"
                "</div>\n"
                "<div class='line'>\n"
                    "&nbsp;\n"
                "</div>\n"
                "<div id='quit' class='quit'>\n"
                    "<a  style='text-decoration:none;color:#00f;' href='#' onclick='quit()'><span id='N01'></span></a>\n"
                "</div>\n"
            "</div>\n"
        "</div>\n"
        "<div class='line_long'></div>\n"
        "<div class='bottom'>\n"
            "<div class='logo'><a href='http://www.sungrowpower.com' target='_blank'><div class='img'></div></a></div>\n"
            "<div class='DS'>\n"
                "<div class='dev_name' id='ID_0x0202'></div>\n"
                "<div class='SN' id='ID_0x0201'></div>\n"
            "</div>\n"
        "</div>\n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
"</html>\n"
};
#endif
