#ifndef _HTML_H_044_H_
#define _HTML_H_044_H_
static const char h_044[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
 "<head>\n"
 	"<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
 	"<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
 	"<script type='text/javascript'>\n"
            "var $=function(o){return document.getElementById(o);};\n"
            "function lang_init_ex(st,end){for(var i=st;i<=end;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
            "function show_tip_ex(id, obj){eval('$(\\'tip'+id+'\\').innerHTML=obj;');}\n"
            "function show_T(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
                "str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_sT(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_sT_ex(tid, id)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' id='\"+id+\"' style='display:none;width:90%'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function sendHttpReq(url, successFn)\n"
            "{\n"
                 //alert(url);   
                "var xmlhttp;\n"
                "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                "xmlhttp.onreadystatechange=function()\n"
                "{\n"
                    "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                    "{\n"
                        "if(xmlhttp.responseText=='1'){successFn();}\n"
                    "}\n"
                "};\n"
                "xmlhttp.open('GET',url,true);\n"
                "xmlhttp.send();\n"
            "}\n"
        "</script>\n"
 	"<style type='text/css'>\n"
 		"tr{height:27px;}\n"
 		".td1{padding-left:40px;text-align:left;}\n"
 		".td2{text-align:left;}\n"
 		".td3{padding-right:40px;text-align:right;}\n"
 		".txt{width:100px;text-align:right;}\n"
 	"</style>\n"
 "</head>\n"
 "<body onload='Init()'>\n"
 	"<script type='text/javascript'>\n"
 		"show_T('N01');\n"
 		"show_sT('N02');\n"
 	"</script>\n"
        "<table width='90%' border='1' id='tab1' style='border-collapse:collapse;border-spacing:0px;border-color:#e0e0e0;'>  \n"
            "<tr id='tr0'>\n"
                "<!-- 电表名称 -->\n"
                "<td width='25%' class='tab_header_color'><span id='N03' style=\"font-weight:bold;\"></span></td>\n"
                "<!-- 使能 -->\n"
                "<td width='50%' class='tab_header_color'><span id='N07' style=\"font-weight:bold;\"></span></td>\n"
                "<!-- 地址 -->\n"
                "<td width='25%' class='tab_header_color'><span id='N15' style=\"font-weight:bold;\"></span></td>\n"
            "</tr>\n"
            "<tr id='tr1'>\n"
                "<td width='25%' class='even'><span id='N04'></span></td>\n"
                "<td width='50%' class='even'><select style='width:200px;text-align:center;' id='Select0'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='ID0'></select></td>\n"
            "</tr>\n"
            "<tr id='tr2'>\n"
                "<td width='25%' class='odd'><span id='N05'></span></td>\n"
                "<td width='50%' class='odd'><select style='width:200px;text-align:center;' id='Select1'></select></td>\n"
                "<td width='25%' class='odd'><select style='width:135px;text-align:center;' id='ID1'></select></td>\n"
            "</tr>\n"
            "<tr id='tr3'>\n"
                "<td width='25%' class='even'><span id='N06'></span></td>\n"
                "<td width='50%' class='even'><select style='width:200px;text-align:center;' id='Select2'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='ID2'></select></td>\n"
            "</tr> \n"
        "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even' align='left'><span id='tip1' class='tip'>&nbsp;</span></td>\n"
                "<td width='50%' class='even' align='right'>\n"
                    "<button class='btn' onclick='doSubmit(this)' id='btn1' style='display:block;'><span id='N400'></span></button>\n"
                "</td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N50');\n"
        "</script>\n"
        "<table width='90%' border='1' id='tab2' style='border-collapse:collapse;border-spacing:0px;border-color:#e0e0e0;'>  \n"
            "<tr id='tr0'>\n"
                "<!-- 引脚名称 -->\n"
                "<td width='25%' class='tab_header_color'><span id='N51' style=\"font-weight:bold;\"></span></td>\n"
                "<!-- 功能 -->\n"
                "<td width='50%' class='tab_header_color'><span id='N63' style=\"font-weight:bold;\"></span></td>\n"
                "<!-- 模式 -->\n"
                "<td width='25%' class='tab_header_color'><span id='N64' style=\"font-weight:bold;\"></span></td>\n"
            "</tr>\n"
            "<tr id='tr1'>\n"
                "<td width='25%' class='even'><span id='N52'></span></td>\n"
                "<td width='50%' class='even'><select style='width:200px;text-align:center;' id='FUNCTION0'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='MODE0'></select></td>\n"
            "</tr>\n"
            "<tr id='tr2'>\n"
                "<td width='25%' class='odd'><span id='N53'></span></td>\n"
                "<td width='50%' class='odd'><select style='width:200px;text-align:center;' id='FUNCTION1'></select></td>\n"
                "<td width='25%' class='odd'><select style='width:135px;text-align:center;' id='MODE1'></select></td>\n"
            "</tr>\n"
            "<tr id='tr3'>\n"
                "<td width='25%' class='even'><span id='N54'></span></td>\n"
                "<td width='50%' class='even'><select style='width:200px;text-align:center;' id='FUNCTION2'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='MODE2'></select></td>\n"
            "</tr> \n"
            "<tr id='tr4'>\n"
                "<td width='25%' class='odd'><span id='N55'></span></td>\n"
                "<td width='50%' class='odd'><select style='width:200px;text-align:center;' id='FUNCTION3'></select></td>\n"
                "<td width='25%' class='odd'><select style='width:135px;text-align:center;' id='MODE3'></select></td>\n"
            "</tr> \n"
            "<tr id='tr5'>\n"
                "<td width='25%' class='even'><span id='N56'></span></td>\n"
                "<td width='50%' class='even'><select style='width:200px;text-align:center;' id='FUNCTION4'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='MODE4'></select></td>\n"
            "</tr> \n"
            "<tr id='tr6'>\n"
                "<td width='25%' class='odd'><span id='N57'></span></td>\n"
                "<td width='50%' class='odd'><select style='width:200px;text-align:center;' id='FUNCTION5'></select></td>\n"
                "<td width='25%' class='odd'><select style='width:135px;text-align:center;' id='MODE5'></select></td>\n"
            "</tr> \n"
            "<tr id='tr7'>\n"
                "<td width='25%' class='even'><span id='N58'></span></td>\n"
                "<td width='50%' class='even'><select style='width:200px;text-align:center;' id='FUNCTION6'></select></td>\n"
                "<td width='25%' class='even'><select style='width:135px;text-align:center;' id='MODE6'></select></td>\n"
            "</tr> \n"
            "<tr id='tr8'>\n"
                "<td width='25%' class='odd'><span id='N59'></span></td>\n"
                "<td width='50%' class='odd'><select style='width:200px;text-align:center;' id='FUNCTION7'></select></td>\n"
                "<td width='25%' class='odd'><select style='width:135px;text-align:center;' id='MODE7'></select></td>\n"
            "</tr> \n"
        "</table>\n"
        "<table width='90%' border='0'>\n"
            "<tr>\n"
                "<td width='50%' class='even' align='left'><span id='tip2' class='tip'>&nbsp;</span></td>\n"
                "<td width='50%' class='even' align='right'>\n"
                    "<button class='btn' onclick='doSubmit(this)' id='btn2' style='display:block;'><span id='N401'></span></button>\n"
                "</td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
 	"<div class='btm_blank'></div>\n"
 	"<div id='trans'></div>\n"
 	"<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
 "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var language=0;\n"
        "var Json;	 \n"
        "var lang=\n"
        "{\n"
            "N01:['辅助设置','Auxiliary Settings'],\n"
            "N02:['电表配置','Ammeter Settings'],\n"
            "N03:['名称','Name'],\n"
            "N04:['电网侧电表','Grid Side Ammeter'],\n"
            "N05:['负载侧电表','Load Side Ammeter'],\n"
            "N06:['光伏侧电表','PV Side Ammeter'],\n"
            "N07:['使能','Enable'],\n"
            "N08:['是','Yes'],\n"
            "N09:['否','No'],\n"
            "N10:['是','Yes'],\n"
            "N11:['否','No'],\n"
            "N12:['是','Yes'],\n"
            "N13:['否','No'],\n"
            "N14:['设备号','Number'],\n"
            "N15:['地址','Address'],\n"
"\n"
            "N50:['节点配置','Nodes Settings'],\n"
            "N51:['名称','Name'],\n"
            "N52:['DIN06','DIN06'],\n"
            "N53:['DIN07','DIN07'],\n"
            "N54:['DIN08','DIN08'],\n"
            "N55:['DIN09','DIN09'],\n"
            "N56:['DIN10','DIN10'],\n"
            "N57:['DIN11','DIN11'],\n"
            "N58:['DIN12','DIN12'],\n"
            "N59:['DIN13','DIN13'],\n"
            "N60:['DIN14','DIN14'],\n"
            "N61:['DIN15','DIN15'],\n"
            "N62:['DIN16','DIN16'],\n"
            "N63:['功能','Funtion'],\n"
            "N64:['模式','Mode'],\n"
            "N65:['禁用','Disable'],\n"
            "N66:['告警','Alarm'],\n"
            "N67:['故障','Fault'],\n"
            "N68:['禁用','Disable'],\n"
            "N69:['告警','Alarm'],\n"
            "N70:['故障','Fault'],\n"
            "N71:['禁用','Disable'],\n"
            "N72:['告警','Alarm'],\n"
            "N73:['故障','Fault'],\n"
            "N74:['禁用','Disable'],\n"
            "N75:['告警','Alarm'],\n"
            "N76:['故障','Fault'],\n"
            "N77:['禁用','Disable'],\n"
            "N78:['告警','Alarm'],\n"
            "N79:['故障','Fault'],\n"
            "N80:['禁用','Disable'],\n"
            "N81:['告警','Alarm'],\n"
            "N82:['故障','Fault'],\n"
            "N83:['禁用','Disable'],\n"
            "N84:['告警','Alarm'],\n"
            "N85:['故障','Fault'],\n"
            "N86:['禁用','Disable'],\n"
            "N87:['告警','Alarm'],\n"
            "N88:['故障','Fault'],\n"
"\n"
            "N100:['常开','Normally Open'],\n"
            "N101:['常闭','Normally Closed'],\n"
            "N102:['常开','Normally Open'],\n"
            "N103:['常闭','Normally Closed'],\n"
            "N104:['常开','Normally Open'],\n"
            "N105:['常闭','Normally Closed'],\n"
            "N106:['常开','Normally Open'],\n"
            "N107:['常闭','Normally Closed'],\n"
            "N108:['常开','Normally Open'],\n"
            "N109:['常闭','Normally Closed'],\n"
            "N110:['常开','Normally Open'],\n"
            "N111:['常闭','Normally Closed'],\n"
            "N112:['常开','Normally Open'],\n"
            "N113:['常闭','Normally Closed'],\n"
            "N114:['常开','Normally Open'],\n"
            "N115:['常闭','Normally Closed'],\n"
"\n"
            "N400:['设&nbsp;&nbsp;置','Set'], \n"
            "N401:['设&nbsp;&nbsp;置','Set'], \n"
"\n"
            "N499:['设置成功！','Set successfully!'],\n"
            "N500:['设置失败！','Set Failed!'],\n"
            "N501:['格式错误！','Format error!'],\n"
            "N502:['范围错误！','Range error!']    \n"
        "};\n"
        "function Init()\n"
        "{\n"
            "var URL='s_044.html?0x0000&time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{             \n"
                    "eval('Json='+xmlhttp.responseText);				\n"
"\n"
     			"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
"\n"
                     //初始化语言
                    "lang_init_ex(1,7); \n"
                    "lang_init_ex(15,15); \n"
                    "lang_init_ex(50,59); \n"
                    "lang_init_ex(63,64);\n"
     			"lang_init_ex(400,401);      \n"
"\n"
                     //删除所有option, 动态切换语言时必须操作
                    "for(var i=0;i<3;i++)\n"
                    "{\n"
                        "eval('$(\\'Select'+i+'\\').options.length=0;');\n"
                        "eval('$(\\'ID'+i+'\\').options.length=0;');\n"
                    "}   \n"
"\n"
                    "for(var i=0;i<8;i++)\n"
                    "{\n"
                        "eval('$(\\'FUNCTION'+i+'\\').options.length=0;');\n"
                        "eval('$(\\'MODE'+i+'\\').options.length=0;');\n"
                    "} \n"
"\n"
                     //初始化
                    "$('Select0').options.add(new Option(lang.N08[language],0));\n"
                    "$('Select0').options.add(new Option(lang.N09[language],1));\n"
                    "$('Select1').options.add(new Option(lang.N10[language],0));\n"
                    "$('Select1').options.add(new Option(lang.N11[language],1));\n"
                    "$('Select2').options.add(new Option(lang.N12[language],0));\n"
                    "$('Select2').options.add(new Option(lang.N13[language],1));\n"
                    "for(var i=0;i<3;i++)\n"
                    "{\n"
                        "for(var k=0; k<247; k++)eval('$(\\'ID'+i+'\\').options.add(new Option('+(k+1)+','+k+'));');                 \n"
                    "}\n"
                    "$('ID0').options[0].selected=true;\n"
                    "$('ID1').options[1].selected=true;\n"
                    "$('ID2').options[2].selected=true;\n"
"\n"
                     //初始化
                    "for(var i=0;i<8;i++)\n"
                    "{\n"
                        "eval('$(\\'FUNCTION'+i+'\\').options.add(new Option(lang.N'+(65+i*3+0)+'[language],0));');\n"
                        "eval('$(\\'FUNCTION'+i+'\\').options.add(new Option(lang.N'+(65+i*3+1)+'[language],1));');\n"
                        "eval('$(\\'FUNCTION'+i+'\\').options.add(new Option(lang.N'+(65+i*3+2)+'[language],2));');  \n"
                        "eval('$(\\'MODE'+i+'\\').options.add(new Option(lang.N'+(100+i*2+0)+'[language],0));');\n"
                        "eval('$(\\'MODE'+i+'\\').options.add(new Option(lang.N'+(100+i*2+1)+'[language],1));');            \n"
                    "}\n"
"\n"
     			"doSetValue(Json);\n"
"\n"
     				//user用户不能配置，install用户可以配置
     			"if(Json.ID_0x0282==0x11)\n"
     			"{\n"
     				"$('btn1').style.display='none';\n"
                        "$('btn2').style.display='none';\n"
     				"$('trans').style.zIndex=9999;\n"
     			"}\n"
     			"else\n"
     			"{\n"
     				"$('btn1').style.display='inline';\n"
                        "$('btn2').style.display='inline';\n"
     				"$('trans').style.zIndex=-9999;\n"
     			"}\n"
 			    "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}\n"
        "function read_back(addr)\n"
        "{\n"
            "var url='s_044.html?';\n"
            "if(addr==0x470){url=url+'0x0470'+'&0x0471'+'&0x0472'+'&0x0750'+'&0x0751'+'&0x0752';}\n"
            "else if(addr==0x490){url=url+'0x0490'+'&0x0491'+'&0x0492'+'&0x0493'+'&0x0494'+'&0x0495'+'&0x0496'+'&0x0497'+'&0x0498'+'&0x0499'+'&0x049A'+'&0x049B'+'&0x049C'+'&0x049D'+'&0x049E'+'&0x049F';}\n"
            "else{url=url+'0x0'+addr.toString(16).toUpperCase();}\n"
            "url=url+'&time='+Math.random();\n"
"\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText); \n"
                    "if(addr == 0x0470)\n"
                    "{\n"
                        "var pr_sel=[0,0,0],pr_addr=[0,0,0],fe_sel=[0,0,0],fe_addr=[0,0,0];\n"
                        "for(var i=0;i<3;i++) \n"
                        "{\n"
                            "eval('pr_addr['+i+']=$(\\'ID'+i+'\\').selectedIndex+1;');\n"
                            "if(eval('$(\\'Select'+i+'\\').selectedIndex;')==0) pr_sel[i]=0xaa;\n"
                            "else pr_sel[i]=0x55;\n"
                            "eval('fe_addr['+i+']=Json.ID_0x0'+(0x0750+i).toString(16).toUpperCase()+'');\n"
                            "eval('fe_sel['+i+']=Json.ID_0x0'+(0x0470+i).toString(16).toUpperCase()+'');\n"
                        "}\n"
                        "for(j=0;j<3;j++)\n"
                        "{\n"
                            "if(pr_addr[j]!=fe_addr[j] || pr_sel[j]!=fe_sel[j])\n"
                            "{\n"
                                "for(var i=0; i<3; i++)\n"
                                "{\n"
                                    "eval('$(\\'Select'+i+'\\').options[(Json.ID_0x0'+(0x0470+i).toString(16).toUpperCase()+')==0xaa?0:1].selected=true;');\n"
                                    "eval('$(\\'ID'+i+'\\').options[(Json.ID_0x0'+(0x0750+i).toString(16).toUpperCase()+')-1].selected=true;');\n"
                                "}\n"
                                "setTimeout('show_tip_ex(1,lang.N500[language])',500);\n"
                                "break;\n"
                            "}         \n"
                        "} \n"
                        "show_tip_ex(1,'&nbsp;');\n"
                        "if(j >= 3) setTimeout('show_tip_ex(1,lang.N499[language])',500);\n"
                        "setTimeout('show_tip_ex(1,\\'&nbsp;\\')',2500);  \n"
                    "}\n"
                    "else if(addr == 0x0490)\n"
                    "{\n"
                        "var pr_function=[0,0,0,0,0,0,0,0],pr_mode=[0,0,0,0,0,0,0,0],fe_function=[0,0,0,0,0,0,0,0,0],fe_mode=[0,0,0,0,0,0,0,0,0];\n"
                        "for(var i=0;i<8;i++) \n"
                        "{\n"
                            "eval('pr_function['+i+']=$(\\'FUNCTION'+i+'\\').selectedIndex;');\n"
                            "if(eval('$(\\'MODE'+i+'\\').selectedIndex;')==0) pr_mode[i]=0xaa;\n"
                            "else pr_mode[i]=0x55;\n"
                            "eval('fe_function['+i+']=Json.ID_0x0'+(0x0490+i*2).toString(16).toUpperCase()+'');\n"
                            "eval('fe_mode['+i+']=Json.ID_0x0'+(0x0491+i*2).toString(16).toUpperCase()+'');\n"
                        "}\n"
                        "var j=0;\n"
                        "for(j=0;j<8;j++) \n"
                        "{\n"
                            "if(pr_function[j] != fe_function[j] || pr_mode[j] != fe_mode[j])\n"
                            "{\n"
                                "for(var i=0; i<8; i++)\n"
                                "{\n"
                                    "eval('$(\\'FUNCTION'+i+'\\').options[Json.ID_0x0'+(0x0490+i*2).toString(16).toUpperCase()+'].selected=true;');\n"
                                    "eval('$(\\'MODE'+i+'\\').options[(Json.ID_0x0'+(0x0491+i*2).toString(16).toUpperCase()+')==0xaa?0:1].selected=true;');\n"
                                "}\n"
                                "setTimeout('show_tip_ex(2,lang.N500[language])',500);\n"
                                "break;\n"
                            "}\n"
                        "}\n"
                        "show_tip_ex(2,'&nbsp;');\n"
                        "if(j >= 8) setTimeout('show_tip_ex(2,lang.N499[language])',500);\n"
                        "setTimeout('show_tip_ex(2,\\'&nbsp;\\')',2500);  \n"
                    "}\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',url,true);\n"
            "xmlhttp.send();  \n"
        "}\n"
        "function doSubmit(obj)\n"
        "{\n"
            "var func=[0,0,0,0,0,0,0,0],mode=[0,0,0,0,0,0,0,0];\n"
            "var sel=[0,0,0,],addr=[0,0,0];\n"
            "var URL='a_044.html?';\n"
            "switch(obj.id)\n"
            "{\n"
             "case 'btn1': \n"
                    "for(var i=0;i<3;i++) \n"
                    "{\n"
                        "eval('addr['+i+']=$(\\'ID'+i+'\\').selectedIndex+1;');\n"
                        "if(eval('$(\\'Select'+i+'\\').selectedIndex;')==0) sel[i]=0xaa;\n"
                        "else sel[i]=0x55;\n"
                    "}\n"
                    "URL=URL+'&0x0470='+sel[0]+'&0x0471='+sel[1]+'&0x0472='+sel[2]+'&0x0750='+addr[0]+'&0x0751='+addr[1]+'&0x0752='+addr[2];\n"
                    "readBack=0x0470;\n"
             	  "break;\n"
                "case 'btn2': \n"
                    "for(var i=0;i<8;i++) \n"
                    "{\n"
                        "eval('func['+i+']=$(\\'FUNCTION'+i+'\\').selectedIndex;');\n"
                        "if(eval('$(\\'MODE'+i+'\\').selectedIndex;')==0) mode[i]=0xaa;\n"
                        "else mode[i]=0x55;\n"
                    "}\n"
                    "URL=URL+'&0x0490='+func[0]+'&0x0491='+mode[0]+'&0x0492='+func[1]+'&0x0493='+mode[1]+'&0x0494='+func[2]+'&0x0495='+mode[2]+'&0x0496='+func[3]+'&0x0497='+mode[3]+'&0x0498='+func[4]+'&0x0499='+mode[4]+'&0x049A='+func[5]+'&0x049B='+mode[5]+'&0x049C='+func[6]+'&0x049D='+mode[6]+'&0x049E='+func[7]+'&0x049F='+mode[7];\n"
                    "readBack=0x0490;\n"
                    "break;\n"
             "default:break;\n"
            "}\n"
            "URL=URL+'&time='+Math.random();\n"
             //alert(URL);
"\n"
            "function success()\n"
            "{\n"
                "setTimeout('read_back('+readBack+')', 100);            			\n"
            "}\n"
             //测试
             //success();            
 		"sendHttpReq(URL, success);\n"
        "}\n"
        "function doSetValue(Json)\n"
        "{\n"
            "for(var i=0; i<3; i++)\n"
            "{\n"
                "eval('$(\\'Select'+i+'\\').options[(Json.ID_0x0'+(0x0470+i).toString(16).toUpperCase()+')==0xaa?0:1].selected=true;');\n"
                "eval('$(\\'ID'+i+'\\').options[(Json.ID_0x0'+(0x0750+i).toString(16).toUpperCase()+')-1].selected=true;');\n"
            "}\n"
            "for(var i=0; i<8; i++)\n"
            "{\n"
                "eval('$(\\'FUNCTION'+i+'\\').options[Json.ID_0x0'+(0x0490+i*2).toString(16).toUpperCase()+'].selected=true;');\n"
                "eval('$(\\'MODE'+i+'\\').options[(Json.ID_0x0'+(0x0491+i*2).toString(16).toUpperCase()+')==0xaa?0:1].selected=true;');\n"
            "}\n"
        "}\n"
    "</script\n"
"</html>\n"
};
#endif
