#ifndef _HTML_H_040_H_
#define _HTML_H_040_H_
static const char h_040[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<style type='text/css'>\n"
            "html{_overflow-y:scroll;}\n"
            "body{margin:0;padding:0;text-align:center;font-size:14px;font-family:'微软雅黑',Verdana,'宋体',sans-serif;background-size:100% 380px; }\n"
            "img{vertical-align: bottom; display: block;}\n"
            ".title{margin:5px auto;width:780px;text-align:left;overflow:hidden;}\n"
            ".r1{margin:0 5px;height:1px;overflow:hidden;}\n"
            ".r2{margin:0 3px;height:1px;overflow:hidden;}\n"
            ".r3{margin:0 2px;height:1px;overflow:hidden;}\n"
            ".r4{margin:0 1px;height:2px;overflow:hidden;}\n"
            ".color{background-color:#F58E03;}\n"
            ".content{height:24px;line-height:24px;padding-left:20px;font-size:24px;color:#EEE;text-align:left;}\n"
            ".blank{height:4px;overflow:hidden;}\n"
            ".btm_blank{height:15px;overflow:hidden;}\n"
            ".back_color{background-color:#efefff;}\n"
            ".back_high{width:100%;height:240px;margin:0 auto;}\n"
            ".img_common{float:right;margin-right:12px;width:50px;height:50px;}\n"
            ".bg1{background:transparent url(i_001.png) no-repeat scroll 0 0;}\n"
            ".bg2{background:transparent url(i_001.png) no-repeat scroll -50px 0;}\n"
            ".bg3{background:transparent url(i_001.png) no-repeat scroll -100px 0;}\n"
            ".bg4{background:transparent url(i_001.png) no-repeat scroll 0 -50px;}\n"
            ".bg5{background:transparent url(i_001.png) no-repeat scroll -50px -50px;}\n"
            ".bg6{background:transparent url(i_001.png) no-repeat scroll -100px -50px;}\n"
            ".bg7{background:transparent url(i_005.png) no-repeat scroll 0 0;}\n"
            ".bg8{background:transparent url(i_006.png) no-repeat scroll 0 0;}\n"
            ".bg9{background:transparent url(i_007.png) no-repeat scroll 0 0;}\n"
        "</style>\n"
        "</script> \n"
    "</head>\n"
    "<body onload='Init()'>\n"
        "<div class=\"hidden\">\n"
            "<script type=\"text/javascript\">\n"
                "var images = new Array()\n"
                "function preload() {\n"
                    "for (i = 0; i < preload.arguments.length; i++) {\n"
                        "images[i] = new Image();\n"
                        "images[i].src = preload.arguments[i];\n"
                    "}\n"
                "}\n"
                "preload(\n"
                    "\"i_008.gif\",\n"
                    "\"i_009.gif\",\n"
                    "\"i_011.gif\",\n"
                    "\"i_012.gif\",\n"
                    "\"i_010.png\",\n"
                    "\"i_013.png\",\n"
                    "\"i_014.png\",\n"
                    "\"i_015.png\",\n"
                    "\"i_016.png\",\n"
                    "\"i_017.png\",\n"
                    "\"i_018.png\",\n"
                    "\"i_019.png\",\n"
                    "\"i_020.png\",\n"
                    "\"i_021.png\",\n"
                    "\"i_022.png\",\n"
                    "\"i_023.png\"\n"
                ")\n"
            "</script>\n"
        "</div>\n"
        "<div class='title' style='width:100%;'>\n"
        "<div class='r1 back_color'></div>\n"
        "<div class='r2 back_color'></div>\n"
        "<div class='r3 back_color'></div>\n"
        "<div class='r4 back_color'></div>\n"
          "<table width=\"100%\" height=\"346\" border=\"0\" border-spacing=\"0\" cellpadding=\"0\" cellspacing=\"0\" padding=\"0\" margin=\"0\" bgcolor=\"#efefff\">    \n"
                  "<tr>\n"
                    "<td colspan=\"2\" align=\"right\" valign=\"bottom\">&nbsp;</td>\n"
                    "<td width=\"28\">&nbsp;</td>\n"
                    "<td width=\"38\" rowspan=\"2\">&nbsp;</td>\n"
                    "<td colspan=\"15\" rowspan=\"5\" align=\"center\" valign=\"bottom\"></td>\n"
                    "<td width=\"32\" rowspan=\"2\">&nbsp;</td>\n"
                    "<td colspan=\"13\" rowspan=\"5\">&nbsp;</td>\n"
                    "<td width=\"32\" rowspan=\"2\">&nbsp;</td>\n"
                    "<td colspan=\"10\" rowspan=\"5\">&nbsp;</td>\n"
                    "<td rowspan=\"15\" valign=\"bottom\"><img src=\"i_022.png\" alt=\"\" width=\"256\" height=\"162\"></td>\n"
                    "<td width=\"261\" rowspan=\"11\">&nbsp;</td>\n"
                  "</tr>\n"
                  "<tr>\n"
                    "<td colspan=\"2\" align=\"right\" valign=\"bottom\">&nbsp;</td>\n"
                    "<td>&nbsp;</td>\n"
                  "</tr>\n"
                  "\n"
                  "<tr>\n"
                    "<td colspan=\"2\" align=\"right\" valign=\"bottom\">&nbsp;</td>\n"
                    "<td width=\"28\">&nbsp;</td>\n"
                    "<td width=\"38\">&nbsp;</td>\n"
                    "<td>&nbsp;</td>\n"
                    "<td>&nbsp;</td>\n"
                  "</tr>\n"
                  "<tr>\n"
                    "<td colspan=\"2\" align=\"right\" valign=\"bottom\">&nbsp;</td>\n"
                    "<td width=\"28\">&nbsp;</td>\n"
                    "<td width=\"38\">&nbsp;</td>\n"
                    "<td>&nbsp;</td>\n"
                    "<td>&nbsp;</td>\n"
                  "</tr>\n"
                  "<tr>\n"
                    "<td colspan=\"2\" align=\"right\" valign=\"bottom\">&nbsp;</td>\n"
                    "<td width=\"28\">&nbsp;</td>\n"
                    "<td width=\"38\">&nbsp;</td>\n"
                    "<td height=\"13\">&nbsp;</td>\n"
                    "<td>&nbsp;</td>\n"
                  "</tr>\n"
                  "<tr>\n"
                    "<td colspan=\"2\" align=\"right\" valign=\"right\"><div id=\"ID_0x0320\">0.0V</div></td>\n"
                    "<td width=\"28\">&nbsp;</td>\n"
                    "<td width=\"38\" rowspan=\"5\"><img src=\"i_019.png\" alt=\"\" width=\"38\" height=\"71\"></td>\n"
                    "<td colspan=\"15\" valign=\"bottom\">&nbsp;</td>\n"
                    "<td valign=\"bottom\">&nbsp;</td>\n"
                    "<td colspan=\"13\" valign=\"bottom\">&nbsp;</td>\n"
                    "<td valign=\"bottom\">&nbsp;</td>\n"
                    "<td colspan=\"10\" valign=\"bottom\">&nbsp;</td>\n"
                  "</tr>\n"
                  "<tr>\n"
                    "<td colspan=\"2\" rowspan=\"3\" align=\"right\"><img src=\"i_018.png\" width=\"104\" height=\"64\"></td>\n"
                    "<td width=\"28\">&nbsp;</td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img1\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img2\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img3\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img4\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img5\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img6\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img7\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img8\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img9\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_014.png\" width=\"9\" height=\"8\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img11\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img12\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img13\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img14\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img15\"/></td>\n"
                    "<td rowspan=\"2\" valign=\"bottom\"><img src=\"i_015.png\" id=\"switch1\" width=\"32\" height=\"24\"></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img16\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img17\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img18\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img19\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img20\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img21\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_014.png\" width=\"9\" height=\"8\"></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img22\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img23\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img24\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img25\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img26\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img27\"/></td>\n"
                    "<td rowspan=\"2\" valign=\"bottom\"><img src=\"i_015.png\" id=\"switch2\" width=\"32\" height=\"24\"></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img28\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img29\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img30\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img31\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img32\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img33\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img34\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img35\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img36\"/></td>\n"
                    "<td width=\"9\" rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img37\"/></td>\n"
                  "</tr>\n"
                  "<tr>\n"
                    "<td><img src=\"i_017.png\" alt=\"1\" width=\"28\" height=\"17\" align=\"middle\"></td>\n"
                  "</tr>\n"
                  "\n"
                  "<tr>\n"
                    "<td width=\"28\" height=\"27\">&nbsp;</td>\n"
                    "<td colspan=\"9\" align=\"center\"><div id=\"ID_0x031B\">0.0Kw</div></td>\n"
                    "<td><img src=\"i_013.png\" id=\"vimg15\" style=\"display:none\"><img src=\"i_013.png\" id=\"vimg16\" style=\"display:none\"><img src=\"i_013.png\" id=\"vimg17\" style=\"display:none\"></td>\n"
                    "<td colspan=\"6\" align=\"center\"><div id=\"ID_0x031A\">0.0V</div></td>\n"
                    "<td colspan=\"6\">&nbsp;</td>\n"
                    "<td><img src=\"i_013.png\" id=\"vimg1\"><img src=\"i_013.png\" id=\"vimg2\"><img src=\"i_013.png\" id=\"vimg3\"></td>\n"
                    "<td colspan=\"7\" align=\"center\"><div id=\"ID_0x0322\">0.0Kw</div> </td>\n"
                    "<td colspan=\"10\" align=\"center\"><div id=\"ID_0x0317\">0.0V</div></td>\n"
                  "</tr>\n"
                  "<tr>\n"
                    "<td align=\"right\"><div id=\"ID_0x031F\"></div></td>\n"
                    "<td align=\"right\"><div id=\"ID_0x031E\"></div></td>\n"
                    "<td width=\"28\">&nbsp;</td>\n"
                    "<td height=\"13\" colspan=\"9\"></td>\n"
                    "<td ><img src=\"i_013.png\" id=\"vimg18\" style=\"display:none\"><img src=\"i_013.png\" id=\"vimg19\" style=\"display:none\"><img src=\"i_013.png\" id=\"vimg20\" style=\"display:none\"></td>\n"
                    "<td colspan=\"6\" align=\"center\" valign=\"top\">&nbsp;</td>\n"
                    "<td colspan=\"6\">&nbsp;</td>\n"
                    "<td><img src=\"i_013.png\" id=\"vimg4\"><img src=\"i_013.png\" id=\"vimg5\"><img src=\"i_013.png\" id=\"vimg6\"></td>\n"
                    "<td colspan=\"7\" align=\"center\"></td>\n"
                    "<td colspan=\"10\" align=\"center\" valign=\"top\">&nbsp;</td>\n"
                  "</tr>\n"
                  "<tr>\n"
                    "<td width=\"336\" align=\"right\"></td>\n"
                    "<td width=\"88\" align=\"right\"></td>\n"
                    "<td width=\"28\">&nbsp;</td>\n"
                    "<td width=\"38\">&nbsp;</td>\n"
                    "<td colspan=\"9\"></td>\n"
                    "<td><img src=\"i_013.png\" id=\"vimg21\" style=\"display:none\"><img src=\"i_013.png\" id=\"vimg22\" style=\"display:none\"><img src=\"i_013.png\" id=\"vimg23\" style=\"display:none\"></td>\n"
                    "<td colspan=\"6\" align=\"center\">&nbsp;</td>\n"
                    "<td colspan=\"6\">&nbsp;</td>\n"
                    "<td><img src=\"i_013.png\" id=\"vimg7\"><img src=\"i_013.png\" id=\"vimg8\"><img src=\"i_013.png\" id=\"vimg9\"></td>\n"
                    "<td colspan=\"7\" align=\"center\"></td>\n"
                    "<td colspan=\"10\" align=\"center\" valign=\"top\">&nbsp;</td>\n"
                  "</tr>\n"
                  "\n"
                  "<tr>\n"
                    "<td colspan=\"2\" rowspan=\"6\" align=\"right\" valign=\"middle\"><div id=\"ID_0x031C\" style='display:none;'>0.0V</div>\n"
                    "<img src=\"i_020.png\" alt=\"\" name=\"i_020\" width=\"102\" height=\"62\" align=\"right\" id=\"i_020\" style='display:none;'></td>\n"
                    "<td>&nbsp;</td>\n"
                    "<td valign=\"bottom\">&nbsp;</td>\n"
                    "<td colspan=\"9\"></td>\n"
                    "<td rowspan=\"2\"><img src=\"i_013.png\" id=\"vimg24\" style=\"display:none\"><img src=\"i_013.png\" id=\"vimg25\" style=\"display:none\"><img src=\"i_013.png\" id=\"vimg26\" style=\"display:none\"><img src=\"i_013.png\" id=\"vimg27\" style=\"display:none\"><img src=\"i_013.png\" id=\"vimg28\" style=\"display:none\"></td>\n"
                    "<td colspan=\"6\" align=\"center\">&nbsp;</td>\n"
                    "<td colspan=\"6\">&nbsp;</td>\n"
                    "<td rowspan=\"2\"><img src=\"i_013.png\" id=\"vimg10\"><img src=\"i_013.png\" id=\"vimg11\"><img src=\"i_013.png\" id=\"vimg12\"><img src=\"i_013.png\" id=\"vimg13\"><img src=\"i_013.png\" id=\"vimg14\"></td>\n"
                    "<td height=\"20\" colspan=\"7\" align=\"center\"><div id=\"ID_0x0319\">0.0Kw</div></td>\n"
                    "<td colspan=\"10\" rowspan=\"2\" align=\"center\" valign=\"top\">&nbsp;</td>\n"
                    "<td rowspan=\"6\" valign=\"top\">&nbsp;</td>\n"
                  "</tr>\n"
                  "<tr>\n"
                    "<td>&nbsp;</td>\n"
                    "<td valign=\"bottom\">&nbsp;</td>\n"
                    "<td colspan=\"9\"></td>\n"
                    "<td colspan=\"6\" align=\"center\">&nbsp;</td>\n"
                    "<td colspan=\"6\">&nbsp;</td>\n"
                    "<td height=\"20\" colspan=\"7\" align=\"center\"><div id=\"ID_0x0318\">0.0V</div></td>\n"
                  "</tr>\n"
                  "\n"
                  "<tr>\n"
                    "<td>&nbsp;</td>\n"
                    "<td rowspan=\"4\" valign=\"top\"><img src=\"i_021.png\" id=\"i_021\" style='display:none;' alt=\"\" width=\"38\" height=\"51\"></td>\n"
                    "<td rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img50\" style='display:none;'/></td>\n"
                    "<td rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img51\" style='display:none;'/></td>\n"
                    "<td rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img52\" style='display:none;'/></td>\n"
                    "<td rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img53\" style='display:none;'/></td>\n"
                    "<td rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img54\" style='display:none;'/></td>\n"
                    "<td rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img55\" style='display:none;'/></td>\n"
                    "<td rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img56\" style='display:none;'/></td>\n"
                    "<td rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img57\" style='display:none;'/></td>\n"
                    "<td rowspan=\"2\" valign=\"bottom\"><img src=\"i_010.png\" id=\"img58\" style='display:none;'/></td>\n"
                    "<td rowspan=\"2\" bordercolor=\"#F0F0F0\" margin=\"0\"><img src=\"i_013.png\" id=\"vimg29\" style=\"display:none\"><img src=\"i_013.png\" id=\"vimg30\" style=\"display:none\"><img src=\"i_013.png\" id=\"vimg31\" style=\"display:none\"><img src=\"i_013.png\" id=\"vimg32\" style=\"display:none\"></td>\n"
                    "<td colspan=\"6\" rowspan=\"2\" align=\"center\">&nbsp;</td>\n"
                    "<td colspan=\"24\" rowspan=\"4\" align=\"left\" valign=\"top\"><img src=\"i_023.png\" alt=\"1\" width=\"124\" height=\"57\"></td>\n"
                  "</tr>\n"
                  "<tr>\n"
                    "<td height=\"17\"><img src=\"i_017.png\" id=\"i_017\" style='display:none;' alt=\"1\" width=\"28\" height=\"17\" align=\"middle\"></td>\n"
                  "</tr>\n"
                  "<tr>\n"
                    "<td>&nbsp;</td>\n"
                    "<td colspan=\"9\" align=\"center\"><div id=\"ID_0x031D\" style='display:block;'>0.0Kw</div></td>\n"
                    "<td align=\"center\" valign=\"top\"></td>\n"
                    "<td colspan=\"6\" align=\"center\"></td>\n"
                    "<td valign=\"bottom\">&nbsp;</td>\n"
                  "</tr>\n"
                  "\n"
                  "<tr>\n"
                    "<td>&nbsp;</td>\n"
                    "<td colspan=\"16\" align=\"center\" valign=\"top\"></td>\n"
                    "<td valign=\"bottom\">&nbsp;</td>\n"
                  "</tr>\n"
          "</table>\n"
        "<div class='r4 back_color'></div>\n"
        "<div class='r3 back_color'></div>\n"
        "<div class='r2 back_color'></div>\n"
        "<div class='r1 back_color'></div>\n"
    "</div>\n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var FromMobileDevice=false;\n"
        "function FromWhichDevice()\n"
        "{\n"
            "var sUserAgent=navigator.userAgent.toLowerCase();\n"
            "var Ipad=sUserAgent.match(/ipad/i)=='ipad';\n"
            "var IphoneOs=sUserAgent.match(/iphone os/i)=='iphone os';\n"
            "var Android=sUserAgent.match(/android/i)=='android';\n"
            "var WindowsPhone=sUserAgent.match(/windows phone/i)=='windows phone';\n"
            "if(Ipad||IphoneOs||Android||WindowsPhone)FromMobileDevice=true;\n"
            "else FromMobileDevice=false;\n"
        "}\n"
        "function lang_init_ex(st,end){for(var i=st;i<=end;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
        "var $=function(o){return document.getElementById(o);};\n"
        "var language=0;\n"
        "var Json;\n"
        "var all_color=new Array('#3CF','#ABFF5D');\n"
        "var o_grid_contactor;\n"
        "var o_mgrid_contactor;\n"
        "var o_grid_direction;\n"
        "var o_mgrid_direction;\n"
        "var o_pcs_direction;\n"
        "var o_pv_direction;\n"
        "var o_load_direction;\n"
         //储能状态变化
        "function changePcsST(num)\n"
        "{\n"
          "if(num==0){\n"
            "for(var i=1;i<=9;i++){eval('$(\\'img'+i+'\\').src=\"i_010.png\"');}           \n"
          "}else if(num==1){     \n"
            "for(var i=1;i<=9;i++){eval('$(\\'img'+i+'\\').src=\"i_008.gif\";');}        \n"
          "}else if(num==2){\n"
            "for(var i=1;i<=9;i++){eval('$(\\'img'+i+'\\').src=\"i_009.gif\";');}\n"
          "}\n"
        "} \n"
"\n"
         //微网状态变化
        "function changeMGridST(num)\n"
        "{\n"
          "if(num==0){\n"
            "for(var i=11;i<=21;i++){eval('$(\\'img'+i+'\\').src=\"i_010.png\"');}           \n"
          "}else if(num==1){     \n"
            "for(var i=11;i<=21;i++){eval('$(\\'img'+i+'\\').src=\"i_008.gif\";');}        \n"
          "}else if(num==2){\n"
            "for(var i=11;i<=21;i++){eval('$(\\'img'+i+'\\').src=\"i_009.gif\";');}\n"
          "}\n"
        "}\n"
        "\n"
         //电网状态变化
        "function changeGirdST(num)\n"
        "{\n"
          "if(num==0){\n"
            "for(var i=22;i<=37;i++){eval('$(\\'img'+i+'\\').src=\"i_010.png\"');}           \n"
          "}else if(num==1){     \n"
            "for(var i=22;i<=37;i++){eval('$(\\'img'+i+'\\').src=\"i_008.gif\";');}        \n"
          "}else if(num==2){\n"
            "for(var i=22;i<=37;i++){eval('$(\\'img'+i+'\\').src=\"i_009.gif\";');}\n"
          "}     \n"
        "}\n"
        "\n"
         //接触器状态变化 id: 0 - 电网接触器  1 - 微网接触器
        "function changeSwST(id, sw)\n"
        "{\n"
            "switch(id)\n"
            "{\n"
                "case 0:\n"
                "{\n"
                    "if(sw==0){\n"
                        "$('switch2').src=\"i_015.png\";\n"
                    "}else if(sw==1)\n"
                    "{\n"
                        "$('switch2').src=\"i_016.png\";\n"
                    "}\n"
                "}\n"
                "break;\n"
                "case 1:\n"
                "{\n"
                    "if(sw==0){\n"
                        "$('switch1').src=\"i_015.png\";\n"
                    "}else if(sw==1)\n"
                    "{\n"
                        "$('switch1').src=\"i_016.png\";\n"
                    "}                       \n"
                "}\n"
                "break;\n"
                "default: \n"
                "break;\n"
            "}\n"
        "}\n"
        "\n"
         //负载状态变化
        "function changeLoadST(num)\n"
        "{\n"
            "if(num==0){\n"
                 //未供电
                "for(var i=1;i<=14;i++) {eval('$(\\'vimg'+i+'\\').src=\"i_013.png\"');}           \n"
            "}else if(num==1){\n"
                 //供电
                "for(var i=1;i<=14;i++){eval('$(\\'vimg'+i+'\\').src=\"i_012.gif\";');}\n"
            "}\n"
        "}\n"
        "\n"
         //PV状态变化
        "function changePvST(num)\n"
        "{\n"
            "if(num==0)\n"
            "{\n"
                "for(var i=50;i<=58;i++){eval('$(\\'img'+i+'\\').src=\"i_010.png\"');}   \n"
                "for(var i=15;i<=32;i++){eval('$(\\'vimg'+i+'\\').src=\"i_013.png\"');}                           \n"
            "}   \n"
            "\n"
            "if(num==1)\n"
            "{\n"
                "for(var i=50;i<=58;i++){eval('$(\\'img'+i+'\\').src=\"i_009.gif\"');}   \n"
                "for(var i=15;i<=32;i++){eval('$(\\'vimg'+i+'\\').src=\"i_011.gif\"');}       \n"
            "}               \n"
        "}     \n"
        "function Init()\n"
        "{\n"
            "FromWhichDevice();\n"
            "ajax_2s();\n"
            "setInterval('ajax_2s()',2000);\n"
        "}\n"
        "function ajax_2s()\n"
        "{\n"
            "var URL='s_031.html?time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function() \n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);\n"
         		"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
"\n"
                    "$('ID_0x0317').innerHTML=(Json.ID_0x0317/10.0).toFixed(1)+'V';\n"
                    "$('ID_0x0318').innerHTML=(Json.ID_0x0318/10.0).toFixed(1)+'V';\n"
                    "$('ID_0x0319').innerHTML=(Json.ID_0x0319/10.0).toFixed(1)+'kW';\n"
                    "$('ID_0x031A').innerHTML=(Json.ID_0x031A/10.0).toFixed(1)+'V';\n"
                    "$('ID_0x031B').innerHTML=(Json.ID_0x031B/10.0).toFixed(1)+'kW';\n"
                    "$('ID_0x031C').innerHTML=(Json.ID_0x031C/10.0).toFixed(1)+'V';\n"
                    "$('ID_0x031D').innerHTML=(Json.ID_0x031D/10.0).toFixed(1)+'kW';\n"
                    "if(Json.ID_0x038F==0xAA)$('ID_0x031E').innerHTML=(Json.ID_0x031E/10.0).toFixed(1)+'%';\n"
                     //$('ID_0x031F').innerHTML=(Json.ID_0x031F/10.0).toFixed(1)+'%';
                    "$('ID_0x0320').innerHTML=(Json.ID_0x0320/10.0).toFixed(1)+'V';\n"
                    "$('ID_0x0322').innerHTML=(Json.ID_0x0322/10.0).toFixed(1)+'kW';\n"
"\n"
                     //总线类型
                    "if(Json.ID_0x0381 == 0)\n"
                    "{\n"
                        "$('i_020').style.display='none';\n"
                        "$('i_017').style.display='none';\n"
                        "$('i_021').style.display='none'; \n"
                        "$('ID_0x031C').style.display='none'; \n"
                        "$('ID_0x031D').style.display='none'; \n"
                        "$('img50').style.display='none';\n"
                        "$('img51').style.display='none';\n"
                        "$('img52').style.display='none';\n"
                        "$('img53').style.display='none';\n"
                        "$('img54').style.display='none';\n"
                        "$('img55').style.display='none';\n"
                        "$('img56').style.display='none';\n"
                        "$('img57').style.display='none';\n"
                        "$('img58').style.display='none';  \n"
                        "$('vimg15').style.display='none';\n"
                        "$('vimg16').style.display='none';\n"
                        "$('vimg17').style.display='none';\n"
                        "$('vimg18').style.display='none';\n"
                        "$('vimg19').style.display='none';\n"
                        "$('vimg20').style.display='none';\n"
                        "$('vimg21').style.display='none';\n"
                        "$('vimg22').style.display='none';\n"
                        "$('vimg23').style.display='none';\n"
                        "$('vimg24').style.display='none';\n"
                        "$('vimg25').style.display='none';\n"
                        "$('vimg26').style.display='none';\n"
                        "$('vimg27').style.display='none';\n"
                        "$('vimg28').style.display='none';\n"
                        "$('vimg29').style.display='none';\n"
                        "$('vimg30').style.display='none';\n"
                        "$('vimg31').style.display='none';\n"
                        "$('vimg32').style.display='none';\n"
                    "}\n"
                    "else\n"
                    "{\n"
                        "$('i_020').style.display='block';\n"
                        "$('i_017').style.display='block';\n"
                        "$('i_021').style.display='block'; \n"
                        "$('ID_0x031C').style.display='block'; \n"
                        "$('ID_0x031D').style.display='block'; \n"
                        "$('img50').style.display='block';\n"
                        "$('img51').style.display='block';\n"
                        "$('img52').style.display='block';\n"
                        "$('img53').style.display='block';\n"
                        "$('img54').style.display='block';\n"
                        "$('img55').style.display='block';\n"
                        "$('img56').style.display='block';\n"
                        "$('img57').style.display='block';\n"
                        "$('img58').style.display='block'; \n"
                        "$('vimg15').style.display='block';\n"
                        "$('vimg16').style.display='block';\n"
                        "$('vimg17').style.display='block';\n"
                        "$('vimg18').style.display='block';\n"
                        "$('vimg19').style.display='block';\n"
                        "$('vimg20').style.display='block';\n"
                        "$('vimg21').style.display='block';\n"
                        "$('vimg22').style.display='block';\n"
                        "$('vimg23').style.display='block';\n"
                        "$('vimg24').style.display='block';\n"
                        "$('vimg25').style.display='block';\n"
                        "$('vimg26').style.display='block';\n"
                        "$('vimg27').style.display='block';\n"
                        "$('vimg28').style.display='block';\n"
                        "$('vimg29').style.display='block';\n"
                        "$('vimg30').style.display='block';\n"
                        "$('vimg31').style.display='block';\n"
                        "$('vimg32').style.display='block';\n"
                    "}\n"
"\n"
                     //电网接触器状态
                    "if(o_grid_contactor!=Json.ID_0x0310)\n"
                    "{\n"
                        "o_grid_contactor=Json.ID_0x0310;\n"
                        "changeSwST(0,o_grid_contactor); \n"
                    "}\n"
                    "\n"
                     //微网接触器状态
                    "if(o_mgrid_contactor!=Json.ID_0x0311)\n"
                    "{\n"
                        "o_mgrid_contactor=Json.ID_0x0311;\n"
                        "changeSwST(1,o_mgrid_contactor);\n"
                    "}\n"
"\n"
                     //电网图片滚动方向
                    "if(o_grid_direction!=Json.ID_0x0312)\n"
                    "{\n"
                        "o_grid_direction=Json.ID_0x0312;\n"
                        "changeGirdST(o_grid_direction);\n"
                    "}            \n"
"\n"
                     //微网图片滚动方向
                    "if(o_mgrid_direction!=Json.ID_0x0313)\n"
                    "{\n"
                        "o_mgrid_direction=Json.ID_0x0313;\n"
                        "changeMGridST(o_mgrid_direction);\n"
                    "}\n"
"\n"
                     //PCS图片滚动方向
                    "if(o_pcs_direction!=Json.ID_0x0309)\n"
                    "{\n"
                        "o_pcs_direction=Json.ID_0x0309;\n"
                        "changePcsST(o_pcs_direction);\n"
                    "}\n"
"\n"
                     //光伏逆变器滚动方向
                    "if(o_pv_direction!=Json.ID_0x0314)\n"
                    "{\n"
                        "o_pv_direction=Json.ID_0x0314;\n"
                        "changePvST(o_pv_direction);\n"
                    "}\n"
"\n"
                     //负载图片滚动方向
                    "if(o_load_direction!=Json.ID_0x0315)\n"
                    "{\n"
                        "o_load_direction=Json.ID_0x0315;\n"
                        "changeLoadST(o_load_direction);\n"
                    "}   \n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}\n"
    "</script>\n"
"</html>\n"
};
#endif
