#ifndef _HTML_H_046_H_
#define _HTML_H_046_H_
static const char h_046[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
        "<script language='javascript' type='text/javascript'>\n"
            "var language=1;\n"
            "var Json;\n"
            "var lang=\n"
            "{\n"
                "N01:['复位记录','Reset Records'],\n"
                "N02:['详细记录','Detailed Records'],\n"
                "N03:['序号','No.'],\n"
                "N04:['时间','Time'],\n"
                "N05:['描述','Description'],\n"
                "N06:['一共','Total '],\n"
                "N07:['页，共',' pages, '],\n"
                "N08:['页，共',' page, '],\n"
                "N09:['条记录',' records'],\n"
                "N10:['条记录',' record'],\n"
                "N11:['无记录。','No record.'],\n"
"\n"
                "N44:['刷新','Refresh']\n"
            "};\n"
        "</script>\n"
        "<script src='j_000.js' type='text/javascript'></script>\n"
        "<style type='text/css'>\n"
            ".inquery{margin:5px auto;width:780px;_width:770px;text-align:right;padding-right:10px;}\n"
            ".txt{margin:0 10px;width:120px;}\n"
            ".PagerView{font-size:12px;font-family:tahoma,arial;color:#333;text-align:center;padding:8px;line-height:100%;}\n"
            ".PagerView span{color:#999;margin:0 1px;padding:3px 6px;border:1px solid #ccc;}\n"
            ".PagerView span.on{color:#fff;font-weight:bold;border:1px solid #666;background:#39f;}\n"
            ".PagerView a{color:#00f;text-decoration:none;}\n"
            ".PagerView a span{color:#33f;border:1px solid #66c;}\n"
            ".pager{width:780px;margin:0 auto;}\n"
        "</style>\n"
    "</head>\n"
    "<body onload='Init()'>\n"
        "<script type='text/javascript'>\n"
            "show_T('N01');\n"
        "</script>\n"
 	"<div class='title'>\n"
 		"<div class='subtitle'>\n"
 			"<div class='r1 subcolor'></div>\n"
 			"<div class='r2 subcolor'></div>\n"
 			"<div class='r3 subcolor'></div>\n"
 			"<div class='r4 subcolor'></div>\n"
 			"<div class='content subcolor subcontent'>\n"
 				"<span id='N02'></span>\n"
 			"</div>\n"
 			"<div class='r4 subcolor'></div>\n"
 			"<div class='r3 subcolor'></div>\n"
 			"<div class='r2 subcolor'></div>\n"
 			"<div class='r1 subcolor'></div>\n"
 			"</div>\n"
 			"<div class='line_short'></div>\n"
 			"</div>\n"
 	"</div>\n"
        "<table width='90%' border='0' style=' margin:0 auto;'>\n"
            "<tr>\n"
                "<td>\n"
                    "<table width='100%' border='0' style='border-collapse:collapse;border:1px #aaa solid;'>\n"
                        "<tr>\n"
                            "<th width='100' scope='col'><span id='N03'></span></span></th>\n"
                            "<th width='332' scope='col'><span id='N04'></span></th>\n"
                            "<th width='332' scope='col'><span id='N05'></span></th>\n"
                        "</tr>\n"
                    "</table>\n"
                "</td>\n"
            "</tr>\n"
            "<tr>\n"
                "<td>\n"
                    "<table width='100%' border='0' style='margin-top:2px;border-collapse:collapse;border:1px #ddd solid;text-align:center'>\n"
                        "<script type='text/javascript'>\n"
                            "var str='';\n"
                            "for(var i=1;i<=10;i++)\n"
                            "{\n"
                                "str+=\"<tr class='\"+(i%2?\"odd\":\"even\")+\"'>\";\n"
                                "str+=\"<td id='r\"+(i<10?(\"0\"+i):i)+\"1' width='100'></td>\";\n"
                                "str+=\"<td id='r\"+(i<10?(\"0\"+i):i)+\"2' width='332'></td>\";\n"
                                "str+=\"<td id='r\"+(i<10?(\"0\"+i):i)+\"3' width='332'></td>\";\n"
                                "str+=\"</tr>\";\n"
                            "}\n"
                            "document.write(str);\n"
                        "</script>\n"
                    "</table>\n"
                    "<img id='waiting' style='margin:0 auto;z-index:20000;position:relative;top:-168px;' src='i_002.gif'/>\n"
                "</td>\n"
            "</tr>\n"
        "</table>\n"
        "<br/>\n"
        "<div id='pager'></div>\n"
        "<table width='90%' border='0'><tr><td width='100%' class='even tip'><span id='tip'>&nbsp;</span></td></tr></table>\n"
        "<div class='btm_blank'></div>\n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var pager;\n"
        "var tid;\n"
        "var temp;\n"
        "var page_num=1;\n"
"\n"
        "function Init()\n"
        "{\n"
 		"FromWhichDevice();\n"
 		"if(FromMobileDevice==true)$('ReFresh').style.display='none';\n"
"\n"
            "var URL='s_046.html?0x0000&time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);\n"
         		"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
         		"lang_init(5);\n"
         		"doSubmit();\n"
         		"show_tip('&nbsp;');\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}\n"
 	"var E_id=new Array('1','2','3','4','5','6','7',\n"
 						  "'8','9','10','11','12','13','14','15',\n"
 						  "'16','17','18','19','20','21','22','23',\n"
 						  "'24','25','26','27','28','29','30','31','32');\n"
 	"var E_name=new Array('12','13','14','15','16','17','18','19',\n"
 							"'20','21','22','23','24','25','26','27',\n"
 							"'28','29','30','31','32','33','34','35',\n"
 							"'36','37','38','39','40','41','42','43');\n"
        "function doSubmit()\n"
        "{\n"
             //调试
 			//temp={'r':[
             //{'C1':1,'C2':'2014/08/13&nbsp;&nbsp;14:52:18','C3':''},
             //{'C1':2,'C2':'2014/08/13&nbsp;&nbsp;14:52:15','C3':''},
             //{'C1':3,'C2':'2014/08/13&nbsp;&nbsp;14:52:11','C3':''},
             //{'C1':4,'C2':'2014/08/13&nbsp;&nbsp;14:52:08','C3':''},
             //{'C1':5,'C2':'2014/08/13&nbsp;&nbsp;14:52:04','C3':''},
             //{'C1':6,'C2':'2014/08/13&nbsp;&nbsp;14:52:00','C3':''},
             //{'C1':7,'C2':'2014/08/13&nbsp;&nbsp;14:51:58','C3':''},
             //{'C1':8,'C2':'2014/08/13&nbsp;&nbsp;14:51:55','C3':''},
             //{'C1':9,'C2':'2014/08/13&nbsp;&nbsp;14:51:52','C3':''},
             //{'C1':10,'C2':'2014/08/13&nbsp;&nbsp;14:14:41','C3':''},
             //{'end':0}]};Records=14;
"\n"
            "var URL='r_046.html?'\n"
            "+'Y='+2000\n"
            "+'&M='+1\n"
            "+'&D='+1\n"
             //分页获取记录，每页10条记录
            "+'&P='+page_num\n"
            "+'&time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('temp='+xmlhttp.responseText);\n"
         		"loop=temp.r.length-1;\n"
                    "show_tip('&nbsp;');\n"
         		"for(var aa=0;aa<loop;aa++)\n"
         		"{\n"
         			"tid=(aa<9)?'0'+(aa+1):aa+1;\n"
         			"for(var j=1;j<=3;j++)\n"
         			"{\n"
         				"eval(\"$('r'+tid+'\"+j+\"').innerHTML=temp.r[aa].C\"+j+\";\");\n"
         					//if(j==3)for(var k=0;k<E_id.length;k++)eval(\"eval(\\\"if(temp.r[aa].C\\\"+\\\"\"+j+\"==E_id[k])$('r\\\"+\\\"\"+tid+\"3').innerHTML=lang.N\"+E_name[k]+\"[language];\\\")\");
         			"}\n"
         		"}\n"
         		"for(var bb=loop;bb<10;bb++)\n"
         		"{\n"
         			"tid=(bb<9)?'0'+(bb+1):bb+1;\n"
         			"for(var k=1;k<=3;k++)$('r'+tid+k).innerHTML='';\n"
         		"}\n"
         		"if(Records<=10)\n"
         		"{\n"
         			"if(Records==0)\n"
         			"{\n"
         				"show_tip(lang.N11[language]);\n"
         				"$('waiting').style.display='none';\n"
         				"$('pager').style.display='none';\n"
         				"return false;\n"
         			"}\n"
         			"else if(Records==1)\n"
         			"{\n"
         				"$('pager').style.display='block';\n"
         				"pager=new PagerView('pager',lang.N06[language],lang.N08[language],lang.N10[language]);\n"
         			"}\n"
         			"else\n"
         			"{\n"
         				"$('pager').style.display='block';\n"
         				"pager=new PagerView('pager',lang.N06[language],lang.N08[language],lang.N09[language]);\n"
         			"}\n"
         		"}\n"
         		"else\n"
         		"{\n"
         			"$('pager').style.display='block';\n"
         			"pager=new PagerView('pager',lang.N06[language],lang.N07[language],lang.N09[language]);\n"
         		"}\n"
         		"pager.itemCount=Records;\n"
         		"pager.size=10;\n"
         		"pager.index=1;\n"
         		"pager.onclick=function(index)\n"
         		"{\n"
                        "var URL='r_046.html?'\n"
                        "+'Y='+2000\n"
                        "+'&M='+1\n"
                        "+'&D='+1\n"
                        "+'&P='+index\n"
                        "+'&time='+Math.random();\n"
"\n"
                        "var xmlhttp;\n"
                        "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                        "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                        "xmlhttp.onreadystatechange=function()\n"
                        "{\n"
                            "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                            "{                      \n"
                                "show_tip('&nbsp;');\n"
                                "eval('temp='+xmlhttp.responseText);\n"
                 			"if(temp.r.length>10)\n"
                 			"{\n"
                                    "loop=10;\n"
                                "}\n"
                 			"else \n"
                 			"{\n"
                                    "loop=temp.r.length-1;\n"
                                "}\n"
                 			"for(var cc=0;cc<loop;cc++)\n"
                 			"{\n"
                 				"tid=(cc<9)?'0'+(cc+1):cc+1;\n"
                 				"for(var j=1;j<=3;j++)\n"
                 				"{\n"
                 					"eval(\"$('r'+tid+'\"+j+\"').innerHTML=temp.r[cc].C\"+j+\";\");\n"
                 						//if(j==3)for(var k=0;k<E_id.length;k++)eval(\"eval(\\\"if(temp.r[cc].C\\\"+\\\"\"+j+\"==E_id[k])$('r\\\"+\\\"\"+tid+\"3').innerHTML=lang.N\"+E_name[k]+\"[language];\\\")\");
                 				"}\n"
                 			"}\n"
                                 //从最后一条清空到表尾的记录
                 			"for(var dd=loop;dd<10;dd++)\n"
                 			"{\n"
                 				"tid=(dd<9)?'0'+(dd+1):dd+1;\n"
                 				"for(var k=1;k<=3;k++)$('r'+tid+k).innerHTML='';\n"
                 			"}\n"
                 			"$('waiting').style.display='none';\n"
                            "}\n"
                         "};\n"
                        "xmlhttp.open('GET',URL,true);\n"
                        "xmlhttp.send();\n"
                        "$('waiting').style.display='inline';\n"
                    "};\n"
                    "pager.render();\n"
                    "$('waiting').style.display='none';\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
            "$('waiting').style.display='inline';\n"
        "}\n"
    "</script>\n"
"</html>\n"
};
#endif
