#ifndef _HTML_H_048_H_
#define _HTML_H_048_H_
static const char h_048[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
        "<style type='text/css'>\n"
            "tr{height:27px;}\n"
            ".select{width:180px;_width:150px;}\n"
            ".time{width:65px;_width:100px;}\n"
            ".txt{width:70px;text-align:center;}\n"
            ".short_txt{width:50px;}\n"
            ".td_value{text-align:right;padding-right:20px;}\n"
            ".td1{padding-left:20px;padding-right:20px;text-align:left;}\n"
            ".td2{padding-left:0px;text-align:center;}\n"
            ".td3{padding-left:60px;text-align:left;}\n"
            ".td4{padding-right:5px;text-align:right;}\n"
            ".td5{padding-right:10px;text-align:right;}\n"
            ".radio{padding-left:30px;}\n"
            ".btnStyle{width:70px;height:24px;}\n"
            ".submenu{line-height:32px;padding-left:20px;width:225px;height:32px;color:#000;background-color:#eee;font-weight:normal;font-size:14px;}\n"
            ".PagerView{font-size:12px;font-family:tahoma,arial;color:#333;text-align:center;padding:8px;line-height:100%;}\n"
            ".PagerView span{color:#999;margin:0 1px;padding:3px 6px;border:1px solid #ccc;}\n"
            ".PagerView span.on{color:#fff;font-weight:bold;border:1px solid #666;background:#39f;}\n"
            ".PagerView a{color:#00f;text-decoration:none;}\n"
            ".PagerView a span{color:#33f;border:1px solid #66c;}\n"
            ".pager{width:780px;margin:0 auto;}\n"
        "</style>    \n"
        "<script type='text/javascript'>\n"
            "var $=function(o){return document.getElementById(o);};\n"
            "function lang_init_ex(st,end){for(var i=st;i<=end;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
            "function show_tip(obj){$('tip').innerHTML=obj;}\n"
            "function show_T(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
                "str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_net_pcs()\n"
            "{\n"
                "var str='';\n"
                "str+=\"<table id='tbl_net_pcs' width='90%' border='1' bordercolor='#E0E0E0' style='display:none;'>\";\n"
                "for(var i=0; i<60; i++)\n"
                "{\n"
                    "if(i%2==0){\n"
                        "str+=\"<tr id='trSrv\"+i+\"' style='display:none;'>\";\n"
                        "str+=\"<td width='28%' class='td1 odd' style='text-align:center;'><span id='N\"+(564+i*3)+\"'></span></td>\";\n"
                        "str+=\"<td width='17%' class='td1 odd' style='text-align:center;'><input style='width:135px;text-align:center;' id='SerIP\"+i+\"' onkeyup='IPverify(this)' type='text'/></td>\";\n"
                        "str+=\"<td width='17%' class='td1 odd' style='text-align:center;'><span id='N\"+(564+i*3+1)+\"'></span></td>\";\n"
                        "str+=\"<td width='13%' class='td1 odd' style='text-align:center;'><input style='width:80px;text-align:center;' id='PORT\"+i+\"' onkeyup='doRangeCheck(this,reg)' type='text'/></td>\";\n"
                        "str+=\"<td width='13%' class='td1 odd' style='text-align:center;'><span id='N\"+(564+i*3+2)+\"'></span></td>\";\n"
                        "str+=\"<td width='13%' class='td1 odd' style='text-align:center;'><select style='width:80px;text-align:center;' id='ID\"+i+\"'></select></td>\";\n"
                        "str+=\"<td width='10%' align='right' class='odd'><button class='btnStyle' onclick='doSubmit(this)' id='N\"+(50+i)+\"' style='display:block;'></button></td>\";\n"
                        "str+=\"</tr>\";                       \n"
                    "}else{\n"
                        "str+=\"<tr id='trSrv\"+i+\"' style='display:none;'>\";\n"
                        "str+=\"<td width='28%' class='td1 even' style='text-align:center;'><span id='N\"+(564+i*3)+\"'></span></td>\";\n"
                        "str+=\"<td width='17%' class='td1 even' style='text-align:center;'><input style='width:135px;text-align:center;' id='SerIP\"+i+\"' onkeyup='IPverify(this)' type='text'/></td>\";\n"
                        "str+=\"<td width='17%' class='td1 even' style='text-align:center;'><span id='N\"+(564+i*3+1)+\"'></span></td>\";\n"
                        "str+=\"<td width='13%' class='td1 even' style='text-align:center;'><input style='width:80px;text-align:center;' id='PORT\"+i+\"' onkeyup='doRangeCheck(this,reg)' type='text'/></td>\";\n"
                        "str+=\"<td width='13%' class='td1 even' style='text-align:center;'><span id='N\"+(564+i*3+2)+\"'></span></td>\";\n"
                        "str+=\"<td width='13%' class='td1 even' style='text-align:center;'><select style='width:80px;text-align:center;' id='ID\"+i+\"'></select></td>\";\n"
                        "str+=\"<td width='10%' align='right' class='even'><button class='btnStyle' onclick='doSubmit(this)' id='N\"+(50+i)+\"' style='display:block;'></button></td>\";\n"
                        "str+=\"</tr>\";\n"
                    "}\n"
                "}\n"
                "str+=\"</table>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_sT(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_sT_ex(tid, id)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' id='\"+id+\"' style='display:none;width:90%'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function sendHttpReq(url, successFn)\n"
            "{\n"
                 //alert(url);   
                "var xmlhttp;\n"
                "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                "xmlhttp.onreadystatechange=function()\n"
                "{\n"
                    "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                    "{\n"
                        "if(xmlhttp.responseText=='1'){successFn();}\n"
                    "}\n"
                "};\n"
                "xmlhttp.open('GET',url,true);\n"
                "xmlhttp.send();\n"
            "}   \n"
        "var PagerView=function(id,AAA,BBB,CCC)\n"
            "{\n"
                "var self=this;\n"
                "this.id=id;\n"
                "this._pageCount=0;\n"
                "this._start=1;\n"
                "this._end=1;\n"
                "this.container=null;\n"
                "this.index=1;\n"
                "this.size=10;\n"
                "this.maxButtons=10;\n"
                "this.itemCount=0;\n"
                "this.onclick=function(index){return true;};\n"
                "this._onclick=function(index)\n"
                "{\n"
                    "var old=self.index;\n"
                    "self.index=index;\n"
                    "if(self.onclick(index)!==false)self.render();\n"
                    "else self.index=old;\n"
                "};\n"
                "this._calculate=function()\n"
                "{\n"
                    "self._pageCount=parseInt(Math.ceil(self.itemCount/self.size));\n"
                    "self.index=parseInt(self.index);\n"
                    "if(self.index>self._pageCount)self.index=self._pageCount;\n"
                    "if(self.index<1)self.index=1;\n"
                    "self._start=Math.max(1,self.index-parseInt(self.maxButtons/2));\n"
                    "self._end=Math.min(self._pageCount,self._start+self.maxButtons-1);\n"
                    "self._start=Math.max(1,self._end-self.maxButtons+1);\n"
                "};\n"
                "this.page=function(rows)\n"
                "{\n"
                    "self._calculate();\n"
                    "var s_num=(self.index-1)*self.size ;\n"
                    "var e_num=self.index*self.size;\n"
                    "return rows.slice(s_num,e_num);\n"
                "};\n"
                "this.render=function()\n"
                "{\n"
                    "var div=document.getElementById(self.id);\n"
                    "div.view=self;\n"
                    "self.container=div;\n"
                    "self._calculate();\n"
                    "var str='';\n"
                    "str+='<div class=\"PagerView\">\\n';\n"
                    "if(self._pageCount>1)\n"
                    "{\n"
                        "if(self.index!=1)\n"
                        "{\n"
                            "str+='<a href=\"javascript://1\"><span>|&lt;</span></a>';\n"
                            "str+='<a href=\"javascript://'+(self.index-1)+'\"><span>&lt;&lt;</span></a>';\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "str+='<span>|&lt;</span>';\n"
                            "str+='<span>&lt;&lt;</span>';\n"
                        "}\n"
                    "}\n"
                    "for(var i=self._start;i<=self._end;i++)\n"
                    "{\n"
                        "if(i==this.index)\n"
                        "{\n"
                            "if(i<10)str+='<span class=\"on\">'+'0'+i+\"</span>\";\n"
                            "else str+='<span class=\"on\">'+i+\"</span>\";\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "if(i<10)str+='<a href=\"javascript://'+i+'\"><span>'+'0'+i+\"</span></a>\";\n"
                            "else str+='<a href=\"javascript://'+i+'\"><span>'+i+\"</span></a>\";\n"
                        "}\n"
                    "}\n"
                    "if(self._pageCount>1)\n"
                    "{\n"
                        "if(self.index!=self._pageCount)\n"
                        "{\n"
                            "str+='<a href=\"javascript://'+(self.index+1)+'\"><span>&gt;&gt;</span></a>';\n"
                            "str+='<a href=\"javascript://'+self._pageCount+'\"><span>&gt;|</span></a>';\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "str+='<span>&gt;&gt;</span>';\n"
                            "str+='<span>&gt;|</span>';\n"
                        "}\n"
                    "}\n"
                    "str+=AAA+self._pageCount+BBB+self.itemCount+CCC;\n"
                    "str+='</div><!--/.pagerView-->\\n';\n"
                    "self.container.innerHTML=str;\n"
                    "var a_list=self.container.getElementsByTagName('a');\n"
                    "for(var i=0;i<a_list.length;i++)\n"
                    "{\n"
                        "a_list[i].onclick=function()\n"
                        "{\n"
                            "var index=this.getAttribute('href');\n"
                            "if(index!=undefined&&index!='')\n"
                            "{\n"
                                "index=parseInt(index.replace('javascript://',''));\n"
                                "self._onclick(index);\n"
                            "}\n"
                            "return false;\n"
                        "};\n"
                    "}\n"
                "};\n"
            "};\n"
        "</script>\n"
        "<script type='text/javascript'>\n"
            "var language=0;\n"
             //正整数+0
            "var reg=/^(0|[1-9]\\d*)$/;\n"
            "var Json;\n"
            "var flg_pcs = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];\n"
            "var lang=\n"
            "{\n"
                 //PCS 网口
                "N50:['设&nbsp;&nbsp;置','Set'],\n"
                "N51:['设&nbsp;&nbsp;置','Set'],\n"
                "N52:['设&nbsp;&nbsp;置','Set'],\n"
                "N53:['设&nbsp;&nbsp;置','Set'],\n"
                "N54:['设&nbsp;&nbsp;置','Set'],\n"
                "N55:['设&nbsp;&nbsp;置','Set'],\n"
                "N56:['设&nbsp;&nbsp;置','Set'],\n"
                "N57:['设&nbsp;&nbsp;置','Set'],\n"
                "N58:['设&nbsp;&nbsp;置','Set'],\n"
                "N59:['设&nbsp;&nbsp;置','Set'],\n"
                "N60:['设&nbsp;&nbsp;置','Set'],\n"
                "N61:['设&nbsp;&nbsp;置','Set'],\n"
                "N62:['设&nbsp;&nbsp;置','Set'],\n"
                "N63:['设&nbsp;&nbsp;置','Set'],\n"
                "N64:['设&nbsp;&nbsp;置','Set'],\n"
                "N65:['设&nbsp;&nbsp;置','Set'],\n"
                "N66:['设&nbsp;&nbsp;置','Set'],\n"
                "N67:['设&nbsp;&nbsp;置','Set'],\n"
                "N68:['设&nbsp;&nbsp;置','Set'],\n"
                "N69:['设&nbsp;&nbsp;置','Set'],\n"
                "N70:['设&nbsp;&nbsp;置','Set'],\n"
                "N71:['设&nbsp;&nbsp;置','Set'],\n"
                "N72:['设&nbsp;&nbsp;置','Set'],\n"
                "N73:['设&nbsp;&nbsp;置','Set'],\n"
                "N74:['设&nbsp;&nbsp;置','Set'],\n"
                "N75:['设&nbsp;&nbsp;置','Set'],\n"
                "N76:['设&nbsp;&nbsp;置','Set'],\n"
                "N77:['设&nbsp;&nbsp;置','Set'],\n"
                "N78:['设&nbsp;&nbsp;置','Set'],\n"
                "N79:['设&nbsp;&nbsp;置','Set'],\n"
                "N80:['设&nbsp;&nbsp;置','Set'],\n"
                "N81:['设&nbsp;&nbsp;置','Set'],\n"
                "N82:['设&nbsp;&nbsp;置','Set'],\n"
                "N83:['设&nbsp;&nbsp;置','Set'],\n"
                "N84:['设&nbsp;&nbsp;置','Set'],\n"
                "N85:['设&nbsp;&nbsp;置','Set'],\n"
                "N86:['设&nbsp;&nbsp;置','Set'],\n"
                "N87:['设&nbsp;&nbsp;置','Set'],\n"
                "N88:['设&nbsp;&nbsp;置','Set'],\n"
                "N89:['设&nbsp;&nbsp;置','Set'],\n"
                "N90:['设&nbsp;&nbsp;置','Set'],\n"
                "N91:['设&nbsp;&nbsp;置','Set'],\n"
                "N92:['设&nbsp;&nbsp;置','Set'],\n"
                "N93:['设&nbsp;&nbsp;置','Set'],\n"
                "N94:['设&nbsp;&nbsp;置','Set'],\n"
                "N95:['设&nbsp;&nbsp;置','Set'],\n"
                "N96:['设&nbsp;&nbsp;置','Set'],\n"
                "N97:['设&nbsp;&nbsp;置','Set'],\n"
                "N98:['设&nbsp;&nbsp;置','Set'],\n"
                "N99:['设&nbsp;&nbsp;置','Set'],\n"
                "N100:['设&nbsp;&nbsp;置','Set'],\n"
                "N101:['设&nbsp;&nbsp;置','Set'],\n"
                "N102:['设&nbsp;&nbsp;置','Set'],\n"
                "N103:['设&nbsp;&nbsp;置','Set'],\n"
                "N104:['设&nbsp;&nbsp;置','Set'],\n"
                "N105:['设&nbsp;&nbsp;置','Set'],\n"
                "N106:['设&nbsp;&nbsp;置','Set'],\n"
                "N107:['设&nbsp;&nbsp;置','Set'],\n"
                "N108:['设&nbsp;&nbsp;置','Set'],\n"
                "N109:['设&nbsp;&nbsp;置','Set'],\n"
"\n"
                "N500:['一共','Total '],\n"
                "N501:['页，共',' Pages, '],\n"
                "N502:['页，共',' Page, '],\n"
                "N503:['台',' Nums'],\n"
                "N504:['台',' Num'],\n"
"\n"
                "N541:['设置失败！','Set failed!'],\n"
                "N542:['设置成功！','Set successfully!'],\n"
                "N543:['格式错误！','Format error!'],\n"
                "N544:['范围错误！','Range error!'],\n"
"\n"
                "N550:['设&nbsp;&nbsp;置','Set'],\n"
                "N551:['设&nbsp;&nbsp;置','Set'],\n"
"\n"
                "N564:['储能逆变器01 IP','Server01 IP'],\n"
                "N565:['端口号','Port'],\n"
                "N566:['ID','ID'],\n"
                "N567:['储能逆变器02 IP','Server02 IP'],\n"
                "N568:['端口号','Port'],\n"
                "N569:['ID','ID'],\n"
                "N570:['储能逆变器03 IP','Server03 IP'],\n"
                "N571:['端口号','Port'],\n"
                "N572:['ID','ID'],\n"
                "N573:['储能逆变器04 IP','Server04 IP'],\n"
                "N574:['端口号','Port'],\n"
                "N575:['ID','ID'],\n"
                "N576:['储能逆变器05 IP','Server05 IP'],\n"
                "N577:['端口号','Port'],\n"
                "N578:['ID','ID'],\n"
                "N579:['储能逆变器06 IP','Server06 IP'],\n"
                "N580:['端口号','Port'],\n"
                "N581:['ID','ID'],\n"
                "N582:['储能逆变器07 IP','Server07 IP'],\n"
                "N583:['端口号','Port'],\n"
                "N584:['ID','ID'],\n"
                "N585:['储能逆变器08 IP','Server08 IP'],\n"
                "N586:['端口号','Port'],\n"
                "N587:['ID','ID'],\n"
                "N588:['储能逆变器09 IP','Server09 IP'],\n"
                "N589:['端口号','Port'],\n"
                "N590:['ID','ID'],\n"
                "N591:['储能逆变器10 IP','Server10 IP'],\n"
                "N592:['端口号','Port'],\n"
                "N593:['ID','ID'],\n"
                "N594:['储能逆变器11 IP','Server11 IP'],\n"
                "N595:['端口号','Port'],\n"
                "N596:['ID','ID'],\n"
                "N597:['储能逆变器12 IP','Server12 IP'],\n"
                "N598:['端口号','Port'],\n"
                "N599:['ID','ID'],\n"
                "N600:['储能逆变器13 IP','Server13 IP'],\n"
                "N601:['端口号','Port'],\n"
                "N602:['ID','ID'],\n"
                "N603:['储能逆变器14 IP','Server14 IP'],\n"
                "N604:['端口号','Port'],\n"
                "N605:['ID','ID'],\n"
                "N606:['储能逆变器15 IP','Server15 IP'],\n"
                "N607:['端口号','Port'],\n"
                "N608:['ID','ID'],\n"
                "N609:['储能逆变器16 IP','Server16 IP'],\n"
                "N610:['端口号','Port'],\n"
                "N611:['ID','ID'],\n"
                "N612:['储能逆变器17 IP','Server17 IP'],\n"
                "N613:['端口号','Port'],\n"
                "N614:['ID','ID'],\n"
                "N615:['储能逆变器18 IP','Server18 IP'],\n"
                "N616:['端口号','Port'],\n"
                "N617:['ID','ID'],\n"
                "N618:['储能逆变器19 IP','Server19 IP'],\n"
                "N619:['端口号','Port'],\n"
                "N620:['ID','ID'],\n"
                "N621:['储能逆变器20 IP','Server20 IP'],\n"
                "N622:['端口号','Port'],\n"
                "N623:['ID','ID'],\n"
                "N624:['储能逆变器21 IP','Server21 IP'],\n"
                "N625:['端口号','Port'],\n"
                "N626:['ID','ID'],\n"
                "N627:['储能逆变器22 IP','Server22 IP'],\n"
                "N628:['端口号','Port'],\n"
                "N629:['ID','ID'],\n"
                "N630:['储能逆变器23 IP','Server23 IP'],\n"
                "N631:['端口号','Port'],\n"
                "N632:['ID','ID'],\n"
                "N633:['储能逆变器24 IP','Server24 IP'],\n"
                "N634:['端口号','Port'],\n"
                "N635:['ID','ID'],\n"
                "N636:['储能逆变器25 IP','Server25 IP'],\n"
                "N637:['端口号','Port'],\n"
                "N638:['ID','ID'],\n"
                "N639:['储能逆变器26 IP','Server26 IP'],\n"
                "N640:['端口号','Port'],\n"
                "N641:['ID','ID'],\n"
                "N642:['储能逆变器27 IP','Server27 IP'],\n"
                "N643:['端口号','Port'],\n"
                "N644:['ID','ID'],               \n"
                "N645:['储能逆变器28 IP','Server28 IP'],\n"
                "N646:['端口号','Port'],\n"
                "N647:['ID','ID'],           \n"
                "N648:['储能逆变器29 IP','Server29 IP'],\n"
                "N649:['端口号','Port'],\n"
                "N650:['ID','ID'],   \n"
                "N651:['储能逆变器30 IP','Server30 IP'],\n"
                "N652:['端口号','Port'],\n"
                "N653:['ID','ID'],\n"
                "N654:['储能逆变器31 IP','Server31 IP'],\n"
                "N655:['端口号','Port'],\n"
                "N656:['ID','ID'],   \n"
                "N657:['储能逆变器32 IP','Server32 IP'],\n"
                "N658:['端口号','Port'],\n"
                "N659:['ID','ID'],\n"
                "N660:['储能逆变器33 IP','Server33 IP'],\n"
                "N661:['端口号','Port'],\n"
                "N662:['ID','ID'],\n"
                "N663:['储能逆变器34 IP','Server34 IP'],\n"
                "N664:['端口号','Port'],\n"
                "N665:['ID','ID'],\n"
                "N666:['储能逆变器35 IP','Server35 IP'],\n"
                "N667:['端口号','Port'],\n"
                "N668:['ID','ID'],\n"
                "N669:['储能逆变器36 IP','Server36 IP'],\n"
                "N670:['端口号','Port'],\n"
                "N671:['ID','ID'],\n"
                "N672:['储能逆变器37 IP','Server37 IP'],\n"
                "N673:['端口号','Port'],\n"
                "N674:['ID','ID'],               \n"
                "N675:['储能逆变器38 IP','Server38 IP'],\n"
                "N676:['端口号','Port'],\n"
                "N677:['ID','ID'],           \n"
                "N678:['储能逆变器39 IP','Server39 IP'],\n"
                "N679:['端口号','Port'],\n"
                "N680:['ID','ID'],   \n"
                "N681:['储能逆变器40 IP','Server40 IP'],\n"
                "N682:['端口号','Port'],\n"
                "N683:['ID','ID'],   \n"
                "N684:['储能逆变器41 IP','Server41 IP'],\n"
                "N685:['端口号','Port'],\n"
                "N686:['ID','ID'],   \n"
                "N687:['储能逆变器42 IP','Server42 IP'],\n"
                "N688:['端口号','Port'],\n"
                "N689:['ID','ID'],\n"
                "N690:['储能逆变器43 IP','Server43 IP'],\n"
                "N691:['端口号','Port'],\n"
                "N692:['ID','ID'],\n"
                "N693:['储能逆变器44 IP','Server44 IP'],\n"
                "N694:['端口号','Port'],\n"
                "N695:['ID','ID'],\n"
                "N696:['储能逆变器45 IP','Server45 IP'],\n"
                "N697:['端口号','Port'],\n"
                "N698:['ID','ID'],\n"
                "N699:['储能逆变器46 IP','Server46 IP'],\n"
                "N700:['端口号','Port'],\n"
                "N701:['ID','ID'],\n"
                "N702:['储能逆变器47 IP','Server47 IP'],\n"
                "N703:['端口号','Port'],\n"
                "N704:['ID','ID'],               \n"
                "N705:['储能逆变器48 IP','Server48 IP'],\n"
                "N706:['端口号','Port'],\n"
                "N707:['ID','ID'],           \n"
                "N708:['储能逆变器49 IP','Server49 IP'],\n"
                "N709:['端口号','Port'],\n"
                "N710:['ID','ID'],   \n"
                "N711:['储能逆变器50 IP','Server50 IP'],\n"
                "N712:['端口号','Port'],\n"
                "N713:['ID','ID'],\n"
                "N714:['储能逆变器51 IP','Server51 IP'],\n"
                "N715:['端口号','Port'],\n"
                "N716:['ID','ID'],\n"
                "N717:['储能逆变器52 IP','Server52 IP'],\n"
                "N718:['端口号','Port'],\n"
                "N719:['ID','ID'],\n"
                "N720:['储能逆变器53 IP','Server53 IP'],\n"
                "N721:['端口号','Port'],\n"
                "N722:['ID','ID'],\n"
                "N723:['储能逆变器54 IP','Server54 IP'],\n"
                "N724:['端口号','Port'],\n"
                "N725:['ID','ID'],\n"
                "N726:['储能逆变器55 IP','Server55 IP'],\n"
                "N727:['端口号','Port'],\n"
                "N728:['ID','ID'],\n"
                "N729:['储能逆变器56 IP','Server56 IP'],\n"
                "N730:['端口号','Port'],\n"
                "N731:['ID','ID'],\n"
                "N732:['储能逆变器57 IP','Server57 IP'],\n"
                "N733:['端口号','Port'],\n"
                "N734:['ID','ID'],\n"
                "N735:['储能逆变器58 IP','Server58 IP'],\n"
                "N736:['端口号','Port'],\n"
                "N737:['ID','ID'],\n"
                "N738:['储能逆变器59 IP','Server59 IP'],\n"
                "N739:['端口号','Port'],\n"
                "N740:['ID','ID'],\n"
                "N741:['储能逆变器60 IP','Server60 IP'],\n"
                "N742:['端口号','Port'],\n"
                "N743:['ID','ID']\n"
            "};\n"
"\n"
             //显示设置Mdobus地址设置框 nid -- text框id(实际的)，bid -- 确认按钮id(>=1)，tid -- 提示信息区id(>=1), num -- 添加的个数
            "function show_Set(nid,bid,tid,num)\n"
            "{\n"
                "var loop=0;\n"
                "var str='';\n"
                "var style=\"odd\";\n"
                "var more=0, all=0;\n"
                "var line=0;\n"
                "more=num%4;\n"
                "if(more!=0){all=num+(4-more);}\n"
                "else{all=num;}\n"
                "str+=\"<tr id='t\"+(bid+line)+\"' style='display:none'>\";\n"
                "for(var i=0; i<all; i++)\n"
                "{\n"
                    "if(i%8<4){style=\"odd\"}else{style=\"even\"}\n"
                    "if(i>=num){\n"
                        "str+=\"<td width='12%' class='td1 odd \"+style+\"'><span id='text\"+(bid+i)+\"'>No.Na</span></td><td width='9%' class='td2 \"+style+\"'><input class='txt' type='text' value='Na' disabled='true'/></td><td width='8%' class='td2 \"+style+\"'><button class='btnStyle' disabled='true' style='display:block;'></td>\";\n"
                    "}else{                      \n"
                        "str+=\"<td width='12%' class='\"+style+\"'><span id='text\"+(bid+i)+\"'>No.\"+(i<9?'0'+(i+1):(i+1))+\"</span></td><td width='9%' class='td2 \"+style+\"'><input class='txt' id='ID_0x0\"+(nid+i).toString(16).toUpperCase()+\"' value='\"+(i+1)+\"' maxlength='3' onkeyup='doRangeCheck(this,reg)' type='text'/></td><td width='%8' class='td2 \"+style+\"'><button class='btnStyle' onclick='doSubmit(this)' id='N\"+(bid+i)+\"' style='display:block;'></td>\"; \n"
                    "}   \n"
                    "if(i%4==3){\n"
                        "loop=0;\n"
                        "line++;\n"
                        "if(i!=all-1){str+=\"</tr><tr id='t\"+(bid+line)+\"' style='display:none'>\"};\n"
"\n"
                    "}\n"
                    "loop++;\n"
                "}\n"
                "str+=\"</tr>\";\n"
                "document.write(str);\n"
            "}               \n"
        "</script>\n"
    "</head>\n"
    "<body onload='Init()'>\n"
        "<!-- PCS -->\n"
        "<div id='pager' width='90%' style='padding-left:5%;float:left;'></div>  \n"
        "<table id='tbl_pcs' width='90%' border='1' bordercolor=\"#E0E0E0\" style='display:none;'>\n"
            "<script type='text/javascript'>\n"
            "show_net_pcs();\n"
            "</script>\n"
        "</table>\n"
        "<div class='tip' id='tip' style='width:90%;'><span>&nbsp;</span></div>  \n"
        "<div class='btm_blank'></div>\n"
        "<div id='trans'></div>\n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script language='javascript' type='text/javascript'>\n"
"\n"
        "function IPverify(obj)\n"
        "{\n"
            "var reg=/^(\\d{1,2}|1\\d\\d|2[0-4]\\d|25[0-5])(\\.(\\d{1,2}|1\\d\\d|2[0-4]\\d|25[0-5])){3}$/;\n"
            "var str = obj.id;\n"
            "var cutstr;\n"
            "switch(obj.id)\n"
            "{\n"
                "case 'SerIP0':case 'SerIP1':case 'SerIP2':case 'SerIP3':case 'SerIP4':case 'SerIP5':case 'SerIP6':case 'SerIP7':case 'SerIP8':case 'SerIP9':\n"
                "cutstr = str.substring(str.length-1,str.length);\n"
                "break;\n"
                "default:\n"
                "cutstr = str.substring(str.length-2,str.length);\n"
                "break;\n"
            "}\n"
            "var index = parseInt(cutstr)+50;\n"
            "if(!obj.value.match(reg))\n"
            "{\n"
                "eval('$(\\'N'+index+'\\').disabled=true;');\n"
                "obj.style.color='#F00';\n"
                "show_tip(lang.N543[language]);\n"
            "}\n"
            "else\n"
            "{\n"
                "eval('$(\\'N'+index+'\\').disabled=false;');\n"
                "obj.style.color='#000';\n"
                "show_tip('&nbsp;');\n"
            "}\n"
        "}   \n"
        "function change_color(obj)\n"
        "{\n"
            "if(current_id!=obj.id)\n"
            "{\n"
                "obj.style.background='#007b3e';\n"
                "obj.style.color='#fff';\n"
            "}\n"
        "}\n"
        "function resume_color(obj)\n"
        "{\n"
            "if(current_id!=obj.id)\n"
            "{\n"
                "obj.style.background='#aaa';\n"
                "obj.style.color='#000';\n"
            "}\n"
        "}\n"
"\n"
         //pcs
        "function choose_pcs()\n"
        "{\n"
            "var lin=0;\n"
            "if(Json.ID_0x0390==1){ \n"
                "$('tbl_net_pcs').style.display='table';$('pager').style.display='block';            \n"
                "$('tip').style.display='block';\n"
            "} else { \n"
                "$('tbl_net_pcs').style.display='none'; \n"
                "$('tip').style.display='none';\n"
            "}\n"
             //pcs 网口
            "for(var i=0; i<60; i++){\n"
                "if(i>=Json.ID_0x0350){\n"
                    "eval('$(\\'N'+(50+i)+'\\').style.background=\"#F0F0F0\";'); \n"
                "}else{  \n"
                    "if(Json.ID_0x0282==0x22){ \n"
                        "eval('$(\\'N'+(50+i)+'\\').style.background=\"#99D9EA\";');\n"
                    "}else{\n"
                        "eval('$(\\'N'+(50+i)+'\\').style.background=\"#F0F0F0\";');                           \n"
                    "} \n"
                "}\n"
            "}\n"
             //pcs 网口
            "if(Json.ID_0x0350<=10){\n"
                "if(Json.ID_0x0350==0){$('pager').style.display='none';}\n"
                "else if(Json.ID_0x0350==1){\n"
                    "$('pager').style.display='block';\n"
                    "mpager=new PagerView('pager',lang.N500[language],lang.N502[language],lang.N504[language]);\n"
                "}else{\n"
                    "$('pager').style.display='block';\n"
                    "mpager=new PagerView('pager',lang.N500[language],lang.N502[language],lang.N503[language]);\n"
                "}\n"
            "}else{\n"
                "$('pager').style.display='block';\n"
                "mpager=new PagerView('pager',lang.N500[language],lang.N501[language],lang.N503[language]);\n"
            "}   \n"
            "mpager.itemCount=Json.ID_0x0350;\n"
            "mpager.size=10;\n"
            "mpager.index=1; \n"
            "Set_PCS_For_Net(mpager.index);              \n"
            "mpager.onclick=function(index)\n"
            "{\n"
                 //获取PCS储能逆变器器配置数据
                "Set_PCS_For_Net(index);\n"
            "};\n"
             //index显示更新
            "mpager.render();          \n"
        "}\n"
         //设置串口PCS数据, 获取所有PCS 串口modbus参数
        "function Set_PCS_For_Serial()\n"
        "{\n"
            "var URL='s_027.html?0x0640&time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);           \n"
                    "for(var i=0; i<Json.ID_0x0350; i++)\n"
                    "{\n"
                        "eval('$(\\'ID_0x0'+(0x640+i).toString(16).toUpperCase()+'\\').value=Json.ID_0x0'+(0x640+i).toString(16).toUpperCase()+';');\n"
                    "}\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();  \n"
        "}\n"
         //设置网口PCS数据, 获取PCS 单页net参数
        "function Set_PCS_For_Net(index)\n"
        "{\n"
            "eval('var URL=\\'s_027.html?0x'+(0x1000+(index-1)*50).toString(16).toUpperCase()+'&time=\\'+Math.random();');\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);       \n"
                    "for(var i=0,cnt=0; i<Json.ID_0x0350; i++)\n"
                    "{\n"
                        "if(i>=(index-1)*10 && cnt < 10)\n"
                        "{\n"
                            "cnt++;\n"
                            "eval('$(\\'trSrv'+i+'\\').style.display=\\'block\\';');\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "eval('$(\\'trSrv'+i+'\\').style.display=\\'none\\';');\n"
                        "}\n"
                    "}   \n"
                    "for(var i=(index-1)*10,cnt=0; i<Json.ID_0x0350&&cnt<10; i++,cnt++)\n"
                    "{   \n"
                        "eval('$(\\'SerIP'+i+'\\').value=String(Json.ID_0x'+(0x1000+i*5).toString(16).toUpperCase()+')+\\'.\\'+String(Json.ID_0x'+(0x1000+i*5+1).toString(16).toUpperCase()+')+\\'.\\'+String(Json.ID_0x'+(0x1000+i*5+2).toString(16).toUpperCase()+')+\\'.\\'+String(Json.ID_0x'+(0x1000+i*5+3).toString(16).toUpperCase()+');');\n"
                        "eval('$(\\'PORT'+i+'\\').value=Json.ID_0x'+(0x1000+i*5+4).toString(16).toUpperCase()+';');\n"
                        "var temp;\n"
                        "temp=eval('Json.ID_0x0'+(0x640+i).toString(16).toUpperCase()+'')-1;\n"
                        "if(temp>=0)eval('$(\\'ID'+i+'\\').options[temp].selected=true;');\n"
                    "}\n"
                    "show_tip('&nbsp;');\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}       \n"
"\n"
        "function Init()\n"
        "{\n"
             //参数=0读所有设备地址
            "var URL='s_027.html?0x0000&time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);\n"
"\n"
                    "if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                    "lang_init_ex(50,109);\n"
                    "lang_init_ex(564,743);\n"
"\n"
                     //pcs net id
                    "for(var i=0;i<60;i++)\n"
                    "{\n"
                        "for(var j=0; j<247; j++)eval('$(\\'ID'+i+'\\').options.add(new Option('+(j+1)+','+j+'));');           \n"
                    "}\n"
"\n"
                     //设备选择
                    "choose_pcs();\n"
"\n"
                    "if(Json.ID_0x0282==0x11)\n"
                    "{\n"
                        "$('trans').style.zIndex=-9999;\n"
                        "for(var i=0; i<60; i++) eval('$(\\'SerIP'+i+'\\').disabled=true;');\n"
                        "for(var i=0; i<60; i++) eval('$(\\'PORT'+i+'\\').disabled=true;');\n"
                        "for(var i=0; i<60; i++) eval('$(\\'ID'+i+'\\').disabled=true;');\n"
                        "for(var i=0; i<60; i++) eval('$(\\'N'+(50+i)+'\\').disabled=true;');\n"
                    "}\n"
                    "else\n"
                    "{\n"
                        "$('trans').style.zIndex=-9999;\n"
                    "}                   \n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}\n"
        "function read_back(addr)\n"
        "{ \n"
            "var url='s_027.html?';\n"
"\n"
            "if(addr==0x1000){url=url+'0xFFFF'+'&0x1000'+'&0x1001'+'&0x1002'+'&0x1003'+'&0x1004'+'&0x0640';}\n"
            "else if(addr==0x1005){url=url+'0xFFFF'+'&0x1005'+'&0x1006'+'&0x1007'+'&0x1008'+'&0x1009'+'&0x0641';}\n"
            "else if(addr==0x100A){url=url+'0xFFFF'+'&0x100A'+'&0x100B'+'&0x100C'+'&0x100D'+'&0x100E'+'&0x0642';}\n"
            "else if(addr==0x100F){url=url+'0xFFFF'+'&0x100F'+'&0x1010'+'&0x1011'+'&0x1012'+'&0x1013'+'&0x0643';}\n"
            "else if(addr==0x1014){url=url+'0xFFFF'+'&0x1014'+'&0x1015'+'&0x1016'+'&0x1017'+'&0x1018'+'&0x0644';}\n"
            "else if(addr==0x1019){url=url+'0xFFFF'+'&0x1019'+'&0x101A'+'&0x101B'+'&0x101C'+'&0x101D'+'&0x0645';}\n"
            "else if(addr==0x101E){url=url+'0xFFFF'+'&0x101E'+'&0x101F'+'&0x1020'+'&0x1021'+'&0x1022'+'&0x0646';}\n"
            "else if(addr==0x1023){url=url+'0xFFFF'+'&0x1023'+'&0x1024'+'&0x1025'+'&0x1026'+'&0x1027'+'&0x0647';}\n"
            "else if(addr==0x1028){url=url+'0xFFFF'+'&0x1028'+'&0x1029'+'&0x102A'+'&0x102B'+'&0x102C'+'&0x0648';}\n"
            "else if(addr==0x102D){url=url+'0xFFFF'+'&0x102D'+'&0x102E'+'&0x102F'+'&0x1030'+'&0x1031'+'&0x0649';}\n"
            "else if(addr==0x1032){url=url+'0xFFFF'+'&0x1032'+'&0x1033'+'&0x1034'+'&0x1035'+'&0x1036'+'&0x064A';}\n"
            "else if(addr==0x1037){url=url+'0xFFFF'+'&0x1037'+'&0x1038'+'&0x1039'+'&0x103A'+'&0x103B'+'&0x064B';}\n"
            "else if(addr==0x103C){url=url+'0xFFFF'+'&0x103C'+'&0x103D'+'&0x103E'+'&0x103F'+'&0x1040'+'&0x064C';}\n"
            "else if(addr==0x1041){url=url+'0xFFFF'+'&0x1041'+'&0x1042'+'&0x1043'+'&0x1044'+'&0x1045'+'&0x064D';}\n"
            "else if(addr==0x1046){url=url+'0xFFFF'+'&0x1046'+'&0x1047'+'&0x1048'+'&0x1049'+'&0x104A'+'&0x064E';}\n"
            "else if(addr==0x104B){url=url+'0xFFFF'+'&0x104B'+'&0x104C'+'&0x104D'+'&0x104E'+'&0x104F'+'&0x064F';}\n"
            "else if(addr==0x1050){url=url+'0xFFFF'+'&0x1050'+'&0x1051'+'&0x1052'+'&0x1053'+'&0x1054'+'&0x0650';}\n"
            "else if(addr==0x1055){url=url+'0xFFFF'+'&0x1055'+'&0x1056'+'&0x1057'+'&0x1058'+'&0x1059'+'&0x0651';}\n"
            "else if(addr==0x105A){url=url+'0xFFFF'+'&0x105A'+'&0x105B'+'&0x105C'+'&0x105D'+'&0x105E'+'&0x0652';}\n"
            "else if(addr==0x105F){url=url+'0xFFFF'+'&0x105F'+'&0x1060'+'&0x1061'+'&0x1062'+'&0x1063'+'&0x0653';}\n"
            "else if(addr==0x1064){url=url+'0xFFFF'+'&0x1064'+'&0x1065'+'&0x1066'+'&0x1067'+'&0x1068'+'&0x0654';}\n"
            "else if(addr==0x1069){url=url+'0xFFFF'+'&0x1069'+'&0x106A'+'&0x106B'+'&0x106C'+'&0x106D'+'&0x0655';}\n"
            "else if(addr==0x106E){url=url+'0xFFFF'+'&0x106E'+'&0x106F'+'&0x1070'+'&0x1071'+'&0x1072'+'&0x0656';}\n"
            "else if(addr==0x1073){url=url+'0xFFFF'+'&0x1073'+'&0x1074'+'&0x1075'+'&0x1076'+'&0x1077'+'&0x0657';}\n"
            "else if(addr==0x1078){url=url+'0xFFFF'+'&0x1078'+'&0x1079'+'&0x107A'+'&0x107B'+'&0x107C'+'&0x0658';}\n"
            "else if(addr==0x107D){url=url+'0xFFFF'+'&0x107D'+'&0x107E'+'&0x107F'+'&0x1080'+'&0x1081'+'&0x0659';}\n"
            "else if(addr==0x1082){url=url+'0xFFFF'+'&0x1082'+'&0x1083'+'&0x1084'+'&0x1085'+'&0x1086'+'&0x065A';}\n"
            "else if(addr==0x1087){url=url+'0xFFFF'+'&0x1087'+'&0x1088'+'&0x1089'+'&0x108A'+'&0x108B'+'&0x065B';}\n"
            "else if(addr==0x108C){url=url+'0xFFFF'+'&0x108C'+'&0x108D'+'&0x108E'+'&0x108F'+'&0x1090'+'&0x065C';}\n"
            "else if(addr==0x1091){url=url+'0xFFFF'+'&0x1091'+'&0x1092'+'&0x1093'+'&0x1094'+'&0x1095'+'&0x065D';}\n"
            "else if(addr==0x1096){url=url+'0xFFFF'+'&0x1096'+'&0x1097'+'&0x1098'+'&0x1099'+'&0x109A'+'&0x065E';}\n"
            "else if(addr==0x109B){url=url+'0xFFFF'+'&0x109B'+'&0x109C'+'&0x109D'+'&0x109E'+'&0x109F'+'&0x065F';}\n"
            "else if(addr==0x10A0){url=url+'0xFFFF'+'&0x10A0'+'&0x10A1'+'&0x10A2'+'&0x10A3'+'&0x10A4'+'&0x0660';}\n"
            "else if(addr==0x10A5){url=url+'0xFFFF'+'&0x10A5'+'&0x10A6'+'&0x10A7'+'&0x10A8'+'&0x10A9'+'&0x0661';}\n"
            "else if(addr==0x10AA){url=url+'0xFFFF'+'&0x10AA'+'&0x10AB'+'&0x10AC'+'&0x10AD'+'&0x10AE'+'&0x0662';}\n"
            "else if(addr==0x10AF){url=url+'0xFFFF'+'&0x10AF'+'&0x10B0'+'&0x10B1'+'&0x10B2'+'&0x10B3'+'&0x0663';}\n"
            "else if(addr==0x10B4){url=url+'0xFFFF'+'&0x10B4'+'&0x10B5'+'&0x10B6'+'&0x10B7'+'&0x10B8'+'&0x0664';}\n"
            "else if(addr==0x10B9){url=url+'0xFFFF'+'&0x10B9'+'&0x10BA'+'&0x10BB'+'&0x10BC'+'&0x10BD'+'&0x0665';}\n"
            "else if(addr==0x10BE){url=url+'0xFFFF'+'&0x10BE'+'&0x10BF'+'&0x10C0'+'&0x10C1'+'&0x10C2'+'&0x0666';}\n"
            "else if(addr==0x10C3){url=url+'0xFFFF'+'&0x10C3'+'&0x10C4'+'&0x10C5'+'&0x10C6'+'&0x10C7'+'&0x0667';}\n"
            "else if(addr==0x10C8){url=url+'0xFFFF'+'&0x10C8'+'&0x10C9'+'&0x10CA'+'&0x10CB'+'&0x10CC'+'&0x0668';}\n"
            "else if(addr==0x10CD){url=url+'0xFFFF'+'&0x10CD'+'&0x10CE'+'&0x10CF'+'&0x10D0'+'&0x10D1'+'&0x0669';}\n"
            "else if(addr==0x10D2){url=url+'0xFFFF'+'&0x10D2'+'&0x10D3'+'&0x10D4'+'&0x10D5'+'&0x10D6'+'&0x066A';}\n"
            "else if(addr==0x10D7){url=url+'0xFFFF'+'&0x10D7'+'&0x10D8'+'&0x10D9'+'&0x10DA'+'&0x10DB'+'&0x066B';}\n"
            "else if(addr==0x10DC){url=url+'0xFFFF'+'&0x10DC'+'&0x10DD'+'&0x10DE'+'&0x10DF'+'&0x10E0'+'&0x066C';}\n"
            "else if(addr==0x10E1){url=url+'0xFFFF'+'&0x10E1'+'&0x10E2'+'&0x10E3'+'&0x10E4'+'&0x10E5'+'&0x066D';}\n"
            "else if(addr==0x10E6){url=url+'0xFFFF'+'&0x10E6'+'&0x10E7'+'&0x10E8'+'&0x10E9'+'&0x10EA'+'&0x066E';}\n"
            "else if(addr==0x10EB){url=url+'0xFFFF'+'&0x10EB'+'&0x10EC'+'&0x10ED'+'&0x10EE'+'&0x10EF'+'&0x066F';}\n"
            "else if(addr==0x10F0){url=url+'0xFFFF'+'&0x10F0'+'&0x10F1'+'&0x10F2'+'&0x10F3'+'&0x10F4'+'&0x0670';}\n"
            "else if(addr==0x10F5){url=url+'0xFFFF'+'&0x10F5'+'&0x10F6'+'&0x10F7'+'&0x10F8'+'&0x10F9'+'&0x0671';}\n"
            "else if(addr==0x10FA){url=url+'0xFFFF'+'&0x10FA'+'&0x10FB'+'&0x10FC'+'&0x10FD'+'&0x10FE'+'&0x0672';}\n"
            "else if(addr==0x10FF){url=url+'0xFFFF'+'&0x10FF'+'&0x1100'+'&0x1101'+'&0x1102'+'&0x1103'+'&0x0673';}\n"
            "else if(addr==0x1104){url=url+'0xFFFF'+'&0x1104'+'&0x1105'+'&0x1106'+'&0x1107'+'&0x1108'+'&0x0674';}\n"
            "else if(addr==0x1109){url=url+'0xFFFF'+'&0x1109'+'&0x110A'+'&0x110B'+'&0x110C'+'&0x110D'+'&0x0675';}\n"
            "else if(addr==0x110E){url=url+'0xFFFF'+'&0x110E'+'&0x110F'+'&0x1110'+'&0x1111'+'&0x1112'+'&0x0676';}\n"
            "else if(addr==0x1113){url=url+'0xFFFF'+'&0x1113'+'&0x1114'+'&0x1115'+'&0x1116'+'&0x1117'+'&0x0677';}\n"
            "else if(addr==0x1118){url=url+'0xFFFF'+'&0x1118'+'&0x1119'+'&0x111A'+'&0x111B'+'&0x111C'+'&0x0678';}\n"
            "else if(addr==0x111D){url=url+'0xFFFF'+'&0x111D'+'&0x111E'+'&0x111F'+'&0x1120'+'&0x1121'+'&0x0679';}\n"
            "else if(addr==0x1122){url=url+'0xFFFF'+'&0x1122'+'&0x1123'+'&0x1124'+'&0x1125'+'&0x1126'+'&0x067A';}\n"
            "else if(addr==0x1127){url=url+'0xFFFF'+'&0x1127'+'&0x1128'+'&0x1129'+'&0x112A'+'&0x112B'+'&0x067B';}\n"
            "else {url=url+'0xFFFF'+'&0x0'+addr.toString(16).toUpperCase();}\n"
            "url=url+'&time='+Math.random();\n"
             //alert(url);
"\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);\n"
                     //回读PCS 网口参数
                    "if(addr==0x1000 || addr==0x1005 || addr==0x100A || addr==0x100F || addr==0x1014 || addr==0x1019 || \n"
                        "addr==0x101E || addr==0x1023 || addr==0x1028 || addr==0x102D || addr==0x1032 || addr==0x1037 || addr==0x103C ||\n"
                          "addr==0x1041 || addr==0x1046 || addr==0x104B || addr==0x1050 || addr==0x1055 || addr==0x105F || addr==0x1064 ||\n"
                           "addr==0x1069 || addr==0x106E || addr==0x1073 || addr==0x1078 || addr==0x107D || addr==0x1082 || addr==0x1087 ||\n"
                            "addr==0x108C || addr==0x1091 || addr==0x1096 || addr==0x109B || addr==0x10A0 || addr==0x10A5 || addr==0x10AA ||\n"
                             "addr==0x10AF || addr==0x10B4 || addr==0x10B9 || addr==0x10BE || addr==0x10C3 || addr==0x10C8 || addr==0x10CD ||\n"
                              "addr==0x10D2 || addr==0x10D7 || addr==0x10DC || addr==0x10E1 || addr==0x10E6 || addr==0x10EB || addr==0x10F0 || \n"
                               "addr==0x10F5 || addr==0x10FA || addr==0x10FF || addr==0x1104 || addr==0x1109 || addr==0x110E || addr==0x1113 || \n"
                                "addr==0x1118 || addr==0x111D || addr==0x1122 || addr==0x1127)\n"
                    "{\n"
                        "var index = (addr-0x1000)/5;\n"
                        "eval('var ip=$(\\'SerIP'+index+'\\').value;'); \n"
                        "eval('var ip_get=String(Json.ID_0x'+addr.toString(16).toUpperCase()+')+\\'.\\'+String(Json.ID_0x'+(addr+1).toString(16).toUpperCase()+')+\\'.\\'+String(Json.ID_0x'+(addr+2).toString(16).toUpperCase()+')+\\'.\\'+String(Json.ID_0x'+(addr+3).toString(16).toUpperCase()+');');  \n"
                        "eval('var port=$(\\'PORT'+index+'\\').value;');\n"
                        "eval('var port_get=Json.ID_0x'+(addr+4).toString(16).toUpperCase()+';');\n"
                        "eval('var id=$(\\'ID'+index+'\\').selectedIndex+1;');\n"
                        "eval('var id_get=Json.ID_0x0'+(0x640+index).toString(16).toUpperCase()+';');\n"
                        "show_tip('&nbsp;');\n"
                        "if(ip!=ip_get || port!=port_get || id!=id_get){\n"
                            "eval('$(\\'SerIP'+index+'\\').value=ip_get;');\n"
                            "eval('$(\\'PORT'+index+'\\').value=port_get;');\n"
                            "eval('$(\\'ID'+index+'\\').options[Json.ID_0x0'+(0x640+index).toString(16).toUpperCase()+'-1].selected=true;');\n"
                            "setTimeout('show_tip(lang.N541[language])',500);        \n"
                        "}else{\n"
                            "setTimeout('show_tip(lang.N542[language])',500);\n"
                        "}\n"
                        "setTimeout('show_tip(\\'&nbsp;\\')',2500);\n"
                    "}\n"
                     //回读PCS modbus地址    
                    "else if(addr >= 0x640 && addr <= 0x67B)\n"
                    "{\n"
                        "var pr,fe;\n"
                        "eval('pr=$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value;');\n"
                        "eval('fe=Json.ID_0x0'+addr.toString(16).toUpperCase()+';');\n"
                        "if(pr!=fe) eval('$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value=Json.ID_0x0'+addr.toString(16).toUpperCase()+';');                      \n"
                        "show_tip('&nbsp;');\n"
                        "if(pr==fe){setTimeout('show_tip(lang.N542[language])',500);}\n"
                        "else {setTimeout('show_tip(lang.N541[language])',500);}\n"
                        "setTimeout('show_tip(\\'&nbsp;\\')',2500);\n"
                    "}\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',url,true);\n"
            "xmlhttp.send();     \n"
        "}   \n"
"\n"
        "function doSubmit(obj)\n"
        "{\n"
            "var URL='a_027.html?';\n"
"\n"
            "var readBack=0;\n"
            "switch(obj.id)\n"
            "{\n"
                 //net pcs 设置
                "case 'N50': case 'N51': case 'N52': case 'N53': case 'N54': case 'N55': case 'N56': case 'N57': case 'N58': case 'N59':\n"
                "case 'N60': case 'N61': case 'N62': case 'N63': case 'N64': case 'N65': case 'N66': case 'N67': case 'N68': case 'N69':\n"
                "case 'N70': case 'N71': case 'N72': case 'N73': case 'N74': case 'N75': case 'N76': case 'N77': case 'N78': case 'N79':\n"
                "case 'N80': case 'N81': case 'N82': case 'N83': case 'N84': case 'N85': case 'N86': case 'N87': case 'N88': case 'N89':\n"
                "case 'N90': case 'N91': case 'N92': case 'N93': case 'N94': case 'N95': case 'N96': case 'N97': case 'N98': case 'N99':\n"
                "var str = obj.id;\n"
                "var cutstr = str.substring(str.length-2,str.length);\n"
                "var index = parseInt(cutstr)-50;\n"
                "eval('var ip=$(\\'SerIP'+index+'\\').value.split(\\'.\\');');\n"
                "eval('var id=$(\\'ID'+index+'\\').selectedIndex+1;');\n"
                "eval('URL=URL+\\'0x'+(0x1000+5*index).toString(16).toUpperCase()+'=\\'+ip[0]+\\'&0x'+(0x1000+5*index+1).toString(16).toUpperCase()+'=\\'+ip[1]+\\'&0x'+(0x1000+5*index+2).toString(16).toUpperCase()+'=\\'+ip[2]+\\'&0x'+(0x1000+5*index+3).toString(16).toUpperCase()+'=\\'+ip[3]+\\'&0x'+(0x1000+5*index+4).toString(16).toUpperCase()+'=\\'+$(\\'PORT'+index+'\\').value+\\'&0x0'+(0x640+index).toString(16).toUpperCase()+'=\\'+id;');    \n"
                "eval('readBack=0x'+(0x1000+5*index).toString(16).toUpperCase()+';');\n"
                "break;\n"
                "case 'N100': case 'N101': case 'N102': case 'N103': case 'N104': case 'N105': case 'N106': case 'N107': case 'N108': case 'N109':\n"
                "var str = obj.id;\n"
                "var cutstr = str.substring(str.length-3,str.length);\n"
                "var index = parseInt(cutstr)-50;\n"
                "eval('var ip=$(\\'SerIP'+index+'\\').value.split(\\'.\\');');\n"
                "eval('var id=$(\\'ID'+index+'\\').selectedIndex+1;');\n"
                "eval('URL=URL+\\'0x'+(0x1000+5*index).toString(16).toUpperCase()+'=\\'+ip[0]+\\'&0x'+(0x1000+5*index+1).toString(16).toUpperCase()+'=\\'+ip[1]+\\'&0x'+(0x1000+5*index+2).toString(16).toUpperCase()+'=\\'+ip[2]+\\'&0x'+(0x1000+5*index+3).toString(16).toUpperCase()+'=\\'+ip[3]+\\'&0x'+(0x1000+5*index+4).toString(16).toUpperCase()+'=\\'+$(\\'PORT'+index+'\\').value+\\'&0x0'+(0x640+index).toString(16).toUpperCase()+'=\\'+id;');    \n"
                "eval('readBack=0x'+(0x1000+5*index).toString(16).toUpperCase()+';');\n"
                "break;\n"
                "default:break;\n"
            "}\n"
"\n"
            "URL=URL+'&time='+Math.random();\n"
             //alert(URL);          
"\n"
            "function success()\n"
            "{\n"
                "if((readBack >= 0x640 && readBack <= 0x67B) || (readBack >= 0x1000 && readBack <= 0x112B))\n"
                "{\n"
                    "show_tip('&nbsp;');\n"
                    "setTimeout('read_back('+readBack+')', 100);\n"
                    "setTimeout('show_tip(\\'&nbsp;\\')',2500);                    \n"
                "}       \n"
            "} \n"
"\n"
             //测试
             //success();  
"\n"
            "sendHttpReq(URL, success);\n"
        "}\n"
"\n"
        "function show_tip_ex(id, obj){eval('$(\\'tip'+id+'\\').innerHTML=obj;');}\n"
        "function doRangeCheck(obj,reg)\n"
        "{\n"
            "var range=parseInt(obj.value);\n"
            "var err, err2;          \n"
"\n"
            "if(!obj.value.match(reg)){err=2;}\n"
            "else if(range<1||range>247){err=1;}\n"
            "else{err=0;}\n"
    "\n"
             //pcs 网口    
            "if(!obj.value.match(reg)){err2=2;}\n"
            "else if(range>=100000||range==0||range==80||range==8080){err2=1;}\n"
            "else{err2=0;}\n"
"\n"
            "switch(obj.id)\n"
            "{\n"
                "case \"PORT0\": case \"PORT1\": case \"PORT2\": case \"PORT3\": case \"PORT4\": case \"PORT5\": case \"PORT6\": case \"PORT7\": case \"PORT8\": case \"PORT9\":  \n"
                "case \"PORT10\": case \"PORT11\": case \"PORT12\": case \"PORT13\": case \"PORT14\": case \"PORT15\": case \"PORT16\": case \"PORT17\": case \"PORT18\": case \"PORT19\": \n"
                "case \"PORT20\": case \"PORT21\": case \"PORT22\": case \"PORT23\": case \"PORT24\": case \"PORT25\": case \"PORT26\": case \"PORT27\": case \"PORT28\": case \"PORT29\":  \n"
                "case \"PORT30\": case \"PORT31\": case \"PORT32\": case \"PORT33\": case \"PORT34\": case \"PORT35\": case \"PORT36\": case \"PORT37\": case \"PORT38\": case \"PORT39\":  \n"
                "case \"PORT40\": case \"PORT41\": case \"PORT42\": case \"PORT43\": case \"PORT44\": case \"PORT45\": case \"PORT46\": case \"PORT47\": case \"PORT48\": case \"PORT49\":  \n"
                "case \"PORT50\": case \"PORT51\": case \"PORT52\": case \"PORT53\": case \"PORT54\": case \"PORT55\": case \"PORT56\": case \"PORT57\": case \"PORT58\": case \"PORT59\":\n"
                "if(err2==1||err2==2){\n"
                    "for(var i=0; i<Json.ID_0x0350; i++)\n"
                    "{\n"
                        "if(eval('$(\\'PORT'+i+'\\').id')==obj.id) {flg_pcs[i]=1;eval('$(\\'N'+(50+i)+'\\').disabled=true;');break;}\n"
                    "}   \n"
                "}\n"
                "if(err2==1)show_tip(lang.N544[language]);\n"
                "else if(err2==2)show_tip(lang.N543[language]);\n"
                "else{\n"
                    "for(var i=0; i<Json.ID_0x0350; i++)\n"
                    "{\n"
                        "if(eval('$(\\'PORT'+i+'\\').id')==obj.id) {flg_pcs[i]=0;eval('$(\\'N'+(50+i)+'\\').disabled=false;');break;}\n"
                    "}                           \n"
                    "var a=0;\n"
                    "for(var i=0; i<60; i++) a|=flg_pcs[i];\n"
                    "if(a==0)show_tip(\"&nbsp;\");                         \n"
                "}\n"
                "break;\n"
            "}                    \n"
        "}\n"
    "</script>\n"
"</html>\n"
};
#endif
