#ifndef _HTML_H_045_H_
#define _HTML_H_045_H_
static const char h_045[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
        "<script src='j_001.js' type='text/javascript'></script>\n"
        "<style type='text/css'>\n"
        "tr{height:27px;}\n"
        ".td1{text-align:left;padding-left:40px;}\n"
        ".td2{text-align:right;padding-right:5px;}\n"
        ".td3{text-align:right;padding-right:40px;}\n"
        ".div_tab{width:780px;height:45px;margin:0 auto;}\n"
        ".div_btn{width:80px;margin:0 auto;height:30px;text-align:right;margin-top:8px;float:left;}\n"
        ".div_text{width:80px;margin:0 auto;height:25px;text-align:right;margin-top:10px;float:left;}\n"
        ".div_span{width:40px;margin:0 auto;height:25px;font-size:16px;font-weight:bold;text-align:right;margin-top:12px;float:left;}\n"
        ".btn{width:75px;height:30px;}\n"
        ".PagerView{font-size:14px;font-family:tahoma,arial;font-weight:bold;color:#333;text-align:center;padding:8px;line-height:100%;}\n"
        ".PagerView span{color:#999;margin:0 1px;padding:3px 6px;border:1px solid #ccc;}\n"
        ".PagerView span.on{color:#fff;font-weight:bold;border:1px solid #666;background:#888;} \n"
        ".PagerView a{color:#00f;text-decoration:none;}\n"
        ".PagerView a span{color:#33f;border:1px solid #888;}\n"
        ".pager{width:780px;margin:0 auto;}\n"
        "</style>\n"
        "<script type='text/javascript'>\n"
            "var CHANNEL1_NAME=new Array('N003','N004','N005');\n"
            "var CHANNEL1_ID=new Array('ID_0x8000','ID_0x8001','ID_0x8002');\n"
            "var CHANNEL1_UNIT=new Array('W/m2','Wh/m2','Wh/m2');\n"
    "\n"
            "var CHANNEL2_NAME=new Array('N007','N008','N009');\n"
            "var CHANNEL2_ID=new Array('ID_0x8003','ID_0x8004','ID_0x8005');\n"
            "var CHANNEL2_UNIT=new Array('W/m2','Wh/m2','Wh/m2');\n"
"\n"
            "var ST_NAME=new Array('N011','N012','N013','N014','N015','N016','N017','N018');\n"
            "var ST_ID=new Array('ID_0x8006','ID_0x8007','ID_0x8008','ID_0x8009','ID_0x800A','ID_0x800B','ID_0x800C','ID_0x800D');\n"
            "var ST_UNIT=new Array('m/s','Level','℃','','hPa','℃','℃','%RH');\n"
"\n"
            "function show_SUB(TR1,TR2,TR3)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<table width='90%' border='0'>\";\n"
                "for(var i=0;i<TR1.length;i+=2)\n"
                "{\n"
                    "str+=\"<tr id='\"+TR1[i]+i+\"'>\";\n"
                        "str+=\"<td width='20%' class='td1 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR1[i]+\"'></span></td>\";\n"
                        "str+=\"<td width='20%' class='td2 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR2[i]+\"'></span></td>\";\n"
                        "str+=\"<td width='10%' class='td3 \"+(i%4?\"even\":\"odd\")+\"'>\"+TR3[i]+\"</td>\";\n"
                        "if(i+1!=TR1.length)\n"
                        "{\n"
                            "str+=\"<td width='20%' class='td1 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR1[i+1]+\"'></span></td>\";\n"
                            "str+=\"<td width='20%' class='td2 \"+(i%4?\"even\":\"odd\")+\"'><span id='\"+TR2[i+1]+\"'></span></td>\";\n"
                            "str+=\"<td width='10%' class='td3 \"+(i%4?\"even\":\"odd\")+\"'>\"+TR3[i+1]+\"</td>\";\n"
                        "}\n"
                        "else\n"
                        "{\n"
                            "str+=\"<td width='20%' class='td1 \"+(i%4?\"even\":\"odd\")+\"'></td>\";\n"
                            "str+=\"<td width='20%' class='td2 \"+(i%4?\"even\":\"odd\")+\"'></td>\";\n"
                            "str+=\"<td width='10%' class='td3 \"+(i%4?\"even\":\"odd\")+\"'></td>\";\n"
                        "}\n"
                        "\n"
                    "str+=\"</tr>\";\n"
                "}\n"
                "str+=\"</table>\";\n"
                "document.write(str);\n"
            "}\n"
        "</script>\n"
    "</head>\n"
    "<body onload='Init();'>\n"
        "<script type='text/javascript'>\n"
            "show_T('N001');\n"
        "</script>        \n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N002');\n"
            "show_SUB(CHANNEL1_NAME,CHANNEL1_ID,CHANNEL1_UNIT);\n"
        "</script>\n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>     \n"
        "<script type='text/javascript'>\n"
            "show_sT('N006');\n"
            "show_SUB(CHANNEL2_NAME,CHANNEL2_ID,CHANNEL2_UNIT);\n"
        "</script>  \n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>  \n"
        "<script type='text/javascript'>\n"
            "show_sT('N010');\n"
            "show_SUB(ST_NAME,ST_ID,ST_UNIT);\n"
        "</script>  \n"
        "<div class='line_long'></div>\n"
        "<div class='blank'></div>  \n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var $=function(o){return document.getElementById(o);};\n"
        "var language=0;\n"
        "var Json;\n"
        "var CurBms;\n"
        "var lang=\n"
        "{\n"
            "N001:['环境监测仪信息','Env-Detector Information'],\n"
"\n"
            "N002:['通道一信息','Channel1 Information'],\n"
            "N003:['日照辐射强度1','Sunshine Radiation Intensity1'],\n"
            "N004:['日辐射量1','Day Radiation1'],\n"
            "N005:['总辐射量1','All Radiation1'],\n"
"\n"
            "N006:['通道二信息','Channel2 Information'],\n"
            "N007:['日照辐射强度2','Sunshine Radiation Intensity2'],\n"
            "N008:['日辐射量2','Day Radiation2'],\n"
            "N009:['总辐射量2','All Radiation2'],\n"
"\n"
            "N010:['环境信息','Environment Information'],\n"
            "N011:['风速','Wind Speed'],\n"
            "N012:['风速等级','Wind Speed Level'],\n"
            "N013:['风向度数','Degree of Wind Direction'],\n"
            "N014:['风向位置','Wind Position'],\n"
            "N015:['大气压力','Atmospheric Pressure'],\n"
            "N016:['电池板温度','Battery Board Temperature'],\n"
            "N017:['环境温度','Environment Temperature'],\n"
            "N018:['环境湿度','Environment Humidity']\n"
        "}; \n"
"\n"
        "var WindPosition=\n"
        "{\n"
            "N0:['北','North'],\n"
            "N1:['东北偏北','North by northeast'],\n"
            "N2:['东北','Northeast'],\n"
            "N3:['东北偏东','East by Northeast'],\n"
            "N4:['东','East'],   \n"
            "N5:['东南偏东','East by Southeast'],\n"
            "N6:['东南','Southeast'],\n"
            "N7:['东南偏南','South by Southeast'],\n"
            "N8:['南','South'],\n"
            "N9:['西南偏南','South by Southwest'],\n"
            "N10:['西南','Southwest'],\n"
            "N11:['西南偏西','West by Southwest'],\n"
            "N12:['西','West'],\n"
            "N13:['西北偏西','West by Northwest'],\n"
            "N14:['西北','Northwest'],\n"
            "N15:['西北偏北','North by Northwest']\n"
        "};\n"
"\n"
        "function ajax()\n"
        "{\n"
            "var URL='s_045.html?time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);           \n"
                    "if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                    "for(var i=1;i<=18;i++)\n"
                    "{\n"
                        "eval('$(\\'N0'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N0'+(i<10?'0'+i:i)+'[language];');\n"
                    "}\n"
"\n"
                    "if(Json.ID_0x02B6 == 0)\n"
                    "{\n"
                        "$('ID_0x8000').innerHTML=(Json.ID_0x8000/10.0).toFixed(1);\n"
                        "$('ID_0x8001').innerHTML=(Json.ID_0x8001/100.0).toFixed(2);\n"
                        "$('ID_0x8002').innerHTML=(Json.ID_0x8002/10.0).toFixed(1);\n"
                        "$('ID_0x8003').innerHTML=(Json.ID_0x8003/10.0).toFixed(1);\n"
                        "$('ID_0x8004').innerHTML=(Json.ID_0x8004/100.0).toFixed(2);\n"
                        "$('ID_0x8005').innerHTML=(Json.ID_0x8005/10.0).toFixed(1);\n"
                        "$('ID_0x8006').innerHTML=(Json.ID_0x8006/10.0).toFixed(1);\n"
                        "$('ID_0x8007').innerHTML=Json.ID_0x8007;\n"
                        "$('ID_0x8008').innerHTML=(Json.ID_0x8008/10.0).toFixed(1);\n"
"\n"
                        "eval(\"$('ID_0x8009').innerHTML=WindPosition.N\"+Json.ID_0x8009+\"[\"+language+\"]\");\n"
"\n"
                        "$('ID_0x800A').innerHTML=(Json.ID_0x800A/10.0).toFixed(1);\n"
                        "$('ID_0x800B').innerHTML=(Json.ID_0x800B/10.0).toFixed(1);\n"
                        "$('ID_0x800C').innerHTML=(Json.ID_0x800C/10.0).toFixed(1);\n"
                        "$('ID_0x800D').innerHTML=(Json.ID_0x800D/10.0).toFixed(1);\n"
                    "}\n"
                    "else\n"
                    "{\n"
                        "$('ID_0x8000').innerHTML='--';\n"
                        "$('ID_0x8001').innerHTML='--';\n"
                        "$('ID_0x8002').innerHTML='--';\n"
                        "$('ID_0x8003').innerHTML='--';\n"
                        "$('ID_0x8004').innerHTML='--';\n"
                        "$('ID_0x8005').innerHTML='--';\n"
                        "$('ID_0x8006').innerHTML='--';\n"
                        "$('ID_0x8007').innerHTML='--';\n"
                        "$('ID_0x8008').innerHTML='--';\n"
                        "$('ID_0x8009').innerHTML='--';\n"
                        "$('ID_0x800A').innerHTML='--';\n"
                        "$('ID_0x800B').innerHTML='--';\n"
                        "$('ID_0x800C').innerHTML='--';\n"
                        "$('ID_0x800D').innerHTML='--';\n"
                    "}\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}        \n"
        "function Init()\n"
        "{\n"
            "ajax();\n"
            "setInterval('ajax()', 2000);\n"
        "}   \n"
    "</script>\n"
"</html>\n"
};
#endif
