#ifndef _HTML_H_041_H_
#define _HTML_H_041_H_
static const char h_041[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
"<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
"<head>\n"
"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\n"
"<style>\n"
"body {margin-top:1px; background: #e0e0e0; color: #00A2EB; font-family: Tahoma, SimSun, sans-serif; font-size:14px; font-weight: bold; }\n"
"</style>\n"
"</head>\n"
"<body onload='Init();'>\n"
 "<div id='stat' style='float: left;'>\n"
 "<span id='N001'>使用CPU：</span><span id='0x0285'>5</span>% | <span id='N002'>可用内存：</span><span id='0x0286'>34590</span>KB | <span id='N003'>在线用户数：</span><span id='0x0287'>0 / 3</span>\n"
 "</div>\n"
    "<div id='stat' style='float: right; margin-right: 20px;'>\n"
        "<span id='N004'>当前时间：</span><span id='0x0288'>2017/5/20 11:30:00</span>\n"
    "</div>\n"
"</body>\n"
"<script type='text/javascript'>\n"
 "window.history.forward(1);\n"
    "var $=function(o){return document.getElementById(o);};\n"
    "var language=0;\n"
    "var Json;\n"
    "var lang=\n"
    "{\n"
        "N001:['使用CPU：','Used CPU：'],\n"
        "N002:['可用内存：','Free Mem：'],\n"
        "N003:['在线用户数：','Online-Users：'],\n"
        "N004:['时间：','Time：']\n"
    "};\n"
"\n"
    "function Init()\n"
    "{\n"
 	"ajax();\n"
 	"setInterval('ajax()', 6000);\n"
    "}\n"
"\n"
    "function ajax()\n"
    "{\n"
        "var URL='s_041.html?time='+Math.random();\n"
        "var xmlhttp;\n"
        "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
        "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
        "xmlhttp.onreadystatechange=function()\n"
        "{\n"
            "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
            "{\n"
                "eval('Json='+xmlhttp.responseText);\n"
"\n"
     		"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
     		"for(var i=1;i<=4;i++)\n"
     		"{\n"
     			"eval('$(\\'N0'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N0'+(i<10?'0'+i:i)+'[language];');\n"
     		"}\n"
     		"$('0x0285').innerHTML = Json.ID_0x0285;\n"
     		"$('0x0286').innerHTML = Json.ID_0x0286;\n"
     		"$('0x0287').innerHTML = Json.ID_0x0287;\n"
                "$('0x0288').innerHTML = Json.ID_0x0288;\n"
            "}\n"
        "};\n"
        "xmlhttp.open('GET',URL,true);\n"
        "xmlhttp.send();\n"
    "}\n"
"</script>\n"
};
#endif
