#ifndef _HTML_H_043_H_
#define _HTML_H_043_H_
static const char h_043[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
        "<script src='j_001.js' type='text/javascript'></script>\n"
        "<style type='text/css'>\n"
        "tr{height:27px;}\n"
        ".td1{text-align:left;padding-left:40px;}\n"
        ".td2{text-align:right;padding-right:5px;}\n"
        ".td3{text-align:right;padding-right:40px;}\n"
        ".div_tab{width:780px;height:45px;margin:0 auto;}\n"
        ".div_btn{width:80px;margin:0 auto;height:30px;text-align:right;margin-top:8px;float:left;}\n"
        ".div_text{width:80px;margin:0 auto;height:25px;text-align:right;margin-top:10px;float:left;}\n"
        ".div_span{width:40px;margin:0 auto;height:25px;font-size:16px;font-weight:bold;text-align:right;margin-top:12px;float:left;}\n"
        ".btn{width:75px;height:30px;}\n"
        "</style>\n"
    "</head>\n"
    "<body onload='Init();'>\n"
        "<script type='text/javascript'>\n"
            "show_T('N01');\n"
        "</script>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N02');  \n"
        "</script>\n"
        "<table width='90%' border='0'>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N03'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x0188'></span></td>\n"
                "<td width='40%' class='td3 odd'></td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N05'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x0386'></span></td>\n"
                "<td width='40%' class='td3 even'></td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N07'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x014F'></span></td>\n"
                "<td width='40%' class='td3 odd'></td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N09'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x0004'></span></td>\n"
                "<td width='40%' class='td3 even'></td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N11'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x018B'></span></td>\n"
                "<td width='40%' class='td3 odd'></td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N13'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x0016'></span></td>\n"
                "<td width='40%' class='td3 even'>V</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N15'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x0017'></span></td>\n"
                "<td width='40%' class='td3 odd'>Hz</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N04'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x0319'></span></td>\n"
                "<td width='40%' class='td3 even'>kW</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N06'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x0321'></span></td>\n"
                "<td width='40%' class='td3 odd'>kVar</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N08'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x0005'></span></td>\n"
                "<td width='40%' class='td3 even'>kW</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N10'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x0006'></span></td>\n"
                "<td width='40%' class='td3 odd'>kVar</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N17'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x0012'></span></td>\n"
                "<td width='40%' class='td3 even'></td>\n"
            "</tr>\n"
            "<tr id='tS1' style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N12'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x0008'></span></td>\n"
                "<td width='40%' class='td3 odd'>kW</td>\n"
            "</tr>\n"
            "<tr id='tS2' style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N14'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x0009'></span></td>\n"
                "<td width='40%' class='td3 even'>kVar</td>\n"
            "</tr>\n"
            "<tr id='tS3' style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N16'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x0013'></span></td>\n"
                "<td width='40%' class='td3 odd'></td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='btm_blank'></div>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N80');  \n"
        "</script>\n"
        "<table width='90%' border='0'>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N18'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x0330'></span></td>\n"
                "<td width='40%' class='td3 odd'>min</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N19'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x0331'></span></td>\n"
                "<td width='40%' class='td3 even'>h</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N20'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x0332'></span></td>\n"
                "<td width='40%' class='td3 odd'>min</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N21'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x0333'></span></td>\n"
                "<td width='40%' class='td3 even'>h</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N22'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x0334'></span></td>\n"
                "<td width='40%' class='td3 odd'>min</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N23'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x0335'></span></td>\n"
                "<td width='40%' class='td3 even'>h</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N24'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x0336'></span></td>\n"
                "<td width='40%' class='td3 odd'>min</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N25'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x0337'></span></td>\n"
                "<td width='40%' class='td3 even'>h</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N26'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x0338'></span></td>\n"
                "<td width='40%' class='td3 odd'>min</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N27'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x0339'></span></td>\n"
                "<td width='40%' class='td3 even'>h</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N28'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x033A'></span></td>\n"
                "<td width='40%' class='td3 odd'>min</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N29'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x033B'></span></td>\n"
                "<td width='40%' class='td3 even'>h</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N30'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x033C'></span></td>\n"
                "<td width='40%' class='td3 odd'>min</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N31'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x033D'></span></td>\n"
                "<td width='40%' class='td3 even'>h</td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='btm_blank'></div>\n"
        "<script type='text/javascript'>\n"
            "show_sT('N81');  \n"
        "</script>\n"
        "<table width='90%' border='0'>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N32'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x033E'></span></td>\n"
                "<td width='40%' class='td3 odd'>kWh</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N33'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x033F'></span></td>\n"
                "<td width='40%' class='td3 even'>kWh</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N34'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x0340'></span></td>\n"
                "<td width='40%' class='td3 odd'>kWh</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N35'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x0341'></span></td>\n"
                "<td width='40%' class='td3 even'>kWh</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N36'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x0342'></span></td>\n"
                "<td width='40%' class='td3 odd'>kWh</td>\n"
            "</tr>\n"
            "<tr style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N37'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x0343'></span></td>\n"
                "<td width='40%' class='td3 even'>kWh</td>\n"
            "</tr>\n"
            "<tr id='tP1' style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 odd'><span id='N38'></span></td>\n"
                "<td width='35%' class='td2 odd'><span id='ID_0x0344'></span></td>\n"
                "<td width='40%' class='td3 odd'>kWh</td>\n"
            "</tr>\n"
            "<tr id='tP2' style='width:100%;height:24;'>\n"
                "<td width='25%' class='td1 even'><span id='N39'></span></td>\n"
                "<td width='35%' class='td2 even'><span id='ID_0x0345'></span></td>\n"
                "<td width='40%' class='td3 even'>kWh</td>\n"
            "</tr>\n"
        "</table>\n"
        "<div class='line_long'></div>\n"
        "<div class='btm_blank'></div>\n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script type='text/javascript'>\n"
        "window.history.forward(1);\n"
        "var language=0;\n"
        "var Json;\n"
        "var CurPcs;\n"
        "var lang=\n"
        "{\n"
            "N01:['详细信息','Detail Information'],\n"
            "N02:['总信息','Total information'],\n"
            "N03:['主/被动选择','Active/Passtive'],\n"
            "N04:['负载有功功率','P-Load Total'],\n"
            "N05:['启动模式','Start Mode'],\n"
            "N06:['负载无功功率','Q-Load Total'],\n"
            "N07:['系统工作状态','Work State'],\n"
            "N08:['储能逆变器有功功率','P-PCS Total'],\n"
            "N09:['电网状态','Grid Status'],\n"
            "N10:['储能逆变器无功功率','Q-PCS Total'],\n"
            "N11:['功率控制模式','Power Ctrl Mode'],\n"
            "N12:['光伏逆变器有功功率','P-PV Total'],\n"
            "N13:['微网电压','MG Voltage'],\n"
            "N14:['光伏逆变器无功功率','Q-PV Total'],\n"
            "N15:['微网频率','MG Frequency'],\n"
            "N16:['光伏逆变器在线台数','Online PV Num'],\n"
            "N17:['储能逆变器在线台数','Online PCS Num'],\n"
            "N18:['日运行时间','T-Today'],\n"
            "N19:['总运行时间','T-Total'],\n"
            "N20:['微网日运行时间','T-MG Today'],\n"
            "N21:['微网总运行时间','T-MG Total'],\n"
            "N22:['电网日运行时间','T-Grid Today'],\n"
            "N23:['电网总运行时间','T-Grid Total'],\n"
            "N24:['日充电时间','T-Charge Today'],\n"
            "N25:['总充电时间', 'T-Charge Total'],\n"
            "N26:['日放电时间','T-Discharge Today'],\n"
            "N27:['总放电时间','T-Discharge Total'],\n"
            "N28:['日负载供电时间','T-Load Today'],\n"
            "N29:['总负载供电时间','T-Load Total'],\n"
            "N30:['日故障时间','T-Fault Today'],\n"
            "N31:['总故障时间','T-Fault Total'],\n"
            "N32:['电池日充电量','E-Charge Today'],\n"
            "N33:['电池日放电量','E-Discharge Today'],\n"
            "N34:['负载日用电量','E-Load Today'],\n"
            "N35:['负载总用电量','E-Load Total'],\n"
            "N36:['电池总充电量','E-Charge Total'],\n"
            "N37:['电池总放电量','E-Discharge Total'],\n"
            "N38:['光伏日发电量','E-PV Today'],\n"
            "N39:['光伏总发电量','E-PV Total'],\n"
            "\n"
             //功率控制模式
            "N40:['固定功率','Fixed Power'],\n"
            "N41:['跟踪负载功率','Tracking Load'],\n"
            "N42:['PCC点功率控制','PPC Control'],\n"
            "N43:['防逆流','Anti Reflux'], \n"
            "N44:[' ',' '], \n"
            "N45:[' ',' '], \n"
            "N46:[' ',' '], \n"
            "N47:[' ',' '], \n"
            "N48:[' ',' '], \n"
            "N49:[' ',' '], \n"
            "N50:['削峰填谷','Peak Load Shifting'], \n"
            "N51:['交流限发','AC Limited Produce'], \n"
            "N52:['输出平滑','Ramp Rate Control'],\n"
            "N53:['调频','FR'],\n"
"\n"
             //主/被动模式
            "N67:['主动模式','Active Mode'],\n"
            "N68:['被动模式','Passive Mode'],\n"
"\n"
             //启动模式
            "N69:['电网优先','Grid First'],\n"
            "N70:['微网优先','MGrid First'],\n"
"\n"
             //电网状态
            "N71:['无电','Missed'],\n"
            "N72:['有电','Exist'],\n"
"\n"
            "N80:['运行时间','Running Time'],\n"
            "N81:['电量统计','Electric Power Statistics'],\n"
"\n"
             //系统工作状态
            "N132:['<span style=color:#000>初始状态</span>','<span style=color:#000>Initial Status</span>'],\n"
            "N133:['<span style=color:#000>自检过程</span>','<span style=color:#000>Self Checking</span>'],\n"
            "N134:['<span style=color:#007B3E>微网供电启动</span>','<span style=color:#007B3E>MG Starting</span>'],\n"
            "N135:['<span style=color:#007B3E>电网供电启动</span>','<span style=color:#007B3E>Grid Starting</span>'],\n"
            "N136:['<span style=color:#007B3E>微网供电运行</span>','<span style=color:#007B3E>MG Running</span>'],\n"
            "N137:['<span style=color:#007B3E>电网供电运行</span>','<span style=color:#007B3E>Grid Running</span>'],\n"
            "N138:['<span style=color:#F00>故障</span>','<span style=color:#F00>Fault</span>'],\n"
            "N139:['<span style=color:#007B3E>停机中</span>','<span style=color:#007B3E>Stopping</span>'],\n"
            "N140:['<span style=color:#000>停机</span>','<span style=color:#000>Stopped</span>'],\n"
            "N141:['<span style=color:#F00>紧急停机</span>','<span style=color:#F00>Emergency Stop</span>'],\n"
            "N142:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N143:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N144:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N145:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N146:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N147:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N148:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N149:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N150:['<span style=color:#007B3E>启动中</span>','<span style=color:#007B3E>Starting</span>'],\n"
            "N151:['<span style=color:#007B3E>正在同步</span>','<span style=color:#007B3E>Synchronizing</span>'],\n"
            "N152:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N153:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N154:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N155:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N156:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N157:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N158:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N159:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N160:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N161:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N162:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>'],\n"
            "N163:['<span style=color:#007B3E></span>','<span style=color:#007B3E></span>']\n"
        "};\n"
"\n"
        "var E_id=new Array(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31);\n"
        "var E_name=new Array('132','133','134','135','136','137','138','139','140','141','142','143','144','145','146','147','148','149','150','151','152','153','154','155','156','157','158','159','160','161','162','163');\n"
"\n"
        "window.onresize = function()\n"
        "{\n"
            "var bodywidth=document.body.clientWidth;\n"
             //最小宽度867=780/0.9
            "if(bodywidth<867){document.body.style.width=\"867px\";}else{document.body.style.width=\"auto\";}\n"
        "} \n"
	"function Init() \n"
        "{\n"
            "ajax();\n"
            "setInterval('ajax()', 2000);\n"
        "}\n"
        "function ajax()\n"
        "{\n"
            "var URL='s_043.html?time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);           \n"
                    "if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                    "lang_init_ex(1,39);\n"
                    "lang_init_ex(80,81);\n"
                     //工作状态
                    "$('ID_0x014F').style.fontWeight = 'bold';\n"
                    "for(var k=0;k<E_id.length;k++)if(Json.ID_0x014F==E_id[k])eval(\"$('ID_0x014F').innerHTML=lang.N\"+E_name[k]+\"[language];\");\n"
                     //主被动选择
                     //$('ID_0x0188').style.color = '#a349a4';
                    "eval(\"$('ID_0x0188').innerHTML=lang.N\"+(Json.ID_0x0188+67)+\"[language];\");\n"
                     //启动模式
                     //$('ID_0x0386').style.color = '#007b3e';
                    "eval(\"$('ID_0x0386').innerHTML=lang.N\"+(Json.ID_0x0386+69)+\"[language];\");\n"
                     //电网状态
                    "if(Json.ID_0x0004 == 0) { $('ID_0x0004').style.color = '#f00'; } \n"
                    "else { $('ID_0x0004').style.color = '#000'; }\n"
                    "eval(\"$('ID_0x0004').innerHTML=lang.N\"+(Json.ID_0x0004+71)+\"[language];\");\n"
                     //功率控制模式
                    "$('ID_0x018B').style.fontWeight = 'bold';\n"
                     //$('ID_0x018B').style.color = '#ed1c24';
                    "eval(\"$('ID_0x018B').innerHTML=lang.N\"+(Json.ID_0x018B+40)+\"[language];\");\n"
"\n"
                     //负载有功功率
                    "$('ID_0x0319').innerHTML = (Json.ID_0x0319/10.0).toFixed(1);  \n"
                     //负载无功功率
                    "$('ID_0x0321').innerHTML = (Json.ID_0x0321/10.0).toFixed(1);  \n"
                     //储能逆变器有功功率
                    "$('ID_0x0005').innerHTML = (Json.ID_0x0005/10.0).toFixed(1); \n"
                     //储能逆变器无功功率 
                    "$('ID_0x0006').innerHTML = (Json.ID_0x0006/10.0).toFixed(1);  \n"
                     //微网电压
                    "$('ID_0x0016').innerHTML = (Json.ID_0x0016/10.0).toFixed(1); \n"
                     //微网频率 
                    "$('ID_0x0017').innerHTML = (Json.ID_0x0017/100.0).toFixed(2); \n"
                     //PCS在线台数
                    "$('ID_0x0012').innerHTML = Json.ID_0x0012;                      \n"
"\n"
                    "$('ID_0x0330').innerHTML = Json.ID_0x0330;\n"
                    "$('ID_0x0331').innerHTML = Json.ID_0x0331;\n"
                    "$('ID_0x0332').innerHTML = Json.ID_0x0332;\n"
                    "$('ID_0x0333').innerHTML = Json.ID_0x0333;\n"
                    "$('ID_0x0334').innerHTML = Json.ID_0x0334;\n"
                    "$('ID_0x0335').innerHTML = Json.ID_0x0335;\n"
                    "$('ID_0x0336').innerHTML = Json.ID_0x0336;\n"
                    "$('ID_0x0337').innerHTML = Json.ID_0x0337;\n"
                    "$('ID_0x0338').innerHTML = Json.ID_0x0338;\n"
                    "$('ID_0x0339').innerHTML = Json.ID_0x0339;\n"
                    "$('ID_0x033A').innerHTML = Json.ID_0x033A;\n"
                    "$('ID_0x033B').innerHTML = Json.ID_0x033B;\n"
                    "$('ID_0x033C').innerHTML = Json.ID_0x033C;\n"
                    "$('ID_0x033D').innerHTML = Json.ID_0x033D;\n"
                    "$('ID_0x033E').innerHTML = (Json.ID_0x033E/10.0).toFixed(1);\n"
                    "$('ID_0x033F').innerHTML = (Json.ID_0x033F/10.0).toFixed(1);\n"
                    "$('ID_0x0340').innerHTML = (Json.ID_0x0340/10.0).toFixed(1);\n"
                    "$('ID_0x0341').innerHTML = Json.ID_0x0341;\n"
                    "$('ID_0x0342').innerHTML = Json.ID_0x0342;\n"
                    "$('ID_0x0343').innerHTML = Json.ID_0x0343;\n"
                    "if(Json.ID_0x0381 == 0){\n"
                        "$('tS1').style.display = 'none';\n"
                        "$('tS2').style.display = 'none';\n"
                        "$('tS3').style.display = 'none';\n"
                        "$('tP1').style.display = 'none';\n"
                        "$('tP2').style.display = 'none';\n"
                    "}else{\n"
                         //光伏逆变器有功功率
                        "$('ID_0x0008').innerHTML = (Json.ID_0x0008/10.0).toFixed(1); \n"
                         //光伏逆变器无功功率 
                        "$('ID_0x0009').innerHTML = (Json.ID_0x0009/10.0).toFixed(1); \n"
                         //PV在线台数                
                        "$('ID_0x0013').innerHTML = Json.ID_0x0013; \n"
                         //光伏日发电量 
                        "$('ID_0x0344').innerHTML = (Json.ID_0x0344/10.0).toFixed(1);\n"
                         //光伏总发电量
                        "$('ID_0x0345').innerHTML = Json.ID_0x0345;\n"
                    "}\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}   \n"
    "</script>\n"
"</html>\n"
};
#endif
