#ifndef _HTML_H_056_H_
#define _HTML_H_056_H_
static const char h_056[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
 "<head>\n"
 	"<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
 	"<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
 	"<style type='text/css'>\n"
 		"tr{height:27px;}\n"
 		".select{width:180px;_width:150px;}\n"
 		".time{width:65px;_width:100px;}\n"
 		".txt{width:70px;text-align:center;}\n"
 		".short_txt{width:50px;}\n"
 		".td_value{text-align:right;padding-right:20px;}\n"
 		".td1{padding-left:20px;padding-right:20px;text-align:left;}\n"
 		".td2{padding-left:0px;text-align:center;}\n"
 		".td3{padding-left:60px;text-align:left;}\n"
 		".td4{padding-right:5px;text-align:right;}\n"
 		".td5{padding-right:10px;text-align:right;}\n"
 		".radio{padding-left:30px;}\n"
 		".btnStyle{width:70px;height:24px;}\n"
 		".submenu{line-height:32px;padding-left:20px;width:225px;height:32px;color:#000;background-color:#eee;font-weight:normal;font-size:14px;}\n"
 	"</style>	\n"
 	"<script type='text/javascript'>\n"
 		"var $=function(o){return document.getElementById(o);};\n"
 		"function lang_init_ex(st,end){for(var i=st;i<=end;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
 		"function show_tip(obj){$('tip').innerHTML=obj;}\n"
 		"function show_T(tid)\n"
 		"{\n"
 			"var str='';\n"
 			"str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
 			"str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
 			"str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
 			"document.write(str);\n"
 		"}\n"
 		"function show_sT(tid)\n"
 		"{\n"
 			"var str='';\n"
 			"str+=\"<div class='title' style='width:90%;'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
 			"str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
 			"str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
 			"document.write(str);\n"
 		"}\n"
 		"function show_sT_ex(tid, id)\n"
 		"{\n"
 			"var str='';\n"
 			"str+=\"<div class='title' id='\"+id+\"' style='display:none;width:90%'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
 			"str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
 			"str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
 			"document.write(str);\n"
 		"}\n"
 		"function sendHttpReq(url, successFn)\n"
 		"{\n"
 				//alert(url);	
 		       "var xmlhttp;\n"
 		       "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		       "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		       "xmlhttp.onreadystatechange=function()\n"
 		       "{\n"
 		           "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 		           "{\n"
 		               "if(xmlhttp.responseText=='1'){successFn();}\n"
 		           "}\n"
 		       "};\n"
 		       "xmlhttp.open('GET',url,true);\n"
 		       "xmlhttp.send();\n"
 		"}\n"
 	"</script>\n"
 	"<script type='text/javascript'>\n"
 		"var language=0;\n"
 			//正整数+0
 		"var reg=/^(0|[1-9]\\d*)$/;\n"
 		"var Json;\n"
 		"var flg_env = [0];\n"
 		"var lang=\n"
 		"{\n"
 				//环境仪地址设置
 			"N40:['设&nbsp;&nbsp;置','Set'],\n"
 			"N41:['设&nbsp;&nbsp;置','Set'],\n"
 			"N42:['设&nbsp;&nbsp;置','Set'],\n"
 			"N43:['设&nbsp;&nbsp;置','Set'],\n"
"\n"
 			"N541:['设置失败！','Set failed!'],\n"
 			"N542:['设置成功！','Set successfully!'],\n"
 			"N543:['格式错误！','Format error!'],\n"
 			"N544:['范围错误！','Range error!'],\n"
"\n"
 			"N550:['设&nbsp;&nbsp;置','Set'],\n"
 			"N551:['设&nbsp;&nbsp;置','Set']\n"
 		"};\n"
"\n"
 			//显示设置Mdobus地址设置框 nid -- text框id(实际的)，bid -- 确认按钮id(>=1)，tid -- 提示信息区id(>=1), num -- 添加的个数
 		"function show_Set(nid,bid,tid,num)\n"
 		"{\n"
 			"var loop=0;\n"
 			"var str='';\n"
 			"var style=\"odd\";\n"
 			"var more=0, all=0;\n"
 			"var line=0;\n"
 			"more=num%4;\n"
 			"if(more!=0){all=num+(4-more);}\n"
 			"else{all=num;}\n"
 			"str+=\"<tr id='t\"+(bid+line)+\"' style='display:none'>\";\n"
 			"for(var i=0; i<all; i++)\n"
 			"{\n"
 				"if(i%8<4){style=\"odd\"}else{style=\"even\"}\n"
 				"if(i>=num){\n"
 					"str+=\"<td width='12%' class='td1 odd \"+style+\"'><span id='text\"+(bid+i)+\"'>No.Na</span></td><td width='9%' class='td2 \"+style+\"'><input class='txt' type='text' value='Na' disabled='true'/></td><td width='8%' class='td2 \"+style+\"'><button class='btnStyle' disabled='true' style='display:block;'></td>\";\n"
 				"}else{						\n"
 					"str+=\"<td width='12%' class='\"+style+\"'><span id='text\"+(bid+i)+\"'>No.\"+(i<9?'0'+(i+1):(i+1))+\"</span></td><td width='9%' class='td2 \"+style+\"'><input class='txt' id='ID_0x0\"+(nid+i).toString(16).toUpperCase()+\"' value='\"+(i+1)+\"' maxlength='3' onkeyup='doRangeCheck(this,reg)' type='text'/></td><td width='%8' class='td2 \"+style+\"'><button class='btnStyle' onclick='doSubmit(this)' id='N\"+(bid+i)+\"' style='display:block;'></td>\";	\n"
 				"}	\n"
 				"if(i%4==3){\n"
 					"loop=0;\n"
 					"line++;\n"
 					"if(i!=all-1){str+=\"</tr><tr id='t\"+(bid+line)+\"' style='display:none'>\"};\n"
"\n"
 				"}\n"
 				"loop++;\n"
 			"}\n"
 			"str+=\"</tr>\";\n"
 			"document.write(str);\n"
 		"}				\n"
 	"</script>\n"
 "</head>\n"
 "<body onload='Init()'>\n"
 	"<!-- 环境仪 -->\n"
 	"<table id='tbl_env' width='90%' border='1' bordercolor=\"#E0E0E0\" style='display:none;'>\n"
 		"<script type='text/javascript'>\n"
 		"show_Set(0x900, 40, 7, 4);\n"
 		"lang_init_ex(40,43);\n"
 		"</script>\n"
 	"</table>\n"
 	"<div class='tip' id='tip6' style='width:90%;'><span>&nbsp;</span></div>		\n"
 	"<div class='btm_blank'></div>\n"
 	"<div id='trans'></div>\n"
 	"<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
 "</body>\n"
 "<script language='javascript' type='text/javascript'>\n"
 		"\n"
 	"function change_color(obj)\n"
 	"{\n"
 		"if(current_id!=obj.id)\n"
 		"{\n"
 			"obj.style.background='#007b3e';\n"
 			"obj.style.color='#fff';\n"
 		"}\n"
 	"}\n"
 	"function resume_color(obj)\n"
 	"{\n"
 		"if(current_id!=obj.id)\n"
 		"{\n"
 			"obj.style.background='#aaa';\n"
 			"obj.style.color='#000';\n"
 		"}\n"
 	"}\n"
 	"\n"
 		//env
 	"function choose_env()\n"
 	"{\n"
 		"var lin=0;\n"
 		"if(Json.ID_0x039A==1){ $('tbl_env').style.display='table'; $('tip6').style.display='block';} else { $('tbl_env').style.display='none';  $('tip6').style.display='none';}	\n"
 		"for(var i=0; i<4; i++){\n"
 			"if(i>=1){\n"
 				"eval('$(\\'ID_0x0'+(0x900+i).toString(16).toUpperCase()+'\\').value=\\'\\';');\n"
 				"eval('$(\\'ID_0x0'+(0x900+i).toString(16).toUpperCase()+'\\').disabled=\\'true\\';');\n"
 				"eval('$(\\'N'+(40+i)+'\\').disabled=true;');\n"
 				"eval('$(\\'N'+(40+i)+'\\').style.background=\"#F0F0F0\";');\n"
 				"eval('$(\\'text'+(40+i)+'\\').innerHTML=\\'No.--\\';');\n"
 			"}else{\n"
 				"if(Json.ID_0x0282==0x22){\n"
 					"eval('$(\\'N'+(40+i)+'\\').disabled=false;');\n"
 					"eval('$(\\'N'+(40+i)+'\\').style.background=\"#99D9EA\";');\n"
 				"}else{\n"
 					"eval('$(\\'N'+(40+i)+'\\').style.background=\"#F0F0F0\";');\n"
 				"}\n"
 			"}\n"
 		"}\n"
 		"lin=1;\n"
 		"for(var j=0; j<1; j++)\n"
 		"{\n"
 			"if(j>=lin) eval('$(\\'t'+(40+j)+'\\').style.display=\\'none\\';');\n"
 			"else eval('$(\\'t'+(40+j)+'\\').style.display=\\'table\\';');\n"
 		"}\n"
 		"Set_ENV_For_Serial();\n"
 	"}\n"
 	"\n"
 		//设置串口环境监测仪数据
 	"function Set_ENV_For_Serial()\n"
 	"{\n"
 		"var URL='s_027.html?0x0900&time='+Math.random();\n"
 		"var xmlhttp;\n"
 		"if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		"xmlhttp.onreadystatechange=function()\n"
 		"{\n"
 			"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 			"{\n"
 				"eval('Json='+xmlhttp.responseText);			\n"
 				"for(var i=0; i<1; i++)\n"
 				"{\n"
 					"eval('$(\\'ID_0x0'+(0x900+i).toString(16).toUpperCase()+'\\').value=Json.ID_0x0'+(0x900+i).toString(16).toUpperCase()+';');\n"
 				"}\n"
 			"}\n"
 		"};\n"
 		"xmlhttp.open('GET',URL,true);\n"
 		"xmlhttp.send();				\n"
 	"}\n"
"\n"
 	"function Init()\n"
 	"{\n"
 			//参数=0读所有设备地址
 		"var URL='s_027.html?0x0000&time='+Math.random();\n"
 		"var xmlhttp;\n"
 		"if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		"xmlhttp.onreadystatechange=function()\n"
 		"{\n"
 			"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 			"{\n"
 				"eval('Json='+xmlhttp.responseText);\n"
"\n"
 				"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
 				"lang_init_ex(40,43);\n"
"\n"
 					//设备选择
 				"choose_env();\n"
"\n"
 				"if(Json.ID_0x0282==0x11)\n"
 				"{\n"
 					"$('trans').style.zIndex=-9999;\n"
 					"for(var i=0; i<4; i++) eval('$(\\'ID_0x0'+(0x900+i).toString(16).toUpperCase()+'\\').disabled=\\'true\\';');\n"
 					"for(var i=0; i<4; i++) eval('$(\\'N'+(40+i)+'\\').disabled=true;');\n"
 				"}\n"
 				"else\n"
 				"{\n"
 					"$('trans').style.zIndex=-9999;\n"
 				"}					\n"
 			"}\n"
 		"};\n"
 		"xmlhttp.open('GET',URL,true);\n"
 		"xmlhttp.send();\n"
 	"}\n"
 	 "function read_back(addr)\n"
 	"{ \n"
 		"var url='s_027.html?';\n"
"\n"
 		"url=url+'0xFFFF'+'&0x0'+addr.toString(16).toUpperCase();\n"
 		"url=url+'&time='+Math.random();\n"
 			//alert(url);
"\n"
 		"var xmlhttp;\n"
 		"if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		"xmlhttp.onreadystatechange=function()\n"
 		"{\n"
 			"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 			"{\n"
 				"eval('Json='+xmlhttp.responseText); \n"
 	            	//回读环境仪 modbus地址	
 	            "if(addr >= 0x900 && addr <= 0x900)\n"
 	            "{\n"
 					"var pr,fe;\n"
 					"eval('pr=$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value;');\n"
 					"eval('fe=Json.ID_0x0'+addr.toString(16).toUpperCase()+';');\n"
 					"if(pr!=fe) eval('$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value=Json.ID_0x0'+addr.toString(16).toUpperCase()+';');\n"
 		     		"show_tip_ex(6, '&nbsp;');\n"
 		    		"if(pr==fe){setTimeout('show_tip_ex(6,lang.N542[language])',500);}\n"
 		    		"else {setTimeout('show_tip_ex(6,lang.N541[language])',500);}\n"
 			           "setTimeout('show_tip_ex(6, \\'&nbsp;\\')',2500); \n"
 	            "}		\n"
 			"}\n"
 		"};\n"
 		"xmlhttp.open('GET',url,true);\n"
 		"xmlhttp.send();     \n"
        "} 	\n"
"\n"
 	"function doSubmit(obj)\n"
 	"{\n"
            "var URL='a_027.html?';\n"
"\n"
            "var readBack=0;\n"
            "switch(obj.id)\n"
            "{\n"
            		//环境仪设置
            	"case 'N40':\n"
            	"var str = obj.id;\n"
            	"var cutstr = str.substring(str.length-2,str.length);\n"
            	"var index = parseInt(cutstr)-40;\n"
             "if(flg_env[index]){return;}\n"
 			"eval('URL=URL+\\'&0x0'+(0x900+index).toString(16).toUpperCase()+'=\\'+$(\\'ID_0x0'+(0x900+index).toString(16).toUpperCase()+'\\').value;');\n"
 			"eval('readBack=0x0'+(0x900+index).toString(16).toUpperCase()+';');\n"
            	"break;   	\n"
             "default:break;\n"
            "}\n"
"\n"
            "URL=URL+'&time='+Math.random();\n"
             //alert(URL);          
"\n"
            "function success()\n"
            "{\n"
             "if(readBack >= 0x900 && readBack <= 0x900)\n"
             "{\n"
 	     		"show_tip_ex(6, '&nbsp;');\n"
 	    		"setTimeout('read_back('+readBack+')', 100);\n"
 		           "setTimeout('show_tip_ex(6, \\'&nbsp;\\')',2500);   \n"
             "} 			\n"
            "} \n"
"\n"
             //测试
             //success();  
"\n"
 		"sendHttpReq(URL, success);\n"
 	"}\n"
"\n"
 	"function show_tip_ex(id, obj){eval('$(\\'tip'+id+'\\').innerHTML=obj;');}\n"
 	"function doRangeCheck(obj,reg)\n"
 	"{\n"
 		"var range=parseInt(obj.value);\n"
 		"var err, err2;			\n"
"\n"
 		"if(!obj.value.match(reg)){err=2;}\n"
 		"else if(range<1||range>247){err=1;}\n"
 		"else{err=0;}\n"
"\n"
 			//env
 		"switch(obj.id)\n"
 		"{\n"
 			"case \"ID_0x0900\":\n"
 			"if(err==1||err==2)\n"
 			"{\n"
 				"for(var i=0; i<1; i++)\n"
 				"{\n"
 					"if(eval('$(\\'ID_0x0'+(0x900+i).toString(16).toUpperCase()+'\\').id')==obj.id) {flg_pvs[i]=1;eval('$(\\'N'+(40+i)+'\\').disabled=true;');break;}\n"
 				"}					\n"
 			"}\n"
 			"if(err==1)show_tip_ex(6,lang.N544[language]);\n"
 			"else if(err==2)show_tip_ex(6,lang.N543[language]);\n"
 			"else{\n"
 				"for(var i=0; i<Json.ID_0x0353; i++)\n"
 				"{\n"
 					"if(eval('$(\\'ID_0x0'+(0x900+i).toString(16).toUpperCase()+'\\').id')==obj.id) {flg_pvs[i]=0;eval('$(\\'N'+(40+i)+'\\').disabled=false;');break;}\n"
 				"}						\n"
 				"var a=0;\n"
 				"for(var i=0; i<1; i++) a|=flg_env[i];\n"
 				"if(a==0)show_tip_ex(6,\"&nbsp;\");						\n"
 			"}\n"
 			"break;\n"
 		"}\n"
 	"}\n"
 "</script>\n"
"</html>\n"
};
#endif
