#ifndef _HTML_H_051_H_
#define _HTML_H_051_H_
static const char h_051[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
 "<head>\n"
 	"<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
 	"<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
 	"<style type='text/css'>\n"
 		"tr{height:27px;}\n"
 		".select{width:180px;_width:150px;}\n"
 		".time{width:65px;_width:100px;}\n"
 		".txt{width:70px;text-align:center;}\n"
 		".short_txt{width:50px;}\n"
 		".td_value{text-align:right;padding-right:20px;}\n"
 		".td1{padding-left:20px;padding-right:20px;text-align:left;}\n"
 		".td2{padding-left:0px;text-align:center;}\n"
 		".td3{padding-left:60px;text-align:left;}\n"
 		".td4{padding-right:5px;text-align:right;}\n"
 		".td5{padding-right:10px;text-align:right;}\n"
 		".radio{padding-left:30px;}\n"
 		".btnStyle{width:70px;height:24px;}\n"
 		".submenu{line-height:32px;padding-left:20px;width:225px;height:32px;color:#000;background-color:#eee;font-weight:normal;font-size:14px;}\n"
 	"</style>	\n"
 	"<script type='text/javascript'>\n"
 		"var $=function(o){return document.getElementById(o);};\n"
 		"function lang_init_ex(st,end){for(var i=st;i<=end;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
 		"function show_tip(obj){$('tip').innerHTML=obj;}\n"
 		"function show_T(tid)\n"
 		"{\n"
 			"var str='';\n"
 			"str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
 			"str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
 			"str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
 			"document.write(str);\n"
 		"}\n"
 		"function show_sT(tid)\n"
 		"{\n"
 			"var str='';\n"
 			"str+=\"<div class='title' style='width:90%;'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
 			"str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
 			"str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
 			"document.write(str);\n"
 		"}\n"
 		"function show_sT_ex(tid, id)\n"
 		"{\n"
 			"var str='';\n"
 			"str+=\"<div class='title' id='\"+id+\"' style='display:none;width:90%'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
 			"str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
 			"str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
 			"document.write(str);\n"
 		"}\n"
 		"function sendHttpReq(url, successFn)\n"
 		"{\n"
 				//alert(url);	
 		       "var xmlhttp;\n"
 		       "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		       "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		       "xmlhttp.onreadystatechange=function()\n"
 		       "{\n"
 		           "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 		           "{\n"
 		               "if(xmlhttp.responseText=='1'){successFn();}\n"
 		           "}\n"
 		       "};\n"
 		       "xmlhttp.open('GET',url,true);\n"
 		       "xmlhttp.send();\n"
 		"}\n"
 	"</script>\n"
 	"<script type='text/javascript'>\n"
 		"var language=0;\n"
 			//正整数+0
 		"var reg=/^(0|[1-9]\\d*)$/;\n"
 		"var Json;\n"
 		"var flg_pv = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];\n"
 		"var lang=\n"
 		"{\n"
 	 		"N500:['一共','Total '],\n"
 	 		"N501:['页，共',' Pages, '],\n"
 	 		"N502:['页，共',' Page, '],\n"
 	 		"N503:['台',' Nums'],\n"
 	 		"N504:['台',' Num'],\n"
"\n"
 			"N541:['设置失败！','Set failed!'],\n"
 			"N542:['设置成功！','Set successfully!'],\n"
 			"N543:['格式错误！','Format error!'],\n"
 			"N544:['范围错误！','Range error!'],\n"
"\n"
 			"N550:['设&nbsp;&nbsp;置','Set'],\n"
 			"N551:['设&nbsp;&nbsp;置','Set'],\n"
"\n"
 				//PV 串口
 			"N2150:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2151:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2152:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2153:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2154:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2155:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2156:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2157:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2158:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2159:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2160:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2161:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2162:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2163:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2164:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2165:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2166:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2167:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2168:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2169:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2170:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2171:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2172:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2173:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2174:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2175:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2176:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2177:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2178:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2179:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2180:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2181:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2182:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2183:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2184:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2185:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2186:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2187:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2188:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2189:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2190:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2191:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2192:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2193:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2194:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2195:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2196:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2197:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2198:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2199:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2200:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2201:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2202:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2203:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2204:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2205:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2206:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2207:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2208:['设&nbsp;&nbsp;置','Set'],\n"
 			"N2209:['设&nbsp;&nbsp;置','Set']\n"
 		"};\n"
"\n"
 			//显示设置Mdobus地址设置框 nid -- text框id(实际的)，bid -- 确认按钮id(>=1)，tid -- 提示信息区id(>=1), num -- 添加的个数
 		"function show_Set(nid,bid,tid,num)\n"
 		"{\n"
 			"var loop=0;\n"
 			"var str='';\n"
 			"var style=\"odd\";\n"
 			"var more=0, all=0;\n"
 			"var line=0;\n"
 			"more=num%4;\n"
 			"if(more!=0){all=num+(4-more);}\n"
 			"else{all=num;}\n"
 			"str+=\"<tr id='t\"+(bid+line)+\"' style='display:none'>\";\n"
 			"for(var i=0; i<all; i++)\n"
 			"{\n"
 				"if(i%8<4){style=\"odd\"}else{style=\"even\"}\n"
 				"if(i>=num){\n"
 					"str+=\"<td width='12%' class='td1 odd \"+style+\"'><span id='text\"+(bid+i)+\"'>No.Na</span></td><td width='9%' class='td2 \"+style+\"'><input class='txt' type='text' value='Na' disabled='true'/></td><td width='8%' class='td2 \"+style+\"'><button class='btnStyle' disabled='true' style='display:block;'></td>\";\n"
 				"}else{						\n"
 					"str+=\"<td width='12%' class='\"+style+\"'><span id='text\"+(bid+i)+\"'>No.\"+(i<9?'0'+(i+1):(i+1))+\"</span></td><td width='9%' class='td2 \"+style+\"'><input class='txt' id='ID_0x0\"+(nid+i).toString(16).toUpperCase()+\"' value='\"+(i+1)+\"' maxlength='3' onkeyup='doRangeCheck(this,reg)' type='text'/></td><td width='%8' class='td2 \"+style+\"'><button class='btnStyle' onclick='doSubmit(this)' id='N\"+(bid+i)+\"' style='display:block;'></td>\";	\n"
 				"}	\n"
 				"if(i%4==3){\n"
 					"loop=0;\n"
 					"line++;\n"
 					"if(i!=all-1){str+=\"</tr><tr id='t\"+(bid+line)+\"' style='display:none'>\"};\n"
"\n"
 				"}\n"
 				"loop++;\n"
 			"}\n"
 			"str+=\"</tr>\";\n"
 			"document.write(str);\n"
 		"}				\n"
 	"</script>\n"
 "</head>\n"
 "<body onload='Init()'>\n"
 	"<!-- PV -->\n"
 	"<table id='tbl_pv' width='90%' border='1' bordercolor=\"#E0E0E0\" style='display:none;'>\n"
 		"<script type='text/javascript'>\n"
 		"show_Set(0x6B0, 2150, 2, 60);\n"
 		"</script>\n"
 	"</table>\n"
 	"<div class='tip' id='tip1' style='width:90%;'><span>&nbsp;</span></div>	\n"
 	"<div class='btm_blank'></div>\n"
 	"<div id='trans'></div>\n"
 	"<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
 "</body>\n"
 "<script language='javascript' type='text/javascript'>\n"
 	"\n"
 	"function change_color(obj)\n"
 	"{\n"
 		"if(current_id!=obj.id)\n"
 		"{\n"
 			"obj.style.background='#007b3e';\n"
 			"obj.style.color='#fff';\n"
 		"}\n"
 	"}\n"
 	"function resume_color(obj)\n"
 	"{\n"
 		"if(current_id!=obj.id)\n"
 		"{\n"
 			"obj.style.background='#aaa';\n"
 			"obj.style.color='#000';\n"
 		"}\n"
 	"}\n"
 	"\n"
 		//pv
 	"function choose_pv()\n"
 	"{\n"
 		"var lin=0;\n"
 		"if(Json.ID_0x0391==1){ \n"
 			"$('tbl_pv').style.display='table';\n"
 			"$('tip1').style.display='block';\n"
 		"} else { \n"
 			"$('tbl_pv').style.display='none';\n"
 			"$('tip1').style.display='none';\n"
 		"}\n"
"\n"
 			//pv 串口
 		"for(var i=0; i<60; i++){\n"
 			"if(i>=Json.ID_0x0351){\n"
 				"eval('$(\\'ID_0x0'+(0x6B0+i).toString(16).toUpperCase()+'\\').value=\\'\\';');\n"
 				"eval('$(\\'ID_0x0'+(0x6B0+i).toString(16).toUpperCase()+'\\').disabled=\\'true\\';');\n"
 				"eval('$(\\'N'+(2150+i)+'\\').disabled=true;');\n"
 				"eval('$(\\'N'+(2150+i)+'\\').style.background=\"#F0F0F0\";');\n"
 				"eval('$(\\'text'+(2150+i)+'\\').innerHTML=\\'No.--\\';');\n"
 			"}else{\n"
 				"if(Json.ID_0x0282==0x22){\n"
 					"eval('$(\\'N'+(2150+i)+'\\').disabled=false;');\n"
 					"eval('$(\\'N'+(2150+i)+'\\').style.background=\"#99D9EA\";');\n"
 				"}else{\n"
 					"eval('$(\\'N'+(2150+i)+'\\').style.background=\"#F0F0F0\";');\n"
 				"} \n"
 			"}\n"
 		"}\n"
 		"if(Json.ID_0x0351%4==0){lin=parseInt(Json.ID_0x0351/4);}\n"
 		"else {lin=parseInt(Json.ID_0x0351/4)+1;}\n"
 		"for(var j=0; j<15; j++)\n"
 		"{\n"
 			"if(j>=lin) eval('$(\\'t'+(2150+j)+'\\').style.display=\\'none\\';');\n"
 			"else eval('$(\\'t'+(2150+j)+'\\').style.display=\\'table\\';');\n"
 		"}\n"
 		"Set_PV_For_Serial();\n"
 	"}\n"
 	"\n"
 		//设置串口PV数据 
 	"function Set_PV_For_Serial()\n"
 	"{\n"
 		"var URL='s_027.html?0x06B0&time='+Math.random();\n"
 		"var xmlhttp;\n"
 		"if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		"xmlhttp.onreadystatechange=function()\n"
 		"{\n"
 			"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 			"{\n"
 				"eval('Json='+xmlhttp.responseText);			\n"
 				"for(var i=0; i<Json.ID_0x0351; i++)\n"
 				"{\n"
 					"eval('$(\\'ID_0x0'+(0x6B0+i).toString(16).toUpperCase()+'\\').value=Json.ID_0x0'+(0x6B0+i).toString(16).toUpperCase()+';');\n"
 				"}\n"
 			"}\n"
 		"};\n"
 		"xmlhttp.open('GET',URL,true);\n"
 		"xmlhttp.send();\n"
 	"}	\n"
"\n"
 	"function Init()\n"
 	"{\n"
 			//参数=0读所有设备地址
 		"var URL='s_027.html?0x0000&time='+Math.random();\n"
 		"var xmlhttp;\n"
 		"if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		"xmlhttp.onreadystatechange=function()\n"
 		"{\n"
 			"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 			"{\n"
 				"eval('Json='+xmlhttp.responseText);\n"
"\n"
 				"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
 				"lang_init_ex(2150,2209);\n"
"\n"
 					//设备选择
 				"choose_pv();\n"
"\n"
 				"if(Json.ID_0x0282==0x11)\n"
 				"{\n"
 					"$('trans').style.zIndex=-9999;\n"
 					"for(var i=0; i<60; i++) eval('$(\\'ID_0x0'+(0x6B0+i).toString(16).toUpperCase()+'\\').disabled=\\'true\\';');\n"
 					"for(var i=0; i<60; i++) eval('$(\\'N'+(2150+i)+'\\').disabled=true;');\n"
 				"}\n"
 				"else\n"
 				"{\n"
 					"$('trans').style.zIndex=-9999;\n"
 				"}					\n"
 			"}\n"
 		"};\n"
 		"xmlhttp.open('GET',URL,true);\n"
 		"xmlhttp.send();\n"
 	"}\n"
 	 "function read_back(addr)\n"
 	"{ \n"
 		"var url='s_027.html?';\n"
 		"\n"
 		"url=url+'0xFFFF'+'&0x0'+addr.toString(16).toUpperCase();\n"
 		"url=url+'&time='+Math.random();\n"
 			//alert(url);
"\n"
 		"var xmlhttp;\n"
 		"if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		"xmlhttp.onreadystatechange=function()\n"
 		"{\n"
 			"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 			"{\n"
 				"eval('Json='+xmlhttp.responseText);\n"
 			        //回读PV modbus地址
 			       "if(addr >= 0x6B0 && addr <= 0x6EB)\n"
 	            "{\n"
 					"var pr,fe;\n"
 					"eval('pr=$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value;');\n"
 					"eval('fe=Json.ID_0x0'+addr.toString(16).toUpperCase()+';');\n"
 					"if(pr!=fe) eval('$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value=Json.ID_0x0'+addr.toString(16).toUpperCase()+';');	            		\n"
 		     		"show_tip_ex(1, '&nbsp;');\n"
 		    		"if(pr==fe){setTimeout('show_tip_ex(1,lang.N542[language])',500);}\n"
 		    		"else {setTimeout('show_tip_ex(1,lang.N541[language])',500);}\n"
 			           "setTimeout('show_tip_ex(1, \\'&nbsp;\\')',2500);               		\n"
 	            "}\n"
 			"}\n"
 		"};\n"
 		"xmlhttp.open('GET',url,true);\n"
 		"xmlhttp.send();     \n"
        "} 	\n"
"\n"
 	"function doSubmit(obj)\n"
 	"{\n"
            "var URL='a_027.html?';\n"
"\n"
            "var readBack=0;\n"
            "switch(obj.id)\n"
            "{           		\n"
             	//serial pv设置
             "case 'N2150': case 'N2151': case 'N2152': case 'N2153': case 'N2154': case 'N2155': case 'N2156': case 'N2157': case 'N2158': case 'N2159':\n"
             "case 'N2160': case 'N2161': case 'N2162': case 'N2163': case 'N2164': case 'N2165': case 'N2166': case 'N2167': case 'N2168': case 'N2169':\n"
             "case 'N2170': case 'N2171': case 'N2172': case 'N2173': case 'N2174': case 'N2175': case 'N2176': case 'N2177': case 'N2178': case 'N2179':\n"
             "case 'N2180': case 'N2181': case 'N2182': case 'N2183': case 'N2184': case 'N2185': case 'N2186': case 'N2187': case 'N2188': case 'N2189':\n"
             "case 'N2190': case 'N2191': case 'N2192': case 'N2193': case 'N2194': case 'N2195': case 'N2196': case 'N2197': case 'N2198': case 'N2199':\n"
             "case 'N2200': case 'N2201': case 'N2202': case 'N2203': case 'N2204': case 'N2205': case 'N2206': case 'N2207': case 'N2208': case 'N2209':\n"
            	"var str = obj.id;\n"
            	"var cutstr = str.substring(str.length-4,str.length);\n"
            	"var index = parseInt(cutstr)-2150;\n"
             "if(flg_pv[index]){return;}\n"
             "eval('URL=URL+\\'&0x0'+(0x6B0+index).toString(16).toUpperCase()+'=\\'+$(\\'ID_0x0'+(0x6B0+index).toString(16).toUpperCase()+'\\').value;');\n"
             "eval('readBack=0x0'+(0x6B0+index).toString(16).toUpperCase()+';');\n"
             "break;\n"
             "default:break;\n"
            "}\n"
"\n"
            "URL=URL+'&time='+Math.random();\n"
             //alert(URL);          
"\n"
            "function success()\n"
            "{\n"
             "if(readBack >= 0x6B0 && readBack <= 0x6EB || (readBack >= 0x3000 && readBack <= 0x312B))\n"
             "{\n"
 	     		"show_tip_ex(1, '&nbsp;');\n"
 	    		"setTimeout('read_back('+readBack+')', 100);\n"
 		           "setTimeout('show_tip_ex(1, \\'&nbsp;\\')',2500);               		\n"
             "}			\n"
            "} \n"
"\n"
             //测试
             //success();  
"\n"
 		"sendHttpReq(URL, success);\n"
 	"}\n"
"\n"
 	"function show_tip_ex(id, obj){eval('$(\\'tip'+id+'\\').innerHTML=obj;');}\n"
 	"function doRangeCheck(obj,reg)\n"
 	"{\n"
 		"var range=parseInt(obj.value);\n"
 		"var err, err2;			\n"
"\n"
 		"if(!obj.value.match(reg)){err=2;}\n"
 		"else if(range<1||range>247){err=1;}\n"
 		"else{err=0;}\n"
 "\n"
 			//pv	
 		"switch(obj.id)\n"
 		"{\n"
 			"case \"ID_0x06B0\": case \"ID_0x06B1\": case \"ID_0x06B2\": case \"ID_0x06B3\": case \"ID_0x06B4\": case \"ID_0x06B5\": case \"ID_0x06B6\": case \"ID_0x06B7\": case \"ID_0x06B8\": case \"ID_0x06B9\": \n"
 			"case \"ID_0x06BA\": case \"ID_0x06BB\": case \"ID_0x06BC\": case \"ID_0x06BD\": case \"ID_0x06BE\": case \"ID_0x06BF\": case \"ID_0x06C0\": case \"ID_0x06C1\": case \"ID_0x06C2\": case \"ID_0x06C3\": \n"
 			"case \"ID_0x06C4\": case \"ID_0x06C5\": case \"ID_0x06C6\": case \"ID_0x06C7\": case \"ID_0x06C8\": case \"ID_0x06C9\": case \"ID_0x06CA\": case \"ID_0x06CB\": case \"ID_0x06CC\": case \"ID_0x06CD\": \n"
 			"case \"ID_0x06CE\": case \"ID_0x06CF\": case \"ID_0x06D0\": case \"ID_0x06D1\": case \"ID_0x06D2\": case \"ID_0x06D3\": case \"ID_0x06D4\": case \"ID_0x06D5\": case \"ID_0x06D6\": case \"ID_0x06D7\": \n"
 			"case \"ID_0x06D8\": case \"ID_0x06D9\": case \"ID_0x06DA\": case \"ID_0x06DB\": case \"ID_0x06DC\": case \"ID_0x06DD\": case \"ID_0x06DE\": case \"ID_0x06DF\": case \"ID_0x06E0\": case \"ID_0x06E1\":\n"
 			"case \"ID_0x06E2\": case \"ID_0x06E3\": case \"ID_0x06E4\": case \"ID_0x06E5\": case \"ID_0x06E6\": case \"ID_0x06E7\": case \"ID_0x06E8\": case \"ID_0x06E9\": case \"ID_0x06EA\": case \"ID_0x06EB\":\n"
 			"if(err==1||err==2)\n"
 			"{			\n"
 				"for(var i=0; i<Json.ID_0x0351; i++)\n"
 				"{\n"
 					"if(eval('$(\\'ID_0x0'+(0x6B0+i).toString(16).toUpperCase()+'\\').id')==obj.id) {flg_pv[i]=1;eval('$(\\'N'+(2150+i)+'\\').disabled=true;');break;}\n"
 				"}\n"
 			"}\n"
 			"if(err==1)show_tip_ex(1,lang.N544[language]);\n"
 			"else if(err==2)show_tip_ex(1,lang.N543[language]);\n"
 			"else{\n"
 				"for(var i=0; i<Json.ID_0x0351; i++)\n"
 				"{\n"
 					"if(eval('$(\\'ID_0x0'+(0x6B0+i).toString(16).toUpperCase()+'\\').id')==obj.id) {flg_pv[i]=0;eval('$(\\'N'+(2150+i)+'\\').disabled=false;');break;}\n"
 				"}							\n"
 				"var a=0;\n"
 				"for(var i=0; i<50; i++) a|=flg_pv[i];\n"
 				"if(a==0)show_tip_ex(1,\"&nbsp;\");						\n"
 			"}\n"
 			"break;\n"
 		"}\n"
 	"}\n"
 "</script>\n"
"</html>\n"
};
#endif
