#ifndef _HTML_H_050_H_
#define _HTML_H_050_H_
static const char h_050[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
    "<head>\n"
        "<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
        "<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
        "<style type='text/css'>\n"
            "tr{height:27px;}\n"
            ".select{width:180px;_width:150px;}\n"
            ".time{width:65px;_width:100px;}\n"
            ".txt{width:70px;text-align:center;}\n"
            ".short_txt{width:50px;}\n"
            ".td_value{text-align:right;padding-right:20px;}\n"
            ".td1{padding-left:20px;padding-right:20px;text-align:left;}\n"
            ".td2{padding-left:0px;text-align:center;}\n"
            ".td3{padding-left:60px;text-align:left;}\n"
            ".td4{padding-right:5px;text-align:right;}\n"
            ".td5{padding-right:10px;text-align:right;}\n"
            ".radio{padding-left:30px;}\n"
            ".btnStyle{width:70px;height:24px;}\n"
            ".submenu{line-height:32px;padding-left:20px;width:225px;height:32px;color:#000;background-color:#eee;font-weight:normal;font-size:14px;}\n"
        "</style>    \n"
        "<script type='text/javascript'>\n"
            "var $=function(o){return document.getElementById(o);};\n"
            "function lang_init_ex(st,end){for(var i=st;i<=end;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
            "function show_tip(obj){$('tip').innerHTML=obj;}\n"
            "function show_T(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
                "str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_sT(tid)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' style='width:90%;'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function show_sT_ex(tid, id)\n"
            "{\n"
                "var str='';\n"
                "str+=\"<div class='title' id='\"+id+\"' style='display:none;width:90%'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
                "str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
                "str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
                "document.write(str);\n"
            "}\n"
            "function sendHttpReq(url, successFn)\n"
            "{\n"
                 //alert(url);   
                "var xmlhttp;\n"
                "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
                "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
                "xmlhttp.onreadystatechange=function()\n"
                "{\n"
                    "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                    "{\n"
                        "if(xmlhttp.responseText=='1'){successFn();}\n"
                    "}\n"
                "};\n"
                "xmlhttp.open('GET',url,true);\n"
                "xmlhttp.send();\n"
            "}\n"
        "</script>\n"
        "<script type='text/javascript'>\n"
            "var language=0;\n"
             //正整数+0
            "var reg=/^(0|[1-9]\\d*)$/;\n"
            "var Json;\n"
            "var flg_pcs = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];\n"
            "var lang=\n"
            "{\n"
                 //PCS 串口
                "N1100:['设&nbsp;&nbsp;置','Set'],\n"
                "N1101:['设&nbsp;&nbsp;置','Set'],\n"
                "N1102:['设&nbsp;&nbsp;置','Set'],\n"
                "N1103:['设&nbsp;&nbsp;置','Set'],\n"
                "N1104:['设&nbsp;&nbsp;置','Set'],\n"
                "N1105:['设&nbsp;&nbsp;置','Set'],\n"
                "N1106:['设&nbsp;&nbsp;置','Set'],\n"
                "N1107:['设&nbsp;&nbsp;置','Set'],\n"
                "N1108:['设&nbsp;&nbsp;置','Set'],\n"
                "N1109:['设&nbsp;&nbsp;置','Set'],\n"
                "N1110:['设&nbsp;&nbsp;置','Set'],\n"
                "N1111:['设&nbsp;&nbsp;置','Set'],\n"
                "N1112:['设&nbsp;&nbsp;置','Set'],\n"
                "N1113:['设&nbsp;&nbsp;置','Set'],\n"
                "N1114:['设&nbsp;&nbsp;置','Set'],\n"
                "N1115:['设&nbsp;&nbsp;置','Set'],\n"
                "N1116:['设&nbsp;&nbsp;置','Set'],\n"
                "N1117:['设&nbsp;&nbsp;置','Set'],\n"
                "N1118:['设&nbsp;&nbsp;置','Set'],\n"
                "N1119:['设&nbsp;&nbsp;置','Set'],\n"
                "N1120:['设&nbsp;&nbsp;置','Set'],\n"
                "N1121:['设&nbsp;&nbsp;置','Set'],\n"
                "N1122:['设&nbsp;&nbsp;置','Set'],\n"
                "N1123:['设&nbsp;&nbsp;置','Set'],\n"
                "N1124:['设&nbsp;&nbsp;置','Set'],\n"
                "N1125:['设&nbsp;&nbsp;置','Set'],\n"
                "N1126:['设&nbsp;&nbsp;置','Set'],\n"
                "N1127:['设&nbsp;&nbsp;置','Set'],\n"
                "N1128:['设&nbsp;&nbsp;置','Set'],\n"
                "N1129:['设&nbsp;&nbsp;置','Set'],\n"
                "N1130:['设&nbsp;&nbsp;置','Set'],\n"
                "N1131:['设&nbsp;&nbsp;置','Set'],\n"
                "N1132:['设&nbsp;&nbsp;置','Set'],\n"
                "N1133:['设&nbsp;&nbsp;置','Set'],\n"
                "N1134:['设&nbsp;&nbsp;置','Set'],\n"
                "N1135:['设&nbsp;&nbsp;置','Set'],\n"
                "N1136:['设&nbsp;&nbsp;置','Set'],\n"
                "N1137:['设&nbsp;&nbsp;置','Set'],\n"
                "N1138:['设&nbsp;&nbsp;置','Set'],\n"
                "N1139:['设&nbsp;&nbsp;置','Set'],\n"
                "N1140:['设&nbsp;&nbsp;置','Set'],\n"
                "N1141:['设&nbsp;&nbsp;置','Set'],\n"
                "N1142:['设&nbsp;&nbsp;置','Set'],\n"
                "N1143:['设&nbsp;&nbsp;置','Set'],\n"
                "N1144:['设&nbsp;&nbsp;置','Set'],\n"
                "N1145:['设&nbsp;&nbsp;置','Set'],\n"
                "N1146:['设&nbsp;&nbsp;置','Set'],\n"
                "N1147:['设&nbsp;&nbsp;置','Set'],\n"
                "N1148:['设&nbsp;&nbsp;置','Set'],\n"
                "N1149:['设&nbsp;&nbsp;置','Set'],\n"
                "N1150:['设&nbsp;&nbsp;置','Set'],\n"
                "N1151:['设&nbsp;&nbsp;置','Set'],\n"
                "N1152:['设&nbsp;&nbsp;置','Set'],\n"
                "N1153:['设&nbsp;&nbsp;置','Set'],\n"
                "N1154:['设&nbsp;&nbsp;置','Set'],\n"
                "N1155:['设&nbsp;&nbsp;置','Set'],\n"
                "N1156:['设&nbsp;&nbsp;置','Set'],\n"
                "N1157:['设&nbsp;&nbsp;置','Set'],\n"
                "N1158:['设&nbsp;&nbsp;置','Set'],\n"
                "N1159:['设&nbsp;&nbsp;置','Set'],\n"
"\n"
                "N500:['一共','Total '],\n"
                "N501:['页，共',' Pages, '],\n"
                "N502:['页，共',' Page, '],\n"
                "N503:['台',' Nums'],\n"
                "N504:['台',' Num'],\n"
"\n"
                "N541:['设置失败！','Set failed!'],\n"
                "N542:['设置成功！','Set successfully!'],\n"
                "N543:['格式错误！','Format error!'],\n"
                "N544:['范围错误！','Range error!'],\n"
"\n"
                "N550:['设&nbsp;&nbsp;置','Set'],\n"
                "N551:['设&nbsp;&nbsp;置','Set']\n"
            "};\n"
"\n"
             //显示设置Mdobus地址设置框 nid -- text框id(实际的)，bid -- 确认按钮id(>=1)，tid -- 提示信息区id(>=1), num -- 添加的个数
            "function show_Set(nid,bid,tid,num)\n"
            "{\n"
                "var loop=0;\n"
                "var str='';\n"
                "var style=\"odd\";\n"
                "var more=0, all=0;\n"
                "var line=0;\n"
                "more=num%4;\n"
                "if(more!=0){all=num+(4-more);}\n"
                "else{all=num;}\n"
                "str+=\"<tr id='t\"+(bid+line)+\"' style='display:none'>\";\n"
                "for(var i=0; i<all; i++)\n"
                "{\n"
                    "if(i%8<4){style=\"odd\"}else{style=\"even\"}\n"
                    "if(i>=num){\n"
                        "str+=\"<td width='12%' class='td1 odd \"+style+\"'><span id='text\"+(bid+i)+\"'>No.Na</span></td><td width='9%' class='td2 \"+style+\"'><input class='txt' type='text' value='Na' disabled='true'/></td><td width='8%' class='td2 \"+style+\"'><button class='btnStyle' disabled='true' style='display:block;'></td>\";\n"
                    "}else{                      \n"
                        "str+=\"<td width='12%' class='\"+style+\"'><span id='text\"+(bid+i)+\"'>No.\"+(i<9?'0'+(i+1):(i+1))+\"</span></td><td width='9%' class='td2 \"+style+\"'><input class='txt' id='ID_0x0\"+(nid+i).toString(16).toUpperCase()+\"' value='\"+(i+1)+\"' maxlength='3' onkeyup='doRangeCheck(this,reg)' type='text'/></td><td width='%8' class='td2 \"+style+\"'><button class='btnStyle' onclick='doSubmit(this)' id='N\"+(bid+i)+\"' style='display:block;'></td>\"; \n"
                    "}   \n"
                    "if(i%4==3){\n"
                        "loop=0;\n"
                        "line++;\n"
                        "if(i!=all-1){str+=\"</tr><tr id='t\"+(bid+line)+\"' style='display:none'>\"};\n"
"\n"
                    "}\n"
                    "loop++;\n"
                "}\n"
                "str+=\"</tr>\";\n"
                "document.write(str);\n"
            "}               \n"
        "</script>\n"
    "</head>\n"
    "<body onload='Init()'>\n"
        "<!-- PCS -->\n"
        "<table id='tbl_pcs' width='90%' border='1' bordercolor=\"#E0E0E0\" style='display:none;'>\n"
            "<script type='text/javascript'>\n"
            "show_Set(0x640, 1100, 1, 60);\n"
            "</script>\n"
        "</table>\n"
        "<div class='tip' id='tip' style='width:90%;'><span>&nbsp;</span></div>  \n"
        "<div class='btm_blank'></div>\n"
        "<div id='trans'></div>\n"
        "<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
    "</body>\n"
    "<script language='javascript' type='text/javascript'>\n"
"\n"
        "function change_color(obj)\n"
        "{\n"
            "if(current_id!=obj.id)\n"
            "{\n"
                "obj.style.background='#007b3e';\n"
                "obj.style.color='#fff';\n"
            "}\n"
        "}\n"
        "function resume_color(obj)\n"
        "{\n"
            "if(current_id!=obj.id)\n"
            "{\n"
                "obj.style.background='#aaa';\n"
                "obj.style.color='#000';\n"
            "}\n"
        "}\n"
"\n"
         //pcs
        "function choose_pcs()\n"
        "{\n"
            "var lin=0;\n"
            "if(Json.ID_0x0390==1){ \n"
                "$('tbl_pcs').style.display='table';\n"
                "$('tip').style.display='block';\n"
            "} else { \n"
                "$('tbl_pcs').style.display='none';\n"
                "$('tip').style.display='none';\n"
            "}\n"
             //pcs 串口
            "for(var i=0; i<60; i++){\n"
                "if(i>=Json.ID_0x0350){\n"
                    "eval('$(\\'ID_0x0'+(0x640+i).toString(16).toUpperCase()+'\\').value=\\'\\';');\n"
                    "eval('$(\\'ID_0x0'+(0x640+i).toString(16).toUpperCase()+'\\').disabled=true;');\n"
                    "eval('$(\\'N'+(1100+i)+'\\').disabled=true;');\n"
                "}else{  \n"
                    "if(Json.ID_0x0282==0x22){ \n"
                        "eval('$(\\'N'+(1100+i)+'\\').disabled=false;');\n"
                        "eval('$(\\'N'+(1100+i)+'\\').style.background=\"#99D9EA\";');\n"
                    "}else{\n"
                        "eval('$(\\'N'+(1100+i)+'\\').style.background=\"#F0F0F0\";');                           \n"
                    "} \n"
                "}\n"
            "}\n"
"\n"
            "if(Json.ID_0x0350%4==0){lin=parseInt(Json.ID_0x0350/4);}\n"
            "else {lin=parseInt(Json.ID_0x0350/4)+1;}\n"
            "for(var j=0; j<15; j++)\n"
            "{\n"
                "if(j>=lin) eval('$(\\'t'+(1100+j)+'\\').style.display=\\'none\\';');\n"
                "else eval('$(\\'t'+(1100+j)+'\\').style.display=\\'table\\';');\n"
            "}\n"
            "Set_PCS_For_Serial();\n"
        "}\n"
         //设置串口PCS数据, 获取所有PCS 串口modbus参数
        "function Set_PCS_For_Serial()\n"
        "{\n"
            "var URL='s_027.html?0x0640&time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);           \n"
                    "for(var i=0; i<Json.ID_0x0350; i++)\n"
                    "{\n"
                        "eval('$(\\'ID_0x0'+(0x640+i).toString(16).toUpperCase()+'\\').value=Json.ID_0x0'+(0x640+i).toString(16).toUpperCase()+';');\n"
                    "}\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();   \n"
             //alert(URL);       
        "}\n"
"\n"
        "function Init()\n"
        "{\n"
             //参数=0读所有设备地址
            "var URL='s_027.html?0x0000&time='+Math.random();\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);\n"
"\n"
                    "if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
                    "lang_init_ex(1100,1159);\n"
"\n"
                     //设备选择
                    "choose_pcs();\n"
"\n"
                    "if(Json.ID_0x0282==0x11)\n"
                    "{\n"
                        "$('trans').style.zIndex=-9999;\n"
                        "for(var i=0; i< 60; i++) $('N'+(1100+i)+'').disabled=true;\n"
                        "for(var i=0; i< 60; i++) $('ID_0x0'+(0x640+i).toString(16).toUpperCase()+'').disabled=true;\n"
                    "}\n"
                    "else\n"
                    "{\n"
                        "$('trans').style.zIndex=-9999;\n"
                    "}                   \n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',URL,true);\n"
            "xmlhttp.send();\n"
        "}\n"
        "function read_back(addr)\n"
        "{ \n"
            "var url='s_027.html?';\n"
"\n"
            "url=url+'0xFFFF'+'&0x0'+addr.toString(16).toUpperCase();\n"
            "url=url+'&time='+Math.random();\n"
             //alert(url);
"\n"
            "var xmlhttp;\n"
            "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
            "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
            "xmlhttp.onreadystatechange=function()\n"
            "{\n"
                "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
                "{\n"
                    "eval('Json='+xmlhttp.responseText);\n"
                     //回读PCS modbus地址    
                    "if(addr >= 0x640 && addr <= 0x67B)\n"
                    "{\n"
                        "var pr,fe;\n"
                        "eval('pr=$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value;');\n"
                        "eval('fe=Json.ID_0x0'+addr.toString(16).toUpperCase()+';');\n"
                        "if(pr!=fe) eval('$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value=Json.ID_0x0'+addr.toString(16).toUpperCase()+';');                      \n"
                        "show_tip('&nbsp;');\n"
                        "if(pr==fe){setTimeout('show_tip(lang.N542[language])',500);}\n"
                        "else {setTimeout('show_tip(lang.N541[language])',500);}\n"
                        "setTimeout('show_tip(\\'&nbsp;\\')',2500);\n"
                    "}\n"
                "}\n"
            "};\n"
            "xmlhttp.open('GET',url,true);\n"
            "xmlhttp.send();     \n"
        "}   \n"
"\n"
        "function doSubmit(obj)\n"
        "{\n"
            "var URL='a_027.html?';\n"
"\n"
            "var readBack=0;\n"
            "switch(obj.id)\n"
            "{                 \n"
                 //serial pcs 设置
                "case 'N1100': case 'N1101': case 'N1102': case 'N1103': case 'N1104': case 'N1105': case 'N1106': case 'N1107': case 'N1108': case 'N1109':\n"
                "case 'N1110': case 'N1111': case 'N1112': case 'N1113': case 'N1114': case 'N1115': case 'N1116': case 'N1117': case 'N1118': case 'N1119':\n"
                "case 'N1120': case 'N1121': case 'N1122': case 'N1123': case 'N1124': case 'N1125': case 'N1126': case 'N1127': case 'N1128': case 'N1129':\n"
                "case 'N1130': case 'N1131': case 'N1132': case 'N1133': case 'N1134': case 'N1135': case 'N1136': case 'N1137': case 'N1138': case 'N1139':\n"
                "case 'N1140': case 'N1141': case 'N1142': case 'N1143': case 'N1144': case 'N1145': case 'N1146': case 'N1147': case 'N1148': case 'N1149':\n"
                "case 'N1150': case 'N1151': case 'N1152': case 'N1153': case 'N1154': case 'N1155': case 'N1156': case 'N1157': case 'N1158': case 'N1159':\n"
                "var str = obj.id;\n"
                "var cutstr = str.substring(str.length-4,str.length);\n"
                "var index = parseInt(cutstr)-1100;\n"
                "if(flg_pcs[index]){return;}\n"
                "eval('URL=URL+\\'&0x0'+(0x640+index).toString(16).toUpperCase()+'=\\'+$(\\'ID_0x0'+(0x640+index).toString(16).toUpperCase()+'\\').value;');\n"
                "eval('readBack=0x0'+(0x640+index).toString(16).toUpperCase()+';');\n"
                "break;  \n"
                "default:break;\n"
            "}\n"
"\n"
            "URL=URL+'&time='+Math.random();\n"
             //alert(URL);          
"\n"
            "function success()\n"
            "{\n"
                "if((readBack >= 0x640 && readBack <= 0x67B) || (readBack >= 0x1000 && readBack <= 0x112B))\n"
                "{\n"
                    "show_tip('&nbsp;');\n"
                    "setTimeout('read_back('+readBack+')', 100);\n"
                    "setTimeout('show_tip(\\'&nbsp;\\')',2500);                    \n"
                "}       \n"
            "} \n"
"\n"
             //测试
             //success();  
"\n"
            "sendHttpReq(URL, success);\n"
        "}\n"
"\n"
        "function show_tip_ex(id, obj){eval('$(\\'tip'+id+'\\').innerHTML=obj;');}\n"
        "function doRangeCheck(obj,reg)\n"
        "{\n"
            "var range=parseInt(obj.value);\n"
            "var err, err2;          \n"
"\n"
            "if(!obj.value.match(reg)){err=2;}\n"
            "else if(range<1||range>247){err=1;}\n"
            "else{err=0;}\n"
          "\n"
             //pcs 串口                    
            "switch(obj.id)\n"
            "{\n"
                "case \"ID_0x0640\": case \"ID_0x0641\": case \"ID_0x0642\": case \"ID_0x0643\": case \"ID_0x0644\": case \"ID_0x0645\": case \"ID_0x0646\": case \"ID_0x0647\": case \"ID_0x0648\": case \"ID_0x0649\": \n"
                "case \"ID_0x064A\": case \"ID_0x064B\": case \"ID_0x064C\": case \"ID_0x064D\": case \"ID_0x064E\": case \"ID_0x064F\": case \"ID_0x0650\": case \"ID_0x0651\": case \"ID_0x0652\": case \"ID_0x0653\": \n"
                "case \"ID_0x0654\": case \"ID_0x0655\": case \"ID_0x0656\": case \"ID_0x0657\": case \"ID_0x0658\": case \"ID_0x0659\": case \"ID_0x065A\": case \"ID_0x065B\": case \"ID_0x065C\": case \"ID_0x065D\": \n"
                "case \"ID_0x065E\": case \"ID_0x065F\": case \"ID_0x0660\": case \"ID_0x0661\": case \"ID_0x0662\": case \"ID_0x0663\": case \"ID_0x0664\": case \"ID_0x0665\": case \"ID_0x0666\": case \"ID_0x0667\": \n"
                "case \"ID_0x0668\": case \"ID_0x0669\": case \"ID_0x066A\": case \"ID_0x066B\": case \"ID_0x066C\": case \"ID_0x066D\": case \"ID_0x066E\": case \"ID_0x066F\": case \"ID_0x0670\": case \"ID_0x0671\": \n"
                "case \"ID_0x0672\": case \"ID_0x0673\": case \"ID_0x0674\": case \"ID_0x0675\": case \"ID_0x0676\": case \"ID_0x0677\": case \"ID_0x0678\": case \"ID_0x0679\": case \"ID_0x067A\": case \"ID_0x067B\":\n"
                "if(err==1||err==2){ \n"
                    "for(var i=0; i<Json.ID_0x0350; i++)\n"
                    "{\n"
                        "if(eval('$(\\'ID_0x0'+(0x640+i).toString(16).toUpperCase()+'\\').id')==obj.id) {flg_pcs[i]=1;eval('$(\\'N'+(1100+i)+'\\').disabled=true;');break;}\n"
                    "}                       \n"
                "}\n"
                "if(err==1) show_tip(lang.N544[language]);                       \n"
                "else if(err==2) show_tip(lang.N543[language]);                      \n"
                "else{\n"
                    "for(var i=0; i<Json.ID_0x0350; i++)\n"
                    "{\n"
                        "if(eval('$(\\'ID_0x0'+(0x640+i).toString(16).toUpperCase()+'\\').id')==obj.id) {flg_pcs[i]=0;eval('$(\\'N'+(1100+i)+'\\').disabled=false;');break;}\n"
                    "}                           \n"
                    "var a=0;\n"
                    "for(var i=0; i<60; i++) a|=flg_pcs[i];\n"
                    "if(a==0)show_tip(\"&nbsp;\");\n"
                "}\n"
                "break;\n"
            "}\n"
        "}\n"
    "</script>\n"
"</html>\n"
};
#endif
