#ifndef _HTML_H_055_H_
#define _HTML_H_055_H_
static const char h_055[] = {
"HTTP/1.1 200 OK\r\nContent-Type:text/html\r\nAccept-Ranges:bytes\r\n\r\n"
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>\n"
"<html xmlns='http://www.w3.org/1999/xhtml'>\n"
 "<head>\n"
 	"<meta http-equiv='Content-Type' content='text/html; charset=GB2312'/>\n"
 	"<link type='text/css' href='c_000.css' rel='stylesheet'/>\n"
 	"<style type='text/css'>\n"
 		"tr{height:27px;}\n"
 		".select{width:180px;_width:150px;}\n"
 		".time{width:65px;_width:100px;}\n"
 		".txt{width:70px;text-align:center;}\n"
 		".short_txt{width:50px;}\n"
 		".td_value{text-align:right;padding-right:20px;}\n"
 		".td1{padding-left:20px;padding-right:20px;text-align:left;}\n"
 		".td2{padding-left:0px;text-align:center;}\n"
 		".td3{padding-left:60px;text-align:left;}\n"
 		".td4{padding-right:5px;text-align:right;}\n"
 		".td5{padding-right:10px;text-align:right;}\n"
 		".radio{padding-left:30px;}\n"
 		".btnStyle{width:70px;height:24px;}\n"
 		".submenu{line-height:32px;padding-left:20px;width:225px;height:32px;color:#000;background-color:#eee;font-weight:normal;font-size:14px;}\n"
 	"</style>	\n"
 	"<script type='text/javascript'>\n"
 		"var $=function(o){return document.getElementById(o);};\n"
 		"function lang_init_ex(st,end){for(var i=st;i<=end;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
 		"function show_tip(obj){$('tip').innerHTML=obj;}\n"
 		"function show_T(tid)\n"
 		"{\n"
 			"var str='';\n"
 			"str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
 			"str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
 			"str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
 			"document.write(str);\n"
 		"}\n"
 		"function show_sT(tid)\n"
 		"{\n"
 			"var str='';\n"
 			"str+=\"<div class='title' style='width:90%;'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
 			"str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
 			"str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
 			"document.write(str);\n"
 		"}\n"
 		"function show_sT_ex(tid, id)\n"
 		"{\n"
 			"var str='';\n"
 			"str+=\"<div class='title' id='\"+id+\"' style='display:none;width:90%'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
 			"str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
 			"str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
 			"document.write(str);\n"
 		"}\n"
 		"function sendHttpReq(url, successFn)\n"
 		"{\n"
 				//alert(url);	
 		       "var xmlhttp;\n"
 		       "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		       "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		       "xmlhttp.onreadystatechange=function()\n"
 		       "{\n"
 		           "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 		           "{\n"
 		               "if(xmlhttp.responseText=='1'){successFn();}\n"
 		           "}\n"
 		       "};\n"
 		       "xmlhttp.open('GET',url,true);\n"
 		       "xmlhttp.send();\n"
 		"}	\n"
 	"</script>\n"
 	"<script type='text/javascript'>\n"
 		"var language=0;\n"
 			//正整数+0
 		"var reg=/^(0|[1-9]\\d*)$/;\n"
 		"var Json;\n"
 		"var flg_pvs = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];\n"
 		"var lang=\n"
 		"{\n"
 				//PVS, bnt ID 从500开始
 			"N6350:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6351:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6352:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6353:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6354:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6355:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6356:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6357:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6358:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6359:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6360:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6361:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6362:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6363:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6364:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6365:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6366:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6367:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6368:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6369:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6370:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6371:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6372:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6373:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6374:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6375:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6376:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6377:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6378:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6379:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6380:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6381:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6382:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6383:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6384:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6385:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6386:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6387:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6388:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6389:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6390:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6391:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6392:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6393:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6394:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6395:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6396:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6397:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6398:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6399:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6400:['设&nbsp;&nbsp;置','Set'],\n"
 			"N6401:['设&nbsp;&nbsp;置','Set'],\n"
"\n"
 	 		"N500:['一共','Total '],\n"
 	 		"N501:['页，共',' Pages, '],\n"
 	 		"N502:['页，共',' Page, '],\n"
 	 		"N503:['台',' Nums'],\n"
 	 		"N504:['台',' Num'],\n"
"\n"
 			"N541:['设置失败！','Set failed!'],\n"
 			"N542:['设置成功！','Set successfully!'],\n"
 			"N543:['格式错误！','Format error!'],\n"
 			"N544:['范围错误！','Range error!'],\n"
"\n"
 			"N550:['设&nbsp;&nbsp;置','Set'],\n"
 			"N551:['设&nbsp;&nbsp;置','Set']\n"
 		"};\n"
"\n"
 			//显示设置Mdobus地址设置框 nid -- text框id(实际的)，bid -- 确认按钮id(>=1)，tid -- 提示信息区id(>=1), num -- 添加的个数
 		"function show_Set(nid,bid,tid,num)\n"
 		"{\n"
 			"var loop=0;\n"
 			"var str='';\n"
 			"var style=\"odd\";\n"
 			"var more=0, all=0;\n"
 			"var line=0;\n"
 			"more=num%4;\n"
 			"if(more!=0){all=num+(4-more);}\n"
 			"else{all=num;}\n"
 			"str+=\"<tr id='t\"+(bid+line)+\"' style='display:none'>\";\n"
 			"for(var i=0; i<all; i++)\n"
 			"{\n"
 				"if(i%8<4){style=\"odd\"}else{style=\"even\"}\n"
 				"if(i>=num){\n"
 					"str+=\"<td width='12%' class='td1 odd \"+style+\"'><span id='text\"+(bid+i)+\"'>No.Na</span></td><td width='9%' class='td2 \"+style+\"'><input class='txt' type='text' value='Na' disabled='true'/></td><td width='8%' class='td2 \"+style+\"'><button class='btnStyle' disabled='true' style='display:block;'></td>\";\n"
 				"}else{						\n"
 					"str+=\"<td width='12%' class='\"+style+\"'><span id='text\"+(bid+i)+\"'>No.\"+(i<9?'0'+(i+1):(i+1))+\"</span></td><td width='9%' class='td2 \"+style+\"'><input class='txt' id='ID_0x0\"+(nid+i).toString(16).toUpperCase()+\"' value='\"+(i+1)+\"' maxlength='3' onkeyup='doRangeCheck(this,reg)' type='text'/></td><td width='%8' class='td2 \"+style+\"'><button class='btnStyle' onclick='doSubmit(this)' id='N\"+(bid+i)+\"' style='display:block;'></td>\";	\n"
 				"}	\n"
 				"if(i%4==3){\n"
 					"loop=0;\n"
 					"line++;\n"
 					"if(i!=all-1){str+=\"</tr><tr id='t\"+(bid+line)+\"' style='display:none'>\"};\n"
"\n"
 				"}\n"
 				"loop++;\n"
 			"}\n"
 			"str+=\"</tr>\";\n"
 			"document.write(str);\n"
 		"}				\n"
 	"</script>\n"
 "</head>\n"
 "<body onload='Init()'>\n"
 	"<!-- 汇流箱 -->\n"
 	"<table id='tbl_pvs' width='90%' border='1' bordercolor=\"#E0E0E0\" style='display:none;'>\n"
 		"<script type='text/javascript'>\n"
 		"show_Set(0x760, 6350, 6, 52);\n"
 		"lang_init_ex(6350,6401);\n"
 		"</script>\n"
 	"</table>\n"
 	"<div class='tip' id='tip5' style='width:90%;'><span>&nbsp;</span></div>	\n"
 	"<div class='btm_blank'></div>\n"
 	"<div id='trans'></div>\n"
 	"<!--[if IE 6]><script type='text/javascript'>document.execCommand('BackgroundImageCache',false,true);</script><![endif]-->\n"
 "</body>\n"
 "<script language='javascript' type='text/javascript'>\n"
"\n"
 	"function change_color(obj)\n"
 	"{\n"
 		"if(current_id!=obj.id)\n"
 		"{\n"
 			"obj.style.background='#007b3e';\n"
 			"obj.style.color='#fff';\n"
 		"}\n"
 	"}\n"
 	"function resume_color(obj)\n"
 	"{\n"
 		"if(current_id!=obj.id)\n"
 		"{\n"
 			"obj.style.background='#aaa';\n"
 			"obj.style.color='#000';\n"
 		"}\n"
 	"}\n"
 	"\n"
 		//pvs
 	"function choose_pvs()\n"
 	"{\n"
 		"var lin=0;\n"
 		"if(Json.ID_0x0393==1){ $('tbl_pvs').style.display='table'; $('tip5').style.display='block';} else { $('tbl_pvs').style.display='none';  $('tip5').style.display='none';}	\n"
 			//pvs
 		"for(var i=0; i<52; i++){\n"
 			"if(i>=Json.ID_0x0353){\n"
 				"eval('$(\\'ID_0x0'+(0x760+i).toString(16).toUpperCase()+'\\').value=\\'\\';');\n"
 				"eval('$(\\'ID_0x0'+(0x760+i).toString(16).toUpperCase()+'\\').disabled=\\'true\\';');\n"
 				"eval('$(\\'N'+(6350+i)+'\\').disabled=true;');\n"
 				"eval('$(\\'N'+(6350+i)+'\\').style.background=\"#F0F0F0\";');\n"
 				"eval('$(\\'text'+(6350+i)+'\\').innerHTML=\\'No.--\\';');\n"
 			"}else{\n"
 				"if(Json.ID_0x0282==0x22){\n"
 					"eval('$(\\'N'+(6350+i)+'\\').disabled=false;');\n"
 					"eval('$(\\'N'+(6350+i)+'\\').style.background=\"#99D9EA\";');\n"
 				"}else{\n"
 					"eval('$(\\'N'+(6350+i)+'\\').style.background=\"#F0F0F0\";');\n"
 				"}\n"
 			"}\n"
 		"}\n"
 		"if(Json.ID_0x0353%4==0){lin=parseInt(Json.ID_0x0353/4);}\n"
 		"else {lin=parseInt(Json.ID_0x0353/4)+1;}\n"
 		"for(var j=0; j<13; j++)\n"
 		"{\n"
 			"if(j>=lin) eval('$(\\'t'+(6350+j)+'\\').style.display=\\'none\\';');\n"
 			"else eval('$(\\'t'+(6350+j)+'\\').style.display=\\'table\\';');\n"
 		"}	\n"
 		"Set_PVS_For_Serial();	\n"
 	"}\n"
"\n"
 		//设置串口汇流箱数据
 	"function Set_PVS_For_Serial()\n"
 	"{\n"
 		"var URL='s_027.html?0x0760&time='+Math.random();\n"
 		"var xmlhttp;\n"
 		"if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		"xmlhttp.onreadystatechange=function()\n"
 		"{\n"
 			"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 			"{\n"
 				"eval('Json='+xmlhttp.responseText);			\n"
 				"for(var i=0; i<Json.ID_0x0353; i++)\n"
 				"{\n"
 					"eval('$(\\'ID_0x0'+(0x760+i).toString(16).toUpperCase()+'\\').value=Json.ID_0x0'+(0x760+i).toString(16).toUpperCase()+';');\n"
 				"}\n"
 			"}\n"
 		"};\n"
 		"xmlhttp.open('GET',URL,true);\n"
 		"xmlhttp.send();	\n"
 	"}	\n"
"\n"
 	"function Init()\n"
 	"{\n"
 			//参数=0读所有设备地址
 		"var URL='s_027.html?0x0000&time='+Math.random();\n"
 		"var xmlhttp;\n"
 		"if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		"xmlhttp.onreadystatechange=function()\n"
 		"{\n"
 			"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 			"{\n"
 				"eval('Json='+xmlhttp.responseText);\n"
"\n"
 				"if(Json.ID_0x0301==0x55)language=0;else language=1;\n"
 				"lang_init_ex(6350,6401);\n"
"\n"
 					//设备选择
 				"choose_pvs();\n"
"\n"
 				"if(Json.ID_0x0282==0x11)\n"
 				"{\n"
 					"$('trans').style.zIndex=-9999;\n"
 					"for(var i=0; i<52; i++) eval('$(\\'ID_0x0'+(0x760+i).toString(16).toUpperCase()+'\\').disabled=\\'true\\';');\n"
 					"for(var i=0; i<52; i++) eval('$(\\'N'+(6350+i)+'\\').disabled=true;');\n"
 				"}\n"
 				"else\n"
 				"{\n"
 					"$('trans').style.zIndex=-9999;\n"
 				"}					\n"
 			"}\n"
 		"};\n"
 		"xmlhttp.open('GET',URL,true);\n"
 		"xmlhttp.send();\n"
 	"}\n"
 	 "function read_back(addr)\n"
 	"{ \n"
 		"var url='s_027.html?';\n"
"\n"
 		"url=url+'0xFFFF'+'&0x0'+addr.toString(16).toUpperCase();\n"
 		"url=url+'&time='+Math.random();\n"
 			//alert(url);
"\n"
 		"var xmlhttp;\n"
 		"if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
 		"else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
 		"xmlhttp.onreadystatechange=function()\n"
 		"{\n"
 			"if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
 			"{\n"
 				"eval('Json='+xmlhttp.responseText);\n"
 	            	//回读PVS modbus地址
 	            "if(addr >= 0x760 && addr < 0x800)\n"
 	            "{\n"
 					"var pr,fe;\n"
 					"eval('pr=$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value;');\n"
 					"eval('fe=Json.ID_0x0'+addr.toString(16).toUpperCase()+';');\n"
 					"if(pr!=fe) eval('$(\\'ID_0x0'+addr.toString(16).toUpperCase()+'\\').value=Json.ID_0x0'+addr.toString(16).toUpperCase()+';');\n"
 		     		"show_tip_ex(5, '&nbsp;');\n"
 		    		"if(pr==fe){setTimeout('show_tip_ex(5,lang.N542[language])',500);}\n"
 		    		"else {setTimeout('show_tip_ex(5,lang.N541[language])',500);}\n"
 			           "setTimeout('show_tip_ex(5, \\'&nbsp;\\')',2500);               		\n"
 	            "}  \n"
 			"}\n"
 		"};\n"
 		"xmlhttp.open('GET',url,true);\n"
 		"xmlhttp.send();     \n"
        "} 	\n"
"\n"
 	"function doSubmit(obj)\n"
 	"{\n"
            "var URL='a_027.html?';\n"
"\n"
            "var readBack=0;\n"
            "switch(obj.id)\n"
            "{\n"
             	//serail pvs设置 
             "case 'N6350': case 'N6351': case 'N6352': case 'N6353': case 'N6354': case 'N6355': case 'N6356': case 'N6357': case 'N6358': case 'N6359': \n"
             "case 'N6360': case 'N6361': case 'N6362': case 'N6363': case 'N6364': case 'N6365': case 'N6366': case 'N6367': case 'N6368': case 'N6369': \n"
             "case 'N6370': case 'N6371': case 'N6372': case 'N6373': case 'N6374': case 'N6375': case 'N6376': case 'N6377': case 'N6378': case 'N6379':\n"
             "case 'N6380': case 'N6381': case 'N6382': case 'N6383': case 'N6384': case 'N6385': case 'N6386': case 'N6387': case 'N6388': case 'N6389': \n"
             "case 'N6390': case 'N6391': case 'N6392': case 'N6393': case 'N6394': case 'N6395': case 'N6396': case 'N6397': case 'N6398': case 'N6399': \n"
             "var str = obj.id;\n"
             "var cutstr = str.substring(str.length-4,str.length);\n"
            	"var index = parseInt(cutstr)-6350;\n"
             "if(flg_pvs[index]){return;}   \n"
             "eval('URL=URL+\\'&0x0'+(0x760+index).toString(16).toUpperCase()+'=\\'+$(\\'ID_0x0'+(0x760+index).toString(16).toUpperCase()+'\\').value;');\n"
             "eval('readBack=0x0'+(0x760+index).toString(16).toUpperCase()+';');    \n"
             "break;     	\n"
             "default:break;\n"
            "}\n"
"\n"
            "URL=URL+'&time='+Math.random();\n"
             //alert(URL);          
"\n"
            "function success()\n"
            "{\n"
             "if(readBack >= 0x760 && readBack < 0x800)\n"
             "{\n"
 	     		"show_tip_ex(5, '&nbsp;');\n"
 	    		"setTimeout('read_back('+readBack+')', 100);\n"
 		           "setTimeout('show_tip_ex(5, \\'&nbsp;\\')',2500);               		\n"
             "} \n"
            "} \n"
"\n"
             //测试
             //success();  
"\n"
 		"sendHttpReq(URL, success);\n"
 	"}\n"
"\n"
 	"function show_tip_ex(id, obj){eval('$(\\'tip'+id+'\\').innerHTML=obj;');}\n"
 	"function doRangeCheck(obj,reg)\n"
 	"{\n"
 		"var range=parseInt(obj.value);\n"
 		"var err, err2;			\n"
"\n"
 		"if(!obj.value.match(reg)){err=2;}\n"
 		"else if(range<1||range>247){err=1;}\n"
 		"else{err=0;}\n"
 "\n"
 			//pvs
 		"switch(obj.id)\n"
 		"{\n"
 			"case \"ID_0x0760\": case \"ID_0x0761\": case \"ID_0x0762\": case \"ID_0x0763\": case \"ID_0x0764\": case \"ID_0x0765\": case \"ID_0x0766\": case \"ID_0x0767\": case \"ID_0x0768\": case \"ID_0x0769\":\n"
 			 "case \"ID_0x076A\": case \"ID_0x076B\": case \"ID_0x076C\": case \"ID_0x076D\": case \"ID_0x076E\": case \"ID_0x076F\": case \"ID_0x0770\": case \"ID_0x0771\": case \"ID_0x0772\": case \"ID_0x0773\": \n"
 			 "case \"ID_0x0774\": case \"ID_0x0775\": case \"ID_0x0776\": case \"ID_0x0777\": case \"ID_0x0778\": case \"ID_0x0779\": case \"ID_0x077A\": case \"ID_0x077B\": case \"ID_0x077C\": case \"ID_0x077D\": \n"
 			 "case \"ID_0x077E\": case \"ID_0x077F\": case \"ID_0x0780\": case \"ID_0x0781\": case \"ID_0x0782\": case \"ID_0x0783\": case \"ID_0x0784\": case \"ID_0x0785\": case \"ID_0x0786\": case \"ID_0x0787\": \n"
 			 "case \"ID_0x0788\": case \"ID_0x0789\": case \"ID_0x078A\": case \"ID_0x078B\": case \"ID_0x078C\": case \"ID_0x078D\": case \"ID_0x078E\": case \"ID_0x078F\": case \"ID_0x0790\": case \"ID_0x0791\":\n"
 			"if(err==1||err==2)\n"
 			"{\n"
 				"for(var i=0; i<Json.ID_0x0353; i++)\n"
 				"{\n"
 					"if(eval('$(\\'ID_0x0'+(0x760+i).toString(16).toUpperCase()+'\\').id')==obj.id) {flg_pvs[i]=1;eval('$(\\'N'+(6350+i)+'\\').disabled=true;');break;}\n"
 				"}					\n"
 			"}\n"
 			"if(err==1)show_tip_ex(5,lang.N544[language]);\n"
 			"else if(err==2)show_tip_ex(5,lang.N543[language]);\n"
 			"else{\n"
 				"for(var i=0; i<Json.ID_0x0353; i++)\n"
 				"{\n"
 					"if(eval('$(\\'ID_0x0'+(0x760+i).toString(16).toUpperCase()+'\\').id')==obj.id) {flg_pvs[i]=0;eval('$(\\'N'+(6350+i)+'\\').disabled=false;');break;}\n"
 				"}						\n"
 				"var a=0;\n"
 				"for(var i=0; i<50; i++) a|=flg_pvs[i];\n"
 				"if(a==0)show_tip_ex(5,\"&nbsp;\");						\n"
 			"}\n"
 			"break;\n"
 		"}\n"
 	"}\n"
 "</script>\n"
"</html>\n"
};
#endif
