#ifndef _J_008_H_
#define _J_008_H_

static const char j_008[]={
"HTTP/1.1 200 OK\r\nContent-Type:text/javascript\r\nAccept-Ranges:bytes\r\n\r\n"
 // Highcharts JS v5.0.10 (2017-03-31)\n"
 // Exporting module\n"
 // (c) 2010-2017 Torstein Honsi\n"
 // License: www.highcharts.com/license\n"
"(function(k) {\n"
    "\"object\" === typeof module && module.exports ? module.exports = k: k(Highcharts)\n"
"})(function(k) { (function(f) {\n"
        "var k = f.defaultOptions,\n"
        "n = f.doc,\n"
        "A = f.Chart,\n"
        "w = f.addEvent,\n"
        "F = f.removeEvent,\n"
        "D = f.fireEvent,\n"
        "q = f.createElement,\n"
        "B = f.discardElement,\n"
        "u = f.css,\n"
        "p = f.merge,\n"
        "C = f.pick,\n"
        "h = f.each,\n"
        "r = f.extend,\n"
        "G = f.isTouchDevice,\n"
        "E = f.win,\n"
        "H = f.Renderer.prototype.symbols;\n"
        "r(k.lang, {\n"
            "printChart: \"Print chart\",\n"
            "downloadPNG: \"Download PNG image\",\n"
            "downloadJPEG: \"Download JPEG image\",\n"
            "downloadPDF: \"Download PDF document\",\n"
            "downloadSVG: \"Download SVG vector image\",\n"
            "contextButtonTitle: \"Chart context menu\"\n"
        "});\n"
        "k.navigation = {\n"
            "buttonOptions: {\n"
                "theme: {},\n"
                "symbolSize: 14,\n"
                "symbolX: 12.5,\n"
                "symbolY: 10.5,\n"
                "align: \"right\",\n"
                "buttonSpacing: 3,\n"
                "height: 22,\n"
                "verticalAlign: \"top\",\n"
                "width: 24\n"
            "}\n"
        "};\n"
        "p(!0, k.navigation, {\n"
            "menuStyle: {\n"
                "border: \"1px solid #999999\",\n"
                "background: \"#ffffff\",\n"
                "padding: \"5px 0\"\n"
            "},\n"
            "menuItemStyle: {\n"
                "padding: \"0.5em 1em\",\n"
                "background: \"none\",\n"
                "color: \"#333333\",\n"
                "fontSize: G ? \"14px\": \"11px\",\n"
                "transition: \"background 250ms, color 250ms\"\n"
            "},\n"
            "menuItemHoverStyle: {\n"
                "background: \"#335cad\",\n"
                "color: \"#ffffff\"\n"
            "},\n"
            "buttonOptions: {\n"
                "symbolFill: \"#666666\",\n"
                "symbolStroke: \"#666666\",\n"
                "symbolStrokeWidth: 3,\n"
                "theme: {\n"
                    "fill: \"#ffffff\",\n"
                    "stroke: \"none\",\n"
                    "padding: 5\n"
                "}\n"
            "}\n"
        "});\n"
        "k.exporting = {\n"
            "type: \"image/png\",\n"
            "url: \"https://export.highcharts.com/\",\n"
            "printMaxWidth: 780,\n"
            "scale: 2,\n"
            "buttons: {\n"
                "contextButton: {\n"
                    "className: \"highcharts-contextbutton\",\n"
                    "menuClassName: \"highcharts-contextmenu\",\n"
                    "symbol: \"menu\",\n"
                    "_titleKey: \"contextButtonTitle\",\n"
                    "menuItems: [{\n"
                        "textKey: \"printChart\",\n"
                        "onclick: function() {\n"
                            "this.print()\n"
                        "}\n"
                    "},\n"
                    "{\n"
                        "separator: !0\n"
                    "},\n"
                    "{\n"
                        "textKey: \"downloadPNG\",\n"
                        "onclick: function() {\n"
                            "this.exportChart()\n"
                        "}\n"
                    "},\n"
                    "{\n"
                        "textKey: \"downloadJPEG\",\n"
                        "onclick: function() {\n"
                            "this.exportChart({\n"
                                "type: \"image/jpeg\"\n"
                            "})\n"
                        "}\n"
                    "},\n"
                    "{\n"
                        "textKey: \"downloadPDF\",\n"
                        "onclick: function() {\n"
                            "this.exportChart({\n"
                                "type: \"application/pdf\"\n"
                            "})\n"
                        "}\n"
                    "},\n"
                    "{\n"
                        "textKey: \"downloadSVG\",\n"
                        "onclick: function() {\n"
                            "this.exportChart({\n"
                                "type: \"image/svg+xml\"\n"
                            "})\n"
                        "}\n"
                    "}]\n"
                "}\n"
            "}\n"
        "};\n"
        "f.post = function(a, b, e) {\n"
            "var c;\n"
            "a = q(\"form\", p({\n"
                "method: \"post\",\n"
                "action: a,\n"
                "enctype: \"multipart/form-data\"\n"
            "},\n"
            "e), {\n"
                "display: \"none\"\n"
            "},\n"
            "n.body);\n"
            "for (c in b) q(\"input\", {\n"
                "type: \"hidden\",\n"
                "name: c,\n"
                "value: b[c]\n"
            "},\n"
            "null, a);\n"
            "a.submit();\n"
            "B(a)\n"
        "};\n"
        "r(A.prototype, {\n"
            "sanitizeSVG: function(a, b) {\n"
                "if (b && b.exporting && b.exporting.allowHTML) {\n"
                    "var e = a.match(/<\\/svg>(.*?$)/);\n"
                    "e && e[1] && (e = '\\x3cforeignObject x\\x3d\"0\" y\\x3d\"0\" width\\x3d\"' + b.chart.width + '\" height\\x3d\"' + b.chart.height + '\"\\x3e\\x3cbody xmlns\\x3d\"http://www.w3.org/1999/xhtml\"\\x3e' + e[1] + \"\\x3c/body\\x3e\\x3c/foreignObject\\x3e\", a = a.replace(\"\\x3c/svg\\x3e\", e + \"\\x3c/svg\\x3e\"))\n"
                "}\n"
                "a = a.replace(/zIndex=\"[^\"]+\"/g, \"\").replace(/isShadow=\"[^\"]+\"/g, \"\").replace(/symbolName=\"[^\"]+\"/g, \"\").replace(/jQuery[0-9]+=\"[^\"]+\"/g, \"\").replace(/url\\((\"|&quot;)(\\S+)(\"|&quot;)\\)/g, \"url($2)\").replace(/url\\([^#]+#/g, \"url(#\").replace(/<svg /, '\\x3csvg xmlns:xlink\\x3d\"http://www.w3.org/1999/xlink\" ').replace(/ (NS[0-9]+\\:)?href=/g, \" xlink:href\\x3d\").replace(/\\n/, \" \").replace(/<\\/svg>.*?$/, \"\\x3c/svg\\x3e\").replace(/(fill|stroke)=\"rgba\\(([ 0-9]+,[ 0-9]+,[ 0-9]+),([ 0-9\\.]+)\\)\"/g, '$1\\x3d\"rgb($2)\" $1-opacity\\x3d\"$3\"').replace(/&nbsp;/g, \"\\u00a0\").replace(/&shy;/g, \"\\u00ad\");\n"
                "return a = a.replace(/<IMG /g, \"\\x3cimage \").replace(/<(\\/?)TITLE>/g, \"\\x3c$1title\\x3e\").replace(/height=([^\" ]+)/g, 'height\\x3d\"$1\"').replace(/width=([^\" ]+)/g, 'width\\x3d\"$1\"').replace(/hc-svg-href=\"([^\"]+)\">/g, 'xlink:href\\x3d\"$1\"/\\x3e').replace(/ id=([^\" >]+)/g, ' id\\x3d\"$1\"').replace(/class=([^\" >]+)/g, 'class\\x3d\"$1\"').replace(/ transform /g, \" \").replace(/:(path|rect)/g, \"$1\").replace(/style=\"([^\"]+)\"/g,\n"
                "function(a) {\n"
                    "return a.toLowerCase()\n"
                "})\n"
            "},\n"
            "getChartHTML: function() {\n"
                "return this.container.innerHTML\n"
            "},\n"
            "getSVG: function(a) {\n"
                "var b, e, c, v, m, g = p(this.options, a);\n"
                "n.createElementNS || (n.createElementNS = function(a, b) {\n"
                    "return n.createElement(b)\n"
                "});\n"
                "e = q(\"div\", null, {\n"
                    "position: \"absolute\",\n"
                    "top: \"-9999em\",\n"
                    "width: this.chartWidth + \"px\",\n"
                    "height: this.chartHeight + \"px\"\n"
                "},\n"
                "n.body);\n"
                "c = this.renderTo.style.width;\n"
                "m = this.renderTo.style.height;\n"
                "c = g.exporting.sourceWidth || g.chart.width || /px$/.test(c) && parseInt(c, 10) || 600;\n"
                "m = g.exporting.sourceHeight || g.chart.height || /px$/.test(m) && parseInt(m, 10) || 400;\n"
                "r(g.chart, {\n"
                    "animation: !1,\n"
                    "renderTo: e,\n"
                    "forExport: !0,\n"
                    "renderer: \"SVGRenderer\",\n"
                    "width: c,\n"
                    "height: m\n"
                "});\n"
                "g.exporting.enabled = !1;\n"
                "delete g.data;\n"
                "g.series = [];\n"
                "h(this.series,\n"
                "function(a) {\n"
                    "v = p(a.userOptions, {\n"
                        "animation: !1,\n"
                        "enableMouseTracking: !1,\n"
                        "showCheckbox: !1,\n"
                        "visible: a.visible\n"
                    "});\n"
                    "v.isInternal || g.series.push(v)\n"
                "});\n"
                "h(this.axes,\n"
                "function(a) {\n"
                    "a.userOptions.internalKey || (a.userOptions.internalKey = f.uniqueKey())\n"
                "});\n"
                "b = new f.Chart(g, this.callback);\n"
                "a && h([\"xAxis\", \"yAxis\", \"series\"],\n"
                "function(c) {\n"
                    "var d = {};\n"
                    "a[c] && (d[c] = a[c], b.update(d))\n"
                "});\n"
                "h(this.axes,\n"
                "function(a) {\n"
                    "var c = f.find(b.axes,\n"
                    "function(b) {\n"
                        "return b.options.internalKey === a.userOptions.internalKey\n"
                    "}),\n"
                    "d = a.getExtremes(),\n"
                    "e = d.userMin,\n"
                    "d = d.userMax; ! c || void 0 === e && void 0 === d || c.setExtremes(e, d, !0, !1)\n"
                "});\n"
                "c = b.getChartHTML();\n"
                "c = this.sanitizeSVG(c, g);\n"
                "g = null;\n"
                "b.destroy();\n"
                "B(e);\n"
                "return c\n"
            "},\n"
            "getSVGForExport: function(a, b) {\n"
                "var e = this.options.exporting;\n"
                "return this.getSVG(p({\n"
                    "chart: {\n"
                        "borderRadius: 0\n"
                    "}\n"
                "},\n"
                "e.chartOptions, b, {\n"
                    "exporting: {\n"
                        "sourceWidth: a && a.sourceWidth || e.sourceWidth,\n"
                        "sourceHeight: a && a.sourceHeight || e.sourceHeight\n"
                    "}\n"
                "}))\n"
            "},\n"
            "exportChart: function(a, b) {\n"
                "b = this.getSVGForExport(a, b);\n"
                "a = p(this.options.exporting, a);\n"
                "f.post(a.url, {\n"
                    "filename: a.filename || \"chart\",\n"
                    "type: a.type,\n"
                    "width: a.width || 0,\n"
                    "scale: a.scale,\n"
                    "svg: b\n"
                "},\n"
                "a.formAttributes)\n"
            "},\n"
            "print: function() {\n"
                "var a = this,\n"
                "b = a.container,\n"
                "e = [],\n"
                "c = b.parentNode,\n"
                "f = n.body,\n"
                "m = f.childNodes,\n"
                "g = a.options.exporting.printMaxWidth,\n"
                "d,\n"
                "t;\n"
                "if (!a.isPrinting) {\n"
                    "a.isPrinting = !0;\n"
                    "a.pointer.reset(null, 0);\n"
                    "D(a, \"beforePrint\");\n"
                    "if (t = g && a.chartWidth > g) d = [a.options.chart.width, void 0, !1],\n"
                    "a.setSize(g, void 0, !1);\n"
                    "h(m,\n"
                    "function(a, b) {\n"
                        "1 === a.nodeType && (e[b] = a.style.display, a.style.display = \"none\")\n"
                    "});\n"
                    "f.appendChild(b);\n"
                    "E.focus();\n"
                    "E.print();\n"
                    "setTimeout(function() {\n"
                        "c.appendChild(b);\n"
                        "h(m,\n"
                        "function(a, b) {\n"
                            "1 === a.nodeType && (a.style.display = e[b])\n"
                        "});\n"
                        "a.isPrinting = !1;\n"
                        "t && a.setSize.apply(a, d);\n"
                        "D(a, \"afterPrint\")\n"
                    "},\n"
                    "1E3)\n"
                "}\n"
            "},\n"
            "contextMenu: function(a, b, e, c, f, m, g) {\n"
                "var d = this,\n"
                "t = d.options.navigation,\n"
                "v = d.chartWidth,\n"
                "k = d.chartHeight,\n"
                "p = \"cache-\" + a,\n"
                "l = d[p],\n"
                "x = Math.max(f, m),\n"
                "y,\n"
                "z;\n"
                "l || (d[p] = l = q(\"div\", {\n"
                    "className: a\n"
                "},\n"
                "{\n"
                    "position: \"absolute\",\n"
                    "zIndex: 1E3,\n"
                    "padding: x + \"px\"\n"
                "},\n"
                "d.container), y = q(\"div\", {\n"
                    "className: \"highcharts-menu\"\n"
                "},\n"
                "null, l), u(y, r({\n"
                    "MozBoxShadow: \"3px 3px 10px #888\",\n"
                    "WebkitBoxShadow: \"3px 3px 10px #888\",\n"
                    "boxShadow: \"3px 3px 10px #888\"\n"
                "},\n"
                "t.menuStyle)), z = function() {\n"
                    "u(l, {\n"
                        "display: \"none\"\n"
                    "});\n"
                    "g && g.setState(0);\n"
                    "d.openMenu = !1\n"
                "},\n"
                "d.exportEvents.push(w(l, \"mouseleave\",\n"
                "function() {\n"
                    "l.hideTimer = setTimeout(z, 500)\n"
                "}), w(l, \"mouseenter\",\n"
                "function() {\n"
                    "clearTimeout(l.hideTimer)\n"
                "}), w(n, \"mouseup\",\n"
                "function(b) {\n"
                    "d.pointer.inClass(b.target, a) || z()\n"
                "})), h(b,\n"
                "function(a) {\n"
                    "if (a) {\n"
                        "var b;\n"
                        "a.separator ? b = q(\"hr\", null, null, y) : (b = q(\"div\", {\n"
                            "className: \"highcharts-menu-item\",\n"
                            "onclick: function(b) {\n"
                                "b && b.stopPropagation();\n"
                                "z();\n"
                                "a.onclick && a.onclick.apply(d, arguments)\n"
                            "},\n"
                            "innerHTML: a.text || d.options.lang[a.textKey]\n"
                        "},\n"
                        "null, y), b.onmouseover = function() {\n"
                            "u(this, t.menuItemHoverStyle)\n"
                        "},\n"
                        "b.onmouseout = function() {\n"
                            "u(this, t.menuItemStyle)\n"
                        "},\n"
                        "u(b, r({\n"
                            "cursor: \"pointer\"\n"
                        "},\n"
                        "t.menuItemStyle)));\n"
                        "d.exportDivElements.push(b)\n"
                    "}\n"
                "}), d.exportDivElements.push(y, l), d.exportMenuWidth = l.offsetWidth, d.exportMenuHeight = l.offsetHeight);\n"
                "b = {\n"
                    "display: \"block\"\n"
                "};\n"
                "e + d.exportMenuWidth > v ? b.right = v - e - f - x + \"px\": b.left = e - x + \"px\";\n"
                "c + m + d.exportMenuHeight > k && \"top\" !== g.alignOptions.verticalAlign ? b.bottom = k - c - x + \"px\": b.top = c + m - x + \"px\";\n"
                "u(l, b);\n"
                "d.openMenu = !0\n"
            "},\n"
            "addButton: function(a) {\n"
                "var b = this,\n"
                "e = b.renderer,\n"
                "c = p(b.options.navigation.buttonOptions, a),\n"
                "f = c.onclick,\n"
                "m = c.menuItems,\n"
                "g,\n"
                "d,\n"
                "k = c.symbolSize || 12;\n"
                "b.btnCount || (b.btnCount = 0);\n"
                "b.exportDivElements || (b.exportDivElements = [], b.exportSVGElements = []);\n"
                "if (!1 !== c.enabled) {\n"
                    "var h = c.theme,\n"
                    "n = h.states,\n"
                    "q = n && n.hover,\n"
                    "n = n && n.select,\n"
                    "l;\n"
                    "delete h.states;\n"
                    "f ? l = function(a) {\n"
                        "a.stopPropagation();\n"
                        "f.call(b, a)\n"
                    "}: m && (l = function() {\n"
                        "b.contextMenu(d.menuClassName, m, d.translateX, d.translateY, d.width, d.height, d);\n"
                        "d.setState(2)\n"
                    "});\n"
                    "c.text && c.symbol ? h.paddingLeft = C(h.paddingLeft, 25) : c.text || r(h, {\n"
                        "width: c.width,\n"
                        "height: c.height,\n"
                        "padding: 0\n"
                    "});\n"
                    "d = e.button(c.text, 0, 0, l, h, q, n).addClass(a.className).attr({\n"
                        "\"stroke-linecap\": \"round\",\n"
                        "title: b.options.lang[c._titleKey],\n"
                        "zIndex: 3\n"
                    "});\n"
                    "d.menuClassName = a.menuClassName || \"highcharts-menu-\" + b.btnCount++;\n"
                    "c.symbol && (g = e.symbol(c.symbol, c.symbolX - k / 2, c.symbolY - k / 2, k, k).addClass(\"highcharts-button-symbol\").attr({\n"
                        "zIndex: 1\n"
                    "}).add(d), g.attr({\n"
                        "stroke: c.symbolStroke,\n"
                        "fill: c.symbolFill,\n"
                        "\"stroke-width\": c.symbolStrokeWidth || 1\n"
                    "}));\n"
                    "d.add().align(r(c, {\n"
                        "width: d.width,\n"
                        "x: C(c.x, b.buttonOffset)\n"
                    "}), !0, \"spacingBox\");\n"
                    "b.buttonOffset += (d.width + c.buttonSpacing) * (\"right\" === c.align ? -1 : 1);\n"
                    "b.exportSVGElements.push(d, g)\n"
                "}\n"
            "},\n"
            "destroyExport: function(a) {\n"
                "var b = a ? a.target: this;\n"
                "a = b.exportSVGElements;\n"
                "var e = b.exportDivElements,\n"
                "c = b.exportEvents,\n"
                "f;\n"
                "a && (h(a,\n"
                "function(a, c) {\n"
                    "a && (a.onclick = a.ontouchstart = null, f = \"cache-\" + a.menuClassName, b[f] && delete b[f], b.exportSVGElements[c] = a.destroy())\n"
                "}), a.length = 0);\n"
                "e && (h(e,\n"
                "function(a, c) {\n"
                    "clearTimeout(a.hideTimer);\n"
                    "F(a, \"mouseleave\");\n"
                    "b.exportDivElements[c] = a.onmouseout = a.onmouseover = a.ontouchstart = a.onclick = null;\n"
                    "B(a)\n"
                "}), e.length = 0);\n"
                "c && (h(c,\n"
                "function(a) {\n"
                    "a()\n"
                "}), c.length = 0)\n"
            "}\n"
        "});\n"
        "H.menu = function(a, b, e, c) {\n"
            "return [\"M\", a, b + 2.5, \"L\", a + e, b + 2.5, \"M\", a, b + c / 2 + .5, \"L\", a + e, b + c / 2 + .5, \"M\", a, b + c - 1.5, \"L\", a + e, b + c - 1.5]\n"
        "};\n"
        "A.prototype.renderExporting = function() {\n"
            "var a, b = this.options.exporting,\n"
            "e = b.buttons,\n"
            "c = this.isDirtyExporting || !this.exportSVGElements;\n"
            "this.buttonOffset = 0;\n"
            "this.isDirtyExporting && this.destroyExport();\n"
            "if (c && !1 !== b.enabled) {\n"
                "this.exportEvents = [];\n"
                "for (a in e) this.addButton(e[a]);\n"
                "this.isDirtyExporting = !1\n"
            "}\n"
            "w(this, \"destroy\", this.destroyExport)\n"
        "};\n"
        "A.prototype.callbacks.push(function(a) {\n"
            "a.renderExporting();\n"
            "w(a, \"redraw\", a.renderExporting);\n"
            "h([\"exporting\", \"navigation\"],\n"
            "function(b) {\n"
                "a[b] = {\n"
                    "update: function(e, c) {\n"
                        "a.isDirtyExporting = !0;\n"
                        "p(!0, a.options[b], e);\n"
                        "C(c, !0) && a.redraw()\n"
                    "}\n"
                "}\n"
            "})\n"
        "})\n"
    "})(k)\n"
"});\n"
};
#endif
