#ifndef _J_001_H_
#define _J_001_H_
static const char j_001[]={
"HTTP/1.1 200 OK\r\nContent-Type:text/javascript\r\nAccept-Ranges:bytes\r\n\r\n"
 "var $=function(o){return document.getElementById(o);};\n"
 "var spp10=function(o){return parseInt(parseFloat($(o).value)*10);};\n"
 "var spp100=function(o){return parseInt(parseFloat($(o).value)*100);};\n"
 "var spp1k=function(o){return parseInt(parseFloat($(o).value)*1000);};\n"
 "var check1=true;var check2=true;var check3=true;var check4=true;\n"
 "var check5=true;var check6=true;var check7=true;var check8=true;\n"
 "var check9=true;var check10=true;var check11=true;var check12=true;\n"
 "function ture_or_flase(){if(check1&&check2&&check3&&check4&&check5&&check6&&check7&&check8&&check9&&check10&&check11&&check12)return true;else return false;}\n"
 "var rtn=ture_or_flase();\n"
 "function show_tip(obj){$('tip').innerHTML=obj;}\n"
 "function show_nbsp(){$('tip').innerHTML='&nbsp;';}\n"
 	//需要将'\\'转换为'\\\\'
 "function lang_init(loop){for(var i=1;i<=loop;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
 	//需要将'\\'转换为'\\\\'
 "function lang_init_ex(st,end){for(var i=st;i<=end;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
 "var FromMobileDevice=false;\n"
 "function FromWhichDevice()\n"
 "{\n"
 	"var sUserAgent=navigator.userAgent.toLowerCase();\n"
 	"var Ipad=sUserAgent.match(/ipad/i)=='ipad';\n"
 	"var IphoneOs=sUserAgent.match(/iphone os/i)=='iphone os';\n"
 	"var Android=sUserAgent.match(/android/i)=='android';\n"
 	"var WindowsPhone=sUserAgent.match(/windows phone/i)=='windows phone';\n"
 	"if(Ipad||IphoneOs||Android||WindowsPhone)FromMobileDevice=true;\n"
 	"else FromMobileDevice=false;\n"
 "}\n"
 //"function resetTime()\n"
 //"{\n"
 //	"clearTimeout(myTime);\n"
 //	"myTime=setTimeout('Timeout()',600000);\n"
 //"}\n"
 //"function Timeout()\n"
 //"{\n"
 //	"parent.document.location.href='Login.html';\n"
 //"}\n"
 //"var myTime=setTimeout('Timeout()',600000);\n"
 //"window.document.documentElement.onmousemove=resetTime;\n"
 "function show_T(tid)\n"
 "{\n"
 	"var str='';\n"
 	"str+=\"<div class='title' style='width:90%;'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
 	"str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
 	"str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
 	"document.write(str);\n"
 "}\n"
 "function show_sT(tid)\n"
 "{\n"
 	"var str='';\n"
 	"str+=\"<div class='title' style='width:90%;'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
 	"str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
 	"str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
 	"document.write(str);\n"
 "}\n"
 "function show_sT_ex(tid, id)\n"
 "{\n"
 	"var str='';\n"
 	"str+=\"<div class='title' id='\"+id+\"' style='display:none;width:90%'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
 	"str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
 	"str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
 	"document.write(str);\n"
 "}\n"
 "window.document.onkeydowm=show_nbsp;\n"
 "function sendHttpReq(url, successFn)\n"
 "{\n"
 		//alert(url);	
        "var xmlhttp;\n"
        "if(window.XMLHttpRequest)xmlhttp=new XMLHttpRequest();\n"
        "else xmlhttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
        "xmlhttp.onreadystatechange=function()\n"
        "{\n"
            "if(xmlhttp.readyState==4 && xmlhttp.status==200)\n"
            "{\n"
                "if(xmlhttp.responseText=='1'){successFn();}\n"
            "}\n"
        "};\n"
        "xmlhttp.open('GET',url,true);\n"
        "xmlhttp.send();\n"
 "}\n"
"\n"
};
#endif
