#ifndef _J_000_H_
#define _J_000_H_
static const char j_000[]={
"HTTP/1.1 200 OK\r\nContent-Type:text/javascript\r\nAccept-Ranges:bytes\r\n\r\n"
	"var $=function(o){return document.getElementById(o);};"
	"var OBJ=function(o){return document.getElementById(o);};"
	"var spp10=function(o){return parseInt(parseFloat($(o).value)*10);};"
	"var spp100=function(o){return parseInt(parseFloat($(o).value)*100);};"
	"var spp1k=function(o){return parseInt(parseFloat($(o).value)*1000);};"
	"var check1=true;var check2=true;var check3=true;var check4=true;"
	"var check5=true;var check6=true;var check7=true;var check8=true;"
	"var check9=true;var check10=true;var check11=true;var check12=true;"
	"function ture_or_flase(){if(check1&&check2&&check3&&check4&&check5&&check6&&check7&&check8&&check9&&check10&&check11&&check12)return true;else return false;}"
	"var rtn=ture_or_flase();"
	"function show_tip(obj){$('tip').innerHTML=obj;}"
	"function show_nbsp(){$('tip').innerHTML='&nbsp;';}"
	"function lang_init(loop){for(var i=1;i<=loop;i++)eval('$(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}"
	"var FromMobileDevice=false;"
	"function FromWhichDevice()"
	"{"
		"var sUserAgent=navigator.userAgent.toLowerCase();"
		"var Ipad=sUserAgent.match(/ipad/i)=='ipad';"
		"var IphoneOs=sUserAgent.match(/iphone os/i)=='iphone os';"
		"var Android=sUserAgent.match(/android/i)=='android';"
		"var WindowsPhone=sUserAgent.match(/windows phone/i)=='windows phone';"
		"if(Ipad||IphoneOs||Android||WindowsPhone)FromMobileDevice=true;"
		"else FromMobileDevice=false;"
	"}"
	"function resetTime()"
	"{"
		"clearTimeout(myTime);"
		"myTime=setTimeout('Timeout()',600000);"
	"}"
	//"function Timeout()"
	//"{"
	//	"parent.document.location.href='Login.html';"
	//"}"
	//"var myTime=setTimeout('Timeout()',600000);"
	//"window.document.documentElement.onmousemove=resetTime;"
	"function show_T(tid)"
	"{"
		"var str='';"
		"str+=\"<div class='title'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";"
		"str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";"
		"str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";"
		"document.write(str);"
	"}"
	"function show_sT(tid)"
	"{"
		"var str='';"
		"str+=\"<div class='title'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";"
		"str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";"
		"str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";"
		"document.write(str);"
	"}"
	"window.document.onkeydowm=show_nbsp;"
	"function SelectYear()"
	"{"
		"for(i=2000;i<=2099;i++)"
		"{"
			"document.write('<option value=\\''+i+'\\'>'+i+'</option>');"
		"}"
	"}"
	"function SelectMonth()"
	"{"
		"for(i=1;i<=12;i++)"
		"{"
			"if(i<10)document.write('<option value=\\''+i+'\\'>0'+i+'</option>');"
			"else document.write('<option value=\\''+i+'\\'>'+i+'</option>');"
		"}"
	"}"
	"function CheckDay(Y,M,D)"
	"{"
		"var YearNo,MonthNo,DayNo;"
		"try"
		"{"
			"YearNo=$(Y).value;"
			"MonthNo=$(M).value;"
		"}"
		"catch(e)"
		"{"
			"var datenow=new Date();"
			"YearNo=datenow.getFullYear();"
			"MonthNo=datenow.getMonth()+1;"
		"}"
		"var i,DayCount;"
		"if(MonthNo==1||MonthNo==3||MonthNo==5||MonthNo==7||MonthNo==8||MonthNo==10||MonthNo==12)"
		"{"
			"DayCount=31;"
		"}"
		"if(MonthNo==4||MonthNo==6||MonthNo==9||MonthNo==11 )"
		"{"
			"DayCount=30;"
		"}"
		"if(MonthNo==2)"
		"{"
			"if(IsRunY(YearNo))"
			"{"
				"DayCount=29;"
			"}"
			"else"
			"{"
				"DayCount=28;"
			"}"
		"}"
		"$(D).length=DayCount;"
		"var currentDay=new Date().getDate();"
		"for(i=0;i<DayCount;i++)"
		"{"
			"$(D)[i]=new Option(i+1);"
			"$(D)[i].value=i+1;"
			"$(D)[i].innerHTML=i<9?'0'+(i+1):(i+1);"
			"if(currentDay==(i+1))"
			"$(D)[i].selected=true;"
		"}"
	"}"
	"function IsRunY(YearNo)"
	"{"
		"if((YearNo%4==0&&YearNo%100!=0)||YearNo%400==0)return true;"
		"else return false;"
	"}"
	"var PagerView=function(id,AAA,BBB,CCC)"
	"{"
		"var self=this;"
		"this.id=id;"
		"this._pageCount=0;"
		"this._start=1;"
		"this._end=1;"
		"this.container=null;"
		"this.index=1;"
		"this.size=10;"
		"this.maxButtons=10;"
		"this.itemCount=0;"
		"this.onclick=function(index){return true;};"
		"this._onclick=function(index)"
		"{"
			"var old=self.index;"
			"self.index=index;"
			"if(self.onclick(index)!==false)self.render();"
			"else self.index=old;"
		"};"
		"this._calculate=function()"
		"{"
			"self._pageCount=parseInt(Math.ceil(self.itemCount/self.size));"
			"self.index=parseInt(self.index);"
			"if(self.index>self._pageCount)self.index=self._pageCount;"
			"if(self.index<1)self.index=1;"
			"self._start=Math.max(1,self.index-parseInt(self.maxButtons/2));"
			"self._end=Math.min(self._pageCount,self._start+self.maxButtons-1);"
			"self._start=Math.max(1,self._end-self.maxButtons+1);"
		"};"
		"this.page=function(rows)"
		"{"
			"self._calculate();"
			"var s_num=(self.index-1)*self.size ;"
			"var e_num=self.index*self.size;"
			"return rows.slice(s_num,e_num);"
		"};"
		"this.render=function()"
		"{"
			"var div=document.getElementById(self.id);"
			"div.view=self;"
			"self.container=div;"
			"self._calculate();"
			"var str='';"
			"str+='<div class=\"PagerView\">\\n';"
			"if(self._pageCount>1)"
			"{"
				"if(self.index!=1)"
				"{"
					"str+='<a href=\"javascript://1\"><span>|&lt;</span></a>';"
					"str+='<a href=\"javascript://'+(self.index-1)+'\"><span>&lt;&lt;</span></a>';"
				"}"
				"else"
				"{"
					"str+='<span>|&lt;</span>';"
					"str+='<span>&lt;&lt;</span>';"
				"}"
			"}"
			"for(var i=self._start;i<=self._end;i++)"
			"{"
				"if(i==this.index)"
				"{"
					"if(i<10)str+='<span class=\"on\">'+'0'+i+\"</span>\";"
					"else str+='<span class=\"on\">'+i+\"</span>\";"
				"}"
				"else"
				"{"
					"if(i<10)str+='<a href=\"javascript://'+i+'\"><span>'+'0'+i+\"</span></a>\";"
					"else str+='<a href=\"javascript://'+i+'\"><span>'+i+\"</span></a>\";"
				"}"
			"}"
			"if(self._pageCount>1)"
			"{"
				"if(self.index!=self._pageCount)"
				"{"
					"str+='<a href=\"javascript://'+(self.index+1)+'\"><span>&gt;&gt;</span></a>';"
					"str+='<a href=\"javascript://'+self._pageCount+'\"><span>&gt;|</span></a>';"
				"}"
				"else"
				"{"
					"str+='<span>&gt;&gt;</span>';"
					"str+='<span>&gt;|</span>';"
				"}"
			"}"
			"str+=AAA+self._pageCount+BBB+self.itemCount+CCC;"
			"str+='</div><!--/.pagerView-->\\n';"
			"self.container.innerHTML=str;"
			"var a_list=self.container.getElementsByTagName('a');"
			"for(var i=0;i<a_list.length;i++)"
			"{"
				"a_list[i].onclick=function()"
				"{"
					"var index=this.getAttribute('href');"
					"if(index!=undefined&&index!='')"
					"{"
						"index=parseInt(index.replace('javascript://',''));"
						"self._onclick(index);"
					"}"
					"return false;"
				"};"
			"}"
		"};"
	"};"
// 	"var gMonths=new Array('01','02','03','04','05','06','07','08','09','10','11','12');"
// 	"var cn_WeekDay=new Array('日','一','二','三','四','五','六');"
// 	"var en_WeekDay=new Array('Sun','Mon','Tue','Wed','Thu','Fri','Sat');"
// 	"var cn_strToday='今天';"
// 	"var en_strToday='Today';"
// 	"var strYear='-';"
// 	"var strMonth='-';"
// 	"var strDay='';"
// 	"var splitChar='-';"
// 	"var startYear=2000;"
// 	"var endYear=2100;"
// 	"var dayTdHeight=12;"
// 	"var dayTdTextSize=12;"
// 	"var gcNotCurMonth='#BBB';"
// 	"var gcRestDay='#F00';"
// 	"var gcWorkDay='#000';"
// 	"var gcMouseOver='#007B3E';"
// 	"var gcMouseOut='#F4F4F4';"
// 	"var gcToday='#FFFFFF';"
// 	"var gcTodayMouseOver='#F58E03';"
// 	"var gcTodayMouseOut='#79D0FF';"
// 	"var gdCtrl=new Object();"
// 	"var goSelectTag=new Array();"
// 	"var gdCurDate=new Date();"
// 	"var giYear=gdCurDate.getFullYear();"
// 	"var giMonth=gdCurDate.getMonth()+1;"
// 	"var giDay=gdCurDate.getDate();"
// 	"function $A()"
// 	"{"
// 		"var elements=new Array();"
// 		"for(var i=0;i<arguments.length;i++)"
// 		"{"
// 			"var element=arguments[i];"
// 			"if(typeof(arguments[i])=='string')"
// 			"{"
// 				"element=document.getElementById(arguments[i]);"
// 			"}"
// 			"if(arguments.length==1)"
// 			"{"
// 				"return element;"
// 			"}"
// 			"elements.Push(element);"
// 		"}"
// 		"return elements;"
// 	"}"
// 	"Array.prototype.Push=function()"
// 	"{"
// 		"var startLength=this.length;"
// 		"for(var i=0;i<arguments.length;i++)"
// 		"{"
// 			"this[startLength+i]=arguments[i];"
// 		"}"
// 		"return this.length;"
// 	"};"
// 	"String.prototype.HexToDec=function()"
// 	"{"
// 		"return parseInt(this,16);"
// 	"};"
// 	"String.prototype.cleanBlank=function()"
// 	"{"
// 		"return this.isEmpty()?\"\":this.replace(/\\s/g,\"\");"
// 	"};"
// 	"function checkColor()"
// 	"{"
// 		"var color_tmp=(arguments[0]+\"\").replace(/\\s/g,\"\").toUpperCase();"
// 		"var model_tmp1=arguments[1].toUpperCase();"
// 		"var model_tmp2=\"rgb(\"+arguments[1].substring(1,3).HexToDec()+\",\"+arguments[1].substring(1,3).HexToDec()+\",\"+arguments[1].substring(5).HexToDec()+\")\";"
// 		"model_tmp2=model_tmp2.toUpperCase();"
// 		"if(color_tmp==model_tmp1 ||color_tmp==model_tmp2)"
// 		"{"
// 			"return true;"
// 		"}"
// 		"return false;"
// 	"}"
// 	"function $V()"
// 	"{"
// 		"return $A(arguments[0]).value;"
// 	"}"
// 	"function fPopCalendar(evt,popCtrl,dateCtrl)"
// 	"{"
// 		"evt.cancelBubble=true;"
// 		"gdCtrl=dateCtrl;"
// 		"fSetYearMon(giYear,giMonth);"
// 		"var point=fGetXY(popCtrl);"
// 		"with($A(\"calendardiv\").style)"
// 		"{"
// 			"left=point.x+'px';"
// 			"top=(point.y+popCtrl.offsetHeight+1)+'px';"
// 			"visibility='visible';zindex='99';"
// 			"position='absolute';"
// 		"}"
// 		"$A('calendardiv').focus();"
// 	"}"
// 	"function fSetDate(iYear,iMonth,iDay)"
// 	"{"
// 		"var iMonthNew=new String(iMonth);"
// 		"var iDayNew=new String(iDay);"
// 		"if(iMonthNew.length<2)"
// 		"{"
// 			"iMonthNew='0'+iMonthNew;"
// 		"}"
// 		"if(iDayNew.length<2)"
// 		"{"
// 			"iDayNew='0'+iDayNew;"
// 		"}"
// 		"gdCtrl.value=iYear+splitChar+iMonthNew+splitChar+iDayNew;"
// 		"fHideCalendar();"
// 	"}"
// 	"function fHideCalendar()"
// 	"{"
// 		"$A('calendardiv').style.visibility='hidden';"
// 		"for(var i=0;i<goSelectTag.length;i++)"
// 		"{"
// 			"goSelectTag[i].style.visibility='visible';"
// 		"}"
// 		"goSelectTag.length=0;"
// 	"}"
// 	"function fSetSelected()"
// 	"{"
// 		"var iOffset=0;"
// 		"var iYear=parseInt($A('tbSelYear').value);"
// 		"var iMonth=parseInt($A('tbSelMonth').value);"
// 		"var aCell=$A('cellText'+arguments[0]);"
// 		"aCell.bgColor=gcMouseOut;"
// 		"with(aCell)"
// 		"{"
// 			"var iDay=parseInt(innerHTML);"
// 			"if(checkColor(style.color,gcNotCurMonth))"
// 			"{"
// 				"iOffset=(innerHTML>10)?-1:1;"
// 			"}"
// 			"iMonth+=iOffset;"
// 			"if(iMonth<1)"
// 			"{"
// 				"iYear--;"
// 				"iMonth=12;"
// 			"}"
// 			"else if(iMonth>12)"
// 			"{"
// 				"iYear++;"
// 				"iMonth=1;"
// 			"}"
// 		"}"
// 		"fSetDate(iYear,iMonth,iDay);"
// 	"}"
// 	"function Point(iX,iY)"
// 	"{"
// 		"this.x=iX;"
// 		"this.y=iY;"
// 	"}"
// 	"function fBuildCal(iYear,iMonth)"
// 	"{"
// 		"var aMonth=new Array();"
// 		"for(var i=1;i<7;i++)"
// 		"{"
// 			"aMonth[i]=new Array(i);"
// 		"}"
// 		"var dCalDate=new Date(iYear,iMonth-1,1);"
// 		"var iDayOfFirst=dCalDate.getDay();"
// 		"var iDaysInMonth=new Date(iYear,iMonth,0).getDate();"
// 		"var iOffsetLast=new Date(iYear,iMonth-1,0).getDate()-iDayOfFirst+1;"
// 		"var iDate=1;"
// 		"var iNext=1;"
// 		"for(var d=0;d<7;d++)"
// 		"{"
// 			"aMonth[1][d]=(d<iDayOfFirst)?(iOffsetLast+d)*(-1):iDate++;"
// 		"}"
// 		"for(var w=2;w<7;w++)"
// 		"{"
// 			"for(var d=0;d<7;d++)"
// 			"{"
// 				"aMonth[w][d]=(iDate<=iDaysInMonth)?iDate++:(iNext++)*(-1);"
// 			"}"
// 		"}"
// 		"return aMonth;"
// 	"}"
// 	"function fDrawCal(iYear,iMonth,iCellHeight,iDateTextSize,cn_en_WeekDay)"
// 	"{"
// 		"var colorTD=\" bgcolor='\"+gcMouseOut+\"' bordercolor='\"+gcMouseOut+\"'\";"
// 		"var styleTD=\" valign='middle' align='center' style='height:\"+iCellHeight+\"px;font-weight:bolder;font-size:\"+iDateTextSize+\"px;\";"
// 		"var dateCal='';"
// 		"dateCal+='<tr>';"
// 		"for(var i=0;i<7;i++)"
// 		"{"
// 			"dateCal+=\"<td\"+colorTD+styleTD+\"color:#990099'>\"+cn_en_WeekDay[i]+\"</td>\";"
// 		"}"
// 		"dateCal+='</tr>';"
// 		"for(var w=1;w<7;w++)"
// 		"{"
// 			"dateCal+='<tr>';"
// 			"for(var d=0;d<7;d++)"
// 			"{"
// 				"var tmpid=w+\"\"+d;dateCal+=\"<td\"+styleTD+\"cursor:pointer;' onclick='fSetSelected(\"+tmpid+\")'>\";"
// 				"dateCal+=\"<span id='cellText\"+tmpid+\"'></span>\";dateCal+=\"</td>\";"
// 			"}"
// 			"dateCal+='</tr>';"
// 		"}"
// 		"return dateCal;"
// 	"}"
// 	"function fUpdateCal(iYear,iMonth)"
// 	"{"
// 		"var myMonth=fBuildCal(iYear,iMonth);"
// 		"var i=0;"
// 		"for(var w=1;w<7;w++)"
// 		"{"
// 			"for(var d=0;d<7;d++)"
// 			"{"
// 				"with($A('cellText'+w+''+d))"
// 				"{"
// 					"parentNode.bgColor=gcMouseOut;"
// 					"parentNode.borderColor=gcMouseOut;"
// 					"parentNode.onmouseover=function()"
// 					"{"
// 						"this.bgColor=gcMouseOver;"
// 					"};"
// 					"parentNode.onmouseout=function()"
// 					"{"
// 						"this.bgColor=gcMouseOut;"
// 					"};"
// 					"if(myMonth[w][d]<0)"
// 					"{"
// 						"style.color=gcNotCurMonth;"
// 						"innerHTML=Math.abs(myMonth[w][d]);"
// 					"}"
// 					"else"
// 					"{"
// 						"style.color=((d==0)||(d==6))?gcRestDay:gcWorkDay;"
// 						"innerHTML=myMonth[w][d];"
// 						"if(iYear==giYear&&iMonth==giMonth&&myMonth[w][d]==giDay)"
// 						"{"
// 							"style.color=gcToday;parentNode.bgColor=gcTodayMouseOut;"
// 							"parentNode.onmouseover=function()"
// 							"{"
// 								"this.bgColor=gcTodayMouseOver;"
// 							"};"
// 							"parentNode.onmouseout=function()"
// 							"{"
// 								"this.bgColor=gcTodayMouseOut;"
// 							"};"
// 						"}"
// 					"}"
// 				"}"
// 			"}"
// 		"}"
// 	"}"
// 	"function fSetYearMon(iYear,iMon)"
// 	"{"
// 		"$A('tbSelMonth').options[iMon-1].selected=true;"
// 		"for(var i=0;i<$A('tbSelYear').length;i++)"
// 		"{"
// 			"if($A('tbSelYear').options[i].value==iYear)"
// 			"{"
// 				"$A('tbSelYear').options[i].selected=true;"
// 			"}"
// 		"}"
// 		"fUpdateCal(iYear,iMon);"
// 	"}"
// 	"function fPrevMonth()"
// 	"{"
// 		"var iMon=$A('tbSelMonth').value;"
// 		"var iYear=$A('tbSelYear').value;"
// 		"if(--iMon<1)"
// 		"{"
// 			"iMon=12;iYear--;"
// 		"}"
// 		"fSetYearMon(iYear,iMon);"
// 	"}"
// 	"function fNextMonth()"
// 	"{"
// 		"var iMon=$A('tbSelMonth').value;"
// 		"var iYear=$A('tbSelYear').value;"
// 		"if(++iMon>12)"
// 		"{"
// 			"iMon=1;iYear++;"
// 		"}"
// 		"fSetYearMon(iYear,iMon);"
// 	"}"
// 	"function fGetXY(aTag)"
// 	"{"
// 		"var oTmp=aTag;"
// 		"var pt=new Point(0,0);"
// 		"do"
// 		"{"
// 			"pt.x+=oTmp.offsetLeft;"
// 			"pt.y+=oTmp.offsetTop;"
// 			"oTmp=oTmp.offsetParent;"
// 		"}"
// 		"while(oTmp.tagName.toUpperCase()!='BODY');"
// 		"return pt;"
// 	"}"
// 	"function getDateDiv(cn_en_WeekDay,cn_en_strToday)"
// 	"{"
// 		"var noSelectForIE='';"
// 		"var noSelectForFireFox='';"
// 		"if(document.all)"
// 		"{"
// 			"noSelectForIE=\"onselectstart='return false;'\";"
// 		"}"
// 		"else"
// 		"{"
// 			"noSelectForFireFox=\"-moz-user-select:none;\";"
// 		"}"
// 		"var dateDiv='';"
// 		"dateDiv+=\"<div id='calendardiv' onclick='event.cancelBubble=true' \"+noSelectForIE+\" style='\"+noSelectForFireFox+\"position:absolute;z-index:99;visibility:hidden;border:1px solid #999999;'>\";"
// 		"dateDiv+=\"<table border='0' bgcolor='#E0E0E0' cellpadding='1' cellspacing='1' >\";"
// 		"dateDiv+=\"<tr>\";"
// 		"dateDiv+=\"<td><input type='button' id='PrevMonth' value='<' style='height:20px;width:20px;font-weight:bolder;' onclick='fPrevMonth()'>\";"
// 		"dateDiv+=\"</td><td><select id='tbSelYear' onchange='fUpdateCal($V(\\\"tbSelYear\\\"),$V(\\\"tbSelMonth\\\"))'>\";"
// 		"for(var i=startYear;i<endYear;i++)"
// 		"{"
// 			"dateDiv+=\"<option value='\"+i+\"'>\"+i+\"</option>\";"
// 		"}"
// 		"dateDiv+=\"</select></td><td>\";"
// 		"dateDiv+=\"<select id='tbSelMonth' onchange='fUpdateCal($V(\\\"tbSelYear\\\"),$V(\\\"tbSelMonth\\\"))'>\";"
// 		"for(var i=0;i<12;i++)"
// 		"{"
// 			"dateDiv+=\"<option value='\"+(i+1)+\"'>\"+gMonths[i]+\"</option>\";"
// 		"}"
// 		"dateDiv+=\"</select></td><td>\";"
// 		"dateDiv+=\"<input type='button' id='NextMonth' value='>' style='height:20px;width:20px;font-weight:bolder;' onclick='fNextMonth()'>\";"
// 		"dateDiv+=\"</td>\";"
// 		"dateDiv+=\"</tr><tr>\";"
// 		"dateDiv+=\"<td align='center' colspan='4'>\";"
// 		"dateDiv+=\"<div style='background-color:#cccccc'><table width='100%' border='0' cellpadding='3' cellspacing='1'>\";"
// 		"dateDiv+=fDrawCal(giYear,giMonth,dayTdHeight,dayTdTextSize,cn_en_WeekDay);"
// 		"dateDiv+=\"</table></div>\";"
// 		"dateDiv+=\"</td>\";"
// 		"dateDiv+=\"</tr><tr><td align='center' colspan='4' nowrap>\";"
// 		"dateDiv+=\"<span style='cursor:pointer;font-weight:bolder;' onclick='fSetDate(giYear,giMonth,giDay)' onmouseover='this.style.color=\\\"\"+gcMouseOver+\"\\\"' onmouseout='this.style.color=\\\"#000000\\\"'>\"+cn_en_strToday+\":\"+giYear+strYear+giMonth+strMonth+giDay+\"</span>\";"
// 		"dateDiv+=\"</tr></tr>\";dateDiv+=\"</table></div>\";"
// 		"return dateDiv;"
// 	"}"
};
#endif
