#ifndef _J_002_H_
#define _J_002_H_
static const char j_002[]={
"HTTP/1.1 200 OK\r\nContent-Type:text/javascript\r\nAccept-Ranges:bytes\r\n\r\n"
 "var OBJ=function(o){return document.getElementById(o);};\n"
 "function show_tip(obj){OBJ('tip').innerHTML=obj;}\n"
 "function show_nbsp(){OBJ('tip').innerHTML='&nbsp;';}\n"
 "function lang_init(loop){for(var i=1;i<=loop;i++)eval('OBJ(\\'N'+(i<10?'0'+i:i)+'\\').innerHTML=lang.N'+(i<10?'0'+i:i)+'[language];');}\n"
 "var FromMobileDevice=false;\n"
 "function FromWhichDevice()\n"
 "{\n"
 	"var sUserAgent=navigator.userAgent.toLowerCase();\n"
 	"var Ipad=sUserAgent.match(/ipad/i)=='ipad';\n"
 	"var IphoneOs=sUserAgent.match(/iphone os/i)=='iphone os';\n"
 	"var Android=sUserAgent.match(/android/i)=='android';\n"
 	"var WindowsPhone=sUserAgent.match(/windows phone/i)=='windows phone';\n"
 	"if(Ipad||IphoneOs||Android||WindowsPhone)FromMobileDevice=true;\n"
 	"else FromMobileDevice=false;\n"
 "}\n"
 "function show_T(tid)\n"
 "{\n"
 	"var str='';\n"
 	"str+=\"<div class='title'><div class='r1 color'></div><div class='r2 color'></div><div class='r3 color'></div><div class='r4 color'></div>\";\n"
 	"str+=\"<div class='content color'><span id='\"+tid+\"'></span></div>\";\n"
 	"str+=\"<div class='r4 color'></div><div class='r3 color'></div><div class='r2 color'></div><div class='r1 color'></div></div><div class='blank'></div>\";\n"
 	"document.write(str);\n"
 "}\n"
 "function show_sT(tid)\n"
 "{\n"
 	"var str='';\n"
 	"str+=\"<div class='title'><div class='subtitle'><div class='r1 subcolor'></div><div class='r2 subcolor'></div><div class='r3 subcolor'></div><div class='r4 subcolor'></div>\";\n"
 	"str+=\"<div class='content subcolor subcontent'><span id='\"+tid+\"'></span></div>\";\n"
 	"str+=\"<div class='r4 subcolor'></div><div class='r3 subcolor'></div><div class='r2 subcolor'></div><div class='r1 subcolor'></div></div><div class='line_short'></div></div>\";\n"
 	"document.write(str);\n"
 "}\n"
 "function SelectYear()\n"
 "{\n"
 	"for(i=2000;i<=2099;i++)\n"
 	"{\n"
 		"document.write('<option value=\\''+i+'\\'>'+i+'</option>');\n"
 	"}\n"
 "}\n"
 "function SelectMonth()\n"
 "{\n"
 	"for(i=1;i<=12;i++)\n"
 	"{\n"
 		"if(i<10)document.write('<option value=\\''+i+'\\'>0'+i+'</option>');\n"
 		"else document.write('<option value=\\''+i+'\\'>'+i+'</option>');\n"
 	"}\n"
 "}\n"
 "function CheckDay(Y,M,D)\n"
 "{\n"
 	"var YearNo,MonthNo,DayNo;\n"
 	"try\n"
 	"{\n"
 		"YearNo=OBJ(Y).value;\n"
 		"MonthNo=OBJ(M).value;\n"
 	"}\n"
 	"catch(e)\n"
 	"{\n"
 		"var datenow=new Date();\n"
 		"YearNo=datenow.getFullYear();\n"
 		"MonthNo=datenow.getMonth()+1;\n"
 	"}\n"
 	"var i,DayCount;\n"
 	"if(MonthNo==1||MonthNo==3||MonthNo==5||MonthNo==7||MonthNo==8||MonthNo==10||MonthNo==12)\n"
 	"{\n"
 		"DayCount=31;\n"
 	"}\n"
 	"if(MonthNo==4||MonthNo==6||MonthNo==9||MonthNo==11 )\n"
 	"{\n"
 		"DayCount=30;\n"
 	"}\n"
 	"if(MonthNo==2)\n"
 	"{\n"
 		"if(IsRunY(YearNo))\n"
 		"{\n"
 			"DayCount=29;\n"
 		"}\n"
 		"else\n"
 		"{\n"
 			"DayCount=28;\n"
 		"}\n"
 	"}\n"
 	"OBJ(D).length=DayCount;\n"
 	"var currentDay=new Date().getDate();\n"
 	"for(i=0;i<DayCount;i++)\n"
 	"{\n"
 		"OBJ(D)[i]=new Option(i+1);\n"
 		"OBJ(D)[i].value=i+1;\n"
 		"OBJ(D)[i].innerHTML=i<9?'0'+(i+1):(i+1);\n"
 		"if(currentDay==(i+1))\n"
 		"OBJ(D)[i].selected=true;\n"
 	"}\n"
 "}\n"
 "function IsRunY(YearNo)\n"
 "{\n"
 	"if((YearNo%4==0&&YearNo%100!=0)||YearNo%400==0)return true;\n"
 	"else return false;\n"
 "}\n"
 "var PagerView=function(id,AAA,BBB,CCC)\n"
 "{\n"
 	"var self=this;\n"
 	"this.id=id;\n"
 	"this._pageCount=0;\n"
 	"this._start=1;\n"
 	"this._end=1;\n"
 	"this.container=null;\n"
 	"this.index=1;\n"
 	"this.size=10;\n"
 	"this.maxButtons=10;\n"
 	"this.itemCount=0;\n"
 	"this.onclick=function(index){return true;};\n"
 	"this._onclick=function(index)\n"
 	"{\n"
 		"var old=self.index;\n"
 		"self.index=index;\n"
 		"if(self.onclick(index)!==false)self.render();\n"
 		"else self.index=old;\n"
 	"};\n"
 	"this._calculate=function()\n"
 	"{\n"
 		"self._pageCount=parseInt(Math.ceil(self.itemCount/self.size));\n"
 		"self.index=parseInt(self.index);\n"
 		"if(self.index>self._pageCount)self.index=self._pageCount;\n"
 		"if(self.index<1)self.index=1;\n"
 		"self._start=Math.max(1,self.index-parseInt(self.maxButtons/2));\n"
 		"self._end=Math.min(self._pageCount,self._start+self.maxButtons-1);\n"
 		"self._start=Math.max(1,self._end-self.maxButtons+1);\n"
 	"};\n"
 	"this.page=function(rows)\n"
 	"{\n"
 		"self._calculate();\n"
 		"var s_num=(self.index-1)*self.size ;\n"
 		"var e_num=self.index*self.size;\n"
 		"return rows.slice(s_num,e_num);\n"
 	"};\n"
 	"this.render=function()\n"
 	"{\n"
 		"var div=document.getElementById(self.id);\n"
 		"div.view=self;\n"
 		"self.container=div;\n"
 		"self._calculate();\n"
 		"var str='';\n"
 		"str+='<div class=\"PagerView\">\\n';\n"
 		"if(self._pageCount>1)\n"
 		"{\n"
 			"if(self.index!=1)\n"
 			"{\n"
 				"str+='<a href=\"javascript://1\"><span>|&lt;</span></a>';\n"
 				"str+='<a href=\"javascript://'+(self.index-1)+'\"><span>&lt;&lt;</span></a>';\n"
 			"}\n"
 			"else\n"
 			"{\n"
 				"str+='<span>|&lt;</span>';\n"
 				"str+='<span>&lt;&lt;</span>';\n"
 			"}\n"
 		"}\n"
 		"for(var i=self._start;i<=self._end;i++)\n"
 		"{\n"
 			"if(i==this.index)\n"
 			"{\n"
 				"if(i<10)str+='<span class=\"on\">'+'0'+i+\"</span>\";\n"
 				"else str+='<span class=\"on\">'+i+\"</span>\";\n"
 			"}\n"
 			"else\n"
 			"{\n"
 				"if(i<10)str+='<a href=\"javascript://'+i+'\"><span>'+'0'+i+\"</span></a>\";\n"
 				"else str+='<a href=\"javascript://'+i+'\"><span>'+i+\"</span></a>\";\n"
 			"}\n"
 		"}\n"
 		"if(self._pageCount>1)\n"
 		"{\n"
 			"if(self.index!=self._pageCount)\n"
 			"{\n"
 				"str+='<a href=\"javascript://'+(self.index+1)+'\"><span>&gt;&gt;</span></a>';\n"
 				"str+='<a href=\"javascript://'+self._pageCount+'\"><span>&gt;|</span></a>';\n"
 			"}\n"
 			"else\n"
 			"{\n"
 				"str+='<span>&gt;&gt;</span>';\n"
 				"str+='<span>&gt;|</span>';\n"
 			"}\n"
 		"}\n"
 		"str+=AAA+self._pageCount+BBB+self.itemCount+CCC;\n"
 		"str+='</div><!--/.pagerView-->\\n';\n"
 		"self.container.innerHTML=str;\n"
 		"var a_list=self.container.getElementsByTagName('a');\n"
 		"for(var i=0;i<a_list.length;i++)\n"
 		"{\n"
 			"a_list[i].onclick=function()\n"
 			"{\n"
 				"var index=this.getAttribute('href');\n"
 				"if(index!=undefined&&index!='')\n"
 				"{\n"
 					"index=parseInt(index.replace('javascript://',''));\n"
 					"self._onclick(index);\n"
 				"}\n"
 				"return false;\n"
 			"};\n"
 		"}\n"
 	"};\n"
 "};\n"
 "\n"
};
#endif
