#ifndef _J_006_H_
#define _J_006_H_

#if Web_RunTime_Debug==1
static const char j_006[]={
"HTTP/1.1 200 OK\r\nContent-Type:text/javascript\r\nAccept-Ranges:bytes\r\n\r\n"
"if (!document.createElement(\"canvas\").getContext) { (function() {\n"
        "var ab = Math;\n"
        "var n = ab.round;\n"
        "var l = ab.sin;\n"
        "var A = ab.cos;\n"
        "var H = ab.abs;\n"
        "var N = ab.sqrt;\n"
        "var d = 10;\n"
        "var f = d / 2;\n"
        "var z = +navigator.userAgent.match(/MSIE ([\\d.]+)?/)[1];\n"
        "function y() {\n"
            "return this.context_ || (this.context_ = new D(this))\n"
        "}\n"
        "var t = Array.prototype.slice;\n"
        "function g(j, m, p) {\n"
            "var i = t.call(arguments, 2);\n"
            "return function() {\n"
                "return j.apply(m, i.concat(t.call(arguments)))\n"
            "}\n"
        "}\n"
        "function af(i) {\n"
            "return String(i).replace(/&/g, \"&amp;\").replace(/\"/g, \"&quot;\")\n"
        "}\n"
        "function Y(m, j, i) {\n"
            "if (!m.namespaces[j]) {\n"
                "m.namespaces.add(j, i, \"#default#VML\")\n"
            "}\n"
        "}\n"
        "function R(j) {\n"
            "Y(j, \"g_vml_\", \"urn:schemas-microsoft-com:vml\");\n"
            "Y(j, \"g_o_\", \"urn:schemas-microsoft-com:office:office\");\n"
            "if (!j.styleSheets.ex_canvas_) {\n"
                "var i = j.createStyleSheet();\n"
                "i.owningElement.id = \"ex_canvas_\";\n"
                "i.cssText = \"canvas{display:inline-block;overflow:hidden;text-align:left;width:300px;height:150px}\"\n"
            "}\n"
        "}\n"
        "R(document);\n"
        "var e = {\n"
            "init: function(i) {\n"
                "var j = i || document;\n"
                "j.createElement(\"canvas\");\n"
                "j.attachEvent(\"onreadystatechange\", g(this.init_, this, j))\n"
            "},\n"
            "init_: function(p) {\n"
                "var m = p.getElementsByTagName(\"canvas\");\n"
                "for (var j = 0; j < m.length; j++) {\n"
                    "this.initElement(m[j])\n"
                "}\n"
            "},\n"
            "initElement: function(j) {\n"
                "if (!j.getContext) {\n"
                    "j.getContext = y;\n"
                    "R(j.ownerDocument);\n"
                    "j.innerHTML = \"\";\n"
                    "j.attachEvent(\"onpropertychange\", x);\n"
                    "j.attachEvent(\"onresize\", W);\n"
                    "var i = j.attributes;\n"
                    "if (i.width && i.width.specified) {\n"
                        "j.style.width = i.width.nodeValue + \"px\"\n"
                    "} else {\n"
                        "j.width = j.clientWidth\n"
                    "}\n"
                    "if (i.height && i.height.specified) {\n"
                        "j.style.height = i.height.nodeValue + \"px\"\n"
                    "} else {\n"
                        "j.height = j.clientHeight\n"
                    "}\n"
                "}\n"
                "return j\n"
            "}\n"
        "};\n"
        "function x(j) {\n"
            "var i = j.srcElement;\n"
            "switch (j.propertyName) {\n"
            "case \"width\":\n"
                "i.getContext().clearRect();\n"
                "i.style.width = i.attributes.width.nodeValue + \"px\";\n"
                "i.firstChild.style.width = i.clientWidth + \"px\";\n"
                "break;\n"
            "case \"height\":\n"
                "i.getContext().clearRect();\n"
                "i.style.height = i.attributes.height.nodeValue + \"px\";\n"
                "i.firstChild.style.height = i.clientHeight + \"px\";\n"
                "break\n"
            "}\n"
        "}\n"
        "function W(j) {\n"
            "var i = j.srcElement;\n"
            "if (i.firstChild) {\n"
                "i.firstChild.style.width = i.clientWidth + \"px\";\n"
                "i.firstChild.style.height = i.clientHeight + \"px\"\n"
            "}\n"
        "}\n"
        "e.init();\n"
        "var k = [];\n"
        "for (var ae = 0; ae < 16; ae++) {\n"
            "for (var ad = 0; ad < 16; ad++) {\n"
                "k[ae * 16 + ad] = ae.toString(16) + ad.toString(16)\n"
            "}\n"
        "}\n"
        "function B() {\n"
            "return [[1, 0, 0], [0, 1, 0], [0, 0, 1]]\n"
        "}\n"
        "function J(p, m) {\n"
            "var j = B();\n"
            "for (var i = 0; i < 3; i++) {\n"
                "for (var ah = 0; ah < 3; ah++) {\n"
                    "var Z = 0;\n"
                    "for (var ag = 0; ag < 3; ag++) {\n"
                        "Z += p[i][ag] * m[ag][ah]\n"
                    "}\n"
                    "j[i][ah] = Z\n"
                "}\n"
            "}\n"
            "return j\n"
        "}\n"
        "function v(j, i) {\n"
            "i.fillStyle = j.fillStyle;\n"
            "i.lineCap = j.lineCap;\n"
            "i.lineJoin = j.lineJoin;\n"
            "i.lineWidth = j.lineWidth;\n"
            "i.miterLimit = j.miterLimit;\n"
            "i.shadowBlur = j.shadowBlur;\n"
            "i.shadowColor = j.shadowColor;\n"
            "i.shadowOffsetX = j.shadowOffsetX;\n"
            "i.shadowOffsetY = j.shadowOffsetY;\n"
            "i.strokeStyle = j.strokeStyle;\n"
            "i.globalAlpha = j.globalAlpha;\n"
            "i.font = j.font;\n"
            "i.textAlign = j.textAlign;\n"
            "i.textBaseline = j.textBaseline;\n"
            "i.arcScaleX_ = j.arcScaleX_;\n"
            "i.arcScaleY_ = j.arcScaleY_;\n"
            "i.lineScale_ = j.lineScale_\n"
        "}\n"
        "var b = {\n"
            "aliceblue: \"#F0F8FF\",\n"
            "antiquewhite: \"#FAEBD7\",\n"
            "aquamarine: \"#7FFFD4\",\n"
            "azure: \"#F0FFFF\",\n"
            "beige: \"#F5F5DC\",\n"
            "bisque: \"#FFE4C4\",\n"
            "black: \"#000000\",\n"
            "blanchedalmond: \"#FFEBCD\",\n"
            "blueviolet: \"#8A2BE2\",\n"
            "brown: \"#A52A2A\",\n"
            "burlywood: \"#DEB887\",\n"
            "cadetblue: \"#5F9EA0\",\n"
            "chartreuse: \"#7FFF00\",\n"
            "chocolate: \"#D2691E\",\n"
            "coral: \"#FF7F50\",\n"
            "cornflowerblue: \"#6495ED\",\n"
            "cornsilk: \"#FFF8DC\",\n"
            "crimson: \"#DC143C\",\n"
            "cyan: \"#00FFFF\",\n"
            "darkblue: \"#00008B\",\n"
            "darkcyan: \"#008B8B\",\n"
            "darkgoldenrod: \"#B8860B\",\n"
            "darkgray: \"#A9A9A9\",\n"
            "darkgreen: \"#006400\",\n"
            "darkgrey: \"#A9A9A9\",\n"
            "darkkhaki: \"#BDB76B\",\n"
            "darkmagenta: \"#8B008B\",\n"
            "darkolivegreen: \"#556B2F\",\n"
            "darkorange: \"#FF8C00\",\n"
            "darkorchid: \"#9932CC\",\n"
            "darkred: \"#8B0000\",\n"
            "darksalmon: \"#E9967A\",\n"
            "darkseagreen: \"#8FBC8F\",\n"
            "darkslateblue: \"#483D8B\",\n"
            "darkslategray: \"#2F4F4F\",\n"
            "darkslategrey: \"#2F4F4F\",\n"
            "darkturquoise: \"#00CED1\",\n"
            "darkviolet: \"#9400D3\",\n"
            "deeppink: \"#FF1493\",\n"
            "deepskyblue: \"#00BFFF\",\n"
            "dimgray: \"#696969\",\n"
            "dimgrey: \"#696969\",\n"
            "dodgerblue: \"#1E90FF\",\n"
            "firebrick: \"#B22222\",\n"
            "floralwhite: \"#FFFAF0\",\n"
            "forestgreen: \"#228B22\",\n"
            "gainsboro: \"#DCDCDC\",\n"
            "ghostwhite: \"#F8F8FF\",\n"
            "gold: \"#FFD700\",\n"
            "goldenrod: \"#DAA520\",\n"
            "grey: \"#808080\",\n"
            "greenyellow: \"#ADFF2F\",\n"
            "honeydew: \"#F0FFF0\",\n"
            "hotpink: \"#FF69B4\",\n"
            "indianred: \"#CD5C5C\",\n"
            "indigo: \"#4B0082\",\n"
            "ivory: \"#FFFFF0\",\n"
            "khaki: \"#F0E68C\",\n"
            "lavender: \"#E6E6FA\",\n"
            "lavenderblush: \"#FFF0F5\",\n"
            "lawngreen: \"#7CFC00\",\n"
            "lemonchiffon: \"#FFFACD\",\n"
            "lightblue: \"#ADD8E6\",\n"
            "lightcoral: \"#F08080\",\n"
            "lightcyan: \"#E0FFFF\",\n"
            "lightgoldenrodyellow: \"#FAFAD2\",\n"
            "lightgreen: \"#90EE90\",\n"
            "lightgrey: \"#D3D3D3\",\n"
            "lightpink: \"#FFB6C1\",\n"
            "lightsalmon: \"#FFA07A\",\n"
            "lightseagreen: \"#20B2AA\",\n"
            "lightskyblue: \"#87CEFA\",\n"
            "lightslategray: \"#778899\",\n"
            "lightslategrey: \"#778899\",\n"
            "lightsteelblue: \"#B0C4DE\",\n"
            "lightyellow: \"#FFFFE0\",\n"
            "limegreen: \"#32CD32\",\n"
            "linen: \"#FAF0E6\",\n"
            "magenta: \"#FF00FF\",\n"
            "mediumaquamarine: \"#66CDAA\",\n"
            "mediumblue: \"#0000CD\",\n"
            "mediumorchid: \"#BA55D3\",\n"
            "mediumpurple: \"#9370DB\",\n"
            "mediumseagreen: \"#3CB371\",\n"
            "mediumslateblue: \"#7B68EE\",\n"
            "mediumspringgreen: \"#00FA9A\",\n"
            "mediumturquoise: \"#48D1CC\",\n"
            "mediumvioletred: \"#C71585\",\n"
            "midnightblue: \"#191970\",\n"
            "mintcream: \"#F5FFFA\",\n"
            "mistyrose: \"#FFE4E1\",\n"
            "moccasin: \"#FFE4B5\",\n"
            "navajowhite: \"#FFDEAD\",\n"
            "oldlace: \"#FDF5E6\",\n"
            "olivedrab: \"#6B8E23\",\n"
            "orange: \"#FFA500\",\n"
            "orangered: \"#FF4500\",\n"
            "orchid: \"#DA70D6\",\n"
            "palegoldenrod: \"#EEE8AA\",\n"
            "palegreen: \"#98FB98\",\n"
            "paleturquoise: \"#AFEEEE\",\n"
            "palevioletred: \"#DB7093\",\n"
            "papayawhip: \"#FFEFD5\",\n"
            "peachpuff: \"#FFDAB9\",\n"
            "peru: \"#CD853F\",\n"
            "pink: \"#FFC0CB\",\n"
            "plum: \"#DDA0DD\",\n"
            "powderblue: \"#B0E0E6\",\n"
            "rosybrown: \"#BC8F8F\",\n"
            "royalblue: \"#4169E1\",\n"
            "saddlebrown: \"#8B4513\",\n"
            "salmon: \"#FA8072\",\n"
            "sandybrown: \"#F4A460\",\n"
            "seagreen: \"#2E8B57\",\n"
            "seashell: \"#FFF5EE\",\n"
            "sienna: \"#A0522D\",\n"
            "skyblue: \"#87CEEB\",\n"
            "slateblue: \"#6A5ACD\",\n"
            "slategray: \"#708090\",\n"
            "slategrey: \"#708090\",\n"
            "snow: \"#FFFAFA\",\n"
            "springgreen: \"#00FF7F\",\n"
            "steelblue: \"#4682B4\",\n"
            "tan: \"#D2B48C\",\n"
            "thistle: \"#D8BFD8\",\n"
            "tomato: \"#FF6347\",\n"
            "turquoise: \"#40E0D0\",\n"
            "violet: \"#EE82EE\",\n"
            "wheat: \"#F5DEB3\",\n"
            "whitesmoke: \"#F5F5F5\",\n"
            "yellowgreen: \"#9ACD32\"\n"
        "};\n"
        "function M(j) {\n"
            "var p = j.indexOf(\"(\", 3);\n"
            "var i = j.indexOf(\")\", p + 1);\n"
            "var m = j.substring(p + 1, i).split(\",\");\n"
            "if (m.length != 4 || j.charAt(3) != \"a\") {\n"
                "m[3] = 1\n"
            "}\n"
            "return m\n"
        "}\n"
        "function c(i) {\n"
            "return parseFloat(i) / 100\n"
        "}\n"
        "function r(j, m, i) {\n"
            "return Math.min(i, Math.max(m, j))\n"
        "}\n"
        "function I(ag) {\n"
            "var i, ai, aj, ah, ak, Z;\n"
            "ah = parseFloat(ag[0]) / 360 % 360;\n"
            "if (ah < 0) {\n"
                "ah++\n"
            "}\n"
            "ak = r(c(ag[1]), 0, 1);\n"
            "Z = r(c(ag[2]), 0, 1);\n"
            "if (ak == 0) {\n"
                "i = ai = aj = Z\n"
            "} else {\n"
                "var j = Z < 0.5 ? Z * (1 + ak) : Z + ak - Z * ak;\n"
                "var m = 2 * Z - j;\n"
                "i = a(m, j, ah + 1 / 3);\n"
                "ai = a(m, j, ah);\n"
                "aj = a(m, j, ah - 1 / 3)\n"
            "}\n"
            "return \"#\" + k[Math.floor(i * 255)] + k[Math.floor(ai * 255)] + k[Math.floor(aj * 255)]\n"
        "}\n"
        "function a(j, i, m) {\n"
            "if (m < 0) {\n"
                "m++\n"
            "}\n"
            "if (m > 1) {\n"
                "m--\n"
            "}\n"
            "if (6 * m < 1) {\n"
                "return j + (i - j) * 6 * m\n"
            "} else {\n"
                "if (2 * m < 1) {\n"
                    "return i\n"
                "} else {\n"
                    "if (3 * m < 2) {\n"
                        "return j + (i - j) * (2 / 3 - m) * 6\n"
                    "} else {\n"
                        "return j\n"
                    "}\n"
                "}\n"
            "}\n"
        "}\n"
        "var C = {};\n"
        "function F(j) {\n"
            "if (j in C) {\n"
                "return C[j]\n"
            "}\n"
            "var ag, Z = 1;\n"
            "j = String(j);\n"
            "if (j.charAt(0) == \"#\") {\n"
                "ag = j\n"
            "} else {\n"
                "if (/^rgb/.test(j)) {\n"
                    "var p = M(j);\n"
                    "var ag = \"#\",\n"
                    "ah;\n"
                    "for (var m = 0; m < 3; m++) {\n"
                        "if (p[m].indexOf(\"%\") != -1) {\n"
                            "ah = Math.floor(c(p[m]) * 255)\n"
                        "} else {\n"
                            "ah = +p[m]\n"
                        "}\n"
                        "ag += k[r(ah, 0, 255)]\n"
                    "}\n"
                    "Z = +p[3]\n"
                "} else {\n"
                    "if (/^hsl/.test(j)) {\n"
                        "var p = M(j);\n"
                        "ag = I(p);\n"
                        "Z = p[3]\n"
                    "} else {\n"
                        "ag = b[j] || j\n"
                    "}\n"
                "}\n"
            "}\n"
            "return C[j] = {\n"
                "color: ag,\n"
                "alpha: Z\n"
            "}\n"
        "}\n"
        "var o = {\n"
            "style: \"normal\",\n"
            "variant: \"normal\",\n"
            "weight: \"normal\",\n"
            "size: 10,\n"
            "family: \"sans-serif\"\n"
        "};\n"
        "var L = {};\n"
        "function E(i) {\n"
            "if (L[i]) {\n"
                "return L[i]\n"
            "}\n"
            "var p = document.createElement(\"div\");\n"
            "var m = p.style;\n"
            "try {\n"
                "m.font = i\n"
            "} catch(j) {}\n"
            "return L[i] = {\n"
                "style: m.fontStyle || o.style,\n"
                "variant: m.fontVariant || o.variant,\n"
                "weight: m.fontWeight || o.weight,\n"
                "size: m.fontSize || o.size,\n"
                "family: m.fontFamily || o.family\n"
            "}\n"
        "}\n"
        "function u(m, j) {\n"
            "var i = {};\n"
            "for (var ah in m) {\n"
                "i[ah] = m[ah]\n"
            "}\n"
            "var ag = parseFloat(j.currentStyle.fontSize),\n"
            "Z = parseFloat(m.size);\n"
            "if (typeof m.size == \"number\") {\n"
                "i.size = m.size\n"
            "} else {\n"
                "if (m.size.indexOf(\"px\") != -1) {\n"
                    "i.size = Z\n"
                "} else {\n"
                    "if (m.size.indexOf(\"em\") != -1) {\n"
                        "i.size = ag * Z\n"
                    "} else {\n"
                        "if (m.size.indexOf(\"%\") != -1) {\n"
                            "i.size = (ag / 100) * Z\n"
                        "} else {\n"
                            "if (m.size.indexOf(\"pt\") != -1) {\n"
                                "i.size = Z / 0.75\n"
                            "} else {\n"
                                "i.size = ag\n"
                            "}\n"
                        "}\n"
                    "}\n"
                "}\n"
            "}\n"
            "i.size *= 0.981;\n"
            "return i\n"
        "}\n"
        "function ac(i) {\n"
            "return i.style + \" \" + i.variant + \" \" + i.weight + \" \" + i.size + \"px \" + i.family\n"
        "}\n"
        "var s = {\n"
            "butt: \"flat\",\n"
            "round: \"round\"\n"
        "};\n"
        "function S(i) {\n"
            "return s[i] || \"square\"\n"
        "}\n"
        "function D(i) {\n"
            "this.m_ = B();\n"
            "this.mStack_ = [];\n"
            "this.aStack_ = [];\n"
            "this.currentPath_ = [];\n"
            "this.strokeStyle = \"#000\";\n"
            "this.fillStyle = \"#000\";\n"
            "this.lineWidth = 1;\n"
            "this.lineJoin = \"miter\";\n"
            "this.lineCap = \"butt\";\n"
            "this.miterLimit = d * 1;\n"
            "this.globalAlpha = 1;\n"
            "this.font = \"10px sans-serif\";\n"
            "this.textAlign = \"left\";\n"
            "this.textBaseline = \"alphabetic\";\n"
            "this.canvas = i;\n"
            "var m = \"width:\" + i.clientWidth + \"px;height:\" + i.clientHeight + \"px;overflow:hidden;position:absolute\";\n"
            "var j = i.ownerDocument.createElement(\"div\");\n"
            "j.style.cssText = m;\n"
            "i.appendChild(j);\n"
            "var p = j.cloneNode(false);\n"
            "p.style.backgroundColor = \"red\";\n"
            "p.style.filter = \"alpha(opacity=0)\";\n"
            "i.appendChild(p);\n"
            "this.element_ = j;\n"
            "this.arcScaleX_ = 1;\n"
            "this.arcScaleY_ = 1;\n"
            "this.lineScale_ = 1\n"
        "}\n"
        "var q = D.prototype;\n"
        "q.clearRect = function() {\n"
            "if (this.textMeasureEl_) {\n"
                "this.textMeasureEl_.removeNode(true);\n"
                "this.textMeasureEl_ = null\n"
            "}\n"
            "this.element_.innerHTML = \"\"\n"
        "};\n"
        "q.beginPath = function() {\n"
            "this.currentPath_ = []\n"
        "};\n"
        "q.moveTo = function(j, i) {\n"
            "var m = V(this, j, i);\n"
            "this.currentPath_.push({\n"
                "type: \"moveTo\",\n"
                "x: m.x,\n"
                "y: m.y\n"
            "});\n"
            "this.currentX_ = m.x;\n"
            "this.currentY_ = m.y\n"
        "};\n"
        "q.lineTo = function(j, i) {\n"
            "var m = V(this, j, i);\n"
            "this.currentPath_.push({\n"
                "type: \"lineTo\",\n"
                "x: m.x,\n"
                "y: m.y\n"
            "});\n"
            "this.currentX_ = m.x;\n"
            "this.currentY_ = m.y\n"
        "};\n"
        "q.bezierCurveTo = function(m, j, ak, aj, ai, ag) {\n"
            "var i = V(this, ai, ag);\n"
            "var ah = V(this, m, j);\n"
            "var Z = V(this, ak, aj);\n"
            "K(this, ah, Z, i)\n"
        "};\n"
        "function K(i, Z, m, j) {\n"
            "i.currentPath_.push({\n"
                "type: \"bezierCurveTo\",\n"
                "cp1x: Z.x,\n"
                "cp1y: Z.y,\n"
                "cp2x: m.x,\n"
                "cp2y: m.y,\n"
                "x: j.x,\n"
                "y: j.y\n"
            "});\n"
            "i.currentX_ = j.x;\n"
            "i.currentY_ = j.y\n"
        "}\n"
        "q.quadraticCurveTo = function(ai, m, j, i) {\n"
            "var ah = V(this, ai, m);\n"
            "var ag = V(this, j, i);\n"
            "var aj = {\n"
                "x: this.currentX_ + 2 / 3 * (ah.x - this.currentX_),\n"
                "y: this.currentY_ + 2 / 3 * (ah.y - this.currentY_)\n"
            "};\n"
            "var Z = {\n"
                "x: aj.x + (ag.x - this.currentX_) / 3,\n"
                "y: aj.y + (ag.y - this.currentY_) / 3\n"
            "};\n"
            "K(this, aj, Z, ag)\n"
        "};\n"
        "q.arc = function(al, aj, ak, ag, j, m) {\n"
            "ak *= d;\n"
            "var ap = m ? \"at\": \"wa\";\n"
            "var am = al + A(ag) * ak - f;\n"
            "var ao = aj + l(ag) * ak - f;\n"
            "var i = al + A(j) * ak - f;\n"
            "var an = aj + l(j) * ak - f;\n"
            "if (am == i && !m) {\n"
                "am += 0.125\n"
            "}\n"
            "var Z = V(this, al, aj);\n"
            "var ai = V(this, am, ao);\n"
            "var ah = V(this, i, an);\n"
            "this.currentPath_.push({\n"
                "type: ap,\n"
                "x: Z.x,\n"
                "y: Z.y,\n"
                "radius: ak,\n"
                "xStart: ai.x,\n"
                "yStart: ai.y,\n"
                "xEnd: ah.x,\n"
                "yEnd: ah.y\n"
            "})\n"
        "};\n"
        "q.rect = function(m, j, i, p) {\n"
            "this.moveTo(m, j);\n"
            "this.lineTo(m + i, j);\n"
            "this.lineTo(m + i, j + p);\n"
            "this.lineTo(m, j + p);\n"
            "this.closePath()\n"
        "};\n"
        "q.strokeRect = function(m, j, i, p) {\n"
            "var Z = this.currentPath_;\n"
            "this.beginPath();\n"
            "this.moveTo(m, j);\n"
            "this.lineTo(m + i, j);\n"
            "this.lineTo(m + i, j + p);\n"
            "this.lineTo(m, j + p);\n"
            "this.closePath();\n"
            "this.stroke();\n"
            "this.currentPath_ = Z\n"
        "};\n"
        "q.fillRect = function(m, j, i, p) {\n"
            "var Z = this.currentPath_;\n"
            "this.beginPath();\n"
            "this.moveTo(m, j);\n"
            "this.lineTo(m + i, j);\n"
            "this.lineTo(m + i, j + p);\n"
            "this.lineTo(m, j + p);\n"
            "this.closePath();\n"
            "this.fill();\n"
            "this.currentPath_ = Z\n"
        "};\n"
        "q.createLinearGradient = function(j, p, i, m) {\n"
            "var Z = new U(\"gradient\");\n"
            "Z.x0_ = j;\n"
            "Z.y0_ = p;\n"
            "Z.x1_ = i;\n"
            "Z.y1_ = m;\n"
            "return Z\n"
        "};\n"
        "q.createRadialGradient = function(p, ag, m, j, Z, i) {\n"
            "var ah = new U(\"gradientradial\");\n"
            "ah.x0_ = p;\n"
            "ah.y0_ = ag;\n"
            "ah.r0_ = m;\n"
            "ah.x1_ = j;\n"
            "ah.y1_ = Z;\n"
            "ah.r1_ = i;\n"
            "return ah\n"
        "};\n"
        "q.drawImage = function(aq, m) {\n"
            "var aj, ah, al, ay, ao, am, at, aA;\n"
            "var ak = aq.runtimeStyle.width;\n"
            "var ap = aq.runtimeStyle.height;\n"
            "aq.runtimeStyle.width = \"auto\";\n"
            "aq.runtimeStyle.height = \"auto\";\n"
            "var ai = aq.width;\n"
            "var aw = aq.height;\n"
            "aq.runtimeStyle.width = ak;\n"
            "aq.runtimeStyle.height = ap;\n"
            "if (arguments.length == 3) {\n"
                "aj = arguments[1];\n"
                "ah = arguments[2];\n"
                "ao = am = 0;\n"
                "at = al = ai;\n"
                "aA = ay = aw\n"
            "} else {\n"
                "if (arguments.length == 5) {\n"
                    "aj = arguments[1];\n"
                    "ah = arguments[2];\n"
                    "al = arguments[3];\n"
                    "ay = arguments[4];\n"
                    "ao = am = 0;\n"
                    "at = ai;\n"
                    "aA = aw\n"
                "} else {\n"
                    "if (arguments.length == 9) {\n"
                        "ao = arguments[1];\n"
                        "am = arguments[2];\n"
                        "at = arguments[3];\n"
                        "aA = arguments[4];\n"
                        "aj = arguments[5];\n"
                        "ah = arguments[6];\n"
                        "al = arguments[7];\n"
                        "ay = arguments[8]\n"
                    "} else {\n"
                        "throw Error(\"Invalid number of arguments\")\n"
                    "}\n"
                "}\n"
            "}\n"
            "var az = V(this, aj, ah);\n"
            "var p = at / 2;\n"
            "var j = aA / 2;\n"
            "var ax = [];\n"
            "var i = 10;\n"
            "var ag = 10;\n"
            "ax.push(\" <g_vml_:group\", ' coordsize=\"', d * i, \",\", d * ag, '\"', ' coordorigin=\"0,0\"', ' style=\"width:', i, \"px;height:\", ag, \"px;position:absolute;\");\n"
            "if (this.m_[0][0] != 1 || this.m_[0][1] || this.m_[1][1] != 1 || this.m_[1][0]) {\n"
                "var Z = [];\n"
                "Z.push(\"M11=\", this.m_[0][0], \",\", \"M12=\", this.m_[1][0], \",\", \"M21=\", this.m_[0][1], \",\", \"M22=\", this.m_[1][1], \",\", \"Dx=\", n(az.x / d), \",\", \"Dy=\", n(az.y / d), \"\");\n"
                "var av = az;\n"
                "var au = V(this, aj + al, ah);\n"
                "var ar = V(this, aj, ah + ay);\n"
                "var an = V(this, aj + al, ah + ay);\n"
                "av.x = ab.max(av.x, au.x, ar.x, an.x);\n"
                "av.y = ab.max(av.y, au.y, ar.y, an.y);\n"
                "ax.push(\"padding:0 \", n(av.x / d), \"px \", n(av.y / d), \"px 0;filter:progid:DXImageTransform.Microsoft.Matrix(\", Z.join(\"\"), \", sizingmethod='clip');\")\n"
            "} else {\n"
                "ax.push(\"top:\", n(az.y / d), \"px;left:\", n(az.x / d), \"px;\")\n"
            "}\n"
            "ax.push(' \">', '<g_vml_:image src=\"', aq.src, '\"', ' style=\"width:', d * al, \"px;\", \" height:\", d * ay, 'px\"', ' cropleft=\"', ao / ai, '\"', ' croptop=\"', am / aw, '\"', ' cropright=\"', (ai - ao - at) / ai, '\"', ' cropbottom=\"', (aw - am - aA) / aw, '\"', \" />\", \"</g_vml_:group>\");\n"
            "this.element_.insertAdjacentHTML(\"BeforeEnd\", ax.join(\"\"))\n"
        "};\n"
        "q.stroke = function(ao) {\n"
            "var Z = 10;\n"
            "var ap = 10;\n"
            "var ag = 5000;\n"
            "var ai = {\n"
                "x: null,\n"
                "y: null\n"
            "};\n"
            "var an = {\n"
                "x: null,\n"
                "y: null\n"
            "};\n"
            "for (var aj = 0; aj < this.currentPath_.length; aj += ag) {\n"
                "var am = [];\n"
                "var ah = false;\n"
                "am.push(\"<g_vml_:shape\", ' filled=\"', !!ao, '\"', ' style=\"position:absolute;width:', Z, \"px;height:\", ap, 'px;\"', ' coordorigin=\"0,0\"', ' coordsize=\"', d * Z, \",\", d * ap, '\"', ' stroked=\"', !ao, '\"', ' path=\"');\n"
                "var aq = false;\n"
                "for (var ak = aj; ak < Math.min(aj + ag, this.currentPath_.length); ak++) {\n"
                    "if (ak % ag == 0 && ak > 0) {\n"
                        "am.push(\" m \", n(this.currentPath_[ak - 1].x), \",\", n(this.currentPath_[ak - 1].y))\n"
                    "}\n"
                    "var m = this.currentPath_[ak];\n"
                    "var al;\n"
                    "switch (m.type) {\n"
                    "case \"moveTo\":\n"
                        "al = m;\n"
                        "am.push(\" m \", n(m.x), \",\", n(m.y));\n"
                        "break;\n"
                    "case \"lineTo\":\n"
                        "am.push(\" l \", n(m.x), \",\", n(m.y));\n"
                        "break;\n"
                    "case \"close\":\n"
                        "am.push(\" x \");\n"
                        "m = null;\n"
                        "break;\n"
                    "case \"bezierCurveTo\":\n"
                        "am.push(\" c \", n(m.cp1x), \",\", n(m.cp1y), \",\", n(m.cp2x), \",\", n(m.cp2y), \",\", n(m.x), \",\", n(m.y));\n"
                        "break;\n"
                    "case \"at\":\n"
                    "case \"wa\":\n"
                        "am.push(\" \", m.type, \" \", n(m.x - this.arcScaleX_ * m.radius), \",\", n(m.y - this.arcScaleY_ * m.radius), \" \", n(m.x + this.arcScaleX_ * m.radius), \",\", n(m.y + this.arcScaleY_ * m.radius), \" \", n(m.xStart), \",\", n(m.yStart), \" \", n(m.xEnd), \",\", n(m.yEnd));\n"
                        "break\n"
                    "}\n"
                    "if (m) {\n"
                        "if (ai.x == null || m.x < ai.x) {\n"
                            "ai.x = m.x\n"
                        "}\n"
                        "if (an.x == null || m.x > an.x) {\n"
                            "an.x = m.x\n"
                        "}\n"
                        "if (ai.y == null || m.y < ai.y) {\n"
                            "ai.y = m.y\n"
                        "}\n"
                        "if (an.y == null || m.y > an.y) {\n"
                            "an.y = m.y\n"
                        "}\n"
                    "}\n"
                "}\n"
                "am.push(' \">');\n"
                "if (!ao) {\n"
                    "w(this, am)\n"
                "} else {\n"
                    "G(this, am, ai, an)\n"
                "}\n"
                "am.push(\"</g_vml_:shape>\");\n"
                "this.element_.insertAdjacentHTML(\"beforeEnd\", am.join(\"\"))\n"
            "}\n"
        "};\n"
        "function w(m, ag) {\n"
            "var j = F(m.strokeStyle);\n"
            "var p = j.color;\n"
            "var Z = j.alpha * m.globalAlpha;\n"
            "var i = m.lineScale_ * m.lineWidth;\n"
            "if (i < 1) {\n"
                "Z *= i\n"
            "}\n"
            "ag.push(\"<g_vml_:stroke\", ' opacity=\"', Z, '\"', ' joinstyle=\"', m.lineJoin, '\"', ' miterlimit=\"', m.miterLimit, '\"', ' endcap=\"', S(m.lineCap), '\"', ' weight=\"', i, 'px\"', ' color=\"', p, '\" />')\n"
        "}\n"
        "function G(aq, ai, aK, ar) {\n"
            "var aj = aq.fillStyle;\n"
            "var aB = aq.arcScaleX_;\n"
            "var aA = aq.arcScaleY_;\n"
            "var j = ar.x - aK.x;\n"
            "var p = ar.y - aK.y;\n"
            "if (aj instanceof U) {\n"
                "var an = 0;\n"
                "var aF = {\n"
                    "x: 0,\n"
                    "y: 0\n"
                "};\n"
                "var ax = 0;\n"
                "var am = 1;\n"
                "if (aj.type_ == \"gradient\") {\n"
                    "var al = aj.x0_ / aB;\n"
                    "var m = aj.y0_ / aA;\n"
                    "var ak = aj.x1_ / aB;\n"
                    "var aM = aj.y1_ / aA;\n"
                    "var aJ = V(aq, al, m);\n"
                    "var aI = V(aq, ak, aM);\n"
                    "var ag = aI.x - aJ.x;\n"
                    "var Z = aI.y - aJ.y;\n"
                    "an = Math.atan2(ag, Z) * 180 / Math.PI;\n"
                    "if (an < 0) {\n"
                        "an += 360\n"
                    "}\n"
                    "if (an < 0.000001) {\n"
                        "an = 0\n"
                    "}\n"
                "} else {\n"
                    "var aJ = V(aq, aj.x0_, aj.y0_);\n"
                    "aF = {\n"
                        "x: (aJ.x - aK.x) / j,\n"
                        "y: (aJ.y - aK.y) / p\n"
                    "};\n"
                    "j /= aB * d;\n"
                    "p /= aA * d;\n"
                    "var aD = ab.max(j, p);\n"
                    "ax = 2 * aj.r0_ / aD;\n"
                    "am = 2 * aj.r1_ / aD - ax\n"
                "}\n"
                "var av = aj.colors_;\n"
                "av.sort(function(aN, i) {\n"
                    "return aN.offset - i.offset\n"
                "});\n"
                "var ap = av.length;\n"
                "var au = av[0].color;\n"
                "var at = av[ap - 1].color;\n"
                "var az = av[0].alpha * aq.globalAlpha;\n"
                "var ay = av[ap - 1].alpha * aq.globalAlpha;\n"
                "var aE = [];\n"
                "for (var aH = 0; aH < ap; aH++) {\n"
                    "var ao = av[aH];\n"
                    "aE.push(ao.offset * am + ax + \" \" + ao.color)\n"
                "}\n"
                "ai.push('<g_vml_:fill type=\"', aj.type_, '\"', ' method=\"none\" focus=\"100%\"', ' color=\"', au, '\"', ' color2=\"', at, '\"', ' colors=\"', aE.join(\",\"), '\"', ' opacity=\"', ay, '\"', ' g_o_:opacity2=\"', az, '\"', ' angle=\"', an, '\"', ' focusposition=\"', aF.x, \",\", aF.y, '\" />')\n"
            "} else {\n"
                "if (aj instanceof T) {\n"
                    "if (j && p) {\n"
                        "var ah = -aK.x;\n"
                        "var aC = -aK.y;\n"
                        "ai.push(\"<g_vml_:fill\", ' position=\"', ah / j * aB * aB, \",\", aC / p * aA * aA, '\"', ' type=\"tile\"', ' src=\"', aj.src_, '\" />')\n"
                    "}\n"
                "} else {\n"
                    "var aL = F(aq.fillStyle);\n"
                    "var aw = aL.color;\n"
                    "var aG = aL.alpha * aq.globalAlpha;\n"
                    "ai.push('<g_vml_:fill color=\"', aw, '\" opacity=\"', aG, '\" />')\n"
                "}\n"
            "}\n"
        "}\n"
        "q.fill = function() {\n"
            "this.stroke(true)\n"
        "};\n"
        "q.closePath = function() {\n"
            "this.currentPath_.push({\n"
                "type: \"close\"\n"
            "})\n"
        "};\n"
        "function V(j, Z, p) {\n"
            "var i = j.m_;\n"
            "return {\n"
                "x: d * (Z * i[0][0] + p * i[1][0] + i[2][0]) - f,\n"
                "y: d * (Z * i[0][1] + p * i[1][1] + i[2][1]) - f\n"
            "}\n"
        "}\n"
        "q.save = function() {\n"
            "var i = {};\n"
            "v(this, i);\n"
            "this.aStack_.push(i);\n"
            "this.mStack_.push(this.m_);\n"
            "this.m_ = J(B(), this.m_)\n"
        "};\n"
        "q.restore = function() {\n"
            "if (this.aStack_.length) {\n"
                "v(this.aStack_.pop(), this);\n"
                "this.m_ = this.mStack_.pop()\n"
            "}\n"
        "};\n"
        "function h(i) {\n"
            "return isFinite(i[0][0]) && isFinite(i[0][1]) && isFinite(i[1][0]) && isFinite(i[1][1]) && isFinite(i[2][0]) && isFinite(i[2][1])\n"
        "}\n"
        "function aa(j, i, p) {\n"
            "if (!h(i)) {\n"
                "return\n"
            "}\n"
            "j.m_ = i;\n"
            "if (p) {\n"
                "var Z = i[0][0] * i[1][1] - i[0][1] * i[1][0];\n"
                "j.lineScale_ = N(H(Z))\n"
            "}\n"
        "}\n"
        "q.translate = function(m, j) {\n"
            "var i = [[1, 0, 0], [0, 1, 0], [m, j, 1]];\n"
            "aa(this, J(i, this.m_), false)\n"
        "};\n"
        "q.rotate = function(j) {\n"
            "var p = A(j);\n"
            "var m = l(j);\n"
            "var i = [[p, m, 0], [ - m, p, 0], [0, 0, 1]];\n"
            "aa(this, J(i, this.m_), false)\n"
        "};\n"
        "q.scale = function(m, j) {\n"
            "this.arcScaleX_ *= m;\n"
            "this.arcScaleY_ *= j;\n"
            "var i = [[m, 0, 0], [0, j, 0], [0, 0, 1]];\n"
            "aa(this, J(i, this.m_), true)\n"
        "};\n"
        "q.transform = function(Z, p, ah, ag, j, i) {\n"
            "var m = [[Z, p, 0], [ah, ag, 0], [j, i, 1]];\n"
            "aa(this, J(m, this.m_), true)\n"
        "};\n"
        "q.setTransform = function(ag, Z, ai, ah, p, j) {\n"
            "var i = [[ag, Z, 0], [ai, ah, 0], [p, j, 1]];\n"
            "aa(this, i, true)\n"
        "};\n"
        "q.drawText_ = function(am, ak, aj, ap, ai) {\n"
            "var ao = this.m_,\n"
            "at = 1000,\n"
            "j = 0,\n"
            "ar = at,\n"
            "ah = {\n"
                "x: 0,\n"
                "y: 0\n"
            "},\n"
            "ag = [];\n"
            "var i = u(E(this.font), this.element_);\n"
            "var p = ac(i);\n"
            "var au = this.element_.currentStyle;\n"
            "var Z = this.textAlign.toLowerCase();\n"
            "switch (Z) {\n"
            "case \"left\":\n"
            "case \"center\":\n"
            "case \"right\":\n"
                "break;\n"
            "case \"end\":\n"
                "Z = au.direction == \"ltr\" ? \"right\": \"left\";\n"
                "break;\n"
            "case \"start\":\n"
                "Z = au.direction == \"rtl\" ? \"right\": \"left\";\n"
                "break;\n"
            "default:\n"
                "Z = \"left\"\n"
            "}\n"
            "switch (this.textBaseline) {\n"
            "case \"hanging\":\n"
            "case \"top\":\n"
                "ah.y = i.size / 1.75;\n"
                "break;\n"
            "case \"middle\":\n"
                "break;\n"
            "default:\n"
            "case null:\n"
            "case \"alphabetic\":\n"
            "case \"ideographic\":\n"
            "case \"bottom\":\n"
                "ah.y = -i.size / 2.25;\n"
                "break\n"
            "}\n"
            "switch (Z) {\n"
            "case \"right\":\n"
                "j = at;\n"
                "ar = 0.05;\n"
                "break;\n"
            "case \"center\":\n"
                "j = ar = at / 2;\n"
                "break\n"
            "}\n"
            "var aq = V(this, ak + ah.x, aj + ah.y);\n"
            "ag.push('<g_vml_:line from=\"', -j, ' 0\" to=\"', ar, ' 0.05\" ', ' coordsize=\"100 100\" coordorigin=\"0 0\"', ' filled=\"', !ai, '\" stroked=\"', !!ai, '\" style=\"position:absolute;width:1px;height:1px;\">');\n"
            "if (ai) {\n"
                "w(this, ag)\n"
            "} else {\n"
                "G(this, ag, {\n"
                    "x: -j,\n"
                    "y: 0\n"
                "},\n"
                "{\n"
                    "x: ar,\n"
                    "y: i.size\n"
                "})\n"
            "}\n"
            "var an = ao[0][0].toFixed(3) + \",\" + ao[1][0].toFixed(3) + \",\" + ao[0][1].toFixed(3) + \",\" + ao[1][1].toFixed(3) + \",0,0\";\n"
            "var al = n(aq.x / d) + \",\" + n(aq.y / d);\n"
            "ag.push('<g_vml_:skew on=\"t\" matrix=\"', an, '\" ', ' offset=\"', al, '\" origin=\"', j, ' 0\" />', '<g_vml_:path textpathok=\"true\" />', '<g_vml_:textpath on=\"true\" string=\"', af(am), '\" style=\"v-text-align:', Z, \";font:\", af(p), '\" /></g_vml_:line>');\n"
            "this.element_.insertAdjacentHTML(\"beforeEnd\", ag.join(\"\"))\n"
        "};\n"
        "q.fillText = function(m, i, p, j) {\n"
            "this.drawText_(m, i, p, j, false)\n"
        "};\n"
        "q.strokeText = function(m, i, p, j) {\n"
            "this.drawText_(m, i, p, j, true)\n"
        "};\n"
        "q.measureText = function(m) {\n"
            "if (!this.textMeasureEl_) {\n"
                "var i = '<span style=\"position:absolute;top:-20000px;left:0;padding:0;margin:0;border:none;white-space:pre;\"></span>';\n"
                "this.element_.insertAdjacentHTML(\"beforeEnd\", i);\n"
                "this.textMeasureEl_ = this.element_.lastChild\n"
            "}\n"
            "var j = this.element_.ownerDocument;\n"
            "this.textMeasureEl_.innerHTML = \"\";\n"
            "this.textMeasureEl_.style.font = this.font;\n"
            "this.textMeasureEl_.appendChild(j.createTextNode(m));\n"
            "return {\n"
                "width: this.textMeasureEl_.offsetWidth\n"
            "}\n"
        "};\n"
        "q.clip = function() {};\n"
        "q.arcTo = function() {};\n"
        "q.createPattern = function(j, i) {\n"
            "return new T(j, i)\n"
        "};\n"
        "function U(i) {\n"
            "this.type_ = i;\n"
            "this.x0_ = 0;\n"
            "this.y0_ = 0;\n"
            "this.r0_ = 0;\n"
            "this.x1_ = 0;\n"
            "this.y1_ = 0;\n"
            "this.r1_ = 0;\n"
            "this.colors_ = []\n"
        "}\n"
        "U.prototype.addColorStop = function(j, i) {\n"
            "i = F(i);\n"
            "this.colors_.push({\n"
                "offset: j,\n"
                "color: i.color,\n"
                "alpha: i.alpha\n"
            "})\n"
        "};\n"
        "function T(j, i) {\n"
            "Q(j);\n"
            "switch (i) {\n"
            "case \"repeat\":\n"
            "case null:\n"
            "case \"\":\n"
                "this.repetition_ = \"repeat\";\n"
                "break;\n"
            "case \"repeat-x\":\n"
            "case \"repeat-y\":\n"
            "case \"no-repeat\":\n"
                "this.repetition_ = i;\n"
                "break;\n"
            "default:\n"
                "O(\"SYNTAX_ERR\")\n"
            "}\n"
            "this.src_ = j.src;\n"
            "this.width_ = j.width;\n"
            "this.height_ = j.height\n"
        "}\n"
        "function O(i) {\n"
            "throw new P(i)\n"
        "}\n"
        "function Q(i) {\n"
            "if (!i || i.nodeType != 1 || i.tagName != \"IMG\") {\n"
                "O(\"TYPE_MISMATCH_ERR\")\n"
            "}\n"
            "if (i.readyState != \"complete\") {\n"
                "O(\"INVALID_STATE_ERR\")\n"
            "}\n"
        "}\n"
        "function P(i) {\n"
            "this.code = this[i];\n"
            "this.message = i + \": DOM Exception \" + this.code\n"
        "}\n"
        "var X = P.prototype = new Error;\n"
        "X.INDEX_SIZE_ERR = 1;\n"
        "X.DOMSTRING_SIZE_ERR = 2;\n"
        "X.HIERARCHY_REQUEST_ERR = 3;\n"
        "X.WRONG_DOCUMENT_ERR = 4;\n"
        "X.INVALID_CHARACTER_ERR = 5;\n"
        "X.NO_DATA_ALLOWED_ERR = 6;\n"
        "X.NO_MODIFICATION_ALLOWED_ERR = 7;\n"
        "X.NOT_FOUND_ERR = 8;\n"
        "X.NOT_SUPPORTED_ERR = 9;\n"
        "X.INUSE_ATTRIBUTE_ERR = 10;\n"
        "X.INVALID_STATE_ERR = 11;\n"
        "X.SYNTAX_ERR = 12;\n"
        "X.INVALID_MODIFICATION_ERR = 13;\n"
        "X.NAMESPACE_ERR = 14;\n"
        "X.INVALID_ACCESS_ERR = 15;\n"
        "X.VALIDATION_ERR = 16;\n"
        "X.TYPE_MISMATCH_ERR = 17;\n"
        "G_vmlCanvasManager = e;\n"
        "CanvasRenderingContext2D = D;\n"
        "CanvasGradient = U;\n"
        "CanvasPattern = T;\n"
        "DOMException = P\n"
    "})()\n"
"};\n"
};
#else
static const char j_006[]={0};
#endif
#endif
